admin/package-lock.json, admin/package.json, admin/resources/js/app.tsx, admin/resources/js/authProvider.ts, admin/resources/js/components/AdminPage.tsx, admin/resources/js/components/Dashboard.tsx, admin/resources/js/components/MyUrlField.tsx, admin/resources/js/components/Posts.tsx, admin/resources/js/components/Users.tsx, admin/resources/js/dataProvider.ts
- Copies over the main files started in the test-admin folder in the sandbox.
=> Copy react-admin files from GCTC-NTGC/cms-talent-sandbox/test-admin

admin/resources/js/components/CreateUser.tsx, admin/resources/js/components/form/Form.tsx, admin/resources/js/components/form/Input.tsx, admin/resources/js/components/form/Select.tsx
The performance benefit must be minimal, but I did observe fewer component updates with React dev tools, and this seems to be the library's recommended approach.
=> Create alternate "uncontrolled" input components

admin/resources/js/api/generated.ts, admin/resources/js/api/userOperations.graphql
- Adds `UpdateUser` mutation to user operations file.
- Creates new update user types in generated file using the codegen script.
=> Task - UpdateUser mutation

admin/resources/js/api/classificationOperations.graphql, admin/resources/js/api/generated.ts, admin/resources/js/components/ClassificationsTable.tsx, admin/resources/js/fakeData/fakeClassifications.ts, admin/resources/js/stories/ClassificationTable.stories.tsx
=> creating table and story for classifications table

admin/package-lock.json, admin/resources/js/api/generated.ts, admin/resources/js/api/userOperations.graphql, admin/resources/js/components/CreateUser.tsx, admin/resources/js/components/form/Submit.tsx, admin/resources/js/stories/Users.stories.tsx
=> Implement client-side graphQL query for Create User

admin/resources/js/components/Table.tsx
=> Bug - Fix GlobalFilter nesting in Table component

admin/resources/js/components/CmoAssetTable.tsx, admin/resources/js/components/OperationalRequirementTable.tsx, admin/resources/js/components/PoolDashboard.tsx, admin/resources/js/components/UserTable.tsx, admin/resources/js/components/cmoAssets/CreateCmoAsset.tsx, admin/resources/js/components/cmoAssets/UpdateCmoAsset.tsx, admin/resources/js/components/operationalRequirements/CreateOperationalRequirement.tsx, admin/resources/js/components/operationalRequirements/UpdateOperationalRequirement.tsx, admin/resources/js/stories/CmoAsset.stories.tsx, admin/resources/js/stories/OperationalRequirement.stories.tsx, api/src/types.d.ts
Also added links to the Edit pages in OperationalRequirement and CmoAsset tables.
=> Add OperationalReq and CmoAsset pages to PoolDashboard

admin/.storybook/main.js, admin/.storybook/preview.js, admin/package-lock.json, admin/package.json, admin/resources/js/components/IntlContainer.tsx, admin/resources/js/components/PoolDashboard.tsx
This does the bare minimum of react-intl setup so that we can start using formattedMessage.
=> Install react-intl and put IntlProvider at dashboard and storybook roots

admin/resources/js/components/H2Components/Fieldset.tsx, admin/resources/js/components/H2Components/InputContext.tsx, admin/resources/js/components/H2Components/InputError.tsx, admin/resources/js/components/H2Components/InputLabel.tsx, admin/resources/js/components/H2Components/InputWrapper.tsx, admin/resources/js/components/form/Checkbox.tsx, admin/resources/js/components/form/Checklist.tsx, admin/resources/js/components/form/Input.tsx, admin/resources/js/components/form/TextArea.tsx, admin/resources/js/stories/Input.stories.tsx, admin/resources/js/stories/TextArea.stories.tsx
- Adds new `InputWrapper` component to the old Input and `TextArea` components.
- Creates new story for `TextArea` component (let me know if we should add more variations).
- Refactors styling on `InputWrapper` and subcomponents.
=> Task - Styling Input and Textarea

admin/resources/js/components/H2Components/Button.tsx, admin/resources/js/components/PoolDashboard.tsx, admin/resources/js/components/dashboard/Dashboard.tsx, admin/resources/js/components/menu/SideMenu.tsx, admin/resources/js/stories/Button.stories.tsx, admin/resources/js/stories/PoolDashboard.stories.tsx
Resolves #135.
Also adds an optional `block` prop to the Button component to allow for full width buttons.
=> Feature - Style Dashboard menu

admin/resources/js/components/H2Components/Fieldset.tsx, admin/resources/js/components/form/Checkbox.tsx, admin/resources/js/components/form/Checklist.tsx, admin/resources/js/components/form/Radio.tsx, admin/resources/js/components/form/RadioGroup.tsx, admin/resources/js/stories/H2Components/Alert.stories.tsx, admin/resources/js/stories/H2Components/Button.stories.tsx, admin/resources/js/stories/H2Components/Fieldset.stories.tsx, admin/resources/js/stories/H2Components/InputContext.stories.tsx, admin/resources/js/stories/H2Components/InputError.stories.tsx, admin/resources/js/stories/H2Components/InputLabel.stories.tsx, admin/resources/js/stories/H2Components/InputWrapper.stories.tsx, admin/resources/js/stories/form/Checkbox.stories.tsx, admin/resources/js/stories/form/Checklist.stories.tsx, admin/resources/js/stories/form/Input.stories.tsx, admin/resources/js/stories/form/Radio.stories.tsx, admin/resources/js/stories/form/RadioGroup.stories.tsx, admin/resources/js/stories/form/TextArea.stories.tsx
- Adds Radio and RadioGroup components.
- Includes stories for both components.
- Moves stories into correct folder structure.
=> Task - Radio and RadioGroup components

admin/resources/js/components/ClientProvider.tsx, admin/webpack.mix.js
=> Admin - API_URI not recognized by ClientProvider

admin/resources/js/components/H2Components/Alert.tsx, admin/resources/js/components/H2Components/Button.tsx, admin/resources/js/components/H2Components/Fieldset.tsx, admin/resources/js/components/H2Components/InputLabel.tsx, admin/resources/js/components/dashboard/Dashboard.tsx
=> Comply with new version of H2 frontend parsing

admin/resources/js/components/PoolDashboard.tsx, admin/resources/js/components/poolCandidate/PoolCandidatesTable.tsx, admin/resources/js/stories/PoolCandidate.stories.tsx
=> Add ability to edit Pool Candidates

admin/resources/js/components/pool/PoolTable.tsx
=> Add name and description to PoolTable

admin/resources/js/components/form/Select.tsx, admin/resources/js/components/pool/CreatePool.tsx, admin/resources/js/components/pool/UpdatePool.tsx, admin/resources/js/components/pool/messages.ts
Resolves #353.
- Adds i18n for `pool.form.ownerPlaceholder` used in the Create Pool and Update Pool forms.
=> Bug - Select component

admin/resources/js/components/Table.tsx
=> Bug - Update Table column to use name instead of ID

api/app/Models/User.php, api/app/Providers/AuthServiceProvider.php, api/bootstrap/app.php, api/graphql/schema.graphql
Resolves #323
Returns the logged in user, if request has a valid Bearer token, or null, if no token exists or doesn't match a user in database. Returns a 401 error if a bearer token exists but isn't valid, and logs the reasons for failure.
It occurs to me that this is a prime candidate for automated tests, to test that valid tokens work and all the expected failure modes of tokens don't work, but as that is substantially more work I'll make a separate issue for that.
=> Create api endpoint which returns logged in user, or null.

api/app/Models/Department.php, api/database/migrations/2021_09_13_180950_create_departments_table.php, api/database/seeders/DatabaseSeeder.php, api/database/seeders/DepartmentSeeder.php, api/graphql/schema.graphql
- Generated a migration that creates department table (id, department_name, and name).
- Generated an eloquent model class.
- Seeded some data copied from [department csv](http://donnees-data.tpsgc-pwgsc.gc.ca/ba1/min-dept/min-dept.csv).
- Added new Department type to the schema and the basic crud query and mutations.
=> API - Create department model

admin/resources/js/components/PoolDashboard.tsx, admin/resources/js/components/department/CreateDepartment.tsx, admin/resources/js/components/department/UpdateDepartment.tsx, admin/resources/js/components/department/messages.ts, admin/resources/js/stories/Department.stories.tsx
- Adds create and update forms for department
=> Dashboard - Department create update forms

admin/resources/js/components/Table.tsx
=> Fix Table Component Toggle All

api/database/migrations/2021_05_05_163948_create_users_table.php, api/database/migrations/2021_05_26_195131_create_pools_table.php, api/database/migrations/2021_05_27_182801_create_classifications_table.php, api/database/migrations/2021_05_27_182844_create_operational_requirements_table.php, api/database/migrations/2021_05_28_200606_create_pool_lookup_pivot_tables.php, api/database/migrations/2021_06_01_140524_create_pool_candidates_table.php, api/database/migrations/2021_09_13_180950_create_departments_table.php
Resolves #502.
- Namespaces `DB` in migrations
=> API - Change id reference column types from string to uuid

.github/dependabot.yml
=> Feature - Add Dependabot checks for new directories

common/package-lock.json, common/package.json
Why this works locally but not in Azure is, as usual, unknown.
=> Add graphql as dependency in common project

admin/webpack.mix.js
=> Admin - Add missing env keys to webpack mix

admin/resources/js/api/generated.ts, api/app/GraphQL/Operators/PostgreSQLOperator.php, api/app/Models/PoolCandidate.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, common/src/api/generated.ts, talentsearch/resources/js/api/generated.ts
=> Rewrite countPoolCandidates api query with custom methods

.github/dependabot.yml
=> Update dependabot update interval from daily to weekly

admin/resources/views/dashboard.blade.php, talentsearch/resources/views/page_container.blade.php
Resolves #1045. 
Also fixes same issue for /talentsearch.
=> Fix apple-touch-icon path for admin, talentsearch

.github/dependabot.yml
Increase Dependebot open PR limit to 15
solves issue #1126
=> increase Dependebot open PR limit to 15

api/database/migrations/2021_11_09_145430_add_constraints.php
A new database migration created to generate the missing unique and foreign key constraints.  Also fixes column type for pool_candidate_search_requests.department_id.
Solves #927
=> Database Migration - unique and foreign key constraints

api/database/seeders/DepartmentSeeder.php
Resolves #486.
Adds full list of 104 departments from downloaded [csv](http://donnees-data.tpsgc-pwgsc.gc.ca/ba1/min-dept/min-dept.csv).
A brittle [gist](https://gist.github.com/mnigh/6278fcdaad210c398ccb7e9c935f8621) (php) for doing this in the future (provided the format does not change).
=> Update Department seeder

api/app/GraphQL/Directives/CopyFieldDirective.php, api/app/GraphQL/Directives/PopulateSubDirective.php, api/graphql/schema.graphql
A new directive added to populate the sub field directly, not as part of the graphql mutation.  I couldn't find a built-in directive to do this so I created a new one based on the inject directive.
Closes #926
=> New Directive to populate sub field

talentsearch/resources/js/components/search/EstimatedCandidates.tsx
=> Talent Search - Add EstimatedCandidates wrapper background color

admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx
=> Admin - Fix UpdatePoolCandidate form checkboxes

admin/resources/js/components/searchRequest/UpdateSearchRequest.tsx, talentsearch/resources/js/components/request/CreateRequest.tsx
=> Bugfix - Check if location.state is null

.vscode/tasks.json, maintenance/scripts/refresh_api.sh, maintenance/scripts/refresh_talentsearch.sh
The scripts had some unnecessary steps that were removed to speed them up slightly and remove nuisance errors.
The scripts were a bit cumbersome to run.  I added a vscode tasks file to make them more convenient.  Press Ctrl+Shift+B to pull up the build task list.
Closes #1263
=> Maintenance - Tidy scripts and add tasks file

common/src/helpers/router.tsx, talentsearch/resources/js/components/PageContainer.tsx
Resolves #1200.
- Adds ScrollToTop component to **common**
- Adds ScrollToTop component to **talentsearch**
=> Add ScrollToTop component

api/database/seeders/ProdSeeder.php, infrastructure/deploy.sh
=> API - Add ProdSeeder

admin/resources/js/components/poolCandidate/PoolCandidatesTable.tsx, common/README.md
Resolves #1275.
- Fixes typos for translation utility script directions in `common/README.md`
=> Admin - Update Pool Candidate Table headers

admin/resources/js/components/classification/CreateClassification.tsx, admin/resources/js/components/classification/UpdateClassification.tsx, admin/resources/js/components/cmoAsset/CreateCmoAsset.tsx, admin/resources/js/components/cmoAsset/UpdateCmoAsset.tsx, admin/resources/js/components/department/CreateDepartment.tsx, admin/resources/js/components/department/UpdateDepartment.tsx, admin/resources/js/components/operationalRequirement/CreateOperationalRequirement.tsx, admin/resources/js/components/operationalRequirement/UpdateOperationalRequirement.tsx, admin/resources/js/components/pool/CreatePool.tsx, admin/resources/js/components/pool/UpdatePool.tsx, admin/resources/js/components/poolCandidate/CreatePoolCandidate.tsx, admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx, admin/resources/js/components/user/CreateUser.tsx, admin/resources/js/components/user/UpdateUser.tsx
=> Admin - Remove appended colon from input label value

common/hydrogen.config.json
Resolves #1360.
All [credit](https://github.com/GCTC-NTGC/gc-digital-talent/issues/1360#issuecomment-988075613) to @yonikid15.
=> Common - Add missing radius for hydrogen config

admin/resources/css/app.css, common/src/css/common.css
Resolves #1280.
- Adds css class `.input-label-context-button` into common/resources/css/common.css
- Removes css class `.input-label-context-button` from admin/resources/css/app.css
=> Common - Consolidate input label context button css

talentsearch/resources/js/components/search/SearchForm.tsx
=> Change Aboriginal to Indigenous

.vscode/hydrogen.code-snippets
=> Update Hydrogen code snippets for VS Code

admin/.storybook/main.js, admin/package.json, talentsearch/.storybook/main.js, talentsearch/package.json
=> Storybook - Replace deprecated Storybook --static-dir CLI flag

admin/resources/js/components/cmoAsset/CreateCmoAsset.tsx, admin/resources/js/components/cmoAsset/UpdateCmoAsset.tsx
=> Admin - Update CMO Asset forms input labels

talentsearch/resources/js/components/PageContainer.tsx
=> Talent Search - Fix incorrect Hydrogen attribute

admin/resources/js/components/poolCandidate/CreatePoolCandidate.tsx
=> Bugfix - Remove duplicate select user field in create pool candidate form

.vscode/extensions.json, .vscode/project-words.txt, .vscode/settings.json, admin/resources/js/components/AuthContainer.tsx, api/app/Models/User.php
- Add a VS Code extensions recommendation file with [CSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) (and eslint and prettier)
- Add a custom dictionary for CSpell with some project-specific words
- Fix a few small typos found
=> Add spellchecking tooling

talentsearch/resources/js/components/request/CreateRequest.tsx, talentsearch/resources/js/components/request/RequestPage.tsx, talentsearch/resources/js/components/search/SearchForm.tsx
=> Bugfix - Fix unknown object type in search and request pages

api/app/Providers/AuthServiceProvider.php
Restores the ability to respond to API request without a token, like the previous behaviour.
Closes #1517
=> fix auth processing

infrastructure/php-container/src/.htaccess
Restores the routing for the phpinfo.php route
Closes #1531
=> Fix PHP Info routing

talentsearch/resources/js/stories/RequestForm.stories.tsx
=> Fix RequestForm story

api/composer.json, common/src/components/form/RadioGroup/RadioGroup.tsx, talentsearch/resources/js/components/search/SearchForm.tsx
Adjusted RadioGroup to allow default selections and changed education requirement filter to default to no education as per #1474.
=> Made default selection for education requirement.

admin/app/Http/Controllers/AuthController.php
=> Request that authentication service requires mfa

talentsearch/tsconfig.json, talentsearch/webpack.mix.js
=> Bugfix - talent search module resolution

talentsearch/resources/js/components/request/CreateRequest.tsx
=> Bugfix - Set use useForm type in CreateRequest component

talentsearch/resources/js/components/search/SearchContainer.tsx
=> Bugfix - Set 'Get in touch' link to a mailto with pool owners email

admin/resources/js/stories/PoolCandidate.stories.tsx
=> More stabilize storybook fake data

infrastructure/maintenance-container/Dockerfile, maintenance/scripts/lib/common.sh, maintenance/scripts/refresh_admin.sh, maintenance/scripts/refresh_all.sh, maintenance/scripts/refresh_api.sh, maintenance/scripts/refresh_auth.sh, maintenance/scripts/refresh_common.sh, maintenance/scripts/refresh_talentsearch.sh, maintenance/scripts/setup.sh, maintenance/scripts/update_admin_env.sh, maintenance/scripts/update_api_env.sh, maintenance/scripts/update_auth_env.sh, maintenance/scripts/update_env_appkey.sh
Resolves https://github.com/GCTC-NTGC/gc-digital-talent/issues/1782
This PR:
- fixes the php-curl missing from docker that was preventing `composer install`, 05594cc53cd40fe98add35f50369123ceee012b7
- adds error-handling to scripts, raising errors, pipefails, and undeclared vars 27cdc7f078b25e6e6ee6ef9e2dd0e610ba18d758
- makes some fixes to scripts that were detected 
- makes scripts more flexible (run in docker or host machine) 373eeef79bc272784c313b4427d15befd524ac6b
- cross-platform random string generation, now osx+linux (prev way was also generating pipefail) 2922bc5830b51d456b3e749175efc0df0556f03a 2bfe9ae83b611f9d64a7f44821b199140cb856f6
=> Fix docker env and improve scripts

auth/tailwind.config.js
Fixes the tailwind purge warning as per https://github.com/tailwindlabs/tailwindcss/discussions/6019
Closes #1766
=> Fix tailwind warning

.github/dependabot.yml, .github/workflows/bundlewatch.yml, .github/workflows/storybook.yml
Noticed in the dependabot PRs that I wasn't seeing the bundlesize changes with each pkg upgrade, and realized some paths still weren't updated 🤦🏻‍♂️
=> Fix paths to ensure workflows run

api/graphql/schema.graphql
=> deleteDepartment api call must return correct type

api/storage/app/lighthouse-schema.graphql
I forgot to update the compiled graphql schema in #1845, here it is.
=> Update compiled graphql schema

api/database/factories/SkillFamilyFactory.php
=> Fix SkillFamily seeder description

frontend/admin/package.json, frontend/common/package.json, frontend/package-lock.json, frontend/talentsearch/package.json, maintenance/scripts/setup.sh
Thanks to @JoshBeveridge and @patcon the issues identified with hydrogen in a workspace environment have been solved.
- https://github.com/hydrogen-design-system/hydrogen.css/issues/72
- https://github.com/hydrogen-design-system/hydrogen.css/issues/73
This branch upgrades to hydrogen 1.1.17 and removes the workarounds that are no longer needed.
=> Upgrade hydrogen and remove workarounds

frontend/talentsearch/jest.config.js
=> Bugfix - Remove duplicate moduleNameMappers in jest config

infrastructure/deploy.sh
The deploy file checked into the repo isn't yet used directly, its contents are copied into server configuration.
Related to #1841
=> Update server build scripts

frontend/talentsearch/resources/js/components/search/SearchForm.tsx, frontend/talentsearch/resources/js/components/search/SearchHeading.tsx, frontend/talentsearch/resources/js/lang/fr.json
This branch updates some copy (and translations) in the talentsearch search page.
Closes #1905 
Closes #1906 
Closes #1907
=> TalentSearch - Search - Copy updates and translations

frontend/admin/app/Http/Controllers/AuthController.php, frontend/admin/resources/js/components/dashboard/Dashboard.tsx
This branch updates the login button to request the correct locale for login.  It also updates the login endpoint to request the locale from the open ID provider.
Closes #1983
=> Request Login Locale

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, frontend/common/src/constants/localizedConstants.tsx, frontend/common/src/messages/errorMessages.ts, frontend/talentsearch/resources/js/components/educationExperienceForm/EducationExperienceForm.stories.tsx, frontend/talentsearch/resources/js/components/educationExperienceForm/EducationExperienceForm.tsx, frontend/talentsearch/resources/js/components/workExperienceForm/WorkExperienceForm.tsx
Resolves #1793 
Mostly recycling code from the last form component so it was quick. Also did the enums thing here. 
The dropdown for wireframes
https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2
need some changes so @Jerryescandon please update when you can
=> Add Education Experience Form

frontend/talentsearch/resources/js/components/personalExperienceForm/PersonalExperienceForm.stories.tsx, frontend/talentsearch/resources/js/components/personalExperienceForm/PersonalExperienceForm.tsx
for #1790 
it was pretty quick, pretty much recycled from the last few forms, might as well check it off
wireframe here
https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2
=> 1790 - personal experiences form

frontend/talentsearch/resources/js/components/communityExperienceForm/CommunityExperienceForm.stories.tsx, frontend/talentsearch/resources/js/components/communityExperienceForm/CommunityExperienceForm.tsx
=> Community Experience Details form component 

api/database/factories/CmoAssetFactory.php, api/database/factories/OperationalRequirementFactory.php, api/database/factories/PoolFactory.php
This branch adds a unique constraint to the key fields in the model factories for the fields that are missing it.
Closes #2121
=> Fix unique key collisions

api/database/seeders/UserSeederLocal.php, frontend/admin/app/Http/Controllers/AuthController.php, frontend/admin/resources/js/components/AuthContainer.tsx, frontend/admin/resources/js/components/ClientProvider.test.tsx, frontend/admin/resources/js/components/ClientProvider.tsx
To tackle #2086 must do this first
resolves #2133
=> capture ID_Token data

api/database/seeders/UserSeederLocal.php, frontend/admin/app/Http/Controllers/AuthController.php, frontend/admin/composer.json, frontend/admin/composer.lock
resolves #2086 
trying out what the plan is for id_token -> extract and compare
=> add nonce checking for auth

frontend/common/src/components/form/Checkbox/Checkbox.stories.tsx, frontend/common/src/components/form/Checkbox/Checkbox.tsx, frontend/common/src/components/form/Checklist/Checklist.tsx, frontend/common/src/components/form/Radio/Radio.tsx, frontend/common/src/components/form/RadioGroup/RadioGroup.tsx, frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
Resolves #2136 
- Adds new checkbox variation with a bounding box. 
- Question: Should I move the bounding box component into it's own file? Or are we okay with using a boolean prop (boundingBox) to trigger using the other component?
=> Checkbox with bounding box

frontend/common/src/components/Breadcrumbs/Breadcrumbs.stories.tsx, frontend/common/src/components/Breadcrumbs/Breadcrumbs.tsx, frontend/common/src/helpers/util.ts
resolves #1931 
I think there is some hashing out of what this component should look like, do, or how it should do things so I'll mark as draft.
For the time being, it takes an array of objects that are links+link names and renders a component that is a link collection.
=> breadcrumbs component for 1931

.github/workflows/storybook.yml, frontend/admin/.storybook/preview.js, frontend/admin/resources/js/components/IntlContainer.tsx, frontend/admin/resources/js/dashboard.tsx, frontend/admin/tsconfig.json, frontend/common/src/components/form/Submit/Submit.tsx, frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx, frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx, frontend/common/src/lang/fr.json, frontend/common/src/lang/index.ts, frontend/common/src/messages/commonMessages.ts, frontend/talentsearch/.storybook/preview.js, frontend/talentsearch/resources/js/components/IntlContainer.tsx, frontend/talentsearch/tsconfig.json
Closes #2181 
- I'm changed the estimate to a 1 since it didn't take long
- I haven't done translations in a while and the directions in the README helped perfectly 🎉 
- I found the translations to the messages in the TalentCloud repo, so no need to send to translations.
=> Localize messages in Form components

documentation/dependabot.md
Based on #2152 I've tried to codify a guide to merging Dependabot PRs.  These are just my opinions 😁 so feel free to chime in.
I also created a `documentation` top level folder so feel free to comment on that too.
=> Dependabot documentation

frontend/common/src/hooks/useLocalStorage.ts, frontend/talentsearch/resources/js/components/request/CreateRequest.tsx
This spike is a proposed solution to the "how do we keep our users from accidentally losing their form data" problem.
The implementation is to subscribe to form changes using the [React Hook Forms watch API](https://react-hook-form.com/api/useform/watch) and save the form values locally on every change.  The save implementation is the [useLocalStorage function from the usehooks site](https://usehooks.com/useLocalStorage/). 
The proof of concept for this spike is implemented on the Create Request form.
Do we need a "Don't navigate away!" alert?
Do we need a "Your data is being saved locally" message?
Closes #1797
=> Don't lose form data

frontend/admin/.storybook/main.js, frontend/common/.storybook/main.js, frontend/common/src/components/Footer/Footer.stories.tsx, frontend/common/src/components/Header/Header.stories.tsx, frontend/talentsearch/.storybook/main.js, frontend/talentsearch/resources/js/talentSearchConstants.ts
This branch updates the storybook configuration to properly load static assets both locally and in Chromatic.
Check:
- Pool Dashboard
- Footer
- Header
- ProfileFormWrapper
Closes #1455
=> Update Storybook loading of static assets

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, frontend/admin/resources/js/api/userOperations.graphql, frontend/admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx, frontend/admin/resources/js/components/user/UpdateUser.tsx, frontend/admin/resources/js/stories/User.stories.tsx
resolves #1935 
draft, edits to follow
experimenting
=> Feature update/create User new fields

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql
Removes sub field from UpdateUserAsUser mutation.
=> User shouldn't be able to mutate own sub field

frontend/admin/resources/js/components/user/UpdateUser.tsx
This branch restores the field pick logic for the user edit form.
Closes #2321
=> Restore field pick for user form

frontend/common/src/fakeData/fakeExperiences.ts, frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.test.tsx, frontend/talentsearch/src/js/components/skills/SkillAccordion/SkillAccordion.tsx
=> Fix failing tests on admin

frontend/common/src/components/form/Submit/Submit.tsx, frontend/talentsearch/src/js/components/applicantProfile/CancelButton.tsx, frontend/talentsearch/src/js/components/applicantProfile/ProfileFormFooter.tsx, frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.stories.tsx, frontend/talentsearch/src/js/components/applicantProfile/SaveButton.tsx
resolves #2405 
Hitting submit in storybook for this component freezes things, it doesn't need to actually do anything here so I shuffled the form around a bit
no longer freezes, form looks and functions the same
=> fix storybook freezing on profilewrapper

frontend/common/src/components/form/MultiSelect/MultiSelect.stories.tsx, frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
Resolves #2409 
- Also creates a story for MultiSelect which hasn't been added yet.
=> Bugfix - Multiselect width

frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx, frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx, frontend/admin/src/js/lang/fr.json, frontend/admin/src/js/lang/whitelist.json
Resolves #2482 
Please change the copy for the "CMO identifier" label to "Process Number".
French: 
"Identifiant du BGC"  -> "Numéro de processus"
=> Copy change for Create/Update Pool Candidate page #2482

frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx, frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx, frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx
resolves #2498 
Most of the changes were automatic from formatting. 
The actual changes were a few things, the wrong variables were being passed into the pathing. _UserID_ was used not _poolCandidateID_.  It will be important to be wary of the multiple types of ID in use, in this case UserID =/= PoolCandidateID
See changes of relevance at
https://github.com/GCTC-NTGC/gc-digital-talent/compare/feature/2498-candidate-ID-bug?expand=1#diff-7b5fab6aa374ee8dae4c812f085e7937655958ecdb01fa7b6edaacd5c002c1daR23-R34
https://github.com/GCTC-NTGC/gc-digital-talent/compare/feature/2498-candidate-ID-bug?expand=1#diff-7b5fab6aa374ee8dae4c812f085e7937655958ecdb01fa7b6edaacd5c002c1daL46-R47
https://github.com/GCTC-NTGC/gc-digital-talent/compare/feature/2498-candidate-ID-bug?expand=1#diff-7b5fab6aa374ee8dae …
=> Fix bug with candidate ID in requests component directory 

frontend/admin/src/js/components/menu/SideMenu.tsx, frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx, frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx, frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx, frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx, frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx, frontend/admin/src/js/components/skillFamily/SkillFamilyTable.tsx, frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx, frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx, frontend/talentsearch/src/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.tsx, frontend/talentsearch/src/js/components/skills/AddedSkills/AddedSkills.tsx
resolves #2496 
ran npm linting thing, fixed prettier errors that popped up
a bit of weirdness, a few things popped up for prettier in /indigenousapprenticeship, but upon opening the relevant file there were no prettier highlights
=> linting in frontend - prettier

api/app/Models/User.php, api/database/factories/UserFactory.php, api/database/helpers/ApiEnums.php, api/database/migrations/2022_04_27_190153_update_users_table_with_gov_employee_type.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, frontend/common/src/fakeData/fakeUsers.ts, frontend/talentsearch/src/js/api/userOperations.graphql, frontend/talentsearch/src/js/components/GovernmentInfoForm/GovInfoFormOperations.graphql, frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.stories.tsx, frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx, frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
Resolves #2329 
- Added govEmployeeType to User in backend
- Updated GovernmentInfoForm to retrieve and update the new field
- Updated ProfilePage to display text for users current position type
=> 2329 add missing field to user

frontend/talentsearch/src/js/components/communityExperienceForm/CommunityExperienceForm.tsx, frontend/talentsearch/src/js/components/educationExperienceForm/EducationExperienceForm.tsx, frontend/talentsearch/src/js/components/personalExperienceForm/PersonalExperienceForm.tsx, frontend/talentsearch/src/js/components/workExperienceForm/WorkExperienceForm.tsx
resolves #2453 
Added bounded boxes as well as clean up dangling statements that were added to compensate for the lack of the bounded box
=> experience forms touch-ups

auth/package-lock.json, frontend/package-lock.json
It seems like something in the dependabot updates for today scrambled the lock files.  I've rebuilt them.  h/t @esizer for finding the dropped dependency.
Closes #2618
=> Rebuild lock files

frontend/talentsearch/src/js/applicantProfileRoutes.ts, frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.tsx, frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
Resolve #1994 
Ensure each profile form page has routing (can be reached via a url) and that the links on the main Profile page work properly.
Set up pages, with correct routing between them, for:
- Main profile page 
- About Me
- Language Information
- Government Information
- Work Location
- Work Preferences
- Skills and Experience
- Create Experience x 5 and Edit Experience x5 (nearly identical pages, but different urls for each type, and for new vs existing items)
=> 1994 ensure routing is working for all profile edit forms

frontend/admin/src/js/components/GlobalFilter.tsx
Fixes a single instance of import/extension linting
Closes #2490
=> Fix import extension linting

api/database/factories/PoolCandidateFactory.php, api/database/factories/UserFactory.php, api/database/migrations/2022_05_04_173542_add_extra_constraints.php, api/database/seeders/DatabaseSeeder.php
This branch adds some more database constraints.  Most of them are just making pivots unique but I also added one to make the user sub unique.
Testing tips:
Get into the maintenance container: `docker-compose run --rm maintenance bash`
Get to the api directory: `cd /var/www/html/api/`
Check your migration status: `php artisan migrate:status`
Start from scratch: `php artisan migrate:fresh --seed`
Rollback one step: `php artisan migrate:rollback --step=1`
Roll forward to the end: `php artisan migrate`
Closes #1847
=> More DB constraints

.bundlewatch.config.js, frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.stories.tsx, frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx, frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx, frontend/talentsearch/src/js/components/experienceForm/experienceFormOperations.graphql, frontend/talentsearch/src/js/components/experienceForm/mutations.ts
resolves #1932 
I think it is functional and ready to be looked at now, Eric making the dialogs sure was real handy!
eslint is being weird unfortunately, I tried but failed with the ignore eslint prettier at the top
tbh, I'm a little surprised the delete works 😮
=> delete experience function

frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
resolves #2704 
Issue: navigation was back to the same form on submit
Solution: changed path
=> enabled go back on about-me submit

frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
resolves #2709 
issue: mismatched form padding
solution: picked one and switched the other one
=> about-me form width

frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
Resolves #2706 
If I choose to not accept any of the work preferences the summary page says required fields are missing.![Peek 2022-05-10 10-00.gif](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/f7901ed4-c619-41ad-acb9-2a377cda8300)
=> Profiles - Work Preferences always incomplete #2706

frontend/indigenousapprenticeship/src/js/components/Dialog/LearnDialog.tsx, frontend/indigenousapprenticeship/src/js/components/Dialog/RequirementDialog.tsx, frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx
Just some simple updates to the copy for the Indigenous Apprenticeship Program home page to better define program eligibility requirements.
=> IAP Homepage Copy Updates

documentation/style-guide.md
We've had a few discussion lately around best practices.  I think we've reached consensus on them so I tried to get them into the style doc.  I hope I've accurately captured the consensus on these but feel free to add comments on anything missed or misunderstood.
=> Docs - Style Guide - File Naming and Testing

frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
Resolves #2737
Should be "I Have An Indeterminate Position" (with an n)
=> Profile - Government Info - Typo #2737

frontend/package-lock.json, frontend/talentsearch/src/js/applicantProfileRoutes.ts, frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryForm.stories.tsx, frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryForm.tsx, frontend/talentsearch/src/js/components/roleSalaryForm/dialogs.tsx
resolves #2770 
Followed the AboutForm as a scaffold to set up this one similar to it for the sake of uniformity and consistency. Left the hooks and space for API functionality to be pencilled in later without too much hassle hopefully. 
ESLint ignore up top is there because I was having a11y alerts thrown over the modal summoning clickables. I'll need some advice how to best tackle that bit.
=> Roles and Salary Form

frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx, frontend/indigenousapprenticeship/src/js/hooks/useQuote.tsx, frontend/indigenousapprenticeship/src/js/lang/fr.json
This branch adds the French translation for the IAP home page.
Closes #2578
=> IAP French Translation

documentation/environment-variables.md
Hot off the press - environment variables.  Let me know if you find typos, things unclear, room for improvement...
=> Documentation - Environment Variables

frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/components/pool/PoolApplyPage.tsx, frontend/talentsearch/src/js/components/pool/poolOperations.graphql, frontend/talentsearch/src/js/directIntakeRoutes.ts
Resolves #2786 
Adds the placeholder page to apply to a pool.
=> Feature - 2786 -  Add Pool Application Placeholder Page

frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx
Quick hack so Gray can share the FR version of IAP.
**Note**: Need to properly get locale working in storybook in the future.
=> hack: get FR iap story working for preview

frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/components/pool/PoolApplicationThanksPage.tsx, frontend/talentsearch/src/js/directIntakeRoutes.ts
Resolves #2787.
Adds the placeholder page to thank users for applying to a pool.
=> Placeholder application thanks page

documentation/style-guide.md
Guidelines on naming and arranging react components.  Based on https://talent-cloud.slack.com/archives/CB424V61J/p1653943031732649
=> Documentation: Standard Components

api/tests/Feature/UserTest.php
This branch fixes the three old user tests that were set to "skipped".
h/t @JamesHuf for setting up the test suite with admin access.
Closes #1480
=> Fix old user tests

.vscode/project-words.txt, documentation/accessibility.md
This adds some basic documentation on the tooling we are and plan on using for testing accessibility. As well, it provides some glossary information on how to manually test our application for accessibility.
=> Accessibility Documentation

frontend/common/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx, frontend/common/src/components/UserProfile/UserProfile.tsx, frontend/common/src/constants/localizedConstants.tsx
Resolves #2928 
https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4185&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2340%3A4185
=> Update text and styling on Diversity, Equity and Inclusion section of Applicant Profile #2928

frontend/admin/src/js/components/Table/TableEditButton.tsx, frontend/cypress/integration/talentsearch/searchpage.spec.js, frontend/talentsearch/src/js/components/search/SearchContainer.tsx
resolves #2930 
To test, make sure /search isn't breaking or off in anyway 
Added a basic Cypress test, first try. It is something to build up over time I'd say so it can be barebones for now
=> Fix bug breaking going from search to request

frontend/common/src/components/Link/Link.tsx, frontend/talentsearch/src/js/authRoutes.ts, frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/components/register/RegisterPage.tsx, infrastructure/php-container/src/.htaccess
Resolves #2923 
This adds a page where users can register to use the application.
While it is fine to have multiple links with different text that go to the same location, the issue is that the links on this page each have a different function.
- Register for a GC Key
- Login to the application
- Register for application with GC Key
Ref: https://www.w3.org/TR/WCAG20-TECHS/H30.html
=> Feature  -2923 - Register Page

api/database/factories/PoolCandidateFactory.php, api/database/factories/PoolFactory.php, api/database/helpers/ApiEnums.php, api/database/seeders/DatabaseSeeder.php, api/database/seeders/PoolSeeder.php, api/tests/Feature/PoolCandidateTest.php, api/tests/Feature/UserTest.php
resolves #2894 
- candidates can be expired now
- restricted to IT 
- salary or classifications now, not both
testing, make sure it seeds successfully locally and play around in the database with your preferred method (app/adminer/etc)
=> improve seeded data for local testing

frontend/indigenousapprenticeship/src/js/components/Dialog/LearnDialog.tsx, frontend/indigenousapprenticeship/src/js/lang/fr.json
Resolves #3008.
- [Fixes EN and FR string that contained text meant as a comment](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3018/commits/e5c3619bcbfd92941e2ce39569277c9503885d98)
=> Update IAP FR copy

frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
Resolves #2984 
Changes name input label from `First Name and middle Name` -> `First Name and Middle Name`.
=> Copy - 2984 - Fix About Me Form Letter Case

api/app/Models/PoolCandidateFilter.php, api/graphql/schema.graphql, frontend/talentsearch/src/js/components/request/CreateRequest.tsx
This is the second attempt to solve the handling of EE options in a sub-input.  This solution uses a new accessor and mutator on the PoolCandidateFilter model. (Thanks Tristan!)
Ref: https://laravel.com/docs/8.x/eloquent-mutators
Closes #3031
=> Fix search request submission (2nd attempt)

frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx, frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
=> Remove min value from PoolCandidate expiry date validation

.github/workflows/bundlewatch.yml, .github/workflows/storybook.yml, infrastructure/deploy.sh
This branch removes the remaining instances of the hydrogen workaround.
Closes #2308
=> Remove hydrogen workaround

.github/dependabot.yml
=> Removes non-existent files monitored by Dependabot

api/app/Models/User.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/UserTest.php, frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryForm.tsx
resolves #2812 
Adds additional filtering to the UserFilterOrder thing, for UsersPaginated. 
To test, play around in GraphQL and see if anything appears off. This is not connected to anything frontend yet. 
Rolled in that one linting alert thing on all PRs because it was bugging me and it wasn't something that merited its own issue+PR
=> filter users by admin/users table search

frontend/common/src/components/form/Input/Input.tsx, frontend/common/src/components/form/TextArea/TextArea.tsx
resolves #2727 
Testing: Play around with forms (inputs + textareas fields) and ensure they behave and submit as expected
=> add whitespace trimming

frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
resolves #3104 
testing: ensure redirect occurs upon submitting the government info form
=> redirect upon government form submit

frontend/common/src/components/context/AuthorizationProvider.tsx
Resolves #3113.
Tweaked AuthorizationProvider to properly detect if up to date.
To test:
1. Log in as a nonexistent user (eg. 'brand.new.user').
2. Fill out welcome page and submit.
3. Confirm you are redirected to the profile page.
=> Redirect welcome page to profile

.bundlewatch.config.js, .github/workflows/bundlewatch.yml
Resolves #3187 
This adds the Indigenous Apprenticeship Program `app.js` to the `bundlewatch.config.js`
=> Debt - 3187 - Add IAP to bundlewatch

api/app/Http/Controllers/AuthController.php
=> Update acr_values from gckey to gckeymfa

frontend/common/src/lang/fr.json
=> Fix FR string for Message to state user is employed by government

frontend/talentsearch/src/js/components/search/deprecated/SearchContainer.tsx
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/3388#issuecomment-1189544806
=> Fixed markup typo in translation string.

frontend/cypress/integration/admin/admin-workflows.spec.js
May Resolve #3311 
Adds a `cy.wait` for the AllUsersPaginated query to complete when searching for a user.
Not sure if this will fix, going to run it a few times to see since it seems to be intermittent.
=> Bug - 3311 - Fix Auth e2e Workflow Failing

frontend/admin/src/css/app.css, frontend/common/src/components/Toast/Toast.stories.tsx, frontend/common/src/components/Toast/Toast.tsx, frontend/common/src/components/Toast/toast.css, frontend/talentsearch/src/css/app.css
Resolves #3159 
This fixes the X icon on toasts to be a consistent size regardless of the length of content in the toast.
- Added height and flex-shrink to close icon
- Moved css for toast to central location
- Created story for toasts
=> Bug - 3159 - fix toast x icon

frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/AwardAccordion.tsx, frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/CommunityAccordion.tsx, frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/EducationAccordion.tsx, frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/PersonalAccordion.tsx
Resolves #3426.
Updated the experience accordions to use the appropriate icon for their type.
=> Updated experience accordions to use the correct icon for their type

frontend/package.json
Just a little helper for running in `frontend/` dir.
=> Add run-script for building the merged storybook

api/programmatic-types.graphql, api/schema-directives.graphql
so that IDE tools can parse custom directive.
To test:
1. Open project in  VS Code
2. Ensure you have the [graphql-vscode](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) extension 
3. open api/graphql/schema.graphql
4. Test that IDE tools work! You should be able to `Alt+Click` a type to Go to Definition.
5. Open the Output tab of the integrated terminal, select GraphQL Language Server from the dropdown. You should see no errors in the terminal. (In particular, this PR fixes errors about an unknown "pluck" directive.)
=> Update compiled graphql files

frontend/common/src/components/Button/Button.stories.tsx, frontend/common/src/components/CardLink/CardLink.stories.tsx, frontend/common/src/components/Link/Link.stories.tsx, frontend/common/src/components/Pill/Pill.stories.tsx
Resolves #3212 
Combines colour variants of stories to reduce the number of snapshots.
=> Debt - 3212 - Combine Colour Variant Stories

frontend/common/src/components/UserProfile/ExperienceSection.tsx
Resolves #3479 
This adds back the gray background removed in #3457
=> Bug - 3479 - Add Gray Background to Experience Section

frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
=> Add i18n for Label displayed on lateral/secondment bounding box

frontend/common/src/constants/index.ts, frontend/common/src/constants/localizedConstants.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.test.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/EquityOptions.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/dialogs/DisabilityDialog.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/dialogs/IndigenousDialog.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/dialogs/VisibleMinorityDialog.tsx, frontend/talentsearch/src/js/components/diversityEquityInclusion/dialogs/WomanDialog.tsx, frontend/talentsearch/src/js/components/search/SearchForm.tsx, frontend/talentsearch/src/js/components/search/deprecated/SearchForm.tsx
=> Use common source for Employment Equity group messages 

.github/workflows/bundlewatch.yml, .github/workflows/e2e-tests.yml, .github/workflows/jest.yml, .github/workflows/lint.yml, .github/workflows/package-integrity-check.yml, .github/workflows/storybook.yml
Resolves #3380 
Updates the workflows to use the new `--location=global` syntax when upgrading npm
=> Tooling - 3380 - Update npm global syntax

frontend/admin/src/js/components/pool/EditPool/AddSkillsToPool.tsx, frontend/admin/src/js/components/pool/EditPool/editPoolOperations.graphql, frontend/common/src/helpers/skillUtils.ts, frontend/talentsearch/src/js/api/poolCandidateOperations.graphql, frontend/talentsearch/src/js/components/experienceForm/experienceFormOperations.graphql, frontend/talentsearch/src/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.tsx, frontend/talentsearch/src/js/components/skills/AddSkillsToFilter/AddSkillsToFilter.tsx
Resolves #3414.
Makes "Search by keyword" for skills actually use keywords.
=> Make skills searchable by keyword

frontend/common/src/components/CardLink/CardLink.tsx, frontend/common/src/components/Link/Link.tsx, frontend/common/src/components/TileLink/TileLink.tsx
Resolves #3543 
This conditionally sets the `<Link />` click handler when the `external` prop is set to false to allow navigating to external URLs.
=> Bug - 3543 - Fix External Links

frontend/common/src/components/Link/IconLink.tsx, frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx
Resolves #3453 
This improves the display of block level `<IconLink />` component and converts the links to add new experiences to use the `<IconLink />` component.
=> Design - 3453 - update add experience buttons

api/app/Models/User.php, api/database/factories/UserFactory.php, api/database/helpers/ApiEnums.php, api/database/migrations/2022_08_02_175856_add_citizen_veteran_fields.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/UserTest.php, frontend/common/src/fakeData/fakeUsers.ts
closes #3318 
adds the two fields and assorted backend changes that go along with it
test: checkout + migrate then check adminer and play in graphQL playground
Migration added
=> Citizen and Veteran backend

frontend/admin/src/js/api/poolCandidatesOperations.graphql, frontend/admin/src/js/components/user/AdminAboutSection.tsx, frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.tsx, frontend/admin/src/js/components/user/GeneralInformationTab/generalInfoOperations.graphql, frontend/common/src/components/UserProfile/ProfileSections/AboutSection.tsx, frontend/common/src/components/UserProfile/UserProfile.stories.tsx, frontend/common/src/constants/localizedConstants.tsx, frontend/talentsearch/src/js/api/userOperations.graphql, frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.test.tsx, frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx, frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
resolves #3319 
test:
check out submission in /profile/about-me
as well as viewing the user profiles in various places in the app
was a bit iffy on wording in some places, like I thought AboutSection on /profile should match selections on /profile/about-me form
definitely touches a bunch of areas and many small things
=> update frontend with citizen+veteran fields

README.md, api/app/Providers/AuthServiceProvider.php, frontend/admin/package.json, infrastructure/README.md
=> Remove Lumen references

frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.stories.tsx, frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.stories.tsx
This branch fixes the broken Chromatic stories.
Testing:
=> Fix Chromatic Stories

frontend/common/src/components/skills/MissingSkills/MissingSkills.stories.tsx, frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationPageWrapper.stories.tsx
We have a few stories that are unstable and triggering false positives in the diffs.
This branch stabilizes them.
Testing:
1. Run Storybook
2. Screenshot the three stories listed
3. Stop and restart Storybook
4. Compare the three stories to the screenshots
=> Stabilize Chromatic

frontend/admin/src/js/components/apiManagedTable/TableHeader.tsx, frontend/admin/src/js/components/user/UserTableFilterDialog.tsx, frontend/common/src/components/Button/Button.tsx
This resolves some conflicts caused by merging PRs which overwrote hydrogen changes.
=> Fix Hydrogen Conflicts

frontend/admin/src/js/components/user/UserTableFilterDialog.css, frontend/admin/src/js/components/user/UserTableFilterDialog.tsx
Updates the `UserTableFilterDialog` for hydrogen 2.0.0 compatibility.
=> update filter modal to use h2 2.0.0

frontend/indigenousapprenticeship/src/js/components/Dialog/LearnDialog.tsx, frontend/indigenousapprenticeship/src/js/lang/fr.json
closes #3761 
check out
intl-compile
dev
and then verify
=> update copy and translation LearnDialog

api/app/GraphQL/Mutations/TestPoolCandidateSnapshot.graphql, api/app/Models/User.php, api/database/factories/UserFactory.php, api/database/helpers/ApiEnums.php, api/database/migrations/2022_08_25_165115_change_is_veteran_field.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/PoolApplicationTest.php, api/tests/Feature/UserTest.php, frontend/admin/src/js/api/poolCandidatesOperations.graphql, frontend/admin/src/js/components/user/AdminAboutSection.tsx, frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.tsx, frontend/admin/src/js/components/user/GeneralInformationTab/generalInfoOperations.graphql, frontend/admin/src/js/components/user/useUserCsvData.tsx, frontend/admin/src/js/components/user/userOperations.graphql, frontend/common/src/components/UserProfile/ProfileSections/AboutSection.tsx, frontend/common/src/components/UserProfile/UserProfile.stories.tsx, frontend/common/src/constants/localizedConstants.tsx, frontend/common/src/fakeData/fakeUsers.ts, frontend/talentsearch/src/js/api/userOperations.graphql, frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.test.tsx, frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx, frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
resolves #3747 
updates it from a bool to enum, and changes in a bunch of places to adjust to the new typing
test: make sure you can update in /about-me, and it is reflected correctly in /profile and the /admin side of things
as well, keep an eye on the database and play around with adminer and anything else you think might need checking
=> update isVeteran field

frontend/common/src/components/Dialog/Dialog.tsx, frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/Definition.tsx, frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/DisabilityDialog.tsx, frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/IndigenousDialog.tsx, frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/VisibleMinorityDialog.tsx, frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/WomanDialog.tsx
=> Updates EE dialog styles and content

frontend/admin/src/js/components/pool/CreatePool.tsx
closes #3737 
Updates from `<h3>` to `<h2>` while maintaining size
check out -> dev + h2 -> visit `admin/pools/create`
=> update create pool page heading

frontend/talentsearch/src/js/components/employmentEquityForm/EmploymentEquityForm.tsx, frontend/talentsearch/src/js/lang/fr.json
Resolves #3802.
1. `cd frontend/talentsearch`
2. `npm run intl-compile`
3. `npm run production`
4. `npm run storybook`
5. Find **DiversityEquityInclusionForm** component
6. Verify [strings](https://github.com/GCTC-NTGC/gc-digital-talent/issues/3802#issue-1356203948) in English and French
=> Update DiversityEquityInclusionForm copy

frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
I found another incomplete copy change from the hydrogen upgrade.  Let's remove it for now and add it back in when it has been translated and the TODO logic has been finished.
=> Remove incomplete copy change from h2

frontend/common/src/components/Heading/Heading.tsx, frontend/common/src/components/TableOfContents/Section.tsx, frontend/common/src/components/UserProfile/UserProfile.tsx, frontend/common/src/components/accordion/Accordion.tsx, frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
Resolves #3829 
This adjusts some spacing while removing unneeded HTML for the `TableOfContents` components and Pool Advertisement page.
=> Design - 3829 - Pool Advertisement Spacing

frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx
This was mistakenly excised in #3866
=> Added viewport size back into IAP Home component story

frontend/common/src/components/skills/SkillPicker/SkillPicker.tsx, frontend/common/src/fakeData/fakeSkillFamilies.ts, frontend/common/src/fakeData/fakeSkills.ts, frontend/common/src/fakeData/index.ts, frontend/common/src/fakeData/skillFamilies.json, frontend/common/src/fakeData/skills.json, frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.stories.tsx
Resolves #3896
This uses the production skills as JSON files for the Experience Form storybook to better represent the data.
=> Feature - 3896 - Add real skills storybook

frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx, frontend/talentsearch/src/js/components/pool/poolOperations.graphql
closes #3448 
makes the application creation process work
**testing**: 
go to `/browse/pools` and click on a pool, append `/view` to the end of the URL (issue has already been created for this #3899)
if pool cannot be applied to, may need to try another pool or check its status in `/admin/pools` and publish it
click button to apply and ensure 
- success toast
- navigates to review application page
- application visible in My Applications
- Application is DRAFT
=> use create application mutation

frontend/cypress/integration/talentsearch/search-workflows.spec.js
Fixes the e2e test for search which was broken in #3984
=> Bug - Fix Search e2e

frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx, frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx, frontend/common/src/components/UserProfile/UserProfile.tsx
Resolves #3832 
This increases the heading levels for a few components by 1 to meet [WCAG 2.4.10.](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=246#section-headings)
=> a11y - 3832 - Fix Heading Levels

.github/workflows/lint.yml, frontend/admin/src/js/components/apiManagedTable/TableHeader.tsx
closes #3943 
merely adding in @patcon 's code
=> update linting workflow with tsc command

api/graphql/schema.graphql, frontend/common/src/helpers/router.tsx
This branch fixes two bugs on the welcome page:
- No user error message for duplicate email address on user update
- Changes languages on the welcome page triggers a navigation loop
This branch does not fix noted issue that the error message does not place browser focus on the right form field.  Since the error is server-side validation, implementing this would not be straightforward.
- Try to add an existing email address on the welcome page, observe a descriptive error message in the toasts
- Try to change languages on the welcome page, should be possible without looping
Closes #4042
=> Fix bugs with welcome page

frontend/common/src/messages/errorMessages.ts, frontend/talentsearch/src/js/components/awardDetailsForm/AwardDetailsForm.tsx, frontend/talentsearch/src/js/components/communityExperienceForm/CommunityExperienceForm.tsx, frontend/talentsearch/src/js/components/educationExperienceForm/EducationExperienceForm.tsx, frontend/talentsearch/src/js/components/personalExperienceForm/PersonalExperienceForm.tsx, frontend/talentsearch/src/js/components/workExperienceForm/WorkExperienceForm.tsx
closes #4088 
adds a validation input to start dates for all 5 experience forms
test:
ensure you cannot have future experiences and nothing else changed
=> required experiences to not be in the future

frontend/admin/src/js/components/poolCandidate/ViewPoolCandidate/ViewPoolCandidatePage.tsx, frontend/common/src/components/ToggleGroup/ToggleGroup.tsx
Adds toggle component to replace the "Toggle View" button.
Test by fiddling with the toggle and ensuring it works and nothing breaks.
=> Add toggle component to review application page

frontend/hydrogen.config.json, frontend/talentsearch/src/js/components/Home/partials/CallToAction/CallToAction.tsx
Resolves: https://github.com/GCTC-NTGC/gc-digital-talent/issues/4112 (see here for explanation)
=> Added corner bevel to hover state of CallToAction component

frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx
=> Bug - Fix enums in other requirements section of edit pool page

frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/components/support/SupportForm.stories.tsx, frontend/talentsearch/src/js/components/support/SupportPage.stories.tsx, frontend/talentsearch/src/js/components/support/SupportPage.tsx
This branch adds a placeholder page at /support to host the ticketing form.
Closes #4282
=> Add SupportPage component

frontend/talentsearch/src/js/components/support/SupportForm.tsx, frontend/talentsearch/src/js/talentSearchConstants.ts, frontend/talentsearch/webpack.base.js
=> Feature - Add tag to Support Form ticket creation

frontend/talentsearch/src/js/components/reviewMyApplication/ReviewMyApplicationPage.tsx, frontend/talentsearch/src/js/components/signAndSubmit/SignAndSubmitPage.tsx
Resolves #4317.
Fixes some broken links on the pool application pages.
Test by creating an application and ensuring all the links both application pages (review application page and sign and submit page) work properly.
=> Fix broken links on application pages

frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx, frontend/talentsearch/src/js/components/reviewMyApplication/ReviewMyApplicationPage.tsx
=> Bug - Fix breadcrumb links

frontend/common/src/lang/fr.json
=> Fix French typo on Label for the skills families dropdown

frontend/talentsearch/src/js/components/Browse/BrowsePoolsPage.tsx
=> Bug - Fix typo Browse Pools Page call to action

frontend/common/src/components/UserProfile/UserProfile.tsx
Resolves #4364 
Before: 
After:
=> Bug - Fix User Profile component edit links horizontal lining 

frontend/admin/public/index.html, frontend/admin/src/js/components/PoolDashboard.tsx, frontend/admin/src/js/lang/fr.json, frontend/indigenousapprenticeship/public/index.html, frontend/indigenousapprenticeship/src/js/components/Router.tsx, frontend/indigenousapprenticeship/src/js/lang/fr.json, frontend/talentsearch/public/index.html, frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/lang/fr.json
Resolves #3086.
1. Compile talentsearch `npm run intl-compile --workspace=talentsearch`
2. Compile admin `npm run intl-compile --workspace=admin`
3. Compile indigenousapprenticeship `npm run intl-compile --workspace=indigenousapprenticeship`
4. Build talentsearch `npm run production --workspace=talentsearch`
5. Build admin `npm run production --workspace=admin`
6. Build indigenousapprenticeship `npm run production --workspace=indigenousapprenticeship`
7. Navigate to **talentsearch** site
8. Open browser devtools and verify `<meta name="description">` tag's content value contains appropriate copy in English
9. Switch site to French
10. Open browser devtools and verify `<meta name="description">` tag's content value contains appropriate copy in French
11. Navigate to **admin** site
12. Open …
=> Feature - Add dynamic meta descriptions

frontend/common/src/components/Footer/Footer.tsx
=> Bug - Fix CanadaLogo footer alignment

frontend/admin/src/js/components/PoolDashboard.tsx, frontend/admin/src/js/lang/fr.json, frontend/indigenousapprenticeship/src/js/components/Router.tsx, frontend/indigenousapprenticeship/src/js/lang/fr.json, frontend/talentsearch/src/js/components/Router.tsx, frontend/talentsearch/src/js/lang/fr.json
=> Bug - Use react-helmet to change page titles

frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx, frontend/admin/src/js/lang/fr.json, frontend/common/src/lang/fr.json, frontend/talentsearch/src/js/lang/fr.json
=> Fixes miscellaneous i18n problèmes

api/app/Console/Commands/CreateDigitalCareersPools.php, api/app/Console/Commands/MigratePoolCandidatesToUser.php
=> Set job_looking_status in MigratePoolCandidatesToUser command

api/app/Models/PoolCandidate.php, api/tests/Feature/ApplicantTest.php, api/tests/Feature/PoolCandidateTest.php
spun out of #4661 
copies that for the other model with paginated results
make sure tests pass!
=> mirror the null + undefined testing done for User on PoolCandidate

frontend/admin/src/js/components/pool/PoolTable.tsx
Resolves #4578 
Suggested order:
Pool Name > Candidates > Status > Group and level > Owner > Edit
=> Feature - Reorder pool columns

frontend/common/src/lang/fr.json
=> Removes extra space in French string

frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryForm.tsx, frontend/talentsearch/src/js/lang/fr.json
Resolves #4881.
1. Compile French `npm run intl-compile --workspace=talentsearch`
3. Navigate to Role and Salary Expectations `/users/{userId}/profile/role-salary-expectations/edit`
4. Confirm space between **IT** and opening bracket
6. Confirm space remains between **TI** and opening bracket
=> Bug - Add missing space

frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInfoTabDialogs.tsx, frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.tsx, frontend/admin/src/js/lang/fr.json
Resolves #4879.
1. Compile French `npm run intl-compile --workspace=admin`
2. Build admin `npm run production --workspace=admin`
3. Navigate to User `/admin/users/{userId}`
4. Confirm copy **Add user to pool**
6. Confirm copy **Ajouter l'utilisateur au bassin**
=> Copy - Admin User

frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx, frontend/talentsearch/src/js/lang/fr.json
Resolves #4946.
1. Compile talentsearch `npm run intl-compile --workspace=talentsearch`
2. Build talentsearch`npm run production --workspace=talentsearch`
3. Navigate to **/en/browse/pools/{poolId}**
4. Confirm copy changes in English
5. Navigate to **/fr/browse/pools/{poolId}**
6. Confirm copy changes in French
=> Copy - Update Pool advertisement location requirement, Remote option

frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx, frontend/indigenousapprenticeship/src/js/lang/fr.json
Resolves #4950.
1. Compile indigenousapprenticeship `npm run intl-compile --workspace=indigenousapprenticeship`
2. Build indigenousapprenticeship `npm run production --workspace=indigenousapprenticeship`
3. Navigate to **/en/indigenous-it-apprentice**
4. Confirm copy changes in English
5. Navigate to **/fr/indigenous-it-apprentice**
6. Confirm copy changes in French
=> Copy - Update Talent portal strategy item 4 content

frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx, frontend/talentsearch/src/js/lang/fr.json
=> Copy - Fix description typos

frontend/common/src/lang/fr.json
This adds missing translations that were lost at some point and accidentally merged in #4761
=> Bug - Add missing translations

.github/ISSUE_TEMPLATE/⌨-accessibility-issue.md, .github/ISSUE_TEMPLATE/⚙️-new-component.md, .github/ISSUE_TEMPLATE/🧩-new-pattern.md
Adds an issue template for patterns. To be used when creating pattern discussions.
=> Add pattern issue template

frontend/talentsearch/src/js/lang/fr.json
Resolves #4969.
1. Compile talentsearch `npm run intl-compile --workspace=talentsearch`
3. Navigate to **/fr/browse/pools/{poolId}**
6. Confirm copy changes in French
=> Copy - Update Explanation of a pools required occupational skills (fr)

api/README.md, frontend/cypress.config.js, frontend/cypress/README.md, frontend/package.json, infrastructure/README.md
Re-ticketed from (and to be merged into) https://github.com/GCTC-NTGC/gc-digital-talent/pull/4998#issuecomment-1341052248
=> Add small improvements to cypress test running

.github/ISSUE_TEMPLATE/📐-new-design-issue.md
Adds a link to a content spreadsheet template, adds checklist items for usability and accessibility testing
=> Updates the generic design issue template

api/app/GraphQL/Directives/PluckDirective.php
=> Documentation - Remove stale comment

frontend/common/src/components/Pill/Pill.tsx, frontend/talentsearch/src/js/components/Browse/OngoingRecruitmentSection.tsx, frontend/talentsearch/src/js/components/Browse/browseOperations.graphql, frontend/talentsearch/src/js/lang/fr.json
This branch adds a pill to the job stream if any of the classifications in the stream have an essential skills list that is satisfied by the user's skills.
- The styling on the accordion is not *exactly* matching the design.  Flexible theming for the accordion will be covered in #5042.
- Rebuild the talentsearch project and navigate to `http://localhost:8000/en/browse/pools`
- Suggested checklist:
<details>
<summary>Testing query</summary>
It can be tricky to know what skills you need to add to your profile to trigger the pill.  This query can help you know.
```sql
select stream, "group" || '-' || "level" classifiaction, string_agg(english_name, ', ' order by english_name) skills
from (
select p.stream, c."group", c."level", s.name->>'en' english_name
from pools p 
left join …
```
=> Job stream is recommended pill

.github/dependabot.yml, documentation/dependabot.md
Resolves #5096.
1. Verify documentation is still accurate in **documentation/dependabot.md**.
2. Approve this PR and see if Dependabot opens a bunch of PRs tomorrow 😉
=> Feature - Change Dependabot update day to Thursday

.github/ISSUE_TEMPLATE/ 🐛-bug-report.md, .github/ISSUE_TEMPLATE/♻️-debt-refactor.md, .github/ISSUE_TEMPLATE/✏️-documentation.md, .github/ISSUE_TEMPLATE/✨-feature-request.md, .github/ISSUE_TEMPLATE/❓-question.md, .github/ISSUE_TEMPLATE/🛠️-tooling.md, .github/ISSUE_TEMPLATE/🧪-tests.md, .github/PULL_REQUEST_TEMPLATE/🌱-pull-request.md
As promised, I am adding templates for submitting issues and PRs. The following templates have been added:
- 🐛 Bug Report
- ♻️ Debt/Refactor
- ✏️ Documentation
- ✨ Feature
- ❓ Question
- 🧪 Tests
- 🛠️ Tooling
- 🌱 Pull Request
These should cover most use cases for submitting issues. I tried to cover all of the things I beleive are important when submitting different types of issues. I'd love for anyone to provide any additions and improvements they think could be made so we get well defined and easy to follow issues! 😄 
Honestly, I'm not 100% sure how to test these. What I usually do is open the project in VS Code and option click the file and select "Open in Preview" from the context menu. Or, you could open them in a MD editor if you have one.
If you have better ways of testing these, …
=> Feature - Add Issue/PR Templates

frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.stories.tsx, frontend/admin/src/js/stories/Department.stories.tsx, frontend/common/src/components/Accordion/Accordion.stories.tsx, frontend/common/src/components/Accordion/Accordion.test.tsx, frontend/common/src/components/Alert/Alert.stories.tsx, frontend/common/src/components/Card/Card.stories.tsx, frontend/common/src/components/Card/CardFlat/CardFlat.stories.tsx, frontend/common/src/components/Dialog/Dialog.stories.tsx, frontend/common/src/components/Dialog/Dialog.test.tsx, frontend/common/src/components/TableOfContents/TableOfContents.stories.tsx, frontend/common/src/components/Toast/Toast.stories.tsx, frontend/common/src/components/Well/Well.stories.tsx, frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationPageWrapper.stories.tsx, frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.stories.tsx
This PR solves CSpell flagging static lorem ipsum with warnings.
2. Verify modified stories still render correctly.
3. Search files in the repository for `lorem` (i.e. via [cspell cli](https://www.npmjs.com/package/cspell)).
4. Verify there is no static lorem copy.
Resolves #5041.
=> Feature - 5041 - Replace static lorem ipsum

frontend/common/src/components/Breadcrumbs/v2/Breadcrumbsv2.stories.tsx
🤖 Resolves #5299.
This PR fixes a console error that appears in the `Breadcrumbs/v2` component storybook story.
2. Open browser console
3. Navigate to the `Breadcrumbs/v2` component
4. Ensure there are no console errors
=> Bug - 5299 - Fix `Breadcrumbs/v2` component storybook story

api/app/GraphQL/Mutations/CreateApplication.php, api/app/Listeners/StoreApplicationSnapshot.php, api/app/Models/Skill.php, api/app/Policies/PoolPolicy.php, api/app/Providers/AppServiceProvider.php, api/app/Rules/HasEssentialSkills.php, api/tests/Feature/ApplicantFilterTest.php
🤖 Resolves 4539
This branch enables Eloquent strict mode in development environments and corrects a few bugs found.
1.  Make sure Laravel is in not in production mode `php artisan env`
2.  Phpunit tests pass
3. Cypress tests pass
4. Nothing else fishy happening
=> Enable Eloquent strict mode

frontend/admin/src/js/components/apiManagedTable/useTableState.ts
🤖 Resolves #5371
Fixes glitchy behaviour on Hidden Column controls when a table has hidden columns by default, as is the case on the Users table.
Unexpected behaviour was being caused by two things:
1. showing all columns means storing an empty list in the hidden columns param. But an empty list was being stored in the url as an empty string, which was hard to distinguish from the param being undefined at all, and the param being undefined was interpreted as the defaultValue, which in this case is NOT an empty list.
2. a new value could be interpreted as different from the default value if they had the same columns but in a different order. 
These problems were resolved by
1. encoding the hidden columns list as a json string, making the empty list very explicit
2. converting lists to Sets …
=> Fix hidden column controls on User table

apps/web/src/components/ApplicationPageWrapper/ApplicationPageWrapper.stories.tsx, apps/web/src/components/ApplicationPageWrapper/ApplicationPageWrapper.tsx, apps/web/src/components/ProfileFormWrapper/ProfileFormWrapper.stories.tsx, apps/web/src/components/ProfileFormWrapper/ProfileFormWrapper.tsx, apps/web/src/pages/AboutMePage/AboutMeForm.tsx, apps/web/src/pages/CreateAccountPage/CreateAccountPage.tsx, apps/web/src/pages/EmploymentEquityPage/EmploymentEquityForm.tsx, apps/web/src/pages/ExperienceAndSkillsPage/ExperienceAndSkills.tsx, apps/web/src/pages/ExperienceFormPage/ExperienceFormPage.tsx, apps/web/src/pages/GovernmentInfoPage/GovernmentInfoForm.tsx, apps/web/src/pages/LanguageInfoPage/LanguageInformationForm.tsx, apps/web/src/pages/LoggedOutPage/LoggedOutPage.tsx, apps/web/src/pages/LoginPage/LoginPage.tsx, apps/web/src/pages/MyApplicationsPage/MyApplicationsPage.tsx, apps/web/src/pages/PoolAdvertisementPage/PoolAdvertisementPage.tsx, apps/web/src/pages/ProfilePage/ProfilePage.tsx, apps/web/src/pages/RegisterPage/RegisterPage.tsx, apps/web/src/pages/RequestPage/RequestPage.tsx, apps/web/src/pages/ReviewApplicationPage/ReviewApplicationPage.tsx, apps/web/src/pages/RoleSalaryPage/RoleSalaryForm.tsx, apps/web/src/pages/SearchPage/SearchHeading.tsx, apps/web/src/pages/SearchPage/SearchPage.tsx, apps/web/src/pages/SignAndSubmitPage/SignAndSubmitPage.tsx, apps/web/src/pages/WorkLocationPage/WorkLocationForm.tsx, apps/web/src/pages/WorkPreferencesPage/WorkPreferencesForm.tsx, frontend/common/src/components/Hero/Hero.tsx
🤖 Resolves #5314 
This updates all public pages to use the new hero component.
All profile forms have been updated to use the new hero as well so make sure to check those.
> **Note**
> @substrae Mentioned he was working on redesigning the profile form pages so they may look a little odd temporarily.
1. Build frontend `npm run build`
2. Navigate to each page confirming the new hero is there and spacing looks okay
=> Feature - 5314 - Update Page Heroes

apps/web/src/pages/LanguageInfoPage/LanguageInformationForm.tsx
🤖 Resolves #4651.
This PR removes a comment that is no longer applicable.
=> Feature - 4651 - Removes comment

apps/web/package.json, frontend/admin/package.json, frontend/admin/src/js/components/poolCandidate/PoolCandidateDocument.tsx, frontend/admin/src/js/components/user/UserProfileDocument.tsx, frontend/common/package.json, frontend/common/src/components/Button/IconButton.tsx, frontend/common/src/components/CardLink/CardLink.tsx, frontend/common/src/components/CheckButton/CheckButton.tsx, frontend/common/src/components/PageHeader/PageHeader.tsx, package-lock.json
🤖 Resolves #5495 
This branch updates the SVG props for the newest version of heroicons
1. Make sure the site builds and pasts CI tests
2. Review Chromatic visual diffs
=> 5495 bump heroicons

apps/web/src/lang/fr.json, apps/web/src/pages/BrowsePoolsPage/ActiveRecruitmentSection.tsx
🤖 Resolves #5379
This PR updates the copy related to describing how the application process works in the `ActiveRecruitmentSection` component.
1. Navigate to `/en/browse/pools`
2. Verify copy that follows the **Active talent recruitment processes** heading is the expected copy
3. Navigate to `/fr/browse/pools`
4. Verify copy that follows the **Processus actifs de recrutement de talents** heading is the expected copy
=> Copy - 5379 - Updates description of how the application process works

apps/web/src/pages/Applications/MyApplicationsPage/MyApplications.stories.tsx
🤖 Resolves #5431.
h/t @esizer for solution.
This PR fixes the `MyApplications` story in storybook.
2. View **My Applications** story
3. Verify **My Applications** story works as expected
=> Bug - 5431 - Fixes `MyApplications` story

.vscode/project-words.txt, frontend/common/src/components/MissingSkills/MissingSkills.stories.tsx, frontend/common/src/components/MissingSkills/MissingSkills.tsx
🤖 Resolves #5551.
h/t @esizer for going through the logic behind the individual `MissingSkills` conditional blocks!
This PR updates the `MissingSkills` stories to reflect the current functionality and properties of `MissingSkills`.
The `MissingSkills` component itself had a bug in how `missingOptionalSkills` were calculated and was addressed in this PR in order for the different stories to be rendered correctly.
2.  View five **Missing Skills** stories
3. Ensure each story render what its name proposes to do
=> Bug - 5551 - Updates `MissingSkills` component, stories

maintenance/scripts/refresh_frontend.sh
🤖 Resolves #5596
Adds `npm i` to the refresh frontend script to ensure deps are up to date.
1. Run the refresh frontend script using VS Code build tasks and ensure the `npm install` occurs
=> Add npm i to refresh frontend

.github/workflows/translations.yml, apps/web/src/lang/fr.json, frontend/common/src/lang/fr.json
🤖 Resolves #5291
This branch adds the ability for the translation CI to detect orphaned strings in the French translation files.
It works by detecting Git workspace changes, just like the schema check.
1. Copy this branch to a new branch for testing
2. Remove the last one or two commits to add orphaned strings back into the files
3. Post a draft PR and review the CI output
=> Detect orphan translations

.bundlewatch.config.js, .github/workflows/bundlewatch.yml
🤖 Resolves #5167 
This normalizes the file names for bundlewatch.
Done using the [`normalizeFilenames`](https://bundlewatch.io/#/reference/configuration?id=normalizefilenames:~:text=Hash%20remover%3A%20Finds%20characters%20between%20a%20dot%20and%20the%20extension%20and%20removes%20them.) option in the `.bundlewatch.config.js`
1. Run `npx bundlewatch --config .bundlewatch.config.js`
2. Confirm the filename has no hash
=> Bug - 5167 - Normalize bundlewatch file names

frontend/common/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx, frontend/common/src/components/form/Checkbox/Checkbox.tsx
🤖 Resolves #5590 
This re-aligns the input of long labelled checkboxes to the top.
> **Note**
> I had to fix some hydrogen selectors in the diversity form to get hydrogen to compile properly so, bonus? 😅 
2. Check the "Long Text Checkbox" story
3. Confirm the input aligns to the top of the text
4. Confirm other checkbox stories remain unchanged
5. Check the "User Profile 1" story and confirm the Indigenous icons do not leak out of the well
=> Bug - 5590 - Fix checkbox alignment

apps/web/src/components/ApplicationPageWrapper/ApplicationPageWrapper.stories.tsx, apps/web/src/components/ProfileFormWrapper/ProfileFormWrapper.stories.tsx, apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.stories.tsx, apps/web/src/pages/Teams/IndexTeamPage/components/TeamTable/TeamTable.tsx, apps/web/src/pages/Users/ViewUserPage/components/GeneralInformationTab/GeneralInformationTab.stories.tsx, frontend/common/src/components/Accordion/Accordion.stories.tsx, frontend/common/src/components/Alert/Alert.stories.tsx, frontend/common/src/components/Card/Card.stories.tsx, frontend/common/src/components/Card/CardFlat/CardFlat.stories.tsx, frontend/common/src/components/Dialog/Dialog.stories.tsx, frontend/common/src/components/TableOfContents/TableOfContents.stories.tsx, frontend/common/src/components/Toast/Toast.stories.tsx, frontend/common/src/components/Well/Well.stories.tsx, frontend/common/src/fakeData/fakeTeams.ts
🤖 Resolves #5465.
This PR updates faker data to be consistent in order to avoid creating unexpected changes for Chromatic.
2. Observe any instances in storybook stories where `faker` is referenced to render text
3. Ensure on page refresh, text output is the same
=> Bug - 5465 - Updates faker data to be consistent

apps/web/src/hooks/useApplicationInfo.ts, apps/web/src/pages/Profile/AboutMePage/components/AboutMeForm/AboutMeForm.tsx, apps/web/src/pages/Profile/EmploymentEquityPage/components/EmploymentEquityForm/EmploymentEquityForm.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx, apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.tsx, apps/web/src/pages/Profile/LanguageInfoPage/components/LanguageInformationForm/LanguageInformationForm.tsx, apps/web/src/pages/Profile/RoleSalaryPage/components/RoleSalaryForm/RoleSalaryForm.tsx, apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx, apps/web/src/pages/Profile/WorkPreferencesPage/components/WorkPreferencesForm/WorkPreferencesForm.tsx
🤖 Resolves #5609 
This extracts some re-used code out into a hook to keep the codebase DRY.
Returns:
- id: The current application id (if it exists)
- param: The existing search param (if it exists)
- returnRoute: The path any back buttons should return to
- This is either the application,
- The user profile
- Generic profile route (if we do not have the current users id)
2. Navigate to each profile form and confirm they still function along with the back links
3. Create and application
4. Repeat step 3 within the context of an application
=> Debt - 5609 - Create Application Parameter Hook

api/config/rolepermission.php, api/tests/Feature/RolePermissionTest.php
🤖 Resolves #5634
Updates the seeded roles and permissions to match the newest version of [this table](https://docs.google.com/spreadsheets/d/1RC7wufxwjLEvaEunHsfZfOzBefg218dvvzkDwKSiQjI/edit#gid=428263758).
Not sure what the best way to test this is. Look through the seeder and try to check that nothing is missing compared to the spreadsheet?
Also, try to check that the seeder will run without errors even if you have run the previous version of this seeder.
Add a screenshot (if possible).
=> Update roles and permissions according to newest table

apps/web/src/pages/ApplicantDashboardPage/components/DashboardHeading.tsx, apps/web/src/pages/ApplicantDashboardPage/components/HeroCard.tsx, apps/web/src/pages/ApplicantDashboardPage/components/HeroCardItem.tsx
Modifies the look, colors, and animations in the `ApplicantDashboardPage`'s `DashboardHeading` component.
Just some minor changes (I promised I'd handle them myself to avoid further conflicting issues).
1. Compile storybook and verify the changes
=> Dashboard heading updates

packages/client/src/components/ClientProvider/ClientProvider.tsx
🤖 Resolves {#5684}
Current problem is logger is logging when there is no actual graphql error like below ( note **graphQLErrors** is an empty array : 
{"message":"ClientProvider onError","error":{"name":"CombinedError","graphQLErrors":[],"networkError":{}},"operation":{"key":-623720476,"query":{"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"getMe"},"variableDefinitions":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"me"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"roles"},"arguments":[], …
=> log only when there is an error

.github/workflows/blocking-issues.yml
🤖 Resolves {#5924}
This PR will add blocked label on the issue 
Disclaimer: I'm unsure how to test this in local 🤔
=> Add github action for blocked issues label

api/database/factories/DepartmentFactory.php, api/tests/Feature/DepartmentTest.php
🤖 Resolves #5873 
Fixes the `DepartmentTest.php`.
Updates the `DepartmentFactory.php` to increase the randomness of the `department_number` to avoid unique constraints. 
1. Run the `DepartmentTest.php` multiple times (10+)
2. Confirm that is consistently passes
=> [Bug] Fix department test

.github/ISSUE_TEMPLATE/ 🐛-bug-report.md, .github/ISSUE_TEMPLATE/♻️-debt-refactor.md, .github/ISSUE_TEMPLATE/✨-feature-request.md, .github/ISSUE_TEMPLATE/🛠️-tooling.md, .github/ISSUE_TEMPLATE/🧪-tests.md
🤖 Resolves #5986 
Adds the 🛑 Blockers section to issue templates that require it.
1. Review the templates
2. Confirm the templates listed in the AC have the blockers section
3. Confirm they follow the syntax required by the [Blocking Issues action](https://github.com/marketplace/actions/blocking-issues)
=> Add blockers issue templates

apps/web/src/lang/fr.json
=> Update french translation for the CIOB

apps/web/src/components/Table/ApiManagedTable/useFilterOptions.test.tsx, apps/web/src/components/Table/ApiManagedTable/useFilterOptions.tsx, apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.test.tsx
🤖 Resolves #4637.
This PR removes unused todo comments and an already skipped jest test.
1. Ensure app continues to work and passes jest tests.
=> [Debt] Removes unused todo comments, stub jest test

infrastructure/bin/post_deployment.sh
🤖 Resolves #6095 
Resolves the accidental deletion of the web config copying. 
Just copy pasting things back in.
1. Proofread the commit
2. ?
=> Bug - 6095 - add substitution of web config back in

apps/web/package.json, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.test.tsx, package-lock.json, packages/forms/package.json, packages/forms/src/components/BasicForm.tsx
🤖 Resolves #5282 
This bumps `react-hook-form` and massages some types to get it to work properly.
This has been sitting for a while as we wait for `react-hook-form` to make some types external. However, I was able to get it to work by massaging some types. It is a less than ideal solution though, the only place this was done was in `UnsavedChanges` which is currently a pain point anyway so I'm not sure how much negative impact will result from these changes 🤷‍♀️ 
1. Install deps `npm i`
2. Build app `npm run build` and confirm it succeeds without error
3. Navigate to anywhere we are using the `BasicForm` (profile is a good place for this)
4. Interact with the form confirming it works as expected
- …
=> [Debt] Bump `react-hook-form`

.bundlewatch.config.js, apps/web/src/components/Context/ContextProvider.tsx, packages/forms/src/components/Repeater/Repeater.stories.tsx, packages/forms/src/components/Repeater/Repeater.test.tsx, packages/forms/src/components/Repeater/Repeater.tsx, packages/forms/src/index.tsx, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/formMessages.ts, packages/ui/src/components/Announcer/Announcer.tsx, packages/ui/src/index.tsx
🤖 Resolves #6242 
Adds a `Repeater` component to `@gc-digital-talent/forms` package.
This new component is a fairly generic abstraction of the `useFieldArray` hook in `react-hook-form` that provides some styling, with common actions with accessibility considerations.
**SEE**: story shows more complex examples.
> **Note**
> Must be used within a `react-hook-form` `FormProvider`.
```tsx
import { Repeater } from "@gc-digital-talent/forms";
const Form = () => {
const methods = useForm();
const { control } = methods;
const name = "repeater";
const { append, remove, move, fields } = useFieldArray({ name, control });
return (
<FormProvider {...methods}>
<Repeater.Root addText="Add Item" onAdd={append(emptyOrPopulatedObjectOfNewValues)}>
{fields.map((item, index) => (
<Repeater.Fieldset …
```
=> [Feature] Field repeater component

.github/ISSUE_TEMPLATE/⌨-accessibility-issue.md
This branch updates the accessibility issue template to be more similar to the format of other issue templates, especially the bug issue template.
=> [Docs] Updates accessibility issue template

.vscode/extensions.json
🤖 Resolves #5938.
This PR adds two VS Code extension recommendations:
- [Docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
- [French - Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french)
1. Open Visual Studio Code app
2. View [recommended extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions)
3. Observe [Docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker), [French - Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french)
4. Install them!
=> [Docs] Adds VS Code extension recommendations

apps/e2e/cypress/e2e/talentsearch/direct-intake.cy.js, apps/e2e/cypress/e2e/talentsearch/submit-application-workflows.cy.js, apps/web/src/components/Layout/Layout.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationLayout.tsx, apps/web/src/pages/Home/HomePage/components/Hero/Hero.tsx, apps/web/src/pages/Home/HomePage/components/Opportunities/Opportunities.tsx, apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #6290.
This PR changes instances of **Looking for a job?**, **Browse opportunities**, **Browse IT jobs** to **Browse jobs** for better consistency.
1. Navigate to pages affected
2. Ensure copy is correct in English and French
=> [a11y] Consolidates use of several terms that link to the same `browsePools` path

apps/web/src/pages/Applications/SignAndSubmitPage/SignAndSubmitPage.tsx
🤖 Resolves #6359.
This PR fixes the **Sign and submit** page layout to align it with previous steps of the application.
1. Create an application
2. Navigate to **Step 2: Sign and submit**
3. Observe the **On this page** section looks the same as the previous steps layout
=> [Bug] Fixes Sign and submit page layout

apps/web/src/pages/Applications/SignAndSubmitPage/SignAndSubmitPage.tsx
🤖 Resolves #6356.
This PR fixes the **My applications** breadcrumb link URL on the **Sign and submit** page of the application process.
1. Create an application
2. Navigate to **Step 2: Sign and submit**
3. Click **My applications** breadcrumb link
4. Note presence on **My applications** page instead of **Browse jobs** page
=> [Bug] Fixes My applications breadcrumb URL

apps/web/src/lang/fr.json, apps/web/src/pages/Applications/MyApplicationsPage/MyApplications.stories.tsx, apps/web/src/pages/Applications/MyApplicationsPage/MyApplicationsPage.tsx, apps/web/src/pages/Profile/AboutMePage/components/AboutMeForm/AboutMeForm.tsx, apps/web/src/pages/Profile/EmploymentEquityPage/components/EmploymentEquityForm/EmploymentEquityForm.tsx, apps/web/src/pages/Profile/ExperienceAndSkillsPage/components/ExperienceAndSkills.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx, apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.tsx, apps/web/src/pages/Profile/LanguageInfoPage/components/LanguageInformationForm/LanguageInformationForm.tsx, apps/web/src/pages/Profile/RoleSalaryPage/components/RoleSalaryForm/RoleSalaryForm.tsx, apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx, apps/web/src/pages/Profile/WorkPreferencesPage/components/WorkPreferencesForm/WorkPreferencesForm.tsx
🤖 Resolves #6357.
This PR changes instances of My Applications to My applications.
1f5425e178aeb31ef20f9a17f5bb901b8471146c fixes a consistency issue so that the menu item matches the corresponding page title, breadcrumbs, and common use of the term throughout the app in French.
1. Navigate to all components changed
2. Ensure **My applications** (English) and **Mes candidatures** (French) appear
=> [Bug] Changes instances of My Applications to My applications

README.md
🤖 Resolves #5916.
This PR removes a second reference to packages in the root `README.md` file.
1. Open the root `README.md` file
2. Decide whether the copy makes sense
=> [Docs] Removes second reference to packages

api/app/GraphQL/Queries/CountPoolCandidatesByPool.php, api/app/Models/PoolCandidate.php, api/app/Models/User.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/ApplicantFilterTest.php, api/tests/Feature/ApplicantTest.php, api/tests/Feature/CountPoolCandidatesByPoolTest.php, api/tests/Feature/UserTest.php, apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.tsx
🤖 Resolves #6367 
Introduces OR matching of skills rather than just AND. 
Tricky bit to keep things playing nice with ApplicantFilter.php
ApplicantFilterInput.skills is the OR matching while skillsIntersectional is the other one.
Scopes skillsIntersectional for the classic, skillsAdditive is the new coke. The latter becomes the main skills scope so X.skills 
Additional scope was straightforward to add since I only had to recycle the existing mammoth and tweak it.
1. head to view pool candidates for some pool
2. view a user profile, note what skills they have and don't have
3. skill filter for one skill they have and don't have, observe they appear in results
As well, tests pass locally
=> [Feature] skill filter intersectional and additive

apps/web/src/components/ProfileFormWrapper/ProfileFormWrapper.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.test.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
🤖 Resolves #6451.
This PR fixes the case for **my profile** to be sentence case instead of title case. For more information, see the [Canada.ca Content Style Guide](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-1).
1. Navigate to a profile
2. Observe breadcrumb
3. Delete an experience
4. Observe copy
=> [Bug] Fixes case for my profile

documentation/style-guide.md
This PR makes a minor change to the casing from Typescript to TypeScript.
REF: https://www.typescriptlang.org/
=> [Docs] Updates style-guide.md

apps/web/src/components/CallToAction/IconWrapper.tsx, apps/web/src/components/CallToAction/styles.ts, apps/web/src/components/Hero/Hero.tsx, apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx, apps/web/src/pages/Applications/ApplicationResumeAddPage/ApplicationResumeAddPage.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx, hydrogen.config.json, packages/ui/src/components/Accordion/styles.ts
🤖 Resolves #6293 
Updates the line height to `1.5` and fixes small typography/whitespace issues.
1. run `dev` or `storybook`
2. Take a look at headings
3. Take a look at accordions
=> [Styling] Updates line-height, fixes hero text size, fixes accordion whitespace

apps/web/public/restricted.html, infrastructure/conf/nginx-conf-deploy/default, infrastructure/conf/nginx-conf-local/default
🤖 Resolves #5362 
This branch adds a restricted notice page that the F5s can redirect to when necessary.
1. Rebuild site
2. Restart webserver container
3. Navigate to `/restricted.html`
4. Bonus - test on the dev server, too
=> [Feature] Add restricted page

README.md
I just noticed an outdated statement on the readme from when the frontend used to run on Laravel.
=> [Docs] Update README.md server description

apps/web/.env.example, apps/web/src/hooks/useRoutes.ts, apps/web/src/pages/Applications/MyApplicationsPage/components/ApplicationCard/ApplicationActions.tsx, apps/web/src/pages/CreateApplicationPage/CreateApplicationPage.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #6609 
Updates links to application to point to the new application workflow if feature flag is enabled.
There are some `reviewApplication` left, however these only exist within the current application workflow. Not sure if makes sense for the profile forms to return to the new application workflow if you got there from the exiting one 🤔 
1. Search for `reviewApplication` and make sure it only exists within the old application workflow
2. Build `npm run build:fresh`
3. Navigate to "My applications"
4. Confirm all links to applications go to new application workflow
5. Navigate to "My dashboard"
6. Repeat step 4
=> [Debt] Update application links

api/app/Models/Pool.php, api/database/factories/PoolFactory.php, api/database/migrations/2023_05_19_160057_remove_pool_description_column.php, api/database/seeders/PoolSeeder.php, api/database/seeders/PoolSeederUat.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, apps/web/src/pages/Pools/BrowsePoolsPage/browseOperations.graphql, apps/web/src/pages/Pools/BrowsePoolsPage/components/PoolCard/PoolCard.tsx, apps/web/src/pages/Pools/IndexPoolPage/indexPoolsOperations.graphql, apps/web/src/pages/Pools/poolOperations.graphql, apps/web/src/pages/SearchRequests/SearchPage/components/SearchPools.tsx, apps/web/src/pages/SearchRequests/SearchPage/searchPageOperations.graphql, apps/web/src/types/pool.ts, packages/fake-data/src/fakePoolAdvertisements.ts, packages/fake-data/src/fakePools.ts
🤖 Resolves #6636.
This PR removes the description column from the pool database table as well as any associated references in the codebase.
This changes two UI components where the description has been removed.
The description for all pools on the production site is empty so it is not currently rendered anyway.
The description for all pools on the production site is empty so it is not currently rendered anyway and because there are no active talent recruitment processes either, those components are not rendered either.
1. Run `refresh_api.sh`
2. `npm run codegen`
3. `npm run build:fresh`
4. `npm run storybook`
5. Ensure no build errors
6. Ensure *description* value does not render in `PoolCard` …
=> [Debt] Removes pool description

apps/web/src/pages/Applications/MyApplicationsPage/components/ApplicationCard/utils.ts, packages/date-helpers/src/date.test.ts, packages/date-helpers/src/index.ts, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/dateMessages.ts
🤖 Resolves #6649.
This PR standardizes the date/time format of the `ApplicationCard` component and adds missing translation for some strings that were outside of the extraction process previously.
2. Apply to various pools at with different closing dates (you will likely need to adjust the closing date value manually in the database)
3. Verify date formats and related strings are formatted correctly and are translated in French
=> [Fix] Updates date format and related strings

apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicantDashboardPage/components/QualifiedRecruitments/QualifiedRecruitmentStatus.tsx
🤖 Resolves #6835
This PR removes the hard coded pool names.
1. Set an application to APPLICATION_REVIEW status
2. Navigate to your dashboard
3. Suspend your application and check the dialog
4. Restart your application and check the dialog
=> [Fix] Switch to variable strings for pool name

apps/web/src/components/Layout/Layout.tsx, apps/web/src/components/Layout/LogoutButton.tsx, apps/web/src/components/NavMenu/IAPNavMenu.tsx, apps/web/src/hooks/useBreadcrumbs.ts, apps/web/src/lang/fr.json, apps/web/src/pages/Auth/LoginPage/LoginPage.tsx, apps/web/src/pages/Auth/RegisterPage/RegisterPage.tsx, apps/web/src/pages/Home/IAPHomePage/components/ApplyLink.tsx, packages/auth/src/components/RequireAuth.tsx
🤖 Progresses (but does not close) #6887 
> __Note__
I'll put a second PR through with the copy changes later.
This branch customizes the login experience for the IAP.
I added the "personality" search param that can activate IAP specific theme, copy, and behaviour.  This is used to change the login and nav experiences.  We may want to eventually consolidate the layout and nav components between the main site and IAP now that there's leakage between them.
Build the site then test that the AC (other than copy changes) are met.  Note that we decided to reuse the same pages and URLs and not create new pages.
=> [Feature] IAP login

README.md
This PR updates the root `README.md` file.
- links `maintenance/README.md` using markdown
- changes a few sentences for consistency
- removes **tc-report** historic details
=> [Docs] Updates README.md

apps/web/src/pages/Home/IAPHomePage/Home.tsx
🤖 Resolves #7095.
This PR fixes a button on the IAP home page that was hidden when browsing with Firefox.
1. Navigate to `/indigenous-it-apprentice/` using Firefox browser
2. Ensure **Apply Now** button is visible in hero section
=> [Bug] Fixes button in Firefox

apps/web/src/lang/crg.json, apps/web/src/lang/crk.json, apps/web/src/lang/fr.json, apps/web/src/lang/mic.json, apps/web/src/lang/ojw.json, apps/web/src/pages/Home/IAPHomePage/Home.tsx, apps/web/src/pages/Home/IAPHomePage/components/Dialog/ApplyDialog.tsx
🤖 Resolves #6912.
This PR changes "Program" to be sentence case in English on the IAP home page.
1. Navigate to `/en/indigenous-it-apprentice/`
2. Observe instances of "The program", "the program", and "this program"
3. Ensure there are no instances of "The Program", "the Program", or "this Program" (including in any linked dialog instances)
4. Ensure all of the changed strings appear as they did before in French, Western Ojibwe, Michif, Mi'kmaq, and Plains Cree
=> [Bug] Updates "program" to sentence case

apps/web/src/components/Layout/LogoutButton.tsx
🤖 Resolves #6487 
Fixes an alignment issue where the logout button was off by `1px`.
The button had padding assigned by default, this removes that so it can line up with the other links in the nav properly.
2. Login and confirm the "Logout" button lines up with other links
=> [Fix] Nav button alignment

SECURITY.md
🤖 Resolves #1469.
This PR adds a security policy document to the repository.
1. Read security policy and ensure it makes sense.
=> [Docs] Adds security policy

CONTRIBUTING.md
🤖 Resolves #1467.
This PR adds a contributor guide for our GitHub repository.
1. Review the contributor guide file and make sure it makes sense!
=> [Docs] Adds a contributor guide

apps/web/src/components/UserProfile/UserProfile.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx, apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx, apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx, apps/web/src/pages/Profile/ResumeAndRecruitmentPage/components/ResumeAndRecruitment.tsx, apps/web/src/pages/Users/UserInformationPage/UserInformationPage.tsx, packages/ui/src/components/TableOfContents/AnchorLink.tsx, packages/ui/src/components/TableOfContents/List.tsx, packages/ui/src/components/TableOfContents/Navigation.tsx, packages/ui/src/components/TableOfContents/Sidebar.tsx, packages/ui/src/components/TableOfContents/TableOfContents.stories.tsx, packages/ui/src/components/TableOfContents/Wrapper.tsx, packages/ui/src/components/TableOfContents/index.ts
🤖 Resolves #6990 
Updates the table of contents to support nesting. As well, adjusts the spacing to match the mock up.
In order to support nesting, we must now the new sub components `List` and `ListItem`. This allows us to nest lists as deep as is reasonable.
```tsx
<TableOfContents.Wrapper>
<TableOfContents.Navigation>
<TableOfContents.List>
<TableOfContents.ListItem>
<TableOfContents.AnchorLink id="main-section">
Main Section
</TableOfContents.AnchorLink>
<TableOfContents.List>
<TableOfContents.ListItem>
<TableOfContents.AnchorLink id="sub-section">
Sub-Section
</TableOfContents.AnchorLink>
</TableOfContents.ListItem>
</TableOfContents.List>
</TableOfContents.ListItem>
</TableOfContents.List>
</TableOfContents.Navigation>
<TableOfContents.Content>
<TableOfContents.Section …
```
=> [Feature] Support nesting table of contents

documentation/definition-of-done.md
This PR updates the Definition of Done document to include items that closer mirror what is actually being considered currently. Suggestions are very welcome!
1. Review and ensure copy in `definition-of-done.md` file makes sense.
=> [Docs] Updates `definition-of-done.md`

apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/poolAdvertisementOperations.graphql
🤖 Resolves #7219 
Updates the pool contact email on the job poster to use the pool teams contact email address. Hidden if it is not set (unlikely since it is required).
2. Navigate to a job poster
3. Confirm the contact email matches the pool team's set email
=> [Fix] Update pool contact email

.github/pull_request_template.md
This PR adds a Deployment section to the pull request template.
=> [Docs] Adds Deployment section to pull request template

.vscode/project-words.txt, api/app/GraphQL/Validators/DigitalContractingPersonnelRequirementInput.php, api/app/GraphQL/Validators/DigitalContractingQuestionnaireInput.php, api/app/Models/DigitalContractingPersonnelRequirement.php, api/app/Models/DigitalContractingPersonnelSkill.php, api/app/Models/DigitalContractingQuestionnaire.php, api/app/Policies/DigitalContractingQuestionnairePolicy.php, api/app/Rules/ArrayConsistentWithDetail.php, api/app/Rules/ScalarConsistentWithDetail.php, api/config/rolepermission.php, api/database/factories/DigitalContractingPersonnelRequirementFactory.php, api/database/factories/DigitalContractingPersonnelSkillFactory.php, api/database/factories/DigitalContractingQuestionnaireFactory.php, api/database/helpers/DirectiveFormsApiEnums.php, api/database/migrations/2023_07_19_140947_create_digital_contracting_questionnaires_table.php, api/database/seeders/DatabaseSeeder.php, api/database/seeders/DigitalContractingQuestionnaireSeeder.php, api/graphql/directiveForms.graphql, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/DigitalContractingQuestionnaireTest.php, api/tests/Unit/ArrayConsistentWithDetailRuleTest.php, api/tests/Unit/ScalarConsistentWithDetailRuleTest.php, documentation/directive-forms.md
🤖 Resolves #7273
This branch adds the backend work to create, update, and delete the Digital services contracting questionnaire.
- A basic policy was created to limit usage to platform admins for now.
- There's no frontend for this.  Use Graphiql to interact with the backend.
1. Reseed the roles and permissions
2. Refresh the GraphQL schema
3. Check that everything works:
<details>
<summary>CreateDigitalContractingQuestionnaire</summary>
```graphql
mutation CreateDigitalContractingQuestionnaire($questionnaire: DigitalContractingQuestionnaireInput!) {
createDigitalContractingQuestionnaire(
digitalContractingQuestionnaire: $questionnaire
) {
id
authoritiesInvolved
authorityInvolvedOther
branchOther
businessOwnerEmail
businessOwnerJobTitle
businessOwnerName
commodityType
commodityTypeOther …
```
=> [Feature] Contracting questionnaire backend

packages/i18n/src/lang/fr.json
🤖 Resolves #7382 
Solve the broken Intl string. 
Seems to have just been the wrong variable. 
1. Create an application
2. Switch to French
3. No Intl errors
=> [Bug] Stepper Intl fix

apps/web/src/lang/fr.json, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #7428.
This PR updates the **description of pool recruitment, paragraph two** by removing a few words.
1. Navigate to a pool advertisement page
2. Open **What are pool recruitments?** accordion
3. Verify copy in English and French
=> [Copy] Updates description of pool recruitment paragraph two

apps/web/src/components/EmploymentEquity/dialogs/IndigenousDialog.tsx, apps/web/src/lang/fr.json
🤖 Resolves #7358
Switching "Self-Declare" to sentence case
1. Navigate to `/en/users/:id/profile` and open the self-declare modal
2. Observe sentence cased "self-declare"
3. Switch to French and see nothing changed
=> [Copy] Self-declare to sentence case

apps/e2e/cypress/e2e/admin/auth.cy.js
🤖 Resolves #4649 
Removes an unused test and its comments.
1. Confirm code is removed
=> [Debt] Remove unused comments/code `auth.spec.js`

apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
🤖 Resolves #7466.
This PR fixes the alignment of unordered list items on the `ApplicationSuccessPage`.
1. Complete an application
2. Observe left alignment of the unordered list items in both English and French
3. Repeat using Chrome, Firefox, and Safari
=> [Fix] `ApplicationSuccessPage` unordered list item alignment

apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
🤖 Resolves #7586 
Ups the top margin to space it out a bit.
Lol
1. Navigate to `/applications/:application-id/skills`
2. Click Submit and continue button
3. Observe spacing is now present
=> [Bug] Separator margin for application

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql
This PR fixes some of the content of the deprecated reasons and adds issue numbers for work on removing the deprecated queries and fields.
1. Read through and make sure reasons make sense (unlike me in #7641 🥴)
=> [Fix] Update GraphQL deprecated reasons

packages/ui/src/components/Link/MenuLink.tsx
🤖 Resolves #7739
Makes changes to the styling of the active link. 
Bolding was already present, as was the aria-current. 
Text decoration and colour changed per issue. 
1. Open up the app base side
2. Play with menu
=> [Feature] Style change active link in the navigation menu

apps/web/src/lang/fr.json, apps/web/src/pages/SearchRequests/RequestPage/RequestPage.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchHeading.tsx
🤖 Resolves #7718
Changes the copy on the search and a bit on the request pages. 
Needs to be sent for French translation
Needs design review after translations are received 
1. Navigate to search page and observe copy lines up with issue's request, no errors appear present
=> [Copy] Update search page

apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #7927 
Resolve layout issue with apply button on mobile view. 
1. Navigate to pool poster
2. Resize and observe
=> [Bug] Pool poster mobile view

apps/web/src/lang/crg.json, apps/web/src/lang/crk.json, apps/web/src/lang/fr.json, apps/web/src/lang/mic.json, apps/web/src/lang/ojw.json, apps/web/src/pages/Home/IAPHomePage/Home.tsx, apps/web/src/pages/Home/IAPHomePage/components/Dialog/ApplyDialog.tsx
🤖 Resolves #7995.
This PR updates copy on the IT Apprenticeship Program for Indigenous Peoples home page. 
The Apply Now dialog and Step 3 were missing a period at end of a sentences in some languages. Also, the time frame sentence changed from 3-5 to 5-10 business days.
1. Verify strings are updated in all languages.
=> [Copy] Updates time frame copy from 3-5 to 5-10

documentation/definition-of-ready.md
This PR removes a colon from a title.
=> [Docs] Updates definition-of-ready.md

apps/web/src/lang/fr.json, apps/web/src/pages/Skills/SkillShowcasePage.tsx
🤖 Resolves #8103.
This PR updates some copy on the skill showcase page.
1. Navigate to `/applicant/profile-and-applications/skills/showcase`
2. Observe copy changes
=> [Copy] Updates skill showcase copy

apps/web/src/components/UserProfile/SkillShowcaseSection.tsx
Fixes a bug where admins could edit a users top behavioral skills.
=> [Fix] Editable behavioral skills

apps/e2e/package.json, apps/web/package.json, apps/web/src/components/Layout/Layout.tsx, apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx, apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx, apps/web/src/components/SkillDialog/SkillSelection.tsx, apps/web/src/components/SkillPicker/FamilyPicker.tsx, apps/web/src/components/UserProfile/ExperienceByTypeListing.tsx, apps/web/src/components/UserProfile/ExperienceSection.tsx, apps/web/src/components/UserProfile/PrintExperienceByType/PrintExperienceByType.tsx, apps/web/src/pages/Pools/BrowsePoolsPage/components/OngoingRecruitmentSection/OngoingRecruitmentSection.tsx, apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx, apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx, apps/web/src/utils/poolCandidateCombinedStatus.tsx, apps/web/src/utils/skillUtils.ts, apps/web/src/validators/pool/assessmentPlan.ts, package-lock.json, package.json, packages/auth/src/components/RequireAuth.tsx, packages/eslint-config-custom/package.json, packages/forms/src/components/Combobox/Combobox.tsx, packages/forms/src/components/Combobox/utils.ts, packages/forms/src/components/Select/MultiSelectFieldBase.test.tsx, packages/helpers/src/utils/util.ts
🤖 Resolves #7205 
This updates `prettier` to the latest release as well as fixing any violations of new/changed rules.
1. Lint the project `npm run lint -- --force`
2. Confirm it succeeds with no fails
3. Confirm the project still builds and functions as expected `npm run dev`
=> [Dep] Bump prettier to v3

api/app/Policies/AssessmentStepPolicy.php, api/app/Policies/PoolPolicy.php, api/app/Policies/UserPolicy.php
🤖 Resolves #8220 
Rewrites some policies to have safer fall through conditions
1. Look over the policies and confirm the changes make sense.
2. Confirm all tests pass.
=> [Debt] Safer policy fall-throughs

.vscode/project-words.txt, apps/web/src/components/ExperienceSkillFormDialog/ExperienceSkillFormDialog.tsx, apps/web/src/components/PoolCandidatesTable/PoolCandidateTableFilterDialog.tsx, apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx, apps/web/src/components/Table/ApiManagedTable/TableFooter.tsx, apps/web/src/components/Table/ApiManagedTable/useFilterOptions.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationQuestionsPage/components/AnswerInput.tsx, apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchFilterAdvice.tsx, apps/web/src/pages/SkillFamilies/CreateSkillFamilyPage.tsx, apps/web/src/pages/Skills/CreateSkillPage.tsx, apps/web/src/pages/Skills/ImproveBehaviouralSkillsPage.tsx, apps/web/src/pages/Skills/ImproveTechnicalSkillsPage.tsx, apps/web/src/pages/Skills/TopBehaviouralSkillsPage.tsx, apps/web/src/pages/Skills/TopTechnicalSkillsPage.tsx, apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.test.tsx, apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.tsx, packages/eslint-config-custom/index.js, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #3667.
This PR enforces `intl` descriptions.
1. `npm run lint -- -- --max-warnings=0`
2. Observe no warnings or errors for `intl` strings without a description
=> [Tooling] Enforces `intl` descriptions

api/config/feature.php
🤖 Resolves #8420.
This PR fixes an incorrect key for directive forms.
1. Ensure app continues to work as before
=> [Fix] Incorrect key for directive forms

.github/ISSUE_TEMPLATE/⚙️-new-component.md
This PR changes labels for new component GitHub issue template that are no longer used and replaces them with the `feature` label for consistency.
=> [Docs] Changes labels for new component GitHub issue template

packages/forms/src/components/Repeater/ActionButton.tsx, packages/forms/src/components/Repeater/Repeater.stories.tsx, packages/forms/src/components/Repeater/Repeater.test.tsx, packages/forms/src/components/Repeater/Repeater.tsx
🤖 Resolves #8363 
This branch updates the repeater to add some features needed by the assessment builder page.
Note that ActionButton has been factored out to its own file and been hook up with ForwardRef for proper focus management.
Open up the storybook repeater story and check the AC on the issue.
=> [Feature] Repeater updates for assessment builder page

api/tests/Feature/Mutation/UpdateUserTeamRolesTest.php
🤖 Resolves #8303
Resolve the failing test. 
Hard to replicate but the cause seemed straightforward, varying order in results. Worked around this by rewriting the assertion to not be order dependent. 
1. Tests pass locally
2. CI succeeds 5 times
=> [Tests] Fix `testAllTeamMembersCanBeReadFromResponse`

apps/web/src/lang/fr.json, apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx, apps/web/src/pages/SearchRequests/RequestConfirmationPage/components/RequestConfirmationPrintDocument.tsx
🤖 Resolves #8016
Improve the printing when a user prints their request confirmation. 
Just ♻️ for the most part from other implementations. 
1. Submit request and reach confirmation page
2. Print in both English and French
=> [Bug] Improve request confirmation printing

apps/web/src/lang/fr.json
🤖 Resolves #8766.
This PR updates a the term in French for **work stream** to be consistent with other instances of the term.
1. Ensure codebase has no instances of **flux**
=> [Copy] Updates French copy Flux to Volet

apps/web/src/lang/fr.json, apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/ApplicationActions.tsx
🤖 Resolves #8764.
This PR removes unused `ManageAvailabilityAction` code.
1. Confirm no references in the codebase to `ManageAvailabilityAction`
=> [Debt] Removes unused `ManageAvailabilityAction`

packages/auth/src/components/AuthenticationContainer.tsx
🤖 Resolves #8845
This branch updates the memoized refresh function to access the refresh token from localstorage instead of just using the first token frozen from when it was memoized.
> [!IMPORTANT]
Make sure you're testing with SIC and a prod build
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/sign-in-canada.md
1. Rebuild the app with SIC and prod mode.
2. Log in, note the refresh token provided.
3. Wait until the access token expires and trigger a refresh.  Ensure that the first refresh token was used and a second refresh token was provided.
4. Wait until that access token expires and trigger a refresh.  Ensure that the second refresh token was used and a third refresh token was provided.
It's probably  worth running through the original checklist again:
=> [Fix] Have memoized refresh function access localstorage directly

apps/web/src/lang/fr.json, apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx, apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
🤖 Resolves #8752 
- Changes "Pool Name" to "Name" on pool table, and now displays just the pool name.
- Moves group and level column order after name.
- Adds new sort-able stream column (after group and level)
1. Rebuild app `npm run build`.
2. Login as `admin@test.com`.
3. Go to pool table on admin side.
4. Ensure all [A/C](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8752) is met
=> [Feature] Update pool table

apps/web/src/pages/Pools/ViewPoolPage/components/DeleteProcessDialog.tsx
🤖 Resolves #8461
Changes the colour to the error selection
1. Navigate to a draft pool's information page
2. Observe delete button
=> [Bug] Change delete process link text colour

apps/web/src/components/EducationRequirements/EducationRequirements.tsx
🤖 Resolves #8905 
Adds the AS education requirement (same as PM).
3. Publish a pool with the AS classification (or us existing one)
4. View the advertisement
5. Confirm AS education requirements display as [outlined in the ticket](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8905)
=> [Feature] Adds AS education requirement

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql
🤖 Resolves {issue #}
Add more careful permission check for ScreeningQuestionResponse
Ask @tristan-orourke for details and testing advice
=> [Bugfix] Add more careful permission check for ScreeningQuestionResponse

api/graphql/schema.graphql
🤖 Resolves #9142
Resolve the bug hopefully by updating the casing on the referenced model. 
1. Works locally
2. Works in the UAT environment
=> [Bug] Update casing for directive on bookmarking mutation

apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInfo.stories.tsx
🤖 Resolves #9128.
This PR updates arg from `pool` to `poolQuery` to match component prop from `ApplicationInfomation` in `ApplicationInfo` story.
1. `npm run storybook:web`
2. Navigate to `ApplicationInfo` story
3. Observe working story
=> [Fix] Updates arg to match component prop in `ApplicationInfo` story

.vscode/settings.json
Here's a little branch to add a terminal shortcut for the maintenance container in VS Code.  I've found it useful, you might too.
Feel free to add to this branch with extra settings if you're a OSX or Win person.
=> [Tooling] Maintenance terminal shortcut

infrastructure/bin/substitute_file.sh
🤖 Resolves #9325
This branch adds a fix for the script that substitutes variables into config files.  It was changed to accept a list of variables to substitute for the FPM changes but it stopped properly handling the case where no variables are specified.  This is fixed here.
1. Deploy branch to Azure (currently deployed on DEV)
2. Confirm Azure config is properly substituted (just $NGINX_PORT and $ROBOTS_FILENAME)
3. Confirm config.js is properly substituted (all variables)
=> [Fix] Add test for empty variable

apps/web/src/lang/fr.json, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
🤖 Resolves #9314.
This PR adds candidate status section to the candidate page.
2. Navigate to`/admin/candidates/:candidate-id/application`
3. Verify section renders
4. Verify ability to change the status and expiry date
=> [Feature] Adds candidate status section

apps/web/src/components/EmploymentEquity/EquityOptions.tsx, apps/web/src/components/Profile/utils.ts, apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/DirectiveForms/DigitalServicesContractingQuestionnaire/sections/PreambleSection.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInformation.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx, apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/navigationMessages.ts
🤖 Resolves #9388.
This PR consolidates **diversity, equity, and inclusion** strings where possible.
2. Navigate to pages using string
3. Verify string remains the same in English (**Diversity, equity, and inclusion**) and French (**Diversité, équité et inclusion**) and without a period in French.
=> [Copy] Consolidates diversity, equity, and inclusion strings

apps/web/src/components/EducationRequirements/EducationRequirements.tsx, apps/web/src/components/Layout/MaintenanceBanner.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx, packages/ui/src/components/Board/Board.tsx, packages/ui/src/components/Pill/Pill.stories.tsx, packages/ui/src/components/Pill/Pill.tsx
🤖 Resolves #5807 
Fixes a number of minor colour contrast issues that were detected during a review.
During the full review of dark mode, there were hardly any issues found and most were introduced after dark mode was completed so high five to designers and reviewers! 🎉 .
So, I just decided to wrap them all up into one small PR.
1. Build the app
2. Navigate to the spots referenced in [the review comment](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5807#issuecomment-1946967169)
3. Confirm those errors no longer exist
=> [Fix] Dark mode colour contrast

apps/web/src/pages/Users/UpdateUserPage/components/EditTeamRoleDialog.tsx, apps/web/src/pages/Users/UpdateUserPage/components/RemoveIndividualRoleDialog.tsx, apps/web/src/pages/Users/UpdateUserPage/components/RemoveTeamRoleDialog.tsx
🤖 Resolves #9382 
Resolves the screen-reader friendly text per Eric's suggestion. 
1. Navigate to the edit user page
2. Inspect the buttons in the tables
=> [Accessibility] User role table button text

apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
🤖 Resolves #9414 
Reuses the logic to combine responses from RoD view to be used pre-RoD
Copied logic over.
Tried extracting it to a file to be imported by both instances, but was getting odd type errors that were easily resolved by just pasting the code into the file rather than importing 🤷 
1. Not sure how to best test this... Screening questions and their responses are seeded quite differently now
=> [Bug] Viewing screening question responses for applications

apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
This PR adds a missing import for `unpackMaybes` that somehow made it through tests for #9394.
1. GitHub workflows all pass
=> [Fix] Adds missing import for `unpackMaybes`

apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx, apps/web/src/pages/Applications/ApplicationEducationPage/LinkCareerTimeline.tsx
🤖 Resolves #9377.
This PR updates application education requirements step headings to be semantically correct.
2. Create an application
3. Navigate to the education requirements step
4. Run [axe DevTools](https://www.deque.com/axe/devtools/) full page scan
5. Verify no errors
=> [Accessibility] Updates application education requirements step heading level

apps/web/src/lang/fr.json, apps/web/src/messages/poolCandidateMessages.ts, apps/web/src/utils/poolCandidate.ts, apps/web/src/utils/poolCandidateCombinedStatus.tsx, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/commonMessages.ts, packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #9390.
This PR consolidates **Removed** string to use a single source of truth.
1. Search codebase for string **Removed**
2. Verify there is once source of truth
=> [Copy] Consolidates Removed string

apps/web/src/lang/fr.json, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/FinalDecisionDialog.tsx, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #9391.
This PR consolidates **Final assessment decision** string to use a single source of truth.
1. Search codebase for string **Final assessment decision**
2. Verify there is once source of truth
=> [Copy] Consolidates Final assessment decision string

apps/e2e/package.json, apps/web/package.json, apps/web/src/components/Layout/Layout.tsx, apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx, apps/web/src/components/SkillBrowser/utils.ts, apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/SkillSummaryTable.tsx, apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/SkillsQuickSummary.tsx, apps/web/src/pages/Pools/BrowsePoolsPage/components/OngoingRecruitmentSection/OngoingRecruitmentSection.tsx, apps/web/src/utils/skillUtils.ts, apps/web/src/utils/testData.ts, apps/web/src/validators/pool/assessmentPlan.ts, package-lock.json, package.json, packages/auth/src/components/RequireAuth.tsx, packages/eslint-config-custom/package.json, packages/forms/src/components/Combobox/Combobox.tsx, packages/forms/src/components/Combobox/utils.ts
🤖 Resolves #9127 
Bumps prettier and fixes new problems that arose. 
1. Run lint `npm run lint -- --force`
2. Confirm success
3. Confirm all versions of prettier are on the latest `3.2.5`
=> [Dep] Bump `prettier` to `3.2.5`

api/_lighthouse_ide_helper.php, api/composer.json, api/composer.lock, api/programmatic-types.graphql, api/schema-directives.graphql
🤖 Resolves #9494 
Switch to the recommended package as the other is abandoned. 
Appears to work identically so nothing really changed 🤷 
1. Can refresh API locally, no warnings appear
2. Tests pass in CI
3. You can log in and out normally
=> [Dependencies] Switch to jwt-library

apps/web/src/pages/Applications/ApplicationCareerTimelinePage/ApplicationCareerTimelinePage.tsx, apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx, apps/web/src/pages/Applications/ApplicationProfilePage/ApplicationProfilePage.tsx, apps/web/src/pages/Applications/ApplicationQuestionsPage/ApplicationQuestionsPage.tsx, apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx, apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/ApplicationSelfDeclarationPage.tsx, apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx, apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx, apps/web/src/pages/Applications/ApplicationWelcomePage/ApplicationWelcomePage.tsx, apps/web/src/utils/applicationUtils.ts, packages/ui/src/components/Stepper/Step.tsx, packages/ui/src/components/Stepper/Stepper.tsx, packages/ui/src/components/Stepper/testUtils.ts, packages/ui/src/components/Stepper/types.ts, packages/ui/src/components/Stepper/utils.ts
🤖 Resolves #9550 
Makes some minor tweaks to the stepper component that appears within applications.
We used some hardcoded values since we could not use opacity easily. @substrae provided the values used.
- Light: `#C5C6C7`
- Dark: `#7C89A3`
3. Start an application
4. Confirm the stepper matches [the mockup](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-26&mode=design&t=ySGCbzrNufVcF3tN-0)
=> [Style] Update stepper

apps/e2e/cypress/e2e/talentsearch/submit-application-iap.cy.ts, apps/playwright/tests/applicant/application.spec.ts, apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
🤖 Resolves #9551 
Adds the survey link to the application success page as well as adjusting some copy for links.
3. Complete an application
4. Confirm the links in the list have the copy updated
5. Confirm the new survey link exists and link to the proper English and French pages
=> [Feature] Add survey link

apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #9655 
Avoids rendering an accordion on the job poster which references an Inclusivity Statement which doesn't exist yet.
=> Avoid rendering equity statement accordion for now

maintenance/README.md
🤖 Resolves #9638.
This PR makes a few updates to the `maintenance/README.md` mostly related to outdated documentation.
1. Read `maintenance/README.md`
2. Verify instructions still make sense
=> [Docs] Updates `maintenance/README.md`

apps/web/src/components/PoolCandidatesTable/poolCandidateCsv.tsx, apps/web/src/lang/fr.json
🤖 Resolves #9679.
This PR consolidates **Education requirement** string so that it is translated the same in French.
1. Search codebase for instances **Education requirement** string
2. Verify there is only one instance of **Education requirement** string
=> [Copy] Consolidates Education requirement string

api/app/Http/Middleware/AuditQueryMiddleware.php
🤖 Resolves #9705 
This PR formats the admin requests into single line
1. Open up laravel.log file
2. do some admin operations like going to admin dashboard and click on candidate search etc.,
3. Observe the logs 
Out of scope 
Slow query logging
=> [tooling] make the request dump into single query

.github/dependabot.yml
Should fix an issue where dependabot is not updating our `pnpm-lock.yaml` file.
- https://github.com/dependabot/dependabot-core/issues/5226#issuecomment-1179434437
Merge and :pray:
=> [Fix] Dependabot with `pnpm`

.github/dependabot.yml, apps/e2e/cypress/e2e/api/artisan-commands.cy.ts, apps/web/src/assets/css/app.css, apps/web/src/components/Footer/Footer.tsx, apps/web/src/components/Layout/IAPLayout.tsx, apps/web/src/components/Layout/Layout.tsx, apps/web/src/components/Profile/components/DiversityEquityInclusion/CommunityIcon.tsx, apps/web/src/components/UserProfile/ExperienceByTypeListing.tsx, apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx, packages/forms/src/components/Checkbox/Checkbox.tsx, packages/forms/src/components/Combobox/Multi.tsx, packages/ui/src/components/Card/Card.tsx
🤖 Resolves #9798.
This PR removes cruft from the codebase.
1. Verify app runs without change
2. Verify no changes to UI
=> [Debt] Removes cruft

apps/web/src/components/AssessmentResultsTable/testData.ts, apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.stories.tsx
Oops, I broke some stories with #9841 
Switched to rendering from snapshot field but need it either present but null, or present correctly typed. So I did that 
1. Stories fixed
2. Assessment results table, and screening decision dialog stories
=> [Fix] Assessment results related stories

apps/web/src/components/NavMenu/NavMenu.tsx
I forgot to add this in the dialog PR and it got merged :flushed: 
1. Set the notifications feature flag to false
2. Build
3. Confirm the alert icon does not appear in the header
=> [Fix] Hide notifications behind feature flag

apps/web/src/lang/fr.json, apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx, apps/web/src/pages/Applications/ApplicationLayout.tsx, apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx, apps/web/src/pages/Home/ExecutiveHomePage/ExecutiveHomePage.tsx, apps/web/src/pages/Home/HomePage/HomePage.tsx, apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx, apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/IndexPoolCandidatePage.tsx, apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx, apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx, apps/web/src/pages/Pools/PoolLayout.tsx, apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineAndRecruitment.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx, apps/web/src/pages/Profile/ProfilePage/ProfilePage.tsx, apps/web/src/pages/ProfileAndApplicationsPage/ProfileAndApplicationsPage.tsx, apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx, apps/web/src/pages/SearchRequests/SearchPage/SearchPage.tsx, apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx, apps/web/src/pages/Skills/SkillPage.tsx, apps/web/src/pages/Skills/SkillShowcasePage.tsx, apps/web/src/pages/Skills/UpdateUserSkillPage.tsx, apps/web/src/pages/Teams/CreateTeamPage/CreateTeamPage.tsx, apps/web/src/pages/Teams/IndexTeamPage/IndexTeamPage.tsx, apps/web/src/pages/Teams/TeamLayout.tsx, apps/web/src/pages/Users/IndexUserPage/IndexUserPage.tsx
🤖 Resolves #2408 
- Adds a description to `SEO` component using the page subtitle, if it exists.
1. Go to changed pages and inspect it. Ensure there is a `<meta name="description">` with the `content` value including the page description.
=> [Copy] page descriptions

.github/dependabot.yml
This is a test to see if `pnpm` + merge groups is the issue with dependabot not updating the lock file :woman_shrugging:
=> [Fix] Remove merge groups

.github/dependabot.yml
Reverts GCTC-NTGC/gc-digital-talent#9915
This was not the issue and we do want merge groups
=> Revert "[Fix] Remove merge groups"

apps/web/src/lang/fr.json
🤖 Resolves #9914.
This PR updates **Back to** translations in French to be consistent.
1. Verify translations in [issue comment](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9914#issuecomment-2034827196) match those in code
2. Verify instances of translations appear in app
=> [Copy] Updates Back to translations in French

apps/web/src/components/PoolCandidatesTable/tableMessages.ts, apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json
🤖 Resolves #8896.
This PR updates **View** translations in French to be consistent.
1. Verify translations in [issue comment](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8896#issuecomment-2034840057) match those in code
2. Verify instances of translations appear in app
=> [Copy] Updates View translations in French

package.json, pnpm-lock.yaml
Dependabot :robot: is giving us a hard time about this dep saying it is up to date when it isn't. So, lets try manually bumping it to see if bad bot becomes good bot :woman_shrugging: 
1. Install `pnpm i`
2. Confirm turbo scripts function as expected
=> Bump turbo

packages/fake-data/src/skillFamilies.json, packages/fake-data/src/skills.json
🤖 Resolves #10003.
This PR fixes typos in fake data.
1. Open `packages/fake-data/src/skillFamilies.json` and `packages/fake-data/src/skills.json`
2. Verify no typos in any of the `name`, `description`, or `keywords` values
=> [Copy] Fixes typos in fake data

apps/web/package.json, apps/web/src/components/Layout/SitewideBanner.tsx, apps/web/src/components/PoolStatusTable/PoolStatusTable.tsx, apps/web/src/utils/applicationUtils.ts, apps/web/src/utils/poolCandidate.ts, apps/web/src/validators/process/closingDate.ts, packages/date-helpers/package.json, packages/date-helpers/src/date.test.ts, packages/date-helpers/src/index.ts, packages/forms/package.json, packages/forms/src/components/DateInput/DateInput.stories.tsx, packages/forms/src/components/DateInput/DateInput.tsx, packages/forms/src/components/DateInput/utils.ts, pnpm-lock.yaml
🤖 Resolves #8886.
This PR updates `date-fns`, `date-fns-tz` to v3.
1. Verify all tests pass
2. Verify functions used still work as intended
=> [Debt] Updates `date-fns`, `date-fns-tz` to v3

apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx, apps/web/src/components/Profile/components/GovernmentInformation/GovernmentInformation.tsx, apps/web/src/components/SearchRequestTable/components/SearchRequestFilterDialog.tsx, apps/web/src/pages/Classifications/UpdateClassificationPage.tsx, apps/web/src/pages/Classifications/UpdateClassifictionForm.stories.tsx, apps/web/src/pages/Classifications/components/ClassificationTable.stories.tsx, apps/web/src/pages/Classifications/components/ClassificationTable.tsx, apps/web/src/pages/Departments/UpdateDepartmentForm.stories.tsx, apps/web/src/pages/Departments/UpdateDepartmentPage.tsx, apps/web/src/pages/Departments/components/DepartmentTable.stories.tsx, apps/web/src/pages/Departments/components/DepartmentTable.tsx, apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx, apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx, apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx, apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/utils.ts, apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx, apps/web/src/pages/Teams/CreateTeamPage/CreateTeamPage.tsx, apps/web/src/pages/Teams/CreateTeamPage/components/CreateTeamForm.tsx, apps/web/src/pages/Teams/UpdateTeamPage/UpdateTeamPage.tsx, apps/web/src/pages/Teams/UpdateTeamPage/components/UpdateTeamForm.test.tsx, apps/web/src/pages/Teams/UpdateTeamPage/components/UpdateTeamForm.tsx, apps/web/src/pages/Teams/operations.ts
🤖 Resolves #9714  
Updates the queries for root level `Classification` and `Department` to use fragment masking.
2. Navigate to the pages that use the affected queries
3. Confirm they still function as expected
=> [Feature] `Classification` and `Department` fragment masking

apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
🤖 Resolves #10039.
This PR updates post-application survey links.
1. Verify post-application survey links are updated to use new URLs
=> [Feature] Updates post-application survey links

.github/workflows/chromatic.yml
🤖 Resolves #9304.
This PR enables Chromatic Turbosnap.
1. 🤞
=> [Tooling] Enables Chromatic Turbosnap

apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/CareerTimelineAndRecruitmentPage.stories.tsx, apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/CareerTimelineAndRecruitmentPage.tsx, apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineAndRecruitment.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.stories.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.test.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx, apps/web/src/pages/Profile/ProfilePage/ProfilePage.stories.tsx, apps/web/src/pages/Profile/ProfilePage/ProfilePage.tsx, apps/web/src/pages/ProfileAndApplicationsPage/ProfileAndApplications.stories.tsx, apps/web/src/pages/ProfileAndApplicationsPage/ProfileAndApplicationsPage.tsx, apps/web/src/pages/Users/AdminUserProfilePage/AdminUserProfilePage.tsx, apps/web/src/pages/Users/UserInformationPage/UserInformationPage.tsx
🤖 Resolves #9712 
Adds fragment masking to top level user queries.
1. Build `pnpm dev`
2. Navigate to pages where queries were updated
3. Confirm they still function as expected
=> [Debt] `User` fragment masking

apps/web/src/components/SearchRequestFilters/FilterBlock.tsx, apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx, apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.stories.tsx, apps/web/src/pages/SearchRequests/ViewSearchRequestPage/ViewSearchRequestPage.stories.tsx
🤖 Resolves #10080.
This PR refactors and consolidates the `FilterBlock` component used on the admin single request page and the search request form.
1. Navigate to Request Information section of `/admin/talent-requests/:request-id`
2. Verify data is the same for small screen size or large screen size
3. Navigate to Summary of filters section of `/search/request`
4. Verify data is the same for small screen size or large screen size
=> [Fix] Refactors and consolidates `FilterBlock` component

apps/web/src/lang/fr.json, apps/web/src/pages/Auth/SignedOutPage/SignedOutPage.tsx
🤖 Resolves #10135.
This PR updates some of the copy on the signed out page.
1. Compare new copy to copy in issue #10135
2. Confirm copy matches new copy in issue #10135
=> [Copy] Updates detailed logout messages

apps/web/src/lang/fr.json, apps/web/src/pages/SearchRequests/SearchPage/components/EstimatedCandidates.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
🤖 Resolves #9419 
Makes the requested copy updates. 
1. Navigate to the "Find talent" page and observe copy in both languages
=> [Copy] Copy update on page Find talent

apps/web/src/lang/fr.json, apps/web/src/messages/processMessages.ts, apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/CoreRequirementsSection.tsx, apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/Display.tsx
🤖 Resolves #10229 
- Adds validation rule to ensure both values must be included to save changes.
- Adds adds specific location label for english and french values.
2. Create a new process
3. Ensure Core requirements section displays location fields correctly.
4. Ensure pool status at top of page is correct.
=> [Bug] Pool location validation

.github/ISSUE_TEMPLATE/:volleyball:-spike, .github/ISSUE_TEMPLATE/🏐-spike
Add an issue template for Spikes.
=> Create Spike template

apps/web/src/components/ApplicationCard/ApplicationCard.tsx, codecov.yml
🤖 Resolves #10213 
This ignores storybook files for code coverage reports.
1. Check code coverage report
2. Confirm stories are not counted
=> [Debt] Ignore stories in code coverage

apps/web/src/components/Pagination/Pagination.stories.tsx
🤖 Resolves #10193 
Refactors the `Pagination` story to the new format, fixing incorrect args at the same time.
1. Run storybook `pnpm run storybook`
2. Open the `Pagination` story
3. Confirm no errors in the console
=> [Fix] Pagination story

apps/playwright/tests/applicant/application.spec.ts
🤖 Resolves #10393 
Removes a flaky assertion that was superfluous. 
1. Run the test a few times `pnpm run e2e:playwright:chromium application.spec.ts`
2. Confirm it passes consistently
=> [Fix] Application e2e test

apps/web/src/lang/fr.json
This PR removes superfluous spaces in a French string.
=> [Fix] Removes superfluous spaces in French string

pnpm-lock.yaml
Seems dependabot messed up our lockfile, this regenerates and dedupes deps in it.
1. Confirm CI passes
=> [Fix] PNPM lockfile

api/app/Policies/PoolCandidatePolicy.php, apps/web/src/components/NotificationList/NotificationItem.tsx
🤖 Resolves #10691 
Moves the more action icon for notifications to the right of the card.
3. Ensure you have in app notifications enabled for application updates
4. Submit an application
5. Change the status of the submitted application to "qualified available"
6. Navigate to the notifcations page `/applicant/notificatons`
7. Confirm the more actions icon appears on the far right of the card
=> [Fix] Notification action icon alignment

apps/web/src/components/PoolCandidatesTable/poolCandidateCsv.tsx, apps/web/src/pages/Users/UserInformationPage/components/UserCandidatesTable/UserCandidatesTable.tsx, apps/web/src/pages/Users/UserInformationPage/components/UserCandidatesTable/helpers.tsx, packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #10700
Resolve the missing rendering
Refactoring of priority functions recently introduced `getPriorityWeight()` which was needed to grab the appropriate enum to display. Just needed to add it into places 
1. CSV renders with fields
2. Table not missing fields
CSV
Table
=> [Bug] Resolve category and availabilty rendering in CSV/table

apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/ApplicationPrintButton.tsx
🤖 Resolves #10613.
This PR updates the document title for the print actions for each case.
1. Navigate to a candidate's screening and assessment page
2. Download each of the candidate profile types with the print application button
3. Observe the filename for each case matches [this list](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10613#issuecomment-2155284124)
=> [Fix] Updates applicant document title

apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.stories.tsx, apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
🤖 Resolves #10770.
This PR fixes the `PoolTable` and `RequestForm` stories.
1. Observe `PoolTable` storybook renders without error
2. Observe `RequestForm` storybook renders without error
=> [Fix] `PoolTable`, `RequestForm` storybook stories

.github/workflows/chromatic.yml, .github/workflows/jest.yml, .github/workflows/lint.yml, .github/workflows/playwright.yml, .github/workflows/translations.yml, apps/web/src/components/Footer/Footer.tsx, package.json, pnpm-lock.yaml, turbo.json
🤖 Resolves #10607 
Upgrades turborepo to v2.
1. Install deps `pnpm i`
2. Run each script in the root `package.json` that uses `turbo`
3. Confirm they function as expected
=> [Debt] Upgrade turborepo

.github/workflows/chromatic.yml
🤖 Resolves #10847 
Disable turbosnap and go back to manual chromatic runs until styling is fixed.
1. Check chromatic workflow to confirm entire project has snapshots
=> [Temp] Disable turbosnap

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/UserVerifyEmailTest.php, apps/web/src/components/EmailVerification/EmailVerification.stories.tsx, apps/web/src/components/EmailVerification/EmailVerification.test.tsx, apps/web/src/components/EmailVerification/EmailVerification.tsx, apps/web/src/lang/fr.json
🤖 Resolves #10687 
This branch adds a reusable component that can allow a user to validate their email address.  The component doesn't yet appear in that app anywhere - only Storybook.
1. Open Storybook and navigate to EmailVerification / Contact Email
2. Compare to the AC in the issue
=> [Feature] Email verification component

apps/playwright/tests/admin/process-actions.spec.ts, apps/web/src/lang/fr.json, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #10555.
This PR updates Bilingual Language Requirements to include government letter codes.
1. Navigate to a process
2. Observe copy
=> [Feature] Updates Bilingual Language Requirements to include government letter codes

.github/workflows/chromatic.yml
Reverts GCTC-NTGC/gc-digital-talent#10848
=> Revert "[Temp] Disable turbosnap"

apps/web/src/pages/EmailVerificationPage/ProfileContactEmailVerificationPage.tsx
🤖 Resolves #10983.
This PR replaces one instance of the deprecated `data-h2-container` with `data-h2-wrapper`.
2. Verify no warnings appear in console from Hydrogen
=> [Debt] Replaces `data-h2-container` with `data-h2-wrapper`

infrastructure/bin/deploy.sh
🤖 Resolves #10627 
Adds the flag `--optimize-autoloader` to the compose install in the deploy script.
1. Run the deploy script
2. Confirm it runs (check for the `Generating optimized autoload files` message)
=> [Debt] Add autoloader optimize to deploy script

api/database/seeders/AssessmentResultTestSeeder.php, api/database/seeders/PoolCandidateTestSeeder.php, api/database/seeders/UserTestSeeder.php, api/tests/Feature/PoolCandidateSearchRequestPaginatedTest.php, apps/playwright/tests/admin/admin-workflows.spec.ts, apps/playwright/tests/admin/auth.spec.ts, apps/playwright/tests/login-logout.spec.ts
🤖 Resolves #10608.
This PR updates some of the first names, last names, and emails of users and pool candidates in the test seeders.
1. Run test seeders from scratch
2. Verify first names, last names, and emails of users and pool candidates in the test seeders meet the issue's acceptance criteria
=> [Feature] Updates seeder first names, last names, and emails

codecov.yml
This PR turns off PR comments by codecov. 
I'll get a different PR for adding as status check but the comments are annoying currently. 
This can go. 
I think this PR itself should not get any comment from codecov.
=> [Tooling] Turn off PR comments by codecov

.github/ISSUE_TEMPLATE/🦔-spike.md
This PR updates the Spike issue template to use the 🦔 icon, based on a popular [vote](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1719253400596459).
=> [Docs] Updates Spike issue template

documentation/linux-setup.md
🤖 Resolves #10940
This branch adds some documentation for setting up a local Linux or WSL environment with all the tooling need to run the app.
Spelling and grammar?  Confusing spots?  Suggestions for clarity and organization?   Factual errors?
=> [Docs] Linux documentation for local setup

apps/web/src/pages/Auth/RegistrationPages/EmployeeInformationPage/EmployeeInformationPage.tsx
🤖 Resolves #11215.
This PR adds alphabetical sorting to the classification group field on the employee registration form.
1. `pnpm dev:fresh`
2. Log in as a new user
3. Select "yes, I am a government employee"
4. Verify sort order of **Group** field is sorted alphabetically from A-Z in English and French
=> [Fix] Classification group alphabetical sorting

apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx
🤖 Resolves #11128.
This PR updates part of the description for the radio group section on Step 4 of application in English and French.
2. Navigate to http://localhost:8000/en/browse/pools
3. Apply for a process
4. On Step 4, verify description for the radio group section has been updated in English and French
=> [Copy] Updates description for radio group section on Step 4 of application

api/app/Generators/CsvGenerator.php, api/app/Generators/DocGenerator.php, api/app/Jobs/GenerateUserFile.php, api/app/Providers/AppServiceProvider.php, api/app/Traits/Generator/GeneratesFile.php
🤖 Resolves #11229 
This branch corrects a few issues with the async file downloads.
Issue: No error reported when something goes wrong with generation
Fix: Switch "catch exception" to "catch throwable"
Issue: A null education requirement causes CSV crash
Fix: Switch the method signature to accept a nullable parameter
Issue: An ampersand causes DOCX corruption
Fix: Set PHPOffice to escape illegal XML characters
1. Check out the first commit of this branch: 235b8f3231e299c4f8ea1f9d8ee887c5e2f34420 and rebuild
2. Manually set the `education_requirement_option` of a `pool_candidates` row to null in the database
3. Start the queue worker
4. Log into the app as a admin and try the "Download CSV" command for the edited pool candidate
5. Observe the error notification
1. Check out the head of …
=> [Bug] Fix some issues with async file downloads

apps/web/src/hooks/useRoutes.ts
This PR fixes the community routes. The way routes were composed was changed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11235 but didn't make it into the new community routes: https://github.com/GCTC-NTGC/gc-digital-talent/pull/11125.
@mnigh 😓
=> [Fix] Community routes

.github/workflows/chromatic.yml, .github/workflows/jest.yml, .github/workflows/lint.yml, .github/workflows/playwright.yml, .github/workflows/translations.yml, infrastructure/bin/deploy.sh, infrastructure/maintenance-container/Dockerfile, package.json
🤖 Resolves #11196.
Upgrades `pnpm` to the latest version.
1. Update `pnpm add -g pnpm` 
2. Clean module folders `make clean-modules`
3. Install dependencies `pnpm install`
4. Build `pnpm build`
5. Confirm everything works as expected
=> [Debt] Upgrades `pnpm` to v9.7.1

apps/web/src/lang/fr.json, packages/i18n/src/lang/fr.json
🤖 Resolves #11280.
This PR updates French copy mostly as part of the stepped application but includes changes to generic strings shared across the site.
2. Verify copy updates match those in the details section of the description for the linked issue.
=> [Copy] Updates French copy

apps/web/src/lang/fr.json, apps/web/src/pages/Skills/SkillShowcasePage.tsx
🤖 Resolves #11290.
This PR updates French copy (and one English string) related to the skill showcase.
2. Verify copy updates match those in the details section of the description for the linked issue.
=> [Copy] Updates French copy skill showcase

apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx
🤖 Resolves #11334.
This PR removes outdated code.
1. Verify app and tests run as they did before
=> [Debt] Removes outdated code

apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
🤖 Resolves #11337.
This PR removes outdated comments.
1. Verify app and tests run as they did before
=> [Debt] Removes outdated comments

documentation/copy notes.md, documentation/copy.md
Initial documentation of some generic copy guidelines for GC digital talent.
🤖 Resolves 
This .md file will be tracking some decisions and notes regarding copy on the platform. I plan to continue to add on to this as more things pop-up.
=> Create copy notes.md

.github/dependabot.yml
🤖 Resolves  #11329
Add a few more groups as requested
1. Nothing really, other than proofread
=> [Tooling] More dependabot groups

packages/fake-data/src/fakeSkills.ts, packages/fake-data/src/skillFamilies.json, packages/fake-data/src/skillFamilies.json.readme, packages/fake-data/src/skills.json, packages/fake-data/src/skills.json.readme
🤖 Resolves #11293.
This PR updates the fake skills and skill families data to match what is currently on the production site. It also simplifies the `getStaticSkills` function.
2. Navigate to `SkillBrowser` story
3. Verify skill families and skills are the same as on the [production search page](https://talent.canada.ca/en/search) Skills selection
=> [Debt] Updates static skills and skill families use by `fake-data`

api/database/seeders/ClassificationSeeder.php, apps/web/src/components/EducationRequirements/EducationRequirements.tsx, apps/web/src/lang/fr.json, apps/web/src/utils/educationUtils.tsx
🤖 Resolves #11311 
Adds education requirements for the CR classification that currently does not exist but will in the future.
3. Create a classification with group "CR"
4. Create a pool using the new classification
5. Confirm it has the proper education requirements on:
- Edit pool page
- Pool advertisement
- Application
=> [Feature] Add education requirements for CR classification

api/app/Http/Resources/UserResource.php, api/app/Models/PoolCandidate.php, api/app/ValueObjects/ProfileSnapshot.php, api/tests/Feature/SnapshotTest.php
🤖 Resolves #10913 
Adds a version number to snapshots and sets the initial value to 1.
Uses [value object casting](https://laravel.com/docs/10.x/eloquent-mutators#value-object-casting) to cast the snapshot for more complicated getters and setters and adds the version as a static property on it to be added in the setter.
1. Login as any user
2. Apply to a job completing and submitting to generate snapshot
3. Open the database record for the application that was submitted in step 2
4. View the snapshot field to confirm the JSON contains a version number
=> [Feat] Version snapshots

api/app/GraphQL/Mutations/DownloadApplicationDoc.php, api/app/GraphQL/Mutations/DownloadUserDoc.php
🤖 Resolves #11445 
Adjust filename generation to desired format
1. Download some documents
2. Observe the cases: profile, anonymous profile, and application
3. Try and find edge cases to be cautious of?
=> [Feature] Single document download filename

apps/playwright/tests/admin/process-actions.spec.ts
🤖 Resolves #10528 
Adjusts the process actions test to no longer require serial mode.
1. Run the test `pnpm run e2e:playwright:chromium -- --process-actions`
2. Confirm it passes
3. Confirm it still has the same coverage
=> [Debt] Make process tests parallel

apps/web/src/components/DirectiveBlock/DirectiveBlock.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Home/HomePage/components/Featured/Featured.tsx, apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
🤖 Resolves #11489.
Makes some small changes to copy referring to the directive page.
1. Visit the homepage and view updated copy
2. Visit the manager and executive pages and view updated copy
=> [Copy] Update copy about directive page

api/app/GraphQL/Validators/CreateJobPosterTemplateInputValidator.php, api/app/GraphQL/Validators/UpdateJobPosterTemplateInputValidator.php, api/app/Rules/SkillLevelRequiredIfEssential.php, api/database/factories/JobPosterTemplateFactory.php, api/database/migrations/2024_09_17_183902_job_template_nullable_skill_level.php, api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/JobPosterTemplateTest.php
🤖 Resolves #11525.
Makes the skill level for job templates nullable and attempts to validate only asset skills have a null skill level.
1. Run the migration and seeders
2. Confirm asset skills have a null skill level
3. Confirm the validation works as expected
=> [Feature] Job template has nullable skill level

api/tests/Feature/JobPosterTemplateTest.php
🤖 Resolves #11546.
Adds some tests for the skill level validation added in #11543.
1. Confirm tests pass in CI.
2. Confirm tests pass locally.
=> [Tests] Job template skill level validation

apps/web/src/lang/fr.json, apps/web/src/pages/ManagerDashboardPage/ManagerDashboardPage.tsx, apps/web/src/pages/ManagerDashboardPage/messages.ts
🤖 Resolves #11406 
This branch updates some copy on the manager dashboard based on some changes requested after it was built.
One of the AC was to remove an incomplete section.  I confirmed that that section was wrapped in an "incomplete" flag but didn't end up removing it as the whole page is full of incomplete sections.  :smile: 
1. Build app
2. Navigate to `/en/manager/dashboard`
=> [Feat] Manager dashboard copy updates

apps/web/src/pages/ManagerDashboardPage/ManagerDashboardPage.tsx
🤖 Resolves #11464 
- Stores accordion states to local storage on manager dashboard
2. Login as `manager@test.com`
3. Go to `/manager/dashboard`
4. Ensure the accordion state persists on local storage and the state is correct
=> Store accordion states to local storage on manager dashboard

api/phpstan.neon
Removes the ignore for an error that was fixed.
1. Confirm lint workflow passes
=> [Fix] Remove ignore missing import `ArmedForcesStatus`

apps/web/src/lang/fr.json, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/AssetTechnicalSkills.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/EssentialBehaviouralSkills.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/EssentialTechnicalSkills.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/KeyTasks.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/messages.ts, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/JobPosterTemplatesPage.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/messages.ts
🤖 Resolves #11495
Makes the requested copy changes
1. The most important part is probably to nitpick for copy paste mistakes
2. Build pages successfully
=> [Copy] Job template pages copy updates

apps/web/src/components/ExperienceFormFields/ExperienceHeading.tsx, apps/web/src/components/Profile/components/DiversityEquityInclusion/DiversityEquityInclusion.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/ApplicationCareerTimelineAddPage.tsx, apps/web/src/pages/Applications/ApplicationCareerTimelineIntroductionPage/ApplicationCareerTimelineIntroductionPage.tsx, apps/web/src/pages/Applications/ApplicationProfilePage/ApplicationProfilePage.tsx, apps/web/src/pages/Applications/ApplicationQuestionsIntroductionPage/ApplicationQuestionsIntroductionPage.tsx, apps/web/src/pages/Applications/ApplicationSkillsIntroductionPage/ApplicationSkillsIntroductionPage.tsx, apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx, apps/web/src/pages/Applications/ApplicationWelcomePage/ApplicationWelcomePage.tsx, apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #9418 
Updates the copy for advertisements as well as the application process.
3. Go through an application confirming the copy changes requests are reflected in both French and English
=> [Copy] Update copy for application process

apps/web/src/components/AssessmentStepTracker/AssessmentResultsFilterDialog.tsx
🤖 Resolves #11607 
Updates the EE filter to use a multiselect combobox.
I took the liberty of adjusting the layout to allot more room for the new multiselect component to balance it out a bit as well.
3. Navigate to a process screening and evaluation page
4. Open the filter dialog and confirm the EE filter is multiselect and functions as expected
=> [Feature] Update EE filter to use multi combobox

packages/ui/src/components/Chip/Chip.tsx
🤖 Resolves #11585 
- Update top + bottom padding on chip component
1. Build app
2. Ensure chip padding is correct
=> [Feature] Update chip padding

apps/web/src/components/EmploymentEquity/dialogs/IndigenousDialog.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/ApplicationSelfDeclarationPage.tsx, apps/web/src/pages/Home/ExecutiveHomePage/ExecutiveHomePage.tsx, apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx, apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
🤖 Resolves #11610 
Updates copy referring to opportunities to specify job opportunities.
2. Confirm requested copy changes occurred
=> [Copy] Update references to job opportunities

api/app/Builders/PoolBuilder.php, api/app/GraphQL/Mutations/SendUserEmailVerification.php, api/app/GraphQL/Mutations/TogglePoolUserBookmark.php, api/app/GraphQL/Mutations/UpdateSitewideAnnouncement.php, api/app/GraphQL/Mutations/VerifyUserEmail.php, api/app/Models/PoolCandidate.php, api/app/Models/PoolCandidateSearchRequest.php, api/app/Models/User.php, api/app/Policies/PoolCandidatePolicy.php, api/app/Rules/SkillLevelRequiredIfEssential.php, api/phpstan.neon
🤖 Resolves #11592 
Updated typehinting or removed the nullsafe model operator where needed. 
Seemed straightforward to me?
1. No nullsafe errors missed
2. No logic/code in question was  functionally changed
=> [Debt] Larastan - nullsafe operator unneeded 

api/app/Builders/PoolBuilder.php, api/phpstan.neon
🤖 Resolves #11591 
Resolve the sole instance of this error, just an unneeded argument
1. No more of this error type
2. File functionally unchanged
=> [Debt] Larastan - invoke parameter mismatch argument count

apps/web/src/components/NotificationList/NotificationButton.tsx, apps/web/src/components/NotificationList/NotificationDownload.tsx, apps/web/src/components/NotificationList/NotificationLink.tsx, apps/web/src/components/Table/ResponsiveTable/Table.stories.tsx, apps/web/src/pages/Users/UserInformationPage/components/NotesSection.tsx, packages/eslint-config-custom/index.js
🤖 Resolves #11379 
Re-enables and fixes errors associated with the `no-misused-promises` eslint rule.
Most of these were passing async functions to sync attributes (events). The major one was aboided since it is coming from `react-hook-form`. To see details, checkout [the discussion about this](https://github.com/orgs/react-hook-form/discussions/8622).
1. Confirm no lint errors
2. Confirm affected code continues to work as expected
=> [Fix] Misused promises

apps/web/src/lang/fr.json, apps/web/src/pages/PrivacyPolicy/PrivacyPolicy.tsx
🤖 Resolves #11807.
This PR updates the copy for the first paragraph on the privacy policy page.
1. Navigate to http://localhost:8000/en/privacy-policy
2. Verify first paragraph matches the English copy provided in the linked issue
4. Verify first paragraph matches the French copy provided in the linked issue
=> [Copy] Updates first paragraph of privacy policy page

pnpm-lock.yaml
This PR fixes a broken lockfile 🤞.
=> [Fix] `pnpm` lockfile babel resolutions

apps/web/src/lang/fr.json, apps/web/src/pages/ItTrainingFundPage/ItTrainingFundPage.tsx
🤖 Resolves #11880.
This PR updates copy for two strings on the IT Community Training and Development Fund page.
1. Navigate to http://localhost:8000/en/it-training-fund
2. Verify copy is updated in English
3. Switch to french
4. Verify copy is updated in French
=> [Copy] Updates IT Community Training and Development Fund

apps/web/src/lang/__snapshots__/lang.test.ts.snap, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #11936.
This PR removes several strings that are not referenced anywhere in the codebase.
Verify codebase does not have any references to these strings from `commonMessages`.
=> [Debt] Removes unused strings

apps/web/src/pages/AnnouncementsPage/AnnouncementsPage.tsx, apps/web/src/pages/AnnouncementsPage/SitewideAnnouncementDisplay.tsx, apps/web/src/pages/AnnouncementsPage/SitewideAnnouncementForm.tsx
🤖 Resolves #11486.
This PR updates the Announcements page to use the new Hero component. It also updates the layout of the form and display components to be stacked in a single column on smaller screens based on designs in the linked issue and conversation with the designer, @Jerryescandon.
2. Navigate to http://localhost:8000/en/admin/settings/announcements
3. Verify Announcements page used the new Hero component
=> [Feature] Updates Announcements layout

api/lang/fr/final_decision.php, api/lang/fr/pool_candidate_status.php, apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/RevertFinalDecisionDialog.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/RemoveCandidateDialog/RemoveCandidateDialog.tsx, packages/i18n/src/lang/fr.json
🤖 Resolves #11899.
This PR makes a bevy of copy changes mostly related to application status, nearly all of which are French only changes.
- Build `pnpm build`
- Storybook `pnpm storybook`
> [!TIP]
> This list should correspond with the list in the linked issue's details section
1. Navigate to http://localhost:8000/fr/admin/pool-candidates and find candidate with Décision finale of:
a. Qualifié(e)
b. Qualifié(e) : Placé(e)
c. Retiré : Qualifié (Navigate to application page of a candidate with a Décision finale then verify Statut du (de la) candidat(e) is Qualifié(e) retiré(e))
2. Navigate to http://localhost:6006/?path=/story/components-applicationcard--default&globals=locale:fr
a. Search for DRAFT and verify Poursuivez l'ébauche
b. Search for PLACED_CASUAL and verify Embauché(e) …
=> [Copy] Application status strings in French

api/app/Models/PoolCandidate.php, api/database/migrations/2024_10_30_153334_add_index_to_pool_candidates__table.php, api/graphql/schema.graphql
🤖 Resolves  #11762 
I've made some simple improvements like eager loading , adding indexes and reducing computing time on the query by reusing var.s
There wasn't lot of diff when running in normal scenario.
I introduced throttling and 4 hardware concurrency by the browser extension and results are visible in those conditions. 
We do have over fetching on the screening tracker as we are not showing Expired:qualified statuses. 
But when I talked to Jerbo this is something we have to show on the page ..and the enhancement is coming up. So I didn't trim it.
Browser: Edge
Env.
Test Data 
https://dev-talentcloud.tbs-sct.gc.ca/en/admin/pools/df7b540b-4076-47ac-8223-5c669dbf9a64
1009 candidates including expired/rejected 
Current Main performance in the above scenario
This PR 
Verify query timing …
=> 11762 improve screening candidates query

apps/web/src/types/experience.ts
🤖 Resolves #12021.
This PR removes the unnecessary export declaration of `WorkFormValues`.
Verify codebase does not contain any references to `WorkFormValues` outside of the file `apps/web/src/types/experience.ts`.
=> [Debt] Removes `WorkFormValues` export

infrastructure/bin/post_deployment.sh
🤖 Resolves #10625.
This PR replaces the Laravel artisan command `config:cache` with `optimize` in order for Laravel to be optimized in production.
1. Deploy to Azure infrastructure
2. Verify Laravel's configuration, events, routes, and views still work
=> [Debt] Replaces Laravel artisan `config:cache` with `optimize`

apps/playwright/tests/admin/process-actions.spec.ts, apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json, apps/web/src/pages/Classifications/components/ClassificationTable.tsx, apps/web/src/pages/Departments/CreateDepartmentPage.tsx, apps/web/src/pages/Departments/components/DepartmentTable.tsx, apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx, apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx, apps/web/src/pages/Pools/ViewPoolPage/components/DuplicateProcessDialog.tsx, apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx, apps/web/src/pages/Skills/CreateSkillPage.tsx, apps/web/src/pages/Skills/components/SkillTable.tsx, apps/web/src/pages/Skills/components/UpdateSkillShowcase.tsx, apps/web/src/pages/Teams/CreateTeamPage/CreateTeamPage.tsx, apps/web/src/pages/Teams/CreateTeamPage/components/CreateTeamForm.tsx, apps/web/src/pages/Teams/IndexTeamPage/IndexTeamPage.tsx, apps/web/src/pages/Teams/IndexTeamPage/components/TeamTable/TeamTable.tsx, apps/web/src/pages/TrainingOpportunities/CreateTrainingOpportunityPage.tsx, documentation/style-guide.md
🤖 Resolves #12019.
This PR removes pleonasms **create new** and **create a new** where it has been deemed redundant, updates some verb tenses in French, and fixes a typo in documentation.
@NienkeBr for **creating a new** entry in my lexicon, pleonasm.
2. Verify pleonasms **create new** and **create a new** do not exist in English
3. Verify pleonasms **créez/creer un/une nouveau/nouvelle** do not exist in French
<details>
<summary>French and English</summary>
</details>
=> [Copy] Removes pleonasm create new

api/app/Models/PoolCandidate.php
🤖 Resolves #12178.
This PR corrects the spelling of the variable `$decision`.
1. Search codebase for instances of decison
2. Verify no instances of decison
=> [Debt] Corrects spelling of variable `$decision`

api/app/Enums/DirectiveForms/AdvertisingPlatform.php, api/programmatic-types.graphql, api/storage/app/lighthouse-schema.graphql
🤖 Resolves #12190.
This PR replaces `GCXCHNAGE` with `GCXCHANGE`.
Verify no instances of `GCXCHNAGE` in codebase.
=> [Copy] Replaces `GCXCHNAGE` with `GCXCHANGE`

apps/web/src/lang/fr.json, apps/web/src/pages/Pools/EditPoolPage/components/YourImpactSection/YourImpactSection.tsx
🤖 Resolves #12244.
This PR updates the your impact description paragraph in English.
2. Navigate to `http://localhost:8000/fr/admin/pools/{pool-id}/edit#about-role`
3. Verify text in English section following Your impact heading matches the copy in the linked issue
=> [Copy] Updates your impact description paragraph in English

packages/ui/src/components/Accordion/Accordion.tsx
🤖 Resolves #11975 
Resolve the overlap through spacing, also set focus colour to black in all cases
1. Navigate to manager dashboard
2. Keyboard toggle down
=> [Accessibility] Fix accordion focus overlap with actions

api/tests/Feature/SnapshotTest.php
🤖 Resolves #12299 
Remove the localized field from name to fix the test
1. Snapshot test passes CI
2. Passes locally
=> [Bug] Fix snapshot test

api/graphql/schema.graphql
🤖 Resolves #12243.
This PR removes commented out `generalQuestionResponses` on `GeneralQuestion` type.
1. `make refresh-api`
2. `pnpm build:fresh`
3. Verify app builds without error
=> [Debt] Removes commented out `generalQuestionResponses` on `GeneralQuestion` type

packages/ui/src/components/ResourceBlock/BaseItem.tsx, packages/ui/src/components/ResourceBlock/LinkMenuItem.tsx
🤖 Resolves #11977 
Associates the title of a resource block with the description of the block.
1. Rebuild and log in as manager@test.com
2. Navigate to `/manager/dashboard`
=> [Fix] Associate resource block title and description

apps/web/src/components/Table/ResponsiveTable/Table.tsx, apps/web/src/pages/Pools/PoolLayout.tsx
🤖 Resolves #12430 
Replaces the team name (no longer available) with the community name as the subtitle for the process layout.
3. Navigate to a process in the admin intrface `/admin/pools/{poolId}`
4. Confirm the subtitle is the name of the community for the pool
5. Change languages
6. Confirm the subtitle changes to the new language and is still the community name
=> [Fix] Update process subtitle

api/lang/en/priority_weight.php, api/lang/fr/headings.php, apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx, apps/web/src/components/PoolCandidatesTable/tableMessages.ts, apps/web/src/components/PoolFilterInput/PoolFilterInput.tsx, apps/web/src/components/Table/ResponsiveTable/Table.stories.tsx, apps/web/src/lang/fr.json, apps/web/src/messages/adminMessages.ts, apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx, apps/web/src/pages/Users/UserInformationPage/components/AboutSection.tsx, packages/forms/src/components/Select/Select.stories.tsx, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #12417.
This PR updates the Candidates table and its associated filter dialog to use sentence case where title case was otherwise used.
2. Navigate to http://localhost:3000/en/admin/pool-candidates
3. Verify table and its associated filter dialog use sentence case
=> [Copy] Updates Candidates table to use sentence case

apps/web/src/pages/EmployeeProfile/components/GoalsWorkStyleSection/GoalsWorkStyleSection.tsx
🤖 Resolves #12542.
This PR removes an unnecessary export of `GoalsWorkStyleSectionProps`.
2. Navigate to http://localhost:8000/en/applicant/employee-profile
3. Verify Your goals and work style form saves and renders as it did before
=> [Debt] Removes unnecessary export of `GoalsWorkStyleSectionProps`

apps/web/src/components/PoolStatusTable/cells.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
🤖 Resolves #12541.
This PR removes all references to `viewTeamLinkCell` that is not referenced anywhere in the codebase.
1. Search codebase for `viewTeamLinkCell`
2. Verify no instances of `viewTeamLinkCell` in codebase
=> [Debt] Removes `viewTeamLinkCell`

.github/ISSUE_TEMPLATE/✨-feature-request.md, documentation/definition-of-ready.md
Updates our Definition of Ready, based on recent discussion in retro.
References Definition of Ready in Feature ticket template, to make it harder to forget or ignore.
=> [Task] Updated definition of ready

.github/dependabot.yml
🤖 Resolves #12578 
Groups the formatjs dependencies for dependabot.
1. Confirm the group looks good?
=> [Debt] Add formatjs group for dependabot

apps/web/src/pages/SearchRequests/SearchPage/components/AdvancedFilters.tsx, packages/ui/src/components/Breadcrumbs/Breadcrumbs.tsx
🤖 Resolves #12663.
This PR fixes two invalid css values.
Verify hydrogen values are correct.
=> [Fix] Invalid css values

apps/web/src/utils/teamUtils.ts
🤖 Resolves #12660.
This PR removes unused types, functions, and imports from `apps/web/src/utils/teamUtils.ts`.
2. Verify build succeeds without any errors
3. Verify no references to any of the removed types, functions, and imports from `apps/web/src/utils/teamUtils.ts`
=> [Debt] Removes unused types, functions, imports from `teamUtils.ts`

apps/web/src/components/TalentNominationEventCard/TalentNominationEventCard.stories.tsx, apps/web/src/components/TalentNominationEventCard/TalentNominationEventCard.tsx, apps/web/src/lang/fr.json
🤖 Resolves #12313.
This PR adds the `TalentNominationEventCard` component.
2. Navigate to http://localhost:6006/?path=/story/components-talentnominationeventcard--default
=> [Feature] Adds `TalentNominationEventCard` component

apps/web/src/lang/fr.json, apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/ApplicationCareerTimelineAddPage.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
🤖 Resolves #12773.
This PR updates the string **Add experience** to sentence case and consolidates duplicate strings.
2. Navigate to http://localhost:8000/en/applicant/career-timeline/create
3. Verify breadcrumb for **Add experience** is sentence case 
4. Navigate to an application, Step 3 of 7
5. Verify breadcrumb for **Add experience** is sentence case
=> [Copy] Add experience to sentence case

apps/web/src/pages/ApplicantDashboardPage/components/CareerDevelopmentTaskCard.tsx
🤖 Resolves #12777
Check some links and make some fixes
1. Navigate to `/en/applicant`
2. Check out links
=> [Bug] Check-over talent management links 

apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json, apps/web/src/pages/ApplicantDashboardPage/components/MetadataDate.tsx
🤖 Resolves #12823.
This PR updates **Submitted** and **Work streams** strings in French.
2. Navigate to http://localhost:8000/fr/applicant
3. Verify _Soumise_ appears for one of the items (must be a submitted application) in _Candidatures et processus_ section
4. Click the magniying glass icon for the same item
5. Verify one of the labels in the dialog is _Volet de travail_
=> [Copy] Updates Submitted and Work streams strings in French

Makefile.nix, api/app/Enums/TargetRole.php, api/app/GraphQL/Validators/UpdateEmployeeProfileInputValidator.php, api/app/Models/EmployeeProfile.php, api/database/factories/UserFactory.php, api/database/migrations/2025_02_14_145918_rename_dream_role.php, api/graphql/schema.graphql, api/lang/en/target_role.php, api/lang/fr/target_role.php, api/storage/app/lighthouse-schema.graphql, api/tests/Feature/EmployeeProfileTest.php
🤖 Resolves #12743 
Updates the database and graphql schemas to adapt to the changes to the Next Role and Career Objective sections.
<details><summary>GraphQL Query</summary>
```graphql
query DreamRole {
me {
employeeProfile {
nextRoleJobTitle
careerObjectiveJobTitle
nextRoleAdditionalInformation
careerObjectiveAdditionalInformation
nextRoleCommunity {
id
}
careerObjectiveCommunity {
id
}
nextRoleClassification {
id
}
careerObjectiveClassification {
id
}
nextRoleWorkStreams {
id
}
careerObjectiveWorkStreams {
id
}
nextRoleDepartments {
id
}
careerObjectiveDepartments {
id
}
nextRoleTargetRole {
label {localized}
}
careerObjectiveTargetRole {
label {localized}
}
nextRoleTargetRoleOther
careerObjectiveTargetRoleOther
}
}
}
```
</details> 
<details><summary>GraphQL Mutation</summary> …
=> [Feature] Next Role and Career Objective API

.github/workflows/chromatic.yml, .github/workflows/jest.yml, .github/workflows/lint.yml, .github/workflows/playwright.yml, .github/workflows/translations.yml, infrastructure/bin/deploy.sh, infrastructure/maintenance-container/Dockerfile, package.json
🤖 Resolves #12858.
Upgrades `pnpm` to the latest version: 10.
1. Update `npm install -g pnpm@10.5.2` 
2. Clean module folders `make clean-modules`
3. Install dependencies `pnpm install`
4. Build `pnpm build`
5. Confirm everything works as expected
=> [Debt] Upgrades `pnpm` to v10.5.2

api/app/Enums/OrganizationTypeInterest.php, api/lang/en/organization_type_interest.php, api/lang/fr/organization_type_interest.php, api/storage/app/lighthouse-schema.graphql
🤖 Resolves #12918.
This PR adds `MICRO`, `SMALL`, `MEDIUM`,`LARGE` to `OrganizationTypeInterest` enum.
2. Navigate to http://localhost:8000/en/applicant/employee-profile#career-development-section
3. Edit Career development preferences form
4. Choose I’m interested in receiving opportunities for jobs at, or equivalent to, my current group and level.
5. Verify last four checkboxes for Types of organizations you’d consider for lateral movement are `MICRO`, `SMALL`, `MEDIUM`,`LARGE`
6. Choose I’m not looking for lateral movement right now.
7. Choose I’m interested in receiving opportunities for promotion and advancement.
8. Verify last four checkboxes for Types of organizations you’d consider for promotion or advancement are …
=> [Feature] Adds `MICRO`, `SMALL`, `MEDIUM`,`LARGE` to `OrganizationTypeInterest` enum

apps/web/src/components/StatusItem/StatusItem.tsx
🤖 Resolves #12892 
Updates the status item to focus the section it scrolls to.
1. Buld `pnpm run dev:fresh`
2. Login as `applicant-employee@test.com`
3. Navigate to the employee profile `/applicant/employee-profile`
4. Navigate to the TOC using your keyboard
5. Activate a link in the TOC
6. Confirm your focus goes to the section rather than staying in the TOC
=> [a11y] Adds focus on scroll to for status items

apps/web/src/components/Router.tsx, apps/web/src/hooks/useRoutes.ts, apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json, apps/web/src/lang/whitelist.yml, apps/web/src/messages/pageTitles.ts, apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx, apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx, apps/web/src/pages/CommunityInterests/sections/ReviewAndSubmit.tsx, apps/web/src/pages/TalentManagementEventsPage/TalentManagementEventsPage.tsx, apps/web/src/pages/TalentNominations/NominateTalent/NominateTalentPage.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Actions.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Details.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Instructions.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Navigation.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Nominator.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Nominee.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Rationale.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/ReviewAndSubmit.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/SubHeading.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Success.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/UpdateForm.tsx, apps/web/src/pages/TalentNominations/NominateTalent/types.ts, apps/web/src/pages/TalentNominations/NominateTalent/useCurrentStep.ts, apps/web/src/pages/TalentNominations/NominateTalent/useMutations.ts, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/navigationMessages.ts, packages/ui/src/components/Stepper/Stepper.tsx
🤖 Resolves #12315 
Adds the stubs for steps in the talent nomination process.
3. Navigate to `/communities/talent-events`
4. Start a nomination for one of the events
5. Step through the form confirming it works as expected
=> [Feat] Talent nomination stub pages

apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
🤖 Resolves #13009 
- Fixes the sidebar in the Applicants dashboard page. 
1. Build app `run pnpm dev` 
2. Log as in as `applicant-employee@test.com`
3. Go to Applicant dashboard page `/en/applicant`
4. Ensure sidebar is working correctly
=> [Bug] Applicant dashboard sidebar fix

docker-compose.yml, infrastructure/conf/mock-oauth2-server.json, infrastructure/mockauth/resources/login.html
🤖 Resolves #13075 
This just applies some styles to the mock auth now that it is no longer loading from a third party.
1. Rebuild docker `make down; make up;`
2. Go to the sign in
3. Confirm it looks not awful
=> [Debt] Improve mock sign in template

apps/web/src/lang/fr.json
🤖 Resolves #13112.
This PR updates French copy on the Comptrollership executives talent management and its section on the home page.
2. Navigate to http://localhost:8000/fr/
3. Verify changes to copy on the comptrollership section title
4. Navigate to http://localhost:8000/fr/comptrollership-executives
5. Verify changes to copy on the page
=> [Copy] Updates French comptrollership copy

apps/web/src/lang/fr.json, apps/web/src/messages/talentNominationMessages.ts, apps/web/src/pages/ApplicantDashboardPage/components/ReviewTalentNominationDialog.tsx, apps/web/src/pages/ApplicantDashboardPage/components/TalentNominationListItem.tsx
🤖 Resolves #13003 
Adds a review dialog for viewing submitted nominations.
If you want to add a submitted nomination for a user you can open Tinker and run something like this:
```php
$submitter = User::where('sub', 'applicant-employee@test.com')->sole();
$nomination = TalentNomination::factory()->submittedReviewAndSubmit()->create(['submitter_id' => $submitter->id]);
```
1. Rebuild the app
2. Log in as `applicant-employee@test.com`
3. View the nomination in the new "Talent management" widget
=> [Feature] Nomination review dialog for applicant dashboard

apps/web/src/components/EmployeeSearchInput/ControlledInput.tsx, apps/web/src/components/EmployeeSearchInput/EmployeeSearchInput.tsx, apps/web/src/components/EmployeeSearchInput/Error.tsx, apps/web/src/components/EmployeeSearchInput/Result.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/TalentNominations/NominateTalent/components/Details.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Nominator.tsx, apps/web/src/pages/TalentNominations/NominateTalent/components/Nominee.tsx
🤖 Resolves #13184
Make requested changes
Had to prop drill a little to make things smoothly work with the layered input
1. Head to `/en/communities/talent-events`
2. Start a nomination and step through
3. Observe copy changes per issue request
=> [Copy] Nomination flow copy changes

apps/web/src/lang/__snapshots__/lang.test.ts.snap, apps/web/src/lang/fr.json, packages/i18n/src/lang/fr.json
🤖 Resolves #13207.
This PR updates French copy in several places.
2. Navigate to http://localhost:8000/fr/applicant/employee-profile#career-development-section
3. Verify none of these values for Intérêt pour les possibilités d'apprentissage have `//`
4. Navigate to http://localhost:8000/fr/browse/pools
5. _Posez votre candidature_ for one of the processes
6. Verify Postulez dès maintenant does not have any hyphens
7. Navigate to http://localhost:8000/fr/communities/talent-events
8. _Lancez une mise en candidature_ for one of the events
9. Select _Je suis l'auteur ou l'autrice de la mise en candidature_
10. Select _Prochaine étape_
11. Enter a verified Government of Canada employee email for _Rechercher le courriel professionnel de la personne candidate_ field
12. …
=> [Copy] Updates French copy in several places

api/app/Generators/CommunityInterestUserCsvGenerator.php
🤖 Resolves #13285
Use the verification scope to filter 
1. Assert the community talent table and the dataset download match up (download is deduplicated)
2. Download no longer has unverified users
=> [Bug] Use verification scope in CSV query

apps/web/src/lang/fr.json, apps/web/src/pages/TalentNominations/NominationGroup/components/NominationGroupEvaluationDialog.tsx, apps/web/src/pages/TalentNominations/NominationGroup/components/NominationGroupSidebar.tsx, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/NominationGroupEvaluationDialog.tsx, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/components/AdvancementSection.tsx, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/components/DevelopmentProgramsSection.tsx, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/components/LateralMovementSection.tsx, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/components/NominationGroupEvaluationForm.tsx, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/form.ts, apps/web/src/pages/TalentNominations/NominationGroupEvaluationDialog/messages.ts
🤖 Resolves #13021 
Adds the dialog to evaluate a nomination group.
To set a nomination group up, you can run something like this in Tinker:
```php
$community = Community::where('key','digital')->sole();
$talentNominationEvent = TalentNominationEvent::factory()
->hasAttached($community->developmentPrograms)
->create(['community_id'=>$community->id]);
$submitter = User::where('sub', 'applicant-employee@test.com')->sole();
$nominee = User::where('sub', 'community@test.com')->sole();
$nominations = TalentNomination::factory()
->submittedReviewAndSubmit()
->count(3)
->create([
'talent_nomination_event_id' => $talentNominationEvent->id,
'submitter_id' => $submitter->id,
'nominee_id' => $nominee->id,
'nominate_for_advancement' => true,
'nominate_for_lateral_movement' => true, …
```
=> [Feature] Evaluate nomination dialog

api/tests/Unit/Notifications/NominationUtilsTest.php
🤖 Resolves #13329
Resolve the autoloader complaint
1. Refresh API, observe no yellow text like in the screenshot below
=> [Bug] Fix namespace for PHP test

apps/web/src/components/CommunityInterest/CommunityInterest.tsx, apps/web/src/components/ExperienceCard/WorkContent/WorkStreamsContent.tsx, apps/web/src/components/ExperienceWorkStreams/ExperienceWorkStreams.tsx, apps/web/src/components/ExperienceWorkStreams/ExperienceWorkStreamsEditDialog.tsx, apps/web/src/components/NextRoleAndCareerObjective/CareerObjective.tsx, apps/web/src/components/NextRoleAndCareerObjective/NextRole.tsx, apps/web/src/components/UserProfile/ExperienceSection.tsx, apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx, apps/web/src/pages/CommunityDashboardPage/CommunityDashboardPage.tsx, apps/web/src/pages/CommunityInterests/form.ts, apps/web/src/pages/CommunityInterests/sections/TrainingAndDevelopmentOpportunities.tsx, apps/web/src/pages/EmployeeProfile/components/CareerObjective/CareerObjectiveSection.tsx, apps/web/src/pages/EmployeeProfile/components/CareerObjective/Display.tsx, apps/web/src/pages/EmployeeProfile/components/NextRoleSection/Display.tsx, apps/web/src/pages/EmployeeProfile/components/NextRoleSection/NextRoleSection.tsx, apps/web/src/pages/SkillFamilies/ViewSkillFamilyPage.tsx, apps/web/src/pages/Skills/ViewSkillPage.tsx, apps/web/src/pages/TalentEvents/TalentEvent/DetailsPage.tsx, apps/web/src/pages/Users/UserEmployeeInformationPage/components/CareerObjectiveSection.tsx, apps/web/src/pages/Users/UserEmployeeInformationPage/components/NextRoleSection.tsx, apps/web/src/utils/talentNominations.ts, packages/helpers/package.json, packages/helpers/src/index.tsx, packages/helpers/src/utils/sort.test.ts, packages/helpers/src/utils/sort.ts, pnpm-lock.yaml, pnpm-workspace.yaml
🤖 Resolves #13063 
Adds a helper to sort arrays of objects alphabetically by a nested key.
2. Confirm replacements are still sorted properly
=> [Feat] New helper for sorting arrays of complex object alphabetically

apps/playwright/tests/applicant/application.spec.ts
🤖 Resolves #13268 
Adds a test to view application from applicant dashboard.
1. Confirm test passes consistently
2. Confirm it covers the case
=> [Test] View application on dashboard

api/lang/en/education_type.php, apps/playwright/tests/applicant/application-iap.spec.ts, apps/playwright/tests/applicant/application.spec.ts, apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx, apps/web/src/lang/fr.json, apps/web/src/messages/experienceMessages.ts, apps/web/src/pages/Applications/ApplicationEducationPage/LinkCareerTimeline.tsx, apps/web/src/pages/Applications/fragment.ts, apps/web/src/pages/Profile/CareerTimelinePage/components/CareerTimeline.tsx, apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx, apps/web/src/pages/Skills/UpdateUserSkillPage.tsx, apps/web/src/pages/TalentNominations/NominationGroup/CareerExperience.tsx, apps/web/src/pages/Users/AdminUserProfilePage/AdminUserProfilePage.tsx, apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #13293 
- Fixes the education experience display name
- Moves the display name logic to the getExperienceName helper in `experienceUtils.ts`
1. Ensure education experience display name is correct across site
=> [Bug] Fix education experience display title

api/app/Console/Commands/DepartmentDeduplication.php, api/app/Models/Department.php, api/tests/Feature/DepartmentDeduplicationTest.php
🤖 Resolves #13205
Handle references to duplicates, then delete them
Per
https://docs.google.com/spreadsheets/d/1d-Q-CYZyOKeh-Hgt6jqO7-QN0PA4Wm0Y/edit?pli=1&gid=1168595640#gid=1168595640
1. Proofread for typos
2. Little tricky to test locally...
Sample local run
Run
`php artisan app:department-deduplication`
=> [Debt] Department deduping

apps/web/src/pages/ApplicantDashboardPage/components/ReviewTalentNominationDialog.tsx
🤖 Resolves #13348
Add additional info pertaining to nomination type to the dialog
♻️ code
1. Head to applicant dashboard
2. Have or submit nominations
3. Open a nomination to review in "Talent management" widget
=> [Feature] Nomination review dialog add more info

apps/web/src/lang/fr.json, apps/web/src/pages/InstructorLedTrainingPage/InstructorLedTrainingPage.tsx
🤖 Resolves #12551 
Updates the list of training opportunities to announce the filter changes. As well, adds some aria to improve the accessibility of the controls themselves.
2. Navigate to `/it-training-fund/instructor-led-training`
3. Using keyboard and screen reader
4. Change the filters
5. Confirm screen reader lets you know what option is selected
=> [a11y] Announce content changes on instructor lead training page

api/graphql/schema.graphql, api/storage/app/lighthouse-schema.graphql, apps/playwright/tests/applicant/employee-profile.spec.ts, apps/web/src/components/PoolSkillAccordion/PoolSkillAccordion.tsx, apps/web/src/components/StatusItem/StatusItem.tsx, apps/web/src/lang/fr.json, apps/web/src/pages/EmployeeProfile/EmployeeProfilePage.tsx, packages/i18n/src/lang/fr.json, packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #13250.
Adds e2e test for filling out the employee profile.
Confirm test passes with `pnpm run e2e:playwright employee-profile`.
=> [Debt] Add employee profile E2E test

apps/web/src/components/ExperienceFormFields/ExperienceHeading.tsx, apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/ApplicationCareerTimelineAddPage.tsx, packages/ui/src/components/DescriptionList/DescriptionList.stories.tsx, packages/ui/src/components/DescriptionList/DescriptionList.tsx
🤖 Resolves #13556 
Migrates the `DescriptionList` component to tailwindcss.
=> [Debt] Migrate `DescriptionList` to tailwind

apps/web/src/pages/ApplicantDashboardPage/components/ApplicationsProcessesTaskCard.tsx, apps/web/src/pages/ApplicantDashboardPage/components/CareerDevelopmentTaskCard.tsx, apps/web/src/pages/ApplicantDashboardPage/components/TalentManagementTaskCard.tsx, packages/ui/src/components/TaskCard/TaskCard.stories.tsx, packages/ui/src/components/TaskCard/TaskCard.tsx, packages/ui/src/components/TaskCard/index.ts, packages/ui/src/index.tsx
🤖 Resolves #13578 
Migrate the `TaskCard` component to tailwindcss.
I had to add a compat map for colours to pass to links. Comment added to remove it when updating the link component.
=> [Debt] Migrate `TaskCard` to tailwind

packages/ui/src/components/ButtonLinkContent/ButtonLinkContent.tsx, packages/ui/src/components/Link/Link.tsx, packages/ui/src/components/Stepper/Step.tsx, packages/ui/src/components/Stepper/Stepper.tsx, packages/ui/src/components/Stepper/types.ts, packages/ui/src/components/Stepper/utils.ts
🤖 Resolves #13574 
Migrates the `Stepper` component to tailwind.
=> [Debt] Migrate `Stepper` to tailwind

packages/ui/src/components/CardRepeater/Button.tsx, packages/ui/src/components/CardRepeater/Card.tsx, packages/ui/src/components/CardRepeater/List.tsx
🤖 Resolves #13555 
Migrates the `CardRepeater` component to tailwindcss.
=> [Debt] Migrate `CardRepeater` to tailwind

packages/forms/src/components/ErrorSummary.tsx, packages/forms/src/components/UnsavedChanges.tsx, packages/forms/src/components/WordCounter.tsx
🤖 Resolves #13673  
Migrates the root components in the forms package to use tailwindcss.
=> [Debt] Migrates root form components to tailwind

packages/forms/src/components/CheckButton/CheckButton.stories.tsx, packages/forms/src/components/CheckButton/CheckButton.tsx
🤖 Resolves #13660 
Migrates the `CheckButton` component to tailwindcss.
=> [Debt] Migrate `CheckButton` to tailwind

apps/web/src/assets/css/app.css, packages/forms/src/components/Repeater/ActionButton.tsx, packages/forms/src/components/Repeater/Repeater.stories.tsx, packages/forms/src/components/Repeater/Repeater.tsx
🤖 Resolves #13667 
Migrates the `Repeater` component to tailwindcss.
=> [Debt] Migrate `Repeater` to tailwind

packages/forms/src/components/Input/Input.stories.tsx, packages/forms/src/components/Input/Input.tsx
🤖 Resolves #13665 
Migrates the `Input` component to tailwindcss.
=> [Debt] Migrate `Input` to tailwind

apps/web/package.json, apps/web/src/components/EducationRequirements/EducationRequirements.stories.tsx, apps/web/src/components/EducationRequirements/EducationRequirements.tsx, pnpm-lock.yaml
🤖 Resolves #13717 
Migrates `EducationRequirements` component to tailwindcss.
> [!TIP]
> There was no story so you might need to build main to have an example of 2/3 cols and compare to this branch. 
1. No sginificant diff
=> [Debt] Migrate `EducationRequirements` to tailwind

packages/ui/src/components/Container/Container.stories.tsx, packages/ui/src/components/Container/Container.tsx, packages/ui/src/index.tsx
🤖 Resolves #13757
Adds a new `Container` that replaces the `data-h2-wrapper` from hydrogen.
1. Confirm that it works identical to `data-h2-wrapper`
=> [Feat] Adds new `Container` component

apps/web/src/components/SkewedContainer/SkewedContainer.tsx, apps/web/src/components/SkewedContainer/SkewedImageContainer.tsx, packages/ui/src/components/Flourish/Flourish.tsx
🤖 Resolves #13833 
Migrates the `SkewedContainer` component to tailwindcss.
1. no significant chromatic diff
=> [Debt] Migrate `SkewedContainer` to tailwind

apps/web/src/components/Instructions/InstructionList.tsx, apps/web/src/components/Instructions/InstructionStep.tsx, apps/web/src/components/MissingLanguageRequirements/MissingLanguageRequirements.tsx, apps/web/src/components/Pagination/PageButton.tsx, apps/web/src/components/Pagination/Pagination.tsx
🤖 Resolves #13733 
Migrates some miscellaneous components to tailwindcss.
=> [Debt] Migrate misc components 3

apps/web/src/assets/css/tailwind.css, apps/web/src/components/SkillRankCard/NullMessage.tsx, apps/web/src/components/SkillRankCard/SkillRankCard.tsx, apps/web/src/components/SkillRankCard/SkillRankListItem.tsx, apps/web/src/components/SkillTree/SkillTree.tsx, apps/web/src/components/SkillsInDetail/SkillsInDetail.tsx, apps/web/src/components/SpinnerIcon/SpinnerIcon.tsx, apps/web/src/components/StatusItem/StatusItem.tsx, apps/web/src/components/TalentManagementPreferences/TalentManagementPreferences.tsx, apps/web/src/components/TalentNominationEventCard/TalentNominationEventCard.tsx, apps/web/src/components/ToggleForm/ColumnDisplay.tsx, apps/web/src/components/ToggleForm/NullDisplay.tsx, packages/forms/src/types.ts, packages/ui/src/components/TreeView/TreeView.tsx
🤖 Resolves #13837 
Migrates misc components 5 to tailwindcss.
=> [Debt] Migrate misc components 5

apps/web/src/components/PoolCard/IconLabel.tsx, apps/web/src/components/PoolCard/PoolCard.tsx, apps/web/src/components/PoolSkillAccordion/PoolSkillAccordion.tsx, apps/web/src/components/ProcessCard/ProcessCard.tsx, apps/web/src/components/RecruitmentProcesses/RecruitmentProcessDialog.tsx, apps/web/src/components/RecruitmentProcesses/RecruitmentProcesses.tsx, apps/web/src/components/RecruitmentProcesses/RecruitmentProcessesPreviewList.tsx, apps/web/src/components/SearchRequestFilters/FilterBlock.tsx, apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx, apps/web/src/components/SearchRequestTable/components/SearchRequestFilterDialog.tsx, apps/web/src/components/SelfDeclaration/CommunityChips.tsx, apps/web/src/components/SelfDeclaration/CommunityIcon.tsx, apps/web/src/components/SelfDeclaration/CommunitySelection.tsx, packages/ui/src/utils/btnStyles.ts
🤖 Resolves #13832 
Migrates misc components to tailwindcss.
> [!NOTE]
> Not many stories here so best bet is to build main and compare diff locations
=> [Debt] Migrate misc components to tailwind 4

api/lang/en/assssment_decision.php, api/lang/fr/assssment_decision.php
🤖 Resolves #13895.
This PR removes files that have a typo in the filename and are not used.
1. Search for assssment in codebase
2. Verify for instances of assssment in codebase
=> [Debt] Removes unused typo `assssment` files

packages/ui/src/components/NavMenu/NavMenu.tsx
🤖 Resolves #13890 
- Fixes home icon hover state color
2. Ensure icon is visible when hovering (can look at prod site talent.canada.ca for reference)
=> [Bug] Fix home icon hover state color

apps/web/src/pages/AccessibilityStatementPage/AccessibilityStatementPage.tsx, apps/web/src/pages/AnnouncementsPage/AnnouncementsPage.tsx, apps/web/src/pages/AnnouncementsPage/SitewideAnnouncementDisplay.tsx, apps/web/src/pages/AnnouncementsPage/SitewideAnnouncementForm.tsx, apps/web/src/pages/PrivacyPolicy/PrivacyPolicy.tsx, apps/web/src/pages/SupportPage/SupportPage.tsx, apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx, apps/web/src/pages/TermsAndConditions/TermsAndConditions.tsx
🤖 Resolves #13935 
Migrates first group of misc. pages to tailwindcss.
=> [Debt] Migrate misc. pages tailwind 1

apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx, apps/web/src/pages/CommunityDashboardPage/CommunityDashboardPage.tsx
🤖 Resolves #13936 
Migrates both community and admin dashboards to tailwindcss.
=> [Debt] Migrate admin/community dashboards to tailwind

apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/JobPosterTemplatePage.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/AssetTechnicalSkills.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/BasicDetails.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/EssentialBehaviouralSkills.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/EssentialTechnicalSkills.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/KeyTasks.tsx, apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/JobPosterTemplatesPage.tsx
🤖 Resolves #13949 
Migrates the `JobPosterTemplates/` pages to tailwindcss.
=> [Debt] Migrate `JobPosterTemplates/` to tailwind

apps/web/src/pages/EmployeeProfile/EmployeeProfilePage.tsx, apps/web/src/pages/EmployeeProfile/components/CareerDevelopmentSection/CareerDevelopmentSection.tsx, apps/web/src/pages/EmployeeProfile/components/CareerDevelopmentSection/Display.tsx, apps/web/src/pages/EmployeeProfile/components/CareerObjective/CareerObjectiveSection.tsx, apps/web/src/pages/EmployeeProfile/components/CareerObjective/Display.tsx, apps/web/src/pages/EmployeeProfile/components/GoalsWorkStyleSection/Display.tsx, apps/web/src/pages/EmployeeProfile/components/GoalsWorkStyleSection/GoalsWorkStyleSection.tsx, apps/web/src/pages/EmployeeProfile/components/NextRoleSection/Display.tsx, apps/web/src/pages/EmployeeProfile/components/NextRoleSection/NextRoleSection.tsx, apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx, packages/ui/src/components/TableOfContents/List.tsx
🤖 Resolves #13944 
Migrates the `EmployeeProfile` page to tailwindcss.
=> [Debt] Migrate `EmployeeProfile` to tailwind

apps/web/src/pages/WorkStreams/CreateWorkStreamPage.tsx, apps/web/src/pages/WorkStreams/UpdateWorkStreamPage.tsx, apps/web/src/pages/WorkStreams/ViewWorkStreamsPage.tsx
🤖 Resolves #13960 
Migrates `WorkStreams/` pages to tailwindcss.
=> [Debt] Migrate `WorkStreams/` to tailwind

apps/web/src/components/SkillBrowser/SkillBrowserDialog.tsx, apps/web/src/pages/Skills/CreateSkillPage.tsx, apps/web/src/pages/Skills/SkillPage.tsx, apps/web/src/pages/Skills/SkillPortfolioPage.tsx, apps/web/src/pages/Skills/SkillShowcasePage.tsx, apps/web/src/pages/Skills/UpdateSkillPage.tsx, apps/web/src/pages/Skills/UpdateUserSkillPage.tsx, apps/web/src/pages/Skills/ViewSkillPage.tsx, apps/web/src/pages/Skills/components/SkillFilterDialog.tsx, apps/web/src/pages/Skills/components/SkillShowcaseCard.tsx, apps/web/src/pages/Skills/components/UpdateSkillShowcase.tsx, packages/ui/src/components/Dialog/Dialog.tsx, packages/ui/src/components/Link/DownloadCsv.tsx
🤖 Resolves #13955 
Migrates the `Skills/` pages to tailwindcss.
=> [Debt] Migrate `Skills/` to tailwind

apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx, apps/web/src/pages/SearchRequests/RequestConfirmationPage/components/RequestConfirmationPrintDocument.tsx, apps/web/src/pages/SearchRequests/RequestPage/RequestPage.tsx, apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/AdvancedFilters.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/EstimatedCandidates.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/FilterBlock.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/FormFields.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/NoResults.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchFilterAdvice.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx, apps/web/src/pages/SearchRequests/SearchPage/components/SearchResultCard.tsx, apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/UpdateSearchRequest.tsx, apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx, packages/ui/src/components/Card/Card.tsx
🤖 Resolves #13953 
Migrates `SearchRequest/` pages to tailwindcss.
=> [Debt] Migrate `SearchRequests/` to tailwind

apps/playwright/tests/admin/pool-candidate-actions.spec.ts, apps/web/src/components/CandidateBookmark/CandidateBookmark.tsx, apps/web/src/components/PoolCandidatesTable/JobPlacementDialog.tsx, apps/web/src/constants/poolCandidate.ts, apps/web/src/hooks/useCandidateBookmarkToggle.ts, apps/web/src/lang/fr.json, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/CandidateNavigation/CandidateNavigation.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ChangeExpiryDateDialog/ChangeExpiryDateDialog.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/DownloadButton.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/FinalDecisionDialog.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/MoreActions.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesForm.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/RevertFinalDecisionDialog.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/StatusLabel.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ReinstateCandidateDialog/ReinstateCandidateDialog.tsx, apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/RemoveCandidateDialog/RemoveCandidateDialog.tsx, apps/web/src/utils/poolCandidate.ts, packages/ui/src/components/Card/Card.tsx, packages/ui/src/components/DropdownMenu/DropdownMenu.tsx, packages/ui/src/components/Separator/Separator.tsx, packages/ui/src/components/Sidebar/Sidebar.tsx
🤖 Resolves #13605 
Updates the styles of the sidebar for a specific `PoolCandidate` in the admin interface.
3. Navigate to pool candidates `/admin/pool-candidates`
4. Select a candidate
5. Confirm the sidebar matches the mockup for each state
=> [Style] Update application sidebar styles

api/app/Models/PoolCandidate.php, api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #13882.
Removes asset skills from assessment step validation logic.
1. Apply to a pool connecting at least one asset skill to your profile.
2. Navigate to the screening and assessment page for the application `admin/candidates/{applicationId}/application`.
3. Mark all required (but not asset) skills as complete in the first step.
4. Confirm the step is marked as complete.
=> Remove asset skills from step validation

api/app/Notifications/VerifyEmail.php
🤖 Resolves #13707 
- Provides a larger codespace using all the alphabetical chars for email verification code
NOTE: I wasn't able to get the email to send to my account, but hopefully someone else can test it.
1. Build app
2. Create a new account
3. Use GC notify email as your contact email for testing
4. Send verification code, and ensure the code meets the requirements
=> [Feature] Expanded codespace for email verification

api/database/factories/AwardExperienceFactory.php, api/database/factories/CommunityExperienceFactory.php, api/database/factories/EducationExperienceFactory.php, api/database/factories/PersonalExperienceFactory.php, api/database/factories/WorkExperienceFactory.php, api/tests/Feature/Generators/__snapshots__/ApplicationDocGeneratorTest__testApplicationDocSnapshot__1.html, api/tests/Feature/Generators/__snapshots__/UserDocGeneratorTest__testUserProfileDocSnapshot__1.html
🤖 Resolves #14380
Stabilizes the document snapshots.
My theory is that bounding the date ranges by "now" is causing the instability in the end dates.  This changes the date ranges to be bound by the fixed range of 2010 - 2020.
I'm not sure.  Maybe wait a day and rerun CI tomorrow?
=> [Fix] Stabilize document snapshots

api/tests/Feature/Generators/__snapshots__/ApplicationDocGeneratorTest__testApplicationDocSnapshot__1.html, api/tests/Feature/Generators/__snapshots__/UserDocGeneratorTest__testUserProfileDocSnapshot__1.html
Updates: 
- `UserDocGeneratorTest__testUserProfileDocSnapshot__1.html`
- `ApplicationDocGeneratorTest__testApplicationDocSnapshot__1.html`
=> [Fix] Updates UserDocGeneratorTest, ApplicationDocGeneratorTest snapshots

apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx, apps/web/src/components/ScreeningDecisions/Trigger.tsx, apps/web/src/lang/fr.json, apps/web/src/lang/whitelist.yml
🤖 Resolves #14428.
This PR updates the `AssessmentTable` font weight for cells and headers.
2. Navigate to a candidate application
3. Verify font weight is `normal`
=> [Debt] Updates `AssessmentTable` font weight

apps/web/src/hooks/useRoutes.ts
🤖 Resolves #14512
The route method needed to be updated, to the new target
1. Go to a view candidate page
2. Click on profile link
=> [Bug] Outdated user profile on admin route

.github/workflows/lint.yml, .github/workflows/phpunit.yml, docker-compose.yml
🤖 Resolves #14498.
This PR updates postgres to its latest version for 12.
1. `make down; make up`
2. Verify everything works as before
=> [Tooling] Updates to `postgres:12.22`

api/Dockerfile, api/composer.json, api/composer.lock, api/programmatic-types.graphql, infrastructure/webserver.Dockerfile
🤖 Resolves #14499.
This PR updates our docker infrastructure to use PHP 8.4.10.
These commits were some additional fixes:
- 97be58e4bf51799c4b8d44340d00c6311815d532
- 1d6557fbff6e5528b6f183993c79f40c3dc9a765
1. `make down`
2. `docker compose build maintenance`
3. `docker compose build webserver`
4. `make up`
5. `make refresh-api; make seed-fresh; pnpm i; pnpm run build:fresh;`
=> [Tooling] Updates PHP to 8.4.10

apps/web/src/pages/Applications/ApplicationCareerTimelinePage/ApplicationCareerTimelinePage.tsx, apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx, packages/forms/src/components/HiddenInput/HiddenInput.tsx
🤖 Resolves #14479 
Updates the application page to use `HiddenInputs` instead of out basic `Input` component with the `hidden` prop. This should remove the unclear labels that were reported.
3. Delete any experiences you may have
4. Start an application
5. Continue thruogh the application until you get to the experience step
6. Confirm you cannot pass with no experiences stilll
7. Confirm AT does not notice a label or input
8. Contiune to the skills step
9. Repeat stesp 6-7
=> [Fix] Update hidden inputs on application pages

README.md
This PR adds a thanks section with Chromatic as they gave us 35k free snapshots.
=> Add Chromatic thanks

.github/workflows/chromatic.yml, .github/workflows/jest.yml, .github/workflows/lint.yml, .github/workflows/playwright.yml, .github/workflows/translations.yml, infrastructure/bin/deploy.sh, infrastructure/maintenance-container/Dockerfile, package.json
🤖 Resolves #14573.
Upgrades `pnpm` to the latest version: 10.
1. Update `npm install -g pnpm@10.17.0` 
2. Clean module folders `make clean-modules`
3. Install dependencies `pnpm install`
4. Build `pnpm build`
5. Confirm everything works as expected
=> [Debt] Upgrades `pnpm` to v10.17.0

.github/workflows/phpunit.yml
🤖 Resolves #14715 
Fixes the PHPUnit workflow by updating our package lists before instlaling them.
1. Confirm PHPUnit workflow works again
=> [Fix] PHPUnit workflow

documentation/style-guide.md
🤖 Resolves #12839 
Adds a short description of our preferred practices with TypeScript referencing the performance page.
1. Confirm the documentation is accurate
=> [Docs] Add TypeScript section to style guide

api/lang/fr/work_experience_gov_employee_type.php
🤖 Resolves #14685
Make requested changes in the enum localization file. Elected to make the change there per chatter in conversation
1. Observe changed copy in French view of `/fr/applicant/career-timeline/:id/edit`
2. Changes ripple elsewhere like card view
=> [Copy] Change enum French copy for `WorkExperienceGovEmployeeType`

apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/AssessmentDetailsDialog.tsx
🤖 Resolves #14756 
Fixes an issue where the assessment plan dialog was not updating without a page refresh.
Seems as though the `useForm` hook was only getting called when the form initiall enters the DOM. I beleive `react-hook-form` is pretty optimized to avoid re-renders so, even when `intialValeus` were updating, it avoided changing `defaultValues` since they are defaults, and not the live state. We had a reset but with no particular values so, it always reset to the defaults. 
This adds an effect to sync those states up whenever the `initialValues` change.
3. Create a pool with atleast one skill
4. Go to the assessment plan
5. Add a screening question
6. Edit that screening question (without refreshing the page)
7. Go back to edit …
=> [Fix] Assessment plan form dialog not updating
