GCTC-NTGC/gc-digital-talent

- api/package-lock.json
- api/package.json
- graphql.config.yml
Resolves #17, sort of.
Adding a graphql.config file to the project root enables syntax highlighting of graphql schema in VSCode, provided you have the GraphQL extension. This is particularly nice for highlighting syntax errors.
I tried to set up full linting as well, using [graphql-eslint](https://github.com/dotansimha/graphql-eslint), to enforce certain style guidelines. However, I kept running into the following error, and was unable to resolve it:
```
0:0  error  Parsing error: Unable to find any GraphQL type definitions for the following pointers:
- graphql/schema.graphql
```
I am giving up on linting for now, as we do not have many graphql files and should be able to maintain style consistency ourselves.
> Add graphql.config file, enabling GraphQL tools in VSCode

- admin/.storybook/preview.js
- admin/resources/js/components/H2Components/InputLabel.tsx
- admin/resources/js/components/H2Components/InputWrapper.tsx
- admin/resources/js/stories/InputWrapper.stories.tsx
- admin/resources/views/dashboard.blade.php
This component combines the Input error, label, and context. By passing the actual <input> element in as children, it can be used for various kinds of inputs.
When InputError (#130) and InputContext (#131) tasks are complete, they should be added to InputWrapper.
> Create InputWrapper component to combine Input error, label and context.

- admin/resources/js/stories/H2Components/Button.stories.tsx
- admin/resources/js/stories/form/Input.stories.tsx
- admin/resources/js/stories/form/TextArea.stories.tsx
Replaces [deprecated](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args) argType.defaultValue.
`argType.defaultValue` is deprecated and will be removed in Storybook 7.0.
> Bugfix - Storybook stories deprecated warning

- api/graphql/schema.graphql
Resolves #398 
`@belongsTo` directive only applies to Type field definitions, not Input fields.
> Remove @belongsTo directive from Input field definitions

- admin/resources/js/api/departmentOperations.graphql
- admin/resources/js/api/generated.ts
- Creates department graphql operations including: query single department, query all departments, create department mutation, and update department mutation.
> Department graphql operations

- api/database/migrations/2021_09_13_180950_create_departments_table.php
Resolves #503.
In the `infrastructure` folder, run the following so that the departments table gets the new column type change and uuid values:
```
docker-compose exec -w /var/www/html/api php sh -c "php artisan migrate:fresh"
docker-compose exec -w /var/www/html/api php sh -c "php artisan db:seed"
```
> Update departments table id column type to uuid

- common/src/components/form/Checkbox/Checkbox.tsx
- common/src/components/form/Input/Input.tsx
- common/src/components/form/Radio/Radio.tsx
Ran into this error right now with typescript complaining that the `capture` attribute does not exist on the input element. I omitted it for now since the attribute isn't something we need/will need.
> Bugfix - Omit capture attribute from input props (Radio, Input, Checkbox)

- admin/routes/web.php
Resolves #726
Lumen used a different format for wildcard routes, it was no longer working after upgrading the project to Laravel.
> Change wildcard url to use Laravel format

- admin/resources/js/api/generated.ts
- admin/resources/js/api/poolOperations.graphql
- admin/resources/js/components/pool/CreatePool.tsx
- admin/resources/js/components/pool/PoolTable.tsx
- admin/resources/js/components/pool/messages.ts
- admin/resources/js/components/user/UpdateUser.tsx
- api/app/Models/Pool.php
- api/database/factories/PoolFactory.php
- api/database/migrations/2021_11_02_142947_update_pools_table_with_key_column.php
- api/database/seeders/PoolSeeder.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- common/src/api/generated.ts
- common/src/components/form/Input/Input.tsx
- talentsearch/resources/js/api/generated.ts
Resolves #1008 
This ~can~must now be set when a Pool is created. It's more descriptive than a UUID, making it easier to refer to in code to specify a particular pool (eg on the talentsearch page).
> Add 'key' field to Pools

- api/app/GraphQL/Scalars/KeyString.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
This PR adds a KeyString scalar type to the GraphQL schema and updates the types of the key fields from String to KeyString.  The API service will now validate the keys with the same regex used in the frontend to ensure that valid strings are used for the keys.
Solves #1084
> Add KeyString scalar to backend-validate keys

- admin/resources/js/components/classification/CreateClassification.tsx
- admin/resources/js/components/classification/UpdateClassification.tsx
- admin/resources/js/components/cmoAsset/CreateCmoAsset.tsx
- admin/resources/js/components/cmoAsset/UpdateCmoAsset.tsx
- admin/resources/js/components/department/CreateDepartment.tsx
- admin/resources/js/components/department/UpdateDepartment.tsx
- admin/resources/js/components/operationalRequirement/CreateOperationalRequirement.tsx
- admin/resources/js/components/operationalRequirement/UpdateOperationalRequirement.tsx
- admin/resources/js/components/pool/CreatePool.tsx
- admin/resources/js/components/pool/UpdatePool.tsx
- admin/resources/js/components/poolCandidate/CreatePoolCandidate.tsx
- admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx
- admin/resources/js/components/user/CreateUser.tsx
- admin/resources/js/components/user/UpdateUser.tsx
- common/src/messages/errorMessages.ts
- talentsearch/resources/js/components/request/CreateRequest.tsx
Convert form validation error messages in common/src/messages/errorMessages.ts from plain strings to strings that can be localized.
Prettier removed the unneeded wrapper element in UpdatePoolCandidate.tsx as well.
Closes #1039
> Localize form validation error messages

- api/composer.json
- api/composer.lock
Resolves #1249 by requiring a compatible version of psr/cache in `/api`.
This [Dependabot PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1204/commits/a68e3aa28beca457fa8cfd676972594cb1f31b94#diff-1b2cd3a72459c07fc1894484568dad080f874329e95cd8e83538df0cacf69fcbR261) added psr/cache and resolved to using the [newest version (3.0.0)](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1204/commits/a68e3aa28beca457fa8cfd676972594cb1f31b94#diff-1b2cd3a72459c07fc1894484568dad080f874329e95cd8e83538df0cacf69fcbR3755), which requires PHP 8.0+ (we are currently using [PHP 7.4](https://github.com/GCTC-NTGC/gc-digital-talent/blob/66a9dab4b858865efd7001d93567b236c8059bd5/infrastructure/maintenance-container/Dockerfile#L8)).
> API - Update psr/cache to compatible version

- admin/resources/js/components/poolCandidate/CreatePoolCandidate.tsx
- admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx
- admin/resources/js/components/user/CreateUser.tsx
- admin/resources/js/components/user/UpdateUser.tsx
Closes #1272 
This branch sets the input type to email instead of text for a few email form fields that were missing it.  This allows the user's browser to ensure the email addresses appear well formed before submission.
> Set input type to email for email fields

- admin/.env.example
- admin/app/Http/Controllers/AuthController.php
- admin/config/oauth.php
- admin/routes/web.php
- infrastructure/php-container/src/.htaccess
This branch adds an auth-callback route to the web root.  This allows the auth redirect URI to be either {{host}}/admin/auth-callback (as before) or {{host}}/auth-callback (as requested in the issue).  This is accomplished by adding a new rewrite rule to the .htaccess file and adding a new route in the admin application's web.php file.
To test this you can add a new client to the auth app with a redirct uri of `http://localhost:8000/auth-callback` and ~update the redirect uri strings in the admin app's AuthController.php file~ set the OAUTH_REDIRECT_URI value in the admin project's .env file.
Closes #1266
> Add auth-callback route to web root

- api/app/Models/PoolCandidate.php
Fixes orFilterByClassificationToSalary function handling of filtering by zero classifications.  Instead of crashing the function simply returns the same query builder unchanged.
Closes #1379
> Fix handling for filtering by zero classifications

- api/composer.json
- api/composer.lock
With the addition of the PHP platform dependency in the composer.json file the explicit dependency on psr/cache is no longer necessary.  Removing the explicit dependency will allow composer to resolve the best version automatically going forward.  After removing the dependency, composer resolved the same version of psr/cache as was previously hard-coded and the lock file remains mostly unchanged.
Closes #1255
> API - Remove explicit dependency on psr/cache

- admin/app/Http/Controllers/AuthController.php
The branch allows a user to add a `from` url parameter to the login so that they are automatically redirected to the desired location after logging in.  
For example, [http://localhost:8000/admin/login?from=%2Fadmin%2Fusers](http://localhost:8000/admin/login?from=%2Fadmin%2Fusers) should send the user to the users page after logging in.
If no url parameter is provided then they will be redirected to the default page as usual.  It should work with both local auth and SiC.
I'm concerned about this feature adding an [open redirect vulnerability](https://sec.okta.com/articles/2021/02/stealing-oauth-tokens-open-redirects) to the site.  For example, if there was a link to http://llocalhost:8000/admin/login?from=badsite.evil then the token could be stolen.  I have limited to redirect to …
> Add login redirect from parameter

- .vscode/settings.json
- admin/.eslintrc
- talentsearch/.eslintrc
- talentsearch/package-lock.json
- talentsearch/package.json
Branch fixes a few linting warnings:
- add missing dev dependency on eslint-import-resolver-alias
- exclude generated.ts and webpack.mix.js from linting
- exclude .eslintrc from cspell
Closes #1527
> Fix linting warnings

- .vscode/.gitignore
- .vscode/launch.json.example
- admin/tsconfig.json
- admin/webpack.mix.js
- talentsearch/tsconfig.json
- talentsearch/webpack.mix.js
This branch enables Typescript debugging in VS Code.  It enables sourcemap generation and provides example debugging profiles for Chrome and Firefox.  To test it:
1) `npm run dev`
2) Copy desired profiles from launch.json.example to launch.json
3) In the _Run and Debug_ pane choose the profile and click _Start Debugging_
Possible Bugs:
- When I first visited http://localhost:8000/admin in both Firefox and Chrome I got a cached 302 redirect to /admin/public/admin.  I'm not sure why it happened and it might just be my machine.  I clicked the _Disable Cache_ option in my browser's tools and it never happened again. 🤷‍♂️
Chrome Notes:
- It seems like the built-in debugging extension does not support auto-reload on changes.
- The example debugging profile should automatically create a new …
> Enable Typescript Debugging in VS Code

- api/app/Http/Middleware/AuditQueryMiddleware.php
- api/config/lighthouse.php
This branch adds logging of admin requests to the API subproject.  Works for queries from the site or the GraphQL playground.  If the user is unauthenticated or does not have the ADMIN role then no entry is logged.
By default the entries are logged to the daily file in api\storage\logs.  They look like this:
```
[2021-12-30 15:27:18] local.INFO: GraphQL request from admin user [admin@test.com] {"operationName":null,"variables":[],"query":"{
me {
email
}
}
"} 
```
Closes #1538
> Log admin requests

- api/app/Models/Classification.php
- api/app/Models/CmoAsset.php
- api/app/Models/OperationalRequirement.php
- api/database/factories/ClassificationFactory.php
- api/database/factories/CmoAssetFactory.php
- api/database/factories/OperationalRequirementFactory.php
- api/tests/PoolCandidateTest.php
Closes #500 
Creates tests for the `countPoolCandidates($where: PoolCandidateFilterInput)` query. I wrote tests for each filter type:
- testFilterByClassifications
- testFilterByCmoAssets
- testFilterByDiploma
- testFilterByEmploymentEquity
- testFilterByLanguageAbility
- testFilterByOperationalRequirements
- testFilterByWorkRegions
- testFilterByPools
- testFilterByClassificationToSalaryRange (one of the assertions occasionally fails. still looking into it)
> Feature - Candidate count unit tests

- api/composer.json
Allows composer to run without asking for permission to run the `composer/package-versions-deprecated` plugin.
Closes #1643
> Allow composer plugin

- api/database/seeders/DatabaseSeeder.php
When I merged in #1674 it duplicated the truncateTables function.  This is a quick fix for that issue.
> Fix seeder merge issue

- api/app/Providers/BearerTokenServiceProvider.php
- api/config/oauth.php
This branch reconfigures the bearer token service to use the config helper function rather than using the environment variables directly.
Closes #1524
> Update env variables to use the config helper

- admin/resources/js/components/classification/CreateClassification.tsx
- admin/resources/js/components/classification/UpdateClassification.tsx
- admin/resources/js/components/cmoAsset/UpdateCmoAsset.tsx
- admin/resources/js/components/operationalRequirement/UpdateOperationalRequirement.tsx
- admin/resources/js/components/pool/UpdatePool.tsx
- admin/resources/js/components/poolCandidate/UpdatePoolCandidate.tsx
- common/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- common/src/components/form/Select/Select.stories.tsx
- talentsearch/resources/js/stories/SearchForm.stories.tsx
This branch switches all imports of lodash from importing the entire module to importing individual features from their respective files.  This reduces the final bundle size that the user must download to use the application.  https://selleo.com/til/posts/0ac258eyv8-decrease-bundle-size-by-importing-lodash-correctly
The Talent Search pageContainer.js bundle is reduced from 9.33 MiB to 7.95 MiB (15% reduction).
The Admin dashboard.js bundle is reduced from 12.5 MiB to 9.81 MiB (22% reduction).
Closes #1596
> Switch lodash imports to defaults from respective files

- admin/webpack.mix.js
- common/src/components/Footer/Footer.tsx
- common/src/fakeData/fakePoolCandidates.ts
- common/src/fakeData/fakeSearchRequests.ts
- talentsearch/webpack.mix.js
This branch stabilizes the fake data that appears in the storybook stories.  This should allow Chormatic to accurately highlight the changes in a PR instead of finding false positives on each one.
- switch fake data generators from `faker.date.future()` and `faker.date.past()` to `faker.date.between()`
- switch footer from `currentDate()` to a build date calculated by webpack on compilation and a fallback for storybook
Closes #1761
> Stabilize storybook fake data

- admin/hydrogen.config.json
Reticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/1779#issuecomment-1014982666 (Fixes issue in https://github.com/GCTC-NTGC/gc-digital-talent/pull/1767)
Offering this fix for quick merge to get mainline components looking correctly again.
cc @JoshBeveridge for h2 feedback
cc @yonikid15 for merge
> Bugfix: Added talentsearch path to admin project's hydrogen config

- .bundlewatch.config.js
- .github/workflows/bundlewatch.yml
- package.json
A fresh redux of https://github.com/GCTC-NTGC/gc-digital-talent/pull/1449
This will add a workflow like so to the bottom of PRs (takes about 6 minutes to complete), using a CLI and service called bundlewatch:
Unlike chromatic, this workflow **requires no special auth**: it simply pushes a minimal amount of data to an unauthenticated, hosted service, which generates a pretty summary page. Clicking the "Details" link in the status check takes you to this page:
Notable caveat: This tool and service are admittedly unmaintained for the past 2 years. But to be totally sincere, it has worked perfectly for me for since then, despite some complaining in the issue queue about lack of support. (The maintainer joined Dropbox and only works on private repos now.) The hosted service is really nice, and …
> Monitor front-end bundlesize changes

- common/src/components/Chip/Chip.stories.tsx
- common/src/components/Chip/Chip.tsx
- common/src/components/Chip/index.ts
- common/src/components/Pill/Pill.stories.tsx
- common/src/components/Pill/Pill.tsx
This branch adds a new chip component
- Sends event up when dismissed
- Adds storybook stories
- Based on the pill component
- Only dismissed when the X is clicked, not the entire pill
- Similar to provided wireframe
The wireframe has chips with no colour in them so I created a new "neutral" set of colours in the `colorMap` objects.  They're OK but it seems like the gray colours in our hydrogen config file are not matching the Design Foundations document so it's not exactly the same.
Closes #1685
> New Component - Chip

- .github/workflows/bundlewatch.yml
- .github/workflows/storybook.yml
This PR:
- Locked workflows' Node versions using `admin/.nvmrc` (arbitrarily chose the sub-project seemingly most active)
- Locked workflows' NPM versions to 8.3.0 (instead of floating with `latest`, so CI will only change when we change it)
- Only run storybook workflow when appropriate files change
- Only run storybook workflow on mainline pushes, and PRs
> Improve workflow config

- .github/workflows/bundlewatch.yml
Resolves #1848 
This was what was happening in a [main repo dependabot PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1839) (note the lack of bundlesize summary check being written, since dependabot doesn't have permission):
This is the fix applied in a [test dependabot PR within my own  fork](https://github.com/patcon/gc-digital-talent/pull/44):
> Explicitly enable dependabot to write status checks in PRs.

- .vscode/settings.json
- frontend/admin/.eslintrc
- frontend/admin/package.json
- frontend/common/.eslintrc
- frontend/common/package.json
- frontend/package-lock.json
- frontend/talentsearch/.eslintrc
- frontend/talentsearch/package.json
This branches fixes the eslint rules:
- Update VS code settings to locate working directories one level deeper
- Update eslintrc files to properly use formatjs plugin
Fixes #1807
> Fix eslint rules

- .github/dependabot.yml
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/1855#issuecomment-1020629661
This will use dependabot PRs to update external github actions, like here:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/e24472cb3fbabc03ce6c470e8a7efe40a1b3aa63/.github/workflows/bundlewatch.yml#L39
and docker images like here:
https://github.com/patcon/gc-digital-talent/blob/39c1ad507912c40e86a9817259bbe5b35ca79cea/api/Dockerfile#L1
> Added dependabot config for docker images and github actions

- .github/workflows/check-lighthouse-schema.yml
- api/Dockerfile
- infrastructure/docker-compose.yml
Addresses #1775 
This PR:
- adds a dockerfile for multi-stage build of php-based api container image
- in the docker-compose.yml file, this new service is under its own "profile". This ensures that `docker compose up` won't build/run this new container, unless explicitly requested with `docker compose --profile=new up` or `docker compose up api`
- added a workflow to run the new api container. After starting container, the workflow will:
- generate the lighthouse-schema.graphql in the container,
- copy the file from container to the CI workspace,
- check whether the git workspace has new, uncommitted changes (from that file)
- if so, it fails the build
Note, this new `api` container:
1. reflects a proof-of-concept for a more conventional way to run docker containers (minimal build …
> Added workflow (and container) to generate and confirm up-to-date graphql schema

- .vscode/launch.json
I noticed the Jest debug definitions didn't quite work.  I updated it for common (which I was working on).  Is this useful to anyone else?  Do you want me to create the profiles for talentsearch and admin?
> Update VS Code Jest debug definition

- frontend/common/src/components/Header/Header.tsx
- frontend/common/src/components/LanguageRedirectContainer/LanguageRedirectContainer.test.tsx
- frontend/common/src/components/LanguageRedirectContainer/LanguageRedirectContainer.tsx
- frontend/common/src/helpers/localize.test.ts
- frontend/common/src/helpers/localize.ts
This branch solves an issue where the URL search parameters are lost by the language redirect container.  It also adds a Jest test to verify.
Closes #1866
> Preserve search in language redirect

- frontend/admin/resources/js/adminRoutes.ts
- frontend/admin/resources/js/api/skillOperations.graphql
- frontend/admin/resources/js/components/PoolDashboard.tsx
- frontend/admin/resources/js/components/skill/SkillPage.tsx
- frontend/admin/resources/js/components/skill/SkillTable.tsx
- frontend/admin/resources/js/stories/Skill.stories.tsx
- frontend/admin/resources/js/stories/SkillFamily.stories.tsx
- frontend/common/src/fakeData/fakeSkillFamilies.ts
- frontend/common/src/fakeData/fakeSkillFamiliesWithSkills.ts
- frontend/common/src/fakeData/fakeSkills.ts
- frontend/common/src/fakeData/index.ts
This branch adds:
- A page and table for listing skills
- The sidebar link and route to navigate to the page
- The GraphQL operation for retrieving all the skills from storage
- A Storybook story for the table
There's a bit of refactoring around fake skill and skill families as well.  Since the two data sets are interdependent they cause recursion when being generated.  My solution was to add the function `fakeSkillFamiliesWithSkills` to generate the two independently and then combine them.
Closes #1679
> Admin - add skill page and table

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/resources/js/api/userOperations.graphql
- frontend/admin/resources/js/components/classification/UpdateClassification.tsx
- frontend/admin/resources/js/components/user/CreateUser.tsx
- frontend/admin/resources/js/components/user/UpdateUser.tsx
- frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
- frontend/common/src/components/form/Select/Select.tsx
- frontend/common/src/constants/localizedConstants.tsx
This branch adds to the admin site the ability to edit the user's auth fields. The sub and roles fields can be set when creating or updating users.
Closes #1898
> Add auth fields to create/update users in admin

- frontend/admin/package.json
- frontend/common/package.json
- frontend/talentsearch/package.json
I found an apparent globbing issue in the translation extraction scripts while working on PR #1958 .  Maybe it only exists on Linux?  I put the updates here instead of inside that PR.
> Fix translation extract command

- frontend/common/src/fakeData/fakeSkillFamilies.ts
- frontend/common/src/fakeData/fakeSkillFamiliesWithSkills.ts
- frontend/common/src/fakeData/fakeSkills.ts
This branch stabilizes the fakeSkillFamiliesWithSkills function to enable accurate Chromatic diffs.  It seems like the faker.js `unique` function does not work very well and prevents repeatable results.  Also, the seed reset was missing.
Closes #1954
> Stabilize fakeSkillFamiliesWithSkills

- frontend/talentsearch/resources/js/components/search/SearchHeading.tsx
Resolves #1968 
Quick hacky fix for the layout on the French search page. It relies on the length of the titles not changing, but they probably won't change for a while. Until I can come up with something better, I think this should suffice.
> Bugfix - Quick fix search page heading layout

- api/app/Providers/AuthServiceProvider.php
- api/config/oauth.php
Resolves #2033 
If AUTH_DEFAULT_USER env variable is set to a valid user email, then any requests to api _without a bearer token_ will be treated as authenticated as the the default user. This allows you to act as a different user if you _do_ provide a proper bearer token.
I originally tried to implement this as a third implementation of BearerTokenServiceInterface, but BearerTokenServiceInterface is only used if a bearer token _is_ present. Also, I like that in this implementation, the user can fall back on the normal BearerTokenServiceInterface if they do provide a token.
To test:
- Start logged out, and try to access the admin dashboard. You should get authentication errors.
- set `AUTH_DEFAULT_USER=admin@test.com` in api/.env . You should now have full access to admin dashboard.
> Add option of treating un-authorized requests as a default user

- api/database/seeders/UserSeederLocal.php
- frontend/admin/.env.example
- frontend/admin/app/Http/Controllers/AuthController.php
- frontend/admin/config/app.php
Resolves #2044
Our app is hosted behind a proxy in production, so redirecting from the server to a url path won't work, we need to be able to add the domain of the frontend url.
I set the AuthController to use the root APP_URL instead of ADMIN_APP_URL, because the `from` parameter includes the entire domain, including the `/admin`. And since ADMIN_APP_URL wasn't being used anywhere else, I removed it from .env.example. I added an explicit APP_URL in .env.example, but it defaults to localhost in the config file, so the app should work even without changing your .env file.
One unfortunate consequence of this strategy is that if you navigate straight to `/admin/login` like we were doing before, without entering a from parameter, you will be redirected back to the main landing page, which …
> Use root app url in login redirect

- frontend/talentsearch/resources/js/components/awardDetailsForm/AwardDetailsForm.tsx
- frontend/talentsearch/resources/js/components/educationExperienceForm/EducationExperienceForm.tsx
This mini-PR is a followup to #2084 and #2079.
It uses the new sort functionality to sort the new education form.
> Add sort options for eduction experience form

- frontend/common/src/components/tabs/Tab.tsx
- frontend/common/src/components/tabs/tabs.stories.tsx
- frontend/talentsearch/resources/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.stories.tsx
- frontend/talentsearch/resources/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.tsx
- frontend/talentsearch/resources/js/components/skills/AddSkillsToExperience/index.ts
This branch composes the various skills components to an AddSkillsToExperience component.  It includes a Storybook story to view it.  The component emits add and remove skill events to a parent component.
Note that Jerbo requested that *Skills in demand* be changed to *Mainstream skills* so that will be different from the wireframe.
Note that there are a few weird button things going on like stray dots on the pagination and the cursor not changing to pointer in the skill lists.  I believe these are due to #1977.
Closes #1683
> Assemble add skills to experience component

- frontend/admin/.storybook/preview.js
- frontend/common/.storybook/preview.js
- frontend/talentsearch/.storybook/preview.js
Re-ticketed from: https://github.com/GCTC-NTGC/gc-digital-talent/issues/1974#issuecomment-1030216310
Small fix to prevent these missing background issues from catching us again (esp for components that we expect to have a background). White is still an option by selecting "reset" under "background color" of storybook chrome.
cc: @petertgiles
> Default storybook viewer background to off-white

- api/bootstrap/app.php
- api/config/logging.php
Resolves #2039 
I've tested this on Dev and UAT. This ensures that AuditQueryMiddleware writes correctly to the stdout log channel.
> Override default logging settings on api project

- frontend/admin/public/.htaccess
- frontend/admin/public/config.sjs
- frontend/admin/resources/js/adminConstants.ts
- frontend/admin/resources/views/dashboard.blade.php
- infrastructure/docker-compose.yml
- infrastructure/php-container/Dockerfile
Closes #2261
Based on [this trick](https://create-react-app.dev/docs/title-and-meta-tags/#injecting-data-from-the-server-into-the-page), this allows some environment variables to be injected directly into the html when served. ~I tried to do with this with pure PHP (instead of passing variables from the Laravel controller) so as to conflict as little as possible with #1387.~ Environment variables are injected using [Apache SSI](https://httpd.apache.org/docs/current/howto/ssi.html). Any environment variables that we want available at run-time like this must be defined in three places: the htaccess file, the config.sjs file, and the adminConstants file (or other _____Constants file).
To test, simply run `npm run dev` in frontend/admin, and try to login, then logout. The logout will fail if …
> Inject some constant into admin html at runtime

- .github/workflows/check-lighthouse-schema.yml
- api/.env.example
- api/config/app.php
- api/config/sanctum.php
Changes the environment variable used in the _API_ project from `API_APP_URL` to `APP_URL`.  The _API_ project uses this variable for post login redirect with the _from_ parameter.  So if _from_ is /admin/pools they will be redirected to API_APP_URL/admin/pools.  The value of API_APP_URL on the server is tbs-dev.whatever/api so you end up with tbs-dev.whatever/api/admin/pools which fails.  I've switched it to using the APP_URL variable which is just tbs-dev.whatever and can properly accept a relative url.  There's no routing for /api anyway so that variable may not even need to exist.
> API_APP_URL to APP_URL

- .github/workflows/check-lighthouse-schema.yml
The Check Schema workflow has been failing when it runs the command `docker compose up api --detach`, with the message `open /home/runner/work/gc-digital-talent/gc-digital-talent/frontend/admin/.env: no such file or directory`. 
I believe this is due to me adding a reference to admin/.env in the docker-compose file:
```
php:
env_file:
- ../frontend/admin/.env
```
This adds a step to the workflow to copy .example.env to .env, to ensure the docker-compose command can run correctly.
> Fix Check Schema workflow

- frontend/common/src/components/accordion/Accordion.tsx
- frontend/common/src/fakeData/fakeExperienceSkills.ts
- frontend/common/src/fakeData/fakeExperiences.ts
- frontend/common/src/fakeData/fakeSkills.ts
- frontend/talentsearch/resources/js/components/ExperienceAccordion/AnyExperience.tsx
- frontend/talentsearch/resources/js/components/ExperienceAccordion/ExperienceAccordion.stories.tsx
- frontend/talentsearch/resources/js/components/ExperienceAccordion/ExperienceAccordion.tsx
- frontend/talentsearch/resources/js/components/skills/SkillAccordion/SkillAccordion.stories.tsx
- frontend/talentsearch/resources/js/components/skills/SkillAccordion/SkillAccordion.test.tsx
- frontend/talentsearch/resources/js/components/skills/SkillAccordion/SkillAccordion.tsx
- frontend/talentsearch/resources/js/types/ExperienceUtils.ts
resolves #1926 
- extracted AnyExperience into its own file to reuse in skillAccordion
- Skill Accordion takes one 1 skill and parses the experienceSkills array to get the experience list tagged with that skill 
- added a sep story for each type of accordion
Todo:
> 1926-implement skill accordion

- api/app/Http/Controllers/AuthController.php
During final testing of our connection to the production SiC service, we realized that we no longer need to include acr_values=mfa in our request. MFA has been configured as mandatory for our SiC client account. Instead, we can set acr_values=gckey to enable gckey-passthrough, or sending users directly to the gckey login page, ignoring the option of signing in with a bank.
Related to #2252
> Update acr_values to enable gckey-passthrough

- frontend/admin/src/js/adminRoutes.ts
- frontend/admin/src/js/components/PoolDashboard.tsx
Oops, I forgot to remove the operational requirements admin menu link in #2374.  This branch removes it.
Closes #2401
> Remove Operational Requirements Menu Item

- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
Modifies the condition to display either the no candidates or the search pool message. First check if the candidate pool is greater than 0 and displays the search pool. Otherwise, if the candidate pool is 0 or less than 0, it will display the no candidate message along with the filter advice.
Resolves #2213 
I made a bit of an assumption that the entire box should be removed from the DOM rather than just the button referred to in the issue.
> fix: search pools render condition

- frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
This is a simple change to move the `<legend>` of our `<fieldset>` to be a direct child so they are properly associated for assistive technologies. There _should_ be **no visual changes**, just moving the markup around.
Resolves: #2425
> Move legend to be direct descendant of fieldset

- frontend/common/src/components/form/Checkbox/Checkbox.tsx
Resolves #2406 
Box label now clickable, no major changes in component functionality so it shouldn't have broken things (hopefully)
> Make bounded box contents clickable

- .github/workflows/storybook.yml
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/2075#issuecomment-1092813935
This is just sitting pretty for whenever we want to merge it. Going to mark as draft for now, unless someone wants to retired it out of draft mode and just merge.
cc: @petertgiles
> Ignore dependabot PRs from the Chromatic storybook workflow

- frontend/admin/.apache_env
- frontend/admin/.env.example
- infrastructure/docker-compose.yml
This branch factors out the environment variables used by Apache to a separate env file.  
This resolves #2327 by ensuring that an incomplete .env file is not used for php container construction resulting in some environment variables being unset in the container environment.
This resolves #2328 by ensuring that the env file needed for the php container creation is present in a fresh install environment instead of relying on a previous setup script run.
> Fix admin docker env

- frontend/admin/src/js/components/classification/ClassificationPage.tsx
- frontend/admin/src/js/components/cmoAsset/CmoAssetPage.tsx
- frontend/admin/src/js/components/dashboard/Dashboard.tsx
- frontend/admin/src/js/components/department/DepartmentPage.tsx
- frontend/admin/src/js/components/pool/PoolPage.tsx
- frontend/admin/src/js/components/poolCandidate/PoolCandidatePage.tsx
- frontend/admin/src/js/components/skill/SkillPage.tsx
- frontend/admin/src/js/components/skillFamily/SkillFamilyPage.tsx
- frontend/admin/src/js/components/user/UserPage.tsx
- frontend/common/src/components/Button/Button.tsx
- frontend/common/src/components/Link/Link.stories.tsx
- frontend/common/src/components/Link/Link.tsx
- frontend/talentsearch/src/js/components/applicantProfile/CancelButton.tsx
Introduced a new API for the `<Link>` component to apply the same styles found with the `<Button>` component to avoid having to nest interactive elements and improve accessibility.
Resolves #2423 
I did my best to make this as identical to the API for the `<Button>` component but we could make some changes to simplify.
```typescript
export interface LinkProps extends React.HTMLProps<HTMLAnchorElement> {
/** The style colour of the link */
color?: Color;
/** The style mode of the element. */
mode?: "solid" | "outline" | "inline";
block?: boolean;
type?: "button" | "link";
}
```
```tsx
import { Link } from '@common/components/Link';
...
<Link type="button" mode="solid" color="primary" href="/">Home</Link>
... 
```
My only thought is that for the **type** prop, instead of accepting `"link" | …
> 2423 buttons wrapped by links

- frontend/admin/src/.htaccess
- frontend/talentsearch/src/.htaccess
This branch changes the routing fallback file to an absolute path to avoid hitting the 10 rewrite limit in Apache on URLs with many segments.
~Note: leaving as draft until I can test on the dev server.~
Closes #2375
> Fix routing fallback location

- frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
The candidate search should properly pluralize the word _candidates_ for a result count of 1 in the search results:
Resolves #2370
> Talent Search - Pluralize Candidate Result Count #2370

- api/database/helpers/EnumsForFactories.php
- api/database/migrations/2022_04_13_190734_convert_overtime_enum.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateTest.php
- frontend/admin/src/js/stories/PoolCandidate.stories.tsx
- frontend/common/src/constants/localizedConstants.tsx
- frontend/common/src/lang/fr.json
- frontend/talentsearch/src/js/components/search/SearchForm.tsx
- frontend/talentsearch/src/js/components/workPreferencesForm/WorkPreferencesForm.tsx
Resolves #2477
This PR removes a value from the OperationalRequirements enums. If that value remains in the database anywhere, it can cause errors in GraphQL queries. To test:
1. Edit the database to enter a value of `["OVERTIME", "SHIFT_WORK"]` in the following tables & columns:
- users.accepted_operational_requirements
- pool_candidates.accepted_operational_requirements
- pools.operational_requirements
- pool_candidate_filters.operational_requirements
2. Go to http://localhost:8000/graphql-playground, run the following query. (Ensure you either have an admin bearer token, or have set AUTH_DEFAULT_USER=admin@test.com in api/.env) 
You should get an error, something like `Expected a value of type \"OperationalRequirement\" but received: OVERTIME`
```
query {
poolCandidates { …
```
> Update Conditions of Employment

- frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx
- frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
- frontend/admin/src/js/components/user/CreateUser.tsx
- frontend/admin/src/js/components/user/UpdateUser.tsx
Resolves #2455 
Removes required rule from multi-select inputs in PoolCandidate forms on Admin dashboard. An empty selection is reasonable for these fields.
Removes required rule from User telephone fields. 
Adds a default value for status field on new PoolCandidates, for convenience.
> Remove Required tag from some User & PoolCandidate fields

- frontend/talentsearch/src/js/components/request/CreateRequest.tsx
Resolves #2484 
Please remove the text indicated in the image from the search-request (summary?) page. This text is incorrect and does not need to be replaced by anything. Just take it out.
> Remove text from request summary page #2484

- tc-report/en/communities/digital-talent/index.html
- tc-report/fr/communities/digital-talent/index.html
Resolves #2485 
On the Digital Community page (https://talent.canada.ca/en/communities/digital-talent), update the date from "Spring 2021" to "Summer 2022".
French:
"lancée au printemps 2021" -> "lancé à l'été 2022"
> Small copy change for dates on Digital Community page #2485

- frontend/admin/src/js/components/ClientProvider.tsx
We were piping all urql errors to the toasts, displaying them to users which caused two issues.
1. Unfriendly error messages were being displayed to users
2. Came in the form of a long JSON string with no spaces which caused overflow issues
Stopped displaying the urql errors from the toasts since it is not friendly to users.
Resolves #2354 
If we are not currently, we should be logging these errors.
While it is still a good idea we come up with a character limit for toasts, I believe it should be a fairly soft one since a test was done with > 800 characters and, while not ideal, the toast handled the large amount of text decently. I believe that the main issue here was the lack of spaces which causes the odd overflow issues. As long as we ensure that friendly errors messages are being …
> Remove urql Errors from Toasts

- frontend/admin/src/js/components/dashboard/Dashboard.tsx
- frontend/talentsearch/src/js/components/PageContainer.tsx
This is a simple one to add the `main` landmark which allows to [easier navigation](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/at.html) for assistive technology users. As a fall back, we have also added a "skip to main content" link so users accessing the tools with assistive technology that do not support landmarks can still skip the main navigation.
Landmarks Ref: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/main.html
Skip Links Ref: https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html
Resolves: #2427 and #2426
> A11y - 2427 document landmarks

- frontend/admin/src/js/components/dashboard/Dashboard.tsx
- frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.tsx
- frontend/talentsearch/src/js/components/search/SearchPools.tsx
Resolves #2441 
So, I know this is extremely niche but font weight 100 on Firefox in Linux (Pop OS) is too light to easily see.
image.png
When I bump it up to 200 it looks much better.
image.png
On Chromium in Linux and on Windows (Firefox, Chrome, and Edge) it looks heavier and there is no difference between 100 and 200. This makes me think that the font in Firefox in Linux ([Fira Sans](https://fonts.google.com/specimen/Fira+Sans)) is the only one that actually has font weight light enough to show a realistic 100. Could we bump all the uses of 100 up to 200?
Test in Lighthouse for contrast ratio
> Font weight 100 too light on Firefox Linux #2441

- api/app/Models/PoolCandidate.php
- api/tests/Feature/PoolCandidateTest.php
This branch adds a test to demonstrate, and a fix for, a search bug in the talent site.  If a pool candidate has a null field for operational requirement they are not returned when searching for candidates without an operational requirement filter.
The solution is simply to test for an empty filter clause and not populate the filter in the query.
I don't think any of the other fields have the same bug.  Only Work Locations uses the same JsonContains function and it works differently by building the query with a ForEach loop.
Closes #2516
> Fix null operational requriement handling for search

- .github/workflows/docker-smoke-test.yml
Addresses https://github.com/GCTC-NTGC/gc-digital-talent/issues/2536
This does the following:
- creates a workflow that spins up the docker environment
- run it on pushes to "main" branch and any PRs, but skip if only markdown files have changed
- a series of tests are run that confirm:
- there's no site served at first from /talent
- the setup.sh completes successfully
- a specific app successfully served for each of 4 paths after this
- the app is broken intentionally and confirmed as such (deleting index.html)
- the refresh_all.sh script completes successfully
- a specific app successfully served for each of 4 paths after this
- this also adds docker layer caching between runs
- a little github action that cancels other running workflows, to keep two pushes from running at once (since …
> Added smoke tests for setup scripts and docker environment

- .editorconfig
- .github/workflows/docker-smoke-test.yml
- .github/workflows/e2e-tests.yml
- .gitignore
- frontend/cypress.json
- frontend/cypress/README.md
- frontend/cypress/fixtures/example.json
- frontend/cypress/integration/talentsearch/footer.spec.js
- frontend/cypress/integration/talentsearch/language-selection.spec.js
- frontend/cypress/integration/talentsearch/static-pages.spec.js
- frontend/cypress/plugins/index.js
- frontend/cypress/reporters-config.json
- frontend/cypress/support/commands.js
- frontend/cypress/support/index.js
- frontend/package-lock.json
- frontend/package.json
- infrastructure/docker-compose.yml
Resolves https://github.com/GCTC-NTGC/gc-digital-talent/issues/1762
- footer
- static pages (ToS and privacy)
- language selection page
- layers cached between workflows: docker smoke tests, and past runs of this
- https://github.com/archfz/cypress-terminal-report
- https://github.com/EnricoMi/publish-unit-test-result-action
- https://docs.cypress.io/guides/tooling/reporters#Reporter-Options
- https://github.com/bhovhannes/junit-report-merger
- https://github.com/you54f/cypress-multi-reporters
> Create spike for Cypress E2E testing

- frontend/admin/src/js/adminConstants.ts
- frontend/admin/src/js/components/GlobalFilter.tsx
- frontend/admin/src/js/types/react-table-config.d.ts
- frontend/common/src/components/form/BasicForm.tsx
- frontend/common/src/types/utilityTypes.ts
- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/types/react-table-config.d.ts
- frontend/talentsearch/src/js/types/utilityTypes.ts
resolves #2487 
Some "ignores", some fixes. 
I would like to figure out a way to get rid of the remaining `any` in /searchContainer
> linting - type any

- frontend/admin/.eslintrc
- frontend/admin/src/js/components/dashboard/Dashboard.tsx
- frontend/admin/src/js/components/searchRequest/SearchRequestTable.tsx
- frontend/common/src/helpers/router.tsx
- frontend/common/src/hooks/useDeepCompareEffect.ts
- frontend/indigenousapprenticeship/.eslintrc
- frontend/indigenousapprenticeship/src/js/components/PageContainer.tsx
- frontend/talentsearch/.eslintrc
- frontend/talentsearch/src/js/components/PageContainer.tsx
- frontend/talentsearch/src/js/components/search/SearchForm.tsx
This branch addresses the [exhaustive deps](https://github.com/facebook/react/issues/14920) linting warnings we have in our code base.  I found four instances.
c6872c2a8d6d2b7e8e590d466b5f3c42e7179a98 solves the warning in router.tsx.  The solution provided is to stabilize the "not found" component in the parent by storing it in a ref.  This way it can be safely added to the dependency list without triggering continuous rendering.
8330f66cb16a336719b374b15446c230313e9c31 solves the warning in SearchRequestTable.tsx.  The missing dependency can be added without any issues.
aa27bdd4382b2e0c8ae0bc4115153895ee747cce solves the warning in SearchForm.tsx.  The solution provided stabilizes the debounce function in a ref.  The debounce function needs to be a single instance for the life of the …
> Fix exhaustive deps linting errors

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx
This fixes an issue when a user had previously set a classification under the Government Information and reset to student (who should not have a classification), the classification would not be disconnected from the user.
Resolves #2577 
- Made the ClassificationBelongsTo connect argument optional
- Added a disconnect option to remove the relationship
- Updated form logic to disconnect when student was selected as type
> Bug - 2577 - fix classification not being removed when student

- frontend/admin/webpack.base.js
- frontend/indigenousapprenticeship/webpack.base.js
- frontend/talentsearch/webpack.base.js
This branch fixes the loading of build-time environment variables in webpack.
Closes #2566
> Add dotenv loading in webpack

- frontend/admin/.eslintrc
- frontend/admin/src/js/components/Table.tsx
- frontend/common/.eslintrc
- frontend/common/src/components/form/Checkbox/Checkbox.tsx
- frontend/common/src/components/inputPartials/Fieldset/Fieldset.stories.tsx
- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
- frontend/indigenousapprenticeship/.eslintrc
- frontend/talentsearch/.eslintrc
- frontend/talentsearch/src/js/components/skills/SkillChecklist/SkillChecklist.tsx
resolves #2563 
Think I got all them and fixed without things getting funky. One I'm not sure is properly fixable, it wants the label to nest around `<inputs>` and I think the input label being structured as it is makes it throw errors. To fix it might require refactoring the inputs group of components?
> linting - jsx a11y errors

- frontend/admin/.storybook/preview.js
- frontend/admin/src/js/components/IntlContainer.tsx
- frontend/common/src/lang/index.ts
- frontend/indigenousapprenticeship/.storybook/preview.js
- frontend/indigenousapprenticeship/src/js/components/IntlContainer.tsx
- frontend/talentsearch/.storybook/preview.js
- frontend/talentsearch/src/js/components/IntlContainer.tsx
Was only able to find one instance of this in the compiled french in `/common/src/lang/index.ts`. This has been updated to be a default export and each file importing it has ben updated to reflect that.
Resolves #2493
> Debt - 2493 - Prefer Default Export

- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
When changing the spinner to be more accessible and its own component, we moved the candidateResults to its own component to avoid nesting ternary operations. When this was done, we passed a reference of the function rather than calling it to have it render. 
This is a simple change to call the `candidateResults` function to actually render this component.
Resolves #2668
> Bug - 2668 - Fix Missing Request Button

- frontend/common/package.json
- frontend/common/src/fakeData/fakeExperiences.ts
- frontend/common/src/fakeData/fakePoolCandidateFilters.ts
- frontend/common/src/fakeData/fakePoolCandidates.ts
- frontend/common/src/fakeData/fakePools.ts
- frontend/common/src/fakeData/fakeSearchRequests.ts
- frontend/common/src/fakeData/fakeSkillFamilies.ts
- frontend/common/src/fakeData/fakeSkills.ts
- frontend/common/src/fakeData/fakeUsers.ts
- frontend/package-lock.json
This replaces the deprecated `faker.random.arrayElement()` with the new `faker.helpers.arrayElement()`.
Resolves #2624
> Fix deprecated @faker-js/faker functions

- .github/workflows/storybook.yml
It seems as though github actions and dependabot have made some changes and the way we were disabling it is no longer the accepted method. Instead of ignoring branches as we were, we have added a conditinola in the job to not run if the actor is dependabot.
Refs: 
- https://github.community/t/how-to-stop-github-actions-workflow-to-trigger-when-the-pull-request-is-from-dependabot-preview/116486/3
- https://stackoverflow.com/questions/71679568/github-actions-ignore-or-exclude-dependabot-pull-requests
Resolves #2625
You can test locally with [nektos/act](https://github.com/nektos/act).  To run just the storybook workflow with and without dependabot actor:
```sh
act -W ./.github/workflows/storybook.yml pull_request
act -a "dependabot[bot]" -W ./.github/workflows/storybook.yml pull_request
``` …
> Bug - 2625 - Disable Chromatic for dependabot

- frontend/admin/src/js/components/PoolDashboard.tsx
- frontend/admin/src/js/components/home/HomePage.tsx
- frontend/admin/src/js/dashboard.tsx
- frontend/common/src/components/CardLink/CardLink.stories.tsx
- frontend/common/src/components/CardLink/CardLink.tsx
- frontend/common/src/components/CardLink/cardLink.css
- frontend/common/src/components/CardLink/index.ts
- frontend/common/src/components/PageHeader/PageHeader.stories.tsx
- frontend/common/src/components/PageHeader/PageHeader.tsx
- frontend/common/src/components/PageHeader/index.ts
- frontend/common/src/components/PageHeader/pageHeader.css
This creates a placeholder for the admin homepage along with two new supporting components in the `common` project.
Resolves #2634 
As I understand it, this page should only appear when an anonymous user navigate to the admin. As a result, it should redirect to the dashboard if a logged in user navigates to `/admin`. I wrote some preliminary logic for this but am unsure if what is there can be considered best practice. I essentially checked the `AuthContext` to see if the user was logged in, if they were not the page would navigate to a path (soon to be dashboard).
See: [HomePage.tsx:20-24](https://github.com/GCTC-NTGC/gc-digital-talent/blob/061e6cef9d7a2973dfac7bece424ae32be1b3fc8/frontend/admin/src/js/components/home/HomePage.tsx#L20)
```tsx
const { loggedIn } = …
```
> Feature - 2634 -  Admin Homepage Placeholder

- .github/workflows/check-lighthouse-schema.yml
Resolves #2725 
Our `check-lighthouse-schema.yml` workflow was passing with errors due to [a bug with the chosen action](https://github.com/UnicornGlobal/has-changes-action/issues/5). This PR replaces the existing library with a simple custom command which is properly reporting failures as seen in the [test PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2724).
Ref: https://github.com/GCTC-NTGC/gc-digital-talent/runs/6427201880?check_suite_focus=true
> Bug - 2725 - Fix Schema Check Action

- api/app/Models/User.php
- api/app/Providers/AuthServiceProvider.php
- api/app/Services/Contracts/BearerTokenServiceInterface.php
- api/app/Services/Contracts/DatasetInterface.php
- api/app/Services/LocalAuthBearerTokenService.php
- api/app/Services/OpenIdBearerTokenService.php
- api/database/factories/UserFactory.php
- api/database/migrations/2022_05_12_125508_make_email_nullable.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/AuthServiceProviderTest.php
- frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx
- frontend/admin/src/js/components/user/UpdateUser.tsx
This branch adds the feature that users who visit the site with a valid token but don't yet exist in the database will have a new user created for them on-the-fly.
Suggested test methodology:
1) Switch your environment to Sign In Canada
2) Remove the seeded user row for your user (or disable it by clearing the sub value)
3) Log into the admin site
4) Verify that a new user was created with the correct sub value for your SiC ID
Note: New users are not admin so you still won't be able to use the admin site :smile: 
5) Run the test suite
I factored out most of the logic of `AuthServiceProvider` to the `resolveUserOrAbort` method to make it easier to test.  I was never able to figure out how to bootstrap the app with a mock `BearerTokenService` to be able to create a more end-to-end test, …
> Auto create users

- frontend/common/src/components/accordion/Accordion.tsx
Resolves #2763 
This applies a few changes to styling for the accordions to avoid the icon wrapping.
- Add `flex-wrap: nowrap` to container to prevent wrapping
- Add wrapper div to suffix + icon
- Prevent suffix wrapper div from shrinking to stay uniform
Would love @Jerryescandon to review the screenshots to provide some feedback/approval since this has some design concerns.
> Bug - 2763 - Fix Accordion Icon Wrapping

- .github/workflows/lint.yml
- frontend/admin/.eslintrc
- frontend/admin/src/js/components/context/LanguageRedirectProvider.tsx
- frontend/common/.eslintrc
- frontend/common/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- frontend/indigenousapprenticeship/.eslintrc
- frontend/indigenousapprenticeship/src/js/components/Svg/ThickCircle.tsx
- frontend/indigenousapprenticeship/src/js/pageContainer.tsx
- frontend/talentsearch/.eslintrc
- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/pageContainer.tsx
Resolves #2760 
This updates the output for the Request page filter summary to display "(None selected)" instead of "N/A". 
While working on this, a bug with the request button breaking when `classifications` and `cmoAssets` were null has been addressed as well.
So, I thought I was on a different branch trying to shore up some of the remaining lint issues, especially in regards to the actions.
- Updates `import/extensions` to allow `.json`
- Adds a step to the lint action to compile intl to prevent `import/no-unresolved` erroring
- Changes import pattern for json files to avoid problems with typescript
- Even though this was supposed to be fixed, I still ran into errors where typescript didn't like default imports of json files
- `import * as json from "./file.json";` seems to prevent …
> Bug - 2760 - Null States Request Form

- frontend/common/src/components/ClientProvider/ClientProvider.tsx
Resolves #2777 
This adds an `await` to the `refreshTokenSet` function so we can check the state before returning it. Additionally, if that state is no valid, we call `logout`.
Since we reuse `logout` and `return null;` now, this can been moved to a function.
```tsx
/**
* Logout the user and return null AuthState
*
* @returns null
*/
const logoutNullState = () => {
logout();
return null;
};
```
We should write some automated tests here to confirm we can refresh tokens and properly logout when needed. However, I am not sure where to start and opted to get this PR through and do the following manual testing.
This tests that the refresh token is able to successfully refresh the access token.
1. Login to the application
2. Open the DevTools and delete or modify the access token to dirty the …
> Bug - 2777 - Check refreshed AuthState before returning 

- api/app/Models/PoolCandidate.php
- api/tests/Feature/PoolCandidateTest.php
This branch solves the bug where candidates can get pulled in from other pools in the salary-to-classification query.  h/t to Eagle-Eye @vd1992 .  I started by adding some tests for validation.
The query was being built like this:
```
select count(*) from pool_candidates where exists (
select from joined tables where
(exact classification match)
or
(salary to classification match)
and
(candidate_id predicate for exists clause)
)
```
Since AND has precedence the OR operator was not working as intended. I updated the builder to group the OR like this:
```
select count(*) from pool_candidates where exists (
select from joined tables where
(
(exact classification match)
or
(salary to classification match)
)
and
(candidate_id predicate for exists clause)
)
```
Closes #2801
> Group two halves of classification filter

- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/tests/Feature/PoolCandidateTest.php
- api/tests/Feature/UserTest.php
This branch removes the constraint that the candidate must have at least one attached classification of the group being search before they can be classification-to-salary matched.  Tests have been updated to exercise this behavior (or explicitly avoid it when not being tested).
Some queries I used for ad-hoc testing:
```
-- check salaries for IS 4 and 5
select * from classifications c 
where (c.group = 'IS' and c.level = 4) or (c.group = 'IS' and c.level = 5)
-- check candidates with expected salary ranges
select count(*) from pool_candidates pc 
where pc.expected_salary ?| array['_90_99K', '_100K_PLUS']
and "pool_id" in ('c2ed44d3-3bb9-4cf0-b99f-c961e0272779') 
-- check candidates without expected salary ranges but have classification matches
select count(*) from pool_candidates pc
join …
```
> Remove classification group constraint

- .github/issue_template.yml
Just wanted to create a quick one. We can have a few, and this doesn't need to cover everything (a blank is always still an option).
Even if we create through ZenHub most of the time (and bypass GitHub's templates), this can be a file to copy-paste from for an idealized format.
> Add a template for creating new issues

- .vscode/project-words.txt
- frontend/.apache_env
- frontend/talentsearch/src/.htaccess
- frontend/talentsearch/src/config.sjs
- frontend/talentsearch/src/js/components/Router.tsx
This branch adds a feature flag for DIRECTINTAKE.
Remember, to use it you must rebuild the PHP container.
To test, a placeholder route `/en/talent/direct-intake` was created that will render the talent search page when the flag is enabled.
Also, printing `window.__SERVER_CONFIG__` in the dev console will show the flags.
Closes #2782
> Add direct intake flag

- frontend/common/src/components/tabs/TabSet.tsx
- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
- frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
This fixes a few minor bugs on the talent profile page.
> Bug - 2804 - Talent profile bugs

- frontend/admin/src/js/adminRoutes.ts
- frontend/admin/src/js/components/PoolDashboard.tsx
- frontend/admin/src/js/components/pool/ViewPool.tsx
- frontend/admin/src/js/components/pool/pool.operations.graphql
- frontend/common/src/components/PageHeader/PageHeader.tsx
Resolves #2796 
This adds the placeholder page for an individual pool.
We currently have no link to this page and it will be introduced when we update to the new tables in #2639 I believe.
The tabs do not look like they do in the [Prototype](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?node-id=752%3A6863&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1) because they have yet to be updated. This will change when we update the tabs styling.
> Feature - 2796 - Admin pool placeholder page

- api/database/seeders/ClassificationSeeder.php
- api/database/seeders/CmoAssetSeeder.php
- api/database/seeders/PoolSeederUat.php
- api/database/seeders/ProdSeeder.php
- api/database/seeders/UatSeeder.php
- api/database/seeders/UserSeederUat.php
Closes #1763 
- Adds a new UserSeederUat class for where we can add users with subs specific to the UAT server.
- Adds PoolSeederUat which creates a digital_careers pool which should be identical to the one created on Prod. (This required adding a few more CmoAssets, for soft skills.)
- Modified ClassificationSeeder so it creates only realistic Classifications - ie the ones we created manually on Prod.
- Since none of the seeders called by UatSeeder use Model Factories or Faker, it can be run even when composer dev dependencies are not installed.
UatSeeder can be run with `php artisan db:seed --class=UatSeeder`.
This has been tested on the UAT server, and works!
> Create DataSeeder intended (and able) to run on UAT

- frontend/talentsearch/src/js/components/Router.tsx
- frontend/talentsearch/src/js/components/browse/BrowsePoolsPage.tsx
- frontend/talentsearch/src/js/components/browse/browseOperations.graphql
- frontend/talentsearch/src/js/directIntakeRoutes.ts
- frontend/talentsearch/src/js/talentSearchConstants.ts
- infrastructure/php-container/src/.htaccess
Resolves #2781 
This adds the new `/browse` route and page for direct intake.
1. You _may_ need to rebuild your php container 
`docker-compose down php && docker-compose rm php && docker-compose up -d`
2. Build talent search app `cd frontend && npm run production --workspace=talentsearch`
3. Open browser and navigate to `http://localhost:8000/browse`
> Feature - 2781 - browse pools placeholder page

- api/app/Services/Contracts/DatasetInterface.php
- api/tests/Feature/AuthServiceProviderTest.php
Resolves https://github.com/GCTC-NTGC/gc-digital-talent/issues/2873
Not sure why this was a quiet warning for everyone else and fatal errror for me. On investigating, it seems that the official mockery docks say that final classes can't be mocked, and they provide an alternative:
https://docs.mockery.io/en/latest/reference/final_methods_classes.html#dealing-with-final-classes-methods
I've swapped to using proxy mocks, and my phpunit tests are running now :)
> Fixed phpunit tests for DataSet

- api/.env.example
I am utterly ashamed to admit how long I misunderstood this setting, and thought it didn't apply to me. (I thought it was just for tests that didn't want to deal with login, and I didn't realize my logging in via laravel auth wasn't enough 🤦 )
I suspect I fell between the cracks, as it arrived just as I was onboarding, and it didn't get enabled during my initial setup. I've literally been unable to work on applicant profile issues (aside from storybook), and thought I was just an idiot for not being able to grok some pre-requisite step in the code. I was poring over READMEs trying to figure out what I was missing, but it was pretty miserable to feel lost like this on something so low-level. I didn't even know the question to ask for someone to point this out to me 😭  (@vd1992 finally …
> Enable AUTH_DEFAULT_USER by default for local dev

- api/app/Providers/AuthServiceProvider.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/components/user/CreateUser.tsx
- frontend/admin/src/js/components/user/UpdateUser.tsx
- frontend/common/src/helpers/formUtils.ts
- frontend/common/src/helpers/util.ts
- frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
- frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
This branch finishes migrating from `email` to `sub` for authentication.
- Updates to schema
- Updates to admin site
- Updates to profile site
Use cases for testing
Closes #2722
> Finish migrating from email to sub for auth

- frontend/common/src/components/accordion/Accordion.tsx
Resolves #2774.
Fixes console warnings for "Unexpected value 1.5rem..." in certain browsers on the profile page.
> Profile - console warnings for unexpected values

- frontend/common/src/fakeData/fakeExperiences.ts
Resolves #2739 
This replaces the dynamic `faker.date` function calls with a static date to prevent chromatic from marking diffs in the `ExperienceAccordion` stories.
> Tooling - 2739 - Fix dynamic dates causing chromatic diffs

- frontend/common/src/components/form/Checkbox/Checkbox.tsx
- frontend/common/src/components/form/Checklist/Checklist.tsx
- frontend/common/src/components/form/Input/Input.tsx
- frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
- frontend/common/src/components/form/Select/Select.tsx
- frontend/common/src/components/form/TextArea/TextArea.tsx
- frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
Resolves #2915 
This adds the `aria-required="true"` attribute to inputs when `rules.required` is defined so they are properly announced to screen readers.
> a11y - 2915 - Add aria-required

- docker-compose.yml
Pls drop an approval if it works to mitigate the issue you're experiencing :)
**Before** checking out this branch
1. `docker-compose down`
2. `docker-compose up --detach` (presumably needs to be up)
3. shut down docker desktop and restart
4. `docker-compose ps` should show mock-auth container is down with exit code 143
Checkout this branch and repeat. If mock-auth container is up, it should me this is working
> Added restart policy on mock-auth

- api/app/Providers/AuthServiceProvider.php
- api/database/factories/UserFactory.php
- api/database/helpers/ApiEnums.php
- api/database/migrations/2022_06_07_131233_add_applicant_role.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/UserSeederLocal.php
- api/database/seeders/UserSeederUat.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/AuthServiceProviderTest.php
- frontend/common/src/constants/localizedConstants.tsx
- frontend/cypress/fixtures/users.json
- frontend/cypress/integration/admin/auth.spec.js
This branch adds the applicant role to the API.
Tips:
- A test user was added to the seeder for testing as applicant `applicant@test.com`.
Suggested test steps:
Closes #2911
> Add applicant role

- frontend/talentsearch/src/js/authRoutes.ts
- frontend/talentsearch/src/js/components/Router.tsx
- frontend/talentsearch/src/js/components/login/LoginPage.tsx
- infrastructure/php-container/src/.htaccess
Resolves #2922 
This creates the `/login-info` route and page for users to get information before logging into `talentsearch` profiles.
> Feature - 2922 - Login Page

- .bundlewatch.config.js
- frontend/common/src/components/UserProfile/ExperienceByTypeListing.tsx
- frontend/common/src/components/UserProfile/ExperienceSection.tsx
Resolves #2994 
This adds the Edit Experience buttons to the accordions when filtering experiences by type on the profile page.
When filtering by skill, I don't see any experiences, is this a bug?
> Bug - 2994 - Add Edit Button Experience By Type Accordions

- .bundlewatch.config.js
- frontend/common/src/components/Toast/Toast.tsx
Resolves #2916 
This switches out importing css directly for `injectStyles` from `react-toastify`. This prevents the use of `css-loader` and issues caused by it [as suggested in a related issue discussion](https://github.com/fkhadra/react-toastify/issues/195#issuecomment-860722903).
> Bug - 2916 - Fix Toast css-loader Issue

- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
Resolves #2940 
This improves the validation on the edit experience form in two ways:
1. Ensures that when an `id` is present in the URL that a matching experience exists
2. Fixes the `.find` callback on experiences to also check for experience type passed in the URL
> Bug - 2940 - Improve Experience Form Route Validation

- frontend/common/src/components/Header/Header.tsx
- frontend/common/src/helpers/router.tsx
Resolves #2964 
This adds the `lang` attribute to the i18n toggle to improve accessibility by allowing assistive technology to know that the language in this link does not match that of the page improving pronunciation. 
Inorder to do this, we have updated the prop types for the `<Link />` component to use ` React.HTMLProps<HTMLAnchorElement>`
> Bug - 2964 - Add lang Attribute to i18n Toggle

- frontend/admin/src/js/components/menu/SideMenu.stories.tsx
- frontend/common/src/components/Auth/AuthorizationContainer.tsx
- frontend/common/src/components/context/AuthorizationProvider.tsx
- frontend/common/src/components/context/contextOperations.graphql
- frontend/common/src/helpers/router.tsx
- frontend/cypress/fixtures/users.json
- frontend/cypress/integration/talentsearch/direct-intake.spec.js
- frontend/talentsearch/src/js/components/PageContainer.tsx
Resolves #2951 
This checks to see if a user is logged in and has an email associated with their account. If the user has no email, it will redirect to `/talent/profile/create-account`.
~~I'm not happy about it but I had to hardcode the path since the functionality exists in `common` but the path is exclusive to `talentsearch`. Any suggestions to avoid hardcoding this?~~
Answered by @tristan-orourke :D We are now passing this through the `useRouter` hook.
> Feature - 2951 - Redirect new users

- frontend/cypress.json
- frontend/cypress/integration/admin/auth.spec.js
- frontend/cypress/integration/talentsearch/searchpage.spec.js
- frontend/cypress/support/graphql-test-utils.js
Re-ticketed [from Slack message](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1654691932999009?thread_ts=1654635948.795159&cid=C0259G6KXJ6) :lock:
We have some actions that take longer than the 4-second timeout of cypress commands.
The ways to handle this, from best to worst:
1. wait for a related http request to finish via `cy.wait('@someAlias')`
2. look for progressive changes on the way, helpful for progressively loading UIs like ours (each `cy.get()` or equivalent has its own timeout)
3. Bump timeout either on the command or globally in `cypress.json`:
```js
cy.get('.my-selector', {timeout: 10000}).should('not.exist')
```
I bumped the timeout globally (3), but also added an example of the intended way (1).
> Increased cypress timeout

- docker-compose.yml
- infrastructure/adminer-hydra-theme.css
Came across the baked-in adminer themes when messing with docker this evening. Seemed small and might be a little more delightful when adminer shows up on demos, but that's a stretch 🙃  
- sets envvar for material design-y `hydra` theme
- updates hydra theme related to scroll bug
- bonus: sets envvar to default the server field to `postgres`
https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer
> Enable snazzy adminer theme

- frontend/common/src/components/Link/Link.tsx
- frontend/common/src/helpers/sanitizeUrl.ts
Resolves #2993 
This fixes a [medium severity xss vulnerability](https://github.com/GCTC-NTGC/gc-digital-talent/security/code-scanning/10) by sanitizing the `href` input for our `Link` component.
Ref: https://pragmaticwebsecurity.com/articles/spasecurity/react-xss-part1.html
It still flags this even after the addition of sanitization. I think the problem is that all it can do is detect when we are outputting user provided input to the screen and doesn't know if or how well we are sanitizing it.
If someone can confirm the sanitize works, we should be able to safely ignore this as a false positive.
> Security - 2993 - Sanitize URLs

- .github/workflows/lint.yml
Resolves #2866 
This removes that `continue-on-error` in the lint action after ensuring there are no remaining linting errors.
```sh
[frontend] npm run lint --workspaces                                                                                                       main 
> admin@1.3.2 lint
> eslint ./src/js --ext .js,.ts,.jsx,.tsx
> gc-digital-talent-common@1.0.11 lint
> eslint ./src --ext .js,.ts,.jsx,.tsx
> talentsearch@1.0.0 lint
> eslint ./src/js --ext .js,.ts,.jsx,.tsx
> indigenousapprenticeship@1.0.0 lint
> eslint ./src/js --ext .js,.ts,.jsx,.tsx
```
> Tooling - 2866 - Fix Lint Errors

- .vscode/project-words.txt
- frontend/admin/.babelrc
- frontend/admin/.browserslistrc
- frontend/indigenousapprenticeship/.babelrc
- frontend/indigenousapprenticeship/.browserslistrc
- frontend/talentsearch/.babelrc
- frontend/talentsearch/.browserslistrc
Resolves #2360 
This takes the `browserslist` config from our `.babelrc` and puts them in their own file (`.browserslistrc`) for clarity.
```
> 0.5% in CA
last 2 versions
Firefox ESR
not dead
not ie 11
```
> Debt - 2360 - Extract browserslist Config

- frontend/talentsearch/src/js/components/login/LoginPage.tsx
- frontend/talentsearch/src/js/components/register/RegisterPage.tsx
Resolves #3028 
This adds the locale to the login links for `talentsearch` to render the proper gckey page.
> Bug - 3028 - Add Locale, Path to Login Links

- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
This branch fixes the bug where the pool ID is not properly attached to the pool candidate filter when making search requests.
Closes #3058
> Fix missing pool ID

- api/tests/Feature/AuthServiceProviderTest.php
- api/tests/Feature/PoolCandidateTest.php
- api/tests/Feature/UserTest.php
While trying to sort out a potential bug, I noticed that there was a faster way to do setUp in our phpunit tests. Full test run came **down to 12 sec from 45 sec**.
Just run this (might be faster for you, as my docker is slow):
```
docker-compose exec --workdir /var/www/html/api php php vendor/bin/phpunit --verbose
```
---
For anyone curious, this is **how it works**: It runs migration only once at start of each test run (rather than before each test), and keeps every test in a DB transaction that's rolled back after each test completes.
Video explaining it before it was brought into laravel: https://adamwathan.me/2016/11/14/a-better-database-testing-workflow-in-laravel/
> Speed up phpunit test runs

- api/database/factories/UserFactory.php
- api/database/seeders/DatabaseSeeder.php
- api/tests/Feature/UserTest.php
This branch fixes a failing phpunit test - is profile complete.  The new Generic Job Title is part of the "profile complete" test so it must be added to the test users.  I also added it to the database seeder.
Suggested test method:
- run the phpunit test suites and confirm they are successful
Edit: I think the intermittent failure was due to email being null 75% of the time.  It was too much of a hassle to get unique emails in the test so I just changed the factory to never make null emails.
Closes #3072
> Fix profile complete test

- frontend/common/src/helpers/router.tsx
- frontend/cypress/integration/talentsearch/direct-intake.spec.js
Resolves #3080 
Following the login redirect, there was a `return null;` added after the navigation to the new path. This should only be used when navigating away from the site. Returning null caused the application to navigate but never mount the new component and instead showed the last component that was mounted.
Also, added more safety around the authorisation, waiting until the roles have loaded before checking them.
> Bug - 3080 - Fix Create Account Redirect

- frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
- frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
Resolves #3067 
This moves the "required" and "optional" key words next to the `label` of an input and `fieldset` to increase proximity.
1.  Run the `common` workspace storybook
2. Check the `InputLabel` and `Fieldset` components for (required) or (optional) proximity to label
> A11y - 3067 - Improve input required label proximity

- frontend/common/src/components/form/MultiSelect/MultiSelect.stories.tsx
- frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
Extracted from #2641 as things to make that PR more straightforward
- component
- a7a2a18a5 stopped using React.FC (no longer recommended)
- 539813e64 removed HTMLSelectElement props from type (not used, nor needed for react-select component that it wraps)
- 042e46c6e used `{...{ foo, bar }}` spread to send unmodified (and so less important) props into component
- c79e16d1e use same logic for `required` and `aria-required` props, which both accept bool
- de9aa01d6 removed use of controller in `<Controller control={control} />`, which is optional when using FormProvider (which we use)
- storybook
- 71cd4c6a1 less verbose boilerplate
- 3f569fe42 migrated to the new storybook types Meta/Story => ComponentMeta/ComponentStory (prop types auto-detected)
- 16740b382 made story titles less …
> Some house-cleaning on the MultiSelect and story

- frontend/common/src/components/context/AuthorizationProvider.tsx
Resolves #2868 
This fixes an issue where the unauthorized message was flashing on the screen while the query was running. Now, the spinner is displayed while the necessary authorization query is ran.
-  Login to `/admin`
- Refresh a page
- Confirm the spinner appears instead of "Not Authorized" while the `useGetMeQuery` is ran.
> Bug - 2868 - Fix unauthorized component flashing

- .vscode/project-words.txt
- frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx
Resolves #2776 
This adds mobile snapshots to the IAP homepage stories.
1. Navigate to the [Chromatic build](https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=2719)
2. Confirm the English and French Homepage stories for IAP have desktop and mobile snapshots
> Tooling - 2776 - Add IAP Mobile Snapshots

- api/_lighthouse_ide_helper.php
- api/graphql/schema.graphql
- api/programmatic-types.graphql
- api/schema-directives.graphql
- graphql.config.yml
By updating the graphql.config file, and re-running [php artisan lighthouse:ide-helper](https://lighthouse-php.com/4/api-reference/commands.html#ide-helper) I was finally able to get the [vscode-graphql](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) extension running without error!
It now provides Go to Definition, autocomplete, and much improved validation for the schema file and any operations.
The artisan lighthouse command I ran is supposed to run everytime we run composer install, so I'm not sure how those files ended up out of date...
Instructions for Testing
1. Checkout this branch
2. Open in VS Code
3. Install vscode-graphql extension (or restart VS Code if already installed)
4. Open the schema.graphql file
5. Try the "Go to Definition" functionality …
> Improve graphql devtools for VSCode

- api/database/factories/UserFactory.php
resolves #2736 
Specifically the second bit about the acceptance criteria. 
Two cases: 
-> evaluation true in which case random levels are assigned to assessments and estimated ability is nulled
-> evaluation false in which case null assigned to assessments and estimated ability is randomly picked
Now a state of not_complete with assessment levels should not occur, as well as estimated ability with assessed levels
The latter added as per language profile form, you either did an assessment or you add estimated proficiency 
Testing: Migrate and view data in adminer
> adjust language seeding

- api/app/Models/User.php
- api/database/migrations/2022_06_29_172400_index_user_created_at.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/UserTest.php
- frontend/admin/src/js/components/Table/Table.tsx
- frontend/admin/src/js/components/Table/tableComponents.tsx
- frontend/common/src/components/Pagination/Pagination.stories.tsx
- frontend/common/src/components/Pagination/Pagination.tsx
- frontend/talentsearch/src/js/components/skills/AddSkillsToExperience/AddSkillsToExperience.tsx
Related to (but will not close) #3173 
The main changes will happen in a followup PR.
This PR sets some groundwork to make the changes in the followup PR clearer.
- Updates the paginated query in the API to use the built-in lighthouse ordering functionality instead of the recreated scope 
- We lose the "order by id by default" behavior
- But we gain the ability to order by multiple columns and order by ASC and DESC
- Factors out some lower-order table components to a separate file.  This will be shared with the API driven table
- Renames the Pagination component props from `handle*` to `on*`
- I hate that we have to specify the column name for ordering instead of the field name.  It's leaking the implementation into our interface.  I haven't figured out a way around this though.
> Prep for API managed table

- frontend/common/src/css/common.css
The non-zero line-heigh of the icon was causing the field layout to jitter and be slightly different depending on whether context info was set. The jitter wouldn't likely be noticed in live site conditions, but the slight difference in field height when two fields are alongside might be perceptible.
[![](https://recordit.co/uxjMICz0hK.gif)](https://recordit.co/uxjMICz0hK)
[![](https://recordit.co/vJGd3O92rb.gif)](https://recordit.co/vJGd3O92rb)
> Ensure field height is consistent both with/without context info

- frontend/admin/src/js/components/Table/SearchForm.tsx
- frontend/admin/src/js/components/Table/Table.tsx
- frontend/admin/src/js/components/user/UserTable.tsx
Resolves #3227 
This modifies the styled client side table to use `react-table` search, restoring the ability for users to search tables not using the new api driven table.
1. Navigate to any of the `/admin` pages that include a table
2. Type in the search field
3. Ensure the table updates with appropriate rows
> Bug - 3227 - Restore Client Side Table Search

- frontend/admin/src/js/components/PoolDashboard.tsx
- frontend/admin/src/js/dashboard.tsx
- frontend/common/src/components/Pending/Loading.tsx
- frontend/common/src/components/Pending/Pending.tsx
- frontend/talentsearch/src/js/components/Router.tsx
- frontend/talentsearch/src/js/pageContainer.tsx
Resolves #3250 
This makes it so the `<Pending />` component renders the children in addition to the spinner so that the `<ToastContainer>` is always available.
1. Edit a user (or other item in admin)
2. Submit
3. Confirm toast appears on top of the loading spinner.
> Bug - 3250 -  no toasts appearing

- frontend/common/src/components/Dialog/Dialog.tsx
- frontend/common/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
Resolves #3207 
This fixes two components that had text not wrapped in `intl.formatMessage`.
- Dialog close button
- SkillAccordion title and role
> Bug - 3207 - Fix missing intl text

- .bundlewatch.config.js
- .vscode/project-words.txt
- frontend/common/package.json
- frontend/common/src/components/Card/Card.stories.tsx
- frontend/common/src/components/Card/Card.tsx
- frontend/common/src/components/Card/index.ts
- frontend/common/src/helpers/dateUtils.ts
- frontend/common/src/helpers/localize.ts
- frontend/common/src/helpers/skillUtils.ts
- frontend/package-lock.json
- frontend/talentsearch/src/js/components/ClassificationDefinition/ClassificationDefinition.tsx
- frontend/talentsearch/src/js/components/ClassificationDefinition/ITDefinitions.tsx
- frontend/talentsearch/src/js/components/ClassificationDefinition/index.ts
- frontend/talentsearch/src/js/components/Router.tsx
- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
- frontend/talentsearch/src/js/components/pool/PoolInfoCard.test.tsx
- frontend/talentsearch/src/js/components/pool/PoolInfoCard.tsx
- frontend/talentsearch/src/js/components/pool/poolOperations.graphql
- frontend/talentsearch/src/js/components/request/CreateRequest.tsx
- frontend/talentsearch/src/js/directIntakeRoutes.ts
Resolves #3164 
This creates the public facing page for pool advertisements.
1. Navigate to `/browse/pools`
2. Click on one of the pools
3. Add `/view` to the end of the path
4. Confirm you can see the page and it matches the prototype
We are still waiting on mutations to be able to test this with cypress.
We have the following statuses and you should expect the following when you encounter them:
- DRAFT
- 404 if logged in as applicant
- View normally as admin
- PUBLISHED
- See as admin or applicant
- Can apply as applicant
- Tile with info in header should indicate number of days until it expires
- Tomorrow and Today are replaced by number of days when appropriate
- EXPIRED
- See as admin or applicant
- Tile indicates the post is expired
- Apply buttons should be disabled
> We will have …
> Feature - 3164 - Public Pool Advertisement Page

- api/app/Models/Pool.php
- api/tests/Feature/PoolTest.php
resolves #3354 
having the timezone set as Pacific in the accessor attribute was messing with things when current time and expiry time were within a few hours of one another
given the database deals in UTC, I elected to go with UTC time being enforced for the backend, I think it'll be easier that way, plus it seems that sticking with Laravel/database conventions would be preferred in that other issue
as well, added an additional test to ensure the bug was (ideally) resolved
testing: see if you can break the accessor in Adminer + viewing pool poster
sidenote: I think this convention should be kept in mind for mutations creating posters too, to convert time to UTC before executeMutation
> resolve backend advertiseStatus bug

- frontend/admin/package.json
- frontend/common/package.json
- frontend/indigenousapprenticeship/package.json
- frontend/talentsearch/package.json
This changes our compile method from string to [AST](https://formatjs.io/docs/guides/advanced-usage).  I can't tell you why this is the solution but it should actually speed up the application as well as fix the `console.warn` we are getting during tests.
Ref: https://stackoverflow.com/a/71384834
> Bug - Fix @formatjs warning for default rich text elements

- maintenance/README.md
The bad experience of @JoshBeveridge on Windows WSL seemed to involve a memory issue that was resolved by spinning down mock-auth during npm package resolution. Added a hint.
> Improve first-time setup experience via doc update

- .github/workflows/docker-smoke-test.yml
- .github/workflows/e2e-tests.yml
trying to troubleshooting the docker/e2e issues...
okay, each commit represents a solution to the recent issue of workflows for smoketest and cypress
both appear to resolve the issue, I am partial to the latter since I do not know if there is a purpose to the postrun save, disabling it solves the issue for sure and shaves some time off test runs
related to docker layer caching action: https://github.com/satackey/action-docker-layer-caching/issues/139#issuecomment-1007316528
per conversation here
https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1657839973910039
> workflow troubleshooting

- frontend/common/src/components/UserProfile/ProfileSections/WorkPreferencesSection.tsx
resolves #3403 
The look of the WorkPreferences section needs some changing. Now what is _and_ what isn't selected needs to be represented.
As well as what appears required and how things look nulled. 
To test, go to /profile and view the Work Preferences section and...
- test null for wouldAcceptTemporary
- zero selected requirements
- some selected requirements
- all selected requirements
> semi-refactor WorkPreferencesSection

- frontend/admin/src/js/components/dashboard/LatestRequestsTable.tsx
Moves the key for `Cell` accessor in the `LatestRequestsTable` up a level to the `React.Fragment`.
> Add Cell Key to Latest Requests Table

- .github/workflows/codeql-analysis.yml
Resolves #3189 
This bumps the codeql actions to `v2` since `v1` has been deprecated.
> Deps - 3189 - Bump CodeQL Actions

- frontend/common/src/components/UserProfile/ExperienceByTypeListing.tsx
- frontend/common/src/components/UserProfile/ExperienceSection.tsx
Resolves #3455 
Removes the gray backgrounds on tabs for Experience & Skills.
> Design - 3455 - Remove Tab Gray Backgrounds

- frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
- frontend/admin/src/js/stories/Pool.stories.tsx
- frontend/common/src/components/SearchRequestFilters/deprecated/SearchRequestFilters.tsx
- frontend/common/src/components/UserProfile/ExperienceSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/AboutSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/GovernmentInformationSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/LanguageInformationSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/RoleSalarySection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/SkillExperienceSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/WorkLocationSection.tsx
- frontend/common/src/components/UserProfile/ProfileSections/WorkPreferencesSection.tsx
- frontend/common/src/constants/localizedConstants.tsx
- frontend/common/src/messages/commonMessages.ts
Resolves #3195 
This adds more context to the get started links for assistive technology.
> A11y - 3195 - Improve get started link context

- .github/workflows/bundlewatch.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/jest.yml
- .github/workflows/lint.yml
- .github/workflows/package-integrity-check.yml
- .github/workflows/storybook.yml
Resolves #3480 
We have bumped the version of `action/setup-node` to `v3` which fixes an issue with cache. Ran some of the most commonly failing tests 3-4 times and they were consistently passing.
> Bug - 3480 - Fix Setup Node Action

- docker-compose.yml
Resolves #3442 
This removes the duplicate `volumes` key in the `docker-compose.yml` file.
> Bug - 3442 - Remove duplicate volumes key

- frontend/common/src/components/UserProfile/UserProfile.tsx
- frontend/common/src/lang/fr.json
- frontend/cypress/integration/talentsearch/profile-page.spec.js
Resolves #3390 
This updates the About section title to About Me (en) and À propos de moi (fr).
> Copy - 3390 - Update About Section Title

- frontend/common/src/lang/fr.json
Resolves #3502.
Removed by accident in:
- https://github.com/GCTC-NTGC/gc-digital-talent/commit/48589886434d681cd6a9a1e52288f0605a3b014a#diff-9be88dc2973ab04fa23b50f6429fda5ef488c9ddd997982f35bdc12abda31e50L327-L330
> Add FR copy for Text displayed when skill block is open

- api/app/GraphQL/Handlers/LoggingErrorHandler.php
- api/config/lighthouse.php
This branch adds an error handler to Lighthouse which logs any errors passed to it using the Log facade.  Unfortunately, the error handler is not passed the original request so I think it is not possible to log anything other than what is displayed in the Playground results pane.
Here are some test queries to trigger errors:
```
query whoAmI {
me
}
```
```
query users {
users {
firstName
}
}
```
```
query whoAmI {
foo
}
```
You should see the errors appear in your `laravel.log` file.
You can test on the dev server, too:
Closes #2526
> Add GraphQL logging error handler

- frontend/admin/src/js/lang/fr.json
- frontend/common/src/lang/fr.json
Resolves #3507.
- Removed by accident in: https://github.com/GCTC-NTGC/gc-digital-talent/commit/efc33e01a9037d654f2d8e6e7228167b946f4d94#diff-395e2af46ce720b6af1549a80254c2acc90e207dc270993d490498b4e6c06e55L973-L976
- Translates _Are you sure you would like to logout?_ the [same way](https://github.com/GCTC-NTGC/gc-digital-talent/commit/825a9b65fb9b17b4ee9a9118cea503bb73e5db1d) across projects.
> Add and update FR copy for logout strings

- .vscode/project-words.txt
- api/graphql/schema.graphql
- api/tests/Feature/PoolCandidateSearchRequestTest.php
Resolves #3317 
This adds `required_without` validation to the `createPoolCandidateSearchRequest` mutation for `poolCandidateFilter` and `applicantFilter`.
> Debt - 3317 - Improve candidate request validation

- frontend/talentsearch/src/js/components/workPreferencesForm/WorkPreferencesForm.tsx
Resolves #3504 
This updates the Work Preferences form to set the default value of temporary work as undefined if the user has not submitted the form before.
> Bug - 3504 - Fix Work Pref Temp Work Default Value

- frontend/admin/src/js/components/classification/CreateClassification.tsx
- frontend/admin/src/js/components/user/UserTable.tsx
- frontend/common/README.md
- frontend/common/src/components/Header/Header.tsx
- frontend/common/src/helpers/router.tsx
Resolves #3516 
Removes the `<Link />` component found in the common `router.tsx` file and replaces its usage with the other `<Link />` component.
> Debt - 3516 - Remove Duplicate Link Component

- frontend/common/src/components/AlertDialog/AlertDialog.tsx
Resolves #3519 
Adds the required alert dialog styles from @reach. Turns out, they need to be imported from dialog, not alert-dialog 😓
> Bug - 3519 - Add Alert Dialog Styles

- frontend/common/src/components/Tabs/Tab.tsx
- frontend/common/src/components/Tabs/index.ts
- frontend/common/src/components/UserProfile/ExperienceSection.tsx
Resolves #3525 
Moves the tab css imports to prevent being improperly tree shaken.
> Bug - 3525 - Fix Tab Styles

- api/.env.example
resolves #3488 
upon login from `/` path, direct to `/talent/profile` rather than `/admin`
to test
1) copy from .env.example over to your .env
2) navigate to http://localhost:8000/login
3) login and you should be directed to /talent/profile
This change will require additional care
On the servers, the environment variable `OAUTH_POST_LOGIN_REDIRECT` will have to be changed from "http://{hostname}/admin" to "http://{hostname}/talent/profile" to resolve this fully. 
Thank you, Peter
> navigate redirect to /profile

- frontend/common/src/components/form/MultiSelect/MultiSelectFieldV2.stories.tsx
- frontend/common/src/components/form/MultiSelect/MultiSelectFieldV2.test.tsx
- frontend/common/src/components/form/MultiSelect/MultiSelectFieldV2.tsx
- frontend/common/src/components/form/Select/SelectFieldV2.stories.tsx
- frontend/common/src/components/form/Select/SelectFieldV2.test.tsx
- frontend/common/src/components/form/Select/SelectFieldV2.tsx
Extracted from https://github.com/GCTC-NTGC/gc-digital-talent/issues/2641
What this does:
- Adds components for using react-select (single select and multi-select), with MultiSelectFieldV2 as slim extension of SelectFieldV2
- adopts "XField" nomenclature to better communicate that component encloses more logic than just form/input element (label, context messages, input chrome, etc)
- rather than use react-select's more complex `Option: {value: string; label: string}` format, uses simpler `value` of `string` or `string[]`
- added prop `forceArrayFormValue` to optionally force `SelectFieldV2` to store values as array of single value (e.g., `["BAZ"]`). This should simplify submission logic that can now be more agnostic about field type (Select vs MultiSelect)
- makes text content inside …
> Add SelectFieldV2 and MultiSelectV2 components

- frontend/common/src/components/skills/SearchBar/SearchBar.tsx
Resolves #3498 
This updates the skill `<SearchBar />` on key press handler to prevent the enter key from submitting the form.
> Bug - 3498 - Disable Skill Search Submission

- api/database/factories/PoolFactory.php
- api/database/seeders/DatabaseSeeder.php
currently the factory attaches 5 random classifications to a pool, going forward like with the pool advertisement the norm is one classification per pool
having multiple classifications attached to a pool causes a failure in validation
candidate classification seeding needed to be adjusted too as there is only a single classification involved with a pool, so each candidate has one expected classification now
see #3424 for context
**testing**
1) check out and migrate+seed
2) visit "Select: classification_pool" and "Select: classification_pool_candidate" in Adminer and ensure they look like what the above says the goal is
3) check anything you might think be suspicious??? not sure
> adjust poolFactory to attach single classification

- .github/workflows/storybook.yml
Resolves #3527
Didn't really understand how urgent this was. E.g. Accumulating noise in Chromatic visual diffs to the point of it being useless: (guess it's helpful to have a mainline to diff against 🙃 )
https://www.chromatic.com/pullrequest?appId=61e099a1bb1465003a73d3ce&number=3538&view=changes
> Allow chromatic to run on every commit on main branch

- frontend/common/src/components/skills/MissingSkills/MissingSkills.stories.tsx
- frontend/common/src/components/skills/MissingSkills/MissingSkills.test.tsx
- frontend/common/src/components/skills/MissingSkills/MissingSkills.tsx
- frontend/common/src/components/skills/MissingSkills/index.ts
Resolves #3451 
This adds a new `MissingSkills` component to `common`. 
```tsx
export interface MissingSkillsProps {
requiredSkills?: Skill[];
optionalSkills?: Skill[];
addedSkills?: Skill[];
}
```
This is an array of the "Need to Have" skills.
This is an array of the "Nice to Have" skills.
This is an array of the skills that have been added to the users profile.
> Feature - 3451 - Missing Skills Component

- frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationNavigation.tsx
- frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationPageWrapper.stories.tsx
- frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationPageWrapper.tsx
- frontend/talentsearch/src/js/components/ApplicationPageWrapper/Step.tsx
Resolves #3323 
This adds a new component meant to wrap the application pages.
```tsx
export interface StepProps {
path: string; // Path to the page of the step
label: string; // Text to be displayed in the link
disabled?: boolean; // Derived from currentStep in ApplicationNavigationProps
}
interface ApplicationNavigationProps {
currentStep: number; // The current step the user is on (disables that button)
steps: Omit<StepProps, "disabled">[];  // Array of the allowed steps
}
interface ApplicationPageWrapperProps {
title: string; // Main page title
subtitle?: string; // Jpb advertisement title
crumbs?: BreadcrumbsProps["links"]; // Array of breadcrumb links to show
navigation?: ApplicationNavigationProps; // If set, displays the steps as buttons
closingDate: Date; // The closing date of …
```
> Feature - 3323 - Application Page Wrapper

- frontend/common/src/components/skills/MissingSkills/MissingSkills.tsx
I noticed that something is randomizing the order the fake skills in the MissingSkills component stories.  I added a sort to stabilize them for snapshotting.
Testing - Run storybook two or more times and check if the order of the fake skills in the MissingSkills stories is stable.
> Stabilize Missing Skills Stories

- documentation/translation.md
- frontend/common/README.md
As part of #3531 I've tried to improve the translation documentation a bit.
- Factored out the translation instructions to their own readme in the documentation folder (with link from old location)
- Added my request template
> Translation Documentation

- frontend/common/src/components/accordion/Accordion.tsx
Resolves #3535 
This updates the `<Accordion />` component to ensure all IDs are unique as well, it applies the appropriate `role` and `aria-*` attributes.
The added `aria-*` attributes here help associate the elements with each other for assistive technology.
- `aria-controls` on the button allows assistive technology to understand this button has the specific purpose of controlling the the accordions state.
- `aria-describedby` on the content `div` appropriate indicates that the button is used as a descriptor for the content within the `div`
Adding the `role="region"` indicates that the specific `div` holds significance in the document. For the content `div` this allows us to indicate that it is being controlled and labelled by the proceeding button.
> Bug - 3535 - Make Accordion IDs Unique

- infrastructure/azure-pipelines.yml
Only trigger azure build on changes to main, not every PR. Exclude changes to only documentation or maintenance scripts.
Main motivation:
Since we automatically deploy to the Dev server every time an artifact is built, and we're currently building an artifact every time a PR is created or updated (and not necessarily ready for merging into main), the Dev server is likely to be broken at any given time.
> Limit when Azure pipeline builds a new release artifact

- frontend/cypress/integration/admin/admin-workflows.spec.js
Resolves #3311 
Adds an additional `cy.wait("@gqlAllUsersPaginatedQuery");` which follows the pattern set out on the other `searchForUser("Applicant", "applicant@test.com");` calls that do not periodically fail.
Ran the e2e action 3 times and each time it passed. Feel free to re-run it to be extra careful.
> Tooling - 3311 - Improve Admin Workflow e2e

- api/app/Http/Controllers/AuthController.php
- frontend/.apache_env
- frontend/admin/src/js/dashboard.tsx
- frontend/common/src/components/Auth/AuthenticationContainer.tsx
- frontend/common/src/components/context/AuthenticationProvider.tsx
- frontend/common/src/components/context/ContextContainer.tsx
- frontend/common/src/helpers/runtimeVariable.ts
- frontend/indigenousapprenticeship/public/config.sjs
- frontend/talentsearch/public/config.sjs
- frontend/talentsearch/src/js/pageContainer.tsx
We can't make logout fully mandatory as in the AC of the issue.  If the browser is redirected to the Sign In Canada logout URI when there is no active session then a scary error page is displayed.  The logic to guess if a session is still active must remain.  This branch reduces the logic complexity around logout a bit.
- Removed some leftover Laravel Auth logic from api/app/Http/Controllers/AuthController.php.
- Removed the `homePath` prop from AuthenticationContainer.  Browswer will always be sent to `logoutRedirectUri`.
- Added a `getRuntimeVariableNotNull` function that will log an error if a mandatory variable is missing and has a not-null return type.
- Refactored the logic of `logoutAndRefreshPage` to (hopefully) make it a bit clearer
- Test with both SiC and MockAuth
- Log in
- …
> Reduce logout logic complexity

- api/graphql/schema.graphql
- frontend/admin/src/js/components/user/CreateUser.tsx
- frontend/common/src/helpers/util.ts
Resolves #3512 
This adds the `sometimes` validation rule to `sub` and `email` when creating a user.
2. Navigate to `/admin/users/create`
1. Attempt to create a user with no Email or Subject
2. Confirm it submits
1. Create a user with known Email and Subject
2. Attempt to create second user with same Email and Subject
3. Confirm it fails
> Bug - 3512 - Fix empty unique user validation

- frontend/common/src/messages/commonMessages.ts
- frontend/talentsearch/src/js/components/applicantProfile/CancelButton.tsx
- frontend/talentsearch/src/js/components/applicantProfile/ExperienceAndSkills.tsx
- frontend/talentsearch/src/js/components/applicantProfile/ProfileFormFooter.tsx
- frontend/talentsearch/src/js/components/applicantProfile/ProfileFormWrapper.tsx
- frontend/talentsearch/src/js/components/diversityEquityInclusion/DiversityEquityInclusionForm.tsx
- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
Resolves #3393 
This updates the props for the `ProfileFormWrapper` and `CancelButton` to components to allow more customisation. As well, it changes the cancel link text on `/talent/profile/skills-and-experiences` and `/talent/profile/diversity-and-inclusion` for improved context.
1. Build talentsearch `cd frontend && npm run production --workspace=talentsearch`
2. Navigate to `/talent/profile/skills-and-experiences` and `/talent/profile/diversity-and-inclusion`
3. Confirm the cancel links contain the text "Go back to my profile"
> Copy - 3393 - Update profile back button text

- api/app/GraphQL/Mutations/CreateApplication.php
- api/app/Models/PoolCandidate.php
- api/database/migrations/2022_08_11_161706_submitted_at_field_added_application.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolApplicationTest.php
resolves #3332 
testing: 
use this mutation
you will need to fill in values from adminer, if you attempt to create a duplicate application the row count should remain unchanged, and should increment by one when you attempt to make a new one
```
mutation createApplication {
createApplication(userId: "USER_ID", poolId: "POOL_ID") {
user {
id
}
pool {
id
}
}
}
```
status work I did not complete as #3660 deals with that, adding DRAFT as well as doing the status logic
so what I did was just implement the submitted_at field for that issue
> create application mutation

- .github/workflows/dependabot-auto-label.yml
Resolves: #2175
To close the other lingering draft PR https://github.com/GCTC-NTGC/gc-digital-talent/pull/2176
Source: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#label-a-pull-request
- name: `dependencies-priority`
- color: `#d66103`
- description: `Pull requests that update a dependency file (top-level package)`
> Add workflow to label direct dependencies as priority

- frontend/common/src/constants/localizedConstants.tsx
my last merge updated the enum Pool Candidate Statuses, I didn't realize that was something another piece was tightly coupled to and so errors resulted as the piece in LocalizedConstants wasn't updated but components that fetched the enum tried to run the enum through LocalizedConstants
testing
- check out
- run codegen and dev in /admin
- run storybook in /admin and confirms it doesn't error
> resolve broken chromatic build

- api/app/GraphQL/Mutations/TestPoolCandidateSnapshot.graphql
- api/app/GraphQL/Mutations/TestPoolCandidateSnapshot.php
- api/app/GraphQL/Util/GraphQLClient.php
- api/app/Models/PoolCandidate.php
- api/database/migrations/2022_08_16_194515_add_application_snapshot_json.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/SnapshotTest.php
- frontend/talentsearch/src/js/api/userOperations.graphql
This branch demonstrates early snapshot functionality.  It adds a mutation to manually trigger snapshot creation.  Tying it in with application submission will be handled in #3661.
- A migration to add a JSONB column to pool_candidates to store the snapshot.
- A TestPoolCandidateSnapshot mutation to manually trigger a snapshot for a specific poolCandidate
- A phpunit test to verify that the stored snapshot matches the snapshotting query
```
mutation snapshot($poolCandidateId: ID!) {
testPoolCandidateSnapshot(id: $poolCandidateId) {
profileSnapshot
}
}
```
```
php artisan test tests/Feature/SnapshotTest.php 
```
Closes #3340
> Early Snapshot Functionality

- .github/workflows/dependabot-auto-label.yml
Removes orphan quote wrapping `GH_TOKEN` value in Dependabot auto-label workflow from https://github.com/GCTC-NTGC/gc-digital-talent/pull/3562.
> Fix Dependabot auto-label GitHub workflow

- frontend/admin/src/js/components/user/useFilterOptions.tsx
Resolves missing leading zero in classification label used in `useFilterOptions` hook.
> Add leading zero to classification label

- frontend/admin/src/js/components/apiManagedTable/TableHeader.tsx
- frontend/common/src/components/Button/Button.tsx
Looks like `TableHeader` and `Button` were reverted again, this undoes that.
> Revert Hydrogen Overwrites

- frontend/talentsearch/src/js/components/experienceForm/ExperienceSkills.tsx
Resolves #3708 
Removes the default focus when appending a skill to `react-hook-form` `useFieldArray` method.
1. Navigate to user profile
2. Create an experience
3. Add skills to the experience
4. Confirm the description `textarea` is not auto focused after adding a skill
> Bug - 3708 - Remove Skills Auto Focus

- frontend/admin/package.json
- frontend/common/package.json
- frontend/indigenousapprenticeship/package.json
- frontend/package-lock.json
- frontend/talentsearch/package.json
Caused issues with jest tests.
> Revert "Bump eslint-plugin-formatjs from 4.2.2 to 4.3.0 in /frontend"

- frontend/admin/src/js/components/Table/Table.tsx
- frontend/admin/src/js/components/classification/ClassificationPage.tsx
- frontend/admin/src/js/components/classification/ClassificationTable.tsx
- frontend/admin/src/js/components/cmoAsset/CmoAssetPage.tsx
- frontend/admin/src/js/components/cmoAsset/CmoAssetTable.tsx
- frontend/admin/src/js/components/department/DepartmentPage.tsx
- frontend/admin/src/js/components/department/DepartmentTable.tsx
- frontend/admin/src/js/components/pool/PoolPage.tsx
- frontend/admin/src/js/components/pool/PoolTable.tsx
- frontend/admin/src/js/components/searchRequest/SearchRequestPage.tsx
- frontend/admin/src/js/components/searchRequest/SearchRequestTable.tsx
- frontend/admin/src/js/components/skill/SkillPage.tsx
- frontend/admin/src/js/components/skill/SkillTable.tsx
- frontend/admin/src/js/components/skillFamily/SkillFamilyPage.tsx
- frontend/admin/src/js/components/skillFamily/SkillFamilyTable.tsx
Resolves #2656 and #3014 
This replaces the headings of all admin index pages with the new pattern as well as makes the use of `<DashboardContentContainer>` consistent across all of the index pages. 
> Note: Simple text with icon to left of heading, "Add" buttons moved to right side above table
> Design - 2656 - Admin Heading Update

- frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
Resolves #3736 
This darkens the red colour of the required label to meet the current minimum colour contrast rations for WCAG 2.0 AA.
- [Profile](https://colourcontrast.cc/ffffff/bf0000) - 6.53:1
- [Admin](https://colourcontrast.cc/f5f5f5/bf0000) - 5.9:1
> a11y - 3736 - Darken Required Labels

- api/database/migrations/2022_09_06_155536_update_candidate_statuses.php
This branch adds a migration so that existing candidate rows in a database will have the updated statuses needed for PR 3744.  See the status changes [here](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3744/files#diff-bda6dd953620b9cc44f8ffc3bc4acb3f4a4d6089be006de5dcafdf8f0dadf728).
```
select
pool_candidate_status,
count(*)
from pool_candidates pc
group by pool_candidate_status
```
Closes #3810
> Fix candidate statuses

- frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx
- frontend/indigenousapprenticeship/src/js/lang/fr.json
Resolves #3828 
This updates the IAP with some typo fixes and new copy.
- Fix typo for Métis (38e66cf9fb1f62d633004a443aeb0140e10cf8af)
- Adds a mail link to contact us (234b7fc2c960b163e64e10f49e2aee2734cf445e)
- Replaces honesty pledge references with new name (004dc3915eded125e8b67ac92ace5d75d5a7117d)
1. Compile new translations `npm run intl-compile --workspace=indigenousapprenticeship`
2. Build the IAP project `npm run production --workspace=indigenousapprenticeship`
3. Navigate the IAP homepage
4. Confirm the following:
- No ocurrence of "Metis" typo
- "Contact us / communiquer avec nous" is linked to edsc.pda-iap.esdc@hrsdc-rhdcc.gc.ca
- First step in "How it Will Work" references the "Indigenous Peoples Self-Declaration Form" rather than "Honesty Pledge"
> Copy - 3828 - IAP copy fixes

- frontend/admin/src/js/components/menu/AdminSideMenu.tsx
Resolves #3711 
This replaces the existing `startsWith` for active link detection with a strict equals operator.
1. Build the admin project `npm run production --workspace=admin`
2. Navigate and login to admin project
3. Use the side menu and confirm the proper item is highlighted when active
> Note: Pay close attentions to "Skills" and "Skill Families" since this is where the issue was originally ocurring.
> Bug - 3711 - Improve active link detection

- api/app/Console/Commands/DeleteAllSkillsAndSkillFamilies.php
- api/database/helpers/KeyStringHelpers.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/ProdSeeder.php
- api/database/seeders/SkillFamilySeeder.php
- api/database/seeders/SkillSeeder.php
- api/tests/Feature/ApplicantFilterTest.php
- api/tests/Feature/PoolApplicationTest.php
This branch adds a SkillFamilySeeder and SkillSeeder to implemented the skills in [the given worksheet](https://docs.google.com/spreadsheets/d/17Y58sxWaCgj6qoFEn333UoK0sPoqwTeIFlC4Y1ZgP-8/edit?usp=sharing).  It also adds a new artisan command to delete all the existing skills and skill families in the application.
- Try out the deployment script
1. Ensure the database has been backed up
2. Run `php artisan delete:skills_and_skill_families`
3. Run `php artisan db:seed --class=SkillFamilySeeder`
4. Run `php artisan db:seed --class=SkillSeeder`
Closes #3684
> Add new skill seeders

- frontend/admin/.storybook/preview.js
- frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx
talentsearch french string weren't being merged into the omni-storybook during build, and so storybook wasn't properly reflecting live app translations.
https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/workpreferencesform--individual-work-preferences
> Import talentsearch french strings into merged Storybook (hosted on Chromatic)

- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
- frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
Resolves #3704 
This conditionally applies `flex-grow: 1;` to labels when nothing is appended to expand interactive area for radio and checkbox inputs.
> Bug - 3704 - Improve Radio/Check Clickable Area

- frontend/cypress/integration/talentsearch/search-workflows.spec.js
- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/components/search/SearchForm.tsx
- frontend/talentsearch/src/js/components/search/deprecated/SearchForm.tsx
- frontend/talentsearch/src/js/lang/fr.json
Resolves #3870 
This changes both the new and deprecated search form to use `Select` instead of `MultiSelect` for the classification field.
1. Build talentsearch
3. Confirm the classification field is not multi-select and works
4. Remove feature flag, rebuild container
6. Repeat steps 1-3
> Debt - 3870 - Single Select Classification

- .github/workflows/lint.yml
Closes https://github.com/GCTC-NTGC/gc-digital-talent/issues/3682
Quick fix, and no more merges with eslint issues :)
> Force eslint workflow to fail build when even one warning

- api/app/Models/PoolCandidate.php
- api/database/migrations/2022_09_08_191031_generated_candidate_status_weight.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/ApplicantTest.php
closes #3874 
Adds the generated column that is based off of candidate status. Updates the API to use it as well. 
Also, for a high degree of reliability I added testing to ensure every status returns the correct weight. 
Testing: 
Use this query, observe status and statusWeight. Change Status and then observe the query results again. 
```
query poolCandidate {
poolCandidate(id: "ID") {
status
statusWeight
}
}
```
> add status sorting weight

- frontend/common/src/components/SideMenu/SideMenu.stories.tsx
Was missing this update after https://github.com/GCTC-NTGC/gc-digital-talent/pull/3849, and `npm run tsc` was giving a warning
This sort of thing should probably be caught is our linting workflow?
> Update straggler LoginIcon after @heroicon update

- frontend/talentsearch/src/js/components/applications/ApplicationActions.tsx
Resolves #3944 
This updates the path of the "Continue my application" link to go to the proper page (`/browse/applications/:id/apply`).
2. Login as `applicant@test.com`
3. Navigate to "My Applications"
4. Obtain the ID of the application
5. Use the ID to find the application in the `pool_candidates` table in the database
6. Ensure the application is part of an open, not expired pool and has the status `DRAFT`
7. Go back to an refresh the "My Applications" page
8. Click on the "Continue my application" link
9. Ensure if goes to the application page
> Bug - 3944 - Fix Application Card Continue Link

- frontend/admin/src/js/lang/fr.json
- frontend/common/src/components/UserProfile/ProfileSections/WorkPreferencesSection.tsx
- frontend/common/src/constants/localizedConstants.tsx
- frontend/common/src/lang/fr.json
- frontend/talentsearch/src/js/components/workPreferencesForm/WorkPreferencesForm.tsx
- frontend/talentsearch/src/js/lang/fr.json
Resolves https://github.com/GCTC-NTGC/gc-digital-talent/issues/3402
- visit each User Profile stories and scroll to Work Pref section. Flip between FR and EN and note all changing.
- in negation sub-section, note that formatting renders properly
- mainline story: https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/admin-user-profile--user-profile-story-5
- PR story:  https://61e099a1bb1465003a73d3ce-caujsixcak.chromatic.com/?path=/story/admin-user-profile--user-profile-story-5
- visit WorkPreferencesForm story and cycle between EN and FR (links: [mainline story](https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/workpreferencesform--individual-work-preferences) / [PR story](https://61e099a1bb1465003a73d3ce-caujsixcak.chromatic.com/?path=/story/workpreferencesfo …
> Fix up work preferences copy (form and profile section)

- frontend/talentsearch/src/js/components/Router.tsx
- frontend/talentsearch/src/js/lang/fr.json
Resolves #3752.
Removes **Request** menu item from talentsearch navigation.
1. Compile intl `npm run intl-compile --workspace=talentsearch`
2. Build app `npm run production --workspace=talentsearch`
3. Navigate to /search
4. Confirm **Request** menu item is no longer present
> Feature - Remove request menu item

- frontend/package-lock.json
https://github.com/GCTC-NTGC/gc-digital-talent/runs/8359805257
```
npm ERR! Missing: @microsoft/applicationinsights-react-js@3.4.0 from lock file
npm ERR! Missing: @microsoft/applicationinsights-web@2.8.7 from lock file
npm ERR! Missing: @microsoft/applicationinsights-common@2.8.7 from lock file
npm ERR! Missing: @microsoft/applicationinsights-core-js@2.8.7 from lock file
npm ERR! Missing: @microsoft/applicationinsights-shims@2.0.1 from lock file
npm ERR! Missing: @microsoft/dynamicproto-js@1.1.6 from lock file
npm ERR! Missing: @microsoft/applicationinsights-analytics-js@2.8.7 from lock file
npm ERR! Missing: @microsoft/applicationinsights-channel-js@2.8.7 from lock file
npm ERR! Missing: @microsoft/applicationinsights-dependencies-js@2.8.7 from lock file
npm ERR! Missing: …
```
> add missing dependencies in lockfile

- frontend/common/src/fakeData/fakeDepartments.ts
> Update instances of deprecated faker.unique to faker.helpers.unique

- api/graphql/schema.graphql
closes #3975 
a simple change of just adding a directive
testing:
open up `/admin/talent-requests`
open up `/search`
most likely the only requests are the ones seeded at basically the same time, so submit a request from the search then reload the requests table
> sort by newest-oldest requests on admin

- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/components/search/SearchForm.tsx
- frontend/talentsearch/src/js/components/search/deprecated/SearchContainer.tsx
- frontend/talentsearch/src/js/components/search/deprecated/SearchForm.tsx
Resolves #3976 
This makes the location field required on both the current and deprecated search form.
3. Add a Classification
4. Attempt to make a request and ensure it has a error on the location field
5. Set the `FEATURE_APPLICANTSEARCH` feature flag to false in `.apache_env`
6. Rebuild the php container
- `docker-compose stop php`
- `docker-compose rm php`
- `docker-compose up --build --detach`
7. Repeat steps 1-4
> Feature - 3976 - Location Field Required

- frontend/admin/src/js/adminRoutes.ts
- frontend/admin/src/js/components/PoolDashboard.tsx
- frontend/admin/src/js/components/poolCandidate/PoolCandidatesTable.tsx
- frontend/admin/src/js/components/poolCandidate/ViewPoolCandidate/ViewPoolCandidatePage.tsx
- frontend/admin/src/js/components/poolCandidate/ViewPoolCandidate/viewPoolCandidatePage.graphql
- frontend/admin/src/js/stories/PoolCandidate.stories.tsx
- frontend/common/src/components/UserProfile/ProfileSections/AboutSection.tsx
- frontend/common/src/components/UserProfile/UserProfile.tsx
This branch adds the ability to open the admin site, choose a pool candidate (application) and review the snapshot.
- The box on the left to change the status is part of #3691
- The designs call for a toggle to switch between rich and raw views but we don't have a toggle component yet.
- I added #3980 to create the component
- I added #3981 to update this page
1) Navigate to /admin/pools
1) Publish a pool
1) Open a new tab at /talent/profile
1) Finish your profile and switch to "actively looking"
1) Navigate to /browse/pools
1) Select the pool you published
1) Add "/view" to the end of the url :shrug: 
1) Click "apply to the pool"
1) Add any missing skills to an existing experience
1) Sign and submit application
1) Switch back to your admin tab
1) Click "view candidates" for your …
> View snapshot page

- frontend/admin/src/js/lang/fr.json
- frontend/talentsearch/src/js/lang/fr.json
Resolves #3989.
Two strings were using old IDs that did not connect them to their English equivalents. This fixes both of them.
1. Run `npm run intl-compile --workspace=admin`
2. Run `npm run production --workspace=admin`
3. Log in to /fr/admin/dashboard
4. Verify table header shows: "Il y a actuellement environ"...
5. Run `npm run intl-compile --workspace=talentsearch`
6. Run `npm run production --workspace=talentsearch`
7. Navigate to /fr/search
8. Verify table header shows: "Demandes les plus récentes"
> Bug - Fix missing French translations

- frontend/admin/src/js/components/pool/EditPool/CloseDialog.tsx
- frontend/admin/src/js/components/pool/EditPool/PublishDialog.tsx
- frontend/talentsearch/src/js/components/workLocationPreferenceForm/WorkLocationPreferenceForm.tsx
Resolves #3991.
Wraps several strings with `intl.formatMessage` to allow for their localization.
> Bug - Add intl.formatMessage for l10n on strings

- api/database/migrations/2022_09_20_213608_repair_users_armed_forces_status_column.php
Resolves #4017 
Creates a new migration, which converts any "true" or "false" strings to "VETERAN" and "NON_CAF".
> FIx any users.armed_forces_status values which may have been migrated incorrectly

- frontend/common/src/fakeData/fakeDepartments.ts
Resolves #4036
This replaces `faker.helpers.unique` with `faker.random.numeric` in the `fakeDepartments` helper to work around an issue with faker not being able to generate unique numbers.
> **Note:** A new issue is being created to update this once `faker.helpers.unique` works with numbers.
1. Check that chromatic built properly
2. Confirm the **Department** stories work
> Tooling - 4036 - Update Faker Unique

- frontend/talentsearch/src/js/components/login/LoginPage.tsx
- frontend/talentsearch/src/js/components/search/SearchHeading.tsx
- frontend/talentsearch/src/js/talentSearchRoutes.ts
Resolves #3969 
This update the talent search home path as well as the cancel link at `/login-info`.
1. Build talent search project `npm run production --workspace=talentsearch`
2. Navigate to `/search` and ensure heading image appears
3. Navigate to `/login-info`
4. Click **Cancel**
5. Ensure you land on the root route.
> Bug - 3969 - Fix login page cancel link

- frontend/admin/src/js/components/classification/ClassificationTable.tsx
- frontend/admin/src/js/components/skill/SkillTable.tsx
- frontend/admin/src/js/components/user/useFilterOptions.tsx
- frontend/common/src/components/ClientProvider/ClientProvider.tsx
- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
Resolves #3705 
Changes the default urql [request policy](https://formidable.com/open-source/urql/docs/basics/document-caching/#request-policies) to `cache-and-network`, to make really sure we always have up-to-date data, and as an easy way to avoid [this known issue](https://formidable.com/open-source/urql/docs/basics/document-caching/#document-cache-gotchas). 
Following a [slack conversation](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1664213144566129), where we realized we could optimize certain queries to use a different request policy, I've set requests for Skills and for Classifications as examples on how to use the `cache-first` request policy where it makes sense to do so.
> Change default request policy to avoid incorrectly-cached empty lists

- frontend/admin/src/js/components/Table/TableEditButton.tsx
- frontend/admin/src/js/components/classification/ClassificationTable.tsx
- frontend/admin/src/js/components/cmoAsset/CmoAssetTable.tsx
- frontend/admin/src/js/components/department/DepartmentTable.tsx
- frontend/admin/src/js/components/pool/PoolTable.tsx
- frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
- frontend/admin/src/js/components/skill/SkillTable.tsx
- frontend/admin/src/js/components/skillFamily/SkillFamilyTable.tsx
- frontend/admin/src/js/lang/fr.json
Resolves #3701 
This adds more context to the admin tables edit links using the label argument for the `tableEditButtonAccessor` function.
1. Build the admin project `npm run production --workspace=admin`
2. Navigate to the index for each admin section
3. Confirm the edit links content includes enough context (not just "edit")
> a11y - 3701 - Improve Edit Link Context

- frontend/talentsearch/src/js/components/workPreferencesForm/WorkPreferencesForm.tsx
closes #4086 
the issue was that the `data.wouldAcceptTemporary` condition meant `boolToString()` only ran when the variable was true, needs to run when it is either true or false so boolean 
testing: 
ensure form prefills for either option in the "I would consider accepting a job that lasts for:" selection
> work preferences prefill bug

- docker-compose.yml
- infrastructure/db/create-tc-db.sql
This branch downgrades the version of postgres used in the docker compose network.  It should match the versions and extensions in use in production.  It shouldn't affect the deployed applications at all.
Note 1: This will wipe your local database!  You will need to re-seed (or rerun the setup script).
Note 2: Your pgdata volume will have a different name depending on the directory you cloned into.  That's why step 2 is a listing of volumes.
1) docker-compose down
1) docker volume ls
1) docker volume rm gc-digital-talent_pgdata
1) docker-compose up --detach --build
1) docker-compose logs postgres
In the logs you should see some lines like this:
```
postgres_1     | You are now connected to database "gctalent" as user "postgres".
postgres_1     | …
```
> Change docker db version and install extensions

- api/app/GraphQL/Validators/UpdateUserInputValidator.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/api/userOperations.graphql
- frontend/admin/src/js/components/user/CreateUser.tsx
- frontend/admin/src/js/components/user/UpdateUser.tsx
- frontend/talentsearch/src/js/components/GovernmentInfoForm/GovInfoFormOperations.graphql
- frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
- frontend/talentsearch/src/js/components/aboutMeForm/aboutMeFormOperations.graphql
- frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.tsx
- frontend/talentsearch/src/js/components/createAccount/createAccountOperations.graphql
- frontend/talentsearch/src/js/components/employmentEquityForm/EmploymentEquityForm.test.tsx
- frontend/talentsearch/src/js/components/employmentEquityForm/employmentEquityOperations.graphql
- frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.stories.tsx
- frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationOperations.graphql
- frontend/talentsearch/src/js/components/myStatusForm/myStatusOperations.graphql
- frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryFormOperations.graphql
- frontend/talentsearch/src/js/components/workLocationPreferenceForm/workLocationPreferenceOperations.graphql
- frontend/talentsearch/src/js/components/workPreferencesForm/workPreferenceOperations.graphql
This resolves an issue with not being able to update an existing user due to the unique email validation by ignoring the user you are updating.
1. Regenerate the queries `npm run codegen --workspaces`
2. Build all projects `npm run production --workspaces`
3. Navigate tot `/admin/users/`
4. Edit a user and update field other than email
5. Ensure you can save the user
6. Edit it again, using an existing email
7. Ensure you get the unique email error
8. Navigate to `/talent/profile`
9. Go to to the "About Me" form and repeat steps 4-7
10. Logout and register as a new user
11. Attempt to create account with an existing email
12. Ensure you get the unique email error
> Bug - Improve unique email validation

- frontend/talentsearch/src/js/components/aboutMeForm/AboutMeForm.tsx
- frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.test.tsx
- frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.tsx
- frontend/talentsearch/src/js/lang/fr.json
Resolves #4056.
This makes the language used for labels of `first_name` and `last_name` fields consistent.
1. Compile languages `npm run intl-compile --workspace="talentsearch"`
2. Build talentsearch `npm run production --workspace="talentsearch"`
3. Navigate to /en/create-account
4. Confirm the first name and last name fields have the correct labels (First Name, Last Name)
6. Confirm the first name and last name fields have the correct labels (Prénom, Nom de famille)
7. Navigate to My Profile > About Me section
8. Confirm the first name and last name fields have the correct labels (First Name, Last Name)
9. Switch to French
10. Confirm the first name and last name fields have the correct labels (Prénom, Nom de famille)
> Update language used for first_name, last_name labels

- .github/workflows/e2e-tests.yml
Spun out from: https://github.com/GCTC-NTGC/gc-digital-talent/issues/4035#issuecomment-1261116699 h/t @mnigh 
This was causing e2e-tests to show as "skipped", and rarely showing the proper pass/fail status, which makes the e2e tests pretty useless.
Disabling docker layer cache for now, to avoid the github action "out of storage" error. We'll see in the github action run whether it makes the workflow run significantly longer (20-25 min seems to be regular).
> Disable docker layer caching in github action

- frontend/cypress/integration/admin/admin-workflows.spec.js
Due to the `e2e` tests being skipped, silently failing test was introduced in between fixes. This fixes that bug to get tests working again.
> Fix e2e admin workflow

- frontend/admin/src/js/components/poolCandidate/ApplicationStatusForm/ApplicationStatusForm.tsx
- frontend/cypress/integration/admin/pool-candidate.spec.js
Resolves #4110 
This allows admins to remove the expiry date for a pool candidate application. As well, it creates an `e2e` test for this scenario.
1. Build the admin project `npm run production --workspace=admin`
2. Navigate to the admin pools page `/admin/pools`
3. Click "View candidates" for a pool
4. Click "View application" for a pool candidate
5. Empty out the expiry date field
6. Save changes
7. Ensure that the form submits properly
> Bug 4110 - Empty candidate expiry date

- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/components/search/SearchHeading.tsx
- frontend/talentsearch/src/js/components/search/SearchPage.tsx
- frontend/talentsearch/src/js/components/search/deprecated/SearchContainer.tsx
Resolves #4031 
This resolves an odd visual bug where there was some overlapping background colours on the search page.
1. Build talentsearch `npm run production --workspace=talentsearch`
3. Ensure the odd overlap in the issue screenshot no longer appears
> Bug - 4031 - Fix search page gap

- frontend/admin/src/js/components/Table/TableEditButton.tsx
- frontend/admin/src/js/components/pool/PoolTable.tsx
- frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
Resolves #4123 
This updates the action links in admin tables to all be black rather than purple.
2. Navigate to the following pages and ensure all links in tables are black
- `/admin/dashboard`
- `/admin/pools`
- `/admin/pools/{poolId}/pool-candidates`
- `/admin/users`
- `/admin/talent-requests`
- `/admin/talent-requests/{requestId}`
- `/admin/settings/classifications`
- `/admin/cmo-assets`
- `/admin/settings/departments`
- `/admin/settings/skills/families`
- `/admin/settings/skills`
> Bug - 4123 - Fix inconsistent table action links

- frontend/talentsearch/src/js/components/roleSalaryForm/RoleSalaryForm.tsx
Resolves #4087 
This updates the "Learn more" link on the Role and Salary Expectations form to open in a new tab.
2. Navigate to `users/{userId}/profile/role-salary-expectations/edit`
3. Confirm that the Learn more link has (opens in a new tab) text and icon
4. Click link and confirm a new tab opens
> Feature - 4087 - Role, Salary Form External Link

- infrastructure/azure-pipelines.yml
This branch updates the VM for the build pipeline in Azure to Ubuntu 20.04.  I tried 22.04 but it didn't have PHP 7.4.
I did a build of this branch and deployed it to the dev app services.  I guess you could build it and deploy it again to test it?
https://dev.azure.com/tbs-sct/Talent%20Cloud/_build/results?buildId=55679&view=results
Closes #3609
> Change image in azure pipeline

- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
Resolves #4177, #4176.
The text following the **Compétences professionnelles** heading and the **Compétences transférables** heading has been fixed so it is in French. The ID was different between the English and French string as an extra space had been added to the English string which changed the hashed ID.
1. Compile languages `npm run intl-compile --workspace="talentsearch"`
2. Build admin `npm run production --workspace="talentsearch"`
3. Navigate to **Browse opportunities** page
4. Click on a pool name
5. Change language to French
6. Confirm the text following the **Compétences professionnelles** heading is not in English
7. Confirm the text following the **Compétences transférables** heading is not in English
> Remove extra space in defaultMessage values

- frontend/common/src/helpers/dateUtils.ts
Resolves #4100.
We're already saving dates to the API and database in a sensible way, as timezone-agnostic YYYY-mm-dd strings. We just need to be careful about how we present dates in the frontend.
It seems that `new Date(date_string)` will assume `date_string` is a UTC date, but then convert it into local time. That's reasonable when working with times strings, but less so when the original string is just a date. An easy way to get around the issue is to display/format the date as if we were also in UTC timezone.
> Fix Experience Date off by 1 error

- frontend/talentsearch/src/js/components/search/SearchPools.tsx
- frontend/talentsearch/src/js/lang/fr.json
Resolves #4198.
The text following the Pool name heading has been fixed so it is in French. The ID was different between the English and French string as as` <testId>` tags wrapping `{candidateCount}` been added to the English string which changed the hashed ID.
1. Compile languages `npm run intl-compile --workspace="talentsearch"`
2. Build admin `npm run production --workspace="talentsearch"`
3. Navigate to /fr/search
4. Confirm the text following the Pool name heading in the Résultats (Results) box is not in English
> Repair French text translation

- frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
This branch restores some partial work from the Hydrogen upgrade.  It adds a "view results" link to the new search page.
Testing:
Notes:
- It seems like there is a URL fragment issue on Firefox.  I opened #4195.
- This page is still behind a feature flag so no translation needed yet.
Closes #3826
> Restore view results link

- frontend/common/src/components/context/ContextContainer.tsx
We added a `ThemeProvider` that controls dark mode recently with half baked dark mode. This removes the `ThemeProvider` until we can fully bake dark mode 🧑‍🍳 🍰 
1. Build all projects `npm run production --workspaces`
2. Confirm the header and footer are not dark when `(prefers-color-scheme: dark)`
> Bug - Remove Theme Provider

- frontend/admin/src/js/components/pool/EditPool/ClosingDateSection.tsx
Adds a null check for the closing date on the edit pool form.
1. Navigate to http://localhost:8000/en/admin/pools/create .
2. Create a new pool and observe that the End Date field is populated with the standard "mm / dd / yyyy" placeholder.
3. Pick a date and click "Save closing date"
4. Refresh the page and observe that the selected date was preserved
Closes #4167
> Add null check for pool closing date

- frontend/common/src/components/Link/ScrollToLink.tsx
- frontend/common/src/components/Link/index.ts
- frontend/common/src/components/TableOfContents/AnchorLink.tsx
- frontend/talentsearch/src/js/components/search/EstimatedCandidates.tsx
Resolves #4195 
This adds a `<ScrollToLink />` component that implements smooth scrolling and fixes a bug with `href="#id"` links in Firefox.
2. Navigate to `/search` in firefox
3. Confirm "View results" smooth scrolls on first click
4. Navigate to `/talent/profile`
5. Confirm "On this page" links still function
> Bug - 4195 - Fix anchors in Firefox

- frontend/common/src/components/TableOfContents/Content.tsx
- frontend/common/src/components/TableOfContents/Navigation.tsx
- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
Resolves #4211 
Fix for small styling bug Jerbo flagged. This fixes the right hand padding on the pool advertisement page and also makes it responsive.
- Setup your environment with new changes
- Go to a Pool Advertisement page `http://localhost:8000/en/browse/pools/{poolId}`, and see padding on right hand side fixed.
- Also, try checking to see if responsive by shrinking/expanding screen size.
> Bug - Pool advertisement page padding

- frontend/admin/src/js/components/PoolDashboard.tsx
- frontend/indigenousapprenticeship/src/js/components/Router.tsx
Resolves #4203 
This removes the `data-h2` attribute from `react-helment` components so it is always on the `html` element.
We had `data-h2` on the html and within `<Helmet />` . This allowed `react-helmet` to take responsibility for it causing it to be removed while it figured out the locale. Removing it from `<Helmet />` gave the `index.html` responsibility and it never gets removed now.
1. Build admin `npm run production --admin`
2. Navigate to `/admin`
3. Navigate to different pages and ensure hydrogen styles are always applied to the `<Loading />` spinner
> Bug - 4203 - Remove data-h2 from react-helmet

- frontend/common/src/components/Link/ScrollToLink.tsx
- frontend/common/src/helpers/router.tsx
- frontend/indigenousapprenticeship/src/js/components/PageContainer.tsx
- frontend/talentsearch/src/js/components/PageContainer.tsx
- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/components/search/deprecated/SearchContainer.tsx
Resolves #4212 
This fixes an issue with the page not scrolling to a hash on page load.
Our `<ScrollToTop />` component was forcing the page to the top on every page load. This adds some code to check for a hash then wait for the matching element to exist in the DOM before scrolling to it.
> **Note**
> Please test in as many browsers you have available and note the browser and version you were using when you encounter any issues.
1. Build talentsearch `npm run production --workspace=talentsearch`
2. Navigate to `/search#results`
3. Ensure it scrolls to the results element
> Bug - 4212 - Scroll to hash on load

- frontend/admin/src/js/components/PoolDashboard.tsx
Did not think we needed the `Pending` component in `PoolDashboard` but we do, this reverts that change.
1. Confirm `/admin` loads
2. Confirm storybook works
> Bug - Fix admin suspense

- api/app/GraphQL/Validators/Mutation/PublishPoolAdvertisementValidator.php
- api/app/Models/Pool.php
- api/database/factories/PoolFactory.php
- api/database/helpers/ApiEnums.php
- api/database/migrations/2022_10_06_130017_create_pool_publishing_group.php
- api/database/seeders/PoolSeeder.php
- api/database/seeders/PoolSeederUat.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/editPoolOperations.graphql
- frontend/common/src/constants/localizedConstants.tsx
- frontend/common/src/fakeData/fakePools.ts
- frontend/common/src/messages/apiMessages.ts
- frontend/cypress/integration/admin/pools.spec.js
- frontend/cypress/integration/talentsearch/submit-application-workflows.spec.js
This branch adds a publishing group field to pool advertisement.
1. Test migrations and seeders, observe there is a new `publishing_group` column on `pools`
```
php artisan migrate
php artisan migrate:rollback --step=1
php artisan migrate:fresh --seed
```
2. Open storybook and confirm that the Edit Pool Form stories show a populated value
1. Build and launch the site, create a new pool candidate, observe that field starts empty
1. Fill and save all the other fields, try to publish, observe an error messages tells you to fill it
1. Fill the field, save, observe that it is saved
1. Change the field, save, observe that it is saved
1. Publish the pool, observe that it is successful
1. Run the e2e tests and confirm no failures
Closes #4200
> Pool publishing group

- frontend/admin/src/js/components/pool/EditPool/AssetSkillsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/ClosingDateSection.tsx
- frontend/admin/src/js/components/pool/EditPool/EssentialSkillsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/PoolNameSection.tsx
- frontend/admin/src/js/components/pool/EditPool/StatusSection.tsx
- frontend/admin/src/js/components/pool/EditPool/WorkTasksSection.tsx
- frontend/admin/src/js/components/pool/EditPool/YourImpactSection.tsx
- frontend/admin/src/js/components/user/UserProfile.tsx
- frontend/common/src/components/TableOfContents/Heading.tsx
- frontend/common/src/components/UserProfile/UserProfile.tsx
Resolves #4247 
This removes the nested `<h2> elements on the `EditPool` page.
2. Navigate to a pool `/admin/pools/{poolId}/edit`
3. Confirm there are no nested `<h2>` elements or errors in the console
> a11y - 4247 - Remove nested h2

- api/database/factories/PoolCandidateFactory.php
- api/database/seeders/DatabaseSeeder.php
closes #4263 
deletes fields from the factory/seeding that are to be deprecated 
testing:
checks pass
migrating/seeding looks right in adminer
> remove seeding of to be deprecated PoolCandidate fields

- frontend/admin/src/js/components/pool/EditPool/EditPool.tsx
- frontend/common/src/components/form/Checkbox/Checkbox.tsx
- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
- frontend/common/src/components/inputPartials/InputLabel/input-label.css
- frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx
Resolves #3836 
This removes the wrapping `<label>` element which was providing a second label to the checkbox when `boundingBox={true}` .
1. Build talentsearch `npm run production --workspace=talentsearch`
2. Navigate to the following experience forms and confirm is only one label for the bonding box checkboxes
- Community
- Education
- Personal
- Work
> a11y - 3836 - Remove nested labels, checkbox

- api/app/Models/Pool.php
- api/database/seeders/DatabaseSeeder.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolTest.php
- frontend/cypress/integration/admin/pools.spec.js
- frontend/cypress/integration/talentsearch/submit-application-workflows.spec.js
- frontend/talentsearch/src/js/components/browse/BrowsePoolsPage.test.tsx
- frontend/talentsearch/src/js/components/browse/BrowsePoolsPage.tsx
- frontend/talentsearch/src/js/components/browse/PoolCard.tsx
- frontend/talentsearch/src/js/components/browse/browseOperations.graphql
This branch adds a new query in the schema scoped to only return pool advertisements that have been published.  The browse opportunities page also filters the pools to just unexpired IT Jobs and sorts them by published and expired dates.
1. Run phpunit tests and observe that they all pass
2. Reseed your database
3. Run jest tests and observer that they all pass
4. Navigate to `http://localhost:8000/en/browse/pools` and observe that [the correct pools appear in the correct order](https://github.com/gctc-ntgc/gc-digital-talent/issues/4202)
5. Navigate to the admin site to ensure that all pools can still be managed as usual
A graphql query to help with testing:
```
query q {
publishedPoolAdvertisements {
id
name {
en
fr
}
publishedAt
expiryDate
publishingGroup    
advertisementStatus
}
}
``` …
> Advertise correct jobs

- frontend/cypress/integration/admin/pool-candidate.spec.js
Resolves #4309 
This fixes the `should edit and update pool candidate (FEATURE_APPLICANTSEARCH:off)` for pool candidates.
If the first user has no language ability selected (previously required field) then it is not possible to submit the old form. This just selects "English only" to fill out all required fields.
1. Make sure `FEATURE_APPLICANTSEARCH` feature flag is off
2. Run the cypress tests and confirm all `pool-candidate.spec.js` tests pass
> Test - 4309 - Fix Pool Candidate e2e

- frontend/talentsearch/src/js/components/signAndSubmit/SignAndSubmitPage.tsx
Resolves #4303.
For whoever (possibly @petertgiles as part of #4025) is adding in the as of yet added French translation string, the IDs have changed for these strings have changed so there with have to be some manually work done to create the connection.
1. Compile translations `npm run intl-compile --workspace=talentsearch`
3. Start storybook `npm run storybook --workspace=talentsearch`
4. Navigate to **Sign and Submit page** story
5. Verify signature list items on Sign and Submit page are correct
> Bug - Fix Sign and Submit page typos

- frontend/common/src/components/Chip/Chip.stories.tsx
- frontend/common/src/components/Chip/Chip.tsx
- frontend/common/src/components/Chip/chip.css
- frontend/common/src/lang/fr.json
- frontend/talentsearch/src/js/components/skills/AddedSkills/AddedSkills.test.tsx
Resolves #4206 
This wraps a dismissible chip in a button, increasing the touch area. As well, it adds an `aria-label` to improve context for the button action.
1. Run storybook `npm run storybook --workspace=common`
2. Open the "Chip Dismiss" story
3. Confirm the following
- you can click on any area of the 
- has focus indicator
- has hover indicator
> a11y - 4206 - Increase chip touch area

- frontend/common/src/components/SkillPicker/SkillPicker.tsx
This branch turns off autocomplete for the skill picker search box.
1. Navigate to your profile
2. Add an experience
3. Type in the skill search input and observe there is no autocomplete
Closes #4286
> Turn autocomplete off for skill picker search

- api/database/migrations/2022_10_17_141813_change_expiry_date_to_datetime.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/components/pool/EditPool/CloseDialog.tsx
- frontend/admin/src/js/components/pool/EditPool/ClosingDateSection.tsx
- frontend/admin/src/js/components/pool/EditPool/ExtendDialog.tsx
- frontend/admin/src/js/components/pool/EditPool/PublishDialog.tsx
- frontend/admin/src/js/components/pool/ViewPool.tsx
- frontend/common/package.json
- frontend/common/src/helpers/dateUtils.test.ts
- frontend/common/src/helpers/dateUtils.ts
- frontend/cypress/integration/talentsearch/submit-application-workflows.spec.js
- frontend/package-lock.json
- frontend/talentsearch/src/js/api/poolAdvertisementOperations.graphql
- frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationPageWrapper.stories.tsx
- frontend/talentsearch/src/js/components/ApplicationPageWrapper/ApplicationPageWrapper.tsx
- frontend/talentsearch/src/js/components/applications/ApplicationCard.tsx
- frontend/talentsearch/src/js/components/pool/PoolInfoCard.test.tsx
- frontend/talentsearch/src/js/components/pool/PoolInfoCard.tsx
- frontend/talentsearch/src/js/components/reviewMyApplication/ReviewMyApplicationPage.tsx
- frontend/talentsearch/src/js/components/signAndSubmit/SignAndSubmitPage.stories.tsx
- frontend/talentsearch/src/js/components/signAndSubmit/SignAndSubmitPage.tsx
This branch converts the pool advertisement expiry date / closing date from timestamptz to timestamp in the database and from a DateTimeTz to a DateTime in the API.  It also ensures that the front end is always sending UTC datetimes to the API and always interpreting the responses as UTC.  It adds `time-fns-tz` as a dependency for handling time zone conversions.  This seemed like a reasonable choice since we're already using `time-fns`.
The designers have not gotten back to me on when to show the date as Pacific and when to show it as local and how the copy will make that obvious.  For now I have the admin site always show Pacific and the talentsearch site always show local but I'll push the final update off to #4273.  I've skipped the poolcard tests until then, too.  The …
> Convert pool expiry TZ field to UTC

- frontend/admin/src/js/components/poolCandidate/PoolCandidatesTable.tsx
- frontend/admin/src/js/components/user/UserProfilePrintButton.tsx
- frontend/admin/src/js/components/user/UserTable.tsx
- frontend/admin/src/js/lang/fr.json
Resolves #4380.
1. Compile French `npm run intl-compile --workspace=admin`
2. Build admin `npm run production --workspace=admin`
3. Navigate and login at `/fr/admin`
4. Verify Document title for printing User profile is _Profil du candidat_
5. Verify Document title for printing Pool Candidate table results is _Profils de candidats_
6. Verify Document title for printing User table results is _Profils de candidats_
Since these components are already live on the production site, I have [added the French string for _Candidate Profile_](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4382/commits/077b92965a110b1a996db24f10aa365e873ea6be) based on another equivalent that was already in the fr.json file and the [French strings for _Candidate …
> Admin - Fix untranslatable strings

- frontend/common/src/components/form/Select/SelectFieldV2.tsx
Resolves #4400 
This custom sets the react-select menu [Style Object](https://react-select.com/styles#style-object) to have a higher z-index (11) than the [InputLabel](https://github.com/GCTC-NTGC/gc-digital-talent/blob/feature/3875-pool-candidates-fancy-filter/frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx#L73) (10).
> Bug - Set SelectFieldV2 menu z-index higher than input label

- frontend/common/src/constants/NonExecutiveITClassifications.tsx
- frontend/talentsearch/src/js/api/poolCandidateOperations.graphql
- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
- frontend/talentsearch/src/js/components/search/SearchForm.tsx
resolves #4374 
- Search page uses hard coded constants for the classifications named as NonExecutiveITConstants which are from IT-01 to IT-04. 
-  Eliminates pool id from the search
- Search page still filters by expected classifications as usual. No change on that in this PR.
> Modify search page to search across all pools 

- frontend/talentsearch/.env.example
- frontend/talentsearch/src/js/components/support/SupportForm.tsx
- frontend/talentsearch/src/js/lang/fr.json
- frontend/talentsearch/src/js/talentSearchConstants.ts
- frontend/talentsearch/webpack.base.js
Resolves #4231.
In addition to updating the support form error message in English and adding its French string translation, this also [adds TALENTSEARCH_SUPPORT_EMAIL environment variable](https://github.com/GCTC-NTGC/gc-digital-talent/commit/71ce5a00a17a6fd15444f3c2912a0bcc6333df82).
1. Compile talentsearch `npm run intl-compile --workspace=talentsearch`
3. Navigate to **/support**
4. Force an error by commenting out required `email` parameter in [SupportController](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/app/Http/Controllers/SupportController.php#L15)
5. Submit form 
6. Verify error toast message in English and French
> Feature - Update Support Form error

- frontend/common/src/components/MissingSkills/MissingSkills.tsx
- frontend/common/src/components/Pill/Pill.tsx
- frontend/talentsearch/src/js/components/experienceAndSkills/ExperienceAndSkills.tsx
- frontend/talentsearch/src/js/components/reviewMyApplication/ReviewMyApplicationPage.tsx
Resolves #4390 
- Updates the `<MissingSkills />` component styling to match the new design. 
- Moves the component above the "Add Experience" button on the ExperienceAndSkills page.
- Adds new red `error` color to the Pill component.
- Login
- Go to [Browse Pools](http://localhost:8000/en/browse/pools) and apply to job
- Scroll down to ExperienceAndSkills section on apply page and see new changes to component (`/en/browse/applications/{REPLACE_WITH_POOLCANDIDATEID}/apply`)
- Click on edit Experience and Skills button and see new changes to component (`en/users/{REPLACE_WITH_USERID}/profile/experiences?applicationId={REPLACE_WITH_POOLCANDIDATEID}`)
UPDATE: Need to talk to Jerbo about the [design ](https://www.figma.com/proto/spDwyr56BgQKrSdRiHztPL/Skills-and-EX---Poster-and-application-V2? …
> Feature - update missing skills style

- frontend/cypress/integration/talentsearch/direct-intake.spec.js
- frontend/cypress/integration/talentsearch/submit-application-workflows.spec.js
- frontend/talentsearch/src/js/components/Router.tsx
- frontend/talentsearch/src/js/components/pool/CreateApplication.tsx
- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
- frontend/talentsearch/src/js/components/pool/poolOperations.graphql
- frontend/talentsearch/src/js/components/pool/utils.ts
- frontend/talentsearch/src/js/directIntakeRoutes.ts
Resolves #4446 #4445
This removes the requirement to be logged in to browse pools and updates the logic to create an application to support anonymous users.
This may be over engineered and could be simplified but it seemed the best way to handle all possible states if someone navigates directly to create an application. Essentially when a user clicks on "Apply for this process" the following happens behind a loading spinner:
1. Navigates to `/browse/pools/{poolId}/create`
2. If the application can be created, mutation fires and redirected to application
3. If user is not an admin, or pool is draft they are redirected back to the pool where it shows "not found"
4. If the user has applied and mutation is not running, they are redirected to either the application or pool advertisement
In …
> Bug - 4446 - Fix auth browse page

- api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/database/helpers/ApiEnums.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/CountPoolCandidatesByPoolTest.php
This branch adds a new query to the API for counting the number of pool candidates by filtering on their parent users and then groups them by pool.  I wasn't able to get a "natural implementation" based on the existing model and so it was implemented by a standalone query and manual query building.  H/t to @vd1992 for getting me started on the implementation.
I wasn't able to get it to also return the total number of users as originally defined in the issue.  I suggest issuing the existing user query at the same time in the same network request from the frontend.
- I like to uncomment the DB listener in api/app/Providers/AppServiceProvider.php and review the logged SQL.
- You'll need to use GraphQL Playground since there's no frontend usage for this yet.
```
query ($where: …
```
> Candidate count, filtered by user, grouped per pool

- frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/DisabilityDialog.tsx
- frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/IndigenousDialog.tsx
- frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/VisibleMinorityDialog.tsx
- frontend/talentsearch/src/js/components/employmentEquityForm/dialogs/WomanDialog.tsx
- frontend/talentsearch/src/js/lang/fr.json
This branch collections a number of French corrections together.
Check that the acceptance criteria have been met:
>-  "Browse opportunities" was translated wrong. Please use "parcourez les opportunités" everywhere it appears. (especially in the nav)
>- Missing link in French for “sample tests” on the Languages profile sub-page
>- "surmonte ces obstacles" should be "surmonter ces obstacles" at the top of Diversity, equity and inclusion page
>- "seront utilisées" should be "seront utilisés" on both bullets on the Diversity, equity and inclusion page
>- For all four definitions used in the modals ont he Diversity, equity and inclusion plage. Please go copy/paste the french definition from the statscan page (which is linked in the modal). The translations are all a bit off on those.
Closes …
> The French Correction

- frontend/admin/src/js/components/home/HomePage.tsx
- frontend/admin/src/js/lang/fr.json
- frontend/talentsearch/webpack.base.js
Resolves #4485.
1. Compile admin `npm run intl-compile --workspace=admin`
2. Build admin `npm run production --workspace=admin`
3. Navigate to **/en/admin**
4. Verify instructional text for the talent cloud pool manager portal home page includes **GC Digital Talent**
5. Navigate to **/fr/admin**
6. Verify instructional text for the talent cloud pool manager portal home page includes **Talent numérique du GC**
7. Build talentsearch `npm run production --workspace=talentsearch`
8. Navigate to **/en/search**
9. Verify page title is **GC Digital Talent**
> Copy - Change GC Talent to GC Digital Talent

- api/app/GraphQL/Mutations/CreateApplication.php
- api/app/GraphQL/Validators/Mutation/CreateApplicationValidator.php
- api/app/Rules/NotAlreadyApplied.php
- api/app/Rules/PoolPublished.php
- api/database/helpers/ApiEnums.php
- api/tests/Feature/PoolApplicationTest.php
- frontend/common/src/lang/fr.json
- frontend/common/src/messages/apiMessages.ts
- frontend/talentsearch/src/js/components/pool/CreateApplication.tsx
- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
This rearranges the logic in the `CreateApplication` mutation to prevent users from overwriting existing applications. We now throw validation errors earlier. This helps to reduce the amount of business logic on the frontend and reduce odds of leaving users hanging.
GraphQL has the ability to return [partial errors](https://lighthouse-php.com/master/digging-deeper/error-handling.html#partial-errors). This PR uses that to return an `APPLICATION_EXISTS` along with the existing application so we can redirect a user to that existing application. 
On error, the toast is shown twice and using `toastId` is not preventing it for some reason. Is there a better way to prevent duplicate toasts?
1. Run PHPUnit tests
2. Reseed database
3. Build talent search `npm run production …
> Bug - 4463 - Prevent application overwrite

- frontend/common/src/helpers/router.tsx
- frontend/talentsearch/src/js/components/PageContainer.tsx
This removed the client redirect to `/404` in talent search. This was preventing users from clicking the back button. This removes that and updated the `notFound` component with the new 404 page.
1. Build talent search `npm run production --workspace`
2. Navigate to any page
3. Edit the url to be nonsense to trigger 404
4. Click the back button in your browser
5. Ensure you are properly sent back and are no longer on the 404 page
Resolves #4411
> Bug - 4411 - Remove router 404 redirect

- frontend/talentsearch/src/js/components/languageInformationForm/LanguageInformationForm.tsx
This updates the links on `LanguageInformationForm` to use the `ExternalLink` component which includes the indicators for when a link opens in a new tab.
2. Navigate to the language information form on a profile
3. Confirm the links next to "Bilingual evaluation" options have the new tab indicators
4. Select "I am bilingual (En/Fr) and have NOT..." option
5. Confirm the link for self assessment also has the indicators
Resolves #4484
> a11y - 4484 - New Tab Indicators

- frontend/common/src/components/Auth/AuthenticationContainer.tsx
This branch solves the problem where an auth refresh in one tab causes the refresh to fail in a second tab by loading the refresh token from local storage instead of the provider state.
This is a "2 point" solution suggested by Tristan in the issue.  It has the downside of blocking the UI while the token is retrieved from storage and issuing a useless refresh request.  A better solution eventually would be to keep the provider state in sync between tabs using something like storage events.  Or even switching to an auth library that handles this in a worker thread.
1. Set up your environment for log in and log out with Sign In Canada
- Set the log out endpoint in frontend/.apache_env
- Set the client settings in api/.env
2.  Open a tab and log into the app
3. Open a second tab and log into …
> Use refresh token from local storage

- frontend/admin/src/js/components/pool/EditPool/AssetSkillsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/EssentialSkillsSection.tsx
This replaced the `<SkillPicker>` with `<Chips>` on the `EditPool` page when the `formDisabled` variable is `true`.
2. Navigate to pools index `/admin/pools`
3. Edit a pool that is **not** a draft
4. Confirm the skill picker does not appear
Resolves #4474
> Bug - 4474 - Remove skill picker on non-draft pool edit page

- frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
- frontend/talentsearch/src/js/components/search/SearchForm.tsx
This adds `z-index` to the `MultiSelect` field as well as replacing the `MultiSelect` with a `MultiSelectFieldv2` on the `SearchForm`.
3. Use the "Regions" dropdown
4. Ensure that it does not get overlapped by the following labels
Resolves #4531
> Bug - 4531 - Fix multi select overlap

- frontend/admin/src/js/components/pool/EditPool/OtherRequirementsSection.tsx
This updates the default value for location on the edit pool page to be remote.
1. Build admin `npm run production --workspace-admin`
2. Create a new pool in admin
3. Scroll down to the location option in other requirements
4. Confirm the default is "Remote optional (Recommended)"
Resolves #4481
> Feature - 4481 - Update default isRemote option

- frontend/admin/src/js/components/user/UserTable.tsx
- frontend/admin/src/js/lang/fr.json
Resolves #4472 
Removes 'New User' button from user table. This does not remove the page for creating a user.
To test:
1. Navigate to users table `/admin/users`
2. Confirm there's no New User button above the table
> Remove 'New User' button from user table

- .github/workflows/bundlewatch.yml
- .github/workflows/check-lighthouse-schema.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/jest.yml
- .github/workflows/lint.yml
- .github/workflows/phpunit.yml
- .github/workflows/storybook.yml
- api/graphql/schema.graphql
This updates the `set-output`  command in the schema workflow since it has been deprecated.
1. Check actions for deprecated warnings
- [Checks](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4547/checks)
3. Confirmed the failed schema check still outputs proper info
- [Schema Fail](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3372005134)
Resolves #4383 and #4404
> Debt - 4383 - Update set-output

- frontend/admin/src/js/components/pool/EditPool/PoolNameSection.tsx
- frontend/admin/src/js/components/pool/ViewPool.tsx
- frontend/admin/src/js/lang/fr.json
This branch updates the "view pool" page to align it with the "edit pool" page.
Compare "Edit" on the left with "View" on the right:
English:
En Francais:
Closes #4475
> Align pool details pages

- frontend/common/src/components/Card/CardFlat/CardFlat.tsx
This uses `lodash/omit` to remove the label attribute from being spread onto the `<Link>` found in `<CardFlat>`.
2. Navigate to `/browse`
3. Inspect the Indigenous IT Apprenticeship link near the bottom of the page and confirm it has no `label` attribute. 
Resolves #4559
> Bug - 4559 - Remove label from prop spread on CardFlat Link

- frontend/admin/webpack.base.js
- frontend/indigenousapprenticeship/webpack.base.js
- frontend/talentsearch/webpack.base.js
Resolves #4567.
1. Build workspaces `npm run production --workspaces --if-present`
2. Verify **.DS_Store** assets are not part of compilation (i.e. not present in log)
> Debt - Add .DS_Store to CopyPlugin ignore

- frontend/admin/src/js/lang/whitelist.yml
- frontend/common/src/lang/fr.json
- frontend/talentsearch/src/js/lang/fr.json
Related to #4564 - this branch adds the remaining missing translations to "green up" our translation CI step.
Note, I know these aren't perfect, for example xgocDD, but this is just to get our repo up to a good baseline.  I'm happy to spinoff new issues for whatever is found.
<details>
<summary>Admin - English</summary>
```
{
"w/qZsH": {
"defaultMessage": "Classification",
"description": "Label displayed on the pool form classification field."
},
"wHX/8C": {
"defaultMessage": "Admin",
"description": "Title tag for Admin site"
}
}
```
</details>
<details>
<summary>Admin - French</summary>
```
{
"w/qZsH": {
"defaultMessage": "Classification",
"description": "Label displayed on the pool form classification field."
},
"wHX/8C": {
"defaultMessage": "Admin",
"description": "Title tag for Admin …
```
> Baseline translations

- frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx
- frontend/admin/src/js/components/pool/CreatePool.tsx
- frontend/admin/src/js/components/pool/deprecated/CreatePool.tsx
- frontend/admin/src/js/components/pool/deprecated/UpdatePool.tsx
- frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx
- frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
- frontend/common/src/lang/fr.json
- frontend/common/src/messages/commonMessages.ts
- frontend/talentsearch/src/js/components/search/deprecated/SearchForm.tsx
- frontend/talentsearch/src/js/lang/fr.json
Resolves #4580.
- [Adds reusable `nameNotLoaded` message](https://github.com/GCTC-NTGC/gc-digital-talent/commit/3db8eeafffd07e6d4e676ae6602cc863edd6da88)
- [Replaces static strings with `nameNotLoaded`](https://github.com/GCTC-NTGC/gc-digital-talent/commit/e08fe271c165fe3e052c5d617a8ac04580461d5d)
- [Replaces single use translation with common `nameNotLoaded`](https://github.com/GCTC-NTGC/gc-digital-talent/commit/517afed7664cab9295f3eb0fda7a1fca3c4d570b) (this avoids having to send string to be translated!)
> Bug - Fixes non-i18n strings

- api/app/GraphQL/Directives/PluckDirective.php
- api/app/Models/User.php
- api/tests/Feature/UserTest.php
Resolves #4660.
I wrote a regression test for this! Which actually found a similar bug in a directive I wrote.
Testing:
1. seed the database (`docker-compose exec -w /var/www/html/api php php artisan db:seed`)
2. Run the following two queries against our api. I used http://localhost:8000/graphql-playground.
```
query {
countApplicants(where:{
languageAbility: null
})
}
``` 
```
query {
countApplicants(where:{})
}
``` 
Or you can run them with one query using _aliases_ 😉 
```
query {
nullLang: countApplicants(where:{
languageAbility: null
})
undefinedLang: countApplicants(where:{})
}
```
3. Both queries should return the same number. (And it shouldn't be zero!)
> 4660 language ability null

- api/database/factories/ApplicantFilterFactory.php
- frontend/talentsearch/src/js/components/request/CreateRequest.tsx
Resolves #4659.
- [Adds missing wouldAcceptTemporary to CreateRequest](https://github.com/GCTC-NTGC/gc-digital-talent/commit/3988933b24423fd89c6095e3498d7536c64b1d35)
- [Fixes would_accept_temporary to be true or null since false is never an option based on the CreateRequest form value](https://github.com/GCTC-NTGC/gc-digital-talent/commit/a6d9ea45e23cc3318d45319aed98417883355c4a)
> Bug - Adds missing wouldAcceptTemporary to CreateRequest

- frontend/admin/src/js/components/pool/ViewPool.tsx
closes #4572 
updates the link to be pointed at the candidates table
testing:
go to `/en/admin/pools/:id`
and check the links
> bug/4572-manage-candidates-link 

- frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
This uses the new `dateUtils` to format the search request date.
2. Navigate to a search request
3. Confirm "Date Requested" is formatted in local timezone
Resolves #4548
> Copy - 4548 - Format request date

- frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInfoTabDialogs.tsx
This adds a `<FormProvider />` to the candidate dialogs which is now required for any form inputs.
2. Navigate to a user profile
3. Open both the "Change status" and "Expiry date" dialogs in the "Pool status" table
4. Confirm the app **_does not_** crash. 
Resolves #4593
> Bug - 4593 - Fix candidate profile dialogs

- frontend/common/src/components/DropdownMenu/DropdownMenu.tsx
- frontend/common/src/components/ScrollArea/ScrollArea.tsx
- frontend/common/src/components/SkillPicker/FamilyPicker.tsx
- frontend/common/src/components/SkillPicker/SkillPicker.tsx
- frontend/common/src/lang/fr.json
This combines the inputs for filtering the skill picker into a single line (dropdown, input).
> **Note**
> @Jerryescandon answered all my questions, leaving them here for a paper trail. 👍
>
>  tldr; We will not be supporting multiple options for now.
I'm unsure of the best terminology to use in the button. In the mockup it said "All skills", which makes sense initially. However, once you select any number of families, it makes less sense. 
**_What should the button text be once any number of families have been selected?_**
Since we can select multiple families, I have forced the dropdown to stay open when a familiy selected. Just confirming that this is how we prefer it to work.
2. Navigate to the create experience form …
> Feature - 4392 - Combine skill picker inputs

- frontend/talentsearch/src/js/components/languageInformationForm/ConsideredLanguages.tsx
- frontend/talentsearch/src/js/lang/fr.json
This updates the link test for the language proficient self assessment link for users of assistive technology.
2. Navigate to the language information form
3. Select "Bilingual positions"
4. Select "I am bilingual (En/Fr) and have NOT completed an official..."
5. Confirm the link text is "language proficiency self assessment" and the sentence makes grammatical sense
6. Confirm the French has been updated as well
Resolves #4497
> a11y - 4497 - Improve self assessment link context

- api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
- api/app/Models/PoolCandidate.php
- api/tests/Feature/CountPoolCandidatesByPoolTest.php
- frontend/talentsearch/src/js/components/search/SearchContainer.tsx
Resolves #4557 
- Alright, I believe the solution was filtering by the [available users in pools](https://github.com/GCTC-NTGC/gc-digital-talent/blob/bug/4557-search-page-queries/api/app/Models/User.php#L260-L283) in the CountPoolCandidatesByPool query builder. This ensures the pool candidates are QUALIFIED_AVAILABLE or PLACED_CASUAL, and ensures the pool candidate hasn't expired. 
```php
public static function filterByAvailableInPools(Builder $query, ?array $poolIds): Builder
{
if (empty($poolIds)) {
return $query;
}
$poolFilters = [];
foreach ($poolIds as $index => $poolId) {
$poolFilters[$index] = [
'poolId' => $poolId,
'expiryStatus' => ApiEnums::CANDIDATE_EXPIRY_FILTER_ACTIVE,
'statuses' => [ApiEnums::CANDIDATE_STATUS_QUALIFIED_AVAILABLE, ApiEnums::CANDIDATE_STATUS_PLACED_CASUAL]
]; …
```
> Bug - Search page queries

- frontend/talentsearch/src/js/components/Home/partials/Opportunities/Opportunities.tsx
This adds a leading `/` to the link to the IAP on the homepage to prevent duplicate locales.
2. Navigate to the homepage
3. Ensure the "Apply now" link under "Indigenous Apprenticeship Program" does not have a duplicate locale and links to the proper address in both English and French
Resolves #4739
> Bug - 4739 - Fix IAP Homepage Link

- frontend/talentsearch/src/js/components/experienceForm/ExperienceSkills.tsx
This fixes a bug where we used the `essentialSkills` to check when to display separators for `nonEssentialSkills`.
**Bonus**: Adds `decorative` prop for the separator between headings and list items.
2. Make sure you have a published pool advertisement with a different number of essential and non-essential skills
3. Create an application for that pool
4. Edit the skills and experiences on that application
5. Confirm the non-essential skills have the correct layout of separators
Resolves #4592
> Bug - 4592 - Fix skill separator logic

- frontend/admin/src/js/components/pool/PoolTable.tsx
This replaces the normal hyphen for classifications on the `/admin/pools` page with a non-breaking hyphen ("&#8209;") to prevent it from wrapping on smaller screen sizes.
3. Reduce screen size to mobile width
4. Confirm classifications are not wrapping
Resolves #4269
> Bug - 4269 - Prevent classification wrapping

- api/app/Models/PoolCandidate.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/components/poolCandidate/PoolCandidatesTable.tsx
Resolves #4621 
- Adds dropdown to Pool Candidates table.
- Dropdown should include the options: All Table (name AND email), Name, and Email.
- Go to [Admin page](http://localhost:8000/en/admin) and login as admin.
- Go to [Pools table](http://localhost:8000/en/admin/pools) and select "View Candidates" on any of the pools.
- Play around with the Search filter making sure to test all three options (All table, name, and email)
> Feature - pool candidates search filter dropdown

- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx
The Axe tests were failing after an initial timeout of another test.  I assume Axe doesn't clean itself up properly after a timeout.
I just bumped up the timeout for now and placed an issue on the board (#4755) to try to improve the speed of the tests.  I'm not sure it's under our control.  :cry: 
Tests:
Closes #4746
> Bump jest timeout for experience tests

- frontend/talentsearch/src/js/components/pool/CreateApplication.tsx
- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
- frontend/talentsearch/src/js/components/pool/poolOperations.graphql
This removes `roles` from the `getPoolAdvertisementQuery` and favours the `AuthorizationContext` to fix an issue where users could not apply to pools in French.
We were querying roles in two places at the same time. The query we were using was being cancelled in favour of the top level query. This uses the top level query instead to prevent it from being cancelled. The root of the issue was a re-render happening at the `LanguageRedirectContainer` level where our `useLocation` hook is causing unecessary re-renders. This works around that issue but will be better resolved by #4597 
1. Run codegen `npm run codegen --workspaces`
2. Build talent search `npm run production --workspace=talentsearch`
3. Attempt to apply to a pool on the French site while anonymous (not logged in)
4. Confirm the …
> Bug - 4765 - Fix Application Request Priority

- frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
- frontend/talentsearch/src/js/lang/fr.json
This adds "profile" to the title of user profiles to make them more descriptive.
2. Navigate to the profile
3. Confirm the title is "First Last's Profile" in English
4. Confirm the title is "Profile de First Last" in French
Resolves #4624
> a11y - 4624 - Descriptive profile title

- frontend/admin/src/js/components/Router.tsx
- frontend/common/src/helpers/lazyRetry.ts
- frontend/talentsearch/src/js/components/Router.tsx
This implements a retry function for dynamic imports to help prevent `ChunkLoadError`
When we serve our chunks, they are cached in the browser. The `ChunkLoadError` occurs when the browser looks for the file and it does not exists for any number of reasons (original cached file no longer exists, renamed, etc.).
This PR does two things
1. Names our chunks (previously randomly generated)
2. Implements a retry function for loading chunks
By naming chunks, we make debugging easier since file names are human readable and mirror the component name. Also, when the browser caches the file, the name remains the same for all builds so it should be able to find it more consistently.
In the event that the file could not be found we force a browser refresh to hopefully clear the cache and look for the …
> Bug -  4786 - Improve code splitting

- frontend/common/.storybook/preview.js
This adds a missing import for the `withRouter` decorator for `common` stories.
1. Run common storybook `npm run storybook --workspace=common`
2. Ensure it loads properly
> Bug - Fix missing decorator import

- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx
- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.tsx
- frontend/talentsearch/src/js/components/experienceForm/ExperienceSkills.tsx
This hides steps 3 and 4 on the experience form when editing a user profile.
1. Navigate to profile and add an experience
2. Confirm that Skills in Detail and Additional Information sections do not appear and you can still save the form
1. Start an application then add/edit an experience from the application review page
2. Confirm that Skills in Detail and Additional Information sections appear and you can still save the form
Resolves #4828
> Feature - 4828 - Hide skills details profile

- api/app/Models/PoolCandidateSearchRequest.php
- api/database/factories/PoolCandidateSearchRequestFactory.php
- api/database/helpers/ApiEnums.php
- api/database/migrations/2022_11_17_173638_request_status_to_datetime.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/api/poolCandidateSearchRequestOperations.graphql
- frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
- frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx
This branch adds a "Done Date" field to the search request model and converts the Status attribute to be derived from that date.  It also adds the new done date field to the request view in admin.
> **Note**
> I noticed that the "save notes" button was reapplying the status every time.  That was a problem now that there's a timestamp so I fixed that.
<details>
<summary>SQL for testing</summary>
```
select id, status, updated_at/*, done_at*/  
from pool_candidate_search_requests pcsr
order by id
```
</details>
<details>
<summary>Graphql for testing</summary>
```
query {
poolCandidateSearchRequests {
id
status
doneDate
}
}
```
```
mutation updateStatus(
$id: ID!
$poolCandidateSearchRequest: UpdatePoolCandidateSearchRequestInput!
) {
updatePoolCandidateSearchRequest(
id: $id …
```
> Add done date

- .vscode/project-words.txt
- frontend/common/src/components/context/NestedLanguageProvider.tsx
- frontend/common/src/helpers/localize.ts
This creates the `NestedLanguageProvider` to support secondary languages based on a search param.
This uses `react-router` to get the search params and `LanguageProvider` so it must be used as a child of both. I believe the best place to use this is wrapping all items in the `<Layout>` component which is how it was done during testing.
Since we are use user input in search params, this makes use of maps for a more secure approach.
```tsx
import NestedLanguageProvider from "@common/components/context/NestedLanguageProvider";
import * as ojwMessages from "../lang/ojwCompiled.json";
import * as micMessages from "../lang/micCompiled.json";
const messages: Map<string, Messages> = new Map([
["ojw", ojwMessages],
["mic", micMessages],
]);
const Layout = () => {
...
return ( …
```
> Feature - 4795  - Create nested language provider

- frontend/admin/src/js/components/classification/ClassificationTable.tsx
- frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx
- frontend/indigenousapprenticeship/src/js/lang/fr.json
Resolves #4718 
- Wraps the image "header" in a `h1` tag, along with invisible text in a `span` for screen readers.
- Go to IAP homepage. 
- Ensure that image is wrapped in `h1` along with invisible text in span.
- Switch to French and ensure it displays hidden text correctly.
> Accessibility - IAP page h1 tag

- frontend/common/src/components/context/LocaleProvider.tsx
This branch updates the locale switching logic.  You can refer back to the LanguageRedirectContainer.tsx diff
before React Router:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597/files#diff-a2473921f83ace136f802adaab3ebaa1dd8a712484ed0dd7edadf36364b672d9L41
Testing:
Closes #4884
> Update locale switching logic

- frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx
I've updated the filters to use the  localized constants instead of their own strings.
Search page (unchanged):
Result:
En francais:
Closes #4772
> Update copy for work duration

- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
- frontend/talentsearch/src/js/lang/fr.json
This replaced the disabled button on pool advertisements with a "Continue my application" button when the current user has already started an application.
2. Login and start an application to a pool
3. Navigate to the advertisement for that pool
4. Confirm the apply button has been replaced by "Continue my application" and it takes you to your existing application
5. Confirm the text updates to "Continuer ma candidature" in French
Resolves #4776
> Bug -  4776 - Continue application if started

- frontend/admin/src/js/components/pool/EditPool/EditPool.test.tsx
- frontend/admin/src/js/components/pool/EditPool/EditPool.tsx
- frontend/admin/src/js/components/pool/EditPool/ExtendDialog.tsx
- frontend/admin/src/js/components/pool/EditPool/StatusSection.tsx
- frontend/admin/src/js/components/pool/EditPool/useMutations.ts
Resolves #4775 
- Fixes the broken form submission on extend pool closing date on Edit Pool page. 
- The reason for it not working was the Dialog closing (removed from the DOM) before the form could submit. I followed the suggestions from Dialog radix docs to fix [asynchronous form submissions](https://www.radix-ui.com/docs/primitives/components/dialog#close-after-asynchronous-form-submission).
- Also, adds a fix for `endDate` defaultValue not showing up on the `date` input. Removing the time from the date was the solution.
- Go to admin page  and go to Pools table.
- Edit a pool with status Expired/Published. If none exist close a pool early, or create a new one.
- Scroll to bottom and try extending the pool date.
- Ensure default value shows up on date input. 
- Ensure form is submitted …
> Bug - Fix extend pool closing date

- frontend/talentsearch/src/js/components/search/SearchForm.tsx
This moves the conditions of employment section to the bottom of the search form.
2. Navigate to search page
3. Confirm "Conditions of employment / Operational requirements" shows up at the bottom
Resolves #4823
> Feature - 4823 - Move search employment conditions

- frontend/admin/src/js/components/user/UserTable.tsx
This updates the user table mail links to use a normal `<a>` tag rather than the `<Link>` component that is meant for internal links only.
3. Click on the of the email links and confirm it opens your mail client with the proper address
Resolves #4897
> Bug - 4897 - Fix user table mail links

- api/database/seeders/PoolSeeder.php
- frontend/cypress/e2e/talentsearch/search-workflows.cy.js
two things I noticed
first: search workflow would fail sometimes due to chance, for this I constrained the seeded digital careers pool to be more predictable and adjusted the search workflow to look for it
second: stream requirement was merged in with #4864 but this was not reflected in the workflow, and it threw no errors probably due to this line below, I added stream selection into the workflow
closes #4902
> change pool seeding + cypress test tweak

- frontend/admin/src/js/components/searchRequest/SearchRequestTable.tsx
Resolves #4774.
Updates the Search Requests table to properly sort the date received column.
To test by navigate to the requests table in admin and confirm sorting by the "Date Received" column orders rows properly by time. It may be easier to test this in storybook due to the seeder generating requests with the same date.
> Update requests tables to properly sort date

- frontend/admin/src/js/components/apiManagedTable/TableFooter.tsx
- frontend/admin/src/js/lang/fr.json
- frontend/common/src/components/Toast/Toast.tsx
This updates the print button on the api table to show a toast when a user attempts to print with no rows selected. Also, it updates the font weight to match the CSV link.
2. Navigate to the users table
3. Click "print" in the footer without selecting rows
4. Confirm toast appears with error message
5. Select from rows and attempt to print again
6. Confirm print window appears
Resolves #3824
> Bug - 3824 - Table print warn no selection

- frontend/admin/src/js/components/Table/Table.tsx
- frontend/admin/src/js/components/apiManagedTable/BasicTable.tsx
- frontend/admin/src/js/lang/fr.json
This follows the [ARIA Authoring Practices Guideline for Sortable Tables](https://www.w3.org/WAI/ARIA/apg/example-index/table/sortable-table) to improve the a11y for our `<Table>` components sort logic.
- Adds `<caption>` with help text describing sorting
- Adds an `aria-sort` property to the table headers to indicate the sort order
- Adds a `<button>` element and moves sort props to the button
- Updates the styling to show `:hover` and `:focus-visible` styles
- Removes the `title` attribute
2. Navigate to the `/fr/dashboard`
3. Inspect the table and ensure the English text is no longer present (`th[title="Toggle SortBy"]`)
4. Ensure the caption is present
5. Ensure `:hover` and `:focus-visible` styles are present
6. Ensure the …
> A11y - 4793 - Fix table sort markup

- frontend/admin/src/js/components/classification/CreateClassification.tsx
- frontend/admin/src/js/components/classification/UpdateClassification.tsx
- frontend/admin/src/js/components/cmoAsset/CreateCmoAsset.tsx
- frontend/admin/src/js/components/cmoAsset/UpdateCmoAsset.tsx
- frontend/admin/src/js/components/department/CreateDepartment.tsx
- frontend/admin/src/js/components/department/UpdateDepartment.tsx
- frontend/admin/src/js/components/pool/EditPool/AssetSkillsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/EssentialSkillsSection.tsx
- frontend/admin/src/js/components/pool/deprecated/CreatePool.tsx
- frontend/admin/src/js/components/pool/deprecated/UpdatePool.tsx
- frontend/admin/src/js/components/poolCandidate/CreatePoolCandidate.tsx
- frontend/admin/src/js/components/poolCandidate/UpdatePoolCandidate.tsx
- frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx
- frontend/admin/src/js/components/searchRequest/SingleSearchRequestPage.tsx
- frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx
- frontend/admin/src/js/components/skill/CreateSkill.tsx
- frontend/admin/src/js/components/skill/UpdateSkill.tsx
- frontend/admin/src/js/components/skillFamily/CreateSkillFamily.tsx
- frontend/admin/src/js/components/skillFamily/UpdateSkillFamily.tsx
- frontend/admin/src/js/components/user/CreateUser.tsx
- frontend/admin/src/js/components/user/UpdateUser.tsx
This updates the headings on the admin app to meet the [guidelines for heading ranks](https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks).
> **Note**
> The [axe Browser Extension](https://www.deque.com/axe/browser-extensions/) will be very helpful here
2. Navite to every page in admin
3. Ensure each page starts with a `<h1>` and headings only increase by one at a time
Resolves #4913
> a11y - 4913 - Adjust admin heading ranks

- frontend/admin/src/js/lang/fr.json
- frontend/common/src/lang/fr.json
- frontend/indigenousapprenticeship/src/js/lang/fr.json
- frontend/talentsearch/src/js/lang/fr.json
Resolves #4489.
Removes unused strings from fr.json files. Related to https://github.com/GCTC-NTGC/gc-digital-talent/pull/4920.
- admin: 717-651 = 66
- common: 512-472 = 40
- indigenousapprenticeship: 93-89 = 4
- talentsearch: 714-621 = 93
203 unused strings removed from fr.json files! ✂️ 
1. Delete all **en.json**, **newTranslations.json**, and **untranslated.json** files from within **/frontend** (these are untracked files and could have leftover work from other branches)
2. Extract admin `npm run intl-extract --workspace=admin`
3. Extract common `npm run intl-extract --workspace=common`
4. Extract indigenousapprenticeship `npm run intl-extract --workspace=indigenousapprenticeship`
5. Extract talentsearch `npm run intl-extract --workspace=talentsearch`
6. Check admin `npm run …
> Remove strings from fr.json not in en.json

- frontend/common/src/components/ClientProvider/ClientProvider.tsx
This removed the comment about removing the `console.error(err)` from our client provider. Decision was made to keep the log. Also, removed the unused toast line.
1. Make sure the comment has been removed 😄 
Resolves #4646
> Debt - 4646 - Remove error log to do comment

- frontend/common/src/components/Pending/Loading.tsx
This removes the `z-index` when the loading spinner is rendered inline. As well, it prefers hydrogen styling over inline styles.
2. Navigate to the users table, while loading table open the filter or column dialog
3. Confirm the inline loading spinner in table does not render over top of the dialog
4. Confirm spinner styles remain consistent (no changes from `main`)
Resolves #4856
> Bug - 4856 - Fix spinner z-index

- frontend/common/src/helpers/util.ts
- frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx
This returns 404 if there is an error loading the pool on the `/browse/pools/{poolId}` page.
> **Note**
> This may be too generic since it happens on any error, thoughts?
> **Note**
> This may be an issue on other pages also. We should maybe sweep through the pages and make sure we throw errors when necessary.
2. Navigtate to `/browse/pools/anything-but-a-vaild-id`
3. Confirm you see the 404 page
Resolves #4820
> Bug - 4820 - Throw 404 on pool advertisement page error

- frontend/admin/src/js/components/pool/EditPool/ExtendDialog.tsx
This uses `formState.isSubmitting` to disable the save button and update its text to indicate to users the form is in the process of saving. It also removes the `useMemo` from the footer which cause preventing the button from reliably updating.
2. Navigate to a published pool edit page
3. Open the Extend date dialog and submit the form
4. Ensure the button is disabled and reads "Saving..."
5. Ensure it returns to normal state and dialog closes
Resolves #4905
> Bug - 4905 - Indicate saving state, extend dialog

- docker-compose.yml
1. Stop all docker containers
2. Restart machine
3. Verify docker containers are all started automatically
> Add `restart: always` to webserver

- frontend/admin/src/js/components/pool/EditPool/EditPool.test.tsx
This updates the query for the "Extend the date" button query to avoid colliding with fakers generated data causing a false negative.
1. Run `npm run test --workspace=admin -- EditPool` a few times
2. Make sure it consistently passses
3. Repeat in github actions
Resolves #4967
> Bug - 4967 - Improve edit pool extend query

- api/composer.json
- api/composer.lock
- api/config/database.php
- api/schema-directives.graphql
- api/tests/Feature/PoolApplicationTest.php
closes #4540 
upgrades Laravel to 9.X
somehow error messages in some tests got more useful 🤷 
testing
not entirely sure, at the minimum
refresh API -> navigate site to make sure it all works
you must clear cache to account for dependency changes or else you'll run into errors
go to `api/bootstrap/cache` and delete `packages.php` and `services.php`
then run refresh commands or whatever
> dependencies/4540-laravel-9 

- frontend/admin/.env.example
- frontend/admin/public/config.ejs
- frontend/common/src/helpers/runtimeVariable.ts
- frontend/common/src/hooks/useFeatureFlags.ts
- frontend/indigenousapprenticeship/public/config.ejs
- frontend/talentsearch/.env.example
- frontend/talentsearch/public/config.ejs
- frontend/talentsearch/src/js/components/profile/ProfilePage/ProfilePage.tsx
This adds the `FEATURE_ONGOING_RECRUITMENTS` to `admin` and `talentsearch` and sets it to `true`.
1. Copy the `FEATURE_ONGOING_RECRUITMENTS=true` from `.env.example` into your `.env` file for `admin` and `talentsearch`
2. Rebuild the `webserver` docker image
- `docker-compose stop webserver`
- `docker-compose rm webserver`
- `docker-compose up --detach --build`
4. Refresh the frontend (easer to do all)
- `docker-compose run --rm maintenance bash refresh_all.sh`
5. Navigate to `/`
6. Open the javascript console to log `window.__SERVER_CONFIG__` to confirm new flag is in the map and true
7. Navigate to `/admin
8. Repeat step 6
> **Note**
> You can also temporarily `console.log` results of either `getRuntimeVariable("FEATURE_ONGOING_RECRUITMENTS")` or `useFeatureFlags` to confirm.
Add the …
> Feature - 4979 - Add Ongoing Recruitments Feature Flag

- frontend/talentsearch/webpack.base.js
Resolves #4453.
1. Change TALENTSEARCH_RECRUITMENT_EMAIL in `frontend/talentsearch/.env` to **hola@mundo.tld**
3. Navigate to **/en/search**
4. Set enough filters so that there are 0 matching candidates
5. Confirm **Get in touch!** links to **hola@mundo.tld**
> Add TALENTSEARCH_RECRUITMENT_EMAIL to webpack

- frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/AwardAccordion.tsx
- frontend/common/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
- frontend/common/src/lang/fr.json
Resolves #4790.
1. Compile common `npm run intl-compile --workspace=common`
3. Navigate to `/en/users/{profileId}/profile/experiences`
4. Verify there is no extra space before the colon in **Awarded to** and **Scope** in an _Award_ accordion
> Copy - Remove space before colon in English

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
Resolves #4984 
Deprecates uses of cmo assets in the api schema. No real testing - simply look through the file for anything I may have missed.
> Deprecate uses of cmo assets in api schema

- frontend/common/src/lang/fr.json
Resolves #4789.
1. Compile common `npm run intl-compile --workspace=common`
3. Navigate to `/fr/users/{profileId}/profile/experiences`
4. Verify there is a space before the colon in **Décerné à** and **Portée** in an _Prix_ accordion
5. Navigate to `/fr/users/{profileId}/profile#about-section`
6. Verify there is a space before the colon in **Statut de citoyenneté** in the section _À propos de moi_
> Copy - Add missing space before colon in French strings

- frontend/cypress/e2e/talentsearch/support-page.cy.js
- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
Resolves #5037.
1. Reload nginx `docker-compose exec webserver nginx -s reload`
2. Send a POST request to `/api/support/tickets` and verify the status code is not **404**
> Bug - Add `/api/support/tickets` endpoint to webserver

- frontend/common/src/components/SkillPicker/SkillPicker.tsx
- frontend/common/src/components/form/Checkbox/Checkbox.tsx
- frontend/common/src/components/form/Checklist/Checklist.tsx
- frontend/common/src/components/form/Input/Input.tsx
- frontend/common/src/components/form/MultiSelect/MultiSelect.tsx
- frontend/common/src/components/form/RadioGroup/RadioGroup.tsx
- frontend/common/src/components/form/Select/Select.tsx
- frontend/common/src/components/form/Select/SelectFieldV2.tsx
- frontend/common/src/components/form/TextArea/TextArea.tsx
- frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
- frontend/common/src/components/inputPartials/InputUnsaved/InputUnsaved.tsx
- frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.stories.tsx
- frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
- frontend/common/src/lang/fr.json
- frontend/common/src/messages/commonMessages.ts
- frontend/common/src/styles/formStyles.ts
This removes the background colour for inputs with unsaved changes as well as moving the message below the input.
2. Modify form fields in the profile forms
3. Confirm different field types:
1. Have no background colour
2. Have unsaved changes message below input
Resolves #5027
> Bug - 4831 - Fix unsaved changes styles

- frontend/admin/src/js/components/user/GeneralInformationTab/AddToPoolDialog.tsx
Resolves #5049 
Display Published _and_ Expired pools in the AddToPool dialog.
Note that we don't have a way of Archiving pools yet, but when we do, archived pools will NOT appear here.
Testing steps:
1. Log in as an admin.
2. Visit http://localhost:8000/en/admin/pools, and note the name of one Draft pool, one Published pool, and one Expired pool. (If any of these do not exist, you may need to run seeders or create them.)
3. Visit http://localhost:8000/en/admin/users
4. Click View on any user
5. On the User page, click "Add user to Pool"
6. In the dialog, confirm that the Draft pool does not appear
7. In the dialog, confirm that the Published pool appears and you can add the user to it
8. In the dialog, confirm the Expired pool appears and you can add the user to it
> Allow admins to add users to published AND expired pools

- frontend/common/src/components/form/BasicForm.tsx
- frontend/common/src/components/form/UnsavedChanges.tsx
This updated the `<BasicForm />` to only show the `<UnsavedChanges />` alert on the initial render if it has unsaved changes by using internal `useState`. It also allows users to dismiss the alert if they wish.
2. Navigate to a form on the profile
3. Make some changes to the form
4. Confirm the alert at the top of the form does not appear
5. Refresh the page
6. Confirm the alert appears and can be dismissed
7. Dismiss the alert and make more changes
8. Confirm the alert does not reappear
Resolves #4980
> Bug - 4980 - Prevent unsaved changes while editing

- frontend/common/src/components/MissingSkills/MissingSkills.test.tsx
- frontend/common/src/components/MissingSkills/MissingSkills.tsx
- frontend/common/src/helpers/skillUtils.ts
- frontend/common/src/lang/fr.json
This updated missing skills to differentiate between skills that are entirely missing from a profile and those that are only missing details.
> **Note**
> Part of the acceptance criteria was to prevent submission when missing details. However, this was fixed with #4957 but has yet to be deployed so that is not included in this PR.
2. Create or navigate to an existing application
3. Check missing skills
4. Add a missing skill **_from your profile, not the application page_** (we want one that is added but had no details)
5. Refresh the application reivew page
6. Confirm the new skill appears under the label "These required skills are missing information:"
Resolves #5031
> Bug - 5031 - Require skill details application

- frontend/common/src/components/UserProfile/ExperienceAccordion/ExperienceAccordion.tsx
- frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/AwardAccordion.tsx
- frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/CommunityAccordion.tsx
- frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/EducationAccordion.tsx
- frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/PersonalAccordion.tsx
- frontend/common/src/components/UserProfile/ExperienceAccordion/individualExperienceAccordions/WorkAccordion.tsx
- frontend/common/src/components/UserProfile/ExperienceByTypeListing.tsx
- frontend/common/src/components/UserProfile/ExperienceSection.tsx
- frontend/common/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
- frontend/talentsearch/src/js/components/experienceAndSkills/ExperienceAndSkills.tsx
This reduced the heading rank for experience and skill accordions to `<h3 />` to provide [semantic structure.](https://webaim.org/techniques/semanticstructure/).
1. Build all projects `npm run production --workspaces`
3. View a user and open the "Candidate Profile" tab
4. Run axe dev tools and confirm there are no heading rank warnings
5. Open the "By Skills" tab and repeat step 6
6. Navigate to `/talent/profile`
7. Repeat steps 4 + 5
Resolves #5008
> a11y - 5008 - Adjust Experience Skill Accordion Heading Ranks

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- frontend/admin/src/js/components/Table/Table.tsx
- frontend/admin/src/js/components/pool/PoolTable.tsx
- frontend/admin/src/js/components/pool/poolOperations.graphql
- frontend/admin/src/js/lang/fr.json
Resolves #5112.
1. Re-generate lighthouse schema `php artisan lighthouse:print-schema --write`
2. Generate code from your GraphQL schema and GraphQL operations `npm run codegen --workspace=admin`
3. Compile French `npm run intl-compile --workspace=admin`
4. Build admin `npm run production --workspace=admin`
5. Navigate to `/admin/pools`
6. Verify **Created** column is hidden
7. Click columns button and toggle **Created**
8. Verify table is ordered by **Created** in descending order (newest dates at the top)
9. Toggle to French
10. Verify translation for **Created** is **Créé** and date format is correct in French.
> Feature - Add `Created` column to Admin pools table

- frontend/common/src/components/TableOfContents/Navigation.tsx
- frontend/common/src/components/TableOfContents/Sidebar.tsx
Updates the title of the `<TableOfContents.Navigaton />` an `<h2 />`.
> **Note** 
> This also makes the `<Sidebar />` an `<aside />` to be semantically correct.
>
> This could also lead to false negatives on automated scans since it is [considered an exception for heading ranks](https://www.w3.org/WAI/tutorials/page-structure/headings/#exception-for-fixed-page-sections). 
1. Build all projects `npm run production --workspaces`
2. Navigate to any page that uses the `<TableOfContents />` component
3. Confirm the "On this page" text in the sidebar is wrapped in an `<h2 />`
4. Confirm the sidebar is wrapped in `<aside />`
Resolves #4997
> a11y - 4997 - Make TOC Nav Title a Heading

- .github/workflows/bundlewatch.yml
- .github/workflows/check-lighthouse-schema.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/jest.yml
- .github/workflows/lint.yml
- .github/workflows/phpunit.yml
- .github/workflows/storybook.yml
Resolves #4102.
The **ubuntu-latest** and **ubuntu-22.04** [labels](https://github.com/actions/runner-images#available-images) currently represent the same image:
1. Verify there are no instance of **ubuntu-latest** in the codebase.
> Feature - Change ubuntu-latest to ubuntu-22.04

- frontend/admin/src/js/components/user/GeneralInformationTab/ChangeStatusDialog.tsx
This PR fixes the `ChangeStatusDialog` status field labels to show correct values for i18n.
1. Navigate to /en/admin/users/:id
2. Click on **Change status** link
3. Verify **Pool status** field options are human readable
4. Navigate to /fr/admin/users/:id
5. Click on **Modifier le statut** link
6. Verify **Statut du bassin** field options are human readable and in French
Resolves #5163.
> Bug - 5163 - Fix status field option labels

- frontend/cypress/e2e/admin/pool-candidate.cy.js
closes #5165 
resolves an issue with the e2e workflow failing
the workflow would fail sometimes on `pool-candidates.cy`, this was due to there sometimes not being a candidate for "view application" to work on
solution was to always select candidates for Digital Careers, given it has the most candidates seeded, it should almost always have someone to "view application" on
in the long run it is another test to revisit, but for now this should suffice
and make reviewing doable again!!!
testing:
re-run e2e a few times to see if it is all good
> testing/pool-candidate-workflow-issue TEST FIX

- api/tests/Unit/OpenIdBearerTokenTest.php
- api/tests/Unit/resources/README.md
- api/tests/Unit/resources/jwks.json
This branch updates the modulus values advertised in the mock jwks file.  It seems that this value should be base64url encoded and our new library is more strict about this.
Testing: 
- disabled tests are enabled
- PHPunit tests reliably pass
> Fix token tests

- frontend/admin/src/js/lang/fr.json
🤖 Resolves #5179.
This PR solves an accessibility and language issue with how **Department #** is translated in French.
1. Compile French `npm run intl-compile --workspace=admin`
2. Build admin `npm run production --workspace=admin`
3. Turn on screen reader
4. Navigate to `/fr/admin/settings/departments`
5. Verify table has a **Numéro de ministère** column
6. Navigate to `/fr/admin/settings/departments`
7. Verify form has a field with **Numéro de ministère** as a label
> Bug - 5179 - Update Department # copy in French

- frontend/talentsearch/src/js/components/Browse/BrowsePoolsPage.tsx
- frontend/talentsearch/src/js/components/search/SearchPage.tsx
- frontend/talentsearch/src/js/lang/fr.json
🤖 Resolves #5213.
This PR fixes a typo in French, fixes a typo in English in a string description, and makes a string description more descriptive.
1. `npm run intl-compile --workspace=talentsearch`
2. `npm run production --workspace=talentsearch`
3. Navigate to `/browse/pools`
4. Verify page title is _Browse opportunities_ in English and _Parcourez les opportunités_ in French
5. Navigate to `/search`
6. Verify page title is _Search pools_ in English and _Rechercher les bassins de talents_ in French
> Bug - 5213 - Fix French typo, English descriptions

- frontend/common/src/components/UserProfile/ProfileSections/GovernmentInformationSection.tsx
- frontend/common/src/lang/fr.json
🤖 Resolves #5178.
This PR fixes an incorrectly translated string in French and updates a string description to be more descriptive.
1. `npm run intl-compile --workspace=common`
2. `npm run production --workspace=talentsearch`
3. `npm run production --workspace=admin`
4. Navigate to `/users/:id#government-section`
5. Verify department field label is **Department:** in English and **Ministère :** in French
6. Navigate to `/admin/users/:id#government-section` in the Candidate Profile tab
7. Verify department field label is **Department:** in English and **Ministère :** in French
> Bug - 5178 - Fix French string, descriptions

- frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.tsx
- frontend/admin/src/js/components/user/UserTable.tsx
- frontend/common/src/components/UserProfile/ProfileSections/AboutSection.tsx
🤖 Resolves #3316.
This PR adds an aria-label for phone numbers with space after each character for screen readers so that phone numbers are not read out as single long numbers.
2. Visit `/admin/users` and show the Telephone column
3. Visit `/users/:id/profile` and scroll to About me section and Phone
4. Verify with a screen reader that phone numbers are read out as expected
> Bug - 3316 - Add `tel:` link and `aria-label` to phone numbers

- frontend/admin/src/js/components/searchRequest/UpdateSearchRequest.tsx
🤖 Resolves #4814
This fixes an issue where the notes fields was not being cleaned after submission.
Since the request form is not a traditional form we are relying on a function to save notes rather than the submit action. This resets the field to the data it currently has as a way of cleaning it.
1. Build admin `npm run production --admin`
2. Navigate to `/admin/talent-requests`
3. View a request
4. Edit the notes field, noting that it marks it as unsaved
5. Click the Save Notes button
6. Confirm the unsaved message disappears once the data has been saved
> Bug - 4814 - Reset notes field on submission

- frontend/talentsearch/src/js/components/experienceForm/ExperienceForm.test.tsx
This branch further bumps the timeout on a set of slow Jest tests.  When one of these tests times out it results in a series of "Axe is already running" errors in the Jest logs.
Eventually we'll improve these tests in issue #4755 but for now this will help the CI continue to run reliably.
> Bump Jest test timeout

- frontend/common/src/components/UserProfile/accordionUtils.tsx
🤖 Resolves #4860 
This changes the skill accordions to present months with their full name rather than abbreviations.
The month name abbreviations do not match the guidelines for Canadian month abbreviations and are less helpful than presenting the full month name. For this reason, we are no longer using abbreviations for month names.
2. Navigate to the user profile `/talent/profile`
3. Scroll to the accordions in the "My skills and experience" section
4. Confirm the months are the full name in both French and English
> a11y - 4860 - Use full month name for skill accordions

- .github/workflows/storybook.yml
- frontend/admin/package.json
🤖 Resolves #3696.
This PR removes a hardcoded project token and replaces it with a dynamic and secret variable to avoid potential malicious use.
In order to see the Chromatic project token and associated GitHub secret, the reviewer must be an owner of the Chromatic account and the GitHub repository respectively.
1. Verify old chromatic project token does not work locally `npx chromatic --project-token=87148152bdff --auto-accept-changes`
2. Verify Chromatic GitHub workflow runs successfully on this PR
3. Verify Chromatic GitHub workflow logs do not expose project token
> Feature - 3696 - Make Chromatic project token into variable

- frontend/admin/src/js/components/poolCandidate/poolCandidatesOperations.graphql
- frontend/admin/src/js/components/user/GeneralInformationTab/ChangeStatusDialog.tsx
- frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.tsx
- frontend/admin/src/js/lang/fr.json
🤖 Resolves #5132 
This branch adds the ability to change the pool candidate status for multiple pool candidates at the same time.  It's closely related to PR #5256.
1. Log into the admin site
2. Find a user, preferably with several pool candidates
3. Click the __change status__ link beside one of pools and change the status of that pool candidate
4. Click the __change status__ link beside one of pools and change the status of multiple pool candidates together
5. If you inject a junk pool in the code you can trigger an error
> Batch change status for pool candidates

- frontend/admin/webpack.base.js
- frontend/talentsearch/webpack.base.js
🤖 Resolves #5261 
This fixes the watch commands infinite loop issue.
We updated how hydrogen is built but the old webpack configs need to keep the regen in it until they have been merged into apps/web. This tells them to ignore that file in watch mode so it does not re-trigger a built and enter an infinte loop.
1. Run `npm run watch -- --filter=talentsearch`
2. Wait for it to complete
3. Edit a filter in `frontend/talentsearch`
4. Confirm it rebuilds **once**
5. Repeat steps 1-4 but in `admin`
> Bug - 5261 - Fix watch command

- frontend/admin/src/js/components/pool/EditPool/AssetSkillsSection.tsx
- frontend/admin/src/js/components/pool/EditPool/EssentialSkillsSection.tsx
- frontend/common/src/components/SkillPicker/SkillPicker.tsx
🤖 Resolves #5310.
This PR solves some invalid HTML markup that is also related to a11y for duplicate id and duplicate labels on HTML elements.
The `SkillPicker` component was not designed to have multiple instances on the same page. `SkillPickerProps` now has an optional prop called `skillType` that allows for uniqueness when there are two SkillPickers on a single page (unless there are two skill pickers on the same page that have the same `skillType` value, but this would be a very peculiar implementation).
1. Navigate to `/admin/pools/create`
2. Create a new pool
3. Run axe devtools browser extension
4. Observe no duplicate id and label errors
5. Make sure that the **query** input in both Skill …
> Bug - 5310 - Admin Edit Pool page duplicate id, label

- frontend/admin/src/js/components/classification/ClassificationTable.tsx
- frontend/admin/src/js/stories/Classification.stories.tsx
🤖 Resolves #5319
Fixes the `ClassificationTable` crashing.
Removes unnecessary edit url path prop that was causing infinite re-renders.
2. Navigate to `/admin/settings/classifications`
3. Confirm the page loads properly and no update depth error in console
> Bug - 5319 - Fix Classification Table

- frontend/common/src/components/SkillPicker/SkillPicker.tsx
🤖 Resolves #5372.
This PR fixes the `SkillPicker` component for the case where the `skillType` prop is empty.
1. Navigate to /search scroll to **Skills selection** heading
2. Tab through to **Skip list of skills** link
3. Verify that the link skips the list of skills and focuses on the **Selected skills** heading
> Bug - 5372 - Fixes `SkillPicker` component id

- apps/e2e/cypress/e2e/talentsearch/create-account.cy.js
- frontend/talentsearch/src/js/components/createAccount/CreateAccountPage.tsx
- frontend/talentsearch/src/js/components/createAccount/createAccountOperations.graphql
🤖 Resolves #5286 
This branch corrects the the behavior of the create-account redirect and page.
Previously, if you logged in as a new user you would be taken to the Create Account page as usual.  However, once you submitted the form you would be taken back the Create Account page a second time.  It seems like the React Router `navigate` command after submitting the form was running synchronously and the redirect decision was being made before the authorization context provider had a chance to update it's own state with the new details.  I've moved the navigate command out of the mutation promise and into a useEffect that runs after rendering.
1. Log in as a new user, fill out the create account form, observe that you are forwarded to your profile page
2. Log in as an existing user, …
> Fix create account 

- frontend/admin/src/js/components/poolCandidate/PoolCandidatesTable.tsx
🤖 Resolves #5409.
This PR fixes a `aria-labelledby` value that was broken since the element it referenced did not exist due to being named incorrectly.
1. Navigate to `/admin/pools/:poolId/pool-candidates`
2. Inspect elements of page
3. Verify table `aria-labelledby` is **pool-candidate-table-heading**
> Bug - 5409 - Fixes header id value to match aria-labelledby value

- apps/web/src/lang/fr.json
- apps/web/src/pages/ExperienceAndSkillsPage/ExperienceAndSkills.tsx
- frontend/common/src/lang/fr.json
🤖 Resolves #5426.
This PR updates French copy for **Community** so that it is more consistent with related French copy for similar words related to **Experiences** types. Related to #5419.
1. Compile French `npm run intl-compile`
2. Build talentsearch `npm run dev`
3. Navigate to `/fr/users/:id/profile/experiences`
4. Verify button is **Communautaire**
5. Verify experience buttons layout has buttons with the same height (thanks @substrae!)
6. Navigate to `/fr/users/:id/profile/experiences`
7. Click on **Par type** to list by type
8. Verify heading is **Expériences communautaires**
> Copy - 5426 - Updates experience type community in French

- api/tests/Feature/ApplicantFilterTest.php
- api/tests/Feature/ApplicantTest.php
- api/tests/Feature/CountPoolCandidatesByPoolTest.php
- api/tests/Feature/PoolApplicationTest.php
- api/tests/Feature/PoolCandidateSearchRequestTest.php
- api/tests/Feature/PoolCandidateSearchTest.php
- api/tests/Feature/PoolCandidateTest.php
- api/tests/Feature/PoolTest.php
- api/tests/Feature/UserTest.php
🤖 Resolves #5283.
This PR replaces the deprecated Lighthouse PHP trait `ClearsSchemaCache` with `RefreshesSchemaCache`.
1. Run PHPUnit `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "vendor/bin/phpunit --verbose"`
2. Verify tests run normally
> Tests - 5283 - Replaces `ClearsSchemaCache` with `RefreshesSchemaCache`

- frontend/admin/src/js/components/poolCandidate/PoolCandidatesTable.tsx
- frontend/admin/src/js/components/searchRequest/SingleSearchRequestTable.tsx
🤖 Resolves #5428 
This fixes the default filters being populated on the `PoolCandidatesTable` component.
We were only populating pools previously, this simply adjusts it to use all filters.
While fixing this bug, I was able to determine that classifications are not being passed to the request mutation and stored. They appear under "Request Information" because they are coming from the `Pool` rather than the `SearchRequest`.
Is this a bug? Or expected behaviour? If so, should the filter for classifications follow suit and be populated from the pool or should it come from the request when searching?
https://github.com/GCTC-NTGC/gc-digital-talent/blob/e4bc365ba09e14f325c4fe65d469c984396155f5/frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L131-L147
> **Note**
> …
> Bug - 5428 - Fix Search Request Pool Candidates Default Filters

- api/tests/Feature/NotifyTest.php
🤖 Resolves #5470 
This skips the `NotifyTest` is an API key is not present. As well, it moves it to the feature namespace since it is an integration test.
1. If you have GCNOTIFY_API_KEY set, comment it out
2. Run PHP unit
3. Confirm the tests skip
4. Add in an API key
5. Run PHP unit
6. Confirm the tests pass
> Bug - 5470 - Fix GC Notify Test

- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- frontend/common/package.json
There were some missing translations.  Probably they were lost in #5344.  This adds them back in.  It also fixes a small script problem.  We didn't notice since there was a problem with the translation CI as well (#5474).
1. Manually run a translations check for `web`
2. No translations missing
> Bugfix missing translations from 5344

- .github/workflows/translations.yml
- frontend/common/package.json
🤖 Resolves #5473
This fixes a type in the `untranslated.json` file name causing the test to always pass.
@petertgiles is working on re-adding the translations after they were lost during the merge. Once this is approved and his is merged, we can merge this one.
1. Confirm the translations action failed
> Bug - 5473 - Fix translation workflow

- .vscode/hydrogen.code-snippets
- apps/web/package.json
- apps/web/src/pages/SearchPage/EstimatedCandidates.tsx
- frontend/admin/package.json
- frontend/common/package.json
- frontend/common/src/components/Accordion/Accordion.tsx
- frontend/common/src/components/Alert/Alert.tsx
- frontend/common/src/components/Button/Button.tsx
- frontend/common/src/components/CardLink/CardLink.tsx
- frontend/common/src/components/ScrollArea/ScrollArea.tsx
- frontend/common/src/components/Switch/Switch.tsx
- frontend/common/src/components/Tabs/Tabs.tsx
- frontend/common/src/components/TileLink/TileLink.tsx
- frontend/common/src/components/Toast/Toast.tsx
- package-lock.json
- package.json
Updates Hydrogen with a handful of bugfixes and a pinch of love.
The biggest change here is twofold:
- `data-h2-transition` takes standard CSS syntax now instead of the original comma separated values - this was because commas are used in native CSS transition to allow for transitioning multiple properties by comma separating a list
- No one has probably used this yet, but you used to be forced to use the opposite color modifier in dark mode if automated modifiers were enabled - this was because dark mode was swapping the value of the CSS variable, so in dark mode, the `lighter` variable was being swapped to `darker` automatically for you, but this also meant that using `:dark(lighter)` would spit out the darker color... which is not intuitive, so now, `:dark(lighter)` spits out the …
> Hydrogen 2.0.0-beta.39

- apps/web/src/lang/fr.json
- apps/web/src/pages/BrowsePoolsPage/PoolCard/PoolCard.tsx
🤖 Resolves #5358 
It was discovered that hidden text can interfere with Voice Control on iPhone.  It was decided to remove the hidden text as an interim solution.
This branch takes the classification out of hidden text and concatenates to the end in parenthesis.
> **Warning**
> This can be a bit tricky to set up!
1. Enable and turn on Voice Control on your TBS iPhone.  https://support.apple.com/en-ca/guide/iphone/iph2c21a3c88/ios
2. Figure out the IP address of your workstation on your local network (like 192.168.x.x)
3. Connect your TBS iPhone to your local network and browse to the site (like http://192.168.x.x:8000) in Safari
- You might have to adjust some .env setting from _localhost_ to _192.168.x.x_ to make this work
- You may want to try this from a second computer if you run into …
> Remove hidden text from Apply button

- api/graphql/schema.graphql
- frontend/admin/src/js/components/Table/Table.tsx
- frontend/admin/src/js/components/apiManagedTable/TableFooter.tsx
🤖 Resolves #5366.
This PR changes the pagination options for items per page from `10, 20, 30, 40, 50` to `10, 20, 50, 100, 500`.
Technically speaking, a user can already control the items per page via a url query parameter (ex. `/admin/users?pageSize=1000`) though there is a limit on two of the queries:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/aa89339bf525d760050427d7da7057ffe03798c6/api/graphql/schema.graphql#L812
https://github.com/GCTC-NTGC/gc-digital-talent/blob/aa89339bf525d760050427d7da7057ffe03798c6/api/graphql/schema.graphql#L866
1. Navigate to `/admin/pools`
2. Interact with the pagination select element in the table footer
3. Ensure it functions as expected
4. Navigate to `/admin/users`
5. Interact with the pagination select element in the table footer
6. Ensure it …
> Feature - 5366 - Changes pagination `pageSizes` options

- frontend/common/src/components/Link/ScrollToLink.tsx
🤖 Resolves #5468 
Fixes the browser history for table of contents links.
We were using `window.history.pushState()` which adds to the history stack but breaks with `react-router` for navigation. This replaces that with `useNavigate` to do the same thing with `react-router`
2. Navigate to the user profile
3. Click on a table of contents links
4. Go to any other page
5. Hit the browser back button
6. Confirm it actually navigates you
Add a screenshot (if possible).
> Bug - 5468 - Fix TOC  Links

- api/tests/Feature/NotifyTest.php
🤖 Resolves #5525 
Updates the `NotifyTest` namespace to comply with PSR-4.
We moved the `NotifyTest` to the feature namespace but never changed the defined namespace. This updates it to comply with PSR-4.
1. Run `PHPUnit`
2. Confirm the warning is gone and `NotifyTest` runs
> Bug - 5525 - Fix `NotifyTest` namepsace

- apps/web/src/components/SkillsInDetail/SkillsInDetail.stories.tsx
🤖 Resolves #5543.
This PR adds a missing `id` prop for `SkillsInDetail` stories.
2. Verify no error is present in console for **Few Skills** and **Many Skills** **SkillsInDetail** stories
> Bug - 5543 - Fixes `SkillsInDetail` stories

- frontend/common/src/lang/fr.json
🤖 Resolves #5544.
Fixes a variable that was mistakenly translated into French in **Title at organization**.
1. `npm run intl-compile`
2. `npm run storybook`
3. Open **Accordion Community Example** story in FR locale
4. Verify no console errors related to i18n
5. Verify no EN text in title
> Bug - 5544 - Fixes FR for Title at organization

- apps/web/src/pages/MyApplicationsPage/ApplicationCard/ApplicationCard.stories.tsx
🤖 Resolves #5542.
This PR fixes the `key` prop for the `Application Cards` story to be unique.
Is there a reason all the card variations are in one story instead of making a story for each one?
2. Verify no error is present in console for **Application Cards** story
> Bug - 5542 - Fixes `Application Cards` story

- frontend/common/src/components/Accordion/Accordion.docs.mdx
- frontend/common/src/components/Accordion/Accordion.stories.tsx
- frontend/common/src/components/Accordion/Accordion.tsx
- frontend/common/src/components/Accordion/styles.ts
- hydrogen.config.json
🤖 Resolves #5042
This updates the accordions to allow choosing a mode (simple, card) to use.
~~There are some issues with nesting the accordions right now. The issue is, the nested accordions are inheriting the styles from the root accordion so when we nest the card styles, we cannot use simple accordions inside. This may be my lack of experience with hydrogen.~~
~~I'm not sure how often we nest accordion and the priority of getting this working, do we have the time for me to get some assistance form @substrae on this? Or, do we want to break out the nested accordion styles into a new issue and sort that out at a later time once they have been completed?~~
> **Warning**
> For the card style, there is …
> Feature -  5042 - Themed Accordions

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
🤖 Resolves #5533.
This PR removes the **Preferred Spoken Interview Language** and **Preferred Written Exam Language** columns and hides the **Preferred Communication Language** column by default in the User and Pool Candidate tables.
2. Navigate to User table `/admin/users`
3. Verify columns match acceptance criteria in #5533
4. Navigate to Pool Candidate table `/admin/pools/:poolId/pool-candidates`
5. Verify columns match acceptance criteria in #5533
> Bug - 5533 - Updates User and Pool Candidate table columns

- apps/web/.storybook/preview.js
- frontend/common/.storybook/preview.js
🤖 Resolves #5550.
This PR adds the missing `MINIMAL_VIEWPORTS` for storybook that references one of its attributes, `mobile1` in a **Checkbox** story.
2. Open browser console
3. Visit **Long Text Checkbox** story
4. Verify story has viewport set to _Small Mobile_
5. Verify no console warnings
- This PR is a stopgap for properly dealing with viewports, see: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5589.
- Working on this surfaced: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5590
> Bug - 5550 - Adds missing `MINIMAL_VIEWPORTS`

- apps/web/src/pages/Home/IAPHomePage/Home.stories.tsx
🤖 Resolves #5552.
h/t @patcon for [storybook docs](https://storybook.js.org/docs/react/essentials/backgrounds).
This PR fixes a missing background value for `Home Page/IAP` story in storybook.
2. Open browser console
3. View **Home Page/IAP** story
4. Verify **Home Page/IAP** story has white background
5. Verify no console errors related to missing background value
> Bug - 5552 - Adds white background value for `Home Page/IAP` story

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/AdvancedFilters.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/FilterBlock.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- frontend/common/src/components/Accordion/Accordion.tsx
- frontend/common/src/components/Accordion/styles.ts
🤖 Resolves #5457 
This moves some filters on the search page into accordions.
I had to darken the subtitle for the accordions slightly for accessibility.
REF: https://webaim.org/resources/contrastchecker/?fcolor=1A9A8B&bcolor=F5F5F5
1. Build the project `npm run build`
3. Confirm the advanced filters exist at the bottom in accordions
4. Confirm the form still functions as expected
> Feature -  5457 - Add Advanced Filter Accordions to Search Page

- apps/web/src/pages/Profile/AboutMePage/components/AboutMeForm/AboutMeForm.tsx
- apps/web/src/pages/Profile/EmploymentEquityPage/components/EmploymentEquityForm/EmploymentEquityForm.tsx
- apps/web/src/pages/Profile/ExperienceAndSkillsPage/components/ExperienceAndSkills.tsx
- apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.tsx
- apps/web/src/pages/Profile/LanguageInfoPage/components/LanguageInformationForm/LanguageInformationForm.tsx
- apps/web/src/pages/Profile/RoleSalaryPage/components/RoleSalaryForm/RoleSalaryForm.tsx
- apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx
- apps/web/src/pages/Profile/WorkPreferencesPage/components/WorkPreferencesForm/WorkPreferencesForm.tsx
🤖 Resolves #5541.
This PR fixes breadcrumbs for profile forms so that they link correctly in an Application context.
Also, `returnRoute` was standardized to use **applicationId** from `searchParams` instead of from a prop as it had been in some cases.
Test all segments of the breadcrumbs, specifically the following ones.
1. Start an application
2. Click **Edit _Section Name_**  
3. Click on the last breadcrumb in the list
4. Verify the page is the same and the breadcrumbs are in an application context
5. Click on the **Step 1** breadcrumb in the list
6. Verify the page returns to the **My application profile** page
7. Repeat for all sections
1. Click **My Profile**
2. Click **Edit _Section Name_**  
3. Click on the last breadcrumb in the list
4. Verify the page is the same and the …
> Bug - 5541 - Fixes breadcrumbs in Application context

- .vscode/project-words.txt
- api/app/Models/Permission.php
- api/app/Models/Role.php
- api/app/Models/Team.php
- api/app/Models/User.php
- api/app/Providers/AppServiceProvider.php
- api/config/laratrust.php
- api/config/rolepermission.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/ProdSeeder.php
- api/database/seeders/RolePermissionSeeder.php
- api/database/seeders/UatSeeder.php
- api/tests/Feature/RolePermissionTest.php
🤖 Resolves #5436
This adds the `Role` and `Permission` seeders along with a config file for them.
I believed the [laratrust seeder](https://laratrust.santigarcor.me/docs/7.x/usage/seeder.html#seeder-configuration-file) would not work with teams enabled based on their docs so created a custom one based off of theirs.
> **Note**
> All French display names were translated by a 🤖 robot. I will be sending them off to get updated translations.
1. Run the seeder
2. Inspect the database to check for permissions and roles
> **Note**
> My SQL is pretty bad so I would appreciate if someone could assist writing some sample queries to test that the relationships were created accurately 😆
> Feature - 5436 - Seed roles permissions

- apps/web/src/pages/Pools/EditPoolPage/components/WorkTasksSection.tsx
🤖 Resolves #5621.
This PR increases the max words limit for **English - Your work** and **French - Your work** textareas from 200 to 400.
2. Navigate to **Work tasks** section of Edit Pool `/admin/pools/:poolId/edit#work-tasks`
3. Observe word counter value is 400 (when textarea is empty) below **English - Your work**, **French - Your work** textareas
> Feature - 5621 - Updates max words limit for pool your work textareas

- frontend/common/src/components/Link/ScrollToLink.tsx
🤖 Resolves #5603 
This fixes a bug where the `ScrollToLink` component only worked if the hash did not already exist in the URL.
The scroll event was happening at the same time as `react-router` was adjusting scroll position from the `ScrollRestoration` component. We have added a very short timeout to get around this.
1. Navigate to /profile
2. Click a link in the "On this Page" section
3. Scroll up
4. Click the link again
5. Confirm the page still scrolls
> Bug - 5603 - Fix Anchor Link Scrolling

- apps/web/src/pages/Applications/SignAndSubmitPage/SignAndSubmitPage.stories.tsx
- apps/web/src/pages/Applications/SignAndSubmitPage/SignAndSubmitPage.tsx
🤖 Resolves #5357 
This removed the `disabled` attr regardless of the users profile completion status.
This is to handle an extreme edge case where a user navigates to the sign and submit step of an application even when their profile is incomplete.
1. Create an application with an incomplete profile
2. Navigate directly to `/browse/applications/{applicationId}/submit`
3. Ensure the submit button is enabled
4. Attempt the submit the form
5. Ensure you get an error toast with nice messages
> a11y - 5357 - Enable Application Submit

- frontend/common/src/components/Dialog/Dialog.tsx
🤖 Resolves #5637.
This PR adds `z-index` for close button in `Dialog` for the close button to be visible.
2. Navigate to /indigenous-it-apprentice/
3. Click **Apply Now** button
4. Ensure close dialog **x** button is visible
5. Check for any other instances of where the `Dialog` component is used
6. Ensure close dialog **x** button is visible in all instances
> Bug - 5637 - Fixes `Dialog` close button not visible

- maintenance/scripts/setup.sh
🤖 Resolves #5170 
This adds a `touch` command to the setup script to ensure that the log exists for owner and permission updates
1. Run setup on a new workspace
2. Run setup on an existing workspace
3. Ensure the laravel log is universally writable
> Add touch to setup

- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #5625.
This PR removes the **Pool** column from the search request table.
2. Navigate to /admin/dashboard
3. Ensure **Pool** column is not rendered by default and is not in the list of Table columns
4. Navigate to /admin/talent-requests
5. Ensure **Pool** column is not rendered by default and is not in the list of Table columns
> Feature - 5625 - Removes search request table pool column

- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
🤖 Resolves (my own urge to rectify something that may never be an issue)
Realized after merging in PR #5631 and playing with pools table that things could be a little better. 
Stream in the accessor was using enums, therefore was not searchable in french. Which was a little sloppy of me to leave in, sorry ☹️ 
Stream in pool name is now localized from enums, therefore searchable in proper text in english AND french 
1. play with search in english and french on /pools
BEFORE
AFTER
(website is being glitchy with gif creation so this one is a link)
https://recordit.co/yyEX75AfwJ/
> pool searches stream enum

- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx
- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountRedirect.tsx
- frontend/common/src/components/Link/ScrollToLink.tsx
- frontend/common/src/components/form/ErrorSummary.tsx
🤖 Resolves #5466 
This focuses the input when the link to the input is clicked within the error summary.
> **Note**
> For radio groups, you may need to temporarily set the default value to `undefined` to properly force an error.
2. Navigate to the profile
3. Purposefully create some errors on every form input type
4. Submit the form and confirm the error summary appears
5. Click a link to the field in the error summary
6. Confirm focus is moved to the input and you can immediately interact with that input
> a11y - 5466 - Focus Input on Error Link Click

- apps/web/src/components/Table/ApiManagedTable/TableHeader.tsx
- apps/web/src/components/Table/ClientManagedTable/Table.tsx
- frontend/common/src/components/form/Checkbox/Checkbox.tsx
- frontend/common/src/components/form/Checklist/Checklist.tsx
- frontend/common/src/components/form/Input/Input.tsx
- frontend/common/src/components/form/RadioGroup/RadioGroup.tsx
- frontend/common/src/components/form/Select/Select.tsx
- frontend/common/src/components/form/Select/SelectFieldV2.tsx
- frontend/common/src/components/form/TextArea/TextArea.tsx
- frontend/common/src/components/inputPartials/Fieldset/Fieldset.tsx
- frontend/common/src/components/inputPartials/InputContext/InputContext.tsx
- frontend/common/src/components/inputPartials/InputError/InputError.tsx
- frontend/common/src/components/inputPartials/InputLabel/InputLabel.tsx
- frontend/common/src/components/inputPartials/InputWrapper/InputWrapper.tsx
- frontend/common/src/hooks/useInputDescribedBy.ts
🤖 Resolves #5423 
This fixes the input context being read out twice to JAWS.
We were using a collapsible element without the `aria-expanded` and `aria-controls` attributes which was causing the assistive technology to read out the context 2-3 times.
> **Note**
> This is technically not an alert but due to it being in an odd order in the DOM (has focusable items between the area and the control) other methods to get the text to work properly were not successful.
While this solution works, it may be better to [use the `aria-describedby` attribute to add the contextual text to the input](https://www.w3.org/TR/WCAG20-TECHS/ARIA1.html#:~:text=Example%202%3A%20Using%20aria%2Ddescribedby%20to%20associate%20instructions%20with%20form%20fields) rather than hiding it behind a button.
This will be …
> a11y - 5423 - Fix Input Context w/ Assistive Technology

- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/components/Table/ClientManagedTable/index.ts
- apps/web/src/components/Table/ClientManagedTable/types.ts
- apps/web/src/pages/Classifications/components/ClassificationTable.tsx
- apps/web/src/pages/Departments/components/DepartmentTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/SearchRequests/IndexSearchRequestPage/searchRequestOperations.graphql
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.tsx
- apps/web/src/pages/SkillFamilies/components/SkillFamilyTable.tsx
- apps/web/src/pages/Skills/components/SkillTable.tsx
- apps/web/src/pages/Teams/IndexTeamPage/components/TeamTable/TeamTable.tsx
🤖 Resolves #5600 
This updates our `ClientManagedTable` components to use the `Cell` attribute instead of `accessor` to render non-primitive values.
We were using `accessor` to render any value (even JSX). However, the docs state that we should be using `Cell` instead and [make `accessor` a primitive value](https://react-table-v7.tanstack.com/docs/api/useTable#column-options:~:text=The%20data%20returned%20by%20an%20accessor%20should%20be%20primitive%20and%20sortable.).
2. Navigate to each table
3. Confirm they still function as expected
- Search
- Sort
- Rendering values
> Bug - 5600 - Update table accessors

- frontend/common/src/components/Button/IconButton.tsx
- frontend/common/src/components/Dialog/Dialog.test.tsx
- package-lock.json
🤖 Resolves #4656 
This adds the ability to forward a ref to underlying Button component for IconButton.
This turned out to be a blocker for #4389 so I pulled it in here.  I guess the Dialog component relies on passing a ref to the trigger button so it was emitting warnings when I tried to use an IconButton as the trigger.
Read more here: https://beta.reactjs.org/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes
1. Review the new test
2. Observe that the test passes
3. Feel good that I pulled this commit into my PR for #4389 and confirmed that it fixed the problem :smile:
> Allow IconButton to accept a ref

- apps/web/src/components/Router.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Teams/CreateTeamPage/CreateTeamPage.tsx
- apps/web/src/pages/Teams/TeamMembersPage/TeamMembersPage.tsx
- apps/web/src/pages/Teams/UpdateTeamPage/UpdateTeamPage.tsx
- apps/web/src/pages/Teams/ViewTeamPage/ViewTeamPage.tsx
- apps/web/src/pages/Users/UserPlacementPage/UserPlacementPage.tsx
- apps/web/src/pages/Users/ViewUserPageV2/ViewUserPage.tsx
🤖 Resolves #5656 
Adds placeholder routes for some new admin pages.
We already have a ViewUserPage but at a different route (`/admin/users/{id}` vs `/admin/users/{id}/profile`) so the new page is referred to as ViewUserPageV2 a couple times.
Navigate to each of the following routes confirming there is a placeholder page with just a title at each of them:
- `/admin/users/{id}/profile`
- `/admin/users/{id}/placement`
- `/admin/teams/create`
- `/admin/teams/{id}`
- `/admin/teams/{id}/edit`
- `/admin/teams/{id}/members`
> New placeholder admin pages

- .github/ISSUE_TEMPLATE/✨-feature-request.md
Adds blockers tasklist to Feature issue template
This uses [Github Tasklists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists), which enable some useful relationships in Github Projects, ie the `tracks` and `tracked-by` fields.
To see how we might use it in practice, check out https://github.com/orgs/GCTC-NTGC/projects/8/views/10.
1. Paste the new feature-request.md file into a new github issue, and switch to the preview tab. See how you like it.
> Add blockers tasklist to Feature issue template

- .github/workflows/e2e-tests.yml
- apps/e2e/cypress.config.ts
- apps/e2e/cypress/e2e/admin/auth.cy.js
- apps/e2e/cypress/tsconfg.json
- apps/e2e/tsconfig.json
🤖 Resolves #5171 
This solves the `tsconfig.json` warning that shows up in the console while running cypress tests.
Turns out it was fairly simple, not sure I feel great merging this with a 13 story point estimation 😅 
1. Run `npm run e2e:run:all`
2. Confirm the warning does not appear
3. Confirm tests are still passing
> Debt - 5171 - Fix TS Cypress Warning

- apps/web/package.json
- hydrogen.config.json
- package-lock.json
- package.json
Updates Hydrogen to [`2.0.1`](https://github.com/hydrogen-css/hydrogen/pull/224)
Specifically:
- Fixes a bug with gradient configurations
- Reduces console output to three lines when `verbose` is disabled
1. Clear your node module and turbo caches
2. Run Storybook
> Updates Hydrogen, removes unsupported config syntax

- apps/web/.env.example
- apps/web/public/config.ejs
- packages/env/src/useFeatureFlags.ts
- packages/env/src/utils.ts
🤖 Resolves #5736 
This adds a `FEATURE_APPLICANT_DASHBOARD` feature flag
This just makes it available for use, defaulting to enabled, with no visible indication of it being on/off.
As recommended by team, there is no front-facing test, just inspecting PR code.
Add the `FEATURE_APPLICANT_DASHBOARD` environment variable and set it to `false`.
None.
> Added FEATURE_APPLICANT_DASHBOARD boilerplate

- api/app/Console/Commands/RoleSync.php
🤖 Resolves #5437 
This creates the `php artisan role:sync` command to assign new user roles to users.
This only assigns roles only if the user has no existing roles.
1. Run `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan role:sync"`
2. Confirm the appropriate roles are assigned.
3. Confirm `legacy_roles` are untouched
4. Re-run command a few times and confirm no errors
You can check with the following:
>**Note**
> ~~I suck at SQL, so if you know a better way let me know 😅~~
h/t @petertgiles for improving the SQL! 🎉 
```sql
SELECT
u.legacy_roles,
count(*),
string_agg(distinct r.name||coalesce('-'||t.name, ''), ', ')    
FROM users u
LEFT JOIN role_user ON role_user.user_id = …
```
> Feature - 5437 - Assign new user roles

- turbo.json
🤖 Resolves #5808.
This PR removes `check-intl` turbo cache so that running `check-intl:web` knows that the English files have changed and it does a new check.
1. Run `npm run intl-extract`
2. Run `npm run check-intl:web`
3. Make some changes to strings in the code
4. Rerun `npm run intl-extract`
5. Rerun `npm run check-intl:web`
6. Observe that the check was not cached and did notice the changes
- @petertgiles for suggesting the solution
- @esizer for finding the problem
> Bug - 5808 - Removes `check-intl` turbo cache

- apps/web/package.json
- apps/web/src/lang/whitelist.yml
- package-lock.json
Something went wrong with the dependabot upgrade of babel-plugin-formatjs upgrade (#5834) this morning and broke Jest testing.
I've backed #5834 and manually upgraded babel-plugin-formatjs upgrade.
(I accidentally named the branch and first commit 5833.  It was actually 5834 that broke.)
1. Builds OK
2. Jest tests OK
3. Github Actions OK
> Fix babel-plugin-formatjs upgrade

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/HomePage/components/Hero/Hero.tsx
🤖 Resolves #5812.
This PR removes the abbreviation from the Home Page Hero Heading.
1. Navigate to Home page `/en/`
2. Verify h1 heading (**GC Digital Talent**) does not have an underline on **GC** and does not show alt text on hover
3. Navigate to Home page `/fr/`
2. Verify h1 heading (**Talents numériques du GC**) does not have an underline on **GC** and does not show alt text on hover
> Feature - 5812 - Removes abbreviation from Home Page Hero Heading

- apps/web/webpack.base.js
🤖 Resolves #4569.
This PR limits webpack's output to errors and warnings.
2. Observe only output errors and warnings
> Tooling - 4569 - Adds preset `stats` errors-warnings

- api/app/Http/Middleware/AuditQueryMiddleware.php
- api/app/Models/User.php
🤖 Resolves #5794
Adds logging for platform admin 
In the logger removed isAdmin() check and added  hasRole('platform_admin')
- Login as admin ( currently all admins are having platform_admin role using the `syncRoles` )
- Do some admin related changes like adding and editing user 
- Check the laravel logs in local and verify the actions are still being logged
Add a screenshot (if possible).
> add logging for platform admin

- api/app/Policies/RolePolicy.php
- api/app/Policies/UserPolicy.php
- api/graphql/schema.graphql
- api/tests/Feature/UserRoleTest.php
- apps/e2e/cypress/e2e/talentsearch/create-account.cy.js
🤖 Resolves #5782
Updates the `UserPolicy` and `RolePolicy` with the new Laratrust permissions.
The `assign` permissions were added to the `UserPolicy` if the user is attempting update a user's roles using the [`injectArgs`](https://lighthouse-php.com/5/security/authorization.html#restrict-fields-through-policies:~:text=checks%20with%20the-,injectArgs,-argument%3A) option in lighthouse-php.
1. Run PHPUnit and confirm tests pass for `UserRoleTest`
2. Review the policies to confirm they match [the spreadsheet](https://docs.google.com/spreadsheets/d/1RC7wufxwjLEvaEunHsfZfOzBefg218dvvzkDwKSiQjI/edit#gid=428263758)
> Feature - 5782 - Update role policy

- maintenance/README.md
🤖 Resolves #5654.
This PR removes an outdated line from the documentation.
1. Search for `refresh_admin.sh` in codebase
3. Verify it does not appear anywhere
> Docs - 5654 - Removes `refresh_admin.sh` reference

- apps/web/src/hooks/useQuote.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/IAPHomePage/Home.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/ApplyDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/LearnDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/SelfDeclarationDialog.tsx
🤖 Resolves #5903.
This PR removes instances of `wrapAbbr` from the IAP home page and its dialogs.
1. Navigate to `/en/indigenous-it-apprentice`
2. Ensure none of text has abbreviations with underline and alt text on hover
3. Navigate to `/fr/indigenous-it-apprentice`
4. Ensure none of text has abbreviations with underline and alt text on hover
5. Ensure none of text has an English fallback
> Feature - 5903 - Removes instances of `wrapAbbr` from IAP

- api/tests/Unit/PoolCandidatePolicyTest.php
🤖 Resolves #5914 
This fixes the `testUpdate` on `PoolCandidatePolicyTest`.
There was a chance that `$this->poolCandidate` was a draft which would return `false` for the `assertTrue` on `poolOperatorUser`. This updates `$this->poolCandidate` to be submitted before testing assertions.
1. Run `php artisan test tests/Unit/PoolCandidatePolicyTest.php` 10+ times locally
2. Confirm it always passes
> [Bug] Fix `PoolCandidatePolicyTest`

- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #5905
Restores the IAP fr vanity url.
This redirect used to work, but I think it was broken when we moved to nginx.
1. Enter talent.canada.ca/apprentis-autochtone-ti in your browser
2. You should be redirected to https://talent.canada.ca/fr/indigenous-it-apprentice
3. Click the English link to go to the english page (and save your preference for english)
4. Repeat step one. You should still be sent to the french version of the page.
Add a screenshot (if possible).
> Add permanent redirect for IAP fr vanity url

- apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx
- apps/web/src/components/UserProfile/ProfileSections/WorkPreferencesSection.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/ClassificationDefinition.tsx
- apps/web/src/pages/Profile/RoleSalaryPage/components/RoleSalaryForm/RoleSalaryForm.tsx
- apps/web/src/pages/Profile/RoleSalaryPage/components/dialogs.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #5854.
This PR removes `intl.formatMessage` description instructions that should be sent as general [translation instructions](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/translation.md#requesting-translation-services).
1. Ensure all strings still appear correctly in English and French
> Debt - 5854 - Removes `intl.formatMessage` description instructions

- apps/e2e/cypress/e2e/admin/pools.cy.js
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx
- apps/web/src/pages/Pools/poolOperations.graphql
🤖 Resolves #5878 
Incorporates team selection in the pool creation process. 
Just a matter of updating queries and passing in a teams array to the form. 
Overhauled a few things too, like the unused genericJobTitles collection. 
1. play around with pool creation, try to think of edge cases
2. confirm you can create pools and they attach to teams, and your teams are appearing correctly
a query to check your teams and their associated pools
```
query getMyPools {
me {
roleAssignments {
team {
id 
name
pools {
id 
name {
en
}
}
}
}
}
}
```
> Feature - 5878 - pool creation team selection

- apps/web/src/pages/AccessibilityStatementPage/AccessibilityStatementPage.stories.tsx
- apps/web/src/pages/Errors/ErrorPage/ErrorPage.stories.tsx
- apps/web/src/pages/Home/HomePage/HomePage.stories.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.stories.tsx
- packages/storybook-helpers/decorators/ThemeDecorator.tsx
🤖 Resolves #5871 
This should stabilize the themes in chromatic.
It seemed to only be pages that defined `parameters.chromatic.viewports`  that were causing problems. I'm still not sure why they were but, adding `parameters.themeKey` instead of relying on the fallback seems to have worked from my limited testing 🤷‍♀️ 
1. Run storybook locally a few times and make sure the pages changed always show up as the expected theme
2. Check chromatic for no diff
> [Bug] Stabilize chromatic themes

- api/app/Http/Resources/EducationExperienceResource.php
🤖 Resolves #5919 
Resolve the bug with snapshotting. Just removed the field that didn't exist.
The question is, why did this not throw an issue _before_? Laravel 10 changed how some things work?
1. fill out an application with all five experience types
2. submit and ensure you see no errors
3. head to /admin and find that application, ensure the snapshot saved
> Bug - 5919 - update education resource collection 

- api/graphql/schema.graphql
🤖 Resolves #6005 
Adds the `notDraft` scope to `Query.applicant.poolCandidates`.
No one but the owner of a draft may view draft pool candidates. This was causing a problem with `Query.applicant.poolCandidates` since it was exposing draft applications. This adds the scope to filter out draft applications.
1. Login as applicant
2. Submit an application and start another on as a draft
3. Login as an admin
4. View the user information page for the applicant user
5. Confirm there are no GraphQL errors
6. Confirm you only see the submitted application
> [Bug] Fix applicant pool candidates query

- apps/web/src/components/InfoItem/BaseInfoItem.tsx
🤖 Resolves #5990 
This branch fixes a small bug where the status icon would get shrunk if the title text wrapped to a second line.
I think flex box was shrinking the icon item to try to compensate for the longer text item.  I set a min-width on the icon and that seems to have fixed it.
1. Start Storybook and navigate to the Application Dashboard / Dashboard Heading / Partially Completed Profile story.
2. Narrow the viewport until  some of the profile titles start to wrap.
3. Confirm that the icons are the same size for the wrapped and unwrapped lines.
> Fix dashboard status icon size

- apps/web/src/components/InfoItem/BaseInfoItem.tsx
- apps/web/src/components/PageHeader/PageHeader.stories.tsx
- apps/web/src/components/PageHeader/types.ts
- apps/web/src/components/PoolCandidatesTable/PoolCandidateDocument.tsx
- apps/web/src/components/Table/ClientManagedTable/Table.tsx
- apps/web/src/components/Table/ClientManagedTable/tableComponents.tsx
- apps/web/src/components/UserProfileDocument/UserProfileDocument.tsx
- apps/web/src/pages/ApplicantDashboardPage/components/HeroCardItem.tsx
- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Card.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Svg/CloseQuote.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Svg/OpenQuote.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/components/PoolCard/IconLabel.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/ClassificationDefinition.tsx
- apps/web/src/pages/Profile/EmploymentEquityPage/components/EmploymentEquityForm/EquityOption.tsx
- apps/web/src/pages/Profile/EmploymentEquityPage/components/IndigenousEquityOption.tsx
- apps/web/src/pages/Profile/ExperienceAndSkillsPage/components/AddExperienceDialog.tsx
- apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.tsx
- apps/web/src/pages/Skills/CreateSkillPage.tsx
- apps/web/src/types/pages.ts
🤖 Related to (but does not close) #5214 
This branch removes the remainder of the uses of React.FunctionComponent and React.FC from the apps/web project.  Other subsequent PRs will finish removing it from other locations.  This includes some trickier changes that may need closer inspection.
One more PR is incoming with the remainder of replacements (mostly `packages/ui`) and the linting rule.
1. App builds
2. App runs OK and looks normal
3. No more instances of FC or FunctionComponent remain in apps/web
> **Note**
> If any diffs look really big, review with whitespace changes hidden it will appear more familiar.
> Remove remaining FC from apps/web

- packages/auth/src/components/AuthenticationContainer.tsx
- packages/auth/src/components/AuthorizationContainer.tsx
- packages/client/src/components/ClientProvider/ClientProvider.tsx
- packages/eslint-config-custom/index.js
- packages/ui/src/components/Alert/utils.ts
- packages/ui/src/components/Button/IconButton.tsx
- packages/ui/src/components/CardLink/CardLink.stories.tsx
- packages/ui/src/components/CardLink/CardLink.tsx
- packages/ui/src/components/Chip/Chip.tsx
- packages/ui/src/components/Heading/Heading.tsx
- packages/ui/src/components/Link/ExternalLink.tsx
- packages/ui/src/components/Link/IconLink.tsx
- packages/ui/src/components/NotFound/NotFound.tsx
- packages/ui/src/components/Pending/ErrorMessage.tsx
- packages/ui/src/components/Pill/Pill.tsx
- packages/ui/src/components/SideMenu/SideMenu.test.tsx
- packages/ui/src/components/SideMenu/SideMenu.tsx
- packages/ui/src/components/SideMenu/SideMenuContentWrapper.tsx
- packages/ui/src/components/SideMenu/SideMenuItem.tsx
- packages/ui/src/components/Stepper/types.ts
- packages/ui/src/components/TableOfContents/AnchorLink.tsx
- packages/ui/src/components/TableOfContents/Content.tsx
- packages/ui/src/components/TableOfContents/Heading.tsx
- packages/ui/src/components/TableOfContents/Navigation.tsx
- packages/ui/src/components/TableOfContents/Section.tsx
- packages/ui/src/components/TableOfContents/Wrapper.tsx
- packages/ui/src/components/TileLink/TileLink.tsx
🤖 Resolves #5214 
This branch removes the remaining uses of React.FunctionComponent and React.FC from the repo.  It also adds a linting rule to prevent future use.
1. App builds
2. App runs OK and looks normal
3. No more instances of FC or FunctionComponent remain in repo
4. Attempt to add a new one and observe linting warning
> Final FC removal PR with linting rule

- apps/web/public/index.html
- packages/webpack-config/webpack.base.js
🤖 Resolves #5872 
Adds fallback, default open graph tags to `index.html`
This only adds English versions to remain under the soft 155 character limit for SEO. Should we tweak the text to shorten in and include French?
> **Note**
> Hard to test because `react-helmet-async` takes over and replaces the tags.
1. Comment out the `<SEO />` component in `HomePage.tsx` and `Layout.tsx`
2. Build the app `npm run build`
3. Navigate to the homepage `/en`
4. Confirm the open graph tags exist
> [Bug] Add default og tags

- api/database/seeders/UserSeederLocal.php
Seeding some users for convenience, small and quick addition.
While testing with roles in mind, it can be a bit slow if you don't immediately have a user with the specific permissions ready to go. And then rather than edit users with permissions in mind, it is easier to create some role specific ones ready to go.
platform@test.com -> platform-admin
request@test.com -> request-responder
pool@test.com -> pool-operator
All share base-user, without the applicant role you can immediately see login directs people to an error page. 
1. seed and login
2. policies aren't all sorted out yet so things will look off
> Seeding - add users with specific roles to local seeder

- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #6028 
This branch adds a container with margins to the pool advertisement page.  It correct the appearance when using left-aligned navs and matches the profile page better.
> **Note**
There's a lot of whitespace in the diff.  I recommend hiding whitespace in the diff view.
1. Navigate to http://localhost:8000/en/browse/pools/{:pool_id}
> Add container to pool advertisement page

- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationStatusForm/ApplicationStatusForm.tsx
- apps/web/src/pages/Users/UserInformationPage/components/NotesSection.tsx
🤖 Resolves #6030 
Label not rendered correctly. 
Need the label function rather than the html one for it. 
1. head to view user for a pool candidates table
2. observe label is fixed for the notes section
> Bug - 6030 - notes label not rendered correctly

- apps/e2e/cypress/e2e/admin/pool-candidate.cy.js
- apps/web/src/components/AdminSideMenu/AdminSideMenu.tsx
- apps/web/src/components/Router.tsx
- apps/web/src/pages/Pools/IndexPoolPage/IndexPoolPage.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/indexPoolsOperations.graphql
- apps/web/src/utils/teamUtils.ts
🤖 Resolves #5999 
Enables users with platform admin but not pool operator role to also view the pool table.
Simpler solution (I think) than the query pause idea. Just two wrapper components with different queries and conditionally render one or the other.
Platform admin can now also view a pool layout, info, and edit pages (need to in order to publish) but not candidates.
1. use adminer or whichever tool to keep reference of all pools
2. login as pool operator (pool@test.com), view pools table and note pools displayed
3. login as platform admin (platform@test.com), view pools table and note pools displayed
4. pool operator can only view dcm/test team pools whereas the other can view all so the table …
> Feature - 5999 - platform admin can view pools table

- apps/web/.env.example
- apps/web/public/config.ejs
- packages/env/src/useFeatureFlags.ts
- packages/env/src/utils.ts
🤖 Resolves #5960 
This branch adds the feature flag for application revamp. 
1. Copy a new .env file for apps/web (or rerun setup)
2. Rebuild the app (or rerun setup)
3. Visit the site, open the console, and run  `window.__SERVER_CONFIG__`, observe an entry for FEATURE_APPLICATION_REVAMP
> Add feature flag for application revamp :vampire: 

- apps/web/src/pages/Users/UpdateUserPage/UpdateUserPage.tsx
🤖 Resolves #6103 
This prevents role updates from overriding the user email to `null`.
We were setting the users email to `null` when it did not exist (either undefined or empty string) to prevent our validation from seeing `""` as a duplicate email. This unsets the email key in our mutation variables if it is undefined so that it is only nulled when it is an empty string.
1. Build the application `npm run build`
2. Navigate to `/admin/users/{userId}/edit
3. **Add** a role, confirm email is still present
4. **Remove** a role, confirm email is still present
5. **Empty** out the email, confirm it saves as empty
6. Attempt to update to an **existing** email, confirm it fails with nice error message
7. …
> [Bug] Fix user role from removing email

- api/app/Policies/PoolCandidatePolicy.php
- api/config/rolepermission.php
- api/tests/Unit/PoolCandidatePolicyTest.php
🤖 Resolves #6144
Creates the `update-any-applicationStatus` permission and assigns it to request responders to allow them to update candidate statuses and notes.
1. Log in as request@test.com
2. Go to requests table, view a request
3. Adjust the filters until at least one candidate appears, view the candidate
4. Confirm you can successfully update the candidates status and notes
> [Bug] Allow request responders to edit candidate statuses

- apps/web/src/lang/fr.json
- apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx
🤖 Resolves #5610.
This PR updates some English and French copy used in the breadcrumbs on the Work location form to make it consistent with the heading level 1 copy.
2. Navigate to Work location form `/fr/users/:userId/profile/work-location/edit`
3. Verify last breadcrumb item (Lieu de travail) matches heading level 1 (Lieu de travail)
4. Switch to English
5. Verify last breadcrumb item (Work location) matches heading level 1 (Work location)
6. Navigate to Work location form within an application `/fr/users/:userId/profile/work-location/edit?applicationId=:applicationId`
7. Verify last breadcrumb item (Lieu de travail) matches heading level 1 (Lieu de travail)
8. Switch to English …
> [Bug] Updates breadcrumb copy on Work location form page

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/indexPoolsOperations.graphql
🤖 Resolves #6090.
This PR adds the **Publishing group** column to the Admin Pools table.
2. Navigate to `/en/admin/pools`
3. Verify **Publishing group** column is visible by default and shows valid values
4. Verify sorting for **Publishing group** column works for ASC and DESC
> [Feature] Adds Publishing group column to Admin Pools table

- apps/web/src/pages/Teams/UpdateTeamPage/components/UpdateTeamForm.test.tsx
- apps/web/src/pages/Teams/UpdateTeamPage/components/UpdateTeamForm.tsx
🤖 Resolves #6115
Solves the bug and enables updating teams. 
For some reason, roleAssignments was being sneakily passed along in the ...rest. I removed it with the omit function.
As well, added a simple Jest test to exercise the submit functionality of the form. Maybe we should start Jest testing more 🤔 
1. Tests pass
2. Head to /admin/teams as platform_admin and successfully update a team
> Bug - 6115 error when attempting team updates

- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx
- apps/web/src/pages/Applications/ApplicationLayout.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/ApplicationProfilePage.tsx
- apps/web/src/pages/Applications/ApplicationQuestionsIntroductionPage/ApplicationQuestionsIntroductionPage.tsx
- apps/web/src/pages/Applications/ApplicationQuestionsPage/ApplicationQuestionsPage.tsx
- apps/web/src/pages/Applications/ApplicationResumeAddPage/ApplicationResumeAddPage.tsx
- apps/web/src/pages/Applications/ApplicationResumeEditPage/ApplicationResumeEditPage.tsx
- apps/web/src/pages/Applications/ApplicationResumeIntroductionPage/ApplicationResumeIntroductionPage.tsx
- apps/web/src/pages/Applications/ApplicationResumePage/ApplicationResumePage.tsx
- apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx
- apps/web/src/pages/Applications/ApplicationSkillsIntroductionPage/ApplicationSkillsIntroductionPage.tsx
- apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
- apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
- apps/web/src/pages/Applications/ApplicationWelcomePage/ApplicationWelcomePage.tsx
- apps/web/src/pages/Applications/StepDisabledPage/StepDisabledPage.tsx
- apps/web/src/pages/Applications/applicationOperations.graphql
- apps/web/src/types/poolCandidate.ts
- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
- packages/ui/src/components/Stepper/Stepper.stories.tsx
- packages/ui/src/components/Stepper/Stepper.tsx
- packages/ui/src/components/Stepper/testUtils.ts
- packages/ui/src/components/Stepper/types.ts
- packages/ui/src/components/Stepper/utils.ts
- packages/ui/src/index.tsx
🤖 Resolves #6063 
This branch adds a "skip ahead" page if you manually navigate to a disabled step in the flow and updates the stepper status to reflect submitted steps.
~Bonus: it adds the missing nginx config for the new application pages.~ I'll let #6171 handle this.
I had to do a bit of refactoring of the stepper component to make this work.  Specifically, I removed the ability of the stepper to disable its own steps and instead rely on the parent component.  This was needed because only the parent component knows the submitted steps and which ones to unlock.  I also added a "default" step state for steps that are not completed, not current, but need to be clickable for the user to go back to if they jumped ahead.  It also fixes a bug where the success page highlighted the "Welcome" …
> Application skip ahead page

- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/Home/IAPHomePage/components/LanguageSelector.tsx
🤖 Resolves #6098.
This PR adds i18n ability for locale strings used in the `LanguageSelector` component.
<details>
<summary>Strings for translation</summary>
```
{
"HtllH6": {
"defaultMessage": "Western Ojibway",
"description": "Name of Western Ojibway language"
},
"TEt9Ua": {
"defaultMessage": "Plains Cree",
"description": "Name of Plains Cree language"
},
"qxe/hN": {
"defaultMessage": "Mikmaq",
"description": "Name of Mikmaq language"
},
"zAl7ZH": {
"defaultMessage": "Michif",
"description": "Name of Michif language"
}
}
```
</details> 
1. Uncomment and import the LanguageSelector component from the [IAP Home page](https://github.com/GCTC-NTGC/gc-digital-talent/blob/11990f2cc63d26297db374c4dc9cdfe216 …
> [Bug] Adds i18n for `LanguageSelector` locale strings

- turbo.json
🤖 Resolves #6240 
Configures turbo to re-rerun codegen when the api schema changes.
1. Run `npm run codegen`. Should run.
2. Run `npm run codegen` again. Should be full turbo.
3. Change something in the schema.graphql file.
4. Run `refresh_api` script or `php artisan lighthouse:print-schema --write` to recompile the schema
5. Run `npm run codegen` again. Should re-run, and the change to the schema should appear in generated.ts
> [Bug] Add compiled schema file to codegen deps

- packages/client/src/components/ClientProvider/ClientProvider.tsx
- packages/client/src/utils/errors.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #6081 
Toast message when an action fails due to authorization/policy. 
Translation in. 
1. Head to someplace to trigger a policy error
2. Example, attempt editing a pool as platform@test.com
3. Observe toast
> Bug - 6081 - toast error for authorization

- .github/ISSUE_TEMPLATE/ 🐛-bug-report.md
- .github/ISSUE_TEMPLATE/⌨-accessibility-issue.md
- .github/ISSUE_TEMPLATE/♻️-debt-refactor.md
- .github/ISSUE_TEMPLATE/⚙️-new-component.md
- .github/ISSUE_TEMPLATE/✏️-documentation.md
- .github/ISSUE_TEMPLATE/✨-feature-request.md
- .github/ISSUE_TEMPLATE/📐-new-design-issue.md
- .github/ISSUE_TEMPLATE/🛠️-tooling.md
- .github/ISSUE_TEMPLATE/🧩-new-pattern.md
- .github/ISSUE_TEMPLATE/🧪-tests.md
This branch removes the placeholder issue titles from the templates.
We tend to get many issues on our board with very long titles.  For example, many titles start with ":keyboard:  Accessibility Issue - " but it's already clear that it's an issue with the accessibility label. I'm hoping that by removing the placeholder titles, submitters will not use them as prefixes and be encouraged to write short descriptive titles.
> Remove titles from templates

- apps/web/public/index.html
- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #6164 
This branch improves the caching policies for static content
- Disables all caching for local serving
- Sets long cache lives for hashed files
- Sets short cache lives for unhashed files
- Disables caching for index.html
- Adds a missing route rule
- Removes temporary cache-busting extension
> **Note**
To refresh Nginx rules, shell into the webserver container and rule `nginx -s reload`.
> **Note**
To test deployed, I have deployed this branch to DEV.  Contact me if you want to confirm it's still there.
1. Locally:
1.  All responses come back as "no-store".
2. GraphQL responses are also identified as "private".
2. Deployed:
1. Index.html comes back as no-cache, max-age=0
2. Hashed files come back as public, max-age=31536000
3. Unhashed files come back with public, a …
> Cache statics

- apps/web/src/pages/Applications/SignAndSubmitPage/signAndSubmitOperations.graphql
- apps/web/src/pages/Applications/applicationOperations.graphql
- apps/web/src/pages/Pools/PoolAdvertisementPage/poolAdvertisementOperations.graphql
- apps/web/src/pages/Profile/ExperienceAndSkillsPage/experienceAndSkillsOperations.graphql
🤖 Resolves #6300 
Solves the case of the missing skill descriptions. 
Just a case of missing fields from graphql files it appears.
Thing of concern is, we've had a few bugs like this already, really should think of a good way to mitigate this? Or may be something to keep in mind when reviewing. 
1. Find skill picker components and check for descriptions
2. ...
Edit Pool
Edit Application
Browse Opportunities 
Search Page
> Bug - 6300 - skill descriptions missing in query

- apps/e2e/cypress/e2e/admin/auth.cy.js
- apps/web/src/lang/fr.json
- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx
- apps/web/src/pages/Auth/LoggedOutPage/LoggedOutPage.tsx
- apps/web/src/pages/Auth/LoginPage/LoginPage.tsx
- apps/web/src/pages/Auth/RegisterPage/RegisterPage.tsx
- maintenance/README.md
🤖 Resolves #6284.
This PR updates the name of the service GCKey to be rendered with the proper spelling of its name: without the space between **GC** and **Key**.
Any **GC** abbreviation markup on strings that were part of the former **GC Key** have been removed since GCKey is not an abbreviation.
1. Browse `/logged-out`, `login-info`, `/register-info`, `/create-account`
2. Search for instances of **GC Key**
3. Ensure there are no instances of **GC Key**
4. Search codebase for instances of **GC Key**
5. Ensure there are no instances of **GC Key** or **Clé GC**
> [Bug] Fixes GCKey spelling

- apps/web/src/pages/Applications/ApplicantDashboardPage/components/QualifiedRecruitments/QualifiedRecruitments.tsx
🤖 Resolves #6256.
h/t @vd1992.
This PR adds a condition to filter out draft applications based on the `submittedAt` field (and the assumption that if the application has a `submittedAt` value, it is not a draft) from the active recruitments section of the **My dashboard** page.
1. Navigate to `/browse/pools`
2. Create a draft application
3. Navigate to `/applicant/dashboard`
4. Ensure cards in **Draft applications** accordion do not also appear in **Active recruitments** accordion
> [Bug] Fixes active recruitments applications filter

- .vscode/project-words.txt
- .vscode/settings.json
- apps/web/.env.example
- apps/web/public/config.ejs
- apps/web/src/components/Hero/Hero.tsx
- apps/web/src/components/StrikeNotice/StrikeNotice.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx
- apps/web/src/pages/SearchRequests/RequestPage/RequestPage.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchHeading.tsx
- packages/env/src/useFeatureFlags.ts
- packages/env/src/utils.ts
- packages/ui/src/components/Alert/Alert.tsx
🤖 Resolves #6317
- new feature flag
Adds a strike notice to users to explain slower response times on search requests.
This also reduces the hero container to be slightly smaller and fixes alert title line height.
1. Copy `FEATURE_PSAC_STRIKE=true` to your `.env` file
2. Rebuild docker `docker-compose down` `docker-compose up --build --detach`
3. Build the application `npm run build:fresh`
4. Navigate to `/search` to confirm alert appears in both French and English
5. Start a request and confirm alert appears in both French and English on request form page
6. Submit request and confirm alert appears in both French and English on confirmation page
> [Feature] Adds Strike Notice

- apps/web/src/components/Layout/Layout.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/pages/Applications/ApplicationLayout.tsx
- apps/web/src/pages/Applications/MyApplicationsPage/components/ApplicationList/ApplicationList.tsx
- apps/web/src/pages/Applications/SignAndSubmitPage/SignAndSubmitPage.tsx
- apps/web/src/pages/Auth/LoggedOutPage/LoggedOutPage.tsx
- apps/web/src/pages/CreateApplicationPage/CreateApplicationPage.tsx
- apps/web/src/pages/Home/HomePage/components/Hero/Hero.tsx
- apps/web/src/pages/Home/HomePage/components/Opportunities/Opportunities.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #6227 
- Fixes dead browse opportunities link on the applicant dashboard page, found in the draft applications accordion empty state.
- Removes old `browse()` route and renames route `allPools()` to `browsePools()`.
1. Ensure the `browsePools()` route is working correctly.
> Bug - 6227 - browse pools route

- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicantDashboardPage/components/DashboardHeading.tsx
- apps/web/src/pages/Applications/ApplicationResumeIntroductionPage/ApplicationResumeIntroductionPage.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/ApplyDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/LearnDialog.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/components/OngoingRecruitmentSection/OngoingRecruitmentSection.tsx
- apps/web/src/pages/Profile/ExperienceAndSkillsPage/components/AddExperienceDialog.tsx
🤖 Resolves #6288.
This PR corrects spelling of the word résumé in English, excluding the tc-report.
1. Search for instances of the string **résume**, **resumé**, or **resume** in the codebase
2. Ensure no instances found of **résume** or **resumé**
3. Ensure any existing instances of **resume** do not refer to the word that also means curriculum vitae
> [Bug] Corrects spelling of the word résumé in English

- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicantDashboardPage/components/DashboardHeading.tsx
🤖 Resolves #6258.
This PR adds dashboard experiences count that had not been hooked up.
[Fixes French context message to describe number of experience items added](https://github.com/GCTC-NTGC/gc-digital-talent/commit/8a8b37e95c93463aeac3e54f366b620f3fb1a798). This string likely got confused when translating as the translator likely did not know what to translate.
1. Navigate to **My dashboard** page `/applicant/dashboard`
2. Ensure experiences have counts
4. Ensure experiences have counts in French (_article_ not _item_)
> [Bug] Adds dashboard experiences count

- apps/web/src/pages/Applications/ApplicationLayout.tsx
- apps/web/src/pages/Applications/ApplicationQuestionsPage/ApplicationQuestionsPage.tsx
- apps/web/src/pages/Applications/ApplicationResumePage/ApplicationResumePage.tsx
- apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
- apps/web/src/types/poolCandidate.ts
- apps/web/src/utils/applicationUtils.ts
🤖 Resolves #6320 
Adds a redirect if you land on a page in the application process when navigating to it with the base path (`/applications/{applicationId}`)
This is sort of janky and I believe it would be smoother in a [loader](https://reactrouter.com/en/main/route/loader) but we have yet to start implementing the refactor required for that. 😢 
1. Build the app `npm run build:fresh`
2. Start and application
3. Navigate to `/applications/{applicationId}`
4. Confirm you are are redirected to the welcome page
5. Manually update the `submittedSteps`
6. Confirm entering `/applications/{applicationId}` into the address bar redirects to either:
1. The first page for the step that has not been submitted yet …
> [Feature] Application entry redirect

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/HomePage/components/Hero/Hero.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
🤖 Resolves #6287.
This PR updates copy that goes to the same URL to be the same in English and French for consistency.
Changes **Looking to hire?**, **Visit the talent search page** to **Find talent** in English and **Trouvez des talents** in French.
1. Navigate to `/en/`
2. Observe **Find talent** button
3. Switch language to French
4. Observe **Trouvez des talents** button
5. Navigate to `/en/browse/pools`
6. Observe **Find talent** button
7. Switch language to French
8. Observe **Trouvez des talents** button
<details><summary>Home page</summary>
</details>
<details><summary>Browse jobs page</summary>
</details>
> [a11y] Change Looking to hire?, Visit the talent search page to Find talent

- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #6085.
This PR fixes an incorrect icon.
1. Navigate to browse pool `/browse/pools/:poolId/#details-section`
2. Observe icon beside **Hiring policies** heading
> [Bug] Fixes incorrect icon

- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #6360
Updates the pool advertisement to allow pool operators to preview draft advertisements.
This also bumps the draft check to exit early if the advertisement is not a draft avoiding the permissions check entirely since all roles can view non-draft pools.
> **Note**
> This does not care if the pool is part of your team as a pool operator since we do that [check on the backend](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a3068e473c155e21fc5eb4516653f890c6d25ca9/api/app/Policies/PoolPolicy.php#L44) and it should error out anyway.
1. Login as `pool@test.com`
2. Create a draft pool
3. Navigate to `/browse/pools/{poolId}`
4. Confirm you can see the draft pool
5. Attempt to view a draft …
> [Bug] Fix draft pool advertisement visibility

- apps/web/src/components/Table/ApiManagedTable/helpers.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #6329.
This PR updates **Select** in select `input` to use imperative in French.
Fixes text for **Select all** on table "Header label for the row-selection column in tables".
1. See select `input` in French
2. Observe **Sélectionnez**
> [Bug] Update Select to use imperative in French

- packages/ui/src/components/Link/ScrollToLink.tsx
- packages/ui/src/components/TableOfContents/AnchorLink.tsx
- packages/ui/src/components/TableOfContents/Section.tsx
🤖 Resolves #5540 
Updates the `TableOfContents` links so that they set the focus on target section when invoked.
> **Bonus**
> Test this with an AT enabled to hear what is announced at the same time
2. Navigate to a profile
3. Tab to a TOC link and invoke it (with `enter` or `space`)
4. Hit tab
5. Confirm the next focused element is the link in that section
> [A11y] Focus section on TOC link click

- api/database/seeders/DatabaseSeeder.php
🤖 Resolves #6403
Allows you to run Database seeder more than once without errors.
Resets the Pools and Teams tables before seeding.
1. Run `docker-compose exec -w /home/site/wwwroot/api webserver php artisan db:seed`
2. Run `docker-compose exec -w /home/site/wwwroot/api webserver php artisan db:seed` again
3. It should work now!
> [Bugfix] Truncate Pools and Teams tables to avoid errors when seeding again

- apps/web/src/components/InfoItem/BaseInfoItem.tsx
- packages/ui/src/components/Breadcrumbs/Crumb.tsx
- packages/ui/src/components/Link/useCommonLinkStyles.ts
- packages/ui/src/components/TableOfContents/AnchorLink.tsx
🤖 Resolves #6253 
This adds styles to indicate hover state for TOC and Breadcrumb links.
This also updates the `useCommonLinkStyles` hook to set hover state for links that do not have `type=button`.
1. Build `npm run build:fresh`
2. Navigate to a pool advertisement
3. Confirm both "On this page" and breadcrumb links change style when hovered
4. Navigate to a user profile
5. Confirm "On this page" links change style when hovered
> [Bug] Add TOC/Breadcrumb hover states

- api/database/factories/PoolCandidateFactory.php
- api/tests/Feature/ApplicantTest.php
🤖 Resolves #6381 
Fixes the `ApplicantTest::testCountApplicantsQuerySuspended` making it pass consistently.
We introduced a new `suspended_at` column on the `PoolCandidate` model to determine if users are available instead of the deprecated `job_looking_status` on the `User` model but never updated the test to reflect that change.
> **Note**
> There are some formatting changes as a result of the new format on save. Sorry if it complicates the diff 😬 
1. Run `for i in {1..20}; do docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/ApplicantTest.php"; done`
2. Go make a ☕ or 🍵 
3. Come back and ensure there were no failures
> [Bug] Fix suspended application test

- apps/web/src/components/ExperienceFormFields/AwardFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.test.tsx
- apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.tsx
🤖 Resolves #6323.
This PR change all `nullSelection` values to begin with the word **Select**.
h/t @esizer [fix group conditional logic](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6402/commits/23e0774c7eb89af574189f5f9139f13ae01d52ca)
1. Search for values within `nullSelect`
2. Ensure all of the strings begin with the word **Select**
3. Navigate to `/users/:userId/profile/government-info/edit`
4. Observe nullSelection option for **Current Classification Group** and **Current Classification Level**
5. Navigate to `/users/:userId/profile/experiences/award/create
6. Observe nullSelection option for **Awarded to** and **Award Scope**
7. Navigate to …
> [Bug] Changes all `nullSelection` values to begin with Select

- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #6251 
This fixes the experience/education cards colour contrast ratio by using the new `secondary` colour prop instead of the old `ts-secondary`
We deprecated the old prefixed color pallette in favour of hydrogen themes but have yet to update some components.
https://github.com/GCTC-NTGC/gc-digital-talent/issues/6397
2. Navigate to a job poster
3. Run axe dev tools
4. Confirm there are no colour contrast errors
> [A11y] Update education card colour

- apps/web/src/pages/Home/IAPHomePage/components/Card.tsx
🤖 Resolves #6249 
Thinks adds the `aria-hidden` attribute to the icons on the IAP homepage so they are not identified by assistive technologies.
3. Scroll down to the "Strategy" section
4. Confirm the icons have `aria-hidden=true`
5. Confirm an AT does not identify them
> [A11y] Hide icons on IAP to ATs

- apps/web/webpack.prod.js
🤖 Resolves #4570 
Increases the max size to `500000`. 
For asset size, and entrypoint size. I adjusted the latter too because it didn't make sense for it to be less than asset max. 
> [Debt] increase maxAssetSize for webpack prod

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
🤖 Resolves #6315.
This PR makes the Pool Candidates table **Preferred Communication Language** column visible by default and displays the **Preferred Communication Language** directly after the **Candidate Name** column.
1. Navigate to `/admin/pools/:poolId/pool-candidates`
2. Observe **Preferred Communication Language** renders by default
3. Observe **Preferred Communication Language** displays directly after the **Candidate Name** column
> [Feature] Changes Pool Candidates Preferred Communication Language column order and visibility

- apps/web/src/components/Hero/Hero.tsx
🤖 Resolves #6234 
This adds `aria-hidden=true` to the SVG in the hero to avoid ATs announcing it.
This image is purely decorative so does not need to be announced.
> **Note**
> I could only reliable reproduce the issue in VoiceOver so please check with that screen reader to be certain (JAWS and NVDA were ignoring it regardless of the `aria-hidden` attribute)
2. Navigate to a page with the SVG in the hero (pool advertisements is one)
3. Step through the page with your arrows keys and screen reader on
4. Confirm no image is announced (this was happening between the `h1` and breadcrumbs.
> [a11y] Hide hero svg for ATs

- apps/web/src/components/SkillPicker/SkillPicker.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/AssetSkillsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/EssentialSkillsSection.tsx
🤖 Resolves #6369 
This moves the `<Submit />` button outside of the `<SkillPicker />` to stabilize it's submitting/submitted/idle state.
The `<Submit />` button was part of the `<SkillPicker />` form and was not aware of the changing skills. This caused two issues:
1. Changes to the dropdown/search bar were erroneously setting the form state to dirty
2. Skill picker is re-rendered on change so it was reset to clean after every re-render
Moving this out allows us to cleanly track dirty skills and should stabilize the button state.
1. Build the app `npm run build:fresh`
4. Login as `admin@test.com`
5. Create a pool
6. Add a skill and click the submit button
7. Confirm it changes from default message to …
> [Bug] Fix edit pool skill submit button state

- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
🤖 Resolves #6374 
This updates the classification sort on the `PoolTable` to no longer sort differently when the sort order is set to `DESC`
Thanks to @vd1992 who pointed directly to the change that needed to be made 🥇 
1. Build `npm run build:fresh`
3. Sort the "Group and level" column
4. Confirm it sorts as expected in both `ASC` and `DESC` order.
> [Bug] Fix pool classification sort

- apps/web/src/pages/SearchRequests/SearchPage/components/AdvancedFilters.tsx
- packages/ui/src/components/Accordion/StandardHeader.tsx
🤖 Resolves #5728 
This does a few things,
- Increases spacing above advanced filters to match spacing between other sections
- Updates the headings to be the appropriate ranks
- Reduces the size of the headings to be smaller than the lower ranked headings on the pages
Kind of hacky way of getting the font size reduced on the headers but I do believe we plan on overhauling the accordions to support action links so think of this as a temp fix? 😅 
3. Confirm advanced filters has similar spacing to other sections
4. Confirm it is using the appropriate heading tanks
5. Confirm the accordion titles are smaller than the lower ranked "Advanced filters" heading
> [Bug] Adjust advanced filter styles

- apps/web/src/components/Table/ApiManagedTable/SearchForm.tsx
- apps/web/src/components/Table/ClientManagedTable/SearchForm.tsx
- apps/web/src/components/Table/ClientManagedTable/Table.tsx
- apps/web/src/components/Table/ResetButton.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #6368 
Adds a basic reset button to the search input for tables.
2. Navigate to a client table `/admin/pools/`
3. Type in the search
4. Confirm reset button appears
5. Confirm clicking it clears out the search and sets focus on the search input
6. Navigate to an API table `/admin/users`
7. Repeat steps 3-5
> [Feature] Add reset button to table search

- packages/storage/src/local.ts
- packages/storage/src/session.ts
- packages/storage/src/utils.ts
🤖 Resolves #4648 
Updates the storage argument type to no longer accept `undefined`
It appears in the typescript `lib.dom.d.ts` that both local and session storage are never allowed to be undefined so it should be as simple as removing the `undefined` in the arg types.
```tsx
interface WindowLocalStorage {
readonly localStorage: Storage;
}
interface WindowSessionStorage {
readonly sessionStorage: Storage;
}
interface Window extends ... WindowLocalStorage, WindowSessionStorage { ... }
```
2. Navigate to `/admin`
3. open/close the menu
4. Refresh page
5. Confirm menu remains in state you left it in and the local storage is set as expected
6. Navigate to a profile form
7. Make a change …
> [Debt] Prevent `undefined` window storage

- .github/workflows/bundlewatch.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/jest.yml
- .github/workflows/lint.yml
- .github/workflows/storybook.yml
🤖 Resolves #6475.
This PR updates GitHub workflows to all use the same `NPM_VERSION` value in the codebase.
1. Observe this PR's GitHub workflows
2. Ensure they are all running without warnings or errors
3. Search codebase for `NPM_VERSION`
4. Ensure value for `NPM_VERSION` is always 8.11.0
> [Debt] Updates `NPM_VERSION` to 8.11.0

- apps/web/src/components/Layout/Layout.tsx
- packages/ui/src/components/Link/MenuLink.tsx
🤖 Resolves #5704 
Removes the function that does nothing when passed in `type === "link"`
Straightforward enough. 
Alignment of "My dashboard" pre-existing, see #6487
1. Observe MenuLinks unchanged
> [Debt] Remove unusable function from MenuLink

- apps/web/src/components/SelfDeclaration/SelfDeclarationForm.test.tsx
🤖 Resolves #6223 
This branch solves Jest error messages in the `SelfDeclarationForm.test.tsx` file.
It seems like this error message happens when there are unnecessary act statements.  It seems to also be related to React 18 so it probably these started at that point.
https://github.com/testing-library/react-testing-library/issues/1061
1. In the `apps/web` directory run `npx jest --testPathPattern=SelfDeclarationForm.test.tsx`
2. Observe that all tests pass and there are no console error messages.
> [Bug] Remove unnecessary act statements

- packages/ui/src/components/Tabs/Tabs.test.tsx
🤖 Resolves #6220
This branch solves Jest error messages in the `Tabs.test.tsx` file.
There were some DOM changes not happening inside of `act` statements.
1. In the `packages/ui` directory run `npm run test`
2. Observe that all tests pass and there are no console error messages.
> [Bug] Fix tabs test

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/EstimatedCandidates.tsx
🤖 Resolves #6482.
This PR updates a heading, **Estimated Candidates**, to sentence case **Estimated candidates**.
1. Navigate to `/en/search`
2. Observe **Estimated candidates**
3. Navigate to `/fr/search`
4. Observe **Nombre approximatif de candidats** remains the same
> [Bug] Updates Estimated candidates sentence case

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchPools.tsx
🤖 Resolves #6481.
This PR adds a period to the end of sentence for the **Message for total estimated matching candidates in pool**.
1. Navigate to `/en/search`
2. Observe period within results cards
3. Navigate to `/fr/search`
4. Observe period within results cards
> [Bug] Adds period to end of sentence

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/AddSkillsToFilter.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
🤖 Resolves #6416 
Re-connects skills filtering on the search page.
Updates some copy. 
Skills filtering was quick to re-enable. Context was straightforward for location and EE.
Skills was trickier, it is a complex component used in multiple areas. I did not want to muddle with it, so I added the note below the component. I also made it so it can be conditionally rendered based off whether any skills were selected. 
1. Head to search page
2. Fill out a request, note the added notes are present
3. Note skills filtering returns more candidates with more skills selected
4. Submit request, check in the admin dashboard that the request matches and has the correct candidate count
Translations
> [Feature] Search page OR filtering changes

- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.stories.tsx
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/SearchRequests/RequestPage/requestOperations.graphql
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx
- packages/fake-data/src/fakeApplicantFilters.ts
- packages/fake-data/src/index.ts
🤖 Resolves #6366 
Adds a filter block for "Pool requested" to the filter summary component, as well as removes it from the manager info component. 
Nothing too fancy. I mimicked how classifications/skills were done to add pool naming to the request page.
On that note.
This feels sub-optimal and the query will get rather slow with more pools and any other new additions. Something to look at for refactoring search.
Is it possible to save to local storage the selected classification object, array of skills selected, and pool object rather than fetch all classifications + skills + pools on the following page to re-assemble the state on the page prior?
Like
```
objectStore = {
classification : {group ...},
skills: [Skill},
pool: {name ...}
}
```
Then on the request form page, `{ group,  level …
> [Feature] Requested pool labelling for requests

- api/app/GraphQL/Directives/SelfDirective.php
- api/composer.json
- api/schema-directives.graphql
🤖 Resolves #6527 
Adds the `@self` custom lighthouse directive.
I wanted to write some php unit tests for this directive, but I can't figure out how to do so. A proper unit test wouldn't be dependent on the schema or models in the app. I tried using a [test schema](https://lighthouse-php.com/6/testing/extensions.html#mock-resolvers), but couldn't figure out how to set it up in a way that properly made use of the directive.
NOTE: you will need to restart VS Code for IDE tools to recognize the `@self` directive.
1. Temporarily modify the schema: add `applicant: Applicant @self` to the `User` type.
2. Add `AUTH_DEFAULT_USER='admin@test.com'` to api/.env
3. go to http://localhost:8000/graphiql and run the following query:
```
query {
me {
applicant {
email
}
}
}
```
4. You should get the …
> Create a `@self` directive to help organize schema

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/pages/Applications/ApplicationProfilePage/components/GovernmentInformation/utils.ts
- apps/web/src/pages/Profile/GovernmentInfoPage/components/GovernmentInfoForm/GovernmentInfoForm.tsx
🤖 Resolves #6413 
The removal of `BelongsTo` relation classification and department wasn't written how it should be used. Written to use `disconnect`. 
Update the government info section with user info as a government employee then update it as not an employee. 
Keep an eye on the network tab and ensure requests/responses are what they should be for the operation.
> [Bug] GovernmentInfoForm disconnect BelongsTo relations 

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #6480.
This PR fixes the copy for the equity section paragraph in English and French and changes the string **Indigenous identity** to use sentence case.
1. Navigate to `/en/search`
2. Observe **Employment equity** paragraph
3. Observe **Indigenous identity** label for checkbox
4. Navigate to `/fr/search`
2. Observe **Équité en matière d'emploi** paragraph
> [Bug] Fixes equity section copy

- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/components/SearchRequestFilters/deprecated/SearchRequestFilters.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #4647.
This PR removes unused `typeOfOpportunity` as well as its associated copy.
1. View any request in admin
2. Ensure there is no **Type of opportunity** heading under the Request Information section
@substrae or @GCTC-NTGC/designers please update the design in figma to reflect this change.
> [Debt] Removes unused typeOfOpportunity

- api/database/factories/CommunityExperienceFactory.php
- api/database/factories/EducationExperienceFactory.php
- api/database/factories/PersonalExperienceFactory.php
- api/database/factories/WorkExperienceFactory.php
- apps/web/src/pages/Applications/ApplicationResumePage/ApplicationResumePage.tsx
- apps/web/src/pages/Profile/ExperienceAndSkillsPage/ExperienceAndSkillsPage.test.tsx
- apps/web/src/types/experience.ts
- apps/web/src/utils/experienceUtils.ts
🤖 Resolves #6456 
Make sorting experiences work with Award Experiences and removed the duplicate sort.  
Solved by treating them as the same as the other experience types with the special state that award_date = start_date = end_date
As well, resolved some sorting bugs I noticed:
`nonEmptyExperiences` was introduced in #6574, but needs to be passed into what is rendered for the sort to happen
`watchSortExperiencesBy` starts off as undefined, which makes the sort initially disconnected from the select, resolved with a default
Seeding allows for end dates before start dates for experiences, changed that
1. head to `/en/applications/:id/resume`
2. observe sorting
3. create more experiences and see sorting
> [Bug] Fix sorting of Award Experiences

- api/app/Models/PoolCandidate.php
- api/tests/Feature/PoolCandidateTest.php
🤖 Resolves #6594.
h/t @esizer.
This PR fix the pool candidates **number of skills matched** column that was not working correctly and strengthens the tests associated with it.
1. Run `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/PoolCandidateTest.php"`
2. Ensure tests passed 10 times
> [Bug] Fixes pool candidates skill count

- packages/theme/src/components/ThemeProvider.tsx
🤖 Resolves #6012 
This updates the `ThemeProvider` to supply override to the state.
We were relying on default `useState` to compute the theme which was sort of unstable. This also updates the `useMemo` to supply override and use it if no default theme has been provided. This should make the override a little more stable 🤷‍♀️ 
1. Run chromatic
2. Confirm no diff
> [Bug] Fix theme override

- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
🤖 Resolves #6605
I discovered and fixed this bug in the course of investigating something else, so I might as well push up a PR.
Allows you to use the search bar to filter pools by classification or by team.
0. Run seeders
1. Log in as admin@test.com
2. Go to http://localhost:8000/en/admin/pools
3. Type "Digital" in search bar and confirm that non DCM team pools are filtered out
4. Type "IT-02" in search bar and confirm that you only see IT-02 pools
> [Bug] Make teams and classifications on Pool Table more searchable

- api/database/seeders/PoolSeeder.php
- apps/web/public/iap.webmanifest
- apps/web/src/components/Layout/IAPLayout.tsx
- apps/web/src/lang/fr.json
- apps/web/src/lang/mic.json
- apps/web/src/pages/Home/HomePage/components/Featured/Featured.tsx
- apps/web/src/pages/Home/HomePage/components/Opportunities/Opportunities.tsx
- apps/web/src/pages/Home/IAPHomePage/Home.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
- documentation/h2-upgrade-guide.md
- packages/fake-data/src/fakePools.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #6593
This branch replaces all occurrences of the apprenticeship program's name to _IT Apprenticeship Program for Indigenous Peoples_.  Additionally, Brooke confirmed that the French name should use the word _personnes_ not _peuples_ so I updated that, too.  I didn't update the acronym IAP anywhere since it's still reasonably accurate and I haven't heard an updated one used.
1. _Indigenous Apprenticeship Program_ does not appear in the codebase.
2. _Programme d’apprentissage en TI pour les peuples autochtones_ does not appear in the codebase.
3. No missing translations.
4. No mangled translations.
> [Bug] Update name for apprenticeship program

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/BrowsePoolsPage/components/OngoingRecruitmentSection/OngoingRecruitmentSection.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #6584 
Enable reverting to filtering out nothing for the recruitments section. 
Implemented the suggested `<Dropdown>`
Followed the skill picker implementation as a guide. 
1. Navigate to `/en/browse/pools` and scroll down to the ongoing recruitments section
2. Play around with filtering
> [Bug] Enable filtering for All in ongoing recruitments

- apps/web/src/components/Layout/IAPLayout.tsx
🤖 Resolves #6612 
This moves the two strings to child components so they have access to the current nested language provider context.
We were using the parent language provider context that did not include the nested provider strings (Mi'kmaq)
2. Navigate to `/indigenous-it-apprentice?locale=mic`
3. Confirm both the page title and nav menu are using the Mi'kmaq language
> [Bug] Expand nested language provider

- api/app/Rules/QuestionsAnswered.php
- api/tests/Feature/PoolApplicationTest.php
🤖 Resolves #6644 
This checks to ensure the application revamp 🧛 feature flag is enabled before validating that screening questions have been answered.
We have enabled the ability for admins to add screening questions but have yet to display them to users. This is causing issues with our validation since users are unable to answer those questions 😛 . This just exits the validation early if we do not have the flag enabled.
1. Ensure `api/.env` has `FEATURE_APPLICATION_REVAMP=true` under the feature flag section
2. Start an application with screening questions on it
3. Confirm you **_cannot_** submit with none of the questions being answered
4. Disabled the feature flag in `api/.env`
5. Attempt the …
> [Bug] Fix screening question validation

- apps/web/src/pages/Applications/ApplicationProfilePage/components/PersonalInformation/Display.tsx
🤖 Resolves #6531 
This converts `<p>` tags on the `ApplicationProfilePage` to `<span>` tags to not have them improperly nested.
1. Build `npm run build:fresh`
2. Cereate an application and continute to the profile step
3. Run axe dev tools, confirm no errors
4. Confirm there are no console errors about nested `<p>`
5. Confirm the Language section in Personal information still renders as expected
> [Bug] Fix nested `<p>` tags

- apps/web/src/assets/css/app.css
🤖 Resolves #5785 
Adds some default styles to the `abbr` tag so they appear consistently across browsers
2. Navigate the homepage
3. Confirm the GC wrapped in `abbr` shows consistently in all major browsers (Chrome, Firefox, Safari)
>**Note**
> Dotted underline appears slightly differently in each browser, but at least it is there! 😛
> [Bug] Add consistent styles for `abbr` tags

- apps/web/src/pages/Pools/EditPoolPage/components/WorkTasksSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/YourImpactSection.tsx
🤖 Resolves #6645 
- Adds 100 words to French text areas on Edit pool page.
1. Login as admin 
2. Go to pools table and find a pool with DRAFT status.
3. Click on edit and scroll down to Your Impact and Work Tasks section.
4. Ensure the french text areas allow higher word count.
> Feature - 6645 - Add 100 words to fr text areas on edit pool page

- apps/web/src/lang/fr.json
🤖 Resolves #6582.
This PR replaces quotes with _guillemets_ in a French string.
1. `npm run intl-compile`
2. `npm run storybook`
3. Navigate to **Experience Accordion** > **Accordion Award** in storybook
4. Switch locale to FR
5. Observe _guillemets_ instead of quotes in **Comment j’ai utilisé** strings
> [Bug] Replaces quotes with guillemets in French string

- api/graphql/schema.graphql
- apps/web/src/pages/Departments/CreateDepartmentPage.tsx
- apps/web/src/pages/Departments/UpdateDepartmentPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #6409
Make it possible to update department number. 
Needed to ensure `departmentNumber` was passed into the mutation. 
Given `department_number` must be unique in the database, added a validation rule with error message to the input for a nicer experience. To avoid it being forgotten about, I also copied the rule to create department as well. 
I also slapped a min = 0 for department number to prevent having negative department numbers accidentally or even intentionally. Can be reverted if desired. 
1. Head to `/en/admin/settings/departments`
2. Ensure updating a department's number works and the error toast appears if you attempt to reuse numbers
Error message that is returned without the validation
> [Bug] Make department number update-able 

- apps/web/src/components/ExperienceFormFields/AwardFields.tsx
- apps/web/src/components/ExperienceFormFields/CommunityFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/components/SkillsInDetail/SkillsInDetail.tsx
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/Applications/ApplicationProfilePage/components/PersonalInformation/FormFields.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/components/WorkPreferences/FormFields.tsx
- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/WorkTasksSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/YourImpactSection.tsx
- apps/web/src/pages/Profile/AboutMePage/components/AboutMeForm/AboutMeForm.tsx
- apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/Teams/CreateTeamPage/components/CreateTeamFormFields.tsx
- apps/web/src/pages/Users/UserInformationPage/components/NotesSection.tsx
🤖 Resolves #6324.
This PR removes the `placeholder` prop from most `Input` and `TextArea` components with the exceptions of:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/843a63a0350eac9c8c72c84f3ac2edc8d974c932/apps/web/src/components/SkillPicker/SkillPicker.tsx#L152-L156
https://github.com/GCTC-NTGC/gc-digital-talent/blob/843a63a0350eac9c8c72c84f3ac2edc8d974c932/apps/web/src/pages/Profile/AboutMePage/components/AboutMeForm/AboutMeForm.tsx#L374-L379
1. Ensure `placeholder` attribute not used on `input` and `textarea` except for `SkillPicker` and telephone `input`
> [Bug] Removes placeholder prop from most `Input` and `TextArea` components

- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
🤖 Resolves #6306 
Adds missing null states to the admin view pool page.
This currently uses the `commonMessages.notProvided` message in favour of introducing a new string that says a similar thing. Currently, I am waiting to hear if this is acceptable from designers.
>**Note**
> This also lifts the skill family headings outside of the skill check to always display them so we can tell admins that they have no added them instead of hiding it completely.
2. Login as admin and create an empty pool
3. Navigate to the the pool information page for that new pool
4. Confirm there are no empty null states but instead it says "Not provided"
> [Bug] Add missing null states to view pool page

- api/app/Models/User.php
🤖 Resolves #6638 
Remove the deprecated field from being checked in profile completeness. 
Small change. 
1. Create application
2. Ensure your role & salary is incomplete, use Adminer to delete the entry from the `generic_job_title_user` pivot
3. Skip to submit page by changing URL
4. Ensure application submits successfully
May need to switch revamp feature flag off to get around education requirement check.
> [Debt] Remove expectedGenericJobTitles from profile completeness

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.stories.tsx
- apps/web/src/pages/Applications/ApplicationResumePage/ApplicationResumePage.stories.tsx
🤖 Resolves #6595 
Updates the shape of args passed into 3 stories to fix errors with the data the components require.
We updated the shape of `poolCandidatesPaginated` but never updated the story, this fixes that along with adjusting the args for the reivew resume page story.
2. Confirm the following stories function as expected:
- Pages / Application Revamp / Review Resume / No Experiences
- Pages / Application Revamp / Review Resume / Has Experiences
- Tables / Pool Candidates Table / Default
> [Bug] Fix storybook component errors

- apps/web/src/components/Header/Header.tsx
🤖 Resolves #6611 
Removed the `onClick` handler in the language switcher link.
Since our `LocaleProvider` is smart enough to determine locale from the url, I do not believe we needed the `onClick` which prevented the default functionality of the link so we could `setLocale` at the same time. Removing that click handler seemed to fix the browser history bug while keeping the functionality intact 🤷‍♀️ 
2. Navigate to `/en`
4. Confirm language changes
5. Click the browser back button
6. Confirm you can go back
7. Repeat steps 2-6 but with the opposite locale
> [Bug] Fix language switcher history

- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx
🤖 Resolves #6673.
This PR fixes a typo on the education page of the application process.
2. Navigate to a pool advertisement
3. Apply to the pool
4. Continue to the education requirement step
5. Confirm the education requirement copy is accurate
> [Fix] Fixes typo on education page of application

- apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
- packages/i18n/src/components/richTextElements.tsx
🤖 Resolves #6577 
Updates primary text in the `SkillAccordion` component to be `primary.darker`
Kind of hard to see since `primary.darker` is so close to the black colour 😬 
2. Navigate to `/users/{userId}/profile/experiences`
3. Add the same skill to each experience type
4. Select the "By skills" tab
5. Open the accordion for the skill you added to each experience type
6. Confirm all primary text is using `primary.darker`
> [Bug] Fix inconsistent skill accordion colours

- turbo.json
🤖 Resolves #6008 
Adds the custom lint config to the lint turbo config so empty cache when lint rules change.
Lint command: `npm run lint -- -- --max-warnings=0`
1. Run command, note no cache
2. Re-run command, confirm full cache
3. Make change to `packages/eslint-config-custom/index.js`
4. Re-run command, confirm no cache 
5. Re-run command, confirm full cache
6. Revert change
7. Re-run command, confirm full cache
> [Fix] Update link turbo config

- packages/forms/src/utils.ts
🤖 Resolves #6031 
Prevent crashing of the function, and subsequently the page if a very, very long string is input. 
The function is only used in one place, the `Skillpicker`, and it is a rather edge case since it requires someone to go out of their way to intentionally crash their browser. 
Since the input doesn't actually submit anything, rather, just searches through a skills array in the frontend. I decided against adding restrictions to inputs, there was only one place where this function applied anyway. The input in question doesn't have a rules prop either. 
So I elected for the simple cap to short-circuit the function in cases where the string is 1000 characters or more. 
1. Navigate to `/en/search`
2. Head to the skills selection section
3. Paste a very massive string into the …
> [Bug] Prevent matchStringCaseDiacriticInsensitive() from crashing for enormous strings

- packages/app-insights/package.json
- packages/auth/package.json
- packages/client/package.json
- packages/date-helpers/package.json
- packages/env/package.json
- packages/fake-data/package.json
- packages/forms/package.json
- packages/helpers/package.json
- packages/i18n/package.json
- packages/jest-helpers/package.json
- packages/logger/package.json
- packages/storage/package.json
- packages/theme/package.json
- packages/toast/package.json
- packages/tooling/package.json
- packages/ui/package.json
🤖 Resolves #6679 
Removed the `TIIMING` from eslint to reduce noise in output.
1. Run `npm run lint`
2. Confirm they still function and timing table does not show in output
> [Chore] Remove `TIMING` from lint

- .github/workflows/e2e-tests.yml
- apps/e2e/cypress.config.ts
- apps/e2e/package.json
- maintenance/scripts/setup.sh
- package-lock.json
🤖 Resolves #5095, #6510.
This PR upgrades Cypress to v12.
Other related changes:
- Updated the platform recommended in `cypress-io/github-action` docs
- Removed the experimental `experimentalSessionAndOrigin` flag that was incorporated into the version 12 of Cypress
- Update `@testing-library/cypress` to a version compatible with version 12 of Cypress
1. `npm install`
2. `npm run e2e`
3. Ensure Cypress works as it did before locally and in CI
> [Dependency] Upgrades Cypress to version 12

- api/tests/Feature/ApplicantFilterTest.php
🤖 Resolves #6439 
Hopefully solve the annoyance of an occasionally failing test.
Results returned sometimes had some randomness which seems to have messed with assertions.
Attempted to mitigate that by determining what filter was returned first and then adjusting the assertion accordingly to check the corresponding applicant filter model. 
1. Run the test locally a bunch, confirm it succeeds
Snippet to run a bunch locally here
```
for i in {1..30}; do docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/ApplicantFilterTest.php"; done
```
> [Tooling] Resolve testQueryRelationships issue

- apps/web/public/restricted.html
🤖 Resolves #6705 
This branch adds the charset to the head of the restricted page so that the accented characters are rendered properly.
1. Build the app or just manually copy the page from public to dist
2. Visit /restricted.html
> [Bug] Add charset to restricted page

- api/config/rolepermission.php
- api/tests/Feature/RolePermissionTest.php
🤖 
Resolves #6404
Resolves #6406
Updates permissions to solve the error on the users page. 
Given user and applicant models overlap heavily, if you can view any user, you should be able to view any applicant model. 
Checked in 
Needed for the query 
1. Navigate to `en/admin/users` as `platform@test.com`
2. Observe select ability functions
3. Click on edit for a user
4. No error toast about authorization should appear
Run `php artisan db:seed --class=RolePermissionSeeder`
> [Bug] Platform admin applicant permission added

- .github/workflows/e2e-tests.yml
- api/database/seeders/CiSeeder.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/TeamSeederLocal.php
- maintenance/scripts/setup.sh
- package.json
🤖 Resolves #5592 
Adds an option to the `setup.sh` script to run different scripts in CI.
You can no pass options to the command, you cna 
```sh
$ docker-compose run --rm maintenance bash setup.sh -h
Setup the project and your environment.
Syntax: setup.sh [-h|c]
-h   Show this help message.
-c   Setup the environment for CI.
```
1. Run `docker-compose run --rm maintenance bash setup.sh`
2. Confirm it setups the env as usual but in dev mode
3. Run `docker-compose run --rm maintenance bash setup.sh -c`
4. Confirm minimal seeders are run (`CiSeeder.php`) and app is build in prod mode
> [Feature] Adjust setup script for CI

- turbo.json
🤖 Resolves #6176 
This busts the turbo cache when changing our `.env` files.
1. Run `npm run build` x3 (cache is not full after a `turbo.json` change)
2. Confirm you still get full turbo
3. Flip one of our env variables in the `.env` file
4. Re-run `npm run build`
5. Confirm it is a fresh build
> [Chore] Fix turbo `.env` cache

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx
🤖 Resolves #6742.
This PR updates request response time period in English and French.
2. Navigate to `/search/request/test`
3. Ensure copy reads: You will receive a follow up on your request within the next 5 to 10 business days. 
5. Ensure copy reads: Vous recevrez un suivi sur votre demande dans 5 à 10 jours ouvrables.
> [Copy] Updates request response time period

- package-lock.json
- packages/storybook-helpers/main.ts
- packages/storybook-helpers/package.json
- packages/ui/src/components/Switch/Switch.stories.tsx
🤖 Resolves #6280 
This adds the `@storybook/addon-a11y` to storybook to help surface accessibility issues earlier in development.
> **Note**
> Something that is a little annoying is that it scans `#storybook-root` which itself has a violation that sometimes shows up 🤦‍♀️ 
This surfaced some issues with not-so-common components and new tickets were created for each one:
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6766
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6765
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6764
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6763
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6762
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6761
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6760 …
> [Feature] Add accessibility addon to storybook

- packages/ui/src/components/TreeView/TreeView.stories.tsx
🤖 Resolves #6768 
Adds `faker.seed(0)` to the `<TreeView />` story to stabilize the copy during chromatic snapshots.
> **Note**
> Actually not certain how to test this 🤔 Maybe restart storybook a few times and confirm the copy does not change with each run? 🤷‍♀️
> [Bug] Fix `<TreeView />` story faker seed

- apps/web/src/pages/Auth/RegisterPage/RegisterPage.tsx
- packages/ui/src/components/Link/ExternalLink.tsx
- packages/ui/src/components/Link/useCommonLinkStyles.ts
🤖 Resolves #6766 
- Updates the `linkColorMap.secondary` colour and hover colour to fix colour contrast issues on white backgrounds.
- Changes the "Login in instead" link on the Register page to `type=button` to match Login page styling.
1. Go to Register page and ensure the link has sufficient colour contrast. Simple way is to running the axe DevTools extension.
> [Accessibility] External link color contrast

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/EditPoolPage/components/DuplicateDialog.tsx
🤖 Resolves #6794
- Updates duplicate dialog title to "Duplicate job poster", and action button in dialog.
1. Go to Pools table and select "Edit" on any pool.
2. Scroll to bottom and ensure copy change is correct.
3. Open dialog by selecting "Duplicate job poster" and view the title and button copy is correct.
> [Copy] Change "Duplicate this pool" to "Duplicate job poster"

- packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
🤖 Resolves 6763
- Fixes all color contrast errors on ToggleGroup buttons.
- Note: The `primary` color needed black font to pass. Otherwise, all saturated colors have black font.
1. Go to storybook and view ToggleGroup story and ensure there are no violations.
> [Accessibility] Fix color contrast errors on all toggle group buttons

- packages/ui/src/components/ToggleSection/ToggleSection.tsx
🤖 Resolves #6764 
- Removes `aria-selected` attribute from div elements in `<ToggleSelection />, which is only allowed on elements with specific roles (eg. tab, row, etc.)
1. Use Storybook or go to `http://localhost:8000/en/applications/{applicationId}/profile` (You will need to turn on APPLICATION_REVAMP feature flag)
2. Ensure aria errors do not appear.
> [Accessibility] Remove aria-selected attribute from ToggleSelection

- apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx
🤖 Resolves #6760.
This PR changes text colour from `primary` to `primary.dark` on an element that had insufficient contrast.
2. Open the "User profile story 5" story
3. Confirm the text in DEI is not at the minimum contrast requirement (4.5:1)
> [a11y] Changes primary to primary.dark

- api/app/Models/User.php
🤖 Resolves #6826
Resolve the search quirk for names when all columns is selected. 
Just adjusted general search scope to be a composite of other scopes. 
1. Navigate to /users, try searching
2. Navigate to the view candidates page for a pool with candidates, try searching
> [Bug] General searching and name

- packages/ui/src/components/Chip/Chips.tsx
🤖 Resolves #6903 
Removes `ul` padding from the `Chips` component.
2. Confirm chips are not indented
> [Bug] Fix chips padding

- packages/ui/src/hooks/useCommonButtonLinkStyles.ts
🤖 Resolves #6907 
Prevents text links from override font size.
1. Build the app `npm run dev`
2. Confirm links that are used within text match their siblings
3. Confirm other links are unaffected
> [Bug] Fix text link font size

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestPage/RequestPage.tsx
- apps/web/src/pages/SearchRequests/SearchPage/SearchPage.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchHeading.tsx
🤖 Resolves #6175 
Copy change on Search page Title and Subtitle
Note that I also changed Request page for consistency 
New Copy : 
Search the GC Digital Talent database
About the GC Digital Talent database
This talent database is open to most departments and agencies. Candidates in the database vary from just starting their career to seasoned professionals with several years of work experience. There are several ongoing recruitment processes, which means new candidates are being added every week.
- Verify Search page & request page title
> [feature] Update search page title

- packages/ui/src/hooks/useCommonButtonLinkStyles.ts
🤖 Resolves #6943
Fixes a typo introduced by the button and link refactor.
I'm just bad at typing and never noticed hydrogen yelling at me in the console 🤦‍♀️ 
1. Build the app `npm run dev`
2. Confirm no hydrogen errors
3. Confirm buttons have the `copy` font-size unless the mode is set to `text`
> [Fix] Fixes typo for button `font-size`

- .github/dependabot.yml
Unlimited, not an option 🤷 
Surely 50 ought to suffice?
> Dependabot re-add limit

- apps/web/src/pages/Applications/ApplicationContext.tsx
- apps/web/src/pages/Applications/ApplicationLayout.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/utils/applicationUtils.ts
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #6977 
Updates the formatted pool title to not longer include stream and classification when in an application and publishing group is set to IAP.
1. Build app `npm run dev`
2. Navigate to an application for any pool that **_does not_** have IAP publishing group
3. Confirm title **_does_** include stream and classification
4. Navigate to a pool **_within_** the IAP publishing group
5. Confirm the title **_no longer_** contains stream and classification
> [Fix] Remove stream and classification from IAP pool title

- apps/web/src/components/Layout/IAPLayout.tsx
- apps/web/src/components/Layout/Layout.tsx
- apps/web/src/components/NavMenu/IAPNavMenu.tsx
- apps/web/src/lang/fr.json
- packages/ui/src/components/Link/MenuLink.tsx
🤖 Resolves #6886 
Updates the IAP navigation items.
Changes "Home" to "IT Apprenticeship Program for Indigenous Peoples" and adds:
- GC Digital Talent
- Login/Logout
- Register
3. Confirm both IAP and GCDT links appear along with login/register
4. Login
5. Navigate back to `/indigenous-it-apprentice`
6. Confirm Login / Register are now Logout
> [Feature] Update IAP navigation items

- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/config/constants.php
- api/tests/Feature/PoolCandidateSearchTest.php
🤖 Resolves #6986 
Resolves the issue with filtering by suspended selection. 
Read the issue comments for details starting here https://github.com/GCTC-NTGC/gc-digital-talent/issues/6986#issuecomment-1593742001
But yeah, appears `whereDate()` does not work for this and I followed how draft was scoped by just using `where()`
I also adjusted other instances of filtering for suspended from `whereDate` to `where` since it seems like it'd obviously be not working well there either and it seems straightforward a fix. 
1. You cannot replicate the issue Brinda
2. Suspended candidates filtering works not just for the pool candidate table, but elsewhere with availability scopes like the search page. 
3. And tests pass
> [Bug] Suspended filtering fix

- apps/web/src/pages/Pools/BrowsePoolsPage/components/PoolCard/PoolCard.tsx
🤖 Resolves #6952 
This adds `aria-hidden="true"` to the recruitment flag on the browse jobs page.
The flag was being read to screen reader users before the heading, causing some users confusion. Since the content of the flag also appears in the title, we have opted to hide it from the accessibility tree since no information is lost in doing so.
2. Navigate to `/browse/pools`
3. Inspect the flag on pool cards in the accessibility tree
4. Confirm it is ignored
5. Test using a screen reader
6. Confirm the contents of the flag are ignored
> [Fix] Hide recruitment flag from accessibility tree

- .vscode/project-words.txt
- apps/e2e/cypress/e2e/admin/pool-candidate.cy.js
- apps/e2e/cypress/e2e/admin/pools.cy.js
- apps/e2e/cypress/e2e/talentsearch/submit-application.cy.js
- apps/web/src/components/ExperienceFormFields/AwardFields.tsx
- apps/web/src/components/ExperienceFormFields/CommunityFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationStatusForm/ApplicationStatusForm.test.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationStatusForm/ApplicationStatusForm.tsx
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.test.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ExtendDialog.tsx
- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.test.tsx
- apps/web/src/pages/Users/UserInformationPage/components/AddToPoolDialog.tsx
- apps/web/src/pages/Users/UserInformationPage/components/ChangeDateDialog.tsx
- packages/forms/src/components/DateInput/ControlledInput.tsx
- packages/forms/src/components/DateInput/DateInput.tsx
- packages/forms/src/components/DateInput/utils.ts
- packages/forms/src/components/Field/Fieldset.tsx
- packages/forms/src/components/Field/Legend.tsx
- packages/forms/src/components/Input/Input.tsx
- packages/forms/src/index.tsx
- packages/jest-helpers/src/index.ts
- packages/jest-helpers/src/utils/date.ts
🤖 Resolves #6352 
Replaces the default `input[type=date]` with our custom date input and prevents using `input[type=date]` in the future.
Some layouts were slightly adjusted to accommodate the larger inputs.
While testing this, I noticed a bug with our date formatting. If you select August 1st, it is formatted as July 31st. The date stores in the database correctly but rendered incorrectly. If you are testing and notice this, it does seem to be a bug with formatting and not the date input itself.
2. Navigate to every experience form and test the date inputs, confirming they only allow month and year
3. Navigate to a pool edit page in the admin and test the following:
- Closing …
> [Feature] New date picker

- apps/web/src/components/ExperienceFormFields/ErrorSummary.tsx
- apps/web/src/pages/Applications/ApplicationResumeAddPage/components/AddExperienceForm.tsx
- apps/web/src/pages/Applications/ApplicationResumeEditPage/components/ExperienceEditForm.tsx
- packages/forms/src/components/ErrorSummary.tsx
🤖 Resolves #6950 
This fixes a bug where the error summary was not being focused on the application experience forms.
This changes 3 distinct things:
- Removes the summary from the natural tab order only allowing us to focus programmatically
- Prevents the experience forms from focusing the first invalid input on submission
- Adds the missing error summary to the add experience form
2. Start an application and continue to the resume step
3. add an exerience
4. Submit form with errors
5. confirm error summary appears and focus is brought to it
6. Repeat steps 3-5 on the edit form
> [Fix] Focus error summary on experience forms

- apps/web/src/components/ExperienceCard/AwardContent.tsx
🤖 Resolves #7000 
Resolve the date inconsistency for award experiences. 
I just mimicked how dates were rendered for the other experiences on the same page, plus, since you couldn't pick the day itself the card shouldn't display a day. 
It also seems like we already had all the needed functions present. 
Used `formattedDate()` to align with other experiences
1. Navigate to `/resume-and-recruitments`
2. Create an award experience and assert the date displayed is correct
> [Bug] AwardContent date displayed fix

- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
- packages/ui/src/components/Loading/Loading.tsx
- packages/ui/src/components/Pending/Pending.tsx
🤖 Resolves #6951 
This makes the loading indicator use `aria-live=polite` since the value of `assertive` was causing it to interrupt the toasts.
2. Turn on your choice of AT (preferably multiple)
3. Navigate to a form and save it
4. Confirm the toast is announced without being interrupted
> [Bug] Fix loading alert interrupting toasts

- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #6948 
Removes the section from the download view. 
1. Navigate to `/en/admin/pools/:id/pool-candidates`
2. Select 1 or more candidates then click "Download Profiles" 
3. Affirm the section is no longer present
Before
After
> [Feature] Remove pool candidate details section from print

- apps/web/src/pages/Applications/ApplicationProfilePage/components/WorkPreferences/Display.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/components/WorkPreferences/FormFields.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/hooks/useDirtyFields.ts
🤖 Resolves #7024 
Hides work duration, setting it to `true` when within an IAP application.
1. Build npm run dev
2. Navigate to /indigenous-it-apprentice
3. Click "Apply now"
4. Continue to the profile step
5. Confirm work duration does not appear in the work preferences section
6. Click "Edit" on the work preferences section
7. Confirm there is no radio group  for work duration
8. Submit and confirm it submits with the following:
```js
positionDuration: [
"PERMANENT",
"TEMPORARY"
]
```
> [Feature] Hide work duration in IAP application

- packages/ui/src/components/Accordion/styles.ts
🤖 Resolves #6898 
Swap the subtitle colour to the requested `black.light` 
1. Navigate to the search page
2. No colour contrast issues should be left on the page
> [Accessibility] Accordion subtitle colour

- apps/web/src/components/Dialog/IapContactDialog.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationLayout.tsx
- apps/web/src/pages/Auth/LoginPage/LoginPage.tsx
- apps/web/src/pages/Auth/RegisterPage/RegisterPage.tsx
🤖 Resolves #7023 
This adds a dialog with contact information to the IAP application process
3. Click "Apply now"
4. Confirm the "Contact us" button appears below the stepper and opens a dialog with the appropriate content
5. Navigate to `/browse/pools`
6. Start an application for any pool other than the IAP pool
7. Confirm the button does not appear
> [Feature] IAP Contact Dialog

- api/app/GraphQL/Mutations/DuplicatePool.php
- api/app/Models/Pool.php
- api/database/factories/PoolFactory.php
- api/database/migrations/2023_06_22_205656_drop_pool_key_column.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/PoolSeeder.php
- api/database/seeders/PoolSeederUat.php
- api/database/seeders/TeamSeeder.php
- api/database/seeders/TeamSeederLocal.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/ApplicantFilterTest.php
- apps/web/src/pages/SearchRequests/SearchPage/searchPageOperations.graphql
🤖 Resolves #7077
The issue was caused by the DuplicatePool mutation, which appended a timestamp to the end of the original pool's key to keep it unique. However, it did this even when the original key was null (which is bascally always), creating a key which starts with underscore. That isn't a valid KeyString, so GraphQL crashed if you requested the key value for Pools (which we did on the Talent Search page).
I initially fixed the bug in DuplicatePool.php. However... we're not using Pool.key at all. For most of our pools (in production and UAT) it's null anyway. We have no intention of making use of it - publishing group has replaced its original purpose.
So I've removed Pool.key entirely. Good riddance!
To be thorough, we want to test that the pool interactions still work without keys. …
> [Fix] Remove Pool keys, which weren't used and could be invalid

- apps/e2e/cypress/e2e/talentsearch/profile-workflows.cy.js
- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/components/UserProfile/ProfileSections/WorkLocationSection.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationProfilePage/components/WorkPreferences/Display.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/components/WorkPreferences/utils.ts
- apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.test.tsx
- apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx
🤖 Resolves #6829.
This PR replaces the terms **Location specifics** and **Location exemptions** with **Work location exceptions** on the application and profile.
1. Navigate to `/users/:userId/profile#work-location-section`
2. Observe **Work location exceptions** copy
4. Observe **Exceptions relatives au lieu de travail** copy
5. Navigate to `/users/:userId/profile/work-location/edit`
6. Observe **Work location exceptions* label
7. Switch to French
8. Observe **Exceptions relatives au lieu de travail** label
9. Navigate to `/applications/:applicationId/profile`
10. Observe **Work location exceptions** label
11. Switch to French
12. Observe **Exceptions relatives au lieu de …
> [Copy] Updates Work location exceptions copy

- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationProfilePage/components/LanguageProfile/ConsideredLanguages.tsx
- apps/web/src/pages/Profile/LanguageInfoPage/components/ConsideredLanguages.tsx
🤖 Resolves #7104.
This PR removes repeated copy from the `ConsideredLanguages` components.
1. Navigate to `users/:userId/profile/language-info/edit`
2. Observe "You can find out your levels" copy
3. Navigate to `/applications/:applicationId/profile`
4. Click **Edit language profile**
5. Observe "You can find out your levels" copy
> [Bug] Removes `ConsideredLanguages` repeated copy

- apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
🤖 Resolves #7014
This branch separates the query for the experiences on the skill requirements application page.  It mirrors the component on the resume page now.
It's not clear to me why cache invalidation isn't working on this page when the experiences are updated.  My guess is that it might be due to "User" and "Applicant" being different models.  I opened  #7099 to address that.
1. Build the app.
2. Run through the recreation steps in the issue.
> [Fix] Separate query for experiences

- apps/web/package.json
- hydrogen.config.json
- package-lock.json
- package.json
Updates Hydrogen to patch `2.0.2`. Adjustments you'll notice right away:
- More concise console output
- No more timer settings (timers are inline with their respective output and are hidden if the output is hidden)
- Typography theme settings now have options for individually specified `line-height` values
- This will cause a larger visual diff because titles will all adjust ever so slightly to use tighter line-heights
Bonus things:
- @petertgiles and @vd1992 mentioned properly returned exit codes, so you'll see the build fail if Hydrogen completes with errors now
You can learn more about the full release here: https://github.com/hydrogen-css/hydrogen/releases/tag/v2.0.2
- Hydrogen compiles same as ever
- Hydrogen's console output indicates v2.0.2
- There is a visual diff for headings
> [Dep] Hydrogen 2.0.2

- apps/web/src/pages/Home/IAPHomePage/Home.tsx
🤖 Resolves #7078.
This PR fixes an image of feathers that were overlapping text to make it less legible.
1. Navigate to `/indigenous-it-apprentice`
2. Reduce the page width until the first copy heading appears below the image
3. Confirm the feathers do not obscure the heading in any of the five languages
> [Bug] Fixes obscured text

- apps/e2e/cypress/e2e/admin/pool-candidate.cy.js
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/Table/ClientManagedTable/TableViewItemButton.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #7105 
This adds the candidate's name as an `aria-label` to improve the context of the link when viewed in isolation.
We had hidden text (which has known issues) so we needed to add an `aria-label` arg to the view accessor helper to support this.
> **Note**
> You may need to clear the filters to get both a "View profile" and "View application" link to appear to fully test this implementation.
2. Navigate to the pool candidates table `/admin/pools/{poolId}/pool-candidates
3. Inspect both the "View application" and "View profile" links within the accessibility tree
4. Confirm they are unique and include the candidates name
> [A11y] Improve Pool Candidate View Link Context

- apps/web/src/components/Dialog/IapContactDialog.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx
- apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
- apps/web/src/pages/Auth/LoginPage/LoginPage.tsx
- apps/web/src/pages/Auth/RegisterPage/RegisterPage.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
- packages/eslint-config-custom/index.js
🤖 Resolves #7113.
This PR replaces instances of "IT Indigenous Apprenticeship Program" with "IT Apprenticeship Program for Indigenous Peoples" as well as the French equivalent translations. It also adds an eslint rule that forces "Indigenous Apprenticeship Program" copy to error (h/t @petertgiles).
1. Navigate to `/en/login-info?from=/en/indigenous-it-apprentice&personality=iap`
2. Observe **IT Apprenticeship Program for Indigenous Peoples** text in first paragraph
3. Navigate to `/en/register-info?from=/en/indigenous-it-apprentice&personality=iap`
4. Observe **IT Apprenticeship Program for Indigenous Peoples** text in first paragraph
5. Ensure no instances of **Indigenous Apprenticeship Program** …
> [Bug] Fixes name of IAP

- packages/forms/src/components/DateInput/DateInput.test.tsx
- packages/forms/src/components/DateInput/DateInput.tsx
🤖 Resolves #7137 
This branch updates the min and max validation of the DateInput component to not fail on null inputs.
#7079 hasn't been merged yet so I can't complete the last AC.  Whichever PR gets merged first, I'll update the second one to match.
1. Run the new jest tests
> [Fix] Adjust DateInput min and max validation

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/BrowsePoolsPage/components/OngoingRecruitmentSection/OngoingRecruitmentSection.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/messages.ts
🤖 Resolves #6913.
This PR removes the word buckets from the instructions for section with ongoing pool advertisements.
The French equivalent copy does not need to be changed. This PR **does not** make changes to tc-report, which does use the term buckets, as it is out of scope.
1. Navigate to`/browse/pools`
2. Observe "passive recruitment processes that allow us"
> [Copy] Removes term buckets

- apps/web/src/pages/Profile/ResumeAndRecruitmentPage/components/AddExperienceDialog.tsx
🤖 Resolves #7158 
This branch updates the margin for the grid in the _Add experience_ dialog.
This was a regression picked up during the Hydrogen 2.0.2 upgrade.  It seems the built-in flex grid margins changed and the explicit margin in the same element overrode them.  I just removed the explicit margin.
https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/85818a0d-5116-4271-a339-c87bacc23d72
1. Build the app, log in, navigate to the _Résumé and recruitment_ page (or open the _Résumé and recruitment_ story)
2. Click the _Add experience_ button to open the dialog
> [Fix] Fix flex grid margin

- api/app/Listeners/StoreApplicationSnapshot.php
- api/tests/Feature/SnapshotTest.php
🤖 Resolves #6946 
Stop collecting every pool candidate in the snapshot. 
Just filtering pool candidates first before the main resource collection chain. 
As well, update the snapshot test for this. 
1. Assert you cannot replicate what was defined in the issue body 
2. Tests pass
> [Bug] Snapshots and pool candidate models

- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/components/UserProfile/ProfileSections/GovernmentInformationSection.tsx
🤖 Resolves #7103 
This branch adds a null state for the priority number.
I ended up going with "Not provided" instead of "(Number not provided)" for consistency.  The former was already in use for the new inline forms.
1. Build the app
2. Create or edit a user with priority entitlement but no priority number
3. Submit an application
4. Check
- Profile page
- Application _Review your profile_ page
- Admin _View user_ page
- Admin _View application_ page
- Admin "printed" user page
- NOT the CSV - I figured the tabular form is clear enough
- Any spots missed?
> [Feature] Add null state for priority number

- apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.js
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
🤖 Resolves #7073 
This replaces the region `Multiselect` field with a `Checklist` field to improve accessibility.
Assistive technologies were having trouble using our multiselect field so we are replacing it with checklists for now.
3. Confirm work location's regions input is a checklist
4. Confirm it matches [the provided mockup](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7073#issuecomment-1609616741)
5. Confirm it still functions as expected
> [A11y] Replace Multiselect with Checklist for Region input

- apps/web/src/components/SkillPicker/SkillPicker.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/components/PersonalInformation/PersonalInformation.tsx
- apps/web/src/pages/Applications/ApplicationProfilePage/components/WorkPreferences/WorkPreferences.tsx
- apps/web/src/pages/Profile/AboutMePage/components/AboutMeForm/AboutMeForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- packages/forms/src/components/BasicForm.tsx
🤖 Resolves #7009 
- Sets all form modes within the application to `onSubmit` and only validate on or after submission.
> Background: this is to keep the new DateInput component from triggering a validation error before the user has entered their values into all three inputs to form a complete date.
1. Ensure all `useForm` mode overrides are using onSubmit
2. Ensure validation happens on or after submission but **not** before
3. Ensure error summary still functions as expected
4. Ensure form caching still functions as expected
> [Bug] All basic forms `mode` to on submit

- api/app/Models/PoolCandidate.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/usePoolCandidateCsvData.tsx
- apps/web/src/components/SearchRequestTable/SearchRequestsTableApi.tsx
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationStatusForm/ApplicationStatusForm.tsx
- apps/web/src/pages/Users/UserInformationPage/UserInformationPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/uiMessages.ts
- packages/ui/src/components/Spoiler/Spoiler.stories.tsx
- packages/ui/src/components/Spoiler/Spoiler.tsx
- packages/ui/src/index.tsx
🤖 Resolves #6818 
Adds a notes column to the pool candidates table, in a new `<Spoiler />` component, allowing users to search by it.
Added a new component to show partial content with a "read more" button to show the full text.
```tsx
export interface SpoilerProps {
// Accessible name for the "read more" button
linkSuffix: string;
// Text to be truncated to read more
text: string;
// Character count before cutoff
characterCount?: number;
}
```
2. Navigate to the pool candidate table `/admin/pools/{poolID}/pool-candidates
3. Confirm "Notes" is hidden by default
4. Confirm you can show it using the columns dialog
5. Confirm you can open the notes field to read the full text
6. …
> [Feature] Add notes to pool candidates table

- apps/web/src/components/ExperienceCard/ExperienceCard.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #7170.
This PR updates the skill count on the `ExperienceCard` for plural cases in English and French.
1. npm run intl-compile
2. npm run storybook
3. View *Award Experience Card* story
4. Open storybook controls
5. Open `experience` > `skills`
6. Remove skills one at a time
7. Observe string *2 featured skills*
8. Observe string *1 featured skill*
9. Observe string *0 featured skills*
10. Refresh window
11. Switch locale to FR
12. Open `experience.skills` array
13. Remove skills one at a time
14. Observe string *2 compétences mises en évidence*
15. Observe string *1 compétence mise en évidence*
16. Observe string *0 compétence mise en évidence* …
> [Bug] Accounts for plural on `ExperienceCard` skill count

- apps/web/src/components/PoolCandidatesTable/PoolCandidateTableFilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/usePoolCandidateCsvData.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #6354.
This PR changes the column label for `priority` on the Pool Candidates table from **Priority** to **Category**.
Although it was not in the acceptance criteria, I also changed the column label for the CSV in `usePoolCandidateCsvData` since this is a corresponding value.
1. View a pool candidates table page: `/admin/pools/:poolId/pool-candidates`
2. Observe rendered column is **Category** and not **Priority**
3. Open Filters dialog
4. Observe rendered column is **Category** and not **Priority**
5. Open Columns dialog
6. Observe rendered column is **Category** and not **Priority**
> [Feature] Changes Pool Candidates table Priority to Category column label

- api/database/seeders/DepartmentSeeder.php
- api/graphql/schema.graphql
🤖 Resolves #6642
Renames the department in the seeder. The rest of the work is updating through the admin dashboard. 
Updating a department was broken, validation would fail due to the `department_number` constraint even if all you were changing was the name. Normally this is resolved by adding ignoring in validation classes.
However, creating a department has the full validation message that informs you of what you did wrong, and the constraint on `department_number` in table of uniqueness will prevent updating to a number in use.
Given that updating a department number is unlikely to happen much if at all. And that the validation of department number doesn't just involve adding the validation class, but also updating the mutation and form to pass in an id at `UpdateDepartmentInput.id` …
> [Bug] Rename Foreign Affairs and department update issue

- apps/web/src/components/SearchRequestFilters/FilterBlock.tsx
- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/components/SearchRequestFilters/index.ts
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx
🤖 Resolves #7235.
This PR wraps the **government email** value in a `mailto` link on the admin view of a request.
The `FilterBlock` component being used was deprecated, so I referenced a nearly identical non-deprecated one instead. I also moved the non-deprecated `FilterBlock` component into its own file so it could be reused and referenced cleanly.
1. Navigate to `/admin/talent-requests/:requestId`
2. Observe clickable mailto link following **Government Email**
> [Feature] Adds `mailto` link to government email value

- api/app/GraphQL/Mutations/MarkNotificationAsRead.php
🤖 Resolves #7240 
I missed a linter warning in #7233.  This branch updates the dismiss notification mutation to be a little safer.
1. Review code
2. Run phpunit tests
3. (optional) - review AC in  #7233
> [Fix] Fix linter warning in notifications

- apps/web/src/components/NavMenu/NavMenu.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #7275 
Updates the name of the navigation landmark that contains account based actions.
Some users were having issues finding these links easily, we believe that was due to it having a very generic name. This changes the name to hopefully make it easier to locate for AT users.
2. Inspect the nav menu on the right side
3. Confirm the accessible name is "Account menu"
4. Confirm that name is available in the landmark list for ATs
> [a11y] Update right nav landmark name

- apps/web/src/components/Table/ClientManagedTable/Table.tsx
🤖 Resolves #7274 
Removes the `for`, `id` and `title` attributes from the client tables column visibly checkboxes.
These attributes were causing issues for AT users since:
- `for` and `id` were invalid since they contained spaces which indicates multiple values
- `title` attribute is discouraged and causes issues with ATs
Since the input is wrapped in a label, `for` and `id` were doing nothing but confusing the ATs. Since they were confused by multiple values in these attributes it started falling back eventually landing on the `title` attribute. Since the `title` was "Toggle Column Visibility" for all, the users had no idea what column they were toggling and never heard their current state.
All attributes were removed as unnecessary since wrapping an `input` with a `label` automatically …
> [Fix] Remove invalid attributes from column visibility checkboxes

- api/tests/Feature/SnapshotTest.php
🤖 Resolves #7204
This branch (hopefully) fixes the snapshot test that has been failing intermittently.  The solution was to use `array_values` to reindex the array back at zero after removing one of the elements.  I left in the more explicit pool and candidate initialization since I feel it makes the test more clear.  I don't think it actually fixed anything though.
I'm actually finding it really difficult to replicate this failure locally.  This is solution seems pretty stable.  You can check the previous commit before I removed the logging:
https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/5546440323
1. Review the code
2. Review the CI runs
> [Fix] Fix snapshot test

- apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.js
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchResultCard.tsx
🤖 Resolves #6174.
This PR changes the message for total estimated matching candidates in pool to include the word **approximately**.
1. Navigate to `/search`
2. Observe cards under **Results: X matching candidates** heading
3. Ensure card renders **There is approximately 1** (for one result) or **There are approximately 2** (for greater than one result)
5. Ensure card renders **Il y a environ 1** (for one result) or **Il y a environ 2** (for greater than one result)
> [Copy] Changes message for total estimated matching candidates in pool

- apps/web/src/lang/fr.json
🤖 Resolves #7291.
This PR fixes an i18n string which contained a variable that had been translated into French by mistake.
2. Navigate to a pool poster `/fr/browse/pools/:pool-id`
3. Go to _Postulez maintenant_ heading
5. Ensure paragraph following heading is in French
> [Bug] Fixes over translated variable

- api/database/factories/PoolCandidateSearchRequestFactory.php
Oops, I merged in #7312 without realizing that a factory change I made would make tests fail somewhat regularly
Rather than always generate the simulated old requests, null for new fields, change it to a stateful function you can call in the seeder when you need it. Such as to observe copy changes for null states when you want to. 
The test failures stemmed from needing the fields in question to be non-null but they were generated null. 
1. Tests pass
> Fix ApplicantFilterTest

- apps/web/src/pages/Classifications/components/ClassificationTable.tsx
- apps/web/src/pages/SkillFamilies/components/SkillFamilyTable.tsx
- apps/web/src/pages/Skills/components/SkillTable.tsx
🤖 Resolves #4154 
Hides the ID column by default for tables that included them.
2. Navigate to the index pages in `/admin`
3. Confirm that ID columns do not appear by default but can still be turned on
> [Debt] Hide admin table Id columns

- packages/ui/src/components/DropdownMenu/DropdownMenu.stories.tsx
- packages/ui/src/components/DropdownMenu/DropdownMenu.tsx
🤖 Resolves #7351 
Updates the colour of dropdown menu items to fix colour contrast issues. Also, makes the story open by default so we can detect errors easier with the storybook a11y addon.
2. Navigate to the "Dropdown Menu" story
3. Confirm it is open by default
4. Confirm colours have changed and meet colour contrast ration of 4.5:1
> [Fix] Dropdown menu item colour contrast

- apps/web/src/components/PoolCandidatesTable/usePoolCandidateCsvData.tsx
- apps/web/src/pages/Users/IndexUserPage/hooks/useUserCsvData.tsx
- apps/web/src/utils/csvUtils.tsx
🤖 Resolves #7213 
Updates the Indigenous column in CSV downloads to display the communities rather than yes or no.
2. Navigate to the pool candidate and user tables
3. Download CSV of users for each table
4. Confirm both show Indigenous communities in the CSV (empty if none)
[users_2023-07-25T13_57_00.072Z.csv](https://github.com/GCTC-NTGC/gc-digital-talent/files/12162001/users_2023-07-25T13_57_00.072Z.csv)
[pool_candidates_2023-07-25T13_47_59.744Z - pool_candidates_2023-07-25T13_47_59.744Z.csv](https://github.com/GCTC-NTGC/gc-digital-talent/files/12162003/pool_candidates_2023-07-25T13_47_59.744Z.-.pool_candidates_2023-07-25T13_47_59.744Z.csv)
> [Feature] Add Indigenous communities to CSV

- api/app/Models/User.php
- apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx
- apps/web/src/validators/profile/governmentInformation.ts
🤖 Resolves #7220 
This makes the priority number required when the user has selected "Yes" to priority entitlement.
This change occurs in the application and profile pages but **_not_** create account.
2. Login with a new account
3. Confirm priority number is not required when selected "yes" to priority entitlement
4. Navigate to your profile page
5. Confirm Confirm priority number is required when selected "yes" to priority entitlement 
6. Start and application and continue to the profile step
7. Confirm priority number is required when selected "yes" to priority entitlement
> [Fix] Make priority number required

- apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
🤖 Resolves #7168
Resolving the validation quirk present on `/en/applications/:id/skills`
The validation done was different from the one used by the stepper, I changed the page to use that validator instead. 
That one ensured skill details was also filled. 
1. I managed to replicate the issue by doing the steps in the picture
2. Attempt to replicate the bug by doing that, it should not let you proceed until you update all the skills to have details.
> [Bug] Application skills page validation

- apps/web/.eslintrc.js
🤖 Resolves #7436
Fixes a bug with the path resolution for vscode eslint server.
1. Run lint, confirm it works
2. Confirm VSCode highlights linting errors and can fix them
> [Fix] Fix eslint no-unused-modules path for `apps/web`

- .vscode/project-words.txt
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/Home/IAPHomePage/components/LanguageSelector.tsx
🤖 Resolves #7381.
This PR updates the spelling of the name of the language in the language itself from Mi'kmaq to Mi'kmaw.
1. Navigate to `/indigenous-it-apprentice/`
2. Click on select element **This page is available in Indigenous languages**
3. Verify spelling of Mi'kmaw option
5. Click on select element **Cette page est accessible en langues autochtones**
6. Verify spelling of Mi'kmaw option
> [Copy] Updates Mi'kmaq to Mi'kmaw

- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql
- api/app/Http/Resources/PoolCandidateResource.php
- api/app/Http/Resources/PoolResource.php
- api/tests/Feature/SnapshotTest.php
- apps/web/src/pages/Profile/ProfilePage/ProfilePage.stories.tsx
- apps/web/src/pages/Profile/ProfilePage/profileOperations.graphql
- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/TrackApplicationsCard.tsx
- packages/fake-data/src/fakePoolCandidateTypes.ts
- packages/fake-data/src/fakePoolCandidates.ts
- packages/fake-data/src/fakeUsers.ts
🤖 Resolves #7323 
This branch adds a PHPUnit test to ensure the that the query that makes the profile snapshots stays in sync with the regular query for displaying the profile.  It also syncs up the existing drift between the two queries by reordering fields and adding any missing between the two.  
I'm doubtful that _everything_ in the queries is necessary ~but I figured removing anything was out of scope for this PR~.  I needed to remove some extra user fields in [remove redundant user fields](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7447/commits/dca71623946f0366ebf2ba6cd40730a695817338) or the JSON would have a loop in it.  I'm not clear when those fields were added or why since it's older than the file history can retrieve.  They seem redundant since `User` is the top-level …
> [Feature] Snapshot test

- packages/eslint-config-custom/index.js
- packages/forms/.eslintrc.js
- packages/toast/.eslintrc.js
- packages/tooling/.eslintrc.js
- packages/ui/.eslintrc.js
🤖 Resolves #7452 
This disabled the `no-unused-modules` eslint rule in `packages/*`.
Since we extend a non-conventional rule filename (`index.js`), the rule has an issue with `ignoreExports` config. We have decided to disable this rule temporary until we can fix or work around that breaking issue.
1. Open a `.tsx` file in `packages/*`
2. Force an eslint error
3. Confirm VSCode flags the error and can fix it (if it is a fixable error)
> [Fix] Disable `no-unused-modules` rule

- apps/web/src/components/PoolCandidatesTable/usePoolCandidateCsvData.tsx
- apps/web/src/components/Profile/components/LanguageProfile/Display.tsx
- apps/web/src/components/Profile/components/LanguageProfile/utils.ts
- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/components/UserProfile/ProfileSections/LanguageInformationSection.tsx
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/Profile/LanguageInfoPage/components/LanguageInformationForm/LanguageInformationForm.tsx
- apps/web/src/pages/Users/IndexUserPage/hooks/useUserCsvData.tsx
🤖 Resolves #7385
Updates the labels as requested. 
Changed the label that also lists the three as I thought that was straightforward and should be in sync with the inputs. 
Also changed one place to reuse the labels from the utils file. 
1. Navigate to `/en/users/:id/profile#language-section`
2. Play with updating the language levels, observe the copy, and switch to French to check as well
`/fr/admin/users/:id/profile#language-section`
> [Copy] Update language evaluation labels

- apps/web/src/components/Profile/components/FieldDisplay.tsx
🤖 Resolves #7390 
This branch switches the FieldDisplay component to use a div instead of a p.  This fixes the "ul cannot descend from p" warning.
1. Rebuild the app in dev mode.
2. Open your browser console.
3. Navigate to the _Profile information_ page and observe no warnings.
4. Navigate to the _Review your profile_ step in an application and observe no warnings.
> [Fix] Switch FieldDisplay to div

- apps/web/src/components/UserProfile/ProfileSections/LanguageInformationSection.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #7467 
This branch fixes a string where the translators correctly added an abbreviation tag but the original was missing it.  I adjusted "GoC" to the more traditional "GC" in the string as well since that's the abbreviation we have already translated.
1. Log in as admin and open a user profile.
2. Switch to French and confirm the string changes as expected.
> [Fix] Fix language evaluation abbreviation

- apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
🤖 Resolves #7461 
This branch updates the email address on the manager homepage.
1. Browse to /manager.
2. Find the two email links and ensure they point to the right place.
> [Fix] Fix manager email address

- apps/web/src/components/StatusItem/StatusItem.tsx
🤖 Resolves #7454 
Adds `text-align: left;` to the `StatusItem` component.
2. Navigate to `/fr/applicant/profile-and-applications` (more noticeable in French)
3. Confirm text in the cards is all left aligned
> [Fix] Update `StatusItem` to left align text.

- api/database/migrations/2023_08_02_145650_cascade_pool_delete.php
- api/graphql/schema.graphql
🤖 Resolves #7306 
This branch updates the existing pool "delete draft" mutation to perform a force-delete.
I had to update the foreign keys to cascade deletes to the pivot tables.  I left the pivots for _pool candidate_ and _pool candidate filter_ since they should never be hit for drafts.
1. Run migrations and update the schema.
2. Delete a draft pool and observe that the row is completely gone from the database.
I don't know if we want to remove the existing deleted drafts in production.  If so, it can easily be accomplished by SSH'ing into the server and using Tinker.
1. Did you remember to backup the databaae?  :laughing: 
2. `Pool::withTrashed->count()`
3. `Pool::onlyTrashed()->count()`
4. `Pool::onlyTrashed()->forceDelete()`
5. `Pool::withTrashed->count()`
> [Fix] Force delete draft pools

- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/components/UserProfile/PrintExperienceByType/ExperienceItem.tsx
🤖 Resolves #6947 
This branch allows the experiences section of the print view to page break within it.  This avoids a big gap between the _Role and salary_ and the inevitable page break before _Career timeline_.  I also added the styles to avoid breaking within an experience.
1. Log in as admin
2. Print a profile, observe there is no page break between _Role and salary_ and _Career timeline_.
> [Feature] Allow experiences to break in print view

- apps/web/src/lang/fr.json
🤖 Resolves #7361.
This PR changes the spelling of _résidants_ to _résidents_ for consistency.
> [Copy] Changes résidants to résidents

- apps/e2e/cypress/e2e/talentsearch/submit-application-iap.cy.js
- apps/e2e/cypress/e2e/talentsearch/submit-application.cy.js
- apps/web/src/pages/Applications/ApplicationCareerTimelineEditPage/ApplicationCareerTimelineEditPage.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelinePage/ApplicationCareerTimelinePage.tsx
🤖 Resolves #7391 
Updates the application career timeline step to prefer cache when querying existing experiences.
We are calling a top level query on all these pages and queries in nested components seem to cause some issues when querying for similar data. We handle this by preferring cache (set in the parent components).
1. Build in dev mode `npm run dev`
2. Create and application
3. Continue to the career timeline step
4. "Edit" an experience
5. Confirm no console error appears
6. Complete creating the experience and return to the career timeline page
7. Confirm no console error appears
8. Confirm new experience appears
> [Fix] Bad set state call in application career timeline

- apps/web/src/components/ExperienceSortAndFilter/sortAndFilterUtil.ts
- apps/web/src/pages/Applications/ApplicationCareerTimelinePage/ApplicationCareerTimelinePage.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/CareerTimelineSection/CareerTimelineSection.tsx
- apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineSection.tsx
🤖 Resolves #7397 
Fixes an issue with sorting experiences calling hooks in the incorrect order.
This was caused by using a hook `useExperienceInfo` in a non-hook `sortAndFilterExperiences`. The hook was calling `useIntl` at different times because it was not being handled properly due to `useExperienceInfo` (which also contains `useIntl`) being used in a non-hook.
We were just deconstructing it for the title so it was replaced with `getExperienceName` which is what `useExperienceInfo` is using to get the title.
1. Build in dev mode `npm run dev`
2. Navigate to your career timeline (ensuring there are experiences there)
3. Sort the experiences in different ways
4. Confirm there are no errors in the …
> [Fix] Change in hook order

- apps/web/src/hooks/useRoutes.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
🤖 Resolves #7392 
Updates the skill showcase hero card on the "Profile and applications" page.
We have added new paths for the upcoming pages in `useRoutes` and used those for the skill showcase card.
> **Note**
> This does not create the pages, so interacting with the links takes you to a 404.
2. Login and navigaqte to `/applicant/profile-and-application`
3. Confirm the "Skill showcase" card link labels and urls match [the mockup](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7392)
> [Copy] Update skill hero card

- .github/workflows/e2e-tests.yml
- apps/e2e/cypress/README.md
- apps/e2e/package.json
🤖 Resolves #6732.
This PR sets Cypress default browser to Electron. Also, updates a bit of documentation where appropriate.
1. Run each of the scripts in `apps/e2e/package.json`:
- `npm run e2e`
- `npm run e2e:open`
- `npm run e2e:run`
- `npm run e2e:run:all`
- `npm run e2e:run:inspect`
2. Ensure tests run as before except using Electron browser instead of Chrome
> [Debt] Sets Cypress default browser to Electron

- api/app/Models/Experience.php
- api/app/Models/ExperienceSkill.php
- api/app/Models/Skill.php
- api/app/Models/UserSkill.php
- api/app/Traits/ExperienceFactoryWithSkills.php
- api/database/factories/UserFactory.php
- api/database/migrations/2023_07_31_160346_update_experience_skill_with_soft_delete.php
- api/tests/Feature/ExperienceTest.php
- api/tests/Feature/SkillTest.php
- api/tests/Feature/UserSkillTest.php
🤖 Resolves #7363.
This makes ExperienceSkills soft-deleted. That means that if you link an experience to a skill, add details, remove it, and re-link the skill, your previous details text will be restored.
This required some finagling to "simulate" soft-delete functionality, because [pivot models may not use the SoftDeletes trait](https://laravel.com/docs/10.x/eloquent-relationships#defining-custom-intermediate-table-models). In fact, I created an ExperienceSkill model which _can_ use the SoftDeletes trait and used that to make things a bit easier. But I can't use that model in the experience->skill relationships, because our API is currently designed around the `withPivot` functionality.
> Sidebar: Using withPivot is actually something I'd like to deprecate. Not only has it made this …
> [Feature] ExperienceSkill pivots should soft-delete

- apps/web/src/components/EmploymentEquity/EquityOptions.tsx
- apps/web/src/lang/fr.json
- packages/i18n/src/index.tsx
- packages/i18n/src/utils/localize.ts
🤖 Resolves #7537.
This PR removes the `withLocalizedQuotes` function and includes quotes within the i18n string itself instead.
1. Navigate to profile
2. Observe Diversity, equity and inclusion section
3. Ensure definition strings appear correctly in both English and French (as before)
> [Debt] Removes `withLocalizedQuotes` function

- apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
🤖 Resolves #7572.
This PR changes the email address for Contact us on the manager home page to use the `TALENTSEARCH_SUPPORT_EMAIL` constant.
Also, removes an unintended closing curly bracket from the end of one of the subject lines that is part of the `mailto` link, fe877b89c517a979f009505c041685818966eb78.
1. Navigate to `/manager`
2. Hover over or select the **Contact us** buttons
3. Observe to address is gctalent-talentgc@support-soutien.gc.ca
> [Fix] Email for contact us on manager home page

- apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/components/AddExperienceForm.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/components/addExperienceUtils.ts
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #7207 
This branch fixes a scenario where it is possible to add an experience and an error occurs but no error message is displayed.
I found it tricky to figure out a scenario that returns a null object without fully HTTP500'ing.  A good one is to change one of the database columns in the experience table to an incompatible type.
1. Log in as applicant and start an application.
2. On the career timeline step, try to add an experience of the type that you broke.
> [Fix] Fix experience error with no message

- apps/web/src/components/Profile/components/PersonalInformation/FormFields.tsx
🤖 Resolves #7595 
Fixes the vertical spacing in the personal information form on the profile.
2. Navigate to your profile `/users/{userId}/profile`
3. Open the personal information form
4. Confirm it is consistently spaced on desktop and mobile
> [Fix] Spacing for personal information form

- packages/ui/src/components/TableOfContents/Sidebar.tsx
🤖 Resolves #7587 
Adds margin bottom to the sidebar to improve mobile spacing in safari.
2. Navigate to the success page of an application
3. Reduce screen width
4. Confirm stepper is spaced from alert on mobile screens
> [Fix] Sidebar mobile spacing

- apps/web/src/components/PoolCandidatesTable/PoolCandidateTableFilterDialog.tsx
- apps/web/src/components/Table/ApiManagedTable/useFilterOptions.test.tsx
- apps/web/src/components/Table/ApiManagedTable/useFilterOptions.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.stories.tsx
- apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.test.tsx
- apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.tsx
🤖 Resolves #4638 
This removes an unused prop from the admin table filter dialogs.
We have no plan to ever enable the education type filter so we can safely remove it.
3. Confirm the filter dialog still functions
4. Navigate to `/admin/pools/{poolId}/pool-candidates`
5. Confirm the filter dialog still functions
> [Debt] Remove unused prop from filter dialogs

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #4416 
Deprectaes some non-paginated queries in favour of their paginated versions.
We have some queries that contain large datasets that require paginated results. We are deprecating the non-paginated versions to be removed in the near future.
1. Navigate to `/graphql`
2. Confirm the queries are marked as deprecated
3. Confirm the reason stated is accurate
> [Debt] Deprecate non-paginated queries

- api/app/Http/Controllers/SupportController.php
🤖 Resolves #7671.
This PR submits the name value via the support form to the support tickets created in Freshdesk when a user is logged in to the GC Digital Talent application. When creating a contact via a ticket object, Freshdesk uses the left side of the value of an email address. For example, jose.mourinho@test.com create a contact called jose mourinho.
> [!NOTE]  
> Testing requires the creation of a Freshdesk account (documentation added in another PR in f2717b2100f583f2d4a6ebd62f7f2109b8515520).
1. Submit form at `/support` by filling out an email address that is different than the name value
2. Verify that the contact name created is not derived from the email
> [Fix] Sends name to support form

- api/.env.example
- api/app/Http/Controllers/SupportController.php
- api/config/freshdesk.php
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
🤖 Resolves #4190.
This PR submits the user ID value via the support form to the support tickets created in Freshdesk when a user is logged in to the GC Digital Talent application.
> [!NOTE]  
> Testing requires the creation of a Freshdesk account (documentation added in this PR in f2717b2100f583f2d4a6ebd62f7f2109b8515520).
1. Submit form at `/support` without signing in to the application
2. Verify there is no **Unique External ID** section on created ticket in Freshdesk
3. Sign in to application `/login-info'
4. Submit form at `/support`
5. Verify **Unique External ID** section on created ticket in Freshdesk is the same value as the user id from the GC Digital Talent application
> [Feature] Sends user id to support form ticket if logged in

- api/database/seeders/UserSeederLocal.php
- api/database/seeders/UserSeederUat.php
🤖 Resolves #6405 
Updates the seeder to utilize the current role system. 
Seeder updates non-destructively, adding the range of roles to the users. 
Deleted some unused stuff in `UserSeederLocal` as was mentioned in issue discussion. 
1. Off main
2. Run `php artisan migrate:fresh`
3. Run `php artisan db:seed --class=UatSeeder`
4. Open up a database client and observe the user and role tables
5. Switch to branch
6. Run `php artisan db:seed --class=UatSeeder` (run it more than once too)
7. Role and user pivot populated with no users deleted, no duplication
8. Login as a UAT user, observe you have roleAssignments
Run the following solely on UAT
`php artisan db:seed --class=UatSeeder`
> [Debt] UAT user role seeding

- api/app/Providers/AuthServiceProvider.php
🤖 Resolves #7684
No longer gives a default first name, forcing it to be updated before you can submit applications. 
Peter did the legwork with identifying the root of the problem. 
1. Be logged out and then navigate to a pool poster
2. Click apply, be directed to the mock auth
3. Fill in for credentials a completely new user, so fill in random letters for the sub for auth, say "tester1397"
4. Upon signing in you get bounced back to the application and not an account creation page
5. Observe the emptiness
> [Bug] Remove default name for AuthService

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchContainer.tsx
🤖 Resolves #5976 
Prevents the selection of education option from having an effect on API operations. 
Disconnects the education field in the data massage function called before an operation is submitted to the API. Otherwise, the education option is unchanged in that it is select-able everywhere. 
Deprecates the field `hasDiploma` as well. 
1. Note results logged for search results off main at `/en/search` and `/en/admin/pools/:id/pool-candidates`
2. Switch to branch and build
3. Check the places from step one again, observe education filtering no longer changes result count
4. Submit a request with education selected, observe it is unchanged aside from no longer filtering results
5. Open the request from the admin dashboard, observe things are unchanged aside from the results count
> [Bug] Remove education filtering of results

- api/app/Models/User.php
Adds a gap in the authorization scope for the user model.
I think `id` is the correct column. Scopes run on the table of the current model, not the parent correct? 🤔 
1. Run a query for `poolCandidates.user` where the user is owned by the authenticated user
2. Confirm the user appears in the results instead of `null`
> [Fix] `User.scopeAuthorizedToView` to include view own

- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
- apps/web/src/types/experience.ts
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #3709 
This makes a couple of changes to the personal experience form:
- Makes the disclaimer checkbox checked by default if editing an experience
- Unchecks the disclaimer if a field other than it has changed from the default values
If users change their information, we want to make sure they re-agree to share the information since it is technically new info.
> **Note**
> I ran chromatic as part of this to test #7746
2. Create a personal experience
3. Check the disclaimer
4. Make a change
5. Confirm disclaimer unchecks
6. Save experience
7. Edit the same experience
8. Repeat steps 4-5
> [Fix] Uncheck disclaimer when form changes

- apps/web/src/pages/Skills/CreateSkillPage.tsx
- apps/web/src/pages/Skills/UpdateSkillPage.tsx
- apps/web/src/utils/skillUtils.test.ts
- apps/web/src/utils/skillUtils.ts
🤖 Resolves #7765
Allow platform admins to create or edit skills without filling in keywords.
Keywords ended up not being used, or even defined, for our skills library.
1. Log in as [admin@test.com](mailto:admin@test.com)
2. Go to http://localhost:8000/en/admin/settings/skills
3. Edit a skill
4. Edit skill family (or anything else) while leaving keywords blank
5. Try to submit
6. Do the same with creating a new skill
> Make Skill keyword fields not required

- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
🤖 Resolves #7683 
Updates the experience form breadcrumb URL (used as keys) to prevent duplicate keys.
We were using `window.location.pathname`, however, this was updating at a different time than the page was being rendered which lead to two URLs in the breadcrumbs being identical for a short period of time. This updates that URL to use a predefined value to prevent this behaviour.
2. Navigate to "Career timline..." page
3. Edit an experience
4. Click "Save and return..."
5. Confirm no duplicate keys error in console
> [Fix] Unique keys on experience form page

- api/app/Models/Skill.php
🤖 Resolves #7680 
Fixes a minor typo in the inverse relationship for pool nonessential skills.
> **Note**
> I'm not sure how to best test this since we aren't using the relationship yet 🤔
> [Fix] Pool, non-essential skill relationship typo

- packages/forms/src/components/Field/Label.tsx
🤖 Resolves #7682 
Forwards refs to the form label component.
Our label component was no forwarding refs which were required by the `Combobox` component. This updates our label to accept and forward a ref to the underlying component.
2. Navigate to edit or add an experience
3. Open the "Add a skill" dialog
4. Select a family to render the "Skill" combobox
5. Confirm no ref error appears in console
> [Fix] Forward ref to label

- apps/web/src/components/UserProfile/UserProfile.tsx
🤖 Resolves #7757 
Removes the status icon from the table of contents on the admin user profile page.
These icons are meant to communicate completeness to the user. It is less helpful for admins so we are removing it.
3. "View" a user and go to the "User profile" page
4. Confirm the table of contents does not include icons and just shows the bullet
> [Fix] Remove status icon from user profile on admin

- apps/web/src/components/QualifiedRecruitmentCard/QualifiedRecruitmentCard.tsx
🤖 Resolves #7755 
Adds additional column spacing to the skills list on the `QualifedRecruitmentCard`.
Since we are using `ul`, the bullet appears outside of the container which was creating the issue. This just increases the spacing to account for the bullets.
2. Hardcode in some long skill names to ensure it uses all the available space
3. Confirm there is an appropriate amount of space between columns in the list grid
> [Fix] Qualified recruitment card spacing

- api/app/Models/User.php
🤖 Resolves #7828 
Stop deleted experiences from appearing on Career Timeline
1. Log in as applicant
2. Add an experience to your profile
3. Delete the experience
4. Ensure it doesn't appear on career timeline page
1. Log in as admin@test.com
2. View a user on admin site
3. Note that user's id and the url, and the user's experiences
4. Delete the user
5. go back to viewing the user (by manually going to the url if necessary)
6. Ensure you can still see the user's experiences.
> Remove withTrashed scope from User->experience relationships

- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunitySelection.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #7360 
This branch adds the new message for API validation and also adds custom for validation.
This is a bit of a hack, for sure.  The form treats the four different checklist groups as a single element so a regular validation rule causes all the groups to go into a visual error state with the message.  It also doesn't have the submit handler in the component so you can't hook in there.  I tried breaking the form up into separate elements (which is probably the best solution) but it quickly got out of hand with the chips and illustrations and broke everything.  I opted for an independent validation rule that only brings up one standalone validation message.  It looks better but behaves differently in that it doesn't focus the input element and validates onChange.
1. Rule …
> [Fix] Custom validation for First Nations validation

- .github/workflows/lint.yml
🤖 Resolves #7871 
Adds the `/api` folder to the triggers for the lint workflow.
Now that we have a PHP linter, we should be running it in CI when changes are made to PHP files.
> **Note**
> I'm not sure how we would test this since it also runs on changes to that file (which has happened in this PR).
> [Tooling] Add `/api` folder to lint workflow

- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/TrackApplications.tsx
- apps/web/src/utils/applicationUtils.ts
🤖 Resolves #7441
This ensures users do not see applications with the "removed" status.
2. Create an application and set the status to "REMOVED"
3. Navigate to the following pages and ensure it does not appears
- `/users/{userIs}/profile`, in the "Hide recruitment availability" accordion
- `/applicant/profile-and-applications`, both current and past accordions
- `/users/{userId}/profile/career-timeline-and-recruitment`, qualified recruitments section
> [Fix] Hide "removed" applications from applicants

- api/app/GraphQL/Mutations/CreateUserSkill.php
- api/tests/Feature/UserSkillTest.php
🤖 Resolves #7837
Have it so restoring a UserSkill model via mutation class updates values, if applicable. 
Elected to go with a single update call rather than multiple ifs each running a call, that way if another field is added down the line it is easy to keep it all in one call rather than a series of `if (...)` 
1. Get to a UserSkill instance (/en/applicant/profile-and-applications/skills/:skillId)
2. Set it with values, and note them
3. Delete it
4. Navigate back to it
5. Claim again, with different values
6. Ensure it is restored with new values
> [Bug] Restore UserSkill persists values

- api/app/Models/PoolCandidate.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateSearchTest.php
- apps/web/src/components/PoolCandidatesTable/PoolCandidateTableFilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
🤖 Resolves #7816 
Enable filtering pool candidates by government employee field values, this applies to all instances utilizing the pool candidates table. 
Scope, schema tweak, tested, and then connected the pieces in the frontend. 
1. Test you can use the filter, go to a request and open the filter dialog
2. Test the filtering works, see below for an example
Get values through your preferred method, here is the total candidate count excluding draft, and candidate count that are government employees. In this case, 49 and 18 respectively. 
Observe this lines up with filtering for pool candidates in that pool. Matches the numbers from above
Filter state for just government employee, everything else cleared aside from the needed pool selection
> [Feature] Allow filtering pool candidates by gov employee field

- apps/web/package.json
- package-lock.json
- packages/client/package.json
- packages/client/src/components/ClientProvider/ClientProvider.test.tsx
- packages/client/src/components/ClientProvider/ClientProvider.tsx
- packages/forms/package.json
- packages/graphql/package.json
- packages/helpers/package.json
- packages/storybook-helpers/package.json
- packages/ui/package.json
🤖 Resolves #7885 
There was a previously undetected issue with the auth bump branch where prod builds would fail to authenticate properly.  This is a quick fix to roll back that bump so we can try again later.
1. Rebuild in prod mode (`npm run build`), not dev.
2. Log in works.
3. First graphql request after login has authorization header and succeeds.
4. Token refresh succeeds.
5. Log in as deleted user redirects to "deleted user" page.
6. [Introspection corner case](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6547#pullrequestreview-1602788860) does not cause refresh loop.
7. Steps 2 - 6 work with SiC, too.
> [Fix] Revert auth bump

- api/app/GraphQL/Mutations/SubmitApplication.php
🤖 Resolves #7830.
This PR fixes missing input data from an application snapshot.
Several inputs that are part of the last step of the application process were not being saved.
@esizer!
1. Submit an application
2. Open the snapshot on admin side in code
3. Observe the `signature` and `submittedAt` fields were values that were submitted
> [Fix] Application snapshot fields

- apps/web/src/lang/fr.json
- apps/web/src/pages/ProfileAndApplicationsPage/applicantOperations.graphql
- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
🤖 Resolves #6989 
Adds proper validation and skill counts on the skill card on the "Profile and applications" page.
> **Note**
> If https://github.com/GCTC-NTGC/gc-digital-talent/issues/7933 is not merged, you will need to tweak the skill showcase manually to test different cases.
2. Navigate to `/applicant/profile-and-applications`
3. Confirm the validation and skill counts match the expected outcome from the issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/6989
> [Feature] Skill card validation, skill count

- api/database/seeders/DatabaseSeeder.php
🤖 Resolves #7756 
Call the seeder in the base seeder that runs locally/by default. 
1. Seed fresh
2. Ensure e2e succeeds locally
> [Bug] Call GenericJobTitleSeeder in base seeder 

- api/graphql/schema.graphql
🤖 Resolves #7761 
Adds the scope to queries `usersPaginated` and `poolCandidatesPaginated`
Seems straightforward, tried it out and appears to work and nothing seems to perform worse. 
1. Cannot replicate https://github.com/GCTC-NTGC/gc-digital-talent/pull/7760#issuecomment-1698106937
2. Users/candidates tables remain functioning like before
> [Debt] Use authorizedToView scope on queries

- apps/web/src/lang/fr.json
🤖 Resolves #7952.
This PR fixes the French string **status for an application that has been screened out of eligibility** to use a correct translation of the English string **Screened out**.
1. Set application status to  **Screened out**
2. Switch to French
3. Observe _Éliminé à la présélection_ on card
> [Fix] Updates screened out FR string

- apps/web/src/lang/crg.json
- apps/web/src/lang/crk.json
- apps/web/src/lang/mic.json
- apps/web/src/lang/ojw.json
🤖 Resolves #7988.
This PR removes several strings that exist in four of the language files are orphaned and no longer a part of the application.
1. `pBJzgi`, `pgHTkX`, `M1JKQs` do not appear in the codebase
2. Application works as it did before
> [Debt] Removes orphaned i18n strings

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #7645
- Removes `User.expectedGenericJobTitle` from schema.
- The field was not found in any queries throughout the app.
1. Ensure app runs correctly and all tests pass
> [Debt] Remove expectedGenericJobTitle from schema

- apps/web/src/components/ExperienceCard/ExperienceCard.stories.tsx
- apps/web/src/components/ExperienceCard/ExperienceCard.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationSkillsPage/components/SkillTree.tsx
- apps/web/src/pages/Skills/UpdateUserSkillPage.tsx
🤖 Resolves #7818 
Allows devs to pass a single skill to `ExperienceCard`.
When you pass a single skill, the card should show the `experienceSkillRecord.details` above the `Collapisble` component and not inside it.
2. Navigate to the "Single skill - Experience card" story
3. Confirm details are shown without opening the collapsible element
4. Confirm other card stories work as expected
5. Build `npm run dev`
6. Navigate to a application skills step
7. Confirm details are shown without opening the collapsible element
8. Navigate to the skill library and edit  a skill
9. Link an experience
10. Confirm details are shown without opening the collapsible element
> [Fix] Experience cards surface single skill

- api/app/Models/PoolCandidateSearchRequest.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/SearchRequestTable/SearchRequestsTableApi.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/adminMessages.ts
🤖 Resolves #7944 
Adds the e ability to search for requests by ID on the search request table in the admin.
1. Rebuild `npm run dev`
2. Navigate to `/admin/talent-requests`
3. ?Use both the general and specific ID search
4. Confirm the expected results are returned
> [Feature] Search by ID on search request table

- apps/web/src/components/PoolStatusTable/PoolStatusTable.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #7372 
Adds a link to the application snapshot to the pool status table on a users profile.
2. Navigate to a users profile in admin
3. If they are not in a pool, use the "Add user to pool" button to add them to one
4. Confirm there is a new column for "Application" that links to the snapshot
> [Feature] Add snapshot link to pool status table

- apps/web/src/components/ExperienceSkillFormDialog/ExperienceSkillForm.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/components/AddExperienceForm.tsx
- apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ArchiveDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/CloseDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/DeleteDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/DuplicateDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ExtendDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PublishDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/UnarchiveDialog.tsx
- apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/AddExperienceDialog.tsx
- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
- apps/web/src/pages/Teams/TeamMembersPage/components/AddTeamMemberDialog.tsx
- apps/web/src/pages/Teams/TeamMembersPage/components/EditTeamMemberDialog.tsx
- apps/web/src/pages/Teams/TeamMembersPage/components/RemoveTeamMemberDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/AddIndividualRoleDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/AddTeamRoleDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/DeleteUserDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/EditTeamRoleDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/RemoveIndividualRoleDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/RemoveTeamRoleDialog.tsx
- apps/web/src/pages/Users/UserInformationPage/components/AddToPoolDialog.tsx
- apps/web/src/pages/Users/UserInformationPage/components/ChangeDateDialog.tsx
- apps/web/src/pages/Users/UserInformationPage/components/ChangeStatusDialog.tsx
🤖 Resolves #8012.
This PR replaces all instances of the string "Cancel and go back" with the `formMessages` definition.
1. Search for instances of string "Cancel and go back"
2. Observe only one instance in codebase for "Cancel and go back"
> [Debt] Replaces "Cancel and go back" with single source

- apps/web/src/components/SkillDialog/SkillDialog.tsx
🤖 Resolves #8086 
Resolve the inability to scroll up for skill dialogs. 
Tried the method in docs, didn't get anywhere. Gave deleting styling in the component a go and it appears... to have worked?
Don't know what the styling bit did, removing it didn't seem to throw any issue. 
http://recordit.co/oKiXB9mWco
1. Head to skill showcase and edit
2. Play with opening the dialog
The lost, top of the dialog
> [Bug] Skill dialog scrolling

- api/app/Policies/UserPolicy.php
- api/config/rolepermission.php
- api/graphql/schema.graphql
- api/programmatic-types.graphql
- api/schema-directives.graphql
- api/tests/Feature/RolePermissionTest.php
- api/tests/Feature/UserRoleTest.php
Updates the User Policy permission to correctly protect roleAssignment and sub.
This is the bare-minimum quick fix. I'd like to change the updateUserAsAdmin mutation a bit further, to make these kinds of bugs easier to avoid in the future.
I added an one more permission, `update-any-userSub`, to reflect the fact that admins can update MORE fields on the user object than users can touch themselves. Also fixed the field name used to check for role assignment.
1. set `AUTH_DEFAULT_USER='applicant@test.com'` in api/.env 
2. Go to http://localhost:8000/graphiql
3. As a non-admin user, try to edit your own sub field. You can find <applicant-user-id> by running the `me` query. The following mutation should …
> [Bugfix] update user policy

- apps/web/src/components/SkillDialog/SkillDialog.tsx
🤖 Resolves #8104 
Fixes a bug where the skill dialog was not validating inputs on submission.
Since this form can be nested, we had some hacks to prevent triggering the parent form submission. However, this also prevented the skill dialog from triggering a submission which bypassed validation. This just modifies the hack to trigger an artificial submission which checks validation before adding the skill.
1. Navigate to the skill library /applicant/profile-and-applications/skills
2. Activate one of the "Add a skill" buttons
3. Select a skill
4. Do not select a skill level or if you are currently using it
5. Submit the form and observe it properly validates
6. Navigate to an experience
7. Link a skill …
> [Fix] Skill dialog validation on  submission

- apps/web/package.json
- package-lock.json
- package.json
This pull request updates Hydrogen to `2.0.3`. You can see a full list of changes here: https://hydrogen.design/en/docs/releases/#2.0.3
This release contains a bugfix for the the `data-h2-shadow` property, but otherwise doesn't have an effect on core processing.
```[tasklist]
```
> Updates Hydrogen to 2.0.3

- api/app/Http/Kernel.php
- api/app/Http/Middleware/SimulateFirewallMiddleware.php
- packages/client/src/components/ClientProvider/ClientProvider.tsx
- packages/client/src/exchanges/specialErrorExchange.ts
- packages/forms/src/components/Input/Input.tsx
- packages/forms/src/components/TextArea/TextArea.tsx
- packages/forms/src/utils.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/errorMessages.ts
🤖 Resolves #7812 
This branch (attempts) to add an error message to help users identify when a request has been rejected due to banned characters.  It also adds a graceful handling for the narrow no-break space.
Since this behaviour only occurs on the production site behind the production firewall, I added a middleware that can be activated to simulate this behaviour locally.
For the narrow no-break space, I hooked into the whitespace trimming logic that already existed.  I did test that a regular no-break space is OK in production.
1. Uncomment the `SimulateFirewallMiddleware` class in kernel.php
2. Open a form and add a [narrow no-break space](https://symbl.cc/en/202F/) to an input and submit it.
3. Observe that it was converted to a regular no-break space onBlur.
4. Add another …
> [Fix] Handle firewall reject characters

- apps/web/src/pages/Skills/ImproveBehaviouralSkillsPage.tsx
- apps/web/src/pages/Skills/ImproveTechnicalSkillsPage.tsx
- apps/web/src/pages/Skills/TopBehaviouralSkillsPage.tsx
- apps/web/src/pages/Skills/TopTechnicalSkillsPage.tsx
- apps/web/src/pages/Skills/components/UpdateSkillShowcase.tsx
🤖 Resolves #8087
Updating/claiming a skill in the showcase context will update the ranking after the first mutation completes.
Elected to add another mutation via function that returns nothing, given the other is tightly coupled to the form it seemed better to not try and adjust the handler to fit two very different shapes. 
Removed the `append` call as updating the ranking reloads the parent component anyway. 
1. Pick a showcase type, open it up and add a skill
2. Note showcase is updated without requiring another save action on your part
Recording
https://recordit.co/imrrXJUohq
> [Bug] Skill dialog in skill showcases should save ranking

- apps/web/src/pages/Teams/TeamMembersPage/TeamMembersPage.tsx
- apps/web/src/pages/Teams/teamsOperations.graphql
🤖 Resolves #8123 
This fixes an issue that was causing our team members table to infinitely re-render.
We were running three separate queries that go similar data. The data was changing causing re-renders to happen at different intervals. This combines all three queries into one and memoizes the data being passed into and used by the table to stabilize it.
1. Navigate to a team members page `/admin/teams/{teamId}/members`
2. Confirm the table is not re-rendering infinitely
> [Fix] Stabilize team members table

- packages/forms/src/components/DateInput/ControlledInput.tsx
- packages/forms/src/components/DateInput/DateInput.tsx
- packages/forms/src/styles.ts
🤖 Resolves #8003 
This fixes `select` styles for Firefox, preventing them from looking disabled in comparison to other inputs.
This does a few things in order to fix it:
- Passes field state styles to the controlled inputs on the `DateInput`
- This will also now show inputs as red when there is an error
- Updates the state styles to also apply background on the dirty state
- This was an issue for all `select` once the value had been changed they looked to be disabled
> **Note**
> Since this is a Firefox specific bug, you must do the testing in Firefox. Also, confirm no changes in other browsers.
2. Navigate to the date input stories
3. Confirm the month input does …
> [Fix] Update select styles for FF

- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
🤖 Resolves #7884
Conditionally render the section provided the array has a non-zero length. 
1. Navigate to `/en/browse/pools`
2. Nothing should be different
3. Execute the below SQL
4. Do not observe an `OngoingRecruitmentSection`  anymore
```
UPDATE pools
SET published_at = null
WHERE publishing_group = 'IT_JOBS_ONGOING'
```
> [Feature] Render OngoingRecruitmentSection conditionally 

- apps/e2e/cypress/e2e/talentsearch/static-pages.cy.js
- apps/web/src/lang/fr.json
- apps/web/src/pages/DirectivePage/DirectivePage.tsx
- apps/web/src/pages/DirectivePage/utils.ts
🤖 Resolves #8156.
This PR refactors document links to render only a link to the current locale and removes the **(`{locale}`)** copy that was previously was at the end of the labels of those links.
1. Navigate to `/en/directive-on-digital-talent`
2. Observe document links are to English documents only
4. Observe document links are to French documents only
> [Copy] Refactors document links to be current locale only

- apps/web/package.json
- package.json
- packages/forms/src/utils.ts
- packages/storybook-helpers/main.ts
🤖 Resolves #8128 
splits up our storybooks to be more targeted and speed up start up times.
This adds two new commands to run specific story files. The more story files we load, the longer the start up times. This was growing too large so this splits up storybook into 3 different scripts:
- `npm run storybook` - Runs all story files
- `npm run storybook:web` - Runs just story files in `apps/web/**`
- `npm run storyook:design-system` - Runs just story files in `packages/**`
We also had to refactor the new `santizeString` which was using a function that was not available in storybook.
1. Run the different commands noted in the details section
2. Confirm the expected story files are loaded
3. Confirm …
> [Feature] Split storybook scripts

- apps/web/src/components/Table/ResponsiveTable/SearchForm.tsx
- apps/web/src/components/Table/ResponsiveTable/Table.tsx
🤖 Resolves #8109 
Updates the tab order of table action buttons to make the "add" item the first in the tab order.
> **Note**
> This also fixes some extra padding in the search input where the icon used to be but was removed.
2. Navigate tot a table with an "add" option
3. Hit tab and confirm focus goes first to the "add" button then the search form/filters
> [a11y] Adjust table control tab order

- apps/web/src/components/SkillDialog/SkillSelection.tsx
- packages/forms/src/components/Combobox/Multi.tsx
- packages/forms/src/components/Combobox/Single.tsx
🤖 Resolves #8120 
Fixes the available options count when the number of options passed updates.
Uses an effect to sync the internal state when the passed in options array changes length.
2. Navigate to a page with the skill picker
3. Select a skill family
4. Open the combox menu
5. Confirm available options matches expected number
6. Select a new skill family
7. Repeat steps 4 and 5
> [Fix] Combobox available options count

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #7665.
This PR removes `ApplicantFilter.wouldAcceptTemporary` from the graphql schema.
1. Ensure app works as it did before
> [Debt] Removes `ApplicantFilter.wouldAcceptTemporary` from graphql schema

- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/TrackApplicationsCard.tsx
🤖 Resolves #8171.
This PR removes the recruitment type copy as well as the bullet unicode character used as a divider from `TrackApplicationsCard`.
2. Observe `TrackApplicationsCard` story
> [Copy] Removes recruitment type copy from `TrackApplicationsCard`

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/hooks/useSelectedRows.ts
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
🤖 Resolves #7681 
Pauses the row selection queries until users make at least one selection.
This was slightly tricker than I first assumed. I used a ref to track if any selection has been made so we still run the query once all items have been selected so we can empty out the in memory cache of the result. Maybe a better approach would be to try and empty that in memory cache instead of making a trip to the server when we know the response will be an empty array? 🤔 
3. Confirm the initial selected query is not run
4. Select a row
5. Confirm the query runs and printing works
6. Deselect a row
7. Confirm print is empty
8. Navigate to a pool candidates …
> [Debt] Pause row selection queries

- apps/e2e/cypress/e2e/talentsearch/submit-application-iap.cy.js
- apps/web/src/components/EmploymentEquity/dialogs/IndigenousDialog.tsx
- apps/web/src/components/EmploymentEquity/types.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/ApplicationSelfDeclarationPage.tsx
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunityChips.tsx
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunitySelection.tsx
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/SelfDeclarationForm.test.tsx
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/utils.ts
- apps/web/src/utils/indigenousDeclaration.ts
- packages/ui/src/components/Alert/Alert.tsx
- packages/ui/src/components/Chip/Chips.tsx
🤖 Resolves #7525 
Updates the Indigenous self-declaration form to use a radio group for First Nations status.
This was done to force a user to only select one or the other but not both. Some other changes were made as well:
- Spacing has been updated
- Signature field hidden when no community is selected
- Submit button changes content based on the form values (removes the term "sign" when no signature field appears)
> **Note**
> I left in the "select both" error message since we already have it and to guard against any edge cases
2. Navigate to your profile
3. Scroll down to the DEI section
4. Open the Indigenous identify dialog
5. Interact with the form and confirm the First …
> [Feature] First Nations status radio group

- apps/web/src/lang/fr.json
Fixes a translation mistake that wasn't caught in review 😢 
2. Navigate to your "Profile information"
4. Open the Indigenous identity dialog
5. Confirm the First Nations option uses guillemets and not double quotes
> [Fix] First nations guillemets mistake

- api/app/Models/User.php
- api/app/Policies/UserPolicy.php
- api/config/rolepermission.php
- api/tests/Feature/RolePermissionTest.php
🤖 Resolves #7827 
Renames it to 'view-team-applicantProfile'
Not too many moving parts, noted a bug here #8232 
1. Seed fresh
2. Log in as `pool@test.com`, exercise the admin dashboard
3. 'view-team-user' no longer present
Re-run the roles and permission seeder
`php artisan db:seed --class=RolePermissionSeeder`
> [Debt] Rename 'view-team-user'

- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountForm.stories.tsx
🤖 Resolves #7528
Adds a story for the Create account page form. 
Added the story. 
`GovernmentInfoForm.stories.tsx` was removed in #7644 
2. Navigate to Create account story
> [Debt] Create account page story

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/viewPoolCandidatePage.graphql
🤖 Resolves #8248
Add `suspendedAt` to graphql file
`<PoolStatusTable>` renders availibility and for that, need to pass in the field to render correctly. It was missing for this page that renders the snapshot page, which is the second place that table appears. 
1. Snapshot page's info table accounts for availability in rendering
> [Bug] Add missing suspendedAt to graphql file

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- packages/fake-data/src/fakeUsers.ts
🤖 Resolves #7664
Remove the deprecated field. 
Wasn't actually used/referenced anywhere I could find other than the faker file. 
1. Builds fine, tests pass
> [Debt] Remove deprecated 'users.pools'

- apps/web/src/components/Table/ResponsiveTable/Table.tsx
- apps/web/src/components/Table/ResponsiveTable/styles.ts
- apps/web/src/table.d.ts
🤖 Resolves #8222 
This allows the row selection column to shrink. As well, you can force columns to shrink below the min width of `x8` with `meta.shrink?: boolean` in the column def.
1. Run storybook `npm run storybook:web`
2. Navigate to the  "Tables\Responsive Table\Row Selection" story
3. Confirm the column with checkboxes is smaller than the other columns
> [Fix] Reduce width of row selection column

- apps/web/src/components/QualifiedRecruitmentCard/QualifiedRecruitmentCard.test.tsx
- apps/web/src/components/QualifiedRecruitmentCard/QualifiedRecruitmentCard.tsx
- apps/web/src/components/QualifiedRecruitmentCard/utils.ts
- apps/web/src/utils/poolCandidateCombinedStatus.tsx
🤖 Resolves #7300 
Removes the status/availability text on the `QualifiedRecruitmentCard` for placed statuses.
Seems this was mostly done with `isHiredLongTermCombinedStatus` setting it to `null`. This just updates to use `isHiredCombinedStatus` instead to include `PLACED_CASUAL`.
I also noticed some minor items that needed cleaning up:
- Fixed a typo in placed long term enum
- Check for text before rendering `<p>` to avoid empty DOM element
1. Run storybook `npm run storybook:web`
2. Navigate to the Qualified Recruitment Card" story
3. Scroll down to the placed statuses
4. Confirm no status text appears
> [Fix] Remove status text for placed statuses

- apps/web/src/pages/Home/IAPHomePage/Home.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/ApplyDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/DefinitionDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/LearnDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/RequirementDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/SelfDeclarationDialog.tsx
- apps/web/src/pages/Home/IAPHomePage/components/Dialog/VerificationDialog.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
🤖 Resolves #8214 
Wraps the IT Apprenticeship Program for Indigenous Peoples homepage in a `div[lang=locale]` so that the Indigenous languages can be programmatically determined.
We planned on overriding dialog close buttons with the parent language. However, I found an appropriate message already translated and used that to avoid workarounds.
>  **Note**
> I tried to define a central message for the "Close" string but then it wasn't getting translated by the nested provider 🤔. While reviewing, if you know of, for find, a way to get that working that would be great! 
Language codes:
- Michif: crg
- Plains cree: crk
- Western Ojibwe: ojw
- Mi'kmaw: mic
3. Changed to each Indigenous language
4. Confirm the `div` wrapping …
> [Fix] Add `lang` attribute for Indigenous languages

- apps/web/.env.example
- apps/web/public/config.ejs
- apps/web/src/components/CallToActionCard/CallToActionCard.stories.tsx
- apps/web/src/components/CallToActionCard/CallToActionCard.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
- packages/env/src/utils.ts
🤖 Resolves #8286 
Adds a teaser for upcoming exec processes on the brow jobs page.
This adds a new feature flag so we can remove the alert quickly. This flag, when true, shows the exec teaser just below active recruitments and hides the "more opportunities" card at the bottom of the page.
> **Warning**
> There was a copy change from the original ticket
1. Update your `.env` with the new feature flag in the `.env.example` file
3. Navigate to `/browse/pools`
4. Confirm the exec teaser appears instead of the "more opportunities" card
- Add env variable `FEATURE_EXECUTIVE_TEASER=true`
> **Note**
> I assume we want this to true so it shows immediately and we will be setting it to …
> [Feature] Executive teaser

- packages/app-insights/tsup.config.ts
- packages/auth/tsup.config.ts
- packages/client/tsup.config.ts
- packages/env/tsup.config.ts
- packages/forms/tsup.config.ts
- packages/graphql/tsup.config.ts
- packages/helpers/package.json
- packages/i18n/tsup.config.ts
- packages/theme/tsup.config.ts
- packages/toast/tsup.config.ts
- packages/ui/tsup.config.ts
🤖 Resolves #8313 
Makes tsup cli output silent.
This output is rarely ever helpful, we only usually care about errors.
1. Run `npm run build:fresh` to get no cache
2. Observe the reduced amount of output in the console
> [Debt] Reduce Tsup output

- api/graphql/schema.graphql
- apps/web/src/components/AdminSideMenu/AdminSideMenu.tsx
- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/pages/PoolCandidates/AllPoolCandidatesPage/AllPoolCandidatesPage.tsx
🤖 Resolves #8304 
This allows users with the pool operator and request responder roles to view a table of users and all pool candidates. These are scoped specifically to the records they have access to.
We also had some icon discrepancies that were resolved while adding the root pool candidates page thanks to assistance from @Jerryescandon 
2. Login with `pool@test.com`
3. Confirm you see both "Pools candidates" and "Users" in the sidebar
4. Confirm accessing them shows the scoped records
5. Login with `request@test.com`
6. Repeat steps 3-4
> [Feature] Allow pool operator and request responder access to users and pool candidates

- apps/web/src/components/Table/Actions.tsx
- apps/web/src/components/Table/EditLink.tsx
- apps/web/src/components/Table/ViewLink.tsx
- apps/web/src/components/Table/cells.tsx
- apps/web/src/pages/Skills/UpdateSkillPage.tsx
- apps/web/src/pages/Skills/components/SkillTable.tsx
🤖 Resolves #8339
Makes it easier to navigate the skill table, edit a single skill, and return to where you were on the table.
I'm trying a new pattern here, where the table link cell components add a `from` url to the location state, and the edit/view/create page can navigate to that url (which includes table state) if its available. I really like the way this works! I'd be interested in adopting this on other edit/view/create pages.
1. Log in ad admin@test.com
2. Go to skills table
3. Add a search filter, change visible columns and navigate to a later page
4. Narrow your screen so you can't see all columns at once
5. Can you get to the skill edit page without horizontal scrolling?
6. Edit a skill, submit changes
7. Did you come back to the table in the state you left it in? (page and …
> [Feature] Admin Skill table improvements

- packages/forms/src/components/ErrorSummary.tsx
🤖 Resolves #8349 
This updates the support link in the error summary footer to go to `/support` instead of a `mailto`
2. Navigate to a form and trigger the error summary
3. Confirm that clicking the support link takes you to the support page in the appropriate locale
> [Debt] Update support link in error summary

- apps/web/src/pages/DirectiveForms/DigitalServicesContractingQuestionnaire/fieldsSets/PersonnelRequirementFieldset.tsx
- apps/web/src/pages/DirectiveForms/DigitalServicesContractingQuestionnaire/useLabels.ts
🤖 Resolves #7814 
This updates the directive form labels with the wildcard approach for field arrays so they appear in the error summary.
2. Navigate to `/directive-on-digital-talent/digital-services-contracting-questionnaire`
3. Fill out the form ensuring the following (to force an error)
- _Does the contract have specific personnel requirements?_  -> Yes
- Add at least one personnel requirement, leaving it entirely blank\
4. Submit the form
5. Confirm error summary appears with errors for the nested fields
> [Fix] Update directive form to support field arrays in error summary

- packages/forms/src/components/RichTextInput/LinkDialog.tsx
🤖 Resolves #8341 
This fixes a few bugs and adds a quality of life improvement to the link dialog in the rich text input.
There were two bugs fixed in this:
- Pressing "Enter" no longer submits the parent form ( https://github.com/GCTC-NTGC/gc-digital-talent/commit/b77747a491b1810aeb4ec52cab6e85d438734290 )
- Form is reset when closing the dialog  ( https://github.com/GCTC-NTGC/gc-digital-talent/commit/57bc9e792968b80441301d448b4260ddd318e551 )
As well, the link dialog now does not require a protocol. If one is not present, it will prepend the URL with `http://`.
3. Click "Create pool" and continue to edit page or, edit an existing draft pool
4. …
> [Fix] Fix link dialog for rich text input

- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
- apps/web/src/components/Table/ResponsiveTable/SearchForm.tsx
- apps/web/src/components/Table/ResponsiveTable/useControlledTableState.ts
🤖 Resolves #8343 
Fixes the new `<ResponsiveTable />` resetting some state variables on initial page load.
Looks like we forgot to supply the table with `initialState` when it exists. This meant that our table was starting out with an empty state. Then, when that state did not match our current state, it tried to overwrite the URL and use that to update our controlled state.
Simply providing the table with an initial state prevents that. 
1. Run `npm run dev`
2. Navigate to `/admin/skills`
3. Change the state, confirm URL updates
4. Navigate away from that page
5. Click the browser back button
6. Confirm the URL matches that in step 3
7. Confirm the table state matches the URL state with expected date
> [Fix] Prevent table resetting parameters

- apps/web/.storybook/preview.js
- apps/web/src/components/Context/ContextProvider.tsx
- package-lock.json
- packages/env/package.json
- packages/env/src/FeatureFlagProvider.tsx
- packages/env/src/index.ts
- packages/env/src/useFeatureFlags.ts
- packages/env/src/utils.ts
- packages/env/tsconfig.json
- packages/storybook-helpers/decorators/FeatureFlagDecorator.tsx
- packages/storybook-helpers/index.ts
- packages/storybook-helpers/package.json
🤖 Resolves #7097 
Adds the ability to check and control feature flags in storybook.
This does a two things:
- Moves feature flags to context
- Creates a decorator that adds the context to storybook, allowing users to override with `parameters.featureFlags`
```tsx
export default {
component: FeatureFlagComponent,
title: "A Feature Flag Component",
parameters: {
featureFlags: {
flag: true,
}
}
} as Meta;
```
> **Note**
> I found working with `ProfileAndApplicationsHeading` works well since it implements a feature flag that can be toggled and it is obvious.
1. Install and build `npm i && npm run dev`
2. Start storybook `npm run storybook:web`
3. Navigate to the story and confirm it appears as you expect
4. Add the feature flags parameter temporarily
5. Toggle the flag back and forth and …
> [Feature] Add feature flags to storybook

- apps/web/src/components/Footer/Footer.tsx
- apps/web/src/components/Footer/VersionLink.tsx
- apps/web/src/constants/talentSearchConstants.ts
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- packages/webpack-config/webpack.base.js
🤖 Resolves #4691 
Adds a link to the footer that shows the current tag or commit hash (if they exist).
This only works with annotated tags. If there is no annotated tag, it falls back to the commit hash.
2. Scroll to the footer and confirm you see the version link and it functions as expected
> [Feature] Add version link to footer

- apps/web/src/pages/Teams/TeamMembersPage/components/AddTeamMemberDialog.tsx
- apps/web/src/pages/Teams/teamsOperations.graphql
- apps/web/src/utils/nameUtils.tsx
🤖 Resolves #8243
Replace the select with the combobox, and add email to the label formatting. 
1. Head to a team and then the view team member page
2. Observe the dialog's inputs and add people to teams after searching for them
Formatted user labels
Searched for and found a correctly labelled user missing email
> [Feature] Combobox and formatting changes in add team member dialog

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #7655.
This PR removes the `latestPoolCandidateSearchRequests` query, that is no longer used, from the GraphQL schema.
1. Confirm there are no instances or references to the query `latestPoolCandidateSearchRequests` left in the codebase
> [Debt] Removes `latestPoolCandidateSearchRequests` query

- packages/forms/src/components/Combobox/Menu.tsx
🤖 Resolves #8424 
This fixes a bug where downshift was applying `aria-selected=true` to the highlighted item and not the selected item.
1. Run storybook `npm run storybook:design-system`
2. Navigate to the multi combobox story
3. Open the dropdown and select some items
4. Confirm only the selected items in the list have `aria-selected` set to `true`
> [Fix] Properly assign `aria-selected` to multi select combobox

- apps/web/src/lang/fr.json
🤖 Resolves #8468 
Fixes a typo for the education requirements on the French pool advertisement page.
2. Navigate to a pool advertisement
3. Scroll to education requirements
4. Confirm "Les" does not appear after the pool title
> [Fix] Typo on French pool advertisement page

- apps/web/src/components/Hero/Hero.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/AccessibilityStatementPage/AccessibilityStatementPage.tsx
🤖 Resolves #8359 
Makes some minor layout changes to the accessibility statement to align it with other pages.
2. Navigagte to `/accessibility-statement`
3. Confirm the following:
- Hero subtitle does not overlap image on right
- Table of contents exists and functions as expected
- Headings updated to match expected size
- Container is wider matching other pages
> [Design] Fix accessibility statement page layout

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateSearchRequestTest.php
- apps/web/src/pages/SearchRequests/poolCandidateSearchRequestOperations.graphql
🤖 Resolves #7659.
This PR removes the `poolCandidateSearchRequests` GraphQL query from the schema. Additionally, it removes the unused `getPoolCandidateSearchRequests ` query.
1. Ensure no references to `poolCandidateSearchRequests` GraphQL query exist in codebase
> [Debt] Removes `poolCandidateSearchRequests` GraphQL query

- package-lock.json
- packages/auth/package.json
- packages/auth/src/components/AuthenticationContainer.tsx
- packages/client/package.json
- packages/client/src/components/ClientProvider/ClientProvider.tsx
🤖 Resolves #8396
Updates the dependency from 3.1.2 to 4.0.0
The applicable breaking change was the import no longer being a default export. 
https://github.com/auth0/jwt-decode/releases/tag/v4.0.0
1. Login and logout, so auth tasks succeed still
> [Dependencies] Jwt-decode 4.0.0

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/ApplicantFilterTest.php
🤖 Resolves #7653.
This PR removes the `applicantFilter` GraphQL query from the schema. Also, it removes the `testQueryApplicantFilterById` test that is no longer applicable.
1. Ensure no references to `applicantFilter` GraphQL query exist in codebase
> [Debt] Removes `applicantFilter` GraphQL query

- apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/OtherRequirementsSection/OtherRequirementsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ScreeningQuestions.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/SpecialNoteSection/SpecialNoteSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectSection/WhatToExpectSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/WorkTasksSection/WorkTasksSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/YourImpactSection/YourImpactSection.tsx
🤖 Resolves #8460 
Some buttons on the admin pool pages were using tertiary instead of secondary.  This branch fixes that.
1. Build and log into admin.
2. Check the buttons mentioned in the issue.
> [Fix] Change pool buttons from tertiary to secondary

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #8481.
This PR removes the `poolByKey` GraphQL query that is not used.
1. Ensure no instances of the `poolByKey` GraphQL query in the codebase
> [Debt] Removes `poolByKey` GraphQL query

- apps/web/src/lang/fr.json
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #8465.
This PR enables i18n for the `DuplicateUserSkill` error message and adds copy in English and in French.
In English, the error returned is: "The skill you selected is already linked to your profile."
In French, the error returned is: "La compétence que vous avez sélectionnée est déjà reliée à votre profil."
The French strings for the options for when a skill is currently being used and was only used in the past had extra trailing spaces after the first word in the string and an incorrect `majuscule`.
@Jerryescandon for "Work with a designer to pick an error message"!
1. Navigate to `applicant/profile-and-applications/skills`
2. Click **Add a new skill** button
3. Choose a skill that …
> [Fix] Enables i18n for the `DuplicateUserSkill` error message

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/SkillMatchDialog.tsx
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/poolCandidatesOperations.graphql
🤖 Resolves #8523
Removes experiences from the main `PoolCandidatesTable` query moving them to a smaller query when opening the `SkillMatchDialog`.
1. Navigate to the pool candidates page and add a skill to the skill filter.
2. Confirm Experiences are not included in the main query.
3. Open the `SkillMatchDialog` for one of the candidates and confirm a smaller query runs for just that candidates experiences.
> [Debt] Moved experiences from page query to SkillMatchDialogs

- api/app/Enums/PoolCandidateSearchStatus.php
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/SearchRequestTable/components/utils.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/UpdateSearchRequest.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #8542 
Adds a new status enum for search requests. 
1. Optionally seed fresh to generate requests with the new status
2. Head to requests
3. Set requests as the new status, filter, and observe
> [Feature] Add no candidates found status

- apps/web/src/components/PoolStatusTable/PoolStatusTable.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/viewPoolCandidatePage.graphql
- apps/web/src/pages/Users/userOperations.graphql
🤖 Resolves #8540 
Adds the two columns to the specified table. 
Just recycled accessors from the pools table ♻️ 
1. Observe at /en/admin/users/*id
2. Observe at /en/admin/candidates/*id/application
> [Feature] Add columns to pool status table

- apps/web/src/lang/fr.json
🤖 Resolves #8583.
This PR changes _Apprenez-en advantage_ to _Apprenez-en davantage_ in French.
1. Navigate to `/fr/search/request`
2. Observe **Apprenez-en davantage...** copy
3. Navigate to `/fr/applications/:application-id/education` (pool must have `EX` classification group)
4. Observe **Apprenez-en davantage...** copy
> [Copy] Changes Apprenez-en advantage to Apprenez-en davantage

- api/app/Http/Controllers/SupportController.php
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
🤖 Resolves #8581.
This PR adds a response for the `SupportForm` when there is a missing endpoint or key in the app's `api`.
1. Ensure `FRESHDESK_API_TICKETS_ENDPOINT` or `FRESHDESK_API_KEY` in `api/.env` are not set
2. `npm run dev`
3. Navigate to `/support`
4. Fill out and submit form
5. Observe error toast
6. Witness a vast somethingness
> [Fix] Adds `SupportForm` missing endpoint or key response

- api/app/GraphQL/Mutations/ArchivePool.php
- api/app/GraphQL/Mutations/UnarchivePool.php
- api/tests/Feature/PoolTest.php
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #8533
Adds translations for the api error messages when archiving/un-archiving pools.
1. First make the buttons appear for invalid pools by changing the `===` to `!==` in the following lines of code
https://github.com/GCTC-NTGC/gc-digital-talent/blob/ab0700f7c8b9dfec7f980e3badee19188078d6c0/apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx#L375
https://github.com/GCTC-NTGC/gc-digital-talent/blob/ab0700f7c8b9dfec7f980e3badee19188078d6c0/apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx#L381
3. Engage the title link for a Draft or Published pool
4. Engage **Archive process** button (appears as a link)
5. Engage **Archive process** button in the dialog
6. Observe error message
7. Engage **Un-archive process** button (appears as a link)
8. …
> [Copy] Translated error messages for (un-)archiving pools

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
🤖 Resolves #8591 
Fixes a regression in the page size for the pool candidates table after the refactor.
2. Navigate to `/admin/pool-candidates`
3. Confirm you can increase page size to 500
> [Fix] Increase max page size for `PoolCandidatesTable`

- apps/web/src/lang/fr.json
🤖 Resolves #8551.
This PR updates French string for **Text Telephone (TTY/TDD)** to be consistent in French.
1. `npm run dev`
2. Navigate to `/fr/register-info`
3. Open _Avec qui puis-je communiquer si j’ai des questions au sujet de CléGC?_ item
4. Observe _Téléimprimeur (ATS/ATME)_
5. 1. Navigate to `/fr/login-info`
6. Open _Qui dois-je contacter si j'ai des questions sur la CléGC?_ item
7. Observe _Téléimprimeur (ATS/ATME)_
> [Copy] Updates French string for Text Telephone (TTY/TDD)

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
- apps/web/src/components/Table/ResponsiveTable/types.ts
🤖 Resolves #8597 
Fixes a bug that caused infinite re-renders when using `urlSync` on pages that need to read from url params. This also prevents the URL from updating with default filters.
It seems that the `setSearchParams` updater does not work like the default `setState` update in react. Using the updater, it causes a navigation regardless if there are any new params.
We fixed this by checking to see if the new params are different than our current params before setting them.
3. Click on "View candidates" for any row
4. Confirm the page is not infinitely re-rendering
5. Confirm the URL state sync still works
> [Fix] Stabilize `urlSync` for `ResponsiveTable`

- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.test.tsx
- apps/web/src/pages/Pools/BrowsePoolsPage/BrowsePoolsPage.tsx
🤖 Resolves {#8607}
Describe what this PR is solving.
1. Create a Pool with Executive Stream and Executive Publishing group 
2. Publish it 
3. Go to browse pools page and see the pool card exists for the same 
4. go to en/executive page and see the pool card exists there as well 
5. Click on the pool card to open up the job poster and verify you get the proper education requirement section as well
> [Urgent] add posters with executive publishing group  to browse pools page

- apps/web/src/components/Table/ResponsiveTable/Table.tsx
- apps/web/src/components/Table/ResponsiveTable/types.ts
- apps/web/src/pages/Classifications/CreateClassificationPage.tsx
- apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
- apps/web/src/pages/Classifications/components/ClassificationTable.tsx
- apps/web/src/pages/Departments/CreateDepartmentPage.tsx
- apps/web/src/pages/Departments/UpdateDepartmentPage.tsx
- apps/web/src/pages/Departments/components/DepartmentTable.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/UpdateSearchRequest.tsx
- apps/web/src/pages/SkillFamilies/CreateSkillFamilyPage.tsx
- apps/web/src/pages/SkillFamilies/UpdateSkillFamilyPage.tsx
- apps/web/src/pages/SkillFamilies/components/SkillFamilyTable.tsx
- apps/web/src/pages/Skills/CreateSkillPage.tsx
- apps/web/src/pages/Skills/components/SkillTable.tsx
- apps/web/src/pages/Teams/CreateTeamPage/components/CreateTeamForm.tsx
- apps/web/src/pages/Teams/IndexTeamPage/components/TeamTable/TeamTable.tsx
- apps/web/src/pages/Teams/IndexTeamPage/components/TeamTable/helpers.tsx
- apps/web/src/pages/Teams/UpdateTeamPage/components/UpdateTeamForm.tsx
- apps/web/src/pages/Teams/ViewTeamPage/ViewTeamPage.tsx
- apps/web/src/pages/Users/UpdateUserPage/UpdateUserPage.tsx
🤖 Resolves #8345 
Implements the state solution of #8342 in more places. 
For the most part just finding places to copy paste. 
1. Go to effected tables, adjust the filters to change the URL then test the submit and return
2. Effected tables include classifications, departments, teams, skills, skill families, users, and requests
3. Submit and return, as well as go back buttons
https://recordit.co/Orl9vqFytJ
https://recordit.co/CQf17DDn6u
> [Feature] Have more admin tables utilize `state.from` 

- apps/web/src/components/AssessmentStepTracker/utils.ts
🤖 Resolves #8620.
This PR fixes the label logic for `getDecisionInfo` when rendering the totals for **Unsuccessful** or **Successful**.
2. Navigate to `http://localhost:6006/?path=/story/components-assessment-step-tracker--with-candidates`
3. Observe count for **Unsuccessful** or **Successful** for each column
4. Ensure each count matches number of candidates in column
> [Fix] Label logic for `getDecisionInfo`

- apps/web/src/components/SkillBrowser/types.ts
- apps/web/src/components/SkillBrowser/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/EditPoolPage/components/SkillTable.tsx
🤖 Resolves #8398
Changes the title of the add skill dialog on the edit pool page.
1. Navigate to `/admin/pools`
2. Select "edit" on a draft pool
3. Scroll to the essential skills section and select to "Add a skill"
4. Confirm the dialog title is "Add a skill to this process"
5. Scroll to the asset skills section and select to "Add a skill"
6. Confirm the dialog title is "Add a skill to this process"
> [Copy] Update title of add skill dialog on edit pool page

- apps/web/src/validators/process/closingDate.ts
🤖 Resolves #4179.
This PR adds validator logic for when a `closingDate` is in the past so that the correct indicator status is shown for the section that is no longer "complete".
> [!NOTE]
> The copy for the "null" state should possibly be changed, including the action that prompt the user to "Get started", to include a message that is more generic or include a message for the state where a closing date value is in the past, but this seems out of scope for this issue and would also (possibly) change the way the other non "form" sections behave.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c765ade8d25cf1974d400da3a71954e31fcfaac/apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx#L125-L132
Assist reviewers with steps they can take to test that …
> [Fix] Validator logic for past `closingDate`

- packages/ui/src/components/Tabs/Tabs.stories.tsx
- packages/ui/src/components/Tabs/Tabs.test.tsx
- packages/ui/src/components/Tabs/Tabs.tsx
🤖 Resolves #8582 
Updates the tab styles for mobile and dark mode.
1. Run storybook `npm run storybook:design-system`
2. Navigate to the "Tabs" story
3. Confirm it matches the mockup
4. Confirm tabs work on mobile
> [Style] Update `Tab` styling

- packages/forms/src/components/DateInput/DateInput.tsx
🤖 Resolves #8537 
This adds the `id` to the date input fieldset so they can be properly targeted by anchor links.
2. Navigate to `/directive-on-digital-talent/digital-services-contracting-questionnaire`
3. Submit the form with errors (specifically for date fields)
4. Click on the link for the date field in the summary
5. Confirmit scrolls to the fieldset and focuses the first element
> [Fix] Date input error summary links

- apps/web/src/components/Footer/Footer.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #8670.
This PR updates the **Date modified** string to be sentence case to follow the site's existing copy style and corrects the **Date modified** string in French to the termium approved version _Date de modification_.
2. Navigate to any page of the application
3. Confirm footer copy **Date modified** string is sentence case
5. Confirm footer copy _Date de modification_ string exists
> [Copy] Updates date modified string

- apps/web/src/pages/Skills/components/SkillLibraryTable.tsx
🤖 Resolves #8535
Prevent seeing the error toast. 
Just filtering out claimed skills before loading them into the browser dialog. 
1. Navigate to `/en/applicant/profile-and-applications/skills`
2. Observe claimed skills not accessible from the skill browser
3. Claim a skill, it should no longer be addable
> [Bug] Resolve duplicate `UserSkill` in skill library

- package-lock.json
- packages/ui/package.json
- packages/ui/src/components/Tabs/NavTabs.stories.tsx
- packages/ui/src/components/Tabs/NavTabs.tsx
- packages/ui/src/components/Tabs/Tabs.tsx
- packages/ui/src/components/Tabs/utils.ts
- packages/ui/src/index.tsx
🤖 Resolves #8612 
Creates a new `NavTabs` component, reusing styles from the existing `Tabs` component. 
I ended up using [`@radix-ui/react-navigation-menu`](https://www.radix-ui.com/primitives/docs/components/navigation-menu) since it had a lot of nice keyboard controls and other accessibility features built in. We are only using a portion of the functionality, but now that it is installed, if we like we can also use the dropdown menus as well in the future.
```tsx
import { NavTabs } from "@gc-digital-talent/ui";
const PageHeader = () => {
return (
<NavTabs.Root {...args} aria-label="Some page navigation">
<NavTabs.List>
<NavTabs.Item>
<NavTabs.Link href="/one">One</NavTabs.Link>
</NavTabs.Item>
<NavTabs.Item>
<NavTabs.Link href="/two">Two</NavTabs.Link>
</NavTabs.Item>
</NavTabs.List> …
```
> [Feature] Create nav component

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #7658.
This PR removes the unused `poolCandidateFilters` GraphQL query.
1. Ensure no references to `poolCandidateFilters` in codebase
> [Debt] Removes `poolCandidateFilters` GraphQL query

- apps/web/src/pages/PoolCandidates/AllPoolCandidatesPage/AllPoolCandidatesPage.tsx
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/IndexPoolCandidatePage.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.tsx
🤖 Resolves #8755  
Solve the discrepancy between the dialog and what actually happens filter-wise. 
The fallback condition in `transformPoolCandidateSearchInputToFormValues` checks in the desired state and this appears in the filter dialog, however, this is after filtering occurs and is not the earliest point in the flow of page/API. 
Fallback 
Adjusted by having the desired defaults fed in at the earliest state, the component props. 
Noticed this presented an issue for view candidates for a pool, but as well as the all candidates, and view search request pages.
1. Navigate to the view candidates page for a pool, observe the filter dialog and the submitted API operation
2. Repeat for all candidates table
3. Repeat for viewing a single search request
4. Ensure filter submits works as …
> [Bug] Pool candidates table filter dialog and results out of sync

- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql
- api/app/Http/Resources/UserResource.php
- api/app/Models/User.php
- api/database/factories/UserFactory.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/ApplicantFilterTest.php
- api/tests/Feature/ApplicantTest.php
- apps/e2e/cypress/support/userCommands.ts
- apps/web/src/components/UserProfile/UserProfile.stories.tsx
- apps/web/src/pages/Applications/applicationOperations.graphql
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/poolCandidatesOperations.graphql
- apps/web/src/pages/Profile/ProfilePage/profileOperations.graphql
- apps/web/src/pages/ProfileAndApplicationsPage/applicantOperations.graphql
- apps/web/src/pages/Users/UserInformationPage/components/EmploymentEquitySection.tsx
- apps/web/src/pages/Users/userOperations.graphql
- packages/fake-data/src/fakeUsers.ts
🤖 Resolves #7662.
This PR removes the deprecated `user.isIndigenous` GraphQL field.
@esizer for going down the 🐰 🕳️. 
> [!NOTE]  
> There were a few fixes out of the original scope of this issue but are important fixes that are directly related to the `isIndigenous` field.
- [Fix scopeEquity query for indigenous_communities](https://github.com/GCTC-NTGC/gc-digital-talent/commit/663e73d8a1c2fd8c9d5f8a8b829f08ca1bf2577e): had limited any search requests to **only** `LEGACY_IS_INDIGENOUS`
- [Fix isIndigenous reference](https://github.com/GCTC-NTGC/gc-digital-talent/commit/8e5fa65007dd06b5096ddb8072cf99e597eb5993): had limited rendering to **only** `LEGACY_IS_INDIGENOUS`
1. Ensure no references to …
> [Debt] Removes `user.isIndigenous` GraphQL field

- apps/web/src/components/PoolCard/PoolCard.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/utils.tsx
🤖 Resolves #8770 
Ensures that the "Apply on or before date" is the same in all timezones - it is formatted as belonging to Pacific timezone.
This is to avoid a situation where it said "Apply on or before Dec 14" but the poster actually closes at 3am on Dec 14. The solution is just to format the date as it would appear in Pacific timezone, instead of local timezone.
1. Edit the database to ensure you have a job poster in your local environment which closes at 07:59:00 UTC on some day. (Or you can create a new job poster via admin portal.)
2. Look at the Job Poster. The "Apply on or before date" should match the Pacific time date which appears in the detailed modal.
3. The same date should appear on …
> Poster Deadline timezone fix

- api/app/Providers/AuthServiceProvider.php
- api/tests/Feature/AuthServiceProviderTest.php
🤖 Resolves #8722.
This PR fixes a case where an array was trying to be sent to a string in `AuthServiceProvider`.
This change happened as part of #6547 when `Log::notice` was replaced with `AuthenticationException`. `Log::notice` accepts an array as an argument but `AuthenticationException` does not: https://github.com/GCTC-NTGC/gc-digital-talent/pull/6547/commits/f312838a786d9f1a40391cda480f0dc886ee84d0#diff-43896043b9f0d9bf8ee8679ffca9a195c2e149cb9db46e7d1d5ada0a1b47721eL83-R91
1. Use 🧠 logic (I have no idea how to trigger the auth exception locally 😟)
> [Fix] Returns string instead of an array in `AuthServiceProvider`

- apps/e2e/cypress.d.ts
- apps/e2e/cypress/support/e2e.ts
- apps/e2e/cypress/support/featureFlagCommands.ts
- apps/e2e/package.json
- documentation/environment-variables.md
- package-lock.json
🤖 Resolves #4227 
This adds a command that allows us to override our feature flags.
> [!NOTE]
> I was able to get a working example so I posted this PR. Though, I imagine there are other ways of accomplishing this and it does not need to result in a merge.
The approach taken is to intercept and override the `config.js` file on our server. We do this by:
1. Reading the `.env` file in `apps/web`.
2. Spreading any overridden flags (written as an object)
3. Then, we loop over it using the [`Map.prototype.set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/set) method to create the new config
4. Then, we return the new, custom `config.js` file
It is pretty easy to do this, but, similar to aliasing requests, it matters where you use it. It is best to call …
> [Feature] Allow overriding feature flags in cypress

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInformation.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/SkillWithExperiences.tsx
🤖 Resolves #8768 
This fixes an issue where skills were missing from the application print document when the record of desicison flag was set to true.
> [!NOTE]
> While working on this, I noticed we were renders "N/A" when a skill description did not exist. This looked broken to me so I opted to just not render it. Hope that is okay 😅 
1. Make sure you have `FEATURE_RECORD_OF_DECISION=true` in your `.env`
3. Navigate to an application that consists of skills (some seeded data does not)
4. Click on the "Print application" button
5. Confirm the proper skills appear in the print document
> [Fix] Display skills for print

- apps/web/src/hooks/useRequiredParams.ts
🤖 Resolves #8724 
This solves an issue where malformed UUIDs in the URL were not throwing errors.
> [!NOTE]
> A big thanks to @petertgiles for helping play detective and getting to the root of the issue! 🙇‍♀️ 🕵️ 
We encountered an error in our logs where malformed UUIDs were making it to the API. With the help of @petertgiles we were able to determine it was attempting to retrieve a Pool with a specific ID, but there was a stray `]` at the end of the string. Reviewing our code, this did not seem to be a dev error.
Further testing, I found that if you added any extra data to the start or end of a UUID in the URL, it was not being caught by our `useRequiredParams` hook even when the `enforceUUID` option was set to true. Digging deeper, I noticed the regex was only checking to see if the …
> [Fix] Improve UUID enforcement on URL params

- apps/web/src/pages/Profile/ExperienceFormPage/components/ExperienceSkills.tsx
🤖 Resolves #8778
Find and resolve the constraint violation
Given the production environment has limited ways to edit the skill-userskill-experience grouping, where to look was narrowed. 
Setting skill-library to false and exploring I could not replicate the matter except for in one method, attempting to sync the same skill twice in one edit.
The soft deletion and restore seemed without issue to me. 
Solved then by preventing you from selecting the same skill multiple times. 
1. Set skill library to false
2. Be unable to replicate a duplication error from the career timeline
Off main
Pick the same skill twice
Observe console error
Update fails
> [Bug] Duplicate `experience_user_skill_unique`

- api/graphql/schema.graphql
- api/tests/Feature/PoolCandidateTest.php
🤖 Resolves #8808 
This adds the `@canOnParent` directive to the notes field on the `PoolCandidate` model in our GraphQL schema. It uses the `viewAssessmentResults` permission allowing access to only:
- Pool operator (who is part of the team that owns the pool)
- Platform admin
I hope the test I wrote is good enough, it basically checks that we get the notes field for the users who should see it as well as a auth error on those that cannot. I'm hoping it is not over-testing but I wanted to cover all the possibilities 🤷‍♀️ 
```graphql
query MyInfo {
poolCandidate(id: "{id}") {
id
notes
}
}
```
1. Login as an applicant `applicant@test.com`
2. Submit an application
3. Logout and log back in as an admin `admin@test.com`
4. Navigate to the application you just submitted and add some notes to it …
> [Fix] Prevent unauthorized users from accessing pool candidate notes

- apps/web/src/pages/Users/UserInformationPage/components/EmploymentEquitySection.tsx
🤖 Resolves #8825.
This PR fixes the conditional logic for `isIndigenous` in `EmploymentEquitySection`.
1. Log in as a platform admin
2. In the users table, find a user who has claimed membership in an indigenous community and one who has not (you can do this on your own profile, for simplicity)
3. Compare the Employment Equity blocks on the User Information and User Profile pages
> [Fix] `isIndigenous` `EmploymentEquitySection` logic

- apps/web/src/components/FilterDialog/FilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/components/SearchRequestTable/components/SearchRequestFilterDialog.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/IndexUserPage/components/UserFilterDialog.tsx
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
🤖 Resolves #8776 
This fixes the filter count for the dialog to only display the number of filters actually in use.
It appears as though the functionality we want on the clear button is not easily possible. This includes a solution but has been disabled while we revisit it. While it does clear the filters, we are unsure if this is actually what we want based on how we actually use the filters.
The odd stuff comes up when we indiscriminately clear filters, it affects the UI in an unexpected way. This is most notable on radio buttons where the true "empty" value is not empty. 
The current ideas are:
1. Force devs to pass in the expected "empty" value for specific inputs so the generic form is aware of them
2. Override the value for things like radio buttons to be an empty string (this will …
> [Fix] Admin table filter dialog count and clearing

- apps/web/src/components/ExperienceFormFields/AwardFields.tsx
- apps/web/src/components/ExperienceFormFields/CommunityFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelineEditPage/components/ExperienceEditForm.tsx
- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/errorMessages.ts
🤖 Resolves #8725
Uses `maxLength` rules for inputs, as well as correct toasting/action on errored updates. 
Elected to check if an error is returned in the response object, given the nested data object contains 10 possibles keys (5 experiences x 2 mutation types) the truthy check wasn't working right so I thought it would be easier to assert on `res.error` instead. 
1. Head to career timeline and the experiences section of the application flow
2. Check you cannot trigger the value too long error for VARCHAR database error
3. Check failed operations do not return a success toast
A suggestion to check the third option. Open an experience, then open and soft-delete it in adminer, then attempt to update it in app. 
Generate strings of a certain character count with https://loremipsum360.com/
> [Bug] Add character limits to inputs for experience forms

- api/app/Http/Controllers/AuthController.php
🤖 Resolves #8723 
Check the id token is a string, if it isn't throw an exception. 
Not entirely sure of the best way, an idea below
1. Set id token variable to a different type, like an integer value, right before the `throw_unless()` on `$idToken`
2. Attempt logging in, observe exception message
> [Bug] Exception thrown on id token check

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolStatusTable/PoolStatusTable.tsx
- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/components/Table/accessors.tsx
- apps/web/src/components/Table/cells.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
🤖 Resolves #8838 
Fixes the issue with tables not sorting date columns properly.
We had the `accessor` and `cells` mixed up 😅 . This updates it so the accessor returns a `Date` and adds a `cell` to handle the formatting of said date.
> [!NOTE]
> We have been sorting the `PoolTable`  by `ceatedDate` so I was hesitant to change this. Do we still want to be changing this to `updatedDate`.
2. Navigate to tables in the admin
3. Sort any date columns
4. Confirm they are sorted properly
> [Fix] Table date sort

- api/app/Http/Controllers/AuthController.php
🤖 Resolves #8777 
Add retrying and a logging line to the auth callback function, the client request method. 
Attempted to just follow documentation for implementation, not 100% on things. 
https://laravel.com/docs/10.x/http-client
1. Can login successfully
2. ?
> [Bug] Retrying call to auth endpoint

- apps/web/src/components/SkillBrowser/utils.ts
🤖 Resolves #8844 
Fixes the count being `0` when the "All categories" option is selected in the skill browser.
Not sure why typescript didn't catch this but it was because we passed in `"all"` as a skill category which caused the filter to occur. But, since "all" is not a category, it always showed `0`. 
2. Navigate to `/users/{userId}/personal-information/career-timeline/create`
3. Click the "Add a skill" button to invoke the dialog
4. Select "All categories" in the category dropdown
5. Confirm the "All skills" option in the skill family select indicates the full skill count
6. Select a different category
7. Confirm the "All skills" option in the skill family select indicates …
> [Fix] "All skills" skill count in family select

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/poolCandidatesOperations.graphql
🤖 Resolves #8820 
Adds the marker to require a non-null input (array of something). 
1. Build unaffected
2. Can exercise the pool candidates table and nothing changed
> [Debt] Add non-nullable marker to query `poolCandidates`

- apps/web/src/components/ExperienceFormFields/ErrorSummary.tsx
- packages/forms/src/components/BasicForm.tsx
🤖 Resolves #8846 
Fixes the focus of an error summary on a second attempt to submit.
The values we were using the effect dependencies array were not primitives. This meant the callback was never re-fired. This updates it to use the flattened array of input IDs which is primitive. This allows the callback to be called when it updates meaning we can focus the summary every time errors change on submit.
2. Navigate to a basic form that has labels (profile forms work well here)
3. Submit with errors, confirming the summary gets focus
4. Fix on error or introduce more
5. Re submit, confirming the summary is once again focused
6. Navigate to the experience form
7. Repeat steps 3-5
> [Fix] Error summary second focus

- apps/web/src/pages/Skills/components/UpdateSkillShowcase.tsx
🤖 Resolves #8814 
Quick (not great) fix for for the skills showcase pages not updating without a full page refresh.
This uses the `useFieldArray` function `append` to add the skill after the mutation is successful. It is a little janky but works for our purposes until we can revisit the functionality for this type of repeatable item.
2. Login as an applicant and navigate to a skill showcase `/applicant/profile-and-applications/skills/showcase/*`
3. Add a skill in your library
4. Confirm it is added to the list without a refresh
5. Add a skill not in your library
6. Confirm it is added to the list without a refresh
7. Change the order
8. Save and confirm the expected values were …
> [Fix] Update skill showcase without refresh

- apps/web/src/lang/fr.json
🤖 Resolves #8521 
This updates the translation of "Screening questions" to a more succinct message _Questions de sélection_.
The consolidation happened in #8899 but it seems we used the longer version. DCM and the copy writers have requested the shorter _Questions de sélection_.
2. Navigate to a page that mentions screening questions
3. Change to French language
4. Confirm the copy reads _Questions de sélection_
> [Copy] Update screening question translation

- apps/web/src/components/ExperienceFormFields/AwardFields.tsx
- apps/web/src/components/ExperienceFormFields/CommunityFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields.tsx
- packages/forms/src/components/Input/Input.tsx
🤖 Resolves #8841 
Adds a default max length to the `<Input />` component.
The `<Input />` almost always maps to a `varchar(255)` in the database so setting this default max length seemed most logical. It can still be override using the `rules` prop where appropriate. 
2. Navigate to any form with an normal text, number, email, telephone, password or search input on it
3. Add more than 255 characters to the fields
4. Attempt to submit the form
5. Confirm you get the character limit error message
> [Debt] Add default max length to `Input`

- apps/web/src/components/FilterDialog/FilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/IndexPoolCandidatePage.tsx
- packages/forms/src/components/HiddenInput/HiddenInput.tsx
- packages/forms/src/index.tsx
🤖 Resolves #5321 
Hides the pool filter when on the "view candidates" page for a specific pool.
Since the admin is within the specific context of a pool, it does not make sense to allow them to filter by different pools. We also now has the "all pool candidates" page that allows this. So, we are hiding this filter. In order to do this a few things were done:
- Added a hidden input component that is registered with `react-hook-form`
- Allow modifying the filter count on the filter dialog button so we can omit hidden filters from the count
- Used addition here to make it clear what is happening. I currently can't think of a reason why we would want to increase the number right now but seeing  a negative integer makes more sense to me 🤷‍♀️ 
Assist reviewers with steps they can take to test …
> [Feature] Hide pool filter on specific pool candidate page

- api/app/Models/AssessmentResult.php
- api/database/factories/AssessmentResultFactory.php
- api/database/migrations/2024_01_04_144452_add_notes_column_assessment_results_table.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.stories.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialogForm.tsx
- apps/web/src/components/ScreeningDecisions/useLabels.ts
- apps/web/src/components/ScreeningDecisions/utils.ts
🤖 Resolves #8729 
Adds the notes test column to the assessment results table and dialog form.
1. Refresh API `docker-compose run --rm maintenance bash refresh_api.sh`
3. Run storybook `npm run storybook:web`
4. Navigagte to the "AssessmentDescisionDialog -> Generic" story
5. Fill out some notes
6. Submit
7. Confirm they appear in the action data
8. Seed the database `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan migrate:fresh --seed"`
9. Open the database and find an assessment result with notes (or insert one) and copy the pool candidate ID
10. Navigate to `/graphiql`
11. Run a query for the notes using the pool candidate ID copied in step 9
12. Confirm it shows up in the result
```graphql
query AssessmentResults{
poolCandidate(id: …
```
> [Feature] Add notes field to assessment results

- api/database/migrations/2024_01_08_203349_location_exemption_to_text.php
🤖 Resolves #8837
Migrate the column to type text. 
1. Migrate forward and back successfully 
2. Location exemptions not destroyed
3. Can fill out exemptions on your profile with many more characters now
> [Bug] Location exemptions set to text column

- apps/web/src/components/UserSkillFormFields/UserSkillFormFields.tsx
- apps/web/src/pages/Applications/ApplicationEducationPage/utils.tsx
- packages/forms/src/components/CheckButton/CheckButton.tsx
- packages/forms/src/components/Checkbox/Checkbox.tsx
- packages/forms/src/components/Checklist/Checklist.tsx
- packages/forms/src/components/RadioGroup/RadioGroup.stories.tsx
- packages/forms/src/components/RadioGroup/RadioGroup.tsx
- packages/forms/src/utils/getCheckboxRadioStyles.ts
🤖 Resolves #8965 
Increases the total touch target of checkboxes and radio buttons. Also, improves the styling to better match our current design system.
>[!NOTE]
> This was tested in safari and working as expected.
2. Navigate to a form or, start storybook
3. Ensure the touch target is expanded in check lists and radio groups
4. Ensure they still function as expected
> [a11y] Increase touch target for checkbox/radio buttons
