- api/app/Enums/AssessmentDecision.php
- api/database/factories/AssessmentResultFactory.php
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.stories.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/AssessmentStepTracker/ResultsDetails.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialogForm.tsx
- apps/web/src/components/ScreeningDecisions/useOptions.ts
- apps/web/src/components/ScreeningDecisions/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/utils/assessmentResults.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #8644 
Updates the assessment decisions adding an "on hold" and changing "not sure" to be `null`.
I was hoping to get something in the `App\Enums\AssessmentDecision` to be `NOT_SURE = null` but it requires a `string|int` and massaging the input seemed like too much trouble. Instead, a constant was added at `~/utils/assessmentResults` along with a modified `AssessmentDecision` type to allow it to be used in specific spots and then it is massaged on frontend. I'm not super happy with this approach, if anyone else has a better idea I'd be happy to try it out 😄 .
1. Build `npm run run dev`
2. Start storybook `npm run storybook:web`
3. Navigate to the "Assessment Step Tracker" story
4. Confirm …
> [Feature] Update assessment decisions

- api/database/factories/PoolCandidateFactory.php
- api/database/migrations/2023_12_05_210313_add_bookmarked_column_to_pool_candidates.php
🤖 Resolves #8977 
Without a default value/nullable the bookmark column was causing issues for existing rows. This updates the migration to make it nullable with null as a default value. As well, it makes the field optional in the factory so we can simulate this locally as well.
I wasn't sure if we had already ran this migration but the AC mentioned updating the migration instead of creating a new one. If we have and it would be safer to create a new migration, let me know and I can fix that.
```graphql
mutation ToggleBookmark_Mutation($id: ID!) {
togglePoolCandidateBookmark(id: $id)
}
```
1. Run migrations `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan migrate"`
2. Navigate to `/graphiql`
3. Attempt to bookmark a candidate
4. Confirm there is no error
5. …
> [Fix] Bookmark column to support `null`

- apps/web/src/lang/fr.json
- apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineAndRecruitment.tsx
🤖 Resolves #7936 
Fixes a place on the career timeline page where we were self referencing "career timeline" in the description of what it was.
Tested with JAWS, NVDA, Narrator and it read it as a noun properly.
2. Login as an applicant
3. Navigate to `/users/{userId}/personal-information/career-timeline`
4. Confirm the first paragraph uses "resume" and not "career timeline"
5. **Bonus** Try it out with some screen readers and confirm the term "resume" is read out properly
> [Fix] Career timeline self reference

- api/composer.lock
- api/programmatic-types.graphql
- api/schema-directives.graphql
- api/tests/Unit/resources/README.md
- api/tests/Unit/resources/jwks.json
🤖 Resolves #9006 
This branch bumps our jwt dependency and fixes a flaw in our fake data used for testing.
It seems like the base64 encoding used in JWT is not supposed to have any padding '=' characters.  I removed the padding in our fake endpoint and all tests are passing.  See "Base64url Encoding" in section 2 of [https://www.rfc-editor.org/rfc/rfc7515.txt](https://www.rfc-editor.org/rfc/rfc7515.txt).
When I manually ran the composer update there were some unrelated updates applied to the graphql files.
> [!TIP]
> There was some linting happening.  I recommend viewing the diffs with whitespace changes hidden.
- Rebuild with Sign In Canada configured.
- Ensure you can login, refresh, and logout.
- Ensure phpunit tests pass.
> [Fix] Bump jwt library

- apps/web/src/components/SkillBrowser/SkillBrowser.tsx
- apps/web/src/components/SkillBrowser/SkillSelection.tsx
🤖 Resolves #8895
Resolves the bug with sorting of skills. 
A sort that well sorts as expected but also handles French special characters was added in the inline selector, I used it in more places. As I also noticed skill families wasn't sorted either. 
1. Observe skills, skill families being sorted correctly in English and French
2. Inline selector exists on the find talent page, dialog variant like in the issue found on editing experiences
> [Bug] Skill browser sorting of skills

- packages/ui/src/components/ButtonLinkContent/ButtonLinkContent.tsx
🤖 Resolves #9028 
- Reverts back to previous styling on ButtonLinkContent. 
- The issue was caused when trying to line up icons with longer text on l-width screen. However, the formatted messages containing a link seems to be effected which was missed in review.
1. Build app `npm run build`
3. Ensure links across site are lined up correctly (Specifically formattedMessage containing links). One example, is the education requirement step during application process.
> [Bug] Fix inline link styling

- api/app/Http/Controllers/SupportController.php
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
- packages/i18n/package.json
🤖 Resolves #8897 
This branch fixes the crash to a blank white screen on the support page.
The culprit of the app crash was that our toasts are not in the intl provider and our error message used the Link component which calls an intl function.  For a quick fix, I changed it a regular `a` tag.  I opened  #9037 for a more thorough review.
There was a desire to ensure that an email address was always displayed for errors.  So I removed the two other error messages in favour of the single generic one with the email.  I did a bit of refactoring on the submit handler to use `await` to make it easier to read, too.
There was also a desire for better logging around failed ticket creation so I added that as well.  I changed the response code to 500 which makes more sense, I think, and will make it …
> [Fix] Fix the blank white error on the support page

- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/errorMessages.ts
🤖 Resolves #8851 
- Updates the required validation with more explicit error message.
From:
EN: {Label}: This field is required.
FR: {Label}: Ce champ est obligatoire.
To: 
EN: {Label}: This field is required. Please enter a value.
FR: {Label}: Ce champ est obligatoire. Veuillez inscrire une valeur.
1. Cause a required error message to pop up and ensure correct copy shows up.
> [Accessibility] Update required validation with more explicit error message

- apps/web/src/components/PoolCandidatesTable/poolCandidateCsv.tsx
- apps/web/src/pages/Users/IndexUserPage/components/userCsv.tsx
- apps/web/src/utils/csvUtils.tsx
- packages/ui/src/components/Link/DownloadCsv.tsx
🤖 Resolves #9018 
Applies some basic sanitization to strings used in CSV downloads to avoid accidently creating new records.
We had some sanitization on experience details but other user created data was not being sanitized properly. The data containing double quotes and line breaks were leading to CSV interpreting them as new columns and rows, breaking the CSV.
In order to fix this we have:
- Sanitized user created strings by 
- replacing " with "" (way of escaping in CSVs) which was leading to new columns
- removing line breaks `\r\n` which was leading to new rows (records)
- added a column wrapper character (") which wraps each column of data to avoid accidental new columns …
> [Fix] Errant new records in CSV download

- apps/e2e/cypress/e2e/admin/pools.cy.ts
- apps/web/src/pages/Pools/PoolLayout.tsx
- apps/web/src/pages/Pools/poolOperations.graphql
🤖 Resolves #8307 
- Add team name subtitle to pool layout.
2. Go to all "pool" pages and ensure team name shows up. 
- `http://localhost:8000/en/admin/pools/1e390f8d-e2b5-402f-8b7d-3594798c7433`
- http://localhost:8000/en/admin/pools/1e390f8d-e2b5-402f-8b7d-3594798c7433/edit
- http://localhost:8000/en/admin/pools/1e390f8d-e2b5-402f-8b7d-3594798c7433/screening
- http://localhost:8000/en/admin/pools/1e390f8d-e2b5-402f-8b7d-3594798c7433/pool-candidates
> [Bug] Add team name subtitle to pool layout

- api/app/Http/Controllers/SupportController.php
🤖 Resolves #9036 
No longer outputting the endpoint response into the API, just a simple success/error. 
Error toasting and logging of errors already present. 
1. Not sure, does it need to be pushed to dev vertical?
2. Messages appear instead of json
> [Bug] Don't output endpoint response

- packages/forms/src/components/DateInput/DateInput.tsx
🤖 Resolves #9063 
Updates the DateInput field to check equality based on the used fields.
2. Login as an applicant
3. Navigate to the career timeline page `/en/users/{id}/personal-information/career-timeline`
4. Select to edit an experience with no end date
5. Set an end date before the start date
6. Confirm error message appears on submit
7. Set an end date at the same time as the start date
8. Confirm form successfully submits
9. Manually change the date field to include day and repeat steps 4-8
10. Manually change the date field to only the year and repeat steps 4-8
> Date fields limit equality check to active fields

- packages/ui/src/components/Tabs/utils.ts
🤖 Resolves #8785 
- Updates tab active + focused font color to black
1. Build app `npm run build`
3. Go to pools table and select a pool
4. Click and tab through TabNav
5. Ensure all states matches the states in the image above
> [Bug] Update tab active + focused styles

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/utils.ts
- apps/web/src/types/searchRequest.ts
🤖 Resolves #9075 
Adds a new button to the search page that allows users to request candidates from all pools.
This button always appears, regardless of how many pools/candidates are returned by the search in order to be forward thinking (candidates may appear in results in the future).
1. Build the application `npm run dev`
3. Create two pools with the same classification and stream
4. Add _different_ users to both pools, setting their status to "Qualified available"
1. Run a search request that has overlap between the two pools so they appear
2. Submit the request using the new button
3. Navigate to that request in the admin interface
4. Confirm it shows up with candidates and the …
> [Feature] New all pools request button

- apps/web/src/components/Context/ContextProvider.tsx
- apps/web/src/main.tsx
- packages/toast/src/components/Toast/toast.css
🤖 Resolves #9037
- Adds `<Toast />` into ContextContainer, nesting it within the IntlProvider.
1. Build app `npm run build`
2. Add a component calling useIntl (e.g. Button) into a toast.error or toast.success message. 
3. Ensure component appears without crashing page.
4. Ensure other toast events still function correctly.
Example of change in SupportForm.tsx:
```jsx
toast.error(
<Button>
{intl.formatMessage(
{
defaultMessage:
"Sorry, something went wrong. Please email <anchorTag>{emailAddress}</anchorTag> and mention this error code: {errorCode}.",
id: "rNVDaA",
description: "Support form toast message error",
},
{
anchorTag,
emailAddress: TALENTSEARCH_SUPPORT_EMAIL,
errorCode: errorMessage,
},
)}
</Button>,
{ autoClose: 20000 },
);
```
> [Bug] Add toast into context container

- documentation/accessibility.md
🤖 Resolves #8843 
Adds a very broad, general checklist to consider when doing manual accessibility testing.
> [!NOTE]
> Removed some old reference to pa11y since we never adopted it.
This list is non-exhaustive and non-specific. It is more of a general idea of things to consider while testing. Not every item needs to be completed as part of a manual test since it is not applicable. This acts more of a guide than anything else and get you thinking of what kinds of things to be testing.
> [Docs] Add manuall a11y testing steps

- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
🤖 Resolves #9061
Have the total displayed for client side tables be the result after filters were applied. 
Probed around and found a method to use and a place to plug it in. 
1. Ensure API-driven tables unaffected
2. Client side table pagination updated, counts in sync with filtering
> [Bug] Have filtered total display for client side table

- api/app/Policies/AssessmentResultPolicy.php
- api/app/Policies/PoolCandidatePolicy.php
- api/config/rolepermission.php
- api/database/factories/UserFactory.php
- api/graphql/schema.graphql
- api/tests/Feature/PoolCandidateTest.php
- api/tests/Feature/RolePermissionTest.php
- api/tests/Unit/PoolCandidatePolicyTest.php
- apps/web/src/components/Router.tsx
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/AssessmentPlanBuilderPage.tsx
🤖 Resolves #9044
Make sure the permissions are correct so that users with a single admin permission (ie RequestResponder or PoolOperator) can see the pools and PoolCandidates they should be able to.
For those among us who are against the proliferation of permissions, I apologize! I added any/team + view/update permissions specific to applicationNotes, applicationStatus, assessmentPlan, and assessmentResult, because I realized the cross section of who can do what with each of those resources differes _slightly_ across roles.
The [roles and permissions](https://docs.google.com/spreadsheets/d/1RC7wufxwjLEvaEunHsfZfOzBefg218dvvzkDwKSiQjI/edit#gid=428263758) spreadsheet has been updated as well.
0. Run …
> Fix request responder note permission

- apps/web/src/components/SkillRankCard/SkillRankListItem.tsx
- apps/web/src/pages/Skills/UpdateUserSkillPage.tsx
🤖 Resolves #9062 
This updates the update user skill page to return to the skill showcase when that is where the user came from. In addition, the breadcrumbs were not accurate so have been updated to also indicate that the skill showcase is included when coming from there.
It seems that the user can only get here from the library or showcase. So, instead of using a path I simply used "showcase" so we can update the return path and breadcrumbs based on that.
2. Login as an applicant
3. Navigate to your skill showcase `/applicant/profile-and-applications/skills/showcase`
4. If a skill does not exist yet, add one
5. Click on a skill title to edit it
6. Confirm the a …
> [Fix] Update user skill return path

- apps/web/src/components/AssessmentStepTracker/ResultsDetails.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
- apps/web/src/utils/poolCandidate.ts
🤖 Resolves #9131 
Adds a badge to the header of a pool candidate showing the "final decision" from the candidate table with some additional detail. If the user has the "to assess" status, it adds the current step from the assessment step tracker and an icon.
1. Ensure you have `FEATURE_RECORD_OF_DECISION=true` in your `.env` file
3. Login as admin and navigate to `/admin/pool-candidates`
4. Click on the "view" link for candidates with different final decisions
5. Confirm the badge matches the descision
6. Confirm "to assess" has the triangle icon along with the current step
> [Feature] Add status badge to candidate page header

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/IAPManagerHomePage/IAPManagerHomePage.tsx
🤖 Resolves #9107 
Updates the French copy for the IAP manager page.
While doing this, I noticed we had some invalid HTML for the blockquote so re-arranged some stuff to fix that as well.
2. Navigate to the IAP manager page `/fr/indigenous-it-apprentice/hire`
3. Confirm copy matches [the supplied file](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9107)
> [Copy] Update IAP manager homepage French copy

- packages/forms/src/components/Combobox/Multi.tsx
🤖 Resolves #9060 
Fixes an issue where the input was not empty after activating the clear action.
2. Navigate to the search talent page `/search`
3. Scroll down to the "Skills selection" section
4. Select a family to display the skill picker
5. Type something into the text input
6. Active the "X" button in the input
7. Confirm the input is emptied and focused
> [Fix] "X" button clears multi combobox input

- api/app/Http/Controllers/AuthController.php
🤖 Resolves #9148.
This PR changes the response type to JSON for the refresh endpoint.
1. Navigate to `http://localhost:8000/refresh?refresh_token=test`
2. Observe **Content-type** value is **application/json**
> [Fix] Updates refresh endpoint response type to json

- apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
🤖 Resolves #9027 
Moves the error message for skill requirements on the application so that it no longer appears to be associated with the optional skills.
2. Login and an applicant `applicant@test.com`
3. Start an application
4. Continue through the process until the "Skill requirements" page
5. Force an error
6. Scroll to the bottom and confirm the error message appears below the `Separator`
> [Fix] Update position of skill error

- apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchResultCard.tsx
🤖 Resolves #9089
Applies some visual updates to the SearchResultCard.
1. Run `npm run dev`
2. Navigate to the search page `/en/search`
3. Verify the SearchResultCards appear as expected
4. Verify functionality is unchanged
> Visual updates to SearchResultCard

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/components/AssessmentStepTracker/Filters.tsx
- apps/web/src/components/AssessmentStepTracker/testData.ts
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/messages/poolCandidateMessages.ts
- packages/jest-helpers/src/index.ts
- packages/jest-helpers/src/mocks/resizeObserver.ts
🤖 Resolves #9016 
Adds some basic filters for the `AssessmentStepTracker` component.
- Candidate name search
- Status (decision) toggles
The test I wrote only test one filter at a time. Would it be worth it to try some combinations of filters? 🤔 
2. Open storybook `npm run storybook:web`
3. Navigate to the "Assessment Step Tracker" story
4. Play around with the filters
5. Confirm they act as you expect
> [Feature] Basic filters for `AssessmentStepTracker`

- apps/web/webpack.base.js
🤖 Resolves #9134.
This PR changes meta URL to production value so that social sharing works in production.
> [!NOTE]  
> This fix should be temporary as these values should be able to changed for testing. 
1. Inspect page
2. Verify `property="og:url"` value is https://talent.canada.ca/images/digital-talent/banner.jpg
> [Fix] Changes meta URL to production value

- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/graphql/schema.graphql
🤖 Resolves #9153 
This adds better protection to the `Pool.poolCandidates` field in our schema.
As far as Peter and I could tell, this was happening during our auth flakiness the other week(?). What was happening was, authenticated users were accessing the `Pool.poolCandidates` field in some weird time when they were not authenticated.
Since our `pools` query is not guarded, they could access that.  But we did not have a `@guard` directive on the `poolCandidates` field. The `@can` should have saw no user and rejected it but for some reason, the scope is evaluated first here 🤷‍♀️ .
So, this did two things:
- Added a `@guard` to `Pool.poolCandidates` (we only want authenticated users accessing this anyway)
- Did a quick check in the scope to make sure a user exists just in case (this is a …
> [Fix] Prevent `PoolCandidate` authorized to view scope error

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
🤖 Resolves #9199 
Adds the following breadcrumbs to the ROD admin pool candidate page.
Home > Processes > {poolName} > Screening and Assessment > {candidateName}
"Processes" was used in favour of "Recruitments". It seems like we were planning on using "Recruitments" at an earlier stage but decided upon "Processes" instead so the ticket was out of date.
3. Navigate to `/admin/pool-candidates`
4. Click on the view link for a candidate
5. Confirm the breadcrumbs appear with the appropriate links and labels
> [Feature] Add breadcrumbs to ROD application page

- api/app/Console/Commands/RemoveExpiryDates.php
🤖 Resolves #9136 
Add artisan command to null out expiry dates for pool candidates with certain statuses. 
1. Seed fresh
2. Run command
3. Observe candidates in database by updated at, the specified status ones should have been updated
`php artisan app:wipe-expiryDates`
Run
`php artisan app:wipe-expiryDates`
> [Tooling] Add artisan command to null expiry dates

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
🤖 Resolves #9221
Status column wasn't able to be shown on the Pool Candidates table with Record of Decision flag on.
1. With Record of Decision flag OFF, status column is shown on the Pool Candidates table and locked, cannot be hidden
2. Turn Record of Decision flag ON and rebuild
3. Refresh Pool Candidates table page
4. Status column is hidden, but can be shown.
> Enable hiding of status column if Record of Decision flag is true

- packages/forms/src/components/Combobox/Multi.tsx
🤖 Resolves #9239 
Fixes the clear button on the mutli combobox to also reset the options in the dropdown.
3. Type in the skill combobox
4. Click the "X" to clear
5. Without typing, open the dropdown
6. Confirm the options were reset
> [Fix] Combox clear button resets options

- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/ApplicationPrintButton.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/ApplicationPrintDocument.tsx
- apps/web/src/pages/Users/AdminUserProfilePage/AdminUserProfilePage.tsx
- apps/web/src/pages/Users/AdminUserProfilePage/components/SingleUserProfilePrintButton.tsx
🤖 Resolves #9201 
Adds a dropdown allowing users to choose either a full or anonymous application print document.
During developing this, I noticed that the "Print profile" button (where I got the code for this) does not properly print an redacted profile when on the "User profile" page. So, this had to use a different approach of two documents and two handlers. 
I created a ticket (https://github.com/GCTC-NTGC/gc-digital-talent/issues/9209) to look into this in hopes that someone has a better solution. Or at least fix the existing user profile print.
3. Navigate to `/admin/pool-candidates`
4. View an application for a user
5. Active the "Print application" …
> [Feature] Anonymous application print

- apps/web/src/components/AssessmentStepTracker/utils.ts
🤖 Resolves #9241 
Fixes the search on the step tracker to be case insensitve
1. Run storybook `npm run storybook:web`
2. Navigate to the "Assessment Step Tracker" story
3. Use the search typing in queries that do not match the case of results
4. Confirm they appear in the results regardless of case
> [Fix] Step tracker search case insensitve

- apps/web/.env.example
- apps/web/public/config.ejs
- apps/web/src/components/Header/Header.tsx
- apps/web/src/components/ThemeSwitcher/ThemeSwitcher.test.tsx
- apps/web/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/web/src/lang/fr.json
- package-lock.json
- packages/env/src/utils.ts
- packages/theme/package.json
- packages/theme/src/components/ThemeProvider.tsx
- packages/ui/src/components/ToggleGroup/ToggleGroup.stories.tsx
- packages/ui/src/components/ToggleGroup/ToggleGroup.test.tsx
- packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
🤖 Resolves #4033 
Adds the theme switcher to the header with the beta label.
This also includes some changes to the base `ToggleGroup` component, removing the option to change the colour.
> [!TIP]
> If you don't want to change your system settings and just emulate it, here is how you do that you can follow [this guide](https://devtoolstips.org/tips/en/emulate-color-schemes/) for each browser.
2. Navigate to home page
3. Confirm the switcher appears and matches [the mockup](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=11-4115&mode=design&t=PUAWqgbAuvjPXtIT-0)
4. Confirm it starts of the first option
5. Change modes confirming it updates the …
> [Feature] Theme mode switcher

- api/app/Http/Controllers/AuthController.php
🤖 Resolves #9147
This branch turns off exception throwing when requesting a token and instead manually checks for a failed response.  This allows us to do clearer logging.
1. Configure your environment to use the Sign In Canada test server.
2. Break the code so that the authcallback token request to fail.  This is an easy way to do it:
3. Try to log in.
Optional:
Set 
```
APP_ENV=production
APP_DEBUG=false
```
so you can see what the users will see.
> [Debt] Handle logging for tokens better

- .github/workflows/chromatic.yml
- chromatic.config.json
🤖 Resolves #6189.
This PR eliminates warning about a missing build directory for Storybook.
@esizer
1. Verify the error **Unexpected build directory** does not occur in the Chromatic GitHub workflow: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/7849469084/job/21422991428#step:8:48
> [Tooling] Adds Chromatic config

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/IAPManagerHomePage/IAPManagerHomePage.tsx
🤖 Resolves #9231.
This PR changes the word **reconciliation** to lowercase in English on the IAP Manager Homepage.
No changes to the French copy as it is already lowercase.
2. Navigate to `/indigenous-it-apprentice/hire`
3. Verify Reconciliation copy is lowercase
> [Copy] Changes case of Reconciliation to lowercase

- apps/web/src/lang/fr.json
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #9235
Changes the copy to "Talent placement". 
1. With RoD on navigate to `/en/admin/pools/:id/pool-candidates`
2. Observe tabs
> [Copy] Rename candidates tab for a process

- apps/web/src/components/Layout/AdminLayout/AdminLayout.tsx
🤖 Resolves #9195.
This PR updates `active` matching logic for the **Skills** admin nav item.
> [!NOTE]  
> Although this fixes active for `/admin/settings/skills`, `/admin/settings/skills/:skill-id/edit` and `/admin/settings/skills/create` will not match because of the way the paths are set up. Not sure there is a way to fix those without changing their paths.
@esizer: https://github.com/GCTC-NTGC/gc-digital-talent/issues/9195#issuecomment-1924661000
2. Navigate to `/admin/settings/skills/families`
3. Verify that only **Skill Families** is active in nav
4. Navigate to `/admin/settings/skills/`
2. Verify that only **Skills** is active in nav
> [Fix] Updates active matching logic for admin nav item

- api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/graphql/schema.graphql
- api/tests/Feature/ApplicantTest.php
🤖 Resolves #9160
Updates the base scopes for the countApplicants query to match the countPoolCandidatesByPool query.
The steps to reproduce in the issue will still return a different number of candidates due to candidates in archived pools. The base query includes those pools but the search page does not.
The easiest way to test this is probably just ensuring the tests match desired behavior and all pass. Removing any archived pools from your environment should also cause the steps to reproduce in the issue to pass.
> [Bug] Update countApplicants query base scopes

- apps/web/src/components/AssessmentStepTracker/Filters.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
🤖 Resolves #9236 
Updates the "hold for assessment" status colour to "secondary" to differentiate it more from the "to assess" status.
PR mentions the table as well, but that is getting done in a different PR.
3. Navigate to a pools "Screening and assessment" page
4. Confirm the "hold for assessment" status colours are using the secondary (teal, blue?) colours
> [Style] Update hold status colour

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
🤖 Resolves #9224
If RoD is active, default sort is less multi-layered, can sort by more columns. 
Final default sort is now alphabetical always. 
RoD OFF
1. Default final sort is alphabetical
2. Otherwise, unchanged
RoD ON
1. Default final sort is alphabetical
2. Priority and status no longer fed in by default
3. Can sort by priority and status columns now
> [Feature] Remove locked sorting for RoD

- api/app/Models/User.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/pages/Teams/TeamMembersPage/components/AddTeamMemberDialog.tsx
- apps/web/src/pages/Teams/TeamMembersPage/components/useAvailableUsers.ts
- apps/web/src/pages/Teams/teamsOperations.graphql
🤖 Resolves #9064 
Applies a fix to the users team member dialog crashing by using a paginated query.
This adds a new `userPublisProfilesPaginated` query that uses a limited search scope (`publicProfileSearch`) that only searches available fields on the public profile.
It also adds an `excludeIds` option so we return the proper page number (`100`) when filtering out existing team members.
2. Login as admin@test.com
3. Navigate to `/admin/teams`
4. Click on a team name
5. Navigate to the "View team members" tab
6. Active the "Add new member" dialog
7. Focus the "Manager name" field
8. Confirm it opens with only 100 results
9. Search for a user
10. Confirm search returns expected …
> [Fix] User input in team members add dialog

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
🤖 Resolves #9317.
This PR hides Remove candidate button until it is ready to be implemented in https://github.com/GCTC-NTGC/gc-digital-talent/issues/9198.
2. Navigate to`/admin/candidates/:candidate-id/application`
3. Verify there is no **Remove candidate** button
> [Feature] Hides Remove candidate button

- apps/web/src/pages/Applications/ApplicationEducationPage/utils.tsx
🤖 Resolves #9227.
This PR renders `appliedWorkListMessages` that had previously been mistakenly un-rendered in #8474.
@esizer for his 🦅  👀.
1. Navigate to `/applications/:application-id/education`
2. Observe **On-the-job learning** and other relevant list items are rendered
> [Fix] Renders `appliedWorkListMessages`

- apps/web/src/components/AssessmentStepTracker/AssessmentResults.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/CandidateNavigation/CandidateNavigation.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/CandidateNavigation/usePoolCandidateNavigation.ts
🤖 Resolves #9017 
This adds the prev/next/back links to the candidate page when navigating from the assessment tracker.
3. Navigate to a pool's screening and assessment page 
4. Take note of the order candidates appear in a column
5. Click on one
6. Confirm the next/previous links appear
7. Step through confirming that the links navigate to the expected candidate
8. Navigate to the start of the column (first candidate)
9. Confirm the previous link does not appear
10. Navigate to the last candidate
11. Confirm the next link does not appear
12. Confirm that the return to assessment tracker link appears
13. Navigate to the pool candidate from anywhere …
> [Feature] Add prev/next/back links to pool candidate page

- apps/e2e/cypress/e2e/admin/auth.cy.ts
- apps/web/src/components/Layout/AdminLayout/AdminLayout.tsx
- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
🤖 Resolves #9319.
This PR moves `skills/families` to `skill-families` and fixes the active menu issue for skill families and associated pages.
1. Navigate to `/admin/settings/skill-families`
2. Verify navigation item for Skill Families is active
3. Navigate to `/admin/settings/skill-families/create`
4. Verify navigation item for Skill Families is active
5. Navigate to `/admin/settings/skill-families/:skill-family-id/edit`
6. Verify navigation item for Skill Families is active
> [Fix] Moves `skills/families` to `skill-families`

- apps/web/src/components/EducationRequirements/EducationRequirements.tsx
🤖 Resolves #9381 
Adjusts the heading level for education requirements to use the appropriate semantic rank.
3. Navigate to the edit pool page
4. Confirm the education requirements headings are one level more than the section heading
5. Navigate to a pool advertisement page
6. Confirm the education requirements headings are one level more than the section heading
> [Fix] Heading level for education requirements

- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
- apps/web/src/components/Table/ResponsiveTable/TablePagination.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #9379 
Updates the the base table component to ensure landmarks are unique. 
We had an issue where we had a `div` with `role="region"` but applied the `aria-labelledby` attribute to the parent node instead. As well, the pagination had a hardcoded "Page navigation" label, we have prefixed it with the caption to make these unique.
2. Login as an applicant
3. Navigate to the skill library
4. Inspect the table accessibility tree
5. Confirm all landmarks (region, table, nav) have unique names across the tables
> [Fix] Table landmark uniqueness

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/components/AssessmentSummary.tsx
🤖 Resolves #9380 
Adds `aria-hidden=false` to the icons in the decision dialog so they can be programmatically determined by the accessibility tree.
1. Make sure you have the ROD feature flag enabled
3. Navigate to an application
4. Open the "Record final decision" dialog
5. Confirm the icon headers have a programmatically determined name in the accessibility tree
> [Fix] Expose decision table heading icons to a11y tree

- apps/e2e/cypress/e2e/admin/pool-candidate.cy.ts
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/components/SearchRequestTable/SearchRequestTable.test.tsx
- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/components/SearchRequestTable/components/helpers.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #9331.
This PR removes the word view from several table cells.
1. Navigate to Candidate Search table `/admin/pool-candidates` (Candidate name)
2. Verify View copy does not exist
3. Navigate to Pool Candidates table `/admin/pools/:id/pool-candidates` (Candidate name)
4. Verify View copy does not exist
5. Navigate to Talent Request table `/admin/talent-requests` (Job title)
6. Verify View copy does not exist
7. Navigate to Request Candidate Results table `/admin/talent-requests/:id` (Candidate name)
8. Verify View copy does not exist
> [Copy] Removes view copy from several table cells

- apps/web/src/lang/fr.json
- apps/web/src/messages/adminMessages.ts
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/AssessmentPlanBuilderPage.tsx
- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #9389 
Condense instances of "Assessment plan"
1. Build and navigate to places with the string in question, for example, `/fr/admin/pools/:id/plan`
2. Observe
> [Copy] Assessment plan condense copy

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/AssessmentDetailsDialogLabels.ts
🤖 Resolves #9421.
This PR fixes `AssessmentDetailsDialogLabels` messages to be available for i18n.
1. Navigate to assessment plan builder
2. Switch to French
3. Open modal
4. Verify all copy is in French
> [Fix] Adds `defineMessages` for `AssessmentDetailsDialogLabels`

- apps/web/src/pages/Pools/EditPoolPage/components/GeneralQuestionsSection/GeneralQuestionDialog.tsx
🤖 Resolves #9425 
Fixes an issue when removing the first question in general questions section of edit pool page.
2. Navigate to an edit pool page
3. Ensure there is at least one general question
4. Attempt to delete the first item
5. Confirm it gets deleted properly
> [Fix] General question remove

- packages/client/src/components/ClientProvider/ClientProvider.tsx
🤖 Resolves #9300 
Adds the locale to our post logout redirect on auth errors to reduce the number of required redirects.
3. Open inspector and edit the access token to cause it to be malformed
4. Refresh the page
5. Confirm the logout redirects to the localized version of the logged out page
> [Debt] Reduce auth error redirects

- apps/web/src/constants/classificationsAvailableForSearch.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/labels.ts
🤖 Resolves #9477.
This PR adds IT-05 to `classificationsAvailableForSearch`. It also [adds a space after the colon in all of the classifications labels in French](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9479/commits/26497342fe3a1d7dc40c9c217a4903ba6781f8e8) for consistency.
3. Select `Classification filter`
4. Verify **IT-05** is an option
> [Feature] Adds IT-05 to `classificationsAvailableForSearch`

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
🤖 Resolves #9432
Fallback to step type first, then as a last resort render the not available/applicable. 
1. Navigate to the screening and assessment board for various pools
2. Should not see "N/A"
> [Bug] Step title fallback for assessment board

- .github/dependabot.yml
🤖 Resolves #9474 
Add merge groups.
Not sure how to confirm it works? Other than merge and wait until there are enough dependencies to update then trigger it.
Storybook, graphql, tiptap, and types were what I picked as they have multiples. Storybook I allowed major since that would probably have to be merged together anyway for it to not break. 
1. ?
> [Tooling] Dependabot groups

- api/config/rolepermission.php
🤖 Resolves #9428 
Adds the `view-any-assessmentPlan` to the platform admin role. It also updates our file for tracking permissions.
The noted permission is now required to view the pool page but was only given to community managers. So, if you had the platform admin role but not the community manager role, you could no longer view pools.
1. Re-run role permission seeder `php artisan db:seed --class=RolePermissionSeeder`
3. Find a user and give them only the following roles
- Base user
- Applicant
- Request Responder
- Platform admin
4. Copy their sub
5. Logout
6. Login with the sub of the user copied in step 4
7. Navigate to a process information page …
> [Fix] Add missing permission to platform admin

- .github/ISSUE_TEMPLATE/♻️-debt-refactor.md
- .github/ISSUE_TEMPLATE/✨-feature-request.md
- .github/ISSUE_TEMPLATE/🛠️-tooling.md
- .github/ISSUE_TEMPLATE/🧪-tests.md
- .github/workflows/blocking-issues.yml
🤖 Resolves `none`
One of the best features of Zenhub (compared to Github Projects) was a better way to indicate blocked or blocking issues. This is an attempt to improve the experience slightly on Github Projects. 
It makes use of a github Action which can automatically add a "blocked" label to tickets, and remove it when the blocking issues are closed. The original Action was https://github.com/Levi-Lesches/blocking-issues. I forked it in order to modify it slightly -  blockers are now defined in a tasklist, allowing us to leverage `tracks` and `tracked by` fields at the same time.
To indicate blockers, create a tasklist with the title "Blocked By", like so:
````
```[tasklist]
```
````
If any of the blocking tickets are open, the `blocking-issues` workflow will automatically add the …
> Automate blocking issues

- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/IndexUserPage/components/UserFilterDialog.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #9393.
This PR consolidates **Any language** string to use a single source of truth and places the word _français_ first for the translation of **Any language (English or French)** to follow the logo standard where the current language is always first in the order.
1. Search codebase for string Any language
2. Verify there is once source of truth
> [Copy] Consolidates Any language string

- apps/e2e/cypress/e2e/admin/pool-candidate.cy.ts
- apps/e2e/cypress/e2e/talentsearch/directive-forms.cy.ts
- apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.ts
- apps/e2e/cypress/e2e/talentsearch/submit-application-iap.cy.ts
- apps/e2e/cypress/support/graphql-test-utils.ts
- apps/e2e/cypress/support/poolHelpers.ts
🤖 Resolves #8719 
Removes remaining references to `api/generated` in the cypress project.
1. Confirm no more references in `api/generated` in `apps/e2e`
2. Confirm tests will pass as expected
> [Debt] Migrate cypress to `client-preset`

- apps/e2e/cypress.d.ts
- documentation/environment-variables.md
🤖 Resolves #8780
Just improves a type which was left overly general as an oversight.
1. make sure the cypress tests still run and pass.
> Improve a type used in cypress tests

- api/app/Models/RoleAssignment.php
🤖 Resolves #9512. 
Fixes an issue where only `id` was available on the `Team.roleAssignments.user` query.
We had the relationship there but were only selecting `id` so that was the only data that could be returned. This adds the other remaining fields to the select statement so they can be returned in the response.
1. Login as admin
2. /admin/teams/{teamId}/members
3. Confirm you see the user name (first and last) as well as email
> [Fix] Team role assignment user query

- apps/web/src/utils/poolCandidate.ts
🤖 Resolves #9525
If a Pool has no assessment steps, candidates in assessment should show "To assess" in Final Decision column, not "Qualified: Pending decision".
1. Log in as admin
2. Go to a published pool with candidates and no assessment steps (can be seeded or set up manually)
3. Turn on Record of Decision feature flag
4. Set a candidate to New Application status
5. Candidate's status pill should read "To assess", not "Qualified: Pending decision"
> Show status as "To assess" when pool has no AssessmentSteps

- apps/playwright/fixtures/index.ts
- apps/playwright/package.json
- apps/playwright/tests/admin/accessibility.spec.ts
- apps/playwright/utils/axe.ts
- package-lock.json
🤖 Resolves #7670 
Solves the spike with testing accessibility without `jest-axe` by using `@axe-core/playwright`.
While component testing in Playwright is [still experimental](https://playwright.dev/docs/test-components), you can test full pages. The benefit of this is, we can interact with the app and test at different stages. Meaning, we could navigate to a page, open a dialog and run a test. This would catch violations that could be hiding behind not being mounted.
I still think `jest-axe` is a decent solution if we only use it on small, isolated components. I think we should probably move forward with this pattern for more complex testing and avoid doing any `jest-axe` testing inside of the `apps/**` folders. 
If we keep `jest-axe` to components in `packages/**` the speed should be …
> [Feature] Accessibility testing in Playwright

- apps/web/src/components/Layout/AdminLayout/AdminLayout.tsx
🤖 Resolves #9309 
Fixes an issue where navigating to admin from IAP did not switch theme back.
3. Navigate directly to `/admin` with no intermediary step (must use the address bar, not links)
4. Confirm the theme switches back to the default colours
> [Fix] Set admin theme on layout

- apps/web/src/components/Context/ContextProvider.tsx
- apps/web/src/components/Context/motion-features.ts
- apps/web/src/components/SpinnerIcon/SpinnerIcon.tsx
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclaration/CommunityIcon.tsx
- apps/web/src/pages/Home/IAPHomePage/Home.tsx
- packages/ui/package.json
- packages/ui/src/components/CardRepeater/Card.tsx
- packages/ui/src/components/Loading/Loading.tsx
- packages/ui/src/components/SideMenu/SideMenu.tsx
- packages/ui/src/components/SideMenu/SideMenuCategory.tsx
- packages/ui/src/components/SideMenu/SideMenuItem.tsx
🤖 Resolves #8404 
Reduces the initial bundle size of `framer-motion` by lazy loading the animations.
At first, this was causing an increased bundle size. After investigation, it turns out this was because we had `ui` setup to be an external package. Meaning, it was actually getting bundled twice (once in `apps/web` and again in `packages/ui` and using different contexts.
Since we don't actually need `ui` to be an external package and are not publishing it, I converted it to an internal package. Which means, it only gets bundled once in the app and uses the same context 🎉 
1. Build app `npm run build`
2. Confirm animations are working still
3. Confirm the bundle size is lower than on main
> [Debt] Reduce `framer-motion` initial bundle

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
🤖 Resolves #9527 
Adds additional typnames to the query context so `urql` knows to update its cache. 
While this does close the dialog it technically is not a complete solution to #9526 since it only closes because of a re-render.
3. Navigate to a pool candidate who has no assessments
4. Assess a skill
5. Confirm the table updates automatically
> [Fix] Assessment table initial update

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
🤖 Resolves #9526 
Updates the screening decision dialog to close once the mutation is successful. 
3. Navigate to a pool candidate who has no assessments
4. Assess a skill
5. Confirm the dialog closes once the mutation returns a success
https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/4b2870b0-05ac-44c1-a930-6eccfc4ced01
> [Fix] Screening dialog close on success

- apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/processMessages.ts
🤖 Resolves #9516 
Adds a null state for the step tracker and pool candidate pages when their associated process has no assessment plan.
2. Remove all assessment steps from a pool in the database
3. Login as admin `admin@test.com`
4. Navigate to the pool from page 2's screening and assessment sectioon
5. Confirm the null message appears and link goes to the proper talent placement page
6. Navigate to a candidate from the talent placement page
7. Confirm the null message appears under the assessment section for that candidate
> [Fix] Add null states for no assessment plan

- packages/ui/src/components/Spoiler/Spoiler.tsx
🤖 Resolves #9541 
Fixes an issue where both the full and truncated text was appearing on the "Read more" section of the search request table "notes" column.
1. Build the app `npm run dev`
2. Navigate to the search requests table (`/admin/talent-requests`)
3. Enable the "notes" column
4. Activate the "read more" button on one of the rows
5. Confirm that the truncated version of the text no longer appears
> [Fix] Hide truncated text when "read more" open

- packages/ui/src/components/TableOfContents/Heading.tsx
- packages/ui/src/components/TableOfContents/heading.css
🤖 Resolves #9594.
This PR removes legacy table of contents heading css.
1. Search codebase for references to `packages/ui/src/components/TableOfContents/heading.css` file
2. Verify none exist
3. Search codebase for references to `toc-heading__icon` css class
4. Verify none exist
> [Debt] Removes legacy table of contents heading css

- apps/web/src/components/SearchRequestTable/SearchRequestTable.stories.tsx
🤖 Resolves #9416 
Fixes the name of the mock query in the search request table story so it shows items.
1. Run storybook `npm run storybook:web`
2. Navigate to the search request table story
3. Confirm it shows items
> [Fix] Search request table story mock query

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/Table/ResponsiveTable/SearchForm.tsx
- apps/web/src/components/Table/ResponsiveTable/types.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
🤖 Resolves #9517 
Sets default message for the table search to "Entire table" with the option to pass in an override. 
1. Navigate to users and pool candidates table and observe search dropdown unchanged
2. Other tables had their search dropdowns changed
Unchanged
Changed
> [Bug] Default table message

- apps/web/src/components/Profile/components/AccountAndPrivacy/AccountAndPrivacy.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/ApplicationCard.stories.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/ApplicationCard.test.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/ApplicationCard.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/TrackApplications/TrackApplications.tsx
🤖 Resolves #9498.
This PR renames `TrackApplicationsCard` to `ApplicationCard` to reflect what it is: a card with application data.
2. Navigate to **Track your applications** section of `/applicant/profile-and-applications`
3. Verify application cards render as they did before
4. `npm run storybook:web`
5. Navigate to http://localhost:6006/?path=/story/components-application-card--application-cards
6. Verify **Application Cards** story renders as it did before
> [Debt] Renames `TrackApplicationsCard` to `ApplicationCard`

- apps/web/.env.example
- apps/web/public/config.ejs
- apps/web/src/components/Header/Header.tsx
- packages/env/src/utils.ts
- packages/theme/src/components/ThemeProvider.tsx
🤖 Resolves #9291 
Dark mode has been deployed now as a beta so we no longer need the feature flag.
1. Confirm no more instances of `FEATURE_DARK_MODE` and `darkMode`
2. Confirm app still builds and light/dark mode are working as expected
Remove `FEATURE_DARK_MODE` env var.
> [Debt] Removes the dark mode feature flag

- apps/web/src/components/PoolCandidatesTable/helpers.tsx
🤖 Resolves #9298 
Fixes and issue where we were sorting the pool candidates table language field on the wrong database column.
We have multiple items in the column name map for `preferredLang`. The last item was being used which was not intended. This just removes the incorrect items in the map so the proper column name is used.
2. Login as admin`admin@test.com`
3. Navigate to `/admin/pool-candidates`
4. Sort by the "Preferred communication language" column
5. Confirm the sorting is happening as expected
> [Fix] Preferred lang sort on pool candidates table

- apps/web/src/components/SkillBrowser/utils.ts
🤖 Resolves #9602 
Fixes the skill count for "in library" skills when being filtered by category.
This applies a second filter when the category is selected to only get those skills in the users library and the category to more accurately reflect the number of skills that will be avilable.
2. navigate to a skill showcase
3. Click the add a new item button
4. Confirm the number of library skills in the family select matches those available in the combobox
> [Fix] In library skill count

- .github/ISSUE_TEMPLATE/❗-new-notification.md
We'll be creating a lot of notifications as part of https://github.com/GCTC-NTGC/gc-digital-talent/milestone/25 and after. I want to standardize the details we need to successfully add a new type of notification to the app.
> Create template for new notification issues

- apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/CoreRequirementsSection.tsx
- packages/forms/src/components/Input/Input.tsx
🤖 Resolves #9631
Recruitment team needs to publish a job which requires an in-office presence but has offices in many cities across the country, and they don't all fit into 256 characters.  (They require three-hundred-something characters.) A rich-text field may be the better way to go, but here's a quick fix for now.
Allows for overriding the maxLength rule on our Input component.
1. Log in as an admin
2. Edit a draft poster
3. edit Core Requirements
4. set location to Specific Location
5. Add add lest 400 characters of text to Specific Location (English) and Specific Location (French) fields.
6. Make sure you can save the poster
7. Make sure you can publish the poster
8. Make sure the location text appears correctly on the published poster.
> Allow for override of Input maxLength. Extend maxLength for Pool location fields.

- apps/web/src/components/SkillsInDetail/SkillsInDetail.stories.tsx
🤖 Resolves #9629.
This PR refactors the `SkillsInDetail` stories from three stories to one and replaces deprecated storybook functions with current ones.
1. `npm run storybook:web`
2. Observe `SkillsInDetail` storybook is consolidated into one single story
> [Debt] Refactors `SkillsInDetail` story

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/AssessmentStepTracker/ResultsDetails.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
🤖 Resolves #9610 
Changes the initial state of the step tracker to only show "to assess" status and hide the distribution summary.
3. Navigate to a process screening and assessment page
4. Confirm that only the  "to assess" filter is enabled
5. Confirm the distribution is collapsed
> [Debt] Update assessment step tracker initial state

- api/app/Models/AssessmentResult.php
- api/app/Models/AssessmentStep.php
- api/app/Models/GeneralQuestion.php
- api/app/Models/ScreeningQuestion.php
🤖 Resolves #9532 
This logs all changes to the following models:
- `AssessmentResult`
- `AssessmentStep`
- `GeneralQuestion`
- `ScreeningQuestion`
> [!NOTE]
> "Appropriate data" includes `description` (action taken), `subject_type` (model acted on), `subject_id` (record acted on), `causer_type` (model acting), `causer_id` (record actting).
2. Create a pool
3. Add a general question
4. Confirm a new record is created in the `activity_log` table with the appropriate data
5. Confirm a record is created for the default assessment step as well
6. Navigate to that pools edit assessment plan
7. Create a step
8. Confirm a new record is created in the `activity_log` table with the appropriate data
9. Add a screening question step with questions
10. Confirm a new …
> [Feature] Add logging to assessment models

- apps/web/src/components/AssessmentResultsTable/testData.ts
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/components/ScreeningDecisions/useHeaders.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/RODViewPoolCandidatePage.tsx
- packages/fake-data/src/fakePoolSkills.ts
- packages/fake-data/src/fakePools.ts
🤖 Resolves #9524 
Have the screening dialogs draw their skill level from the pool itself and not from the user.
1. Setup pool with poster, assessments, and a candidate
2. Go to screening dialog and observe skill level, should match the pool's skill level
Dialog view
Matches poster
Storybook dialog
> [Bug] Associate ScreeningDecisionDialog skill levels with pool's

- apps/web/src/pages/Pools/PoolAdvertisementPage/components/SkillAccordion.tsx
🤖 Resolves #9672 
Fixes the display of the skill accordion subtitle by removing the parentheses and replacing the list with `span` tags.
2. Navigate to a job poster
3. Confirm the parentheses are no longer present in the subtitle
4. Confirm the list has been replaced by spans
> [Fix] Display of skill accordion subtitle

- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
🤖 Resolves #9625 
Merges the separate category based skill library links into a single link on the profile and applications page.
2. Login as an applicant `applicant@test.com`
3. Navigate to the profile and applications page
4. Confirm there is only one link to the skill library
5. Confirm the status is in error when no skills exists on your profile
6. Confirm adding a skill turns it to the success status
> [Debt] Update skill library card

- apps/web/src/lang/crg.json
- apps/web/src/lang/crk.json
- apps/web/src/lang/fr.json
- apps/web/src/lang/mic.json
- apps/web/src/lang/ojw.json
- apps/web/src/pages/Home/IAPHomePage/Home.tsx
🤖 Resolves #9700.
This PR changes the IAP program launch year to 2024.
2. Navigate to `/en/indigenous-it-apprentice/`
3. Search for **2024**
4. Verify full sentence is **Aim to launch the program in the early half of 2024.**
5. Switch to each of `crg`, `crk`, `mic`, `ojw`, `fr` languages
6. Search for **2024**
7. Verify sentence contains **2024**
> [Copy] Changes IAP program launch year to 2024

- api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
- api/tests/Feature/CountPoolCandidatesByPoolTest.php
🤖 Resolves #9674 
Define the variable `filters` such that it handles the input not being present. 
1. Test query below
2. Tests succeed
```
query count {
countPoolCandidatesByPool(where: null) {
pool {
id
name {
en
}
}
candidateCount
}
}
```
> [Bug] Handle missing `where` in `CountPoolCandidatesByPool`

- apps/web/src/lang/fr.json
- apps/web/src/pages/Skills/SkillLibraryPage.tsx
- apps/web/src/pages/Skills/components/SkillLibraryTable.tsx
🤖 Resolves #9624 
Merges the separate technical and behavioral skill tables on the skill library page.
3. Navigate to the skill library
4. Confirm there is now only one table
5. Confirm the copy and layout match [the mockup ](https://www.figma.com/file/FhRhwczL8JI6JC8eVFlWOm/Skill-library?type=design&node-id=383-16577&mode=design&t=KkN8J2lX1u1JvsOe-0)
6. Confirm the add dialog shows all skills
7. Confirm the level matches the category of skill in the table
> [Debt] Merge skill library tables

- packages/client/src/exchanges/specialErrorExchange.ts
🤖 Resolves #9708.
This PR refactors `specialErrorExchange` options out of an interface.
1. Verify application works as before
2. Verify no unused exports in `specialErrorExchange.ts`
3. Verify that single property interface removed for `specialErrorExchange`
> [Debt] Refactors `specialErrorExchange` options

- apps/playwright/tests/applicant/application.spec.ts
- apps/web/src/pages/Applications/ApplicationQuestionsPage/ApplicationQuestionsPage.tsx
🤖 Resolves #9716 
Get the missing error summary to appear again.
Was missing needed labels prop, with a bunch of trial and error I got something to pass in 😛 
1. Start an application and reach the questions page
2. Attempt to submit incomplete
> [Bug] Missing error summary for application questions

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInformation.tsx
🤖 Resolves #9729.
This PR fixes the heading level for application information accordions.
2. Navigate to a specific application (pool candidate)
3. Scroll down to the "Application information section"
4. Verify that the accordion headings are `h3` and not the same level as the section heading (`h2`)
> [Fix] Heading level for application information accordions

- apps/web/src/components/PoolCandidatesTable/helpers.tsx
🤖 Resolves #9218.
This PR fixes sorting for the `notes` column on the Pool candidates table.
1. Log in as an admin
2. Go to "candidate search" (/admin/pool-candidates)
3. Sort by **Notes** column (ensure at least a few candidates have notes)
4. Verify alphanumeric sorting occurs
> [Fix] `notes` column sorting on Pool candidates table

- apps/web/src/pages/Skills/SkillPage.tsx
🤖 Resolves #9763.
This PR fixes the **Home** breadcrumb link to lead to home route. It also makes use of the `useBreadcrumb` hook.
1. Navigate to `/skills`
2. Click Home breadcrumb link
3. Page that loads is `/`
> [Fix] Skills page crumbs

- api/app/Models/User.php
🤖 Resolves #9071 
This branch removes the Scout search, which is not really made to be integrated into query builder, and uses regular query builder commands for text search.  I tried to essentially replicate the query that Scout was building.  Scout is still being used to maintain the indexes, though.
Does it perform better?  A little better, maybe.  I seeded 10,000 users into my database and the updated query returns in about 800ms while the old query returns in about 1,000.
> [Debt] Integrate text search into builder

- api/app/GraphQL/Validators/PoolIsCompleteValidator.php
- api/app/Models/Pool.php
- api/database/factories/PoolFactory.php
- api/database/migrations/2024_03_11_175506_add_about_us_post_admission_columns_pools_table.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/lang/fr.json
- apps/web/src/messages/processMessages.ts
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.test.tsx
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/AboutUsSection/AboutUsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/AboutUsSection/Display.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectAdmissionSection/Display.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/WhatToExpectAdmissionSection/WhatToExpectAdmissionSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/types.ts
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/validators/process/aboutUs.ts
- apps/web/src/validators/process/whatToExpectAdmission.ts
- packages/forms/src/components/RichTextInput/ControlledInput.tsx
- packages/forms/src/components/RichTextInput/Footer.tsx
🤖 Resolves #8829 
Adds two new fields ("what to expect post admission" and "about us") to the pool model.
1. Migrate `php artisan migrate`
2. Build app `npm run dev`
3. Login as admin `admin@test.com`
4. Create a pool
5. Confirm the new sections exist
6. Confirm they save and load data properly
7. Confirm they appear on the advertisement page as expected
> [Feature] Add new fields to Pool model

- .github/workflows/chromatic.yml
- chromatic.config.json
- packages/storybook-helpers/main.ts
- packages/ui/src/components/Chip/Chip.stories.tsx
🤖 Resolves #9776 
Fixes an issue with chromatic CI with `pnpm`.
Seems as though the forward of the build dir was relative to the place the script exists so it was building to `./apps/web/apps/web/storybook-static`
1. Check chromatic
> [Fix] Chromatic CI build

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
🤖 Resolves #9778 
One place was just using the wrong getter, a quick fix
1. Open assessment dialog for a candidate and observe
> Switch to name getter rather than description

- apps/web/src/pages/Pools/PoolLayout.tsx
🤖 Resolves #9728 
Fixes an issue where pool page navigations were not being announced to screen readers.
2. Login as admin `admin@test.com
3. Start a screen reader
4. Navigate to a pool in the admin
5. Change tabs
6. Confirm page title is being announced after the page change
> [Fix] Announce admin pool page navigations

- api/app/Http/Middleware/SlowQueryLoggerMiddleware.php
🤖 Resolves #9704 
This PR formats slow query logging into single line
1. Open up laravel.log file
2. Go to Admin Dashboard and do any extensive operation like opening up Candidate Search page
3. Observe the log 
```
[2024-03-19 14:42:03] local.INFO: Slow Query, 10.3536912, AdminDashboard_Query, http://localhost:8000/en/admin/dashboard, "query AdminDashboard_Query {\n  me {\n    id\n    firstName\n    lastName\n    __typename\n  }\n}"  
```
> [Tooling] make slow query logging into single line

- .github/dependabot.yml
🤖 Resolves #9750.
This PR updates dependabot's types merge group so that it only includes TypeScript `@types` packages.
@esizer for the [solution](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9750#:~:text=add%20a%20slash%20before%20the%20asterisk%20here%20to%20make%20it%20slightly%20more%20specific).
1. 🤞 it works on dependabot thursday! 🤷
> [Feature] Update dependabot types merge group

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
🤖 Resolves #9812 
Rectify the dialog component to pull data to render out of the snapshot. Also noticed the screening question responses ought to do that too. 
Just recycled code from elsewhere for the most part ♻️ 
1. Submit an application
2. Retroactively update stuff, it should not be reflected in the dialog
Dialog view
Updated experience
Screening questions still rendered
> [Bug] Use snapshot for screening dialog

- .github/dependabot.yml
🤖 Resolves #9847.
Update Dependabot `versioning-strategy` to `lockfile-only`.
1. 🤞
> [Fix] Update Dependabot `versioning-strategy` to `lockfile-only`

- .github/dependabot.yml
🤖 Resolves #9847.
Update Dependabot to remove `versioning-strategy`.
1. 🤞
> [Fix] Remove Dependabot `versioning-strategy`

- api/app/Http/Controllers/SupportController.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
🤖 Resolves #9733
This branch adds a better error to the support page when an "invalid email" code is being returned by Freshdesk.  I ran the suggested error message past Marc and got a "looks good".
1. Set up your environment for Freshdesk (either set up a junk account or copy the values from prod).
> [Feature] Add better email error

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.stories.tsx
🤖 Resolves #9875 
Matt pointed out the stories aren't very useful if not defaulted to open, and it turned out to be an easy fix so here it is 
1. Observe Chromatic diff 
Link instead 
https://www.chromatic.com/review?appId=61e099a1bb1465003a73d3ce&number=9876&type=linked
> [Tests] Set ScreeningDialog stories to open

- apps/web/src/lang/fr.json
🤖 Resolves #9869.
This PR fixes a French typo introduced in #9759. Sorry @tristan-orourke, I lied, [the process is not complete](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9759#pullrequestreview-1949113375) 😓. 
1. Do a French spell check on the word `processus`
2. Verify no instances of `proccesus` in codebase
> [Fix] French typo in word process

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/components/AssessmentStepTracker/testData.ts
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/pages/Pools/ScreeningAndEvaluationPage/ScreeningAndEvaluationPage.tsx
🤖 Resolves #9789
Filter out candidates that were already disqualified prior to RoD
I think I got the gist of what the goal was? 😅 
1. Add a candidate to a process, disqualify them, then ensure they are missing from Screening and assessment
2. Must have no assessment results 
Pool candidate
Present
Missing
> [Bug] Filter out already disqualified candidates in processes

- apps/web/src/pages/Users/IndexUserPage/components/UserFilterDialog.tsx
- apps/web/src/pages/Users/IndexUserPage/components/constants.ts
- apps/web/src/pages/Users/IndexUserPage/components/utils.tsx
🤖 Resolves #9862 
Have it so no roles are missing, that should be present. Did the recommended inversion of the filtering 
Quick fix 🔧 
The roles NOT present are guest, user, and applicant 
1. Navigate to users table
2. Can filter by the desired roles
> [Bug] Resolve missing roles from users table

- Makefile
🤖 Resolves #9886 
Not sure if anyone would find this useful but I use this to run some common commands so I don't need to go looking for them all the time.
If you have [make](https://www.gnu.org/software/make/manual/make.html) installed you can run the following commands:
- `make up`: Start docker compose in detach mode
- `make down`: Shutdown docker-compose
- `make setup`: Runs the `setup.sh` script
- `make refresh`: Runs the `refresh_all.sh` script
- `make refresh-frontend`: Runs the `refresh_frontend.sh` script
- `make refresh-api`: Runs the `refresh_api.sh` script
- `make clean-modules`: Deletes all `node_modules` directories
- `make seed-fresh`: Refreshes the database with new data
- `make migrate`: Runs new db migrations
- `make artisan CMD="some artisan command"`: Run artisan …
> [Tooling] `Makefile` for common scripts

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/IAPManagerHomePage/IAPManagerHomePage.tsx
🤖 Resolves #9868.
This PR fixes typos in French at `/indigenous-it-apprentice/hire` and makes the program title is consistent (in both English and French) with what is used on the rest of the application: IT Apprenticeship Program for Indigenous Peoples (English) and Programme d’apprentissage en TI pour les personnes autochtones (French).
1. Navigate to `/indigenous-it-apprentice/hire`
2. Verify no spelling errors in French in Paragraph 1 of the 'A commitment to diverse digital talent' section
3. Verify the program title for IT Apprenticeship Program for Indigenous Peoples is consistent with what is on other parts of the site (for example, `/indigenous-it-apprentice/`) in English and French
> [Copy] IAP Manager Home French typos

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/EditPoolPage/components/GeneralQuestionsSection/GeneralQuestionsSection.tsx
🤖 Resolves #9903
Increase the limit of general questions from 3 to 10 
1. Go to en/admin/pools page 
2. Click on Create Process
3. Navigate to General Questions section from the left menu 
4. Verify it allows to upto 10 questions for the process and verify the description says 10 instead of 3.
> [Feature] Increase limit for general questions

- apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
🤖 Resolves #9906.
This PR updates the label of the email input to make the government, in this case the Government of Canada, explicitly named.
2. Navigate to `/search/request`
3. Verify label for email field contains **Government of Canada**
> [Copy] Updates email input label to specify government

- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
🤖 Resolves #9902 
Fixes an issue where attempting to edit an experience right after adding it (without hard refresh) caused the form to be empty.
I could only reproduce this if I had no experiences of a specific type. Once at least one experience was added this was no longer an issue. So, I'd test both scenarios to be certain this is fixed.
> [!IMPORTANT]
> It would be best to test this first with no experiences, then with one experience but adding another of a different type. Then again with one of the same type.
3. Navigate to your career timeline
4. Add an experience, returning to career timeline
5. Attempt to edit the newly added experience
6. Confirm the form appears with the appropriate data
> [Fix] Mark experience data as stale after adding

- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
🤖 Resolves #9949.
This PR adds the process number to the process information page.
2. Create a process with the Process number field left empty
3. Navigate to Process information page's Advertisement information section
4. Observe **Process number: Not provided**
5. Enter a value in the field for Process number
6. Navigate to Process information page's Advertisement information section
7. Observe **Process number: `valueEntered`**
> [Feature] Adds process number to process information page

- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #9944.
This PR renames the `id` column header for the Search Request table.
1. Navigate to `/admin/talent-requests`
2. Click Show or hide columns button
3. Select the Tracking number checkbox
4. Verify values in Tracking number column still render the uuid
> [Feature] Renames Search Request table `id` column header

- apps/e2e/cypress/e2e/admin/pools.cy.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
🤖 Resolves #8850.
This PR removes the **Edit** and **Candidates** columns from Processes table.
3. Click **Show or hide columns** button
4. Verify there are no checkboxes for **Edit** or **Candidates**
> [Feature] Removes edit, candidates columns from Processes table

- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateSection.tsx
- apps/web/src/validators/process/closingDate.ts
🤖 Resolves #9987 
Updates the front end validation for a process closing date when it is in draft to check if it is a past date and return an error.
2. Create a process and complete it but do not publish
3. Edit the process directly in the database to set closing date to a past date
4. Review the process to confirm you cannot publish and error icons appear for closing date/basic information
> [Fix] Validate closing date is not in past on process

- apps/web/src/lang/fr.json
- apps/web/src/pages/Skills/SkillPage.tsx
🤖 Resolves #9955.
This PR adds an alert to the skills page.
1. Navigate to `/skills`
2. Observe dismissible alert
> [Feature] Adds alert to skills page

- packages/webpack-config/webpack.base.js
🤖 Resolves #9998 
Removes a duplicate meta description from the `head`
2. Inspect the `head`
3. Confirm only one `meta[name=description]`
4. Confirm it updates on page change
> [Fix] Remove duplicate meta description

- packages/ui/src/components/DropdownMenu/DropdownMenu.tsx
🤖 Resolves #9996 
Fixes colour constrast in the dropdown menu.
We updated the styles for links and buttons in dropdown but forgot to apply those changes for checkboxes and radio buttons :cry: 
2. Navigate to a dropdown (admin tables is a good spot)
3. Confirm they have the secondary colour and proper contrast ratio
> [Fix] Dropdown colour contrast

- api/app/Rules/AssessmentStepComplete.php
- api/app/Rules/PoolSkillIsAssessed.php
- api/app/Rules/QuestionsAnswered.php
- api/tests/Feature/PoolApplicationTest.php
- api/tests/Feature/PoolTest.php
🤖 Resolves #9973 
Removes the remaining ROD feature flag checks on the back end.
Even though we removed the feature flag, there were some remaining checks to skip tests and validation. This removes those from the code so the tests and validation now  run.
1. Run tests `make artisan CMD="test"`
2. Confirm they all run and pass
3. Attempt to publish a pool with a missing skill assessment
4. Confirm validation returns failure
5. Attempt to submit an application with missing screening question response
6. Confirm validation returns error
> [Debt] Remove remaining ROD feature flag checks

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/poolCandidateMessages.ts
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
🤖 Resolves #9848.
This PR distinguishes between asset and essential skills on a candidate's screening and assessment table.
c9563ceb81f21a7620970294efd010e8f61a3bcb fixes a non-unique key error.
@esizer for helping find the component 😉 
1. Create a process with one essential skill and one asset skill
2. Add a candidate to the process
3. Navigate to a candidate's screening and assessment table `/admin/candidates/:candidate-id/application`
4. Verify that **Unclaimed** is rendered for the asset skill
> [Feature] Distinguishes asset skills on candidate screening and assessment table

- apps/web/src/components/Layout/AdminLayout/AdminLayout.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/pages/Skills/IndexSkillPage.tsx
- apps/web/src/pages/Skills/SkillPage.tsx
🤖 Resolves #9880 
- Adds a link to Skills page on the admin dashboard and admin sidebar.
- Changes icons and name of previous skills page
1. Run `pnpm run dev`
3. Go to admin dashboard
4. Ensure new links show up on side menu and dashboard, as well as naming and icons are correct.
> [Feature] Admin side skills page link

- apps/e2e/cypress/e2e/talentsearch/directive-forms.cy.ts
- apps/web/src/components/SkillBrowser/SkillBrowser.tsx
- apps/web/src/components/SkillBrowser/SkillBrowserDialog.stories.tsx
- apps/web/src/components/SkillBrowser/SkillBrowserDialog.tsx
- apps/web/src/components/SkillBrowser/SkillSelection.tsx
- apps/web/src/components/SkillBrowser/messages.ts
- apps/web/src/components/SkillBrowser/types.ts
- apps/web/src/components/SkillBrowser/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/EditPoolPage/components/SkillTable.tsx
- apps/web/src/pages/Skills/SkillPage.tsx
- apps/web/src/pages/Skills/components/SkillLibraryTable.tsx
- apps/web/src/pages/Skills/components/UpdateSkillShowcase.tsx
- packages/forms/src/components/Combobox/Single.tsx
🤖 Resolves #9623 
Updates the skill browser with the following changes:
- Remove category field
- Update skill family label
- Remove skill counts from options
- Add a link to the not found skill suggestion
2. Navigate to a page with the skill browser
3. Confirm it matches [the mock up](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=97-31278&mode=design&t=q0CnoXe0a8womMfK-4)
4. Confirm it still functions as expected
5. Run storybook `pnpm run storybook:web`
6. Navigate to the skill browser stories
7. Confirm each story matches  [the mock up](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=97-31278&mode=design&t=q0CnoXe0a8womMfK-4)
4. Confirm it still functions as expected
> [Debt] Update skill browser

- api/tests/Feature/SnapshotTest.php
🤖 Resolves #9975
This is annoying, lets clear it up.
Fixing by sorting the experiences on both the same way, as the order of the experiences does not matter.
1. Tests repeatedly pass in CI
2. As well as locally
Run
`for i in {1..50}; do docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/SnapshotTest.php"; done`
> [Tests] Fix SnapshotTest

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
🤖 Resolves #10012.
This PR updates logic so that **Unclaimed** is rendered for an asset skill only when there the applicant (from snapshot) skill does not have a linked experienced on the screening and assessment table.
1. Create a process with one essential skill and two asset skills
2. Create an application to this process where one of the asset skills has an experience attached and one asset skill that does not have an experience attached
3. Navigate to a candidate's screening and assessment table `/admin/candidates/:candidate-id/application`
4. Verify that **Unclaimed** is rendered for the asset skill with no skill attached
5. Verify that **To assess** is rendered for the asset skill with skill …
> [Feature] Screening and assessment asset skill experience linked skill logic

- apps/web/src/pages/SkillFamilies/UpdateSkillFamilyForm.stories.tsx
- apps/web/src/pages/SkillFamilies/UpdateSkillFamilyPage.tsx
- apps/web/src/pages/Skills/UpdateSkillForm.stories.tsx
- apps/web/src/pages/Skills/UpdateSkillPage.tsx
- apps/web/src/pages/Skills/UpdateUserSkillForm.stories.tsx
- apps/web/src/pages/Skills/UpdateUserSkillPage.tsx
- packages/fake-data/src/fakeUserSkills.ts
🤖 Resolves #9713 
Adds top level fragment masking for `Skill` and `SkillFamily` queries.
2. Navigate to pages affected
3. Confirm they work as expected
> [Debt] `Skill` and `SkillFamily` fragment masking

- packages/storybook-helpers/main.ts
- packages/storybook-helpers/package.json
- pnpm-lock.yaml
🤖 Resolves #9636 
This may fix an issue with stories that include `img[srcset]` being unstable
I reached out to chromatic suppoer and they suggested preloading assets. I added the `PreloadWebpackPlugin` to see if that will sort things out. At the same time, I noticed we were not passing a static dir option for static assets so I also added that hoping it might make things a bit more stable :woman_shrugging: 
1. Check to diffs on separate chromatic runs to confirm it seems stable:
- https://www.chromatic.com/review?appId=61e099a1bb1465003a73d3ce&number=10026&type=linked
- ... There would be more here but it seems chromatic won't re-run with no changes :/
> [Fix] Stabilize `srcset` in chromatic

- apps/web/src/components/NotificationList/NotificationListPage.tsx
🤖 Resolves #9961 
Adds the appropriate spacing to the notification dialog null message when in the dialog.
2. Open the notification dialog
3. Confirm the null message lines up with the other content
> [Fix] Notification dialog null spacing

- api/app/Models/PoolCandidate.php
🤖 Resolves #9974 
Resolve the lazy load instance. Turns out it was missing an eager in the snapshot process
1. Migrate and seed fresh
2. Run below command
`php artisan db:seed --class=UserRandomSeeder`
> [Bug] Missing eager load of classification

- packages/storybook-helpers/decorators/ThemeDecorator.tsx
Fixes an issue where the theme was trying to update too often in storybook causing an error.
Recently we removed the `useEffect` to prevent infinite re-renders but apparently it was needed. This merges the two concepts along with a memo to help avoid infinite re-renders and stabilize things a bit.
1. Run storybook `pnpm run storybook`
2. Bounce around stories
3. Open the javasript console
4. Confirm no errors related to the `ThemeDecorator` or `ThemeSetter` components
> [Fix] Theme decorator setting theme too often

- apps/web/src/components/PoolCandidatesTable/poolCandidateCsv.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/ApplicationPrintDocument.tsx
🤖 Resolves #9997 
Updates the headings for questions on pool candidate documents to be appropriately labelled based on the date displayed.
I think I did this correctly based on the discussion in stand up :sweat_smile: . Anyway, feel free to nitpick here so we get this right.
3. Navigate to a pool candidate
4. Select the "Print application" option
5. Confirm the section for questions has the appropriate heading (General questions)
6. Navigate to a pool "Talent placement" tab
7. Download CSV for candidates
8. Confirm the question columns are labelled as "General question: X"
> [Fix] Adjust document question headings

- apps/web/src/pages/Home/HomePage/HomePage.stories.tsx
- apps/web/src/pages/Home/IAPHomePage/Home.stories.tsx
- packages/storybook-helpers/modes.ts
🤖 Resolves #4371.
This PR adds French Chromatic modes for Digital Talent, IAP home pages.
1. `pnpm storybook:web`
2. Open Chromatic for this branch
3. Observe snapshots variants for **Pages/Home Page/IAP** and **Pages/Home Page/Digital Talent**
> [Tooling] Adds Chromatic modes including French for Digital Talent, IAP home pages

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
🤖 Resolves #10064.
This PR renders status column by default on Pool Candidate table.
1. Navigate to `/admin/pool-candidates`
2. Verify **Status** column renders by default
> [Feature] Renders status column by default on Pool Candidate table

- infrastructure/bin/post_deployment.sh
🤖 Resolves #10072 
Remove `php-gd` install from the post deployment script.
1. Confirm the `post_deployment.sh` script runs successfully with no errors
2. Confirm you can still generate CSV files locally for testing
> [Fix] Remove `php-gd` from post deploy install

- api/app/Enums/DisqualificationReason.php
- api/app/GraphQL/Mutations/DisqualifyCandidate.php
- api/app/GraphQL/Mutations/PlaceCandidate.php
- api/app/GraphQL/Mutations/QualifyCandidate.php
- api/app/GraphQL/Mutations/RevertFinalDecision.php
- api/app/GraphQL/Mutations/RevertPlaceCandidate.php
- api/app/GraphQL/Validators/DisqualifyCandidateValidator.php
- api/app/GraphQL/Validators/PlaceCandidateValidator.php
- api/app/GraphQL/Validators/QualifyCandidateValidator.php
- api/app/GraphQL/Validators/RevertFinalDecisionValidator.php
- api/app/GraphQL/Validators/RevertPlaceCandidateValidator.php
- api/app/Models/PoolCandidate.php
- api/app/Providers/GraphQLServiceProvider.php
- api/database/factories/PoolCandidateFactory.php
- api/database/helpers/ApiErrorEnums.php
- api/database/migrations/2024_04_15_194823_add_final_decision_at_field.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateUpdateTest.php
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/FinalDecisionDialog.tsx
🤖 Resolves #9190
Adds the three mutations as well as a `final_decision_at` date time field. Includes factory, schema, and testing. 
Also swaps in the new mutations for the final decision dialog. 
1. Migrate back and forth
2. Seed fresh
3. Test new mutations, see below
4. Use final decision dialog to qualify or disqualify candidates, remember to reset status first in some cases
```
mutation qualifyCandidate {
qualifyCandidate(
id: ":ID"
expiryDate: ":date"
) {
id
status
expiryDate
finalDecisionAt
}
}
```
```
mutation disqualifyCandidate {
disqualifyCandidate(
id: ":id"
reason: ":reason"  ) {
id
status
finalDecisionAt
}
}
```
```
mutation revertFinalDecision {
revertFinalDecision(id: ":id") {
id
status
expiryDate
finalDecisionAt
}
}
```
> [Feature] qualify/disqualify/revert a candidate mutations

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #10071 
Resolve the typos present, as well as implement the suggestion. I think it looks nicer that way as it cleanly matches the accordion. 
1. Navigate to `/en/browse/pools/:id`
2. Then in French
> [Bug] French formatting on poster page

- api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/graphql/schema.graphql
🤖 Resolves #10062 
This PR allows IT-05 group that is published under "OTHER" publishing group to be searchable via the Find Talent form along with existing IT_JOBS_ONGOING, IT-JOBS. 
Technically it will allow any group that is published under "Other" will be part of the count candidates query.
I'm unsure whether this will bite back us though. 
The scopeInITPublishingGroup has been modified to include "Other" publishing group.
However it is not ITPublishingGroup any more.
Should we rename this scope? 
Would like dev suggestion
1. Create a process with IT-05 and publish under "Other" group
3. Apply for the same process via `View Advertisement` and apply from there. ( This will NOT be shown on browse …
> [Feature] Add "Other" Publishing group to the searchable list of groups

- apps/web/src/constants/poolCandidate.ts
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
🤖 Resolves #9315 
Adds conditional rendering for the Record/Revert final decision dialogs based on the candidates status.
The revert dialog is being worked on so right now it just has a fragment and nothing shows up. It will be added in #9197 
> [!TIP]
> If you want to test the revert, just drop a hard coded message in the placeholder fragment spot temporarily before building.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8ace5559efca71b6e53066e1e98f9d9d656f6e51/apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx#L813-L815
2. Login as admin `adm,in@test.com`
3. Navigate to a pool candidate
4. Change their status to ones that appear in `RECORD_DECISION_STATUSES` and `REVERT_DECISION_STATUSES`
5. Confirm the button is rendered for …
> [Feature] Conditionally render decision dialogs

- api/database/migrations/2024_04_18_210339_job_alert_default_ignored.php
🤖 Resolves #10086
Sets JOB_ALERT as default ignored for emails and updates existing models to reflect that. 
Elected to do a migration as it covers both tasks in one go. 
1. Migrate back and forth, nothing broke
2. Create a new user, run `User::create()` in tinker for example
3. Query notification fields in `/graphiql`
Nothing currently needs to be done
> [Feature] Promotional email set to opt in

- infrastructure/azure-pipelines.yml
- infrastructure/bin/deploy.sh
🤖 Resolves #9726 
This branch makes the deployment artifact (and resulting deployment) smaller in Azure.
The deploy.sh script (really, it's a "build artifact" script) currently builds the application and then zips the entire workspace as the deployment artifact.  This branch copies only the needed files to a staging directory first, then compresses those files for the artifact.
This reduces the deployment artifact size from 611 MB to 395 MB.  The build process does seem to take a little longer (~40s) but still within the normal range we see.
1. Can build this branch in Azure
2. Can deploy the artifacts from this branch to an app service.
> [Debt] Make deployment artifact smaller

- documentation/freshdesk.md
🤖 Resolves #8900.
This PR adds additional Freshdesk instructions for local testing in the form of a markdown document.
> [!NOTE]
> I wasn't sure whether or not to link to the new markdown file somewhere. I decided against it (root `README.md` seemed like the wrong place, within the maintenance instructions also seemed like an odd place) but I am happy to entertain any suggestions, if they come in.
1. Read through and carry out instructions in `documentation/freshdesk.md`
2. Ensure instructions work and are easy to understand
> [Docs] Adds Freshdesk instructions for local testing

- api/database/migrations/2024_03_13_134951_create_experiences_table.php
🤖 Resolves #10146 
This branch fixes the JSON escaping of fields in the database migration for the experience refactor.
Manual string concatenation is not a great way to construct JSON literals since it doesn't handle escaping any of the JSON reserved characters. :facepalm: This branch instead uses the PostgreSQL builtin function `json_build_object` to contstruct the objects safely.
1. Check out https://github.com/GCTC-NTGC/gc-digital-talent/commit/57447242a25240c8c53fd53155cd50b3a5a578cb which is the commit right before the merge commit with the flawed migration.
2. Setup the project
3. Manually edit one or more rows in the five experience tables to add some reserved JSON characters or full JSON literals.
4. Check out the branch head
5. Run the DB migrations
> [Bug] Fix experience migration JSON escaping

- packages/i18n/src/const.ts
- packages/i18n/src/index.tsx
- packages/i18n/src/utils/localize.ts
🤖 Resolves #10145 
Removes a file for a const (`STORED_LOCALE`) that was only being used in one place.
2. Switch languages
3. Confirm the proper value is stored in local storage
> [Debt] Remove stored locale

- api/database/factories/AssessmentResultFactory.php
🤖 Resolves #10162 
- Removes `other-justification-notes` from AssessmentResultFactory.
1. Try running fresh migration and seeder `php artisan migrate:fresh --seed`
2. Ensure no errors pop up
> [Bug] Remove other_justification_notes from AssessmentResultFactory

- .github/workflows/jest.yml
Jest does not always run upon merging a branch in, this prevents code coverage uploads. PHP Unit always runs so it always pushes up a new coverage report. 
As seen in devspam, this causes confusion with drastic coverage changes stemming from if either one or two workflows uploaded something
Just having Jest always run for merges. Shouldn't really run that much more often, but clear up the occasional confusion.
> [Tooling] Jest always runs on merging

- apps/web/src/components/Header/Header.tsx
- apps/web/src/components/Layout/AdminLayout/AdminLayout.tsx
- apps/web/src/components/Layout/IAPLayout.tsx
- apps/web/src/components/Layout/Layout.tsx
- apps/web/src/components/Layout/SitewideBanner.tsx
- apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx
- apps/web/src/components/Profile/components/LanguageProfile/ConsideredLanguages.tsx
- apps/web/src/components/Router.tsx
- apps/web/src/components/SEO/SEO.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
- apps/web/src/pages/DirectiveForms/DigitalServicesContractingQuestionnaire/DigitalServicesContractingQuestionnairePage.tsx
- apps/web/src/pages/DirectivePage/DirectivePage.tsx
- apps/web/src/pages/DirectivePage/Resources.tsx
- apps/web/src/pages/Home/HomePage/components/About/About.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/Display.tsx
- packages/auth/src/components/AuthenticationProvider.tsx
- packages/eslint-config-custom/react.js
- packages/forms/src/components/ErrorSummary.tsx
- packages/i18n/src/components/LanguageProvider.tsx
🤖 Resolves #10133 
Replaces the `useLocale` hook with the `getLocale` helper in pages and components.
The `useLocale` is for use above the `LanguageProvider` or, setting the locale. This replaces it in any place it was being used outside of those use cases.
2. Confirm language switching still works for the places where locale was updated
3. Confirm `useLocale` only appears in `Header`, `Router` and context providers
> [Debt] Replace `useLocale` hook

- api/app/Models/PoolCandidate.php
- api/database/factories/PoolCandidateFactory.php
- api/database/migrations/2024_04_25_143252_remove_cmo_identifier_column_pool_candidates_table.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/pages/Users/UserInformationPage/components/AddToPoolDialog.tsx
- apps/web/src/pages/Users/UserInformationPage/components/mutation.ts
- packages/fake-data/src/fakePoolCandidates.ts
🤖 Resolves #10155.
This PR removes the `cmoIdentifier` field from the `PoolCandidate` GraphQL type and the `cmo_identifier` column from the `pool_candidates` database table.
1. Ensure no instances of `cmoIdentifier` or `cmo_identifier` in the codebase (exceptions being in migration files)
2. Build app
3. Navigate to PoolCandidatesTable
4. Ensure page loads with no errors
5. `php artisan migrate`
6. Observe `cmo_identifier` column does not exist in the `pool_candidates` database table
7. `php artisan migrate:rollback --step=1`
8. Observe `cmo_identifier` column does exist with NULL values in its rows in the `pool_candidates` database table
> [Debt] Removes `cmoIdentifier` field and `cmo_identifier` column

- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/IndexPoolCandidatePage.tsx
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #9788.
This PR updates the `<title>` tag to match page tab title.
1. Navigate to `/admin/pools/:pool-id`
2. Click on Talent placement link
3. Observe the `<title>` tag is the same as the page tab title.
https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/94cb1977-3ab7-4971-ba19-eca91c8a207b
> [Debt] Updates title tag to match page tab title

- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.test.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.tsx
🤖 Resolves #10079 
Adds placed tentative to the search request tables default fitlers.
3. Navigate to a search request
4. Scroll down to the candidates table
5. Confirm the status "offer in progress" appears
6. Confirm the query it sent with the filter attached
> [Feature] Placed tenatative default search request candidate filter

- apps/web/src/components/UserProfile/ExperienceByTypeListing.tsx
- apps/web/src/components/UserProfile/ExperienceSection.tsx
🤖 Resolves #10197.
This PR hides edit button for all users in the admin user profile since this is not the intended user flow to edit experiences.
1. As a user with an admin role, navigate to `/admin/users/:user-id/profile#career-timeline-section`
2. Ensure the user's page who is being visited has existing experiences and is not the current user
3. Observe  lack of an edit button on `ExperienceCard` in By Type and By Date tabs
> [Fix] Hides edit button in `ExperienceCard` on admin user profile

- apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.test.tsx
- apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #10196.
This PR removes some extra spaces rendered in `SkillAccordion`. Also, it consolidates some i18n messages and brings some of the messages in line with those used for the experience labels which needed only a bit of refactoring in the `SkillAccordion` component in order to eliminate some duplicates. Finally, it adds some conditional rendering in order to avoid empty HTML tags.
2. Navigate to Accordion Education Example story
3. Observe extra spaces
4. Check Chromatic for any other different to **Accordion {Type} Example stories**
> [Fix] Removes `SkillAccordion` extra spaces

- packages/ui/src/components/Board/Board.tsx
🤖 Resolves #10194
Improve the styling for the chevron, using the font function.
Replicates the styling used for accordion components and the collapsible elsewhere, though, could not just nest things in buttons without chaining buttons. 
1. Navigate to Board component
2. Switch to Dark
3. Styling of chevron changes
> [Bug] Missing styling for chevron in Screening and assessment page

- apps/web/src/components/ExperienceFormFields/AdditionalDetails.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #10222.
This PR removes the word **optionally** from the additional details field description since the additional details field is required and not optional.
1. Navigate to `/users/:user-id/personal-information/career-timeline/:experience-id/edit#additional-details`
2. Verify the word **optionally** does not appear anywhere in the description of the additional details field
3. Navigate to `/applications/:application-id/career-timeline/add`
4. Verify the word **optionally** does not appear anywhere in the description of the additional details field
> [Copy] Removes word optionally from additional details field description

- api/tests/Feature/ApplicantFilterTest.php
🤖 Resolves #10201 
Resolve the intermittent failures. 
Appears to be due to the `->unique()` not exactly working as expected, simplified this step instead.
As well, don't think this test needs seeding of 100 candidates, so cut that down a bit. Performance improved!
1. CI succeeds
2. Run below locally successfully
```
for i in {1..50}; do docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/ApplicantFilterTest.php"; done
```
Faster!
> [Bug] Resolve flaky `ApplicantFilterTest` test

- apps/web/src/components/NotificationList/NotificationList.tsx
- apps/web/src/components/NotificationList/NotificationListPage.tsx
- apps/web/src/components/NotificationList/NotificationPortal.tsx
🤖 Resolves #9960 
Fixes an issue where the notification dialog was not properly rendering its null state.
These were using portals to render the null state but, the portal had the wrong ID. This fixes it to make the IDs unique and available for the root of the portal.
1. `pnpm run dev`
3. Make sure you have no notifications for the user you logged in as
4. Open the notification dialog
5. Confirm the null message appears
> [Fix] Notification dialog null state

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
🤖 Resolves #10231 
Updates the candidate count query to use a new field that counts the rows of non-draft pool candidates on a pool.
3. Navigate to the main "Process information" page for a published pool with candidates
4. Confirm the total candidates count matches the non-draft pool candidates in the pool
> [Debt] Improve pool candidate count query

- infrastructure/bin/post_deployment.sh
- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #7155 
This fixes the config issues from the Nginx Amplify static analysis tool.
1. To fix the "missing a default.conf file" warning I added a `touch` command to the post-deploy script to create an empty file.
2. To fix the "missing a server_name directive" warning I added a substitution from an Azure variable that holds the domain name of the site.
3. To fix the two warnings about the git rule, I deleted it. :axe:  We no longer send the entire workspace to the app service so there's no way a real .git directory will be present.  If someone wants to see our git repo they can go to GH to get it.  :grin: 
1. Site can be built and visited locally.
2. Site can be built and visited in Azure.
> [Debt] Fix Nginx Warnings

- api/app/Enums/PoolCandidateSearchStatus.php
- api/database/migrations/2024_05_03_182815_update_search_request_status_weight_column_not_complicant.php
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/SearchRequestTable/components/utils.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #9947 
Adds a new "Not compliant" status for search requests.
When I was adding the weight for sorting I noticed two things:
1. We weren't actually using it to sort search requests
2. We did not have a weight for "done - no candidates"
So, I updated the sorting query to use the weight instead of doing it alphanumerically. As well, I added a weight for the no candidates and slotted it in just below the normal "done" status.
3. Navigate to search request table `/admin/talent-requests`
4. Sort by status
5. Confirm order appears correct
6. Confirm you can edit a search request to set status to "not compliant"
> [Feature] Not compliant request status

- api/app/Models/PoolCandidateFilter.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #10211.
This PR adds deprecated tags to the `PoolCandidateFilter` model and the `poolCandidateFilter` field.
1. Open `api/app/Models/PoolCandidateSearchRequest.php` Line 83 in IDE 
2. Observe `PoolCandidateFilter` code has strikethrough and deprecated
3. Navigate to http://localhost:8000/graphiql
4. Write query `PoolCandidateSearchRequest. poolCandidateFilter`
5. Observe deprecation message for `poolCandidateFilter`
> [Debt] Deprecates `PoolCandidateFilter` model, `poolCandidateFilter` field

- .github/workflows/chromatic.yml
🤖 Resolves #10281.
This PR updates the Github Chromatic workflow to run whenever the `chromatic.yml` file itself is changed. It used to, but stopped when the filename of the workflow itself was changed.
1. Observe that this PR runs the Github Chromatic workflow since the file has been changed
2. Verify no references to `storybook.yml` in the codebase
> [Tooling] Updates Chromatic workflow filename references

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.stories.tsx
- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/pages/Applications/ApplicationQuestionsPage/components/AnswerInput.tsx
- apps/web/src/pages/SearchRequests/RequestPage/RequestPage.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.tsx
- apps/web/src/types/experience.ts
- apps/web/src/utils/experienceUtils.tsx
- packages/eslint-config-custom/index.js
🤖 Resolves #10206 
Adds  `__typename` to list of allowed underscore dangle rule in eslint. 
This comes from the API and we need to use it some places so instead of ignoring the rule in all those places, we are just going to add it to the allow list.
1. Confirm `pnpm run lint` runs with no errors
> [Debt] Allow `__typename` underscore dangle

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
🤖 Resolves #10235 
Adds the ability for sorting the pool candidates table by the skill count column
While working on this, I noticed we still had some old code for "locking" columns when record of decision flag is not present. Since we recently removed this flag, the locking was happening at the query level when it was not meant to be. So, this also removes that old code to no longer lock column sorting on this table.
3. Navigate to the pool candidates table (`/admin/pool-candidates`)
4. Add alot of skills tot he filters
- Also, remove the government employee filter and set both status filters to "all" to maximize the candidates displayed
5. Sort by the "skill count" column
6. Confirm the results are sorted as expected
> [Fix] Allow sorting candidates table by skill count

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.stories.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/ScreeningAndEvaluationPage/ScreeningAndEvaluationPage.tsx
🤖 Resolves #10223 
Updates the screening and evaluation page to use a batched, paginated query to prevent memory errors on large data sets.
> [!TIP]
> To test this effectively, it is best to seed a lot of candidates for a specific pool.
> `PoolCandidate::factory()->create(['pool_id' => '{poolId}']);`
2. Navigate to screening and decision page for a pool
3. Confirm the columns show loading message at first
4. Confirm data is batched in sizes of 100
> [Feature] Batch candidate query for screening and evaluation

- .github/workflows/chromatic.yml
:robot: Resolves #10296
Pins chromatic action to a stable patch release to fix the workflow and allow dependabot to bump it in the future.
Check chromatic? :thinking:
> [Fix] Pin chromatic to previous patch release

- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/UserInformationPage/components/ChangeStatusDialog.tsx
🤖 Resolves #10283.
This PR removes a trailing space on status link in red Candidate status box that shouldn't exist.
2. Navigate to `/admin/candidates/:candidate-id/application`
3. Observe no trailing space on status link in red Candidate status box
> [Fix] Removes trailing space in status link

- apps/web/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #10299.
This PR removes beta label from theme switcher.
2. Navigate to home page
3. Verify beta label is no longer part of the theme switcher
> [Feature] Removes beta label from theme switcher

- apps/web/src/lang/fr.json
- packages/client/src/exchanges/specialErrorExchange.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/errorMessages.ts
🤖 Resolves #8283.
This PR updates the message returned in a toast for when requests that are rejected by the firewall.
Fixes a typo where **our** was being translated incorrectly as **votre**: https://github.com/GCTC-NTGC/gc-digital-talent/pull/10338/commits/53eda91dfd2f3fc3efc8de552503b67636b883c1.
> [!IMPORTANT]
> Temporarily remove `if` statement wrapping `toast.error(intl.formatMessage(errorMessages.requestRejected));` in https://github.com/GCTC-NTGC/gc-digital-talent/blob/0d3464a8e34e010c6d2e2c922f5685938854a8e0/packages/client/src/exchanges/specialErrorExchange.ts#L24-L30
1. Navigate to a page that makes a request
2. 🐻 witness to the 🍞 💥
> [Copy] Updates error message copy for firewall rejections

- apps/web/src/components/UserProfile/ExperienceSection.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #10198.
This PR adds null state for when no skills have been linked to any experiences.
- [Consolidated `No information has been provided` strings](https://github.com/GCTC-NTGC/gc-digital-talent/commit/2e9091f266e53cc2ade9ac7b69ab5c3aeb9270bb) where the only difference was a period (kept the one with correct punctuation and 🪓 the one without.
- [Replaced `div` with `Well` component for no skills have been linked to any experiences null state and no experiences null state](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10336/commits/e55b417efb77f5395309d755d66164dc7e4d002e).
1. As a user with an admin role, navigate to `/admin/users/:user-id/profile#career-timeline-section`
2. Ensure …
> [Fix] Adds null state for when no skills have been linked to any experiences

- apps/web/src/components/Layout/AdminLayout/AdminLayout.stories.tsx
🤖 Resolves #10343.
This PR adds chromatic mode for `AdminLayout` to stabilize the theme switcher in the snapshot.
1. Open chromatic build for this PR
2. Verify canvas and snapshot have the same state (system default) for the theme switcher in `AdminLayout` story
> [Fix] Adds chromatic mode for `AdminLayout`

- apps/web/src/pages/Notifications/NotificationsPage/NotificationsPage.tsx
- apps/web/src/pages/Profile/AccountSettings/types.ts
- apps/web/src/pages/Profile/AccountSettings/utils.ts
🤖 Resolves #10329 
Updates the notification settings to display the proper value in the check boxes.
This also fixes the link from the notifications page to notification settings.
2. Go to your notifications page
3. Click on the "Update settings" link in the sidebar
4. Confirm it takes you to the Notification settings section on the Account settings page
5. Update settings
6. Confirm the check boxes are checked for items not in the ignored array
> [Fix] Notifications settings inverted

- apps/web/src/components/NotificationList/NotificationItem.tsx
🤖 Resolves #10209 
Moves the unread indicator on notifications to the top of the notification text.
1. Build `pnpm dev`
2. Seed a notification
- Easy way is logging in as admin `admin@test.com`, applying to process, then changing your status on that process
3. Check both the notification dialog and notification page `/applicant/notifications`
4. Confirm the unread indicator aligns with the top text
> [Fix] Move unread notification indicator

- packages/eslint-config-custom/index.js
🤖 Resolves #10379 
Updates the ESLint parser options to work with VSCode.
1. Open a typescript file
2. Confirm ESLint loads and functions as expected
3. Run `pnpm run lint --force`
4. Confirm it functions with no error
> [Fix] Parser options in ESLint

- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/KeywordSearchTest.php
- api/tests/Feature/PoolCandidateSearchTest.php
- api/tests/Feature/UserTest.php
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/pages/Users/IndexUserPage/components/utils.tsx
🤖 Resolves #9963 
Remove the comma separation from the text search from front, API, and back. 
1. Commas will not split, ensure searching not broken for tables
2. Not much to actually test
> [Debture] Remove search comma separation

- apps/web/src/components/PoolCandidatesTable/poolCandidateCsv.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/IndexUserPage/components/userCsv.tsx
🤖 Resolves #10335.
This PR adds unformatted version of string for the column header **I have completed a Public Service Commission evaluation of my second official language.** in the pool candidates and users generated CSV documents.
It would have been nice to remove the `<strong>` tags wrapping parts of the original string altogether but 🤷.
1. Download CSV on pool candidates table
2. Observe column title for **I have completed a Public Service Commission evaluation of my second official language.** is without `object` 
3. Download CSV on users table
4. Observe column title for **I have completed a Public Service Commission evaluation of my second official language.** is without `object`
> [Fix] Adds unformatted version of string for CSV column header

- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateSearchTest.php
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/SearchRequestCandidatesTable.tsx
🤖 Resolves #10081
Updates the pool candidate tables classification filters to not also filter out unqualified candidates.
Adds a new appliedClassifications field to PoolCandidateSearchInput which won't also filter based on status.
1. Ensure you have a pool with at least on each of qualified, expired, and non-qualified status (ex. screened in) as well as at least one qualified candidate of a different classification.
2. Navigate to the search page `/search`.
3. Filter to the classification of the pool in step one and make note of the candidate count.
4. Fill out the necessary fields to submit and talent request for the classification.
5. Navigate to the talent requests page `/admin/talent-requests`.
6. Select to view your new request.
7. Scroll down to the candidate results section and …
> [Feature] Admin table classification filter doesn't also filter status

- README.md
- apps/e2e/cypress/README.md
- documentation/accessibility.md
- documentation/notifications.md
- documentation/translation.md
- infrastructure/README.md
- maintenance/README.md
This PR changes formatting in some of the markdown files to use [GitHub's alert markdown extension](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). It also fixes a typo and changes some other copy syntax.
> [!TIP]
> An apple a day keeps the doctor away.
> [Docs] Changes markdown formatting to use alerts

- apps/e2e/cypress/e2e/admin/pools.cy.ts
- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
🤖 Resolves #10373
Enable previewing a draft pool with the protected endpoint functional as well as have it asserted in E2E testing. 
1. Have protected endpoints active
2. Navigate to process main page (`en/admin/pools/:id`) for a published pool
3. Observe the view link directing you to the advertisement talent side
4. Navigate to the process page for a draft pool
5. Observe the preview link directing you to a poster view nested within admin
> [Bug] Previewing a draft pool

- apps/web/src/hooks/usePoolMutations.ts
- apps/web/src/pages/Pools/ViewPoolPage/components/PublishProcessDialog.tsx
🤖 Resolves #10339.
Makes the publish pool dialog only close after the mutation succeeds.
I actually changed it to stop closing the dialog automatically at all since we navigate away from the page when the mutation succeeds anyway.
1. Slow down the publish pool mutation (add a manual delay, throttle in browser, etc)
2. Find or create a draft pool and ensure it is ready to be published
3. Navigate to the process information page for the draft pool `/admin/pools/{id}`
4. Select to publish the pool
5. Confirm the dialog does not close until the mutation succeeds and that it navigates to the 'processes' page `/admin/pools`
6. Force the publish pool mutation to fail
7. Repeat steps 2-4
8. Confirm the dialog does not close (or navigate away) when the mutation fails.
> Publish pool dialog only closes on mutation success

- infrastructure/azure-pipelines-dev.yml
- infrastructure/azure-pipelines.yml
- infrastructure/bin/set_php_versions.sh
🤖 Resolves #10202.
This PR updates the Azure Pipeline `vmImage` to use the same version of Ubuntu as the GitHub action worklfows.
Because the GitHub runner `ubuntu-22.04` only includes a single version of PHP, version 8.1, which is different from what is currently used by us, version 8.2, a PPA is required in order to install a different version of PHP along with its extensions.
1. Deploy in Azure to dev vertical
2. Verify PHP version 8.2 is installed and app works as it did before the PPA
> [Debt] Updates Azure Pipelines ubuntu image 

- apps/web/src/components/FilterDialog/FilterDialog.tsx
- apps/web/src/components/Table/ResponsiveTable/SearchForm.tsx
- apps/web/src/components/Table/ResponsiveTable/Table.tsx
🤖 Resolves #10038 
Fixes the layout of the table controls on smaller screens.
The provided layout did not work well on small screens so that was left unchanged and only the medium sized screens were affected in this.
3. Navigate to a table with all controls (search, hide columns, filter, add)
- The process table is a good example of this
4. Resize your window slowly
5. Confirm the buttons have an acceptable layout on all screen sizes until ~312px
> [Fix] Table control layout

- api/app/Notify/Client.php
🤖 Resolves #10473 
This branch moves the exception out of the GCNotify client constructor.  It seems that even if you mock the client with the facade the constructor is still called and the exception will occur.
1. Don't set a value for the GCNOTIFY_API_KEY variable
2. PHPUnit tests should not fail
> [Fix] Move exception out of GCNotify client constructor

- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
- apps/web/src/validators/profile/about.ts
🤖 Resolves #10435.
This PR adds back fields that are needed in the `DashboardHeadingUser` fragment.
704cb763ea6d99c6a4a9dbb027f54c6bedff3f04: Removes a duplicate key (`preferredLanguageForInterview`) and adds in a missing key, `preferredLanguageForExam`, for the `aboutSectionHasEmptyRequiredFields` validator function.
2. Create a user account
3. Navigate to `/applicant`
4. Observe incomplete status (red) on Personal and contact info item
5. Navigate to `/applicant/personal-information#about-section`
6. Fill in required fields and submit form
7. Navigate to `/applicant`
8. Observe complete status (green) on Personal and contact info item
> [Fix] Profile about section completeness

- apps/web/src/lang/fr.json
- apps/web/src/utils/nameUtils.tsx
🤖 Resolves #10425.
This PR changes the occupational group abbreviation for IT in French from TI to IT since the [Government of Canada does not translate the acronym](https://www.canada.ca/fr/secretariat-conseil-tresor/services/conventions-collectives/groupes-professionnels/technologies-information.html). 
It also changes the occupational group abbreviation for AS in French from SA to AS since the [Government of Canada does not translate the acronym](https://www.canada.ca/fr/secretariat-conseil-tresor/services/conventions-collectives/groupes-professionnels/services-programmes-administration.html#occ-as).
2. Navigate to More information (Informations complémentaires) section of a process …
> [Copy] Updates occupational group abbreviations in French

- apps/web/src/lang/fr.json
- apps/web/src/pages/Skills/components/SkillTable.tsx
- apps/web/src/pages/Skills/components/tableHelpers.tsx
🤖 Resolves #10037 
fixes some styling issues on the skills table by displaying families as a default list and wrapping the description in a spoiler.
3. Navigate to the skills page `/admin/skills`
4. Confirm the families show up as a vanilla list
5. Confirm the description field has a spoiler
> [Fix] Skill table styling

- api/app/Policies/CommunityPolicy.php
- apps/e2e/cypress/e2e/talentsearch/search-workflows.cy.ts
🤖 Resolves #10476 
This fixes the communities policy to allow anonymous users to view any.
The policy omitted the option user argument that lead to requiring the policy to be authenticated. It seems odd, but we need to include `?User $user` in the arguments to allow anonymous users (even if we never use it).
REF: https://laravel.com/docs/11.x/authorization#guest-users
1. Ensure you are not logged in
2. Confirm you can submit a search request
> [Fix] Anonymous view of communities

- api/tests/Feature/PoolApplicationTest.php
🤖 Resolves #10475
Fixes the flaky test.
Appears it was due to the seeding attaching a skill that varied in whether it was technical or behavioural. Only technical skills are required so it would fail to see the expected error if it was a behavioural skill.
Also updated the test after it, that one wasn't flaky but it better asserts its test case this way
1. CI successful 
2. Local testing 
Run locally
`for i in {1..25}; do docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/PoolApplicationTest.php"; done`
> [Bug] Flaky test in PoolApplicationTest file

- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/InclusivityEquityPage/InclusivityEquityPage.stories.tsx
- apps/web/src/pages/InclusivityEquityPage/InclusivityEquityPage.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #10508 
Adds page for inclusivity and equity along with re-instating the accordion for it on the advertisement page.
2. Navigate to a job advertisement
3. Scroll down to the "Other information" section
4. Confirm the accordion for inclusivity and equity appears
5. Confirm it links to the new page (`/inclusivity-equity`)
6. Confirm content matches [mock-up](https://www.figma.com/design/DoZfqY9Rm8FkQ3pZT3uEsz/Inclusivity-statement-(All-users)?node-id=1-2&t=qYGIse7xd9vIPDjG-0) and links go to the appropriate pages
> [Feature] Inclusivity and equity page

- Makefile.nix
🤖 Resolves #9838 
This branch adds a makefile especially for Linux environments where the right versions of php, composer, node, and pnpm are already installed.  It does not use the maintenance container and, as a result, does not have any files owned by root.  It also does not use any of the maintenance scripts.
Unfortunately, our environment requires setting the ownership to www-data on certain files so there is a sudo prompt in the "setup" script.
The scripts will fail if any files are already owned by root.  I recommend cleaning your workspace first with the `git_clean` script.  WARNING - it will delete all uncommitted files!  It also has a sudo prompt.
I found a VS Code extension (https://marketplace.visualstudio.com/items?itemName=carlos-algms.make-task-provider) that works nicely …
> [Feature] Local-only makefile for Linux

- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/CandidateNavigation/CandidateNavigation.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesForm.tsx
🤖 Resolves #10530 
- Fixes notes section scroll styling by setting overflow-y to auto.
-  Switches trigger button text from "Edit notes to "Add notes" depending on state.
3. View a pool candidate on admin side (e.g. `http://localhost:8000/en/admin/candidates/{poolCandidateId}/application`)
4. Ensure notes looks correct after adding and removing notes.
> [Debt] Fix styling to more actions side menu notes section

- .github/workflows/playwright.yml
🤖 Resolves #10552.
This PR removes Firefox tests from Playwright workflow.
It also limits the browsers installed to `chromium` and `webkit` as `firefox` is no longer needed to be installed.
1. Verify playwright GitHub workflow does not install Firefox
2. Verify playwright GitHub workflow passes
> [Tooling] Removes Firefox tests from Playwright workflow

- api/database/seeders/PoolCandidateTestSeeder.php
🤖 Resolves #10507 
Updates seeders for (non) veteran candidates to be accurate.
1. Run seeders `make seed-fresh`
2. Confirm the candidates labelled "Veteran" and "Not a veteran" have the proper armed forces status
> [Fix] (Non) Veteran seeding

- apps/playwright/.eslintrc.js
- apps/playwright/fixtures/AppPage.ts
- apps/playwright/fixtures/ApplicationPage.ts
- apps/playwright/package.json
- apps/playwright/playwright.config.ts
- apps/playwright/tests/admin/admin-workflows.spec.ts
- apps/playwright/tests/admin/process-actions.spec.ts
- apps/playwright/tests/admin/process-permissions.spec.ts
- apps/playwright/utils/auth.ts
- pnpm-lock.yaml
🤖 Resolves #10575 
Improves the authentication of playwright tests to hopefully make them more reliable.
While the tests consistently pass in CI (with only one worker), when parallelized them, they seem to be flaky which all seems to be coming from the auth. This makes some changes that seem to allow them to pass more consistently when run locally.
> [!NOTE]
> This also adds a [recommended ESLint rule](https://playwright.dev/docs/best-practices#lint-your-tests) to avoid floating promises that could also cause issues with stability.
> [!NOTE]
> Webkit is still struggling for me but chromium and firefox seem fine :woman_shrugging: 
1. Run tests a few times in firefox `pnpm run e2e:playwright:firefox`
2. Confirm reliabliulity has improved
3. Repeat 1-2 in chromium `pnpm run …
> [Fix] Improve playwright auth

- api/app/Models/Pool.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #10511 
Adds the process number to the admin pool table as well as the pool advertisement.
3. Navigate to the index pools page `/admin/pools`
4. Confirm process number appears and can be sorted as well as found through search
5. View the advertisement of a pool
6. Confirm process number appears at the bottom right
> [Feature] Add process number to table and advertisement

- apps/web/src/components/ExperienceSkillFormDialog/ExperienceSkillForm.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #10569 
Updates the link experience to skill dialog to move question prompts out of accordion. As well as changes the first prompt.
3. Start application
4. Continue to skills section
5. Open the link experience dialog
6. Confirm it matches the ticket descrioption
> [Feature] Update experience skill dialog

- api/app/Enums/PriorityWeight.php
- api/app/Models/PoolCandidate.php
- api/app/Providers/GraphQLServiceProvider.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/utils/poolCandidate.ts
- apps/web/src/utils/userUtils.ts
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #8668 
- Adds PriorityWeight enum
- Updates PoolCandidateSearchInput to accept enum instead of the associated integer weights to help make it more readable on the frontend.
- Question: I've added a static function which contains a map of the enum value to it's associated weight, and returns the weight (int). Should we also update the `user.priorityWeight` field to be the PriorityWeight enum as well, and call that method when needed?
1. Build app `make setup` 
3. Go to pool candidates table and ensure the "Category" filter (priorityWeight) works correctly.
> [Debt] Priority weight enum

- api/app/Http/Controllers/SupportController.php
🤖 Resolves #10581.
This PR sets the `type` field on a Freshdesk ticket created via the support page.
> [!IMPORTANT]  
> Freshdesk environment variables will be required to test local submission of the support form.
1. Navigate to `/support` page
2. Fill out and submit the support form
3. Verify that the associated ticket in Freshdesk that was created has the `type` field set to the corresponding subject value
> [Feature] Sets `type` field on Freshdesk ticket

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #10616.
This PR adds a sentence to the skill requirements description on the job advertisement page.
2. Navigate to `/en/browse/pools/:pool-id#skill-requirements`
3. Verify new sentence renders at the end of the second paragraph of the description in English
5. Verify new sentence renders at the end of the second paragraph of the description in French
> [Copy] Adds sentence to skill requirements description job advertisement

- apps/web/src/pages/Pools/PoolAdvertisementPage/components/SkillAccordion.tsx
🤖 Resolves #10612.
This PR adds a conditional statement around the **Level: {skillLevel}** and **Level definition** text for legacy processes that do not have skill levels.
```sql
SELECT skill_id, required_skill_level FROM pool_skill WHERE pool_id = $pool_id
```
2. Navigate to a job advertisement `/browse/pools/:pool-id#skill-requirements`
3. Find from the `:pool-id` in the `pool_skill` database table and set `required_skill_level` to `NULL` (see previous SQL query section)
5. Navigate to a job advertisement `/browse/pools/:pool-id#skill-requirements`
6. Verify changed skill accordion with  `NULL` skill level doesn't render **Level: {skillLevel}** text in the accordion trigger or …
> [Fix] Adds conditional for skill accordion without `skillLevel`

- api/tests/Feature/ApplicantTest.php
- api/tests/Feature/AssessmentResultTest.php
- api/tests/Feature/AssessmentStepTest.php
- api/tests/Feature/AuthServiceProviderTest.php
- api/tests/Feature/DepartmentSpecificRecruitmentProcessFormTest.php
- api/tests/Feature/DigitalContractingQuestionnaireTest.php
- api/tests/Feature/ExperienceTest.php
- api/tests/Feature/GeneralQuestionResponsesTest.php
- api/tests/Feature/GeneralQuestionTest.php
- api/tests/Feature/HardDeleteOldUsersTest.php
- api/tests/Feature/KeywordSearchTest.php
- api/tests/Feature/Mutation/UpdateUserTeamRolesTest.php
- api/tests/Feature/NotificationTest.php
- api/tests/Feature/PoolApplicationTest.php
- api/tests/Feature/PoolCandidateSearchTest.php
- api/tests/Feature/PoolCandidateTest.php
- api/tests/Feature/PoolCandidateUpdateTest.php
- api/tests/Feature/PoolTest.php
- api/tests/Feature/ScreeningQuestionsTest.php
- api/tests/Feature/TeamsTest.php
- api/tests/Feature/UserRoleTest.php
- api/tests/Feature/UserSkillTest.php
- api/tests/Feature/UserTest.php
- api/tests/Unit/OpenIdBearerTokenTest.php
🤖 Resolves #10352 
Adds the missing namespaces to test files as well as fixing the imports.
1. Confirm all files under `app\tests` has a namespace
2. Confirm tests still pass
> [Fix] Add missing namespaces to test files

- api/database/factories/AssessmentResultFactory.php
- api/database/seeders/AssessmentResultTestSeeder.php
🤖 Resolves #10498 
Makes some justifications on `AssessmentResult` `null` when seeding fresh test data.
When the result decision is "unsure" or "on hold", the justification should be null in most cases. This updates the seeder to create more accurate data in that scenario instead of always setting a justification regardless of decision
1. Re-seed fresh data `make seed-fresh`
2. Login to the database at `http://localhost:8080`
3. Confirm that some `justifications` are `null` when the `assessment_decision` is either `null` or `HOLD`
> [Debt] Make some assessment decisions null

- apps/web/src/lang/fr.json
- apps/web/src/pages/DirectivePage/DirectivePage.tsx
🤖 Resolves #10648.
This PR removes the third paragraph describing the directive on digital talent.
2. Navigate to `/en/directive-on-digital-talent`
3. Observe only two paragraphs in What is the Directive on Digital Talent? section
> [Copy] Removes Third paragraph describing the directive on digital talent

- apps/web/src/pages/Auth/SignInPage/SignInPage.tsx
- apps/web/src/pages/Auth/SignUpPage/SignUpPage.tsx
🤖 Resolves #10635.
This PR fixes some i18n message keys that were incorrect. No need to translate to French since the translations already exist in the codebase.
2. Navigate to `/en/login-info`
3. Observe content for What can I do if my authenticator codes are no longer being accepted? item is Please contact our Help Desk for help with recovering your account.
4. Navigate to `/en/register-info`
5. Observe content for What can I do if my authenticator codes are no longer being accepted? item is Please contact our Help Desk for help with recovering your account.
> [Fix] FAQ answer for auth codes question

- api/tests/Feature/DigitalContractingQuestionnaireTest.php
- apps/web/src/pages/DirectiveForms/DigitalServicesContractingQuestionnaire/DigitalServicesContractingQuestionnairePage.stories.tsx
- apps/web/src/pages/DirectiveForms/DigitalServicesContractingQuestionnaire/fieldsSets/PersonnelRequirementFieldset.stories.tsx
🤖 Resolves #10644.
This PR skips directive forms tests and Chromatic snapshotting since the feature has no imminent launch.
> [!NOTE]
> Since storybook is not working, there is no way to test the disabling of Chromatic snapshots at the moment.
1. `make artisan CMD="test"`
2. Observe skipped tests for `DigitalContractingQuestionnaireTest`
> [Test] Skips directive forms PHPUnit tests and Chromatic snapshotting

- packages/i18n/src/lang/fr.json
🤖 Resolves #10676
Change the translated word
1. Observe lead level is no longer translated to "diriger"
> [Copy] Change diriger to principal

- api/tests/Feature/UserVerifyEmailTest.php
🤖 Resolves #10681.
This PR adds a namespace to the `UserVerifyEmailTest` PHPUnit test.
1. Verify `UserVerifyEmailTest` file is not skipped during autoloading in CI: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/9508374286/job/26209558009?pr=10682#step:7:542
2. Verify `UserVerifyEmailTest` does not comply with psr-4 autoloading standard message does not show CI: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/9508374289/job/26209558172?pr=10682#step:5:316
> [Fix] Adds namespace to `UserVerifyEmailTest` PHPUnit test

- apps/web/src/components/NotificationList/NotificationActions.tsx
- apps/web/src/lang/fr.json
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/errorMessages.ts
🤖 Resolves #10636 
Adds an announcement to ATs that the "mark all as read" was a success and an error alert on failure.
2. Login as any user (easier with `admin@test.com`)
3. Generate some notifications for the user
4. Open a screen reader
5. Use the "mark all as read" button either in the notifications dialog or on the `/applicant/notifications` page
6. Confirm success feedback is provided (announced)
> [a11y] Announce mark all as read success to ATs

- apps/web/src/components/NotificationList/NotificationItem.tsx
- apps/web/src/components/NotificationList/NotificationListPage.tsx
🤖 Resolves #10640 
- Moves focus onto the first item of newly loaded notifications
I found the easiest way to seed data was adding `admin@test.com` to a pool, then changing the pool candidate status as many times as needed...
2. Seed data
3. Go to notifications page
4. Try loading more notifications and ensure that focus lands on first loaded notification.
> [Accessibility] Focus on first loaded item

- apps/web/src/components/Footer/Footer.tsx
- packages/storybook-helpers/main.ts
🤖 Resolves #10769 
Stabilizes the footer snapshots.
We had some dynamic variables leading for false positives on chromatic diffs. This hardcodes those to make the snapshots more stable.
1. Run storybook `pnpm run storybook`
2. Confirm footer store contains the hard coded data
> [Fix] Stabilize snapshots

- api/config/cors.php
🤖 Resolves #10779 
Adds our missing auth paths to the allowed cors paths for the dev server.
1. Set token expiry to a low amount in ./infrastructure/conf/mock-oauth2-server.json
2. Bust config cache `make artisan CMD="config:cache"`
3. Run he dev server pnpm run watch
4. Login
5. Wait for the token to expire
6. Navigate to attempt a refresh
7. Confirm token can be refreshed
> [Fix] Add auth paths to allowed cors

- api/tests/Feature/PoolTest.php
🤖 Resolves #10651.
Fixes the flaky pool bookmark scope test.
1. CI successful
2. Local testing succeeds
`for i in {1..25}; do docker-compose run --rm -w /var/www/html/api maintenance sh -c "./vendor/bin/phpunit ./tests/Feature/PoolTest.php"; done`
> [Fix] Flaky pool bookmark scope test

- documentation/sign-in-canada.md
🤖 Resolves #10766.
This PR adds `request_responder`, `community_manager` roles to the Sign in Canada documentation example.
1. Observe `documentation/sign-in-canada.md` account creation adds `request_responder`, `community_manager` roles to the user
2. Verify updated tinker command still works
> [Docs] Adds `request_responder`, `community_manager` roles

- apps/web/src/components/Table/ResponsiveTable/NullMessage.tsx
- apps/web/src/components/Table/tableMessages.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Classifications/components/ClassificationTable.tsx
- apps/web/src/pages/Departments/components/DepartmentTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/SkillFamilies/components/SkillFamilyTable.tsx
- apps/web/src/pages/Skills/components/SkillTable.tsx
- apps/web/src/pages/Teams/IndexTeamPage/components/TeamTable/TeamTable.tsx
- apps/web/src/pages/Teams/TeamMembersPage/TeamMembersPage.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/IndividualRoleTable.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/TeamRoleTable.tsx
🤖 Resolves #9463.
This PR removes the fallback for the `nullMessage.description` prop for the `Table` component and adds custom messages for where there is an `add` prop.
1. Navigate to tables
2. Verify any table that has an add or create button has an instructional description when the table yields no results.
> [Fix] Updates table `nullMessage` descriptions

- Makefile
- docker-compose.yml
- infrastructure/bin/post_deployment.sh
- infrastructure/maintenance-container/Dockerfile
- infrastructure/webserver.Dockerfile
🤖 Resolves #10777 
This branch adds the postgresql to the app service setup to ensure that a fresh setup is possible.  It also adds it to the local webserver docker container to mirror the setup.
I created a custom Dockerfile for the webserver image.  Before, we were pretty strict about using a pristine image but this is a convenient way to mimic some of the customization we perform on the image during post-deploy.
1. Rebuild the webserver image `docker-compose build webserver`
2. Composer install by whatever method you normally use
1. Deploy this branch to the dev vertical
2. SSH in
> [Fix] Add postgresql client to app service

- apps/web/package.json
- packages/forms/package.json
- packages/storybook-helpers/package.json
- packages/ui/package.json
- pnpm-lock.yaml
🤖 Resolves #10796 
This branch rolls back the version of framer-motion in use.  It seems like the latest update "fixes" something that breaks our notification pane.
1. Rebuild
2. Make sure notification pane goes in and out without locking the app
> [!Note]
This is a quick-and-dirty fix.  I'll post an issue to try to solve the root cause and write that regression test.
> [FIX] Roll back framer-motion

- .github/dependabot.yml
🤖 Resolves #10818.
This PR adds a Dependabot group for radix dependencies so that they are grouped into a single PR.
1. 🤞 it works on Dependabot Thursday! 🤷
> [Tooling] Adds Dependabot radix group

- apps/web/src/pages/Applications/ApplicationCareerTimelinePage/ApplicationCareerTimelinePage.tsx
- apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineSection.tsx
🤖 Resolves #10784.
This PR fixes the spacing between actions and well or cards for the career timeline in the profile and application contexts.
1. Navigate to `/applicant/career-timeline#manage-your-career-timeline`
2. Verify spacing between actions and well or cards matches design
3. Navigate to `/applications/:application-id/career-timeline`
4. Verify spacing between actions and well or cards matches design
> [Fix] `ExperienceSortAndFilter` spacing

- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
🤖 Resolves #10850 
Associates the title and description for notifications with the parent dialog.
I just forgot to use the primitves since this is a custom solution :sweat_smile: 
3. Open notification dialog
4. Confirm no errors in console
5. Inspect the dialog a11y tree
6. Confirm it has the proper title and description
> [Fix] Associate notification dialog title and description with dialog

- apps/web/src/components/Hero/Hero.stories.tsx
- apps/web/src/components/Layout/AdminLayout/AdminLayout.stories.tsx
- packages/ui/src/components/DropdownMenu/DropdownMenu.stories.tsx
🤖 Resolves #10851.
This PR fixes unstable storybook snapshots in Chromatic and adds modes to several stories that were not taking the listed snapshots because of the missing `parameters` key.
1. Open Chromatic build for this PR
2. Verify canvas and snapshot have the same state (system default) for the theme switcher in `AdminLayout` story
3. Verify `DropdownMenu` and `Hero` stories have snapshots for all the modes listed
> [Fix] Adds missing `parameters` key

- api/database/seeders/ProdSeeder.php
🤖 Resolves #10767 
Adds the community seeder to the list of seeders run in production.
1. Refresh database `make artisan CMD="migrate:fresh"`
2. Run prod seeder `make artisan CMD="db:seed --class=ProdSeeder"`
3. Check database and confirm bot initial communities exist
> [Fix] Add community seeder to prod seeder

- apps/playwright/tests/applicant/create-account.spec.ts
- apps/web/src/components/Profile/components/PersonalInformation/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
- apps/web/src/pages/Teams/CreateTeamPage/components/CreateTeamFormFields.tsx
- apps/web/src/pages/Teams/ViewTeamPage/components/ViewTeam.tsx
- apps/web/src/pages/Users/UserInformationPage/components/AboutSection.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #10822.
Renames several email fields to 'Contact email address'.
1. Confirm the various locations listed in the issue now use 'Contact email address'
- Profile
- Registration form
- Pool Candidate table
- User table
- Profile , CSV downloads
2. Look for anywhere else I may have missed
> [Copy] Rename email fields to 'Contact email address'

- api/app/Jobs/GcNotifyApiRequest.php
🤖 Resolves : #10820 
This branch sets the notification throttle to bucket by job.  It also tunes the retry timing.  
This will behave differently now:
1. If a single job hits the exception throttle, all other jobs will continue in their own timing without changes.
2. The tuned exception throttle works like this: "Wait four minutes between tries.  Try again up to three times then blocked for 10 minutes.  Job fails if not complete in 30 minutes total."
Note: as far as I can tell, if a message is accepted by the API but is not deliverable it does not trigger an API error.  So this may not even be an issue in production.
1. Set up the "steps to reproduce" from the issue.
2. Observer that your legitimate email is properly sent.
> [Fix] Tune notification throttle

- api/app/GraphQL/Mutations/DuplicatePool.php
- api/tests/Feature/PoolTest.php
🤖 Resolves #10696 
Updates pool duplication to copy over all pool skill pivot data.
2. Create a pool with various skill types and levels
3. Duplicate the pool
4. Confirm skills and all pivot data was copied to the new pool
> [Fix] Copy skill levels on pool duplication

- api/composer.json
- api/composer.lock
- api/database/migrations/2024_06_14_163600_add_pool_department.php
- api/programmatic-types.graphql
- api/schema-directives.graphql
🤖 Related to (but does not close) [9754](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9754)
We can't quite upgrade to Laravel 11 yet but this PR accomplishes a few small things:
- bumps Laratrust to 8.3
- identifies migrations that need to be checked
- unrelated, but running `composer update` rebuilds some graphql files
1. Rebuild app
2. Verify no functional or visible changes
> [Debt] Prep for Laravel 11

- apps/web/src/components/FilterDialog/FilterDialog.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ClaimVerification/ClaimVerificationDialog.tsx
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/AssessmentDetailsDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/ClosingDateSection/ClosingDateDialog.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/GeneralQuestionsSection/GeneralQuestionDialog.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/SkillLevelDialog.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/WorkLocationDialog.tsx
- apps/web/src/pages/Skills/UpdateUserSkillPage.tsx
- packages/ui/src/components/Dialog/Dialog.stories.tsx
- packages/ui/src/components/Dialog/Dialog.test.tsx
- packages/ui/src/components/Dialog/Dialog.tsx
🤖 Resolves #10864 
Fixes an issue with dialogs missing descriptions.
I was wrong about it being as simple as I assumed. The place where we need to apply the prop override was on a different component. Sadly, without making larger changes to how we compose the `Dialog`, for now we just need to pass `hasSubtitle` to `Dialog.Content` when there is a subtitle present.
2. Confirm dialogs with no subtitle have no warnings in console
3. Confirm dialogs with subtitles still have the `aria-describedby` attribute and is properly associated to the subtitle
> [Fix] Dialog descriptions

- api/app/Http/Controllers/AuthController.php
- api/app/Services/OpenIdBearerTokenService.php
🤖 Resolves #10746
This branch updates the backend to recognize common error codes from SIC and then logs it at a DEBUG level.
1. Set up with SIC
2. Log in
3. In an external tool, like Postman, use up the current refresh token
4. Wait until the app tries refresh on its own, or try to manually use the old refresh token again in Postman
1. Set up with SIC
2. Log in
3. Set up a query with Graphiql, like a "me" query
4. Log out
5. Issue query in Graphiql
> whitelist refresh error

- api/tests/Feature/ExperienceTest.php
🤖 Resolves #7483 
Adjusts the assertion query to check for existence rather than exact position (order is not guaranteed).
1. Run the test multiple times `for i in {1..25}; do make artisan CMD="test --filter testSkillRelationshipsWorkWithPivot ./tests/Feature/ExperienceTest.php"; done`
2. Confirm no failures
> [Fix] Stabilize experience test

- apps/web/src/components/Layout/BannerContent.tsx
- apps/web/src/components/Layout/SitewideBanner.tsx
🤖 Resolves #10897 
Updates the site banner to be dynamically imported so it does not need to load when there is no message to be displayed.
Since the banner contains rich text, we need to load tiptap to render the data. Tiptap is one of our larger libraries (307kb) so we should only load it when we need it.
2. Navigate to the homepage
3. Confirm tip tap is not loaded
4. Enable the banner
5. Navigate home
6. Confirm tiptap is loaded and banner renders
> [Perf] Lazy load site banner

- api/app/Models/PoolCandidate.php
- api/tests/Feature/UserTest.php
🤖 Resolves #10902
Resolve the scope and policy conflict by removing the two lines requested in the issue. 
1. Attempt to replicate the issue per reproduction steps
>     Create an applicant who has submitted one application and has at least one other application still in draft
>     Log in as a platform_admin and/or as a Request Responder
>     You should see the applicant in the table for the relevant process
>     You should be able to click the user and see their profile (this currently fails)
>     You should be able to view the user's profile (this currently fails)
2. Ideally no longer see issues
> [Bug] Resolve `view-any-submittedApplication` and authorized scope issue

- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/components/PrintButton/SingleUserProfilePrintButton.tsx
- apps/web/src/components/PrintButton/UserProfilePrintButton.tsx
- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInformation.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/ApplicationPrintButton.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/MoreActions.tsx
- apps/web/src/pages/Users/AdminUserProfilePage/AdminUserProfilePage.tsx
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
- apps/web/src/pages/Users/IndexUserPage/components/utils.tsx
🤖 Resolves #10866 
Fixes the user profile print documents to print the correct information.
Looks as though the profile print document accepted either a `PoolCandidate` or `User` which is not expected. The document should always be the `User`. So when printing the user profile from the application page, we were passing in the snapshot which was missing data and since the document accepted the entire `PoolCandidate` type, it was fine with this.
I noticed a lot of tech debt in these print documents and how we actually go about doing it which could be why we are finding issues with them Is it worth taking a closer look in another ticket or just push the server generated version higher up in the priority list? :thinking:  …
> [Fix] Profile print documents

- apps/web/package.json
- apps/web/vite.config.ts
- pnpm-lock.yaml
🤖 Resolves #10935 
Compresses our assets at build time.
1. Build the project `pnpm run build:fresh`
2. Navigate to the homepage
3. Confirm the assets are not the full size
4. Confirm the header exists `Content-Encoding: gzip`
> [Debt] Compress assets at built time

- api/app/Models/PoolCandidate.php
- api/database/factories/PoolCandidateFactory.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #10919 
Fixes a few gaps in the logic when computing the assessment status.
The main issue was, we were computing it based on available results. So, as soon as a single success occurred, the user passed the step. We have rewrote the logic to do it based off of skills needing to be assessed. There is some frontend stuff that is a little odd but this is how it should work now:
1. On every step, all skills (except for unclaimed optional technical skills) must be assessed before the step is considered complete and the user can move on to the next step
2. On the first step (application screening), all technical skills and education requirement must pass
3. Every other step,
1. If a skill is essential and failed, step automatically fails
2. If the skill is unsure or has not been …
> [Fix] Assessment status logic

- api/app/Models/User.php
🤖 Resolves #10862 
Adds a fallback (English) to the users preferred locale
1. Null out a users `preferred_lang`
2. Attempt to send a notification to them
3. Confirm to null locale error
> [Fix] Add fallback to preferred locale

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInfo.stories.tsx
🤖 Resolves #10963.
This PR adds missing arg `user` to `ApplicationInfo` story.
2. Verify `ApplicationInfo` story has no errors
> [Fix] Adds missing arg `user` to `ApplicationInfo` story

- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #10359.
This PR adds human-readable strings for some API error messages.
1. Verify strings in the code match those in the linked issue.
> [Copy] Adds human-readable strings for some API error messages

- infrastructure/azure-pipelines.yml
🤖 Resolves #10886 
This branch adds the ability to include the dev dependencies when deploying to Azure.  Rather than creating a new pipeline, I added a runtime parameter to the existing pipeline.
The one thing I'm not sure about is how the trigger will work.  I hope the default value will be used but we'll find out when it gets merged.  :sweat_smile:  If it doesn't work we can manually trigger the pipeline when needed until the change gets backed out.
1. Run the Azure Pipeline in dev mode
2. Deploy to an app service
3. SSH in and try a factory in Tinker
> [FIX] Add dev dependencies to Azure build pipeline

- .github/workflows/blocking-issues.yml
This should fix a bug with the blocking-issues action, where the `blocked: dependencies` label is not automatically added or removed from some tickets when it should be.
I think the root of the issue was that the bot was assuming that issues were always written as `#123`. In fact, they are often written as a full url (eg `https://github.com/org/repo/issues/123`). Thus, it was not parsing many of them correctly.
I'm not sure if this _can_ be tested? I believe its set up to only run on main. :/
> Update to new blocking-issues version

- api/app/Models/Pool.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolTest.php
🤖 Resolves #10865
Enable filtering for archived pools to work per intent. Filtered out by default, but returned if wanted
Just kicking the scope off the query as a blanket application and into the fields scope functions.
Permissions was decided to not be a problem for archived pools
1. Navigate to pools table and also ensure you have a pool archived if not seeded
2. Default view returns all but archived pools
3. Play with the filters in the dialog, trying different combinations and check results
4. Ensure you can view archived pools when filtering for them
> [Bug] Filtering for archived pools fix

- apps/web/src/components/PoolCandidatesTable/JobPlacement.stories.tsx
- apps/web/src/components/PoolCandidatesTable/JobPlacementDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/MoreActions.tsx
- apps/web/src/pages/Users/UserInformationPage/UserInformationPage.stories.tsx
- apps/web/src/pages/Users/UserInformationPage/UserInformationPage.tsx
- apps/web/src/pages/Users/UserInformationPage/components/CandidateStatusSection.tsx
- apps/web/src/pages/Users/UserInformationPage/components/UserCandidatesTable/UserCandidatesTable.tsx
- apps/web/src/pages/Users/UserInformationPage/types.ts
🤖 Resolves #10926 
This merges a lot of the queries being run on the "Candidate search" page using fragments to run them all at the page level.
While working on this I noticed two things:
1. We are needed to drill a lot of props (see job placement) and I was wondering if we could work on this a bit :sweat_smile: 
2. We have a few other places that could probably be merged using fragments
3. We are grabbing some data before we actually need it (i.e all skills/pools for the comboboxes in the filter dialog) 
3. Navigate to `/admin/pool-candidates`
4. Inspect the network tab to see reduced query count. Should be 4 (minimum amount I could do)
1. Auth query
2. Site banner
3. Candidates
4. Additional data for filters/dialogs
> [Debt] Merge pool candidates queries

- apps/web/src/components/Table/ResponsiveTable/Table.tsx
🤖 Resolves #10828.
This PR fixes `AddAction` logic for the `Table` component.
The attributes that were styling the `<Control>` were being applied for the `linkProps` case but not for the `component` case.
2. Navigate to `/admin/users/:user-id/edit`
3. Verify Individual roles table and Team based roles table add action is right-aligned
4. Navigate to `/applicant/skills#manage`
5. Verify Skills table add action is right-aligned
6. Verify other tables where `add` prop is used render as they did before
> [Fix] Fixes `AddAction` table logic

- .github/workflows/translations.yml
- api/app/Console/Commands/CheckIntl.php
- api/app/Discoverers/EnumDiscoverer.php
- api/app/Providers/GraphQLServiceProvider.php
- api/app/Traits/HasLocalization.php
- api/storage/app/.gitignore
🤖 Resolves #10900 
Adds a command to verify strings on the api.
Similar to the `pnpm run check-intl:*` scripts, this checks our new api strings. It looks for:
- Missing files for an enum
- Missing strings for each localized enum string
- Strings that match exactly
Run the command with: `make artisan CMD="app:check-intl"` which outputs a list of errors if there are any and stores the output json in `api/storage/app`.
If there are known missing strings (we have some) or known exact matches where the word is known to be the same in English and French, you can add them to the allow lists defined on the command.
If the allow lists get too large then maybe we can consider moving them to a config file? :thinking: 
1. Run `make artisan CMD="app:check-intl"`
2. Confirm success
3. Force errors by …
> [Feature] Add intl command to api

- api/app/Console/Commands/SyncAssessmentStatus.php
🤖 Resolves #10960 
Adds a command that allows us to sync candidates assessment statuses.
1. Seed some candidates
2. Remove their status or change it to be incorrect
3. Run the command `make artisan CMD="app:sync-assessment-status"`
4. Check to ensure their status updated as expected
After deployment run the artisan command to sync new asessessment statuses:
```sh
php artisan app:sync-assessment-status
```
> [Feature] Add assessment status sync command

- infrastructure/bin/post_deployment.sh
🤖 Resolves #10908 
Gives ownership of the `api/app/storage` dir to `www-data:www-data`.
This simply follows the [documentation for laravel deployment](https://laravel.com/docs/11.x/deployment#directory-permissions).
1. Run `post_deployment.sh`
2. Confirm the `/tmp/api/app/storage` folder is owned by `www-data`
> [Fix] Update permissions for storage dir

- apps/web/src/components/PoolCard/PoolCard.tsx
- apps/web/src/components/Profile/components/GovernmentInformation/utils.ts
- apps/web/src/components/QualifiedRecruitmentCard/QualifiedRecruitmentCard.tsx
- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/components/SearchRequestTable/components/helpers.tsx
- apps/web/src/pages/Applications/fragment.ts
- apps/web/src/pages/Auth/CreateAccountPage/CreateAccountPage.tsx
- apps/web/src/pages/Auth/CreateAccountPage/components/GovernmentInfoForm.tsx
- apps/web/src/pages/Classifications/components/ClassificationTable.tsx
- apps/web/src/pages/CreateApplicationPage/CreateApplicationPage.tsx
- apps/web/src/pages/Departments/components/DepartmentTable.tsx
- apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/utils.ts
- apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
- apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineAndRecruitment.tsx
- apps/web/src/pages/SearchRequests/RequestPage/RequestPage.tsx
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/FormFields.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/utils.ts
- apps/web/src/pages/Teams/TeamMembersPage/helpers.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/EditTeamRoleDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/RemoveTeamRoleDialog.tsx
- apps/web/src/pages/Users/UpdateUserPage/components/TeamRoleTable.tsx
- apps/web/src/pages/Users/UpdateUserPage/types.ts
- apps/web/src/types/searchRequest.ts
- apps/web/src/utils/poolUtils.tsx
🤖 Progresses #10799
Chips away at the issue by targeting types
`Team`
`Classification`
`Department`
Make the issue less daunting by electing to chip away at it over time.
There are many types to look at, but it is complicated by nesting of types too. For instance, may need to shake out `Classification` more once type `Pool` has been constrained as the former can be nested in the latter
Thoughts? @esizer 
1. All functionality related to the three types still works
2. Nothing left to change
> [Debt] Constrain types classification, team, and department

- apps/web/src/components/NotificationList/NotificationList.tsx
🤖 Resolves #11024 
Prevents users from requesting more than the max number of pages available.
While our throttle would prevent this from causing too much issue on the server, the user could request a max array size and crash their client. This helps avoid that mistake.
3. Navigate to `http://localhost:8000/en/applicant/notifications?pages=5000`
4. Confirm that the number of queries created is not 5000 but the max pages (should be 1 since no notifications exist)
> [Fix] Set a max page for notifications paginatation

- api/app/Console/Commands/PruneUserGeneratedFiles.php
🤖 Resolves #11016 
Updates the artisan command that prunes user generated files to be files older than 24 hours instead of 12.
Looks like this was already being scheduled, so we just needed to update the time.
> [!NOTE]
> This is kind of hard to test but the following is as good as we can achieve.
1. Place a file in `api/storage/app/user_generated/{iserId}/{filename}/`
2. change its last modified date `touch -d "25 hours ago" filename
3. Update [the schedule time](https://github.com/GCTC-NTGC/gc-digital-talent/blob/6828bd863471c118ed3c9e75e877fad15c0966b8/api/app/Console/Kernel.php#L26-L28) to be just ahead of the current time
4. Wait until just past the time set
5. Run the schedule `make artisan CMD="schedule:run"`
6. Confirm it runs
7. Confirm file removed
> [Debt] Update file prune command

- packages/forms/src/components/Field/Required.tsx
- packages/i18n/src/components/richTextElements.tsx
🤖 Resolves #10918.
This PR updates colours to meet contrast for a11y.
2. Navigate to an admin process page that is set to draft
3. Verify colour contrast of word **draft** is at least WCAG AA
4. Navigate to different instances where a field label required is used
5. Verify colour contrast of asterisk is at least WCAG AA
> [Fix] Updates colours for a11y contrast

- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
- apps/web/src/components/NotificationList/NotificationList.tsx
🤖 Resolves #10916.
This PR removes margin from the `<ul>` element in the `NotificationDialog` component and adds equal margin to the `<p>` element in `NotificationDialog` component.
> [!NOTE]  
> Removing the empty `<ul>` was not possible but at least this solution doesn't render visible margin where it shouldn't be.
thanks @esizer.
2. Navigate to `/applicant/notifications`
3. Verify notifications work on the notifications page and dialog as they did before but without the margin on an empty `<ul>`
> [Fix] Removes notifications margin on empty `ul`

- api/app/Models/PoolCandidate.php
- api/graphql/schema.graphql
- api/tests/Feature/PoolCandidatesPaginatedTest.php
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
🤖 Resolves #10932 
Removes the resolved policy on the pool candidates paginated query to improve performance.
This relies only on the authorized scope for a pool candidate when making a paginated query. Due to this, we had to make the policy more strict by checking to see if a user has any of the required permissions and if they do not, we simply exit early, returning an empty result.
2. Login with different roles
3. Navigate to the pool candidates table
4. Confirm you only see the expected candidates
> [Fix] Remove policy from paginated pool candidates query

- apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.stories.tsx
- apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx
- apps/web/src/components/AssessmentResultsTable/types.ts
- apps/web/src/components/CandidateDialog/ChangeStatusDialog.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/components/PoolStatusTable/PoolStatusTable.tsx
- apps/web/src/components/ProfileDocument/ProfileDocument.tsx
- apps/web/src/components/ProfileDocument/UserSkillList.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/components/SkillRankCard/SkillRankListItem.tsx
- apps/web/src/components/UserProfile/SkillShowcaseSection.tsx
- apps/web/src/pages/Applications/fragment.ts
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/AssessmentDetailsDialog.tsx
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/SkillSummaryTable.tsx
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/utils.ts
- apps/web/src/pages/Skills/ImproveBehaviouralSkillsPage.tsx
- apps/web/src/pages/Skills/ImproveTechnicalSkillsPage.tsx
- apps/web/src/pages/Skills/SkillLibraryPage.tsx
- apps/web/src/pages/Skills/TopBehaviouralSkillsPage.tsx
- apps/web/src/pages/Skills/TopTechnicalSkillsPage.tsx
- apps/web/src/pages/Skills/components/SkillLibraryTable.tsx
- apps/web/src/pages/Skills/components/UpdateSkillShowcase.tsx
- apps/web/src/pages/Skills/operations.ts
- apps/web/src/utils/skillUtils.ts
🤖 Progresses #10799
Chips away at the issue by targeting types
`PoolSkill` 
`UserSkill`
Some of this was laying groundwork for later, like more fragments on the ViewPoolCandidate page to enable thorough shaking later. Some fields will need to be revisited once types `User` and `PoolCandidate` are handled as there is unneeded querying in places when something has to run through the generic type. 
I think I've had my fill of this issue for the time being 😛 
1.  All functionality related to the types still works
2.  Nothing left to change
> [Debt] Constrain types PoolSkill and UserSkill

- apps/web/src/components/AssessmentStepTracker/utils.ts
🤖 Resolves #11035 
Fix the bug so that the number renders correctly. 
Thank you @yonikid15 for finding the bug and suggesting a fix
1. Navigate to Screening and assessment for pools
2. Observe distribution count and compare against candidate list
> [Bugfix] Fix total candidates number for Screening and assessment

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
🤖 Resolves #11044 
Adds published at date to the pools table.
2. Logion as admin `admin@test.com`
3. Navigate to pools table `/admin/pools`
4. Confirm the published column shows up
5. Confirm it sorts as expected
6. Confirm you can show/hide it
> [Feat] Add published date to pools table

- api/lang/fr/armed_forces_status.php
- api/lang/fr/assessment_decision.php
🤖 Resolves #10980, resolves #10917 
Fixes an error where graphql could sometimes return a content type of `text/html`
I initially thought that this had to do with `@self` since the only queries causing an issue were ones that used that directive. However, I started building those queries out adding fields one at a time until I hit the unexpected content type.
Turns out they had a sneaky thing in common, they both use `ArmedForcesStatus` enum (via the user type). After looking into it, I noticed an empty line at the start of the lang file. Removing this fixed the problem. 
i'm not sure how we can catch this in the future since it technically isn't incorrect :face_with_spiral_eyes: 
2. Navigate to any page that queries for armed forces of assessment …
> [Fix] GraphQL response content type

- apps/web/src/components/AssessmentStepTracker/Filters.tsx
🤖 Resolves #11039 
Fixes the mobile layout for the switches on the assessment step tracker.
3. Navigate to a pool's assessment step tracker
4. Reduce window width to a phone size
5. Confirm the filters are all visible without need to side scroll
> [Fix] Mobile layout for step tracker filters

- apps/playwright/playwright.config.ts
- apps/playwright/tests/footer.spec.ts
🤖 Resolves #10654 
Updates the playwright config so we have html report being generated in CI.
We only had the line reporter which never generated files to be uploaded. This ads back in `html` reporter. It also reduced the timeouts to hopefully speed up playwright on failures (waiting 3 mins for a fail forces failed tests to run too long)
> [!NOTE]
> The login-logout tests are flaky in webkit for some reason so you may see some failures for them :cry: 
1. Check [failed run](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/10099080085?pr=11069) and confirm report exists
2. Confirm that it still passes
> [Fix] Playwright report in CI

- api/app/Models/PoolCandidate.php
🤖 Resolves #11032 
Removes the candidate status attribute that only contained commented out code and returned the unaltered attribute.
1. Confirm pool candidate status still returns the expected result
> [Debt] Candidate status attribute

- apps/web/src/components/CandidateDialog/ChangeStatusDialog.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/NotesForm.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/RemoveCandidateDialog/RemoveCandidateDialog.tsx
🤖 Resolves #10987 
Moves enum queries in dialogs do they are only run once the dialog is open.
Seems like a lot of these queries were resolved already so I just cleaned up the remaining two.
2. Login as an admin `admin@test.com`
3. Navigate to a pool candidate
4. Confirm only one query is being made to get page content
5. Confirm the affected dialogs still function
> [Debt] Reduce queries on view pool candidate page

- api/app/Models/PoolCandidate.php
🤖 Resolves #11085 
Adds a truth check on the `end` call on our decisions array before attempting to access an index in case the array is empty.
1. Empty out some deicisions for assessment result
2. Run the sync `make artisan CMD="app:sync-assessment-status"`
3. Confirm no errors
> [Fix] Add check for empty decisions on assessment step sync

- .vscode/launch.json
- Makefile.nix
- api/.env.example
- infrastructure/conf/mock-oauth2-server.json
This PR is just a collection of small local tweaks to help my DX a bit.  I don't know if these affect anyone else - I'm scratching my own itches here.
- Add a debugging profile for Firefox + Storybook
- Remove most uses of `sudo`.  Uses the webserver container instead
- Switch `config:clear` to `optimize:clear`.  See [#10625](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10625)
- Remove `--force` from pnpm.  It doesn't seem to be necessary anymore.
- Remove `--build` from compose up.  It became a lot slower with the custom webserver image.
- Default GCKey MFA to OFF.  I can't remember the last time I wanted to turn MFA on locally.
- Bumped token lifetime from 2 minutes to 10 minutes.  That aligns with prod and gives you a bit more time in Graphiql.
You can try debugging Storybook, …
> Small local env tweaks

- apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx
🤖 Resolves #11080
Filter for teams with a truthy `displayName` and then render them on the create process page. 
1. Ensure you have teams lacking a name first
2. Then ensure they are not rendered in the dropdown
Off main
Off branch
> [Bugfix] Filter for `displayName` in teams dropdown 

- apps/web/src/components/AssessmentStepTracker/AssessmentResultsFilterDialog.tsx
- apps/web/src/components/AssessmentStepTracker/types.ts
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/components/FilterDialog/FilterDialog.tsx
- apps/web/src/pages/Pools/ScreeningAndEvaluationPage/ScreeningAndEvaluationPage.tsx
🤖 Resolves #11043 
Fixes the reset of the step tracker filter count as well as updating operational requirements to be multiselect.
Also, while working on this, I realized we had an issue in the filter dialog. When you modified the count, we were still checking the original count to show the badge so I fixed that as well.
3. Navigate to a step tracker
4. Apply some filters
5. Confirm they function and the count badge in the button is accurate
6. Reset the filters
7. Confirm filters reset as expected and the badge count also resets
> [Fix] Step tracker filter reset

- apps/web/src/pages/Pools/ScreeningAndEvaluationPage/ScreeningAndEvaluationPage.tsx
🤖 Resolves #11135
Fixes and issue where we were running an unnecessary amount of queries on the screening and assessment page severely impacting performance.
We had a query at the top for pool candidates to determine the page size so we could run the correct number of queries in batches. However, this query had no filters applied to it at all, meaning it was running a count of all pool candidates, not just active ones on the current pool.
Because of this, the pager count was based on all candidates and not the ones we were looking for. 
This is applying the same filters to the top level query so it gets the proper page count.
> [!NOTE]
> You can also tweak the batch size for better testing.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/60a37565053b5ca25e5f8a34e76591c000270216/apps/we …
> [Fix] Reduce unnecessary queries on screening and assessment page

- .github/workflows/playwright.yml
🤖 Resolves #11139 
Updates the playwright workflow to use docker compose v2.
1. Confirm all workflows run and succeed
> [Fix] Use docker compose v2 in all workflows

- api/app/Models/PoolCandidate.php
🤖 Resolves #11143
Fixes a recently introduced bug which stopped applicants from seeing their own applications on their dashboard.
Future tickets will be created do add regression testing and fix the root cause. This is a quick fix for now.
The root cause of this has to do with our custom `ProtectedRequestUserChecker`. 
[Laratrust](https://laratrust.santigarcor.me/docs/8.x/usage/roles-and-permissions.html#checking-for-roles-permissions) allows you to pass an array of permissions into `isAbleTo`. If the user has any one of the permissions, it should return true.
However, our custom UserChecker first checks that none of those permissions are 'privileged'. If any of them are, it returns false unless the request came in through the protected endpoint.
So, because we passed an array of …
> [Bugfix] Allow applicants to see their applications listed on dashboard

- api/app/Generators/CsvGenerator.php
🤖 Resolves #11127 
Sets BOM for UTF-8 CSV so non-ascii characters are rendered properly.
1. Start the queue worker `make queue-work`
3. Navigate to the French candidate search table `/fr/admin/pool-candidates`
4. Download candidates
5. Confirm the file renders properly in Excel by default
> [Fix] CSV rendering of characters

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/HomePage/components/About/About.tsx
🤖 Resolves #11156.
This PR updates the spelling of the Office of the Chief Information Officer of Canada in French as well as a related broken URL.
2. Navigate to `/fr/`
3. Verify copy is _le bureau du dirigeant principal de l'information_ instead of _le bureau de la dirigeante principale de l'information_ in heading, paragraph, and hidden text link of _En savoir plus_
4. Verify URL for link _En savoir plus_ navigates to https://www.canada.ca/fr/secretariat-conseil-tresor/organisation/mandat/dirigeant-principal-information.html
> [Fix] Updates French Office of the Chief Information Officer of Canada

- apps/web/.storybook/preview.ts
🤖 Resolves #11129.
This PR removes a Storybook a deprecated variable of `globals` and replaces it with `initialGlobals`.
2. Verify storybook deprecation warning no longer appears when running storybook
> [Debt] Replaces deprecated Storybook `globals`

- apps/web/src/components/PoolCandidatesTable/helpers.tsx
🤖 Resolves #11154 
Updates the priority cell on pool candidates table to render "other" when the weight for it is present.
3. Navigate to any pool candidates table
4. Observe "Other" appearing in the category column when weight is `40`
> [Fix] Adds "other" back to priority cell

- api/app/Models/PoolCandidate.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #11158 
Handles the step being passed before it actually should be.
This was due to education results being an empty array and thus skipped by the for loop block, resolved with a falsy case. 
1. Have a user apply to the pool
2. Navigate to that candidates assessment
3. Assess skills on application screening making sure to not assess the education requirement
4. Observe the step no longer passes while education requirement is still "to assess"
> [Bugfix] Application screening passing without education

- packages/i18n/src/lang/fr.json
🤖 Resolves #11210.
This PR removes an incorrect d apostrophe from a string in the `Combobox` component.
> [!TIP]
> The `Combobox` component itself can be tested using storybook:
> 1. `pnpm intl-compile; pnpm storybook`
> 2. Navigate to http://localhost:6006/?path=/story/forms-src-components-combobox--multi-min-max&globals=locale:fr
2. Navigate to http://localhost:8000/fr/search
3. Select 0, 1, and 2 _compétences_ in the _Sélection des compétences_ section
4. Verify no d apostrophe
> [Copy] Removes d apostrophe from `Combobox`

- apps/web/src/lang/fr.json
🤖 Resolves #11213.
This PR changes the word _votre_ to _notre_ on FAQ so that the help desk is **our** help desk rather than **your** which doesn't make sense.
2. Navigate to http://localhost:8000/fr/login-info
3. Select 0, 1, and 2 _compétences_ in the _Sélection des compétences_ section
4. Verify the first 3 questions in the FAQ reads ".... notre Bureau d'aide..." and no longer "votre Bureau d'aide"
> [Copy] Changes votre to notre on FAQ

- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/components/FormFields.tsx
🤖 Resolves #11211.
This PR adds a missing **s** to the message describing the work location filter in the search form in English.
2. Navigate to http://localhost:8000/en/search
3. Verify plural s exists for work location requirements in **Work location** section
> [Copy] Adds missing s to description of search form work location field

- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx
🤖 Resolves #11212.
This PR changes several  titles on the Search request page to use sentence case in English.
2. Navigate to http://localhost:8000/en/search/request
3. Verify titles all use sentence case
> [Copy] Changes Search request page titles to sentence case

- apps/web/src/lang/fr.json
🤖 Resolves #11160.
This PR updates French version of Office of the Chief Information Officer since the name of the office itself changed in early 2024 when a new Chief Information Officer of Canada was appointed.
2. Navigate to http://localhost:8000/fr/directive-on-digital-talent
3. Observe _de la dirigeante principale_ has been replaced with _du dirigeant principal_
4. `pnpm storybook`
5. Navigate to http://localhost:6006/?path=/story/pages-directive-on-digital-talent-digital-services-contracting-questionnaire--empty&globals=locale:fr
6. Observe _de la dirigeante principale_ has been replaced with _du dirigeant principal_
> [Copy] Updates French version of Office of the Chief Information Officer

- apps/web/src/pages/Users/UserInformationPage/components/UserCandidatesTable/UserCandidatesTable.tsx
Resolves #11237 
`UserInformationPage` or `/admin/users/:userId` was broken due to type erroring, specifically the `UserCandidatesTable` component for users with applications.
A fragment was needed and some unneeded and probably to blame type coercing was removed. Whoops
1. User information page works/loads for users with a non-empty candidates table
Before
After
> [Fix] Add missing fragment for `UserInformationPage` component

- packages/eslint-config-custom/index.js
🤖 Resolves #11277.
This PR adds the `eslint` rules `no-console` and `no-alert` that had been removed as part of the airbnb rules in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11095.
> [!NOTE]  
> Is this still strictly true?
https://github.com/GCTC-NTGC/gc-digital-talent/blob/c17c53b33104412ec1651fd1e76708169a7128a8/documentation/style-guide.md?plain=1#L42-L45
1. Add `console.log(1)` and `alert(1)` somewhere in a .tsx file 
2. `pnpm lint`
3. Observe errors during lint process
> [Fix] Adds `eslint` rules `no-console`, `no-alert`

- apps/playwright/package.json
- apps/web/src/components/ApplicationCard/ApplicationActions.tsx
- apps/web/src/components/AssessmentResultsTable/types.ts
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/AssessmentStepTracker/utils.ts
- apps/web/src/hooks/useRequiredParams.ts
- packages/eslint-config-custom/index.js
- packages/eslint-config-custom/package.json
- packages/eslint-config-custom/react.js
- packages/i18n/src/cli.ts
- packages/storage/src/utils.ts
- pnpm-lock.yaml
🤖 Resolves #11123 
Bumps `typescript-eslint` to the latest version, updating the config and fixing any new errors.
1. Run lint `pnpm run lint --force`
2. Confirm it passes
> [Debt] Bump `typescript-eslint` to v8

- api/app/Models/PoolCandidate.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #11209
Should prevent candidates getting stuck on a screening and assessment step when everything seems to be assessed.
Asset skills that candidates had in their skill library but not attached to an experience were appearing as unclaimed but requiring assessment. This updates the check to only require assessment for a skill if the candidate has an attached experience.
1. Find or create a published process with 2 or more technical asset skills
2. As a candidate: add one of the technical asset skills to your skill library ensuring it does NOT have an attached experience
3. Apply to the process adding all required information and a technical asset skill other than the one in 2
4. As an admin: …
> [Fix] Candidates stuck on assessment step

- api/app/Models/PoolCandidateSearchRequest.php
- api/database/factories/PoolCandidateSearchRequestFactory.php
- api/database/migrations/2024_08_16_103756_add_user_id_to_pool_candidate_search_requests.php
- api/tests/Feature/PoolCandidateSearchRequestTest.php
🤖 Resolves #10976 
- Adds a user_id column to the pool_candidate_search_requests table
- If a user is logged in then set the user_id to the logged in users id, if a guest user is logged in then leave it as null
1. Ensure search requests still works correctly
2. Ensure user id is only set when a user is logged in and not a guest
Run migration for new column.
> [Feature] Add user id to search request table

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #7656.
This PR removes the deprecated `poolCandidates` query from the GraphQL schema.
1. Search codebase for any instances of the `poolCandidates` query
2. Verify there are no instances of the `poolCandidates` query in the codebase
> [Debt] Removes deprecated `poolCandidates` query

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #7652.
This PR removes the deprecated `applicants` query from the GraphQL schema.
1. Search codebase for any instances of the `applicants` query
2. Verify there are no instances of the `applicants` query in the codebase
> [Debt] Removes deprecated `applicants` query

- packages/i18n/src/lang/fr.json
🤖 Resolves #11297.
This PR replaces the typo _Oupse_ with _Oups_ in French.
2. Navigate to http://localhost:8000/fr/applicant/personal-information#about-section
3. Edit the _Renseignements personnels et coordonnées_ section
4. Leave _Prénom_ form field blank and submit form
5. Observe Oups message
6. Verify _Oups_ does not have a trailing e
> [Copy] Replaces Oupse with Oups in French

- apps/web/src/components/EmailVerification/EmailVerification.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Auth/RegistrationPages/GettingStartedPage/GettingStartedPage.tsx
🤖 Resolves #11298.
This PR adds a the ability to translate the heading "Verify your contact email" in French. It also consolidates this string with an existing identical one. Finally, it changes the single consolidated "Verify your contact email" string in French to _Vérifiez votre adresse courriel de contact_ using the _impératif_ verb tense.
2. Create a new account
4. Observe _Vérifiez votre adresse courriel de contact_ button
5. Attempt to verify email
6. Observe _Vérifiez votre adresse courriel de contact_ heading
> [Fix] Adds French translation for Verify your contact email

- .github/ISSUE_TEMPLATE/ 🐛-bug-report.md
- .github/ISSUE_TEMPLATE/⌨-accessibility-issue.md
- .github/ISSUE_TEMPLATE/♻️-debt-refactor.md
- .github/ISSUE_TEMPLATE/⚙️-new-component.md
- .github/ISSUE_TEMPLATE/✏️-documentation.md
- .github/ISSUE_TEMPLATE/✨-feature-request.md
- .github/ISSUE_TEMPLATE/❗-new-notification.md
- .github/ISSUE_TEMPLATE/🔤-copy.md
- .github/ISSUE_TEMPLATE/🛠️-tooling.md
- .github/ISSUE_TEMPLATE/🦔-spike.md
- .github/ISSUE_TEMPLATE/🧪-tests.md
- .github/pull_request_template.md
I get a bit annoyed when I have to delete a bunch of template instructional text and boilerplate when writing up an issue or PR.  I also get annoyed when said text and boilerplate ends up in posted text.  I had the idea of using comments instead.
Let me know what you think of this idea.  If anyone really doesn't like it we can close this without merging.  :grin: 
A few small other changes:
- Removed example blocker item from the tasklist.  Those usually aren't added in the markdown editor anyway.
- Merged designer tag into design section.  We probably don't need a whole h3 section for a user name.
> Move template instructions and boilerplate into comments

- apps/web/src/lang/fr.json
🤖 Resolves #11299.
This PR fixes the message after unlinking an experience with a skill in French.
1. Navigate to http://localhost:8000/en/applicant/skills
2. Add a new skill
3. Navigate to that skill
5. Link an experience
6. Observe toast message _Lien établi avec l’expérience!_
7. Remove this experience
8. Verify toast message is _Lien avec l’expérience supprimé!_
> [Fix] Message after unlinking an experience with a skill

- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.test.tsx
🤖 Resolves #11332.
This PR restores the should add skill test in `ExperienceForm.test.tsx` and removes the out of date TODO comment.
1. `pnpm run test --filter=./apps/web -- ExperienceForm`
2. Verify no warnings or errors
> [Debt] Restores jest test should add skill

- packages/ui/src/components/PreviewList/PreviewList.tsx
The existing PreviewList component has some complex spacing that makes it tricky to use in a design.  This branch removes outer padding and margins from the root component and switches the `ul` and `li` components to `div`s with semantic roles to avoid pulling in existing list CSS.
> [Fix] Simplify spacing around PreviewList

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationInformation/ApplicationInformation.tsx
🤖 Resolves #11345
Resolve the error. 
The nested field was null and the lightest solution seemed to just leverage the snapshot object present
1.  Navigate to `/en/admin/candidates/:id/application`
2. Confirm no errors
> [Bugfix] Fix erroring `ApplicationInformation` component

- .vscode/project-words.txt
- apps/web/src/components/SelfDeclaration/CommunitySelection.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationSelfDeclarationPage/SelfDeclarationForm.test.tsx
🤖 Resolves #11232.
This PR removes an alert that was not relevant to the profile in the Indigenous identity section of the user profile. It also updates some copy to use full doublets instead of abbreviated doublets. Finally, it orders listed communities in the `CommunitySelection` to be ordered alphabetically depending on the locale selected (en or fr).
2. Navigate to http://localhost:3000/en/applicant/personal-information#diversity-equity-inclusion-section
3. Engage the Edit this information button
4. Uncheck all the checkboxes except My community isn't listed
5. Verify the alert warning does not appear, no matter which combination of checkboxes you select
6. Switch to French
7. Engage the Edit this information button
8. Verify the text for Métis reads _Je suis …
> [Fix] Personal information Indigenous identity

- apps/web/src/pages/Pools/PoolAdvertisementPage/components/SkillAccordion.tsx
🤖 Resolves #11363.
This PR adds a conditional for `screeningTime` based on required or optional skill.
2. `pnpm storybook`
3. Navigate to http://localhost:6006/?path=/story/pages-pools-pooladvertisementpage--open
4. Verify no screening time copy in skill accordion for skills that are optional
> [Copy] Adds conditional for `screeningTime` based on required or optional skill

- packages/ui/src/components/PreviewList/PreviewList.stories.tsx
🤖 Resolves #11308  
Stabilize the story.
First I was going to set the seed value but noticed faker was being called to set just a single name while everything else was hardcoded. So I elected to just set the name as well to our dear superadmin's
1. Static name
> [Bugfix] Stabilize `PreviewList` story

- api/app/Http/Middleware/AcceptLanguageMiddleware.php
- api/routes/graphql.php
- api/tests/Unit/AcceptLanguageMiddlewareTest.php
- packages/client/src/components/ClientProvider/ClientProvider.tsx
🤖 Resolves #11336 
Uses the `Accept-Language` header to set the app locale for graphql requests.
REF: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
For the server, we add a middleware that parses the `Accept-Language` header to get the preferred locale and set the app locale to one we support falling back to English.
On the client, we attach the header to all graphql requests basing it on the locale set in `react-intl`.
1. Hard to test but maybe just review the tests and ensure they pass and are comprehensive?
> [Feat] Makes laravel aware of client locale

- api/app/Http/Controllers/CspReportController.php
- api/routes/api.php
- apps/web/vite.config.ts
- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #10614 
This adds a starting point for our content security policy in report mode along with an endpoint to log the report.
For those wondering how to read the policy [MDN has good documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on it. I'll try my best to describe our specific policy:
- `default-src 'self'` This is the default, where self means anything coming from our domain
- `font-src fonts.gstatic.com 'self'` Is allowing google fonts
- `style-src-elem fonts.googleapis.com 'self' 'unsafe-inline' Allows styles from google fonts and inline.
- NOTE: This is unsafe and I describe why later on
- `img-src 'self' data;` This is allowing images where the url starts with `data:` 
- We may be able to get rid of this if we no longer process images through vite
- …
> [Feature] Adds a content security policy in report mode

- packages/auth/src/hooks/useApiRoutes.ts
🤖 Resolves #11387 
Adds a prefix to the login path for non-local dev builds to build it off the root domain.
1. Set `apiHost` to false in `useApiRoutes`
2. Build `pnpm run dev:fresh`
3. Navigate to `/login-info`
4. Confirm the GCKey button links to the proper path
> [Fix] Prefix login path

- apps/web/src/components/NotificationList/NotificationButton.tsx
- apps/web/src/components/NotificationList/NotificationDownload.tsx
- apps/web/src/components/NotificationList/NotificationItem.tsx
- apps/web/src/components/NotificationList/NotificationLink.tsx
🤖 Resolves #10637 
Attempts to focus the next notification in the list on delete.
This stores a reference to the next item in the list on mount. If it exists when the component is unmounting (deleted) it will attempt to move focus to that next item.
> [!TIP]
> I found that the easiest way to seed some notifications is downloading a few files while the worker is running
3. Seed some notifications for the user
4. Using only your keyboard, delete a notification
5. Confirm that the focus is moved to the next item in the list
> [Fix] Delete notification focus management

- api/app/Listeners/SendNewJobPostedNotification.php
🤖 Resolves #11152 , #11153 
I believe the the reason some people got three notifications and some got zero is that the job that queues the notification for each user was timing out and retrying.  This branch sets the timeout to a longer value and disables retries.
I can see the job that Brinda was referring to in the prod `failed_jobs` table with a TimeoutException.  The default timeout for a job is 60 seconds, the wait to retry is 90 seconds, and our workers are set to 3 retries.  This all lines up with the timeline Brinda logged in the issue.
I seeded 23,000 users locally which is about how many we have who received this notification in prod.  I confirmed that the job fails after 60 seconds, having queued about 7400 jobs.  When I upped the timeout, the full set took a little over 3 …
> Adjust tries and timeout

- api/lang/en/assessment_result_justification.php
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialogForm.tsx
- apps/web/src/components/ScreeningDecisions/useLabels.ts
- apps/web/src/lang/fr.json
🤖 Resolves #11391
Require decision notes if the justifications contains the "Other" option, as well as remove a bit of stray punctuation. 
One label was no longer used with the backend enums addition so it was 🪓 
1. Navigate to `/en/admin/candidates/:id/application`
2. Observe required conditional dependent on justifications checklist
> [Bug/copy] Have "Other reason" require decision notes

- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
🤖 Resolves #10638 
This resets the notification dialog scrollY to 0 when you focus the close button.
I'm not really sure why this was not working before and I don't love this solution but it works.
> [!TIP]
> I found that the easiest way to seed some notifications is downloading a few files while the worker is running
3. Seed some notifications for the user (do a lot, enough to get the notification dialog to scroll)
4. Using only your keyboard, tab through the list
5. Confirm that the scroll position is reset when the focus cycles back up to the top (close button)
> [Fix] Reset scroll on close button focus

- apps/web/src/pages/Profile/AccountSettings/AccountSettingsPage.tsx
🤖 Resolves #11394
Updates the account settings breadcrumb to use the correct path.
3. Navigate to acccount settings `/applicant/settings`
4. Confirm the breadcrumb links are correct
> [Fix] Account settings breadcrumb path

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #11397 
Updates the `id` field on the `HasRoleAssignments` interface to `ID` so that the types that implement it meet the spec.
We should probably look into using `UUID` for the types instead of this but  that is going to require updating frontend code.
1. ope graphiql `/graphiql`
2. Confirm the schema appears
3. Confirm no errors related to the interface when fetching the schema
> [Fix] `HasRoleAssignments` interface id field

- api/graphql/schema.graphql
🤖 Resolves #11398 
Eager loads the team relation where we use `teamIdForRoleAssignment` 
1. Open graphiql `/graphiql`
2. Make the listed queries and confirm no lazy load error
```
query {
communities {
teamIdForRoleAssignment
}
pools {
teamIdForRoleAssignment
}
}
```
> Fix] Adds an eager load for team relation

- packages/forms/src/components/Checklist/Checklist.stories.tsx
- packages/forms/src/components/Checklist/Checklist.tsx
🤖 Related to (but does not close) #11285 
This branch adds the ability to add "content below" for checklists.  This is needed for the "area of selection" stuff.
1.Start Storybook or Chromatic.
2. Check the Checklist \ Content Below story
> [Feature] Add "content below" to checklist

- apps/web/src/components/PoolCard/PoolCard.stories.tsx
- apps/web/src/components/PoolCard/PoolCard.tsx
- apps/web/src/lang/fr.json
🤖 Related to (but does not close) #11285
This branch adds a temporary area of selection field to the pool card if the new `areaOfSelection` prop is provided.  This allows the new feature to be added before we're finished rebuilding the pool card.  It builds a combined string from the combination of the two new props.  The combined strings were provided by Nienke.
1. Launch Storybook or Chromatic
2. View Pool Card / With Who Can Apply
> [Feature] Temporary area of selection on pool card

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
🤖 Resolves #11366 
Replaces the data portal card with an Indigenous apprenticeship card on the manager homepage.
2. Navigate to the manager page
3. Confirm the final card under the "What we can do for you" heading has the supplied English and French content
> [Feature] Replace manager homepage data card

- api/app/Generators/ApplicationDocGenerator.php
- api/app/Generators/PoolCandidateUserDocGenerator.php
- api/app/Generators/UserDocGenerator.php
- api/app/GraphQL/Mutations/DownloadApplicationDoc.php
- api/app/GraphQL/Mutations/DownloadApplicationsDoc.php
- api/app/GraphQL/Mutations/DownloadPoolCandidateDoc.php
- api/app/GraphQL/Mutations/DownloadPoolCandidatesDoc.php
- api/app/GraphQL/Mutations/DownloadUserDoc.php
- api/app/GraphQL/Mutations/DownloadUsersDoc.php
🤖 Resolves #11234 
Moves the authorized to view scope to be run in the job rather than mutations for file generation.
1. Start the queue `make queue-work`
3. Download users and candidates from the tables
4. Confirm you still get the expected results
5. Run a mutation with a reduced permission user and IDs for users you do not have access to
6. Confirm those users do not appear in the generated file
> [Debt] Move file generation auth to job

- api/app/Http/Controllers/AuthController.php
- api/app/Providers/AuthServiceProvider.php
- api/database/migrations/2024_09_03_171609_add_last_active_timestamp.php
- api/tests/Feature/AuthServiceProviderTest.php
🤖 Resolves #11426 
Adds a field to track last active and handles updating it through an authorization callback
1. Migration works
2. Open up database tool and check logging in updates the new field
> [Feature] Last active at tracking

- api/app/Enums/PoolAreaOfSelection.php
- api/app/Enums/PoolSelectionLimitation.php
- api/app/GraphQL/Validators/PoolIsCompleteValidator.php
- api/app/Models/Pool.php
- api/database/factories/PoolFactory.php
- api/database/migrations/2024_08_28_145445_create_area_of_selection.php
- api/graphql/schema.graphql
- api/lang/en/pool_area_of_selection.php
- api/lang/en/pool_selection_limitation.php
- api/lang/fr/pool_area_of_selection.php
- api/lang/fr/pool_selection_limitation.php
- api/storage/app/lighthouse-schema.graphql
- apps/playwright/utils/pools.ts
- apps/web/src/components/PoolCard/PoolCard.stories.tsx
- apps/web/src/components/PoolCard/PoolCard.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/processMessages.ts
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/Display.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/utils.ts
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/AreaOfSelectionWell.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/WhoCanApplyText.tsx
- apps/web/src/validators/process/classification.ts
- packages/fake-data/src/fakePools.ts
- packages/forms/src/utils.ts
🤖 Resolves #11285 
This branch adds the "area of selection" feature where pools can be designated as open to the public or just employees, and what category of employees.
1. Build the project, including running the migration.
2. Log in as admin and test the pool editor.
3. As any user test the pool advertisement page.
> [Feat] Area of selection

- .github/workflows/lint.yml
- packages/eslint-config-custom/index.js
- packages/eslint-config-custom/react.js
🤖 Resolves #11465
Workflow no longer fails on warnings, additionally, most warnings changed to be error with the sole exception being deprecation warnings. 
1. Workflows pass
2. Eric's stamp of approval
> [Tooling] Eslint warnings changes

- api/app/Jobs/GcNotifyApiRequest.php
- api/app/Jobs/GenerateUserFile.php
🤖 Resolves #11288 
This branch adds logging to a local file using on-demand logging for asynchronous Laravel jobs.  It doesn't remove any existing logging - just adds more.
>[!NOTE]
This is just one way to trigger job logging.  Feel free to test this a different way.
1. Build the branch with dev tools enabled and release it to the dev app service.
2. Change the ID of the GCNOTIFY_TEMPLATE_TEST_EMAIL env variable to any invalid template ID in the app service.
3. SSH into the app service and launch tinker.
4. `User::factory()->create()->notify(new Test('test', GcNotifyEmailChannel::class))`
> [Feature] Logging to local file for jobs

- api/tests/Feature/UnprotectedApplicationTest.php
- apps/playwright/tests/applicant/application.spec.ts
- apps/playwright/utils/user.ts
🤖 Resolves #11147 
Adds a regression test for permissions of applications on an unprotected endpoint.
We fixed an error where applications could not view their own applications (https://github.com/GCTC-NTGC/gc-digital-talent/issues/11143) and fixed it in https://github.com/GCTC-NTGC/gc-digital-talent/pull/11145. This adds tests to prevent any regression of that fix.
1. Confirm added tests meet AC
2. Confirm tests pass reliably
3. Add the code provided to the pool candidate authorization scope
4. Confirm tests fail
```php
// PoolCandidate::scopeAuthorizedToView
$hasSomePermission = $user->isAbleTo([
'view-own-application',
'view-team-submittedApplication',
'view-any-submittedApplication',
]);
if (! $hasSomePermission) {
$query->where('id', null);
return;
}
```
> [Tests] Regression tests for application permissions 

- api/tests/Feature/ExperienceTest.php
🤖 Resolves #7483 
Updates the assertions for the test to check each fragment to avoid order causing errors.
I don't believe we care about the order or anything so this just checks to see if each skill fragment exists. This should stabilize the test a bit more.
`for i in {1..10}; do make artisan CMD="test --filter=testSkillRelationshipsWorkWithPivot ./tests/Feature/ExperienceTest.php"; done`
1. Run the test multiple times
2. Confirm no failures
> [Test] Update experience skill pivot assertions

- api/app/Builders/PoolBuilder.php
- api/app/Console/Commands/SendNotificationsApplicationDeadlineApproaching.php
- api/app/GraphQL/Queries/CountPoolCandidatesByPool.php
- api/app/Models/Pool.php
- api/app/Models/PoolCandidate.php
- api/app/Models/User.php
- api/app/Rules/SkillNotUsedByActivePool.php
- api/graphql/schema.graphql
- api/tests/Feature/PoolTest.php
🤖 Resolves #11231 
Adds a specific eloquent builder for the pool model and moves scopes there.
I attempted to keep the naming as close as possible to what it is now but had to make some minor changes. Some scopes are prefixed with SQL like keywords, matching built in builder methods. I did this in an attempted to avoid name collisions with relationships (i.e `classifications`).
I made this changes only where needed to keep the scope smaller but maybe we want to use the keyword prefix for other methods in the future (`whereInPublishingGroup` vs `publishingGroups`). I think this makes the intention of the methods more clear.
1. Confirm existing scope tests are passing
2. Interact with places the scopes are used (mainly browse jobs and pools table)
3. Confirm they still function as expected
> [Debt] Add pool eloquent builder class

- api/app/Models/UserSkill.php
- api/app/Traits/Generator/GeneratesUserDoc.php
🤖 Resolves #11488 
Fixes an issue where skill details were not being displayed in profile and application downloads.
Looks like there were two issues,
1. We were trying to get details from the skill but they exist on the user skill
2. Not all skill pivots had the same alias so they would not appear
2. Apply to a process making sure you have one of each experience type with skill details
3. Navigate to the candidate admin page for the application in step 2
4. Download both a profile and application document
5. Confirm the details for skills on all experience types appear
> [Fix] Show skill details in document downloads

- api/app/GraphQL/Mutations/UpdatePoolCandidateStatus.php
- api/graphql/schema.graphql
- api/tests/Feature/PoolCandidateUpdateTest.php
🤖 Resolves #11490 
Updates the manual pool candidate status mutation to also update the appropriate timestamps.
While not explictly stated in the ticket, I added a check to make sure the status was actually changing from its existing value before setting the timestamp which makes sense to me. If this is wrong, let me know and I can change that.
2. Take not of the following time stamps: `placed_at`, `final_decision_at` and `removed_at` from the database for a candidate
3. Use the manual status change dialog to change the status
4. Confirm the appropriate time stamps are updated while the others remain untouched
> [Feature] Update time stamps on manual pool candidate status changes

- api/app/Generators/PoolCandidateCsvGenerator.php
🤖 Resolves #11519 
Updates the order we generate values in to add values that depend on the pool after the initial generation.
1. Start work queue `make queue-work`
3. Navigate to the candidates table `/admin/pool-candidates`
4. Download CSV of the candidates
5. Compare the download to the snapshots, confirming that the following appears in the expected cells:
- General question responses
- Screening question responses
- Skill details
> [Fix] Add missing values to pool candidate csv

- api/app/Enums/SupervisoryStatus.php
- api/graphql/schema.graphql
- api/lang/en/supervisory_status.php
- api/lang/fr/supervisory_status.php
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/JobPosterTemplatesPage.tsx
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/messages.ts
- apps/web/src/pages/ManagerDashboardPage/ManagerDashboardPage.tsx
- packages/ui/src/components/PreviewList/PreviewList.stories.tsx
- packages/ui/src/components/PreviewList/PreviewList.tsx
- packages/ui/src/index.tsx
🤖 Resolves #11430 
Adds the index page for job poster templates.
> [!NOTE]
> To test page sizes, you will need to either seed more than 8 templates or temporarily set page size to less than 3.
2. Navigate to `/job-templates`
3. Confirm the items are shown and filters/sorting/pages function as expected
> [Feature] Job poster templates page

- api/app/Generators/ApplicationDocGenerator.php
- api/lang/en/headings.php
- api/lang/fr/headings.php
🤖 Resolves #11493 
Fixes the application document to have the title "Application snapshot", distinguishing it from profile documents.
2. Navigate to an pool candidate page in the admin view
3. Downoad their application
4. Confirm the title is "Application snapshot"
5. Confirm the title in French is "Capture d'écran de la candidature"
> [Fix] Application document title

- apps/playwright/tests/admin/admin-workflows.spec.ts
- apps/playwright/tests/open-graph.spec.ts
🤖 Resolves #11527 
Stabilizes the admin workflow test by ensuring the user we are expecting appears on the table before assertions.
1. Run the test multiple times
2. Confirm test consistently passes
> [Fix] Stabilize admin workflow test

- api/app/Traits/HydratesSnapshot.php
- api/tests/Feature/SnapshotTest.php
🤖 Resolves #11537 
Fixes an issue where checking if a snapshot field was a localized enum was slightly too permissive.
It appears empty strings were passing the validation setup to assert whether a field was a localized enum or not. I'm not not sure how it was passing the validation since it require that the `value` key was required and if it did not exist, it fell through to an array validation. To me, both of those should have failed on an empty string but they were not.
So, this just adds an additional top level check and if it is either null or a string, it will fail early which seems to fix the issue.
2. Add an experience (community was what was failing but I think it could be any so try them all maybe?)
3. Apply to a process
4. Navigate tot he …
> [Fix] Hydrating snapshots for document download

- apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx
- apps/web/src/components/AssessmentResultsTable/types.ts
- apps/web/src/components/AssessmentResultsTable/utils.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.stories.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx
🤖 Resolves #11531 
Fixes the assessment status table dialog to show education requirement along with evidence.
> [!NOTE]
> This is not the best solution but for urgency, it works.
We were relying on the snapshot to render this but that information recently removed from the snapshot so no longer exists. This instead queries the info from the pool candidate directly and drills the required info down.
3. Apply to a process, taking note of the education requirement option/experience to select
4. Navigate to the admin view of the application
5. Open the education requirement assessment dialog
6. Confirm the option and experience you selected appears in the dialog
> [Fix] Education requirement in assessment dialog

- apps/web/src/components/AssessmentResultsTable/utils.tsx
🤖 Resolves #11544 
Fixes supporting evidence not appearing for essential skill assessments in the screening dialog.
Missed drilling experiences on the different dialog render for essential skills (was only doing it for the non-skill based dialogs.
3. Navigate to a pool candidate in the admin interface
4. Open the screening dialog for a claimed skill
5. Confirm the supporting evidence (experience card w/ details) appears
> [Fix] Supporting evidence for essential skills

- apps/web/src/components/ExperienceFormFields/AdditionalDetails.tsx
- apps/web/src/components/ExperienceSkillFormDialog/ExperienceSkillForm.tsx
- apps/web/src/constants/talentSearchConstants.ts
- apps/web/src/pages/Applications/ApplicationQuestionsPage/components/AnswerInput.tsx
🤖 Resolves #11496 
This branch updates the text areas listed in the issue for the application process to increase the limits when the locale is FR.
The ratio was added as an app-wide constant that individual pages use to calculate the right limit.
> [!Warning] 
These pages break in Vite Watch mode for an as-of-yet unknown reason.  It seems to be related to the use of `process` in the constants file and other pages experience it too.  Use a regular dev or prod build for testing.
1. Rebuild the app
2. Start a new application and proceed through the steps.
3. Note the three places with text areas and switch back and forth between EN and FR.
> [Feat] Change word counts for FR in application

- api/app/Models/PoolCandidate.php
🤖 Resolves #11601 
Adds the missing `ArmedForcesStatus` import in the `PoolCandidate` model.
2. Navigate to the pool candidates page `/admin/pool-candidates`
3. Confirm no error, specifically related to `ArmedForcesStatus`
> [Fix] Add missing import armed forces

- api/app/GraphQL/Mutations/SendUserEmailVerification.php
- api/app/Notifications/VerifyEmail.php
- api/tests/Feature/UserVerifyEmailTest.php
- apps/web/src/components/Profile/components/GovernmentInformation/Display.tsx
🤖 Resolves #11573 
Prevents users from attempting to verify null emails.
This is accomplished with two things:
- We hide the link to verify when the email is null on the front end
- If the user somehow gets there with a null email, we verify it exists and return an error when it does not
1. Login as any user
2. Confirm you have a work email set but not verified
3. Load both the profile and verify email pages
4. Manually set both work email and verified at columns in the DB to null
5. Reload both pages in step 3
6. Confirm no verify link appears on profile
7. Confirm you get error on the verify page
> [Fix] Prevent attempting to verify null emails

- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
- apps/web/src/pages/Skills/SkillPage.tsx
- apps/web/src/pages/Skills/SkillPortfolioPage.tsx
- apps/web/src/pages/Skills/SkillShowcasePage.tsx
- apps/web/src/pages/Skills/UpdateUserSkillPage.tsx
- apps/web/src/pages/Skills/components/SkillPortfolioTable.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/navigationMessages.ts
🤖 Resolves #11588 
Updates the page titles for skill pages.
I also changed the `SkillLibraryPage` component to be `SkillPortfolioPage` to avoid confusion.
2. Login as an application user
3. Navigate to `/applicant/skills`
4. Confirm page title is "Skills portfolio" along with all breadcrumbs
5. Navigate to `/skill`
6. Confirm page title is "Skills library" along with breadcrumbs
> [Copy] Update skills page titles

- api/tests/Feature/Notifications/TriggerNewJobPostedTest.php
🤖 Resolves #11624 
Stabilizes the test for notifying users of published processes.
We recent;y updated it to not send when publishing group was `OTHER`. Since the publishing group for that test was random, it would sometimes create it as other and fail the test.
1. Run the test multiple times
2. Confirm it consistently passes
> [Fix] Stabilize published process notify test 

- api/tests/Feature/PoolCandidateTest.php
🤖 Resolves #11586 
Attempts to stabilize the ordering of candidate priority claims.
I think this was because the user who had unverified priority was not explicitly set to claim it so it was random and when they never claimed priority entitlement, they would naturally be sorted lower causing the error.
1. Confirm the `testOrderByClaimVerification` test passes consistently
> [Fix] Stabilize priority claim order 

- api/database/factories/CommunityFactory.php
🤖 Resolves #11644 
Increases the uniqueness of the community key factory by increasing the words in the result and using the `unique` method.
I'm not sure the `unique` key works when called separately so I also increased the words. We were using 2 which was sometimes causing collisions. 
1. Create a seeder to generates a lot of communities (1000?)
2. Run the seeder
3. Confirm unique constraint is not violated
> [Fix] Increase uniqueness community key factory

- api/lang/en/headings.php
- api/lang/fr/headings.php
- apps/web/src/lang/fr.json
- apps/web/src/messages/profileMessages.ts
- apps/web/src/pages/Auth/RegistrationPages/EmployeeInformationPage/EmployeeInformationPage.test.tsx
- apps/web/src/pages/Auth/RegistrationPages/EmployeeInformationPage/EmployeeInformationPage.tsx
- apps/web/src/pages/Auth/RegistrationPages/GettingStartedPage/GettingStartedPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #11613.
Updates the copy for "Contract type" to "Employment type" and "Contract duration" to "Employment duration" on a few pages. Also removes quotes from form fields in registration pages. All updates are mirrored in french.
1. Confirm the removed quotes in registration forms
2. Confirm "Contract type" updated to "Employment type" on the Employee Information page
3. Confirm "Contract duration" updated to "Employment duration" in a few places:
- Applicant profile
- Admin view applicant profile
- Snapshot
- Profile download
> [Copy] Change contract to employment and remove quotes

- apps/web/src/components/ApplicationCard/ApplicationActions.tsx
- apps/web/src/components/ApplicationCard/ApplicationCard.tsx
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
- apps/web/src/components/EmailVerification/EmailVerification.test.tsx
- apps/web/src/components/EmploymentEquity/EquityOptions.tsx
- apps/web/src/components/NotificationList/NotificationItem.tsx
- apps/web/src/components/NotificationList/RemoveDialog.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/QualifiedRecruitmentCard/QualifiedRecruitmentCard.tsx
- apps/web/src/components/SkillBrowser/SkillBrowserDialog.tsx
- apps/web/src/hooks/useApplicationDownloads.ts
- apps/web/src/hooks/usePoolMutations.ts
- apps/web/src/hooks/useUserDownloads.ts
- apps/web/src/pages/Auth/RegistrationPages/GettingStartedPage/GettingStartedPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/AssetSkillsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/EssentialSkillsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/GeneralQuestionsSection/GeneralQuestionsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/SkillTable.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/UpdatePublishedProcessDialog/UpdatePublishedProcessDialog.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/pages/Pools/ScreeningAndEvaluationPage/ScreeningAndEvaluationPage.tsx
- apps/web/src/pages/Skills/components/SkillPortfolioTable.tsx
- packages/eslint-config-custom/index.js
- packages/forms/src/components/Combobox/Combobox.stories.tsx
- packages/forms/src/components/DateInput/DateInput.stories.tsx
- packages/forms/src/components/RichTextInput/LinkDialog.tsx
🤖 Resolves #11381 
Enables eslint rule and fixes associated errors.
1. Confirm no lint errors
2. Test promises to confirm functionality is unchanged
> [Fix] Remove floating promises

- api/composer.json
- api/composer.lock
🤖 Resolves  #11310 
* Created our own fork https://github.com/GCTC-NTGC/laravel-scout-postgres-tsvector
* Modified it to support laravel 11 with this [commit](https://github.com/GCTC-NTGC/laravel-scout-postgres-tsvector/commit/78458d781c6b737a1ab8144bf59f03815b067e6e) 
* Replaced reference of https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector with our fork. 
1. Run Composer update 
2. Verify you have reference to the new fork 
3. Verify search still works
> [Debt] use our own fork for laravel-scout plugin

- api/app/Models/PoolCandidate.php
🤖 Resolves #11678 
Fixes the return type of the pool candidate category accessor.
2. Navigate to the pool candidates page `/admin/pool-candidates`
3. Confirm no errors and category displays as expected
> [Fix] `PoolCandidate` category accessor return

- .vscode/settings.json
- .vscode/tasks.json
- Makefile
- Makefile.nix
- api/README.md
- docker-compose.yml
- documentation/linux-setup.md
- infrastructure/README.md
- maintenance/README.md
🤖 Resolves #10685 
This branch upgrades documentation and tooling to expect that Docker Compose 2 is installed locally.
The migration guide at https://docs.docker.com/compose/releases/migrate/ lists only a few edge cases where v2 isn't fully compatible with v1.  It seems like no changes are needed for our project.
> [!important]
If you are using a variant of Ubuntu 22.04 locally or in WSL you might need to install Docker Compose v2 with:
`sudo apt-get install docker-compose-v2`
> [Tooling] Upgrade to docker compose 2

- apps/playwright/tests/search-workflows.spec.ts
- apps/web/src/pages/SearchRequests/SearchPage/components/EstimatedCandidates.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
🤖 Resolves #11393 
Use the loading/spinner component to obscure more content if fetching is ongoing 
All obscured below the divider per https://github.com/GCTC-NTGC/gc-digital-talent/issues/11393#issuecomment-2371357549
1. Navigate to search page
2. Observe spinners when search ongoing 
Estimated box
Results below the divider
> [Bug] Talent search page and more spinners!

- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/JobPosterTemplatesPage.tsx
🤖 Resolves #11657
Sorts the classification filter options on the job templates page in ascending order.
1. Update some classifications so the IT classifications returned from this query are out of order
```
query classifications {
classifications {
group
level
}
}
```
2. Visit the job templates page `/en/job-templates` and confirm the classification filter options are sorted
> [Fix] Sort classifications on the job templates page

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/AreaOfSelectionWell.tsx
🤖 Resolves #11708
Makes minor updates to the text in the special area of selection note on job posters to change "opportunity" to "job opportunity" and "possibilité" to "possibilité d'emploi".
Update a draft pool and view the it's job poster to confirm the copy is updated in each of the following cases:
1. Area of selection is employees and neither At-level or Departmental preference
2. Area of selection is employees and At-level only
3. Area of selection is employees and Departmental preference only
4. Area of selection is employees and both At-level and Departmental preference
> [Copy] Update copy in special notes section

- packages/forms/src/components/Combobox/Input.tsx
- packages/forms/src/components/Combobox/Menu.tsx
- packages/forms/src/components/Repeater/Repeater.tsx
🤖 Resolves #11675 
Replaces the deprecated `motion` with `motion.create`.
1. Confirm no instances of just `motion`
2. Confirm animations on affected components still function
> [Debt] Replace `motion` with `motion.create`

- apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/gckeyMessages.ts
- apps/web/src/pages/Auth/RegistrationPages/EmployeeInformationPage/EmployeeInformationPage.tsx
🤖 Resolves #11738.
Replaces "Help Desk" with "support team" and "bureau d'aide" with "équipe de soutien" throughout the site.
1. Confirm the copy change in:
- The FAQ on the Sign in page (multiple locations)
- The FAQ on the Sign up page (multiple locations)
- The invalid work email domain message on the employee information registration page
- The invalid work email domain message in the profile
2. Confirm there are no other uses of "Help Desk" or "bureau d'aide" on the site
> [Copy] Replace help desk with support team

- apps/web/src/pages/Applications/utils.ts
🤖 Resolves #11748 
Fixes a bad null coalescing fix.  In this case, it was actually supposed to be an OR, not a null coalesce.
The way the logic for the "should I show the questions step" was being calculated was "only show if there are general questions".  This specific pool has no general questions but does have screening questions.  The screening questions were skipped, then.
1. Set up a pool with zero general questions but at least one screening question.
2. Submit an application to the pool, verifying that you filled in the screening questions.
3. Try with other pools using different permutations of questions.
> [Fix] Allow filling in screening question

- apps/web/src/components/SkillsInDetail/SkillsInDetail.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #11750 
Adds a more descriptive, hidden, label for skill details labels to improve the experience for AT users.
> [!NOTE]
> @NienkeBr also provided an updated, visible, French label 
3. Navigate to the experience form (add or edit is fine)
4. Add a skill to the form
5. Inspect the details text area
6. Confirm it has the skill name included in the accessible name for the input
> [Fix] Add hidden description skill details label

- apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/Display.tsx
🤖 Resolves #11751
Fix the input error issue. It appears the logic to determine whether it was truly not complete was not quite right
1. Edit a draft pool
2. Ensure location does not incorrectly present in an errored state
Error state
All good
> [Bug] Fix error display of core requirements location

- packages/ui/src/components/Accordion/Accordion.stories.tsx
- packages/ui/src/components/Accordion/Accordion.tsx
🤖 Resolves #11497 
This branch adds candy striping to the base card accordion component.
1. Rebuild and check some pages with card accordions.
2. Check in dark mode as well.
3. Review the Chromatic diffs.
> [Feature] Add striping to card accordions

- packages/date-helpers/package.json
- packages/date-helpers/src/date.test.ts
- packages/date-helpers/src/index.ts
- packages/eslint-config-custom/react.js
- pnpm-lock.yaml
🤖 Resolves #11570 
Replaces the `date-fns-tz` library with `@date-fns/tz`
Hopefully our tests are good for this :sweat_smile: 
1. Confirm no references to `data-fns-tz`
2. Confirm helpers that use timezones still function as expected
> [Debt] Update to use `@date-fns/tz`

- apps/web/src/components/Router.tsx
🤖 Resolves #11717 
Updates the index route at `/browse` show the 404 page.
2. Navigate to `/browse`
3. Confirm not found (404) page
4. Navigate to `/browse/pools`
5. Confirm expected page is rendered
> [Fix] Make `/browse` return 404

- apps/web/src/components/EmploymentEquity/dialogs/DialogFooter.tsx
- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
- apps/web/src/components/Table/ResponsiveTable/RowSelection.tsx
- apps/web/src/components/Table/ResponsiveTable/styles.ts
- apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/SpecialNoteSection/SpecialNoteSection.tsx
- apps/web/src/pages/Users/UserInformationPage/components/AboutSection.tsx
- packages/ui/src/components/Accordion/Accordion.tsx
🤖 Related to PR #11651 
After finding a few bugs from #11651:
- [#11749](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11749)
- [#11748](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11748)
- [#11751](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11751)
I took another look at that PR and identified a few more.  These are all places where boolean OR comparisons were improperly changed to null coalesces.
1. Rebuild the app
2. Check the places touched by this PR (EE dialog, table download, etc)
> [Fix] Roll back lint coalescing bugs

- infrastructure/bin/post_deployment.sh
- infrastructure/webserver.Dockerfile
🤖 Resolves #11764 
Bumps the memory limit of the PHP CLI configuration to 256MB.
1. Rebuild your web server image: `docker compose build`
2. "UP" your docker composer network and shell into the webserver container.
3. `php -i | grep 'memory_limit'`
>[!TIP]
This is deployed to the DEV vertical right now.
1. Deploy to Azure DEV or UAT
2. SSH into the app service
3. `php -i | grep 'memory_limit'`
> [Feature] Bump PHP CLI memory limit

- .github/workflows/phpunit.yml
- api/app/Http/Controllers/AuthController.php
- api/app/Providers/AuthServiceProvider.php
- api/phpunit.xml
- api/tests/Feature/AuthServiceProviderTest.php
- api/tests/Unit/AuthControllerTest.php
🤖 Resolves #11466
Shift user creation to the callback in AuthController.php
Nothing fancy needed to be done
1. Can log in normally with existing user
2. User creation works
3. Sign in values updated or set appropriately
4. Test above with SiC
> [Debt] User creation shifted to `authCallback()`

- api/app/Checkers/ProtectedRequestUserChecker.php
🤖 Resolves #11766 
Updates the protected user checker to log unsafe usage at a DEBUG level since it is a normal event.
1. Rebuild app and log in.
2. Confirm that the "tried to unsafely.." log messages are at the DEBUG level.
> [Feature] Change logging level of protected chcker

- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves #11801.
This PR adds the Department label and value from a pool to the job advertisement.
1. Navigate to a job advertisement at http://localhost:8000/en/browse/pools
2. Navigate to Employment details section
3. Verify Department label and value exists
> [Feature] Adds department to job advertisement

- apps/web/src/utils/educationUtils.tsx
- packages/forms/src/components/RadioGroup/RadioGroup.stories.tsx
- packages/forms/src/components/RadioGroup/RadioGroup.tsx
🤖 Resolves #11227.
This PR adds `margin-right` on the `contentBelow` part of radio group section.
2. Navigate to http://localhost:8000/en/browse/pools
3. Apply for a process
4. On Step 4, switch to French
5. Observe the text spacing is correct within the radio group section
6. `pnpm storybook`
7. Navigate to http://localhost:6006/?path=/story/forms-src-components-radiogroup--content-below&globals=viewport:phone
8. Observe the text spacing is correct within the radio group section
> [Fix] `margin-right` on radio group section

- apps/web/src/lang/fr.json
🤖 Resolves #11815.
This PR updates the subtitle on the Privacy policy page in French.
1. Navigate to http://localhost:8000/fr/privacy-policy
2. Verify subtitle is _Apprenez-en davantage sur la façon dont Talents numériques du GC traite de la vie privée des utilisateurs et utilisatrices._
> [Copy] Updates subtitle on Privacy policy page in French

- apps/web/src/components/Layout/AdminLayout/AdminLayout.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/utils/pageIcons.ts
🤖 Resolves #11798.
This PR adds job templates links to the admin menu and dashboard.
1. Navigate to http://localhost:8000/en/admin
2. Verify a link exists in the menu to Job templates in the Recruitment section
3. Verify a link exists in the dashboard to Job templates in the Managing a recruitment process section
> [Feature] Adds job templates links to admin menu and dashboard

- api/database/seeders/CommunitySeeder.php
🤖 Resolves #11743 
We created Communities programmatically on UAT and Prod (maybe Dev, too) without creating their corresponding teams, meaning that users can't be added to them with roles.
New communities created through the UI will have teams created automatically, but this adds some code to CommunitySeeder to add teams for any communities without them.
1. After running normal local seeding, delete the Community-type teams in the database.
2. Try to add a user to a community. This should fail.
3. Run `php artisan db:seed --class=CommunitySeeder`
4. Repeat step 2, it should work now.
Run `php artisan db:seed --class=CommunitySeeder` to ensure all
> If community doesn't have team, create one in seeder

- packages/auth/src/components/AuthorizationContainer.tsx
- packages/auth/src/components/AuthorizationProvider.tsx
🤖 Resolves #11811
Removes `teamable` from myAuth query.
The main thing to review and test here is that this teamable object isn't used anywhere else.
> Avoid loading teamable in myAuth query

- apps/web/src/pages/DirectivePage/DirectivePage.tsx
🤖 Resolves #11862.
This PR adds the missing `SEO` component with title and subtitle to the Directive page.
2. Navigate to http://localhost:3000/en/directive-on-digital-talent
3. Verify Directive page title and subtitle of page is used for `<head>` `title` and `description`
> [Fix] Adds `SEO` to Directive page

- packages/forms/src/types.ts
🤖 Resolves #11854.
This PR removes the unused `InputFieldError` from the codebase.
2. Verify form fields error work as they did before
3. Verify no instances of `InputFieldError` in the codebase
> [Debt] Removes `InputFieldError`

- apps/web/src/pages/Communities/CommunityLayout.tsx
🤖 Resolves #11822
Fix to allow community admins to view the manage access tab for communities.
This appears to have been a result of #11811 removing teamable from roleAssignments in UserAuthInfo. I resolved this by querying for the users roleAssignments with teamable on the page.
1. Sign in as a community admin (ex. `community@test.com`)
2. Navigate to the view page for a community `en/admin/communities/{communityId}`
3. Confirm you can view and navigate to the "manage access" tab
4. Confirm you can add community recruiters (but not community admins) to the community
> [Fix] Allow community admins to view community access tab

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialogForm.tsx
🤖 Resolves #11927 
Always render decision notes for education assessments. So in this case, render the input for successful decisions as well. 
1. Navigate to assessments for a candidate
2. Observe notes input rendered for education assessments
> [Feature] Render decision notes for successful education assessments

- apps/web/src/components/NavMenu/useMainNavLinks.tsx
🤖 Resolves #11944.
This PR adds `FindTalent` link for applicant role, guest in nav menu.
2. Navigate to http://localhost:8000/
3. Verify **Find talent** appears in nav menu for guest (not signed in user)
4. Sign in as applicant@test.com
5. Verify **Find talent** appears in nav menu for applicant user
6. Sign out
7. Sign in as manager@test.com
8. Verify **Find talent** appears in nav menu for manager user
9. Sign out
10. Sign in as community@test.com
11. Verify **Find talent** does not appear in nav menu for community user
12. Sign out
13. Sign in as admin@test.com
14. Verify **Find talent** does not appear in nav menu for admin user
> [Fix] Adds `FindTalent` link for applicant role, guest in nav menu

- apps/playwright/tests/admin/accessibility.spec.ts
- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.test.tsx
🤖 Resolves #11940  
Moves the assessment step tracker accessibility test to playwright.
1. Confirm test has similar or more coverage
2. Confirm test passes consistently
> [Fix] Move screening and assessment a11y test to playwright

- api/app/Generators/PoolCandidateCsvGenerator.php
- api/app/Generators/UserCsvGenerator.php
🤖 Resolves #11963 
Adds `1` to the CSV row count to account for the header row and not overwrite it.
1. Start the queue `make queue-work`
3. Navigate to the candidates table `/en/admin/pool-candidates`
4. Select one row
5. Download CSV and confirm 2 rows are present (1 for headers, other for candidate)
6. Repeat for users table `/en/admin/users`
> [Fix] Increment CSV row count by 1

- packages/ui/src/components/NavMenu/NavMenuWrapper.tsx
🤖 Resolves #11970.
This PR removes an unnecessary export declaration of `NavMenuProps` which is not used within other modules.
2. Navigate to http://localhost:8000/
3. Verify nav menu still works as before
> [Debt] Removes unnecessary `NavMenuProps` export

- apps/web/src/components/ApplicationCard/ApplicationActions.tsx
- apps/web/src/components/ApplicationCard/ApplicationCard.test.tsx
- apps/web/src/components/ApplicationCard/ApplicationCard.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #11969.
This PR removes the support link from the `ApplicationCard` component.
2. Verify no Get support text on `ApplicationCard` component http://localhost:6006/?path=/story/components-applicationcard--default
> [Feature] Removes `SupportAction` from `ApplicationCard`

- apps/web/src/lang/fr.json
- apps/web/src/pages/AnnouncementsPage/AnnouncementsPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #11934.
This PR updates the announcement form success message to be sentence case and similar to other messages returned on the site.
1. Navigate to http://localhost:8000/en/admin/settings/announcements
2. Submit form and verify success message in toast matches the [approved copy](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11934#issuecomment-2479179304)
> [Copy] Updates announcement form success message

- apps/web/src/lang/fr.json
🤖 Resolves #11987.
This PR changes the French text for the label for showing the submitted date of an application.
1. `pnpm build; pnpm storybook`
2. Navigate to http://localhost:6006/?path=/story/components-applicationcard--default&globals=locale:fr
3. Verify text contains _Candidature soumise :_
> [Copy] Updates French Label for showing the submitted date of an application

- apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
🤖 Resolves #12022
Manager info page should be public.
Try to view /manager as a guest user, and as an applicant user.
> Remove auth requirement from Manager home page

- apps/web/src/pages/Manager/ManagerDashboardPage/ManagerDashboardPage.tsx
- apps/web/src/pages/Manager/components/PoolCandidateSearchRequestPreviewListItem.tsx
🤖 Resolves #11974.
This PR updates the "Your talent requests" heading to be an `h3`. It also adds a prop of `headingAs` to the `PoolCandidateSearchRequestPreviewListItem` component in order to control its heading level.
1. Navigate to http://localhost:3000/en/manager/dashboard
2. Verify the "Your talent requests" heading level of `h3`
> [Fix] Sets accordion trigger for Your talent requests to `h3`

- api/app/Enums/CourseFormat.php
- api/app/Enums/CourseLanguage.php
- api/app/Models/TrainingOpportunity.php
- api/app/Policies/TrainingOpportunityPolicy.php
- api/config/rolepermission.php
- api/database/factories/TrainingOpportunityFactory.php
- api/database/migrations/2024_11_18_190306_create_training_opportunities_table.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/TrainingOpportunityRandomSeeder.php
- api/graphql/schema.graphql
- api/lang/en/course_format.php
- api/lang/en/course_language.php
- api/lang/fr/course_format.php
- api/lang/fr/course_language.php
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/TrainingOpportunityTest.php
🤖 Resolves #11930
Set up the backend for the feature. New table, seeding, queries, mutations, and testing added. 
New permission added, `create-any-trainingOpportunity` for `platform_admin`
1. Migrate and seeding
2. Try queries
3. Try mutations
Sample operations
```
query a {
trainingOpportunity(id: "ID") {
id
title {
en
fr
}
registrationDeadline
trainingStart
courseLanguage {
value
}
applicationUrl {
en
fr
}
}
}
```
```
query b {
trainingOpportunitiesPaginated(where: {hidePassedRegistrationDeadline: true}) {
data {
registrationDeadline
}
paginatorInfo {
count
total
}
}
}
```
```
mutation x {
createTrainingOpportunity(
createTrainingOpportunity: {
title: {en: "en", fr: "fr"}
description: {en: "en", fr: "fr"}
courseFormat: ON_SITE
trainingStart: "2011-05-23"
courseLanguage: FRENCH …
```
> [Feature] Training page backend

- infrastructure/maintenance-container/Dockerfile
🤖 Resolves #12029 
Rolls the base Ubuntu version of the maintenance container back to 22.04.
I don't love that we have to call `apt-get update` twice but I don't think there's any way around it.
1. Rebuild the container `docker compose build maintenance --no-cache`
2. Test out various make commands
3. Test out maintnenace shell `docker compose run --rm maintenance bash`
4. Confirm Playwright CI runs in GH
> Roll back maintenance to 22.04

- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/uiMessages.ts
🤖 Resolves #12016.
This PR updates the open and close nav menu actions to use sentence case instead of title case.
2. Navigate to http://localhost:8000/en/
3. Verify nav menu button action reads Open menu
4. Open nav menu
5. Verify nav menu button action reads Close menu
> [Copy] Updates nav menu actions to use sentence case

- apps/web/src/components/NavMenu/MainNavMenu.tsx
- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
- packages/ui/src/components/NavMenu/NavMenuWrapper.tsx
🤖 Resolves #12020 
Fixes the action dropdown in the notification dialog to be a higher `z-index` than the dialog content.
3. Force a notification
4. Open the notification dialog
5. Open the actions menu for the notification (vertical ellipses)
6. Confirm the menu is visible
> [Fix] Notification dialog z-index

- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields.tsx
- apps/web/src/lang/fr.json
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #12058.
This PR updates some of the experience form label text to use sentence case to be consistent with other labels and the site's copy style.
1. Navigate to http://localhost:8000/en/applicant/career-timeline/create
2. Verify form labels on each experience type use sentence case
4. Verify form labels on each experience type use sentence case
> [Copy] Updates experience form label text to use sentence case

- apps/playwright/tests/admin/auth.spec.ts
- apps/playwright/tests/login-logout.spec.ts
- apps/web/src/components/NavMenu/MainNavMenu.tsx
- apps/web/src/components/NavMenu/useMainNavLinks.tsx
- apps/web/src/pages/Auth/SignedOutPage/SignedOutPage.tsx
- packages/ui/src/components/NavMenu/NavMenu.tsx
🤖 Resolves #11981 
Updates the signout action to be a link to `/logged-out` to preserve keyboard shortcuts and styling.
This can act as an interim fix since it is better than what we currently have. The main issue right now is that the confirmation is still a dialog which comes with the expectation of focus management. Since we are visting a new page we lose focus entirely and it will shift back to the heading of the previous page when cancelling.
A solution could be, instead of using a dialog, we add the confirmation directly on the page like how GitHub does it currently.
2. Sign in as any existing user
3. Tab to the "Your account" dropdown
4. Confirm that arrow keys allow you to navigate all items in the dropdown (including sign out)
5. Confirm sign out …
> [Fix] Signout action in nav menu

- apps/web/src/components/Layout/IAPLayout.tsx
- apps/web/src/components/Layout/MainLayout.tsx
- apps/web/src/components/Layout/RouteErrorBoundary/RouteErrorBoundary.stories.tsx
- apps/web/src/components/Layout/RouteErrorBoundary/RouteErrorBoundary.tsx
- apps/web/src/components/Router.tsx
🤖 Resolves #11998 
Renames the router based error boundary to differentiate it from a component based error boundary
2. Force a router error (404 is an easy one)
3. Confirm you still see the expected error boundary
> [Debt] Differentiate error boundaries

- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/navigationMessages.ts
🤖 Resolves #12078.
This PR updates the navigation menu item to **Browse the skills library** in English.
1. Navigate to http://localhost:8000/en/applicant
2. Sign in as applicant@test.com
3. Verify navigation menu item is **Browse the skills library** in English
> [Copy] Updates navigation menu item name for skill library

- apps/web/.env.example
- apps/web/src/constants/talentSearchConstants.ts
- apps/web/src/vite-env.d.ts
- apps/web/vite.config.ts
- infrastructure/azure-pipelines.yml
🤖 Resolves #11578 
Switches the talentsearch constants to plain constants to let watch mode work properly on those pages.
Vite imports environment variables [a little differently](https://vite.dev/guide/env-and-mode) than Webpack.  However, switching to the import.meta imports that Vite uses [breaks Jest](url).  Working around this would require the import of yet another dependency and mocking the variables for testing.  After [some discussion on Slack](https://talent-cloud.slack.com/archives/CB424V61J/p1732656221379149) I decided to switch these to plain constants.
1. Build in watch mode `pnpm run watch`
2. Log in as `admin@test.com`
3. Visit `http://localhost:3000/en/admin/communities/{communityId}/edit` and confirm it doesn't crash.
Make sure the two constants still work:
1. Visit …
> [Fix] Switch env constants to import.meta

- apps/web/src/pages/TrainingOpportunities/components/TrainingOpportunityForm.tsx
- packages/forms/package.json
- packages/forms/src/components/RichTextInput/ControlledInput.tsx
- packages/forms/src/components/RichTextInput/MenuBar.tsx
- packages/forms/src/components/RichTextInput/RichTextInput.stories.tsx
- packages/forms/src/components/RichTextInput/RichTextInput.tsx
- packages/forms/src/components/RichTextInput/RichTextRenderer.tsx
- packages/forms/src/components/RichTextInput/utils.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/richTextMessages.ts
- pnpm-lock.yaml
🤖 Resolves #12086 
Adds the ability for heading 3 nodes in the rich text editor for the new training opportunities pages.
Adds a prop `allowHeadings?: boolean = false` to the `RichTextInput` component to allow adding only a heading 3 to the content. This feature has only been enabled for the training opportunities description right now.
1. Install new dependecy `pnpm i`
2. Build app `pnpm run dev:fresh`
3. Login as admin `admin@test.com`
4. Navigate to training opportunites (`/admin/training-opportunities`) and create a new one
5. Confirm you can add a heading
6. Submit the new opportunity
7. Navigate to the public side (`/en/it-training-fund/instructor-led-training`)
8. Find the new opportunity created in step 6
9. Click "Learn more and apply"
10. Confirm the heading is render at rank 3
> [Feature] Support headings in rich text editor

- apps/playwright/tests/admin/admin-workflows.spec.ts
- apps/playwright/tests/applicant/profile-workflows.spec.ts
- apps/web/src/components/CandidateDialog/ChangeStatusDialog.tsx
- apps/web/src/components/FilterDialog/FilterDialog.tsx
- apps/web/src/components/Profile/components/LanguageProfile/ConsideredLanguages.tsx
- apps/web/src/components/Profile/components/LanguageProfile/FormFields.tsx
- apps/web/src/components/Profile/components/LanguageProfile/LanguageProfile.tsx
- apps/web/src/components/Profile/components/PersonalInformation/FormFields.tsx
- apps/web/src/components/Profile/components/PersonalInformation/PersonalInformation.tsx
- apps/web/src/components/Profile/components/WorkPreferences/FormFields.tsx
- apps/web/src/components/Profile/components/WorkPreferences/WorkPreferences.tsx
- apps/web/src/components/Profile/types.ts
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialogForm.tsx
- apps/web/src/components/ScreeningDecisions/useOptions.ts
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/MoreActions.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/RemoveCandidateDialog/RemoveCandidateDialog.stories.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/RemoveCandidateDialog/RemoveCandidateDialog.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolFilterDialog.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Skills/CreateSkillPage.tsx
- apps/web/src/pages/Skills/UpdateSkillPage.tsx
- apps/web/src/pages/Skills/operations.ts
- apps/web/src/pages/Users/UpdateUserPage/UpdateUserPage.stories.tsx
- apps/web/src/pages/Users/UpdateUserPage/UpdateUserPage.tsx
- apps/web/src/pages/Users/UpdateUserPage/operations.ts
🤖 Resolves #12068 
Fixes the issue where localized enums used as options in forms were causing issues with form default values.
Some of the localized enums that come from the API were not available until after the form initialized, causing problems with rendering the default values. This moves the queries for the options up 1-2 levels so we can delay form initialization until the options have been returned from the API.
2. Find all forms that use the `localizedEnumToOptions` helper
3. Confirm that their default values are initialized properly
> [Fix] Localized enums being available for form init

- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql
- api/app/GraphQL/Validators/CreateUpdateWorkExperienceValidator.php
- api/app/Http/Resources/WorkExperienceResource.php
- api/app/Models/WorkExperience.php
- api/database/factories/WorkExperienceFactory.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/pages/Profile/ProfilePage/ProfilePage.tsx
🤖 Resolves #12111
A field was missing from the batch added to work experiences. This adds it in alongside touches elsewhere
1. Field added, nothing missing, query/mutation functional
2. Name required for a firm or agency contractor, forbidden otherwise
Sample
```
mutation abc {
createWorkExperience(
userId: "be5e1e96-390d-4fb0-bc2a-3ba5c83727fd"
workExperience: {
employmentCategory: GOVERNMENT_OF_CANADA, 
govEmploymentType: CONTRACTOR, 
department: {connect: "063162f7-a036-4047-91fb-51b5a749f716"}
govContractorRoleSeniority: EXECUTIVE
govContractorType: FIRM_OR_AGENCY
contractorFirmAgencyName: "name"
}
) {
id
}
}
```
> [Feature] Add missing firm/agency name field

- api/app/Models/Classification.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/labels.ts
- apps/web/src/utils/nameUtils.tsx
- apps/web/src/utils/poolUtils.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #12084.
This PR adds CR-04, PM-05, and PM-06 to `scopeAvailableInSearch` so that they are available as options in the classification filter of the search for talent form.
The CR abbreviation was also added as it was not in the codebase before.
1. Navigate to http://localhost:8000/en/search
2. Verify CR-04, PM-05, and PM-06 are options with English job titles in classification filter select
4. Verify CR-04, PM-05, and PM-06 are options with French job titles in classification filter select
> [Feature] Adds CR-04, PM-05, PM-06 to `scopeAvailableInSearch`

- apps/web/src/pages/SkillFamilies/ViewSkillFamilyPage.tsx
- apps/web/src/pages/Skills/ViewSkillPage.tsx
🤖 Resolves #12093
Sort the skills, then pass into the `<Chips />` for rendering, sorts in English and French 
1. Navigate to `en/admin/settings/skill-families`
2. View various skill family pages and observe skill sorting
3. In English and French
> [Bug] Sort skills first then render chips for Skill family view

- apps/web/src/pages/SkillFamilies/components/SkillFamilyTable.tsx
🤖 Resolves #12094
Have the table default sort by the name column in ascending order
1. Navigate to `/en/admin/settings/skill-families`
2. Observe sorting
> [Bug] `SkillFamily` table now default sorted by name

- apps/web/src/pages/TrainingOpportunities/components/TrainingOpportunityForm.tsx
- packages/forms/src/components/Input/Input.tsx
🤖 Resolves #12080 
Adds the URL type to our input component and updates the training opportunity form to use that type for the application URL field.
1. Buld the app `pnpm run dev:fresh`
3. Navigate to the training opportunity form `/admin/training-opportunities/create`
4. Attempt to submit form with a non-URL in the "Application URL" fields
5. Confirm it fails
6. Re-attempt to submit updating the "Application URL" fields to be real URLs
7. Confirm submission is successful
> [Feat] Add URL type to input component

- apps/web/src/lang/fr.json
- apps/web/src/lang/lang.test.ts
🤖 Resolves #12092.
This PR updates French strings to use _guillemets_ instead of quotes. It also adds a test to check for instances of strings in French that contain double quotes.
1. Verify there are no instances of `\"` in any of the fr.json files
2. Add an escaped double quote `\"`, curly opening double quote `“`, and a curly closing double quote `”`  to one of the strings in an fr.json file
3. `cd apps/web`
4. `pnpm test  src/lang/lang.test.ts`
5. Verify test fails with any of an escaped double quote `\"`, curly opening double quote `“`, or a curly closing double quote `”`
> [Copy] Updates French strings to use guillemets instead of quotes

- packages/client/src/exchanges/protectedEndpointExchange.ts
🤖 Resolves #12070.
This PR removes `directive-on-digital-talent` paths from `privilegedPaths` in `protectedEndpointExchange`.
If I understand correctly, this would need to be tested on one of the Azure verticals.
> [Fix] Removes `directive-on-digital-talent` paths from `privilegedPaths` in `protectedEndpointExchange`

- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ClaimVerification/ClaimVerificationDialog.tsx
🤖 Resolves #12171.
This PR updates the message for updating a candidate's claim verification to **Successfully updated claim verification**  so that it uses the correct verb tense.
2. Update a candidate's veteran status claim
3. Observe toast message is **Successfully updated claim verification**
> [Copy] Updates English success message claim verification

- packages/auth/src/hooks/useLogoutChannel.ts
🤖 Resolves #11669 
Updates our use of `BroadcastChannel` to check to make sure it exists in the window (supported by browser) before we use it. 
This was used to broadcast a logout event to all tabs so a user is not logged in on another tab accidentally.
> [!NOTE]
> I don't have access to any of the browsers that do not support this feature but this should work. Hopefully someone has access to one of the browsers that does not support `BroadcastChannel` to confirm the exception is not thrown. Of course Safari has only supported it for 2 years :woman_facepalming: 
2. Login as any user account
3. Open another tab that is logged in
4. Logout of one of the tabs
5. Confirm the other tab still logs out as well
6. Repeat steps 2-4 in one of the unsupported …
> [Fix] Check for `BroadcastChannel` before using it

- api/app/Http/Controllers/SupportController.php
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
- documentation/freshdesk.md
🤖 Resolves #12072.
This PR adds the [userAgent](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgent) string to a new support ticket via to the `SupportForm` component.
> [!NOTE]  
> To test creating a support ticket, you will need to access to and [credentials for Freshdesk](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/freshdesk.md).
1. `make refresh-api; pnpm build`
2. Navigate to http://localhost:8000/en/support
3. Fill out the support form and submit
5. Verify User Agent field in newly created Freshdesk ticket has the appropriate `userAgent` string value
> [Feature]  Adds `userAgent` string to Freshdesk ticket

- api/graphql/schema.graphql
- apps/web/src/pages/Classifications/CreateClassificationPage.tsx
- apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
🤖 Resolves #12170 
Updates the salary inputs on the classification forms to prevent entering negative values.
You can still type in negative values but the browser prevents it and using the spin buttons will prevent going lower than 0.
We did have validation at the database level but this also adds it at the graphql level so we can avoid even getting to the database.
2. Login is admin `admin@test.com`
3. Go to the create classification form `/admin/settings/classifications/create`
4. Attempt to submit a negative value in the salary fields
5. Confirm you get browser validation error
6. Try using spin buttons to go lower than 0
7. Confirm it prevents you from that action
8. Repeat steps 4-7 on the update classificatioon page …
> [Fix] Prevent entering negative values in salary fields

- api/app/GraphQL/Directives/ResolveWithDirective.php
- api/app/Traits/Generator/GeneratesDoc.php
- api/tests/Feature/CandidateFinalDecisionTest.php
- api/tests/Feature/PoolCandidateUpdateTest.php
- api/tests/Unit/FilterableTraitTest.php
- apps/web/src/lang/fr.json
- docker-compose.yml
🤖 Resolves #12191.
This PR fixes a variety of typos in the codebase, only one of which (29c0a3815ff81860319acbd8eba9e7e7975b0f7f) is user-facing (thanks to @NienkeBr for catching the unnecessary _de_ 🏅).
Verify all of the typos that were listed have been corrected appropriately.
> [Copy] Fixes various typos

- apps/web/src/pages/ItTrainingFundPage/ItTrainingFundPage.tsx
🤖 Resolves #11859
Fixes the font weights on the IT training fund page.
We decided not to do any updates to the default values of our heading component.  This branch just fixes one spot I'm aware of.
1. Open design at https://www.figma.com/design/Ml1qNqW5t8V0HDcB5ISQZu/IT-Community-Training-and-Development-Fund?node-id=848-3089&t=DsvHax6qfHYHKWdf-4
2. Rebuild site and go to /en/it-training-fund/instructor-led-training
3. Confirm that the h2 headings have a font weight of 400 as in the Figma design.
> [Fix] Update font weights on IT training fund page

- api/app/GraphQL/Validators/UpdateUserAsAdminInputValidator.php
- api/app/GraphQL/Validators/UpdateUserAsUserInputValidator.php
- api/app/GraphQL/Validators/UpdateUserInputValidator.php
- api/graphql/schema.graphql
- apps/web/src/pages/Users/UpdateUserPage/UpdateUserPage.tsx
- packages/helpers/src/constants/regularExpressions.ts
🤖 Resolves #12027 
Relaxes the domain validation for work email when mutated by admins.  Also adds some new domains.
Confirmed that the domain for Canada Post is hyphenated, not period delimited.
https://www.canadapost-postescanada.ca
Added ccc.ca and canadapost-postescanada.ca and gg.ca as valid work domains.  Found a related bug: 
https://github.com/GCTC-NTGC/gc-digital-talent/issues/12144
I added a separate validator for UpdateUserAsAdmin.  Unfortunately, it's just a copy/paste job which makes it vulnerable to missing future additions to the main validator but I couldn't find a good way to share rules between validators.  If anyone has a bright idea, I'm all ears.
> [!WARNING]
Due to the previously mentioned bug, some domains that end with a valid string may pass validation …
> [Feature] Override work email validation for admins

- api/app/Builders/PoolBuilder.php
- api/app/Enums/NullsOption.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Unit/PoolBuilderTest.php
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolTable.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
🤖 Resolves #11535 
Sorts publish date with nulls last on the pool table.
I just added a new sorting scope to the pool paginated query.  It would be nice to generalize this to something we could use throughout the schema but for now it's a stopgap.
The new scope could be used for any physical column in the table but is not advanced enough to handle relationships like Lighthouse's directive can.  It also only accepts a single column at a time.
1. Rebuild and log in as admin@test.com
2. Navigate to /en/admin/pools
3. Play with sorting options
1. Navigate to /admin/graphiql and add an `authorization` header with a bearer token for admin@test.com
2. Play with sorting options
```graphql
query Pools($where:PoolFilterInput, $orderByColumn: OrderByColumnInput) {
poolsPaginated(first: 100, …
```
> [Fix] Sort nulls last for pool publish date

- apps/web/src/pages/Users/UserInformationPage/components/AboutSection.tsx
🤖 Resolves #12169 
Using overflow-wrap, handle really long email addresses 
1. Navigate to `/admin/users/:id`
2. For a user with long email or edit an email to be long
3. Observe wrapped text
> [Bug] Wrap long emails on User information tab

- api/app/GraphQL/Validators/UpdateUserAsUserInputValidator.php
- packages/helpers/src/constants/regularExpressions.ts
🤖 Resolves #12144.
This PR updates the `workEmailDomainRegex` to be more restrictive. It also updates the backend validator `UpdateUserAsUserInputValidator` to use the same regular expression as `workEmailDomainRegex`.
> [!NOTE]
> The regular expression is not perfect but it is better than what came before. 
> [!TIP]
> For testing regex against strings, https://regex101.com/r/T8IYJU/4.
2. Navigate to http://localhost:8000/en/applicant/personal-information#government-section
3. Edit Government employee information
4. Enter example@gc.ca in Work email address input
5. Save changes
6. Verify success toast Government information updated successfully!
7. Edit Government employee information
8. Enter example@tbs-sct.gc.ca in Work email address input
9. Save changes
10. Verify …
> [Fix] Updates `workEmailDomainRegex`

- .github/workflows/lint.yml
- .github/workflows/phpunit.yml
- .github/workflows/translations.yml
- .gitignore
- api/Dockerfile
- api/composer.json
- api/composer.lock
- api/schema-directives.graphql
- documentation/linux-setup.md
- infrastructure/azure-pipelines-dev.yml
- infrastructure/azure-pipelines.yml
- infrastructure/maintenance-container/Dockerfile
- infrastructure/webserver.Dockerfile
🤖 Resolves #11819 
Bumps the environment to PHP 8.3.
1. Bring your docker compose network down and rebuild the images
- `docker compose build webserver`
- `docker compose build maintenance`
2. Rebuild the `api` project
- deploy app service with php 8.3
- deploy this branch into the app service
- Set phpVersion in IaC to 8.3
> [Debt] Bump environment to PHP 8.3

- apps/web/src/lang/fr.json
- apps/web/src/pages/AdminDashboardPage/AdminDashboard.test.tsx
- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/pages/CommunityDashboardPage/CommunityDashboardPage.tsx
🤖 Resolves #12209.
This PR updates dashboard subtitle copy based on the community or admin dashboard. It also splits the `AdminDashboardPage` component into `AdminDashboardPage` and `CommunityDashboardPage`.
1. Navigate to http://localhost:8000/en/admin
2. Use role switcher (is that the name of it?) to Admin 
3. Verify hero subtitle text matches issue copy
4. Use role switcher (is that the name of it?) to Community
5. Verify hero subtitle text matches issue copy
> [Copy] Updates dashboard based on community or admin

- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
🤖 Resolves #12146 
Get rid of the fallback to personal, allowing the null state to happen again
1. Navigate to `/en/applicant/career-timeline`
2. Test creating experiences has a null select
3. Test editing experiences unchanged
> [Bug] Remove defaulting to personal for experience type select

- api/app/Models/PoolCandidate.php
🤖 Resolves #12173
From what I can see, the only way to trigger thiswas to change the status of a PoolCandidate _to_ DRAFT or DRAFT_EXPIRED. Or to make an assessment on a DRAFT application. Neither of which should have happened... So further investigation into the prod logs might be worth it. Check the history table. Were any PoolCandidates updated when these logs happened? Why?
I like that it logs an error for unmatched decisions. This is a good red flag for us if we add a new status or FinalDecision value and forget to put it here. So for now, I allow the DRAFT statuses to skip the call to log an error, without changing the final values.
1. Log in as an admin
2. Change a submitted PoolCandidate status direction to DRAFT.
3. Check api/storage/logs/laravel.log. You should no longer see …
> [FIX] Add missing case for missing FinalDecision weighting

- apps/web/src/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
🤖 Resolves #11162.
This PR (🤞) fixes unstable storybook snapshots for the `ThemeSwitcher` component in Chromatic.
1. Open Chromatic build for this PR
3. Verify `ThemeSwitcher` story has snapshots for all the modes listed (light, dark)
> [Fix] Stabilizes `ThemeSwitcher` story for Chromatic

- api/app/Notifications/GcNotifyEmailChannel.php
🤖 Resolves #11654.
This PR wraps GC Notify API request in conditionals to avoid making unnescary API rquests if there is no API key or template id.
1. `make queue-work`
2. In a separate terminal instance from `make queue-work`, `make artisan CMD="send-notifications:system notification_test --channelEmail"`
3. Verify all emails fail in terminal and are logged in `api/storage/logs/laravel.log`
> [Debt] Wraps GC Notify API request in conditionals

- api/composer.json
- api/composer.lock
🤖 Resolves #12161.
This PR replaces the `laravel-scout-postgres-tsvector` [fork](https://github.com/GCTC-NTGC/laravel-scout-postgres-tsvector) with the [original](https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector/releases/tag/v9.2.0) library used that has been updated to support Laravel 11.
1. `make refresh-api`
2. Verify [search](http://localhost:8000/en/admin/users) still works
> [Debt] Replaces `laravel-scout-postgres-tsvector` fork with original

- documentation/linux-setup.md
🤖 Resolves 
Adds a missing dependency for running PHP locally.
1. `php -v` runs  and shows 8.3 locally
> Add php-cli to linux instructions

- apps/web/src/lang/fr.json
🤖 Resolves #12280.
This PR fixes the French **Label for the French - Your Impact textarea in the edit pool page** to be consistent with other similar labels.
1. Create a process
2. Switch to French
3. Verify label exists with **Français - Votre impact**
> [Copy] French Label for the French - Your Impact textarea in the edit pool page

- api/app/Traits/Generator/GeneratesUserDoc.php
🤖 Resolves #12250
Employment category will be non-null going forward, but so far all experiences will have it as null, the document needs to handle that case. 
Not sure what the bit about skills is referencing 
1. Have a user with work experiences missing the new fields
2. Test downloads
> [Bug] Profile doc handling null employment category

- api/app/Casts/LocalizedString.php
- api/app/Models/AssessmentStep.php
- api/app/Models/Classification.php
- api/app/Models/Community.php
- api/app/Models/Department.php
- api/app/Models/GeneralQuestion.php
- api/app/Models/GenericJobTitle.php
- api/app/Models/JobPosterTemplate.php
- api/app/Models/Pool.php
- api/app/Models/Role.php
- api/app/Models/ScreeningQuestion.php
- api/app/Models/Skill.php
- api/app/Models/SkillFamily.php
- api/app/Models/Team.php
- api/app/Models/TrainingOpportunity.php
- api/app/Models/WorkStream.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/ApplicantFilterTest.php
- api/tests/Feature/CommunityTest.php
- api/tests/Feature/JobPosterTemplateTest.php
- api/tests/Feature/PoolCandidateTest.php
- api/tests/Feature/PoolTest.php
- api/tests/Feature/SnapshotTest.php
- api/tests/Unit/PoolCandidatePolicyTest.php
- api/tests/Unit/PoolPolicyTest.php
🤖 Resolves #11341 
Updates the grpahql type for `LocalizedString` to return the localized string based on the app locale.
This is adding a custom cast that includes the current localized string along with both languages for the `LocalizedString` type. This does not update the frontend to use this new field.
1. Open graphqil `/graphiql`
2. Query for the models affected
3. Confirm `localized` is added to the return type
4. Switch the locale with the header `Accept-Language en|fr`
5. Confirm the localized message switches between the current locale as expected
6. Confirm setting values still functions
> [Feat] Return locale aware string from `LocalizedString`

- infrastructure/conf/nginx-conf-local/default
- packages/client/src/exchanges/specialErrorExchange.ts
- packages/client/src/index.tsx
- packages/client/src/utils/canAccessProtectedEndpoint.ts
🤖 Resolves #12071 
Adds a utility function to detect if the protected endpoint is reachable (and therefore, on the VPN).  As a bonus, I also updated the special error exchange to better detect being off the VPN.
Unfortunately, we don't have a way to test for the VPN locally, or even on UAT.  I added an Nginx rule (commented out by default) to simulate it.  I hope it's an accurate simulation.  :crossed_fingers: 
1. Since the AC doesn't specify that this function should be used anywhere, plop this testing code with a button on a page somehwere:
```tsx
async function handleClick() {
const result = await canAccessProtectedEndpoint();
console.log(result);
}
```
2. Rebuild and test that your button returns `true`.
3. Enable the firewall simulator and test that the button returns `false`.
1. …
> [Feature] Utility function to detect the VPN

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/JobPosterTemplateTest.php
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/BasicDetails.tsx
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/JobPosterTemplatesPage.tsx
🤖 Resolves #7574 
Updates the `JobPosterTemplate` grpahql type to use the `WorkStream` relationship.
3. Navigate to the index page for job poster templates `/job-templates`
4. Filter by work stream and confirm it functions as expected
5. Open a template
6. Confirm the stream is displayed properly
> [Feat] Add work stream to job poster templates

- apps/playwright/tests/support-page.spec.ts
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
🤖 Resolves #12215 
Uses search params to pre-populate the support form `subject` and `description` fields.
> [!TIP]
> When adding search params, make sure they are encoded for URIs.
2. Navigate to `/support`
3. Confirm the form is empty
4. Add search params for `subject` (only "bug", "feedback" and "question" are supported values) and `description`
5. Confirm the form is populated
6. Confirm unsupported subject fields leads to an empty "I'm looking to..." field
7. Confirm unsafe input to the `description` param is sanitized (i.e `<script>alert('unsafe');</script>` does nothing)
> [Feat] Populate support form from search params

- api/app/Traits/HasLocalization.php
- api/tests/Feature/SnapshotTest.php
🤖 Resolves #11338 
Adds the locale aware label for localized enums in the graphql schema.
1. Navigate to `/graphiql`
2. Query for a localized enum
3. Confirm the new `label.localized` field appears
4. Update the `Accept-Language` header to `fr`
5. Re-run the query in step 2
6. Confirm the field updates to French
```graphql
query {
localizedEnumStrings(enumName: "ArmedForcesStatus") {
label {
en
fr
localized
}
}
}
```
> [Feat] Add locale aware label to localized enums

- apps/web/src/pages/Applications/fragment.ts
🤖 Resolves #12147 
Fixes a missing work email field in the query.
1. Rebuild app
2. Log in as a new user
3. In the create account flow, mark as a government employee and add a work email address
4. Start a new application
> [Fix] Add missing work email field in applicant query

- .github/workflows/playwright.yml
- apps/playwright/playwright.config.ts
🤖 Resolves #12187 
Updates the playwright workflow to utilize shards, reducing the amount of time needed to run.
This makes a few crucial changes:
- Updates the report to blob (required to merge reports)
- Runs all the tests in a single command instead of separate for each browser (makes balancing shards more even)
- Shards the tests into 4 different matrices
- Merges all reports into a single html report at the end instead of having a report per browser
We have went for 44mins to 22mins for total run time which is  a 50% reduction in total runtime. We can probably squeeze some more savings if we [split some larger tests files up](https://github.com/GCTC-NTGC/gc-digital-talent/issues/12357) to better leverage parallelism.
1. Confirm playwright workflow runs as expected
> [Feat] Shard playwright tests in CI

- apps/web/src/pages/Profile/AccountSettings/AccountSettingsPage.tsx
🤖 Resolves #12353 
Adds the `RequireAuth` wrapper to the account settings page for the redirect.
2. Ensure you are not authenticated
3. Navigate to `/applicant/settings`
4. Confirm you are redirected to the login info page
5. Confirm completing the login takes you back to `/applicant/settings`
> [Fix] Account settings auth redirect

- apps/web/src/lang/fr.json
🤖 Resolves #12367.
This PR updates the French Title for the instructor led training page string.
2. Navigate to http://localhost:8000/fr/it-training-fund/instructor-led-training
3. Verify title of the document, heading title level 1, and breacrumb is _Possibilités de formation dirigées par un instructeur ou une instructrice_
> [Copy] Updates French Title for the instructor led training page

- api/app/Models/Classification.php
- api/database/seeders/ClassificationSeeder.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/labels.ts
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #12251.
This PR adds EX-03 and EX-04 to `scopeAvailableInSearch` so that they are available as options in the classification filter of the search for talent form.
The EX salary range URLs (`getClassificationSalaryRangeUrl`) were also added as they were not previously in the codebase.
1. Navigate to http://localhost:8000/en/search
2. Verify EX-03 and EX-04 are options with English job titles in classification filter select
4. Verify EX-03 and EX-04 are options with French job titles in classification filter select
> [Feature] Adds EX-03, EX-04 to `scopeAvailableInSearch`

- infrastructure/bin/post_deployment.sh
🤖 Resolves #12223 
Re-runs the permission after optimize command to hopefully fix them.
I think this lined up with the addition of `php artisan optimize` after changing permissions. I think that deletes and/or rewrites some files that could have modified permissions on them to something undesirable. Since the graphiql error seems to be permissions related, this was my best guess.
> [!NOTE]
> This requires a deployment, or at least running `post_deployment.sh`
1. Run `post_deployment.sh`
2. Confirm `/graphiql` loads correctly with no error
> [Fix] Storage permissions after optimize

- apps/web/src/components/PoolCandidatesTable/tableMessages.ts
- apps/web/src/components/SearchRequestFilters/FilterBlock.tsx
- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/components/SearchRequestTable/SearchRequestTable.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/AdvancedFilters.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/UpdateSearchRequest.tsx
- apps/web/src/pages/SearchRequests/ViewSearchRequestPage/components/ViewSearchRequest.tsx
- apps/web/src/pages/Users/IndexUserPage/components/UserTable.tsx
🤖 Resolves #12335.
This PR makes some copy fixes on the search request page and view request page, primarily issues of title case to sentence case, but also some other fixes to English copy and some French edits. It also removes all the colons from the labels in both languages (`FilterBlock` component) and updates some other text for consistency.
2. Navigate to Search request page
3. Verify English and French copy matches requested changes in linked issue
4. Navigate to View request page
5. Verify English and French copy matches requested changes in linked issue
<details><summary>Search request page</summary>
</details> 
<details><summary>View request page</summary>
</details> 
<details><summary>Other</summary>
</details>
> [Copy] Change to sentence case; remove superfluous colons; update English and French copy

- .github/workflows/phpunit.yml
🤖 Resolves #12389.
This PR fixes a deprecated argument from v.5.0.0 of `codecov-action`.
1. Let GitHub workflows finish
2. Verify no codecov warnings in CI for PHPUnit test workflow
> [Tooling] Fixes `codecov-action` argument

- apps/web/src/pages/Auth/RegistrationPages/GettingStartedPage/GettingStartedPage.tsx
🤖 Resolves #12327 
Fixes and issue where the getting started form was always displaying the success message, even on failure.
Looks as though we were not rejecting the promise when there was an error on the main mutation, only in the mutation that occurs after. This lead to our error exchange showing an error toast and the success toast running regardless if there was an error.
> [!NOTE]
> On success, you may still see error toast but this is going to be expected if you selected "verify email" submit action and do not have a GC Notify API key set. Technically this is correct since account creation is successful and the error is sending the verification email.
2. Login as a new user
3. On the first step of account registration, set contact email to one …
> [Fix] Getting started success toast always triggered

- api/database/migrations/2024_12_24_170232_rename_work_stream_security_name.php
- api/lang/fr/pool_stream.php
🤖 Resolves #12375.
This PR updates the French workstream name for `SECURITY` in the database via a Laravel migration and updates the original pool stream lang file where it came from.
1. `make refresh-api`
2. `pnpm build:fresh`
3. Navigate to http://localhost:8000/fr/search
4. Verify option _Sécurité_ exists in _Volet_ select input
5. Create a process
6. Verify option _Sécurité_ exists in _Flux de travail_ select input
This PR adds a migration that doesn't require any manual deployment action other than making sure the migration is run.
> [Feature] Update French workstream name for `SECURITY`

- apps/web/src/components/ExperienceSkillFormDialog/ExperienceSkillForm.tsx
- apps/web/src/components/SkillsInDetail/SkillsInDetail.tsx
🤖 Resolves #12163.
This PR updates the skill justification word limit in English and French.
2. Apply to a job advertisement
3. Navigate to Step 5 of 7
4. Connect a career timeline experience
5. Verify Describe how you used this skill field has a word limit of 400
6. Switch to French
7. Verify Décrivez comment vous avez utilisé cette compétence field has a word limit of 560
8. Navigate to http://localhost:8000/en/applicant/career-timeline/create
9. Select type Work experience
10. Click Add a skill button
11. Verify Describe how this skill featured in this role field has a word limit of 400
12. Switch to French
7. Verify Décrivez la façon dont cette compétence a été mise en valeur dans ce rôle field has a word limit of 560
> [Feature] Updates skill justification word limit

- apps/web/src/lang/fr.json
- apps/web/src/messages/pageTitles.ts
- apps/web/src/pages/AdminDashboardPage/AdminDashboard.test.tsx
- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/pages/CommunityDashboardPage/CommunityDashboardPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/navigationMessages.ts
🤖 Resolves #11999.
This PR replaces "Job templates library" in resources section on admin dashboard.
2. Navigate to http://localhost:8000/en/admin
3. Verify "Job advertisements templates" link renders in resources section
> [Copy] Replaces "Job templates library" in resources section on admin dashboard

- api/app/Http/Controllers/SupportController.php
- documentation/freshdesk.md
🤖 Resolves #11390.
This PR adds the Application Insights User ID and the Application Insights Session ID cookie value strings to new support tickets via to the `SupportController`.
> [!NOTE]  
> To test creating a support ticket, you will need to access to and [credentials for Freshdesk](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/freshdesk.md). The `APPLICATIONINSIGHTS_CONNECTION_STRING` in apps/web/index.html will also need to be manually set locally.
1. `make refresh-api; pnpm build`
2. Navigate to http://localhost:8000/en/support
3. Fill out the support form and submit
5. Verify Application Insights User ID field and Application Insights Session ID field in a newly created Freshdesk ticket has the appropriate values from `ai_user` and `ai_session` cookies
> [Feature] Adds Application Insights User, Session cookie values to Freshdesk ticket

- packages/forms/src/components/Input/Input.tsx
- packages/forms/src/components/TextArea/TextArea.tsx
- packages/forms/src/utils.ts
🤖 Resolves #11370 
Removes our `sanitizeString` function in favour of adding characters to the firewall allow list.
2. Confirm you can submit forms with text inputs
> [Debt] Remove sanitize string function

- apps/playwright/tests/admin/auth.spec.ts
- apps/playwright/tests/login-logout.spec.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
- apps/web/src/pages/CommunityDashboardPage/CommunityDashboardPage.tsx
- apps/web/src/pages/ProfileAndApplicationsPage/components/ProfileAndApplicationsHeading.tsx
🤖 Resolves #11978 
Adds hidden text to the dashboard titles to improve context for non-visual users.
Hopefully we find a more permanent solution as this is a stop gap since:
- We know we have issues with hidden text in voiceover
- They still lack context for visual users
3. Navigate to the applicant dashboard `/applicant`
4. Confirm the `h1` indicates the page you are on in hidden text
5. Repeat step 4 on the admin dashboard `/admin`
6. Login as the community admin `community@test.com`
7. Repeat step 4 onm the community dashboard `/community`
> [A11y] Add context to dashboard page titles

- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/lang/__snapshots__/lang.test.ts.snap
- apps/web/src/lang/fr.json
- apps/web/src/messages/pageTitles.ts
- apps/web/src/pages/CertificationExamVouchersPage/CertificationExamVouchersPage.tsx
- apps/web/src/pages/ItTrainingFundPage/ItTrainingFundPage.tsx
🤖 Resolves #12360.
This PR adds the certification exam vouchers page and updates some links and copy on the IT training fund page.
2. Navigate to http://localhost:8000/en/it-training-fund/certification-exam-vouchers
3. Verify copy and layout match designs
4. Navigate to http://localhost:8000/en/it-training-fund
5. Verify copy and links match issue
<details><summary>Screenshots (4)</summary>
</details>
> [Feature] Adds certification exam vouchers page

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/SalaryRangeDialog.tsx
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #12292 
Replaces the direct link to a collective agreement with an explanatory dialog about the salary ranges.
1. Rebuild and navigate to /en/browse/pools/{pool-id}
2. Find the salary range row and click the info icon
> [Feat] Salary ranges dialog

- packages/client/src/components/ClientProvider/ClientProvider.test.tsx
- packages/client/src/components/ClientProvider/ClientProvider.tsx
- packages/client/src/constants.ts
🤖 Resolves #12369 
We've been getting lots of reports of premature logouts with our app.  Our best explanation is that the Surface tablets appear to have over 5 seconds of clock skew which means that the client is attempting to use an expired token.  Also, URQL is not configured to recognize the token_validation error and so it does not attempt to refresh when it gets the error.  This PR attempts to fix both problems.
1. Rebuild and log in to app
2. Add "throw new Exception('Failed to get introspection');" to the top of `verifyJwtWithIntrospection` in api/app/Services/OpenIdBearerTokenService.php and to simulate an expired token.
3. Make an API call in your browser
1. Manually change allowableClockSkewSeconds in packages/client/src/constants.ts to something very large, like 8 * 60.
2. …
> [Fix] Add token validation to didAuthError and allowable clock skew to willAuthError

- api/app/Models/Classification.php
- api/app/Models/User.php
- apps/playwright/tests/search-workflows.spec.ts
- apps/web/src/components/ExperienceCard/WorkContent/GovContent.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/GovFields.tsx
- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
- apps/web/src/components/PoolCard/PoolCard.tsx
- apps/web/src/components/Profile/components/GovernmentInformation/Display.tsx
- apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx
- apps/web/src/components/Profile/components/GovernmentInformation/utils.ts
- apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx
- apps/web/src/components/SearchRequestTable/components/SearchRequestFilterDialog.tsx
- apps/web/src/components/SearchRequestTable/components/helpers.tsx
- apps/web/src/components/UserProfile/ProfileSections/GovernmentInformationSection.tsx
- apps/web/src/pages/Auth/RegistrationPages/EmployeeInformationPage/EmployeeInformationPage.tsx
- apps/web/src/pages/Classifications/CreateClassificationPage.tsx
- apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
- apps/web/src/pages/Classifications/helpers.tsx
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatesPage/JobPosterTemplatesPage.tsx
- apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/EducationRequirementsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/utils.ts
- apps/web/src/pages/Pools/IndexPoolPage/components/PoolFilterDialog.tsx
- apps/web/src/pages/Pools/IndexPoolPage/components/helpers.tsx
- apps/web/src/pages/SearchRequests/SearchPage/utils.ts
- apps/web/src/utils/nameUtils.tsx
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #12248.
This PR increases classification level options and accounts for the absence or presence of a leading zero in the levels.
1. `make refresh-api; make seed-fresh; pnpm i; pnpm build:fresh`
2. Navigate to http://localhost:8000/en/admin/settings/classifications/create
3. Create a classification item with a level of **19**
4. Navigate throughout the site wherever classification levels are rendered or used in aria-labels to verify absence or presence of a leading zero in the levels depending on if the level is single digit or two digits.
> [Feature] Increases classification level options

- .github/workflows/blocking-issues.yml
- .github/workflows/chromatic.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/jest.yml
- .github/workflows/lighthouse-php.yml
- .github/workflows/lint.yml
- .github/workflows/phpunit.yml
- .github/workflows/playwright.yml
- .github/workflows/translations.yml
- documentation/linux-setup.md
- infrastructure/azure-pipelines.yml
- infrastructure/bin/set_php_versions.sh
- infrastructure/maintenance-container/Dockerfile
🤖 Resolves #10684.
This PR updates Ubuntu to 24.04 in the maintenance container, GitHub workflows, and the Azure pipelines.
1. Bring docker compose network down and rebuild the images `docker compose down`
2. Build the images `docker compose up --detach --build`
3. Verify app still runs exactly as before
1. Deploy this branch into the app service
2. Verify app still runs exactly as before
> [Tooling] Updates Ubuntu to 24.04

- api/app/Console/Commands/SendNotificationsAdHocEmail.php
- api/app/Console/Commands/SendNotificationsEmail.php
- api/app/Notifications/AdHocEmail.php
🤖 Resolves #11542 
Adds an Artisan command and Laravel notification for sending ad hoc emails with just the first name and last name.
The command will select users to notify by one of three criteria:
- specific email addresses
- specific notification families
- all users
1. Update your api/.env file with the "team" api key
2. Rerun ./artisan optimize:clear
3. Start a queue worker
4. Update one user to have your GCNotify registered email address
5. Test various forms of the Artisan command
`./artisan send-notifications:ad-hoc-email cdaa82f1-7f76-4d9e-a82e-328c41a6ab62 0831e036-8dfb-4f5e-8b31-867b2c526d77 --emailAddress=email1@example.org --emailAddress=email2@example.org`
`./artisan send-notifications:ad-hoc-email cdaa82f1-7f76-4d9e-a82e-328c41a6ab62 0831e036-8dfb-4f5e-8b31-867b2c526d77 …
> [Feature] Ad hoc email command

- apps/playwright/fixtures/ApplicationPage.ts
- apps/playwright/fixtures/ExperiencePage.ts
- apps/web/src/components/ExperienceFormFields/AwardFields.tsx
- apps/web/src/components/ExperienceFormFields/CommunityFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/ExperienceDetails.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/ExternalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/WorkFields.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/ApplicationCareerTimelineAddPage.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelineAddPage/components/AddExperienceForm.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelineEditPage/ApplicationCareerTimelineEditPage.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelineEditPage/components/ExperienceEditForm.tsx
- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceForm.stories.tsx
- apps/web/src/pages/Profile/ExperienceFormPage/ExperienceFormPage.tsx
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #12323
Populate with suggestions, using `<datalist />`, orgs for all experiences except personal by pulling names from all experiences except personal.
There are two contexts for experiences, through timeline and within an application. A util function for reuse was added as well due to more than one context
1. Login and have experiences
2. Create/edit experiences and observe whether suggestions were populated for org name
> [Feature] Autocomplete experience orgs

- api/app/Generators/ApplicationDocGenerator.php
- api/app/Models/WorkExperience.php
- api/app/Traits/Generator/GeneratesUserDoc.php
- api/lang/en/common.php
- api/lang/fr/common.php
- apps/web/src/components/ExperienceFormFields/WorkFields/GovFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/WorkFields.tsx
- apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx
- apps/web/src/lang/fr.json
- apps/web/src/utils/experienceUtils.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/uiMessages.ts
🤖 Resolves #12434 
- Fixes work experience fields resetting when a skill is added
- Fixes null message on classification select
2. Login as `applicant@test.com` (or whoever)
3. Go to career timeline and create an experience
4. Select work experience type and fill in some sub fields
5. Scroll down and add a skill
6. Scroll back up and confirm no sub fields have been reset
> [Bug] work experience form reset fields bug

- apps/web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
- apps/web/src/pages/CommunityDashboardPage/CommunityDashboardPage.tsx
🤖 Resolves #12110.
This PR updates `margin-bottom` on last item in array for dashboard lists so that they have equal vertical spacing.
2. Navigate to http://localhost:3000/en/admin
3. Verify dashboard lists have equal vertical spacing
4. Navigate to http://localhost:3000/en/community
5. Verify dashboard lists have equal vertical spacing
> [Fix] Dashboard lists have equal vertical spacing

- apps/web/src/components/PoolCandidatesTable/PoolCandidateFilterDialog.tsx
🤖 Resolves #12462 
Fixes the stream filter to use the new work streams instead of pool stream.
3. Navigate to the pool candidates table `/admin/pool-candidates`
4. Confirm stream filter fucntions as expected with no errors
> [Fix] Stream filter in pool candidates dialog

- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #12100 
Adds an announcement for ATs that the total number of items in the table has changed.
2. Open your favourte screen reader
3. Navigate to a client side table e.g `/skills`
4. Change some filters
5. Observe the announcement of row count
6. Login as admin `admin@test.com`
7. Navigate to a server side table `/admin/users`
8. Repeat steps 4 + 5
> [a11y] Announce table row count to ATs

- api/app/Generators/ApplicationDocGenerator.php
- api/app/Models/Experience.php
🤖 Resolves #12459
Render names correctly, in this case department name was missing
Reused the logic of massaging the relational fields, condensed into one place to avoid redundancy 
1. Test application download for various experiences
> [Bug] Skills section of application download, experience names fixed

- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #12436.
This PR sets an exception for /robots.txt to avoid CSP violations from requests for /robots.txt.
1. `make down; make up;` 
2. Navigate to http://localhost:8000/robots.txt
3. Verify nothing in console related to CSP
> [Fix] Avoids CSP violations for robots.txt

- apps/web/src/pages/CreateApplicationPage/CreateApplicationPage.tsx
🤖 Resolves #12314
As the title states, fix that annoyance. 
Followed the suggestion to handle the toast spam rather than try and diagnose why duplicate application creation was happening
1. Navigate to some process `/browse/pools/:id`
2. Apply
3. Apply again by visiting directly `/browse/pools/:id/create-application`
4. Observe toasts
> [Bug] Resolve toast spam in create application path when an application already exists

- apps/web/src/lang/fr.json
- apps/web/src/pages/Skills/components/SkillTable.tsx
- apps/web/src/pages/Skills/components/tableHelpers.tsx
🤖 Resolves #12155 
Updates skill table, removing spoiler, to show full description.
2. Navigate to skills page `/skills`
3. Confirm you see the full description with no "read more" links
> [Style] Show full description in skill table

- packages/forms/src/components/TextArea/TextArea.stories.tsx
🤖 Resolves #12474.
This PR removes `TextArea` custom arg `maxWidth` from story.
2. Verify `TextArea` stories work as before
> [Debt] Removes `TextArea` custom arg `maxWidth` from story

- packages/ui/src/components/ToggleSection/ToggleSection.stories.tsx
- packages/ui/src/components/ToggleSection/ToggleSection.tsx
🤖 Resolves #11935.
This PR fixes the `ToggleSection.Header` component Heading and Toggle text so it does not overlap and is on a new row for smaller screens.
2. Navigate to http://localhost:8000/en/admin/settings/announcements
3. Edit the form
4. Verify text Sitewide announcement does not overlap with Cancel editing and Cancel editing is on a new row
> [Fix] `ToggleSection.Header` component Heading and Toggle style

- apps/web/package.json
- apps/web/src/pages/SearchRequests/RequestConfirmationPage/RequestConfirmationPage.tsx
- pnpm-lock.yaml
🤖 Resolves #12387.
This PR upgrades `react-to-print` to version 3.
1. `pnpm i; pnpm build:fresh`
2. Navigate to http://localhost:8000/en/search
3. Submit a talent request
4. Click Print this information button
5. Print dialog with content from page should appear in browser
https://github.com/user-attachments/assets/98fa9f7e-a5f0-4f74-af1b-b0c074424e98
> [Debt] Upgrades `react-to-print` to version 3

- api/app/Enums/DevelopmentProgramParticipationStatus.php
- api/app/GraphQL/Validators/CreateCommunityInterestInputValidator.php
- api/app/GraphQL/Validators/CreateDevelopmentProgramInterestInputValidator.php
- api/app/GraphQL/Validators/UpdateCommunityInterestInputValidator.php
- api/app/GraphQL/Validators/UpdateDevelopmentProgramInterestInputValidator.php
- api/app/Models/Community.php
- api/app/Models/CommunityInterest.php
- api/app/Models/DevelopmentProgram.php
- api/app/Models/DevelopmentProgramInterest.php
- api/database/factories/CommunityInterestFactory.php
- api/database/factories/DevelopmentProgramFactory.php
- api/database/factories/DevelopmentProgramInterestFactory.php
- api/database/factories/UserFactory.php
- api/database/helpers/ApiErrorEnums.php
- api/database/helpers/FactoryHelpers.php
- api/database/migrations/2025_01_06_203632_create_development_programs_table.php
- api/database/migrations/2025_01_07_200651_create_development_program_interests_table.php
- api/database/seeders/CiSeeder.php
- api/database/seeders/CommunityRandomSeeder.php
- api/database/seeders/CommunityTestSeeder.php
- api/database/seeders/DatabaseSeeder.php
- api/database/seeders/UserRandomSeeder.php
- api/database/seeders/UserTestSeeder.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/CommunityInterestTest.php
- api/tests/Feature/DevelopmentProgramInterestTest.php
🤖 Resolves #12099 
Adds backend modelling for development programs.
1. Rebuild app (with migrations, etc)
2. Test using Graphiql - there is no UI yet
Some queries:
<details><summary>Query dev programs</summary>
```graphql
query Communities {
communities {
id
developmentPrograms {
id
name {en fr}
descriptionForProfile {en fr}  
descriptionForNominations {en fr}  		
eligibleClassifications {group level}
}
}
}
```
</details>
<details><summary>Query my interest in dev programs</summary>
```graphql
query Me {
me {
employeeProfile {
communityInterests {
id
community {
name {
en
}
}
interestInDevelopmentPrograms {
id
developmentProgram {
name {
en
}
}
participationStatus
completionDate
}
}
}
}
}
```
</details>
<details><summary>CreateCommunityInterest</summary>
```graphql
mutation …
```
> [Feature] Development programs backend

- api/app/Models/PoolCandidate.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #12421
Updates the way the assessmentStatus field for PoolCandidates is calculated to allow a slightly more detailed status to be shown to candidates.
Prevents assessmentSteps showing up in the assessmentStatus.assessmentStepStatuses field on PoolCandidates until they have at least one assessmentResult to make it possible for candidates to tell if the step has started to be assessed or not.
1. Confirm tests still pass
2. Create and submit an application and update it's assessment progress confirming it's possible to tell if a step has begun assessment by whether it shows in the assessmentStepStatuses field.
Useful query:
```
query PoolCandidate {
poolCandidate(id: userId) {
assessmentStatus {
assessmentStepStatuses {
step
decision
}
overallAssessmentStatus
currentStep
}
}
}
``` …
> [Feature] Improve candidate assessmentStatus data

- apps/web/src/components/EducationRequirements/EducationRequirements.tsx
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/pages/Applications/ApplicationEducationPage/ApplicationEducationPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/EducationRequirementsSection.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- apps/web/src/types/classificationGroup.ts
- apps/web/src/utils/educationUtils.tsx
🤖 Resolves #12495.
This PR fixes `AS` classification group so that it inherits values from the `PM` classification group. It also adds some type safety with the `ClassificationGroup` type (thanks @petertgiles).
2. Create a process with classification set to `AS-03`
3. Navigate to the published process and apply
4. Verify Minimum experience or equivalent education options are the same as on the edit process page (Advertisement information)
> [Fix] `AS` classification group education requirements

- api/app/Policies/PoolCandidatePolicy.php
- api/graphql/schema.graphql
- api/tests/Feature/PoolCandidateUpdateTest.php
- api/tests/Unit/PoolCandidatePolicyTest.php
🤖 Resolves #12480
Adds a policy method that calls other policy methods in order to allow the mutation to adapt to different input statuses. Being permissive depending on the status passed in, allowing roles like process operator to do more. 
1. Test the mutation
Mutation 
```
mutation a {
updatePoolCandidateStatus(
id: "id123"
poolCandidate: {expiryDate: null, status: NEW_APPLICATION}
) {
id
status {
value
}
}
}
```
> [Debt-ture] `updatePoolCandidateStatus` policy enhancment 

- api/app/Models/Classification.php
- api/database/seeders/ClassificationSeeder.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/labels.ts
🤖 Resolves #12498.
This PR adds AS-03 and AS-05 to `scopeAvailableInSearch` so that they are available as options in the classification filter of the search for talent form.
> [!NOTE]
> AS-01 to AS-05 min and max salaries were update to current levels in `ClassificationSeeder`.
1. Navigate to http://localhost:8000/en/search
2. Verify AS-03 and AS-05 are options with English job titles in classification filter select
4. Verify AS-03 and AS-05 are options with French job titles in classification filter select
> [Feature] Adds AS-03, AS-05 to `scopeAvailableInSearch`

- api/app/Enums/CandidateRemovalReason.php
- api/lang/en/candidate_removal_reason.php
- api/lang/fr/candidate_removal_reason.php
- api/storage/app/lighthouse-schema.graphql
- packages/i18n/src/utils/enum.ts
🤖 Resolves #12500.
This PR adds `INELIGIBLE` element to the `CandidateRemovalReason` enum.
2. Login as a user with `platform_admin` role
3. Navigate to a pool candidate `/admin/candidates/:pool-candidate-id/application` without a status of `REMOVED`
4. In the More actions section, click on status link to open dialog
5. Verify **Candidate is ineligible** is the third radio option for **Reason**
6. Submit form
7. Verify no errors
> [Feature] Adds `INELIGIBLE` element to `CandidateRemovalReason` enum

- apps/playwright/tests/admin/pool-candidate-actions.spec.ts
The verification and notes test is failing a bunch, sometimes, and it is driving me bananas 
1. Runs well locally, and in CI
> [Fix] Try stabilizing `pool-candidates-actions.spec.ts`

- apps/web/src/pages/Classifications/CreateClassificationPage.tsx
- apps/web/src/pages/Classifications/UpdateClassificationPage.tsx
- apps/web/src/pages/Communities/CreateCommunityPage/components/CreateCommunityForm.tsx
- apps/web/src/pages/Communities/UpdateCommunityPage/UpdateCommunityPage.tsx
- apps/web/src/pages/Departments/CreateDepartmentPage.tsx
- apps/web/src/pages/Departments/UpdateDepartmentPage.tsx
- apps/web/src/pages/SkillFamilies/CreateSkillFamilyPage.tsx
- apps/web/src/pages/SkillFamilies/UpdateSkillFamilyPage.tsx
- apps/web/src/pages/Skills/CreateSkillPage.tsx
- apps/web/src/pages/Skills/UpdateSkillPage.tsx
🤖 Resolves #12159 
This adds the `autocomplete="off"` attribute to name fields for our resources so that they no longer suggest personal names.
3. Navigate to the create/update page for each resource (system setting)
4. Confirm personal name suggestions do not appear and it has autocomplete turn off on the name fields
> [Fix] Turn off autocomplete for resource name fields

- api/app/Models/EmployeeProfile.php
🤖 Resolves #12537
Fix the typos
Added `id` to match return type
1. Run query without issue
```
query me {
me {
id
employeeProfile {
userPublicProfile {
id
}
}
}
}
```
> [Bug] Fix typos in select for `EmployeeProfile::userPublicProfile()`

- api/README.md
This PR updates some documentation that had a typo in the name of a field. It also adds some markdown to two names of fields.
> [Docs] Fixes name of field; updates markdown

- .github/pull_request_template.md
This PR updates the instructions for adding a [deployment label](https://github.com/GCTC-NTGC/gc-digital-talent/labels/deployment) when deployment steps are needed.
> [Docs] Updates deployment steps instructions

- api/app/Models/RoleAssignment.php
- api/app/Models/User.php
- api/database/migrations/2025_01_20_164045_add_timestamps_role_user_table.php
🤖 Resolves #12491 
Adds timestamps and activity log to role assignments.
This is a little more involved because of traits coming from Laratrust.
- Had to extend the `roles` relationship that comes from the trait
- Added custom logs on the `roleAdded` and `roleRemoved` model events since the default made it difficult to determine what actually happened.
The logged properties are the ID of role and team (if present) removed or added. Hopefully this makes sense, if it does not, this is not too difficult to change.
1. Refresh API `make refresh-api`
3. Navigate to edit a user `/admin/users/{userId}/edit`
4. Add both a normal and team based role
5. Confirm the new records in the database for `role_user` table have the appropriate timestamps
6. Remove both …
> [Feat] Log role assignment activity

- api/app/Console/Commands/SyncAssessmentStatus.php
- api/app/Models/PoolCandidate.php
- api/database/seeders/AssessmentResultTestSeeder.php
- api/database/seeders/DatabaseSeeder.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #12525
Fixes bug where an unsuccessful assessment in final assessment step didn't lead to an overall status of "Disqualified: Pending decision"
I also made some changes to assessment step seeding to make this easier to test manually. Its still not perfect, but a lot easier I think.
Make sure the unit test does what its supposed to.
1. Revert commit 2c3b7c488d2ff95403fb4552682903f2b708a4f6 locally
2. Run phpunit tests (I use `make artisan CMD=test`). The new test should fail.
3. Undo your revert. All tests should pass.
Testing manually
1. Run data seeders
2. Log in as admin@test.com
3. Go to the process called "Published – Complex"
4. Go to the user named Perfect Priority
5. unplace the user, and undo final decision
6. Assess an essential skill in the final assessment step as …
> [Bug] Fix mistake in how status is computed for final assessment step

- api/app/Console/Commands/UnsuspendPlacedCandidates.php
🤖 Resolves #12479
Adds a command for the purpose of reversing what was done database-wise in https://github.com/GCTC-NTGC/gc-digital-talent/issues/12212
Effectively the same command just reversed
1. Set candidates with the relevant status as suspended
2. Run command below
3. Check it worked
Can be run before or after deployment, so at anytime
Run
`php artisan app:unsuspend-placed-candidates`
> [Bug] Add `unsuspend-placed-candidates` command

- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
- apps/web/src/pages/SupportPage/components/SupportForm/utils.ts
🤖 Resolves #12473 
Refactors the support form in order to handle unknown errors.
The form was handling all errors from the response except edge cases where we had no response to work with (500). This refactors it to handle that edge case and return the default error.
2. Navigate to support form `/support`
3. Turn off the web container
4. Submit the form
5. Confirm an error toast appears
> [Fix] Notify user of unknown support form errors

- .vscode/project-words.txt
- README.md
- apps/web/src/components/Pagination/usePagination.ts
- apps/web/src/components/Profile/components/WorkPreferences/utils.ts
- apps/web/src/lang/fr.json
- apps/web/src/lang/mic.json
- apps/web/src/pages/Home/ManagerHomePage/ManagerHomePage.tsx
- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
- documentation/translation.md
- maintenance/README.md
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
- packages/i18n/src/messages/formMessages.ts
- packages/i18n/src/messages/uiMessages.ts
🤖 Resolves #12535.
This PR removes unnecessary leading spaces, removes unnecessary trailing spaces, removes unnecessary trailing periods, replaces non-unicode spaces with unicode spaces, fixes typos in descriptions, replaces `...` (three periods) with `…` (one ellipsis), and adds a few terms to the project dictionary for spell checking.
1. Verify no unnecessary leading spaces in `intl` messages exist in codebase
2. Verify no unnecessary trailing spaces in `intl` messages exist in codebase
3. Verify no unnecessary trailing periods in `intl` messages exist in codebase
4. Verify no non-unicode spaces in `intl` messages exist in codebase
5. Verify no typos in descriptions in `intl` messages (or at least less than before)
6. Verify no  `...` (three periods) used where `…` (one ellipsis) is …
> [Copy] Formatting, typos, and unnecessary spaces

- api/database/factories/UserFactory.php
- api/database/seeders/UserTestSeeder.php
🤖 Resolves #12484 
Adds a specific test user to the seeded data which is a verified government employee with Government of Canada work experience.
This creates a specific test user (`applicant-employee@test.com`) that has the follow state:
- Employee profile
- Verified work email
- At least 1 current Government of Canada work experience
1. Run a fresh ssed `make seed-fresh`
2. Confirm it runs with no errors
3. Login as `applicant-employee@test.com`
4. Confirm they have 
- a verified work email (`/applicant/personal-information`)
- employee profile (`//applicant/employee-profile`)
- 1 current GC work experience (`/applicant/career-timeline`)
> [Feat] Seed user with employee profile

- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/formMessages.ts
- packages/i18n/src/messages/navigationMessages.ts
- packages/i18n/src/messages/uiMessages.ts
🤖 Resolves #12585.
This PR removes unused strings from the codebase.
1. Search codebase for each of the removed keys
2. Verify no keys were removed that are being used
> [Debt] Removes unused strings

- apps/web/src/types/experience.ts
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #12557 
Fixes an issue where checking current role on an existing work experience was not resetting the end date.
3. Create a work experience with an end date
4. Edit experience from step 3, checking the "current role" checkbox
5. Confirm the end date is set to null and renders as "Present"
> [Fix] Resetting end date for current work experiences

- apps/playwright/fixtures/ExperiencePage.ts
- apps/playwright/tests/applicant/experience/link-skill.spec.ts
🤖 Resolves #12493
Updates the skill link test to also submit a work experience to cover a case where fields were resetting after linking a skill.
1. Confirm test changes cover the case specified in the ticket
2. Confirm it passes
> [Test] Submit work experience after linking skill

- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #12470 
Adds headers to block frames on our site.
Following [OWASP recommendations](https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#recommendation), we are adding headers that block frames.
1. Rebuild your image `make down; make up;`
2. Navigate to a page on localhost
3. Confirm both `X-Frame-Options: Deny`  header and `frame-ancestors 'none'` option in CSP appear in headers
> [Debt] Block frames for security

- api/app/Models/PoolCandidate.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
🤖 Resolves #12552
Updates the site to prevent requiring assessment for non-essential behavioural skills. Essential skills and non-essential technical skills should remain the same.
1. Create a pool with both an essential skill and an asset behavioural skill.
2. Create an assessment step which assesses both skills.
3. Publish the pool filling in any other fields required.
4. Create and submit an application to the pool.
5. Navigate to view the application at `admin/candidates/{candidateId}/application`.
6. Confirm the essential skill appears as "To assess" and the asset skill as "Unclaimed" in the assessment step from 2.
7. Assess the essential skill as demonstrated.
8. Confirm the step appears as successful.
> [Feature] Never require asset behavioural skill assessment

- api/app/GraphQL/Validators/CreatePoolSkillInputValidator.php
- api/database/helpers/ApiErrorEnums.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/playwright/utils/pools.ts
- apps/web/src/hooks/usePoolMutations.ts
- apps/web/src/pages/Pools/EditPoolPage/components/AssetSkillsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/EssentialSkillsSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/types.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #11432.
This PR creates a rule that does not allow a skill to added as both essential and asset in a pool (process).
2. Create a process
3. Add a skill to the pool as essential
4. Verify skill is added successfully
5. Add the same skill that was added as an essential skill previously to the pool as asset
6. Verify error toast is rendered with message "You can't include a skill as both essential and an asset in the same process. Please choose one and remove it from the other section."
> [Fix] Rule for pool skill not added as both essential and asset

- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql
- api/app/Http/Resources/UserResource.php
- api/tests/Feature/SnapshotTest.php
- apps/web/src/components/EmploymentEquity/EquityOption.tsx
- apps/web/src/components/EmploymentEquity/EquityOptions.tsx
- apps/web/src/components/EmploymentEquity/IndigenousEquityOption.tsx
- apps/web/src/components/EmploymentEquity/dialogs/DisabilityDialog.tsx
- apps/web/src/components/EmploymentEquity/dialogs/IndigenousDialog.tsx
- apps/web/src/components/EmploymentEquity/dialogs/VisibleMinorityDialog.tsx
- apps/web/src/components/EmploymentEquity/dialogs/WomanDialog.tsx
- apps/web/src/components/EmploymentEquity/types.ts
- apps/web/src/components/Profile/components/DiversityEquityInclusion/DiversityEquityInclusion.tsx
- apps/web/src/pages/Profile/ProfilePage/ProfilePage.tsx
- packages/auth/src/components/AuthorizationProvider.tsx
🤖 Resolves #11355 
Fixes an issue where the equity dialogs were not closing on the user profile page. This also makes some adjustments to the queries on that page to avoid re-mounting it after each mutation.
We were storing sub in the snapshot and our tests were using the profile page query to confirm it matched. The issue here is twofold.
1. We likely should not store sub in the snapshot for security reasons
2. We moved sub to `UserAuthInfo`
We were querying `authInfo { id sub }` just to satisfy the snapshot test. Since we queried this, once the `User` became stale, it was also making its sub types as stale so the `AuthorizationContext` was re-rendering. This re-render caused the `Pending` component to unmount the children (basically the entire app) so the page "refreshed" and user lost …
> [Fix] Equity dialogs close on success

- apps/web/src/pages/Users/UpdateUserPage/types.ts
🤖 Resolves #12616.
This PR removes the unreferenced interface `TeamAssignment`.
Verify `TeamAssignment` interface is not referenced anywhere and is not present in the codebase.
> [Debt] Removes unreferenced interface `TeamAssignment`

- apps/web/src/pages/Users/UpdateUserPage/components/helpers.tsx
🤖 Resolves #12615.
This PR removes the unreferenced function `isTeamTeamable`.
Verify `isTeamTeamable` is not referenced anywhere and is not present in the codebase.
> [Debt] Removes unreferenced function `isTeamTeamable`

- apps/web/src/types/classificationGroup.ts
🤖 Resolves #12637.
This PR removes export for `CLASSIFICATION_GROUP`.
Verify `CLASSIFICATION_GROUP` is not referenced anywhere except in `apps/web/src/types/classificationGroup.ts`.
> [Debt] Removes export for `CLASSIFICATION_GROUP`

- apps/web/src/pages/WorkStreams/WorkStreamTable.tsx
🤖 Resolves #12617.
This PR removes export for `WorkStreamTableRow_Fragment`.
Verify `WorkStreamTableRow_Fragment` is not referenced anywhere except in `apps/web/src/pages/WorkStreams/WorkStreamTable.tsx`.
> [Debt] Removes export for `WorkStreamTableRow_Fragment`

- apps/web/src/pages/WorkStreams/WorkStreamTable.tsx
🤖 Resolves #12618.
This PR removes export for `WorkStreamTable`.
Verify `WorkStreamTable` is not referenced anywhere except in `apps/web/src/pages/WorkStreams/WorkStreamTable.tsx`.
> [Debt] Removes export for `WorkStreamTable`

- apps/web/src/constants/poolCandidate.ts
- apps/web/src/utils/poolCandidate.ts
🤖 Resolves #12642.
This PR removes the `isScreenedOutStatus` function. It also removes the unnecessary export of `isDisqualifiedFinalDecision` and `isQualifiedFinalDecision`. Finally, it removes the unused `SCREENED_OUT_STATUSES`
1. Verify `isScreenedOutStatus` function is not referenced anywhere in codebase
2. Verify `isDisqualifiedFinalDecision` function is only referenced in own file `apps/web/src/utils/poolCandidate.ts`
3. Verify `isQualifiedFinalDecision` function is only referenced in own file `apps/web/src/utils/poolCandidate.ts`
4. Verify `SCREENED_OUT_STATUSES` is not referenced anywhere in codebase
> [Debt] Removes `isScreenedOutStatus` function; removes unnecessary exports; removes unused `SCREENED_OUT_STATUSES`

- apps/web/src/pages/Users/UpdateUserPage/types.ts
🤖 Resolves #12646.
This PR removes the unnecessary export of `TeamTeamable` type.
Verify `TeamTeamable` type is only referenced in own file `apps/web/src/pages/Users/UpdateUserPage/types.ts`
> [Debt] Removes unnecessary export of `TeamTeamable`

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #12649.
This PR removes the `@deprecated` directive for `hasDiploma` fields.
Verify `@deprecated(reason: "hasDiploma to be replaced")` has been removed from all instances of the `hasDiploma` field in `api/graphql/schema.graphql`.
> [Debt] Removes `@deprecated` directive for `hasDiploma` fields

- packages/forms/src/components/DateInput/ControlledInput.tsx
- packages/forms/src/components/DateInput/DateInput.stories.tsx
🤖 Resolves #12655 
Fixes the display of a default value in DateInput when in a field array.  Includes a storybook story for demo.
h/t @mnigh and @esizer for pointing me through this.
I've switch the default value access from a simple property dereference to the Lodash Get method which handles indexed array access well.
1. DateInput Storybook stories all work
2. Exist DateInputs still work in the app
> [Bug] Fix default value handling of DateInput

- apps/web/src/components/NavMenu/MainNavMenu.tsx
🤖 Resolves #12610.
This PR removes an invalid `text-align` css value from the `MainNavMenu` component which was never being applied due  to it being applied via a media query.
2. Navigate to http://localhost:8000/ with Firefox browser
3. Verify no change to mobile menu on screen width of less than 1080px
4. Verify no css warning Error in parsing value for ‘text-align’. Declaration dropped.
> [Fix] Removes invalid auto value for `text-align`

- apps/web/src/components/ExperienceFormFields/WorkFields/GovFields.tsx
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #12657
This was applicable to all work experiences, not just ones with secondment selections. 
Effectively, existing logic for `formValuesToSubmitData` did not entirely apply now that experiences could have expected end date values. The end date needed to be handled differently for work experiences
1. Head to career timeline
2. Experiment with create/edit of work experiences
> [Bug] Work experiences expected end date not working

- packages/ui/src/components/Breadcrumbs/Breadcrumbs.tsx
🤖 Resolves #12665.
This PR removes unused `fullWidth` prop from the `Breadcrumbs` component.
Verify `fullWidth` prop on `Breadcrumbs` component is not referenced anywhere in the codebase.
> [Debt] Removes `fullWidth` prop from `Breadcrumbs` component

- api/app/Generators/PoolCandidateCsvGenerator.php
- api/app/Generators/UserCsvGenerator.php
- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql
- api/app/Http/Resources/UserResource.php
- api/app/Models/User.php
- api/app/Traits/Generator/GeneratesUserDoc.php
- api/database/factories/UserFactory.php
- api/database/migrations/2025_01_30_180016_rename_user_gov_columns.php
- api/graphql/schema.graphql
- api/lang/en/headings.php
- api/lang/fr/headings.php
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/KeywordSearchTest.php
- api/tests/Feature/PoolCandidateSearchTest.php
- api/tests/Feature/UserTest.php
🤖 Resolves #12645 
Renames the fields related to being a government employee to be prefixed with `computed_` in preparation for the work experience event listener work.
This only renames and points existing fields to these for now. Actual computation will be done in separate tickets.
1. Refresh api `make refresh-api; make seed-fresh`
2. Confirm no errors
3. Confirm the following works:
- Setting and displaying government info on profile/application
- Downloading user government employee info
> [Feature] Rename `User.gov_*` columns to prefix with `computed_`

- apps/web/src/pages/Profile/ProfilePage/ProfileSnapshot.test.ts
🤖 Resolves #12683.
This PR adds `.skip` to Should have frontend and backend queries matching test.
1. `cd apps/web`
2. `pnpm test -- src/pages/Profile/ProfilePage/ProfileSnapshot.test.ts`
3. Verify Should have frontend and backend queries matching test is skipped
> [Tests] Adds `.skip` to Should have frontend and backend queries matching test

- api/app/Events/WorkExperienceSaved.php
- api/app/Listeners/ComputeGovEmployeeProfileData.php
- api/app/Models/WorkExperience.php
- api/app/Providers/EventServiceProvider.php
🤖 Resolves #12643 
Computes and logs current work experience on created and updated work experience events.
This is just logging the expected values, storing them will be completed in a future ticket.
1. Refresh api `make refresh-api`
2. Login as any user role
3. Start be creating a few non-government experiences
4. Confirm that `computed_is_gov_employee` remains false
5. Add a few gov employee work experiences with varying position type, employment types and start dates
6. Confirm that the appropriate experience values are logged based on the logic outlined in the ticket
> [Feature] Computed current gov work experience

- api/app/Models/CommunityInterest.php
- api/app/Policies/CommunityInterestPolicy.php
- api/config/rolepermission.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/CommunityInterestTest.php
- api/tests/Feature/RolePermissionTest.php
🤖 Resolves #12603 
Add a paginated query to fetch records, it scopes by what community the authenticated user is. As well, it is restricted to community admin and community recruiter roles. 
New permission added `view-team-communityInterest`
Also added to Google Sheets file
1. It will probably be necessary to open Adminer/whatever to adjust the community_interest records to be in a community a user has admin/recruiter privileges in first
2. Query as a community admin/recruiter for records
Query
```
query b {
communityInterestsPaginated(where: {
userName: null
}) {
paginatorInfo {
total
}
data {
community {
name {
en
}
}
user {
firstName
}
trainingInterest
jobInterest
}
}
}
```
Run role-permission seeder
`./artisan db:seed --class=RolePermissionSeeder`
> [Feature] `CommunityInterest` paginated query

- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
🤖 Resolves #12729.
This PR replaces the deprecated use of `m` with `m.create` where `m` is an alias for motion, the animation library.
1. `pnpm watch`
2. Navigate to http://localhost:3000/en/applicant
3. Login as any user
4. Open the notifications dialog via the bell icon
5. Verify no warning messages in console related to `m` or `motion`
> [Debt] Replaces `m` with `m.create`

- api/app/Listeners/ComputeGovEmployeeProfileData.php
- api/app/Models/User.php
- api/database/factories/UserFactory.php
- api/tests/Feature/ComputeGovInfoTest.php
- api/tests/Feature/PoolCandidateSearchTest.php
🤖 Resolves #12648 
Updates the event listener for work experiences to store the values it computes.
...
1. Login as any user
2. Add a work experience with the following state:
- Is a government experience
- Has either no end date or one in the future
3. Confirm your profile updates saying you are a government employee with details specific to the experience created in step 2
4. Delete said experience
5. Confirm your profile updates to indicate you are not a government employee
6. Refer to the priority laid out in https://github.com/GCTC-NTGC/gc-digital-talent/issues/12643 and confirm it functions as expected
> [Feature] Store computed government information values

- api/tests/Feature/PoolCandidateUpdateTest.php
🤖 Resolves #12747 
Updates the comparison of timestamps in the application status test to be less specific (down to minute rather than millisecond). 
1. Run the test multiple times 
2. Confirm it passes every time
> [Fix] Application status timestamp test comparison

- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
- packages/ui/src/components/ResourceBlock/Root.tsx
🤖 Resolves #12249 
Adds a link to the employee profile page to the dashboard for verified government employees.
The state is always complete since we have success hardcoded for now. We may need a ticket to fix that :thinking: 
2. Login as a non-employee, likely `applicant@test.com`
3. Confirm the link does not appear in the sidebar
4. Login as an employee `applicant-employee@test.com`
5. Confirm the link does appear and sends you to the appropriate page
> [Feat] Add employee profile link

- apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
🤖 Resolves #12784 
- Fix personal information url on applicant dashboard
1. Build app
2. Login as `applicant-employee@test.com`
3. Ensure link takes employee to `/en/applicant/personal-information`
> [Bug] Fix personal information url

- api/app/GraphQL/Validators/UpdateUserAsUserInputValidator.php
- packages/helpers/src/constants/regularExpressions.ts
🤖 Resolves #12723.
Adds (far to many) more valid government email domains for the work email field.
Go through the various email domains in the list in the issue confirming:
- The domain itself is OK
- Subdomains are OK, like abc.gg.ca is OK for gg.ca
- Supersets are not OK, like digg.ca is not OK for gg.ca
> [Feature] Add more valid government email domains

- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
🤖 Resolves #12785.
This PR adds Application ID to the application process dialog.
3. Sign in as applicant@test.com
4. Navigate to http://localhost:8000/en/applicant
5. Expand Job applications accordion
6. Activate trigger for Review your application dialog
7. Verify Application ID and its value are rendered
> [Fix] Adds Application ID

- apps/web/src/pages/CommunityInterests/sections/FindANewCommunity.tsx
🤖 Resolves #12793 
Prevents a user from attempting to add am interest in a community twice.
1. Log in as `applicant-employee@test.com`
2. Note on the dashboard which communities have already had interests added for them
3. Click "Add a community"
4. Observe that communities with interests already added are not available to pick
> [Bug] Exclude already interested communities from "add" page

- apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
🤖 Resolves #12836.
This PR fixes the value rendered for **Employment length** to use `opportunityLength` value in `ReviewApplicationDialog`.
1. Navigate to http://localhost:8000/en/applicant
2. Click on a submitted application
3. Verify **Employment length** renders correct value
> [Fix] `opportunityLength` value in `ReviewApplicationDialog`

- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
🤖 Resolves #12819.
Updates the guidance copy to find recruitment processes you've been qualified for in both English and French. Also updates it so the copy only appears for applications with the "Qualified in process" status.
1. Ensure the FEATURE_NEW_APPLICANT_DASHBOARD flag is on.
2. Create and submit a new application.
3. Navigate to the new applicant dashboard page `/en/applicant/dashboard`.
4. View the dialog for your submitted application and confirm the guidance text does not appear.
5. As an admin mark the application as qualified.
6. View the applicant dialog for the application and confirm the updated guidance copy appears.
Qualified application:
Non-qualified application:
> [Copy] Update recruitment process guidance copy

- apps/web/src/pages/Communities/CreateCommunityPage/components/CreateCommunityForm.tsx
- apps/web/src/pages/Communities/UpdateCommunityPage/UpdateCommunityPage.tsx
- apps/web/src/pages/CommunityInterests/sections/AdditionalInformation.tsx
- apps/web/src/pages/EmployeeProfile/components/GoalsWorkStyleSection/Display.tsx
- apps/web/src/pages/EmployeeProfile/components/GoalsWorkStyleSection/GoalsWorkStyleSection.tsx
🤖 Resolves #12795.
This PR replaces `RichTextInput` with `TextArea` in several components.
2. Navigate to http://localhost:8000/en/applicant/community-interests/create
3. Verify 1 textarea does not allow for markup
4. Navigate to http://localhost:8000/en/admin/communities/create
5. Verify 2 textareas do not allow for markup
6. Navigate to http://localhost:8000/en/admin/communities/:community-id/edit
7. Verify 2 textareas do not allow for markup
8. Navigate to http://localhost:8000/en/applicant/employee-profile#goals-work-style-section
9. Verify 3 textareas do not allow for markup
<details><summary>Screenshots (4)</summary>
<p>
</p>
</details>
> [Fix] Replaces `RichTextInput` with `TextArea`

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/lang/fr.json
- apps/web/src/messages/employeeProfileMessages.ts
- apps/web/src/pages/EmployeeProfile/EmployeeProfilePage.tsx
- apps/web/src/pages/EmployeeProfile/components/CareerObjective/CareerObjectiveSection.tsx
- apps/web/src/pages/EmployeeProfile/components/CareerObjective/Display.tsx
- apps/web/src/pages/EmployeeProfile/components/NextRoleSection/Display.tsx
- apps/web/src/pages/EmployeeProfile/components/NextRoleSection/NextRoleSection.tsx
- apps/web/src/pages/EmployeeProfile/messages.ts
- apps/web/src/validators/employeeProfile/careerObjective.ts
- apps/web/src/validators/employeeProfile/nextRole.ts
🤖 Resolves #12012 
Adds the frontend UI for the "Next Role" and "Career Objective" sections.
1. Log in as 'applicant-employee@test.com'
2. Navigate to /applicant/employee-profile
3. Test updating fields in the Next Role and Career Objective sections.
> [Feature] Next Role and Career Objective frontend

- api/app/Models/User.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/UserTest.php
- apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.stories.tsx
- apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
- apps/web/src/pages/EmployeeProfile/EmployeeProfilePage.tsx
- apps/web/src/utils/userUtils.ts
🤖 Resolves #12828 
Moves the calculation of whether a user us a verified government employee to the backend instead of computing it on the server.
1. Rebuild `make refresh-api; make seed-fresh; pnpm dev:fresh;`
2. Login as a user who is not a verified government employee
3. Confirm the pages protected by this check cannot be accessed
4. Login as a verified government employee
5. Confirm pages protected by this check can be accessed
> [Debt] Move verified gov employee to backend

- apps/web/src/pages/TrainingOpportunities/components/TrainingOpportunityForm.tsx
🤖 Resolves #12703 
Removes the validation for training opportunity deadline to allow creating/updating with date in the past.
3. Navigate to the create form `/en/admin/training-opportunities/create`
4. Confirm you can submit with a deadline in the past
5. Edit the training opportunity
6. Confirm you can update with a deadline in the past
> [Feat] Allow past deadlines for training opportunities

- apps/web/src/components/ExperienceCard/ExperienceCard.tsx
- apps/web/src/components/ExperienceCard/WorkContent/WorkStreamsContent.tsx
- apps/web/src/pages/Applications/fragment.ts
- apps/web/src/pages/Profile/CareerTimelineAndRecruitmentPage/components/CareerTimelineAndRecruitment.tsx
- apps/web/src/pages/Users/AdminUserProfilePage/AdminUserProfilePage.tsx
🤖 Resolves #12827 
Updates the `ExperienceCard` component to display work streams for `WorkExperience` type.
3. Create a work experienc with some woprk streams
4. Navigate to the career timeline
5. Confirm the work streams appear on the card under "Addition details"
> [Feat] Add work streams to `ExperienceCard`

- apps/playwright/tests/applicant/application-iap.spec.ts
- apps/playwright/tests/applicant/application.spec.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx
- apps/web/src/pages/Applications/ApplicationSuccessPage/ApplicationSuccessPage.tsx
🤖 Resolves #12859.
This PR updates the copy on application success alert. It also updates an identical string used in a toast.
2. Apply to a job
3. Verify success message is updated with appropriate copy and URLs in English and French
4. Apply to a job with publishing group of IAP
5. Verify success message is updated with appropriate copy and URLs in English and French
> [Copy] Updates application success alert

- apps/web/src/pages/CommunityInterests/form.ts
🤖 Resolves #12860
Sets the initial value for the consent checkbox in the community interest form based on saved job/training interest.
1. Navigate to the applicant dashboard and select to add a community interest.
2. Select a functional community.
3. Confirm the consent section appears without a checkbox.
4. Select interest in job opportunities.
5. Confirm the consent checkbox appears unchecked.
6. Fill out the remaining fields and submit the form.
7. On the applicant dashboard select to edit the community interest.
8. Confirm the form starts with the consent checkbox checked.
9. Remove any job/training interest and save the form.
10. On the applicant dashboard select to edit the community interest.
11. Confirm the consent section appears without a checkbox.
12. Select interest in job …
> Set default value for consent checkbox based on saved job/training interest

- apps/web/src/components/EmploymentEquity/dialogs/Definition.tsx
- apps/web/src/components/EmploymentEquity/dialogs/DisabilityDialog.tsx
- apps/web/src/components/EmploymentEquity/dialogs/IndigenousDialog.tsx
- apps/web/src/components/EmploymentEquity/dialogs/VisibleMinorityDialog.tsx
- apps/web/src/components/EmploymentEquity/dialogs/WomanDialog.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #12584.
This PR updates the `Definition` component instances to omit three dots.
1. pnpm build
2. Navigate to http://localhost:8000/en/applicant/personal-information#diversity-equity-inclusion-section
3. Open each of the four equity dialogs
4. Verify each one adheres to new format in English and French
> [Copy] Updates `Definition` component instances to omit three dots

- apps/web/src/components/ExperienceFormFields/WorkFields/GovFields.tsx
🤖 Resolves #12769 
Fixes an issue that occurred when changing the employment type was resetting fields to their default values rather than nulling them causing the form to go to unrealistic states.
When using `resetField` from `react-hook-form` it sets it back to the default value. So, when editing an existing experience it was resetting `govContractorType` to the one that was previously selected rather then setting it to `null`. Since this was the only condition to display that field, it remained visible and the user could submit a non-contractor experience with a firm or agency name.
Using `null` as the default value fro these resets fixes that issue.
3. Create a government contractor work experience that has a form or agency name
4. …
> [Fix] Resetting government fields on work experience form

- apps/web/src/lang/fr.json
- apps/web/src/pages/CommunityInterests/sections/ReviewAndSubmit.tsx
🤖 Resolves #12948.
This PR updates copy on the add and edit community interest forms to reflect that it is not possible to remove a community interest.
2. Navigate to http://localhost:8000/en/applicant/community-interests/create
3. Verify copy indicated in the linked issue has been changed in English and French
> [Copy] Add and edit community interest forms inability to remove

- apps/web/src/components/CommunityInterestDialog/CommunityInterestDialog.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/CommunityInterests/sections/FindANewCommunity.tsx
🤖 Resolves #12913.
This PR updates copy on the add and edit community interest forms and dialog for preferred work streams.
2. Navigate to http://localhost:8000/en/applicant/community-interests/create
3. Verify copy indicated in the linked issue has been changed in English and French
> [!NOTE]
> The Add a community, Edit a community, Dialog on applicant dashboard use the same string sources for the two strings changed in this PR.
> [Copy] Add and edit community interest preferred work streams

- api/app/Models/DevelopmentProgramInterest.php
- api/database/factories/CommunityInterestFactory.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/CommunityInterestDialog/CommunityInterestDialog.tsx
- apps/web/src/components/CommunityInterestDialog/DevelopmentProgramInterestItem.tsx
- apps/web/src/pages/CommunityInterests/UpdateCommunityInterestPage/UpdateCommunityInterestPage.tsx
- apps/web/src/pages/CommunityInterests/form.ts
- apps/web/src/pages/CommunityInterests/sections/TrainingAndDevelopmentOpportunities.tsx
🤖 Resolves #12924 
Fixes issues with updating and displaying development program interests.
This was multifaceted and the scope was expanded a little to address as many issues as I discovered here.
1. Looks like laravel was having trouble resolving the relationship due to not explicitly stating the foreign key (usually uses magic to figure this out). Adding this allowed us to actually get the relationship since before it was always an empty array
2. Order of community development programs and form values were different. This was resulting in users updating the wrong development program. We were looping thourhg the community dev programs and just assuming the default form values were in the same order and using index as the key name.
3. Use of `sync` on a `HasMany`. You cannot sync a has …
> [Fix] Development program interests

- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #12891 
Adds the number of unread notifications to the `aria-label` for the notification dialog trigger for screen readers.
2. Login
3. Confirim, with no unread notifications, the label remains the same
4. Create a notification for the logged in user
5. Confirm the label updates to include a count of new/unread notifications
> [a11y] Include unread notification count in `aria-label`

- apps/web/src/components/ExperienceCard/ExperienceCard.tsx
- packages/fake-data/src/fakeExperiences.ts
- packages/fake-data/src/fakeLocalizedEnum.ts
🤖 Resolves #12947.
This PR updates the `ExperienceCard` layout to fit elements within its container on smaller screen widths.
The `fakeExperiences` used by the `ExperienceCard` stories have not kept up with changes to the data shape of experiences, including whether they are government, contractor, or a host of others. For the purposes of rendering as much as possible for visual testing, some of these fields have been added to `fakeExperiences` for the type work.
2. Navigate to http://localhost:6006/?path=/story/components-experiencecard--work-experience-card
3. Open canvas in new tab
4. Toggle device toolbar and set width to 310px (this is for Chrome, other browsers may differ)
5. Verify text does not overflow outside of container
6. Verify card on larger screen …
> [Fix] `ExperienceCard` layout fits elements on smaller screen widths

- apps/web/src/pages/ApplicantDashboardPage/ApplicantDashboardPage.tsx
- packages/ui/src/components/ResourceBlock/SingleLinkItem.tsx
🤖 Resolves #12886 
This adds heading markup to the links on the applicant dashboard.
3. Confirm links in the sidebar have the appropriate heading mark up
> [a11y] Add semantic heading markup to dashboard links

- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql
- api/app/Http/Resources/CommunityResource.php
- api/app/Http/Resources/WorkExperienceResource.php
- api/app/Http/Resources/WorkStreamResource.php
- api/app/ValueObjects/ProfileSnapshot.php
- apps/web/src/pages/Profile/ProfilePage/ProfilePage.tsx
🤖 Resolves #12914 
Adds work experience work streams and community to the application snapshot so they can be rendered.
2. Add a work experience with work streams
3. Submit an application'
4. Navigate to the application on the admin interface
5. Confirm work streams appear on the card under "Career timeline"
> [Fix] Adds work streams to application snapshot

- packages/ui/src/components/Breadcrumbs/Crumb.tsx
🤖 Resolves #12901 
Forces the document to reload when activating the current page breadcrumb.
2. Navigate to a page with breadcrumbs i.e `/browse/pools`
3. Turn on a screen reader
4. Activate the current breadcrumb
5. Confirm the page is reloaded and the heading is announced
> [A11y] Reload document on current breadcrumb activation

- api/app/GraphQL/Validators/CreateCommunityInterestInputValidator.php
- api/app/GraphQL/Validators/UpdateCommunityInterestInputValidator.php
- api/database/migrations/2025_03_19_160515_make_interest_columns_nullable.php
- apps/web/src/pages/CommunityInterests/form.ts
- apps/web/src/pages/CommunityInterests/util.ts
🤖 Resolves #13030
Handles nulls in community interests better, allowing community interests other than finance.
1. Run migration
2. Log in as applicant-employee@test.com
3. On the dashboard, navigate to the community section
4. Add different community interests
5. Edit different community interests
> [Bug] Handle nulls better in community interests

- apps/web/src/components/Router.tsx
- apps/web/src/components/TalentNominationEventCard/TalentNominationEventCard.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/pages/CreateTalentNominationPage/CreateTalentNominationPage.tsx
- apps/web/src/pages/TalentManagementEventsPage/TalentManagementEventsPage.tsx
🤖 Resolves #13005.
This PR adds a `CreateTalentNominationPage` component that works in a similar way to the `CreateApplicationPage` that is renders nothing but adds logic to force a redirect to the login page for non-logged in users.
3. Navigate to http://localhost:8000/en/communities/talent-events
4. Logout so no user is logged in
5. Press **Start a nomination** link
6. Verify redirect to login page
7. Login as applicant-employee@test.com
8. Verify nomination is created and nomination form instructions page is navigated to
9. Navigate to http://localhost:8000/en/communities/talent-events
10. Login as applicant-employee@test.com
11. Press **Start a nomination** link
12. Verify nomination is created and nomination form instructions page is navigated to
> [Feature] Create Talent Nomination Page

- apps/web/src/pages/Users/UserEmployeeInformationPage/components/CareerDevelopmentSection.tsx
🤖 Resolves #13036.
This PR adds retirement values to GC employee profile in the Career development preferences section.
2. Navigate to http://localhost:8000/en/admin/users/
3. View GC employee profile tab of a government employee
4. Verify retirement eligibility and year of retirement eligibility are rendered in the Career development preferences section
> [Feature] Adds retirement values to GC employee profile

- apps/web/src/pages/Users/UserEmployeeInformationPage/components/CareerObjectiveSection.tsx
- apps/web/src/pages/Users/UserEmployeeInformationPage/components/NextRoleSection.tsx
🤖 Resolves #13057.
This PR fixes sorting for unordered lists on GC employee profile that are already sorted alphabetically on their equivalent employee profile (non-admin) page.
2. Navigate to a GC employee profile tab of a government employee
3. Verify all unordered lists (Desired work streams, Preferred departments or agencies) are alphabetically sorted in English and French
> [Fix] Sort alphabetically unordered lists on GC employee profile

- api/app/Models/Skill.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/lang/__snapshots__/lang.test.ts.snap
- apps/web/src/lang/fr.json
- apps/web/src/pages/TalentNominations/NominateTalent/NominateTalentPage.tsx
- apps/web/src/pages/TalentNominations/NominateTalent/components/Actions.tsx
- apps/web/src/pages/TalentNominations/NominateTalent/components/Rationale.tsx
🤖 Resolves #12321 
Populates the rationale step of a talent nomination.
- Competencies error message is a placeholder, waiting for actual message.
- Had to add a families scope to skills so we don't query all just to show less than 10
1. Refresh api `make refresh-api`
2. Build `pnpm run build:fresh`
3. Login as any user
4. Navigate to talent events `/communities/talent-events`
5. Start a nomination for an event that has leadership competencies selected
6. Contiune until you get to the "Ratioinale" step
7. Complete the step confirming skills appear and only accepts exacty 3 items
8. Repeat steps 4-6 with an event that does not have leadership competencies
9. Confirm the "Rationale" step does not include skills
> [Feat] Talent nomination rationale

- api/app/GraphQL/Validators/CreateDevelopmentProgramInterestInputValidator.php
- api/app/GraphQL/Validators/UpdateDevelopmentProgramInterestInputValidator.php
🤖 Resolves #13064 
Make the field nullable in validation for both create and update operations
1. Create a community interest and then update it, from your applicant dashboard
2. In both cases, select a community that has training programs and then do not fill them in
> [Bug] Make `participationStatus` nullable for community interest

- apps/web/src/lang/fr.json
🤖 Resolves #13072.
This PR updates French Title for the comptrollership executives talent management page.
2. Navigate to http://localhost:8000/fr/comptrollership-executives
3. Verify page title and `h1` are _Gestion des talents de la fonction de contrôleur_
> [Copy] Updates French Title for the comptrollership executives talent management page

- apps/web/src/lang/fr.json
- apps/web/src/pages/EmployeeProfile/components/CareerDevelopmentSection/CareerDevelopmentSection.tsx
- apps/web/src/pages/EmployeeProfile/components/CareerObjective/CareerObjectiveSection.tsx
- apps/web/src/pages/EmployeeProfile/components/GoalsWorkStyleSection/GoalsWorkStyleSection.tsx
- apps/web/src/pages/EmployeeProfile/components/NextRoleSection/NextRoleSection.tsx
🤖 Resolves #13039.
This PR updates the button styles from `inline` to `solid` to match other Save changes buttons on the employee profile page.
> [!NOTE]
> The gap value and `aria-label` copy style have been updated for consistency as well and a typo in French fixed.
2. Log in as a government employee 
3. Navigate to http://localhost:8000/en/applicant/employee-profile#career-development-section
4. Verify all Save changes buttons on the page use the same style, gap value, and `aria-label` copy style
> [Fix] Consistent submit button, gap value, `aria-label` style on employee profile page

- apps/playwright/tests/login-logout.spec.ts
- apps/playwright/utils/auth.ts
🤖 Resolves #13082.
This PR fixes a playwright selector for sign in that was changed in #13076.
1. `pnpm e2e:playwright:chromium`
2. Verify all tests pass
> [Fix] Playwright selector sign in

- apps/web/src/pages/CertificationExamVouchersPage/CertificationExamVouchersPage.tsx
🤖 Resolves #13069
Updated links for the English and French "Request Voucher" buttons on the IT Training Fund page.
Updated both the English and French "Request Voucher" links to:
English link: https://forms-formulaires.alpha.canada.ca/en/id/cm8hx7lwz000uyl693aju6upq
French link: https://forms-formulaires.alpha.canada.ca/fr/id/cm8hx7lwz000uyl693aju6upq
1. Build app `run pnpm dev`
2. Navigate to: `https://talent.canada.ca/en/it-training-fund/certification-exam-vouchers`
3. Click the "Request a voucher" button.
4. Verify the redirected page:
- Scroll to the bottom and check the "Application for certification exam vouchers" page.
- Confirm the page is up-to-date by checking the date at the bottom.
5. Repeat steps 2-3 for the French page.
English: 
French:
> [Feature] Update link to exam vouchers form - it training fund page

- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/lang/fr.json
- apps/web/src/messages/pageTitles.ts
- apps/web/src/pages/TalentNominations/NominationGroup/CareerExperience.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/Details.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/Layout.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/Profile.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/types.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/navigationMessages.ts
🤖 Resolves #12851 
Adds blank stub pages for the admin view of a nomination group.
> [!TIP]
> Sometimes the nominee may not be a verified gov employee so you may need to tweak DB info. 
2. Login as a community talent coordinator (I just have admin@test.com this role)
3. Navigate to `/admin/talent-events/{eventId}/nominations/{nominationGroupid}
4. Confirm the page exists with bread crumbs and tabs
> [Feat] Nomination group admin stub pages

- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/CareerDevelopmentTaskCard.tsx
🤖 Resolves #13089.
This PR update copy to correctly refer to a link rather than a button on the applicant dashboard.
2. Navigate to http://localhost:8000/en/applicant
3. Verify null state copy is **Communities might be suggested based on your career experience. You can also add functional communities using the "Add a community" link.**
5. Verify null state copy is **Des collectivités peuvent être suggérées en fonction de votre expérience professionnelle. Vous pouvez également ajouter des collectivités fonctionnelles en cliquant sur le lien « Ajoutez une collectivité ».**
> [Copy] Update copy to correctly refer to a link rather than a button on the applicant dashboard

- apps/web/src/pages/Users/UserEmployeeInformationPage/UserEmployeeInformationPage.tsx
- apps/web/src/pages/Users/UserInformationPage/UserInformationPage.tsx
🤖 Resolves #13066
Adds the ability for the community talent coordinator role to access the first three admin user tabs.
1. Make sure your permissions are up to date `php artisan db:seed --class=RolePermissionSeeder`
2. Log in as talent-coordinator@test.com
3. Navigate to /admin/community-talent
4.  Click on a name to go to /admin/users/{userId}/employee-profile
5. Click the other tabs
> [Bug] Fix coordinator roles on admin user pages

- apps/web/src/pages/TalentNominations/NominateTalent/NominateTalentPage.tsx
🤖 Resolves #13091 
Fixes an issue where the initial redirect was being added to history preventing the back button from functioning as expected.
2. Login as employee `applicant-employee@test.com`
3. Naivgate to `/communities/talent-events`
4. Start a nomination for an event
5. Click the browser back button
6. Confirm you are sent back to the list of events
> [Fix] Browser history after nomination creation

- apps/web/src/hooks/useBreadcrumbs.ts
🤖 Resolves #13098 
Removes the logic that changed the path of the home link in breadcrumbs to be the current nav roles dashboard.
1. Build app` pnpm run dev:fresh`
3. Change your nav role
4. Confirm the home link in breadcrumbs always points to `/`
> [Fix] Remove logic that changes home link in breadcrumbs

- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/TalentEvents/TalentEvent/DetailsPage.tsx
- apps/web/src/pages/TalentEvents/TalentEvent/Layout.tsx
- apps/web/src/pages/TalentEvents/TalentEvent/NominationsPage.tsx
- apps/web/src/pages/TalentEvents/TalentEvent/types.ts
- apps/web/src/pages/TalentNominations/NominationGroup/Layout.tsx
🤖 Resolves #13087 
Adds the admin stubs for a talent nomination event.
1. Find a talent event for a digital community (or create one)
2. Login as talent coordinator `talent-coordinator@test.com`
3. Navigate to `/admin/talent-events/{eventId}`
4. Confirm it appears with the proper layout
> [Feat] Admin talent even stubs

- apps/web/src/lang/fr.json
- apps/web/src/pages/TalentEvents/TalentEvent/DetailsPage.tsx
🤖 Resolves #13121 
Adds the admin details page for talent nomination events.
> [!WARNING]
> It will not look exactly like the mockup since it is out of date. Look to see that it matches a layout/spacing/etc 
2. Login as talent coordinator (either `talent-coordinator@test.com` or any other and give yourself the role)
3. Find a talent event in the database that is assigned to a community you are the talent coordinator for
4. Navigate to `/admin/talent-events/{eventId}`
5. Confirm it displays information in a similar manner to the mock up
> [Feat] Talent nomination event details page

- api/app/GraphQL/Validators/CreateCommunityInterestInputValidator.php
- api/app/GraphQL/Validators/UpdateCommunityInterestInputValidator.php
- api/app/Models/CommunityInterest.php
- api/app/Policies/UserPolicy.php
- api/database/factories/CommunityInterestFactory.php
- api/database/migrations/2025_04_02_132147_add_community_interest_consent.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/CommunityInterestTest.php
- api/tests/Feature/DevelopmentProgramInterestTest.php
- api/tests/Unit/UserPolicyTest.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/CommunityInterests/CreateCommunityInterestPage/CreateCommunityInterestPage.tsx
- apps/web/src/pages/CommunityInterests/UpdateCommunityInterestPage/UpdateCommunityInterestPage.tsx
- apps/web/src/pages/CommunityInterests/form.ts
- apps/web/src/pages/CommunityInterests/sections/ReviewAndSubmit.tsx
🤖 Resolves #13136 
Adds database storage for the consent checkbox, makes it mandatory, and uses it for policies.
1. Run migrations
2. Log in as applicant-employee@test.com
3. Log in as talent-coordinator@test.com
> [Feature] Make consent mandatory for community interests

- apps/web/src/pages/ApplicantDashboardPage/components/ReviewTalentNominationDialog.tsx
🤖 Resolves #13172
- Fix nominator name and work email on dialog when fallback name and email is selected
1. Build app `pnpm run build`
3. Go to applicant dashboard
4. View talent nominations
5. Ensure nomination dialogs have nominator name and email, when fallback  name and email are selected
> [Bug] Nominator name and email on dialog

- api/app/GraphQL/Validators/Mutation/SubmitTalentNominationValidator.php
- api/app/GraphQL/Validators/UpdateTalentNominationInputValidator.php
- apps/web/src/pages/TalentNominations/NominateTalent/components/Rationale.tsx
🤖 Resolves #13179 
Removes the rule making additional comments a required field for a nomination rationale.
2. Login as an employee `applicant-employee@test.com`
3. Start a nomination
4. Contiune to the rationale step
5. Observe that the additional comments field is not required
> [Fix] Remove required rule for rationale additional comments

- apps/web/src/lang/fr.json
- apps/web/src/pages/TalentNominations/NominateTalent/components/Details.tsx
- apps/web/src/pages/TalentNominations/NominateTalent/components/Nominator.tsx
- apps/web/src/pages/TalentNominations/NominateTalent/components/Nominee.tsx
🤖 Resolves #13144.
This PR updates duplicate labels in nomination form and shortens nominator labels in French by using an abbreviated doublet.
2. Login as a verified Government of Canada employee using `applicant-employee@test.com`
3. Navigate to http://localhost:8000/en/communities/talent-events
4. Start a nomination
5. Force fallback for nominator to appear
6. Verify labels are no longer identical
7. Switch to French
8. Verify abbreviated doublet is used where requested
<details><summary>English (3)</summary>
<p>
</p>
</details> 
<details><summary>French (3)</summary>
<p>
</p>
</details>
> [Copy] Updates nomination form labels and copy

- apps/web/src/components/Router.tsx
🤖 Resolves 
Fix the router issue enabling accessing event pages again
1. Can navigate to `/en/admin/talent-events/:eventId` from the table again
2. Table and subsequent nested paths accessible
> Fix talent events nested path

- apps/web/src/pages/TrainingOpportunities/CreateTrainingOpportunityPage.tsx
🤖 Resolves #13128 
Fixed breadcrumb on the admin Create Training opportunity form.
1. Build app `run pnpm dev`
2. Login in as admin
3. Navigate to `/en/admin/training-opportunities`
4. Click on create training opportunity to open the form
5. Hover over or click the "Training Opportunities" breadcrumb
6. URL updated to `/en/admin/training-opportunities`
> [Bug] Updated admin training breadcrumb

- apps/web/src/components/ExperienceFormFields/CommunityFields.tsx
- apps/web/src/components/ExperienceFormFields/EducationFields.tsx
- apps/web/src/components/ExperienceFormFields/PersonalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/CafFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/ExternalFields.tsx
- apps/web/src/components/ExperienceFormFields/WorkFields/GovFields.tsx
- packages/forms/src/components/DateInput/ControlledInput.tsx
- packages/forms/src/components/DateInput/DateInput.tsx
- packages/forms/src/components/DateInput/types.ts
- packages/forms/src/components/DateInput/utils.ts
🤖 Resolves #13058 
Updates the date ranges for experiences to always be set to the start and end of a month.
We previously would store both start and end dates to the start of the month. This was causing issues with "current role" when the end date was the current month since it looked like a past experience.
This updates both start and end date to always be set to the start/end of a month to avoid this.
1. Refresh api `make refresh-api`
2. Attempt to set an experience start/end dates to middle of the month days (e.g. January 15th)
3. Confirm start date is constrained tot he first day of that month and end date is constrained to the last day in the month
4. Set expected end date of experience to the current month
5. Confirm fronted is still able to discern that the experience is current
> [Fix] Constrain start/end dates to edges of month ranges

- apps/web/src/pages/CommunityInterests/sections/AdditionalInformation.tsx
🤖 Resolves [13185](https://github.com/GCTC-NTGC/gc-digital-talent/issues/13185)
Validate financial management community form when the consent check box is not checked .
Created a check that ensures that the .includes() method is only called if the selectedFinanceOtherRoles is an array, which enforces the validation check.
1. Click Add community in the dashboard
2. Select Finance community in the drop down ( can't be reproduced with others )
3. First 2 options can be anything
4. Check CFO status
5. Don't check anything for Additional duties and Other roles
6. Don't check consent check box
7. Click Submit
8. Should show validation error at the consent checkbox
> [BUG] Creating a Financial Community Interest leading to a error page on a specific scenario

- apps/web/src/lang/fr.json
- apps/web/src/pages/TalentEvents/TalentEvent/NominationsPage.tsx
- apps/web/src/pages/TalentEvents/TalentEvent/util.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/components/NominationGroupSidebar.stories.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/components/NominationGroupSidebar.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/components/NominationNavigation/NominationNavigation.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/components/NominationNavigation/useNominationNavigation.ts
🤖 Resolves #13023 
Adds next and previous buttons to the nomination group layout sidebar.
1. Open database and ensure there are more than three talent nomination groups for a specific event
2. Make sure the talent coordinator account is assigned to the community for the event in step 1
3. Build the app `pnpm run dev:fresh`
4. Login as talent coordinator `talent-coordinator@test.com`
5. Navigate to the nominations talent for the event in step 1
6. Click on a name in the table
7. Confirm the next/previous buttons appear in the sidebar and function as expected
> [Feat] Next/Prev navigation for nominations

- api/app/Models/TalentNomination.php
- api/tests/Feature/TalentNominationGroupTest.php
🤖 Resolves #13239 
Fix the `firstOrCreate()` call
Tests `testNominationCanCreateNewGroup` and `testNominationCanAttachToExistingGroup` already provided partial coverage
1. Cannot replicate the issue, so, no nomination event mismatch in the event-group-nomination trio
> [Bug] Talent nomination group first or create fix

- api/app/Policies/CommunityInterestPolicy.php
🤖 Resolves #13261
The other gaps were solved, I think one corner case remains after which things should hopefully all work right
1. Become a talent coordinator of some community A
2. Submit a community interest in community B, consent to being searchable
3. Access community talent table without issue
> [Bug] Allow viewing own `CommunityInterest.user` field

- apps/web/src/pages/TalentEvents/components/TalentEventTable.tsx
- apps/web/src/pages/TalentEvents/components/helpers.tsx
🤖 Resolves #13265 
Updates the count of nominees on the talent events table to use `TalentNominationGroup` instead of `TalentNomination`. This effectively counts unique nominees instead of individual nominations.
2. Login as `talent-coordinator@test.com`
3. Create multiple nomination groups for an event, making sure some contain multiple nominations
4. Navigate to `/admin/talent-events`
5. Confirm the nominations column counts only the groups and not individual nominations
> [Fix] Nominee count on talent events table

- apps/web/src/components/Profile/components/WorkPreferences/Display.tsx
- apps/web/src/components/Profile/components/WorkPreferences/FormFields.tsx
- apps/web/src/components/Profile/components/WorkPreferences/utils.ts
- apps/web/src/lang/fr.json
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/localizedConstants.tsx
🤖 Resolves #13283.
This PR updates how the telework statement reads in both English and French; fixes some copy syntax; and removes unused copy and a function argument.
2. Navigate to http://localhost:8000/en/applicant/personal-information#work-preferences-section
3. Check all Work location preferences checkboxes and save form
4. Verify copy in English
6. Verify copy in French
> [Copy] Updates `WorkRegionsDetailed` and telework copy

- apps/web/src/pages/TalentNominations/NominateTalent/components/Details.tsx
🤖 Resolves #13291 
Fixes as issue that was causing the fallback being rendered for the advancement reference when the page loads.
2. Login as an employee `applicant-employee@test.com`
3. Start a nomination, continuing to the details page
4. Select "Advancement" as the option
5. Search for a user not in the system for the reference field
6. Enter a fallback
7. Save that step
8. Reload the page
9. Confirm fallback is rendered and displayed as expected
> [Fix] Advancement reference fallback not rendering on load

- apps/web/src/lang/fr.json
- apps/web/src/pages/TalentNominations/NominateTalent/components/Rationale.tsx
🤖 Resolves #13304.
This PR updates the English and French subtitle for nomination rationale step copy for each of the cases where the talent event is `includeLeadershipCompetencies` is `true` and `false`.
> [!TIP]
> Toggle the `includeLeadershipCompetencies` boolean value in the `talent_nomination_events` table to see both cases 
2. Navigate to http://localhost:8000/en/communities/talent-events
3. Create a nomination
4. Navigate to Step 6
5. Verify copy is updated as per linked issue
6. Switch to French
7. Verify copy is updated as per linked issue
> [Copy] Updates Subtitle for nomination rationale step

- packages/toast/src/components/Toast/Toast.stories.tsx
- packages/toast/src/components/Toast/styles.ts
🤖 Resolves #13334.
This PR updates the Toast component dismiss icon colour on smaller width screens to improve colour contrast. It also adds a toast.error to the Toast storybook story.
2. Verify Toast component dismiss icon colour meets minimum colour contrast standards
> [Fix] Toast dark mode dismiss colour

- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
🤖 Resolves #13298
👋 Introduction
This fix ensures that only one submission can happen at a time. It prevents users from submitting the screening decision form multiple times while a create or update mutation is in progress.  Previously user's could click the `Save decision` button multiple times which resulted in multiple submissions to the database.
🧪 Testing
1. Log in as `admin@test.com`
2. Navigate to a pool candidate
3. Click on an assessment
4. Rapidly click `Save decision`
5. Observe that multiple submissions are no longer occurring
> [Bug] Fix duplicate submit for multiple submissions - assessment decision dialog

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #12669.
This PR removes the deprecated and unused `pools` GraphQL query.
2. Verify there are no references to the `pools` GraphQL query in the codebase
> [Debt] Removes `pools` GraphQL query

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/GenericJobTitleTest.php
🤖 Resolves #12671.
This PR removes the (nearly and now) unused `genericJobTitle` GraphQL query.
2. Verify there are no references to the `genericJobTitle` GraphQL query in the codebase
3. Verify there are no references to the `testViewGenericJobTitle` function in the codebase
> [Debt] Removes `genericJobTitle` GraphQL query

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateSearchRequestTest.php
🤖 Resolves #12677.
This PR removes the (nearly and now) unused `deletePoolCandidateSearchRequest` GraphQL mutation.
2. Verify there are no references to the `deletePoolCandidateSearchRequest` GraphQL mutation in the codebase
> [Debt] Removes `deletePoolCandidateSearchRequest ` GraphQL mutation

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
🤖 Resolves #12674.
This PR removes the unused `deletePoolCandidate` GraphQL mutation.
2. Verify there are no references to the `deletePoolCandidate` GraphQL mutation in the codebase
> [Debt] Removes `deletePoolCandidate ` GraphQL mutation

- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/spike.yml
🤖 Resolves #13257 
Fixes the "definition of ready" link on the feature template (I think!).
Also, I took the opportunity to trim the spike template down a bit.
> [Bug] Fix template DOR link

- apps/web/src/components/SkillBrowser/SkillBrowser.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/CoreRequirementsSection/CoreRequirementsSection.tsx
🤖 Resolves #11371 
Updates the type casting for form watchers to prefer the use of the generic.
1. Confirm no more type casts around `useWatch` and `watch` form methods
2. Confirm typescript is still happy
> [Debt] Remove form watch type casts

- apps/web/src/lang/fr.json
- apps/web/src/pages/WorkStreams/CreateWorkStreamPage.tsx
🤖 Resolves #12920
Updates the validation for a work stream key to allow any case of letter.
3. Navigate to create a work stream `/admin/settings/work-streams/create`
4. Confirm the validation allows only letters (of any case) and underscores
> [Fix] Allow uppercase letters for work stream key

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/AssessmentDetailsDialog.tsx
🤖 Resolves #12540 
Fixes an issue where empty error messages were appearing for the skill selection in the assessment plan dialogs
This is not a great solution but maybe works for now? :woman_shrugging: 
The issue is that we have two separate inputs that are essentially collecting for a single data point so at least one of the inputs is required.
To be valid you must select at least one skill from either input. The ideal fix would be to use a single input instead of two separate ones that are combined in the validation and submission, however that will need come designer input so I went with this solution for now :confused: 
> [!NOTE]
> The new error message was provided by @NienkeBr since "required" was not specific enough and could cause confusion. 
2. …
> [Fix] Missing error messages on assessment plan skills inputs

- api/app/GraphQL/Validators/Query/GovEmployeeProfileValidator.php
- api/app/Models/User.php
- api/app/Rules/IsVerifiedGovEmployee.php
- api/database/helpers/ApiErrorEnums.php
- api/tests/Feature/GovEmployeeProfileTest.php
- apps/web/src/components/EmployeeSearchInput/Error.tsx
- apps/web/src/components/EmployeeSearchInput/types.ts
- apps/web/src/lang/fr.json
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/apiMessages.ts
🤖 Resolves #12831
Adds the error message for when search a government employee that they exist but have yet to verify themselves.
2. Login as a verified gov employee `applicant-employee@test.com`
3. Find a user in the DB that has a work emial but null verification
4. Start a nomination
5. Using one of the employee search inputs in the nomination, search for the user from step 3
6. Confirm the error message indicating someone was found but has yet to verify themsevles
> [Feat] User found, not verified error message

- api/tests/Feature/Notifications/TriggerApplicationStatusChangedTest.php
🤖 Resolves #12782 
Prevents a test fail due to an unrelated notification firing when none are expected.
This simply nulls the fields that would trigger a "gov employee but not verified" notification from being sent since we are not expecting any.
> [!TIP]
> `while make artisan CMD="test tests/Feature/Notifications/TriggerApplicationStatusChangedTest.php --filter=testNothingSentForNewApplications --stop-on-failure"; do echo; done`
1. Run the command provided
2. Confirm test passes 30 times in a row (or more if you want :woman_shrugging: )
> [Fix] Prevent unrelated notification in status changed test

- api/app/Generators/PoolCandidateCsvGenerator.php
- apps/web/src/pages/Users/UserInformationPage/components/UserCandidatesTable/UserCandidatesTable.tsx
🤖 Resolves #12915
If you as an admin have a draft application, it appears in places where it isn't particularly useful. It is fine policy wise, it just isn't useful for them to be rendered/listed
1. Log in as an admin user
2. Create a draft application for some pool abc
3. Go to `/en/admin/users/:userId#candidate-status` for your user
4. Go to the page then download full dataset for pool abc at `/en/admin/pools/:poolId/pool-candidates`
5. Confirm your draft application does not appear
> [Bug] Filter out own draft from admin tools

- apps/web/src/components/Profile/components/LanguageProfile/Display.tsx
- apps/web/src/components/Profile/components/LanguageProfile/utils.ts
- apps/web/src/lang/fr.json
🤖 Resolves #13330.
This PR updates the options for the language section of the user profile.
2. Navigate to http://localhost:8000/en/applicant/personal-information#language-section
3. Verify values for Language of positions you would like to be considered for are updated to those in the linked issue
4. Edit the form
5. Verify checkbox labels for Language of positions you would like to be considered for are updated to those in the linked issue
6. Navigate to admin view of user profile
7. Verify values for Language of positions you would like to be considered for are updated to those in the linked issue
> [Copy] Updates user language profile strings

- api/lang/en/employment_category.php
- api/lang/fr/employment_category.php
- apps/playwright/fixtures/ExperiencePage.ts
- apps/web/src/components/ExperienceFormFields/WorkFields/WorkFields.tsx
- apps/web/src/lang/fr.json
🤖 Resolves #13301.
This PR updates work experience employment category strings.
2. Navigate to http://localhost:8000/en/applicant/career-timeline/create
3. Select Work experience in Experience type field
4. Verify Employment category labels and descriptions match those in the linked issue 
> [Copy] Updates work experience employment category strings

- apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx
🤖 Resolves #13397 
Fixes an issue where skill definitions were dissapearing after you assess a skill.
This one was a little odd and I had a hard time understanidng how this is all put together :sweat_smile: 
It seems we use a different item from the query to display skill definitions depending on if it has been assessed or not :confused: 
```ts
const poolSkill = assessmentResult?.poolSkill ?? poolSkillToAssess;
```
So, the assessment result was not querying the required info to display a definition. There is most certainly a better way to solve this but the component itself is pretty hard to understand and could probably do with some clean up so I opted for a low effort fix for now :woman_shrugging: 
3. Navigate to a …
> [Fix] Display skill definitions after assessing a skill

- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/FunctionalCommunityListItem.tsx
🤖 Resolves #13342 
Adjust the button label to be more informative as to what happens on click
1. Go to applicant dashboard
2. Have a functional community interest
3. Observe accessible label on button for that interest
> [Accessibility] Functional community button label in dashboard

- apps/web/src/lang/fr.json
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #13418.
This PR updates the label displayed on Community Experience form for project input in English and French.
2. Navigate to http://localhost:8000/en/applicant/career-timeline/create
3. Select community participation from Experience type
4. Verify label for field is Project or product
> [Copy] Updates label displayed on Community Experience form for project input

- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewTalentNominationDialog.tsx
🤖 Resolves #13416.
This PR removes "and track its progress" from the subtitle of the dialog and removes the status well from the dialog.
2. Navigate to http://localhost:8000/en/applicant
3. Select and open the dialog for a talent nomination
4. Verify the status well is no longer rendered
5. Verify the subtitle has been updated
> [Copy] Updates nomination dialog subtitle, removes nomination dialog status well

- packages/storybook-helpers/package.json
- pnpm-lock.yaml
Reverts GCTC-NTGC/gc-digital-talent#13431
This broke chromatic it seems so we should roll it back.
> Revert "Bump storybook-react-intl from 3.2.3 to 4.0.1 in the storybook group"

- packages/forms/src/components/RichTextInput/Footer.tsx
- packages/forms/src/components/RichTextInput/RichTextInput.tsx
- packages/forms/src/formUtils.test.ts
- packages/forms/src/utils.ts
🤖 Resolves #12775
The word counter wasn't working right for instances of `<RichTextInput />`
This was due to HTML characters not being handled at all with the word counter function we used. I added another word counter function for handling HTML, for use in rich text. I elected to avoid a one size fits all function so that each function can be tuned separately if needed
1. Test text inputs with word counters
2. Example, text fields for editing a pool
> [Bug] Improve word counter for rich text

- api/app/Policies/UserPolicy.php
🤖 Resolves #13135
The method has been worked on a bit since issue creation so the issue is a bit outdated. Blocks 1, 2, and 4 look right to me. Block 3 seems to not assert the correct team pairing so I adjusted that. 
Tried to go for light as possible touch
What needed changing
If you pass in `rolesTeams` as is, you get a bunch of teams that could all have different roles. If you are X in Team A, and a Y in Team B. You need to assert attempting to be Y in A fails
1. Exercise viewing users while possessing different roles/teams
> [Bug] Adjust `UserPolicy.view()` team logic

- api/app/Casts/LanguageCode.php
- api/app/Discoverers/EnumDiscoverer.php
- api/app/Enums/Language.php
- api/app/Models/User.php
- api/app/Notifications/AdHocEmail.php
- api/app/Notifications/ApplicationDeadlineApproaching.php
- api/app/Notifications/ApplicationStatusChanged.php
- api/app/Notifications/NewJobPosted.php
- api/app/Notifications/System.php
- api/app/Notifications/TalentNominationReceivedNominator.php
- api/app/Notifications/TalentNominationReceivedSubmitter.php
- api/app/Notifications/VerifyEmail.php
- api/app/Providers/GraphQLServiceProvider.php
- api/database/factories/UserFactory.php
- api/phpstan-baseline.neon
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/SnapshotTest.php
🤖 Resolves #10964 
Removes the backing of the `Language` enum to make it consistent with the other enums.
This was backed so we could have case sensitive comparisons with the app locale. So, instead of backing, it just uses `strtolower` in the comparisons. 
> [!IMPORTANT]
> It would be nice if someone could test creating a new user and triggering an email notification in each language to confirm that works. That is probably the most brittle version
1. Refresh api `make refresh-api` 
2. Build the app `pnpm run dev:fresh`
3. Login as any user
4. Change your prefered language a few times
5. Confirm that still works
6. Preferably trigger an email and confirm you get the correct language
> [Debt] Remove backing from language enum

- apps/web/src/components/SkillBrowser/SkillBrowserDialog.tsx
🤖 Resolves #13284 
Prevents the skill browser form from propagating the submission up to the parent form.
2. Login as applicant `applicant-employee@test.com`
3. Navigate to either create or edit experience
4. Scroll down to the skills section
5. Using your keyboard, select "Add a skill"
6. Select a skill and submit the form (with your keyboard)
7. Confirm the skill is selected and there is no attempt to submit the experience form
> [Fix] Skill dialog submitting parent form

- api/lang/en/talent_nomination_group_decision.php
- api/lang/en/talent_nomination_group_status.php
- api/lang/fr/talent_nomination_group_decision.php
- api/lang/fr/talent_nomination_group_status.php
- apps/web/src/pages/TalentNominations/NominationGroup/components/ComputedIcon.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #13414.
Updates "Rejected" nomination statuses to instead say "Not supported".
1. Navigate to view a talent nomination group: `/admin/talent-events/{eventId}/nominations/{nominationGroupId}`.
2. Assess the candidate as not supported if it isn't already.
3. Confirm the status says "Not supported".
4. Navigate to view the nomination table for the event: `/admin/talent-events/{eventId}/nominations`.
5. Confirm the status of your nomination is "Not supported".
6. Look for any other instances referring to nomination status as "Rejected".
> [Copy] Update "Rejected" nomination statuses to "Not supported"

- .vscode/project-words.txt
- api/resources/views/vendor/graphiql/index.blade.php
🤖 Resolves #13446
Get the graphiql page up and running again. There were two issues at play
- Bug with `e.useInsertionEffect` resolved by updating to >= [v3.3.3](https://github.com/mll-lab/laravel-graphiql/releases/tag/v3.3.3)
- Deprecated `DownloadAssetsCommand` resolved by following instructions for [4.0.0](https://github.com/mll-lab/laravel-graphiql/releases/tag/v4.0.0)
1. Can use the graphiql tool again
> [Bug] Update graphiql index to remove deprecated

- api/graphql/schema.graphql
🤖 Resolves #13249
Investigating, and it appears the one expected instance of `canQuery` fetching all does indeed fetch all. Once a high number of departments exists, queries that touch that policy degrade significantly.
I elected to delete the policy call as neither current nor near-future requires gating department, no context where you need to hide  the department from a pool you can view. 
Lotta seeding to do testing. Tangential, some possible performance issues become noticeable with large data volume, An issue already exists for this though https://github.com/GCTC-NTGC/gc-digital-talent/issues/13269
1. Not sure, at the minimum ensure nothing broke
> [Bug] Fix remaining `canQuery` call that fetches all

- api/app/Builders/UserBuilder.php
🤖 Resolves #13465
Fixes the issue, it appears the key name was wrong. This appears to have been a bug present for a while 😬 
1. Test the talent search
Field on the filter type is called `workStreams`
Query `CountPoolCandidatesByPool` correctly referred to it
Scope `whereHasTalentSearchablePublishingGroups` referred to something else instead
> [Bug] Resolve `countApplicants` and `countPoolCandidatesByPool` mismatch

- packages/storybook-helpers/main.ts
- packages/storybook-helpers/package.json
- packages/ui/src/components/Chip/Chip.stories.tsx
- pnpm-lock.yaml
🤖 Resolves #13460.
This PR adds the storybook addon designs and adds a design URL to the `Chip` component's default story.
1. `pnpm i`
2. `pnpm storybook`
3. Navigate to http://localhost:6006/?path=/story/ui-src-components-chip--default
4. Select the Design tab
5. Verify design tab has the appropriate URL for the current `Chip` component
> [Tooling] Adds storybook addon designs

- api/tests/Feature/SnapshotTest.php
🤖 Resolves #13093 
Adds all experience types to the user in the snapshot test to extend out coverage.
We recently had a flaky test due to it depending on the types of experiences a user had when creating a snapshot so we have added all experience types to have more coverage.
1. Run the snapshot test multiple times `make test CMD="./tests/Feature/SnapshotTest.php"`
2. Confirm it passes consistently
> [Test] Add all experience types to snapshot test user

- apps/web/src/pages/TalentNominations/NominateTalent/components/SubHeading.tsx
🤖 Resolves #13289 
Adds a focus and scroll to top on mount of the nomination talent step sub headings.
2. Login as an employee `applicant-employee@test.com`
3. Start a nomination
4. Fill out a step with lots of data to force a scroll that is noticable
5. Submit the page
6. Confirm the next page subheading is focus and scroll position is reset
> [Feat] Scroll to top on nomination form step transition

- apps/playwright/fixtures/ExperiencePage.ts
- apps/web/src/lang/fr.json
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #13483.
This PR updates the group label displayed on Community Experience form for group input in English and French.
2. Navigate to http://localhost:8000/en/applicant/career-timeline/create
3. Select community participation from Experience type
4. Verify label for field is Group, organization, or community
6. Verify label for field is Groupe, organisation ou collectivité
> [Copy] Updates label displayed on Community Experience form for group input

- apps/web/src/components/SkillBrowser/SkillBrowserDialog.tsx
🤖 Resolves #13254 
Updates the skill browser dialog to no longer disable the submit button.
2. Login as an applicant `applicant@test.com`
3. Go to the skill library
4. Using keyboard, select a skill and submit the form
5. Confirm the button is no longer disabled and focus remains on the submit button
6. Confirm you cannot trigger the submit multiple times
> [Fix] Do not disable skill browser submit button

- .github/dependabot.yml
Remove a 3rd party plugin from the storybook group since it can have breaking changes (and has) that we don't want to tie to actual storybook bumps.
> [Fix] Remove `storybook-react-intl` from dependabot group

- api/app/Enums/PoolSelectionLimitation.php
- api/app/GraphQL/Validators/PoolIsCompleteValidator.php
- api/database/factories/PoolFactory.php
- api/lang/en/pool_selection_limitation.php
- api/lang/fr/pool_selection_limitation.php
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/PoolCard/PoolCard.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/processMessages.ts
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/Display.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/AreaOfSelectionWell.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/components/WhoCanApplyText.tsx
- packages/eslint-config-custom/react.mjs
- packages/i18n/src/components/richTextElements.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #13507 
Adds the ability to limit public pools to Canadian citizens only.
1. Rebuild the app
2. Log in as admin@test.com
3. Create or edit a draft pool and experiment with the area of selection controls
4. View a pool advertisement from the applicant side
5. Observe well and "who can apply" changes based on area of selection controls
> [Feature] Area of selection limitation - Canadian citizens

- apps/web/src/components/ExperienceWorkStreams/ExperienceWorkStreams.tsx
- apps/web/src/components/Table/ResponsiveTable/ResponsiveTable.tsx
- apps/web/src/components/Table/ResponsiveTable/RowSelection.tsx
- apps/web/src/components/UserProfile/SkillAccordion/SkillAccordion.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Applications/ApplicationCareerTimelineEditPage/ApplicationCareerTimelineEditPage.tsx
- apps/web/src/pages/Applications/ApplicationCareerTimelinePage/ApplicationCareerTimelinePage.tsx
- apps/web/src/pages/Auth/SignUpPage/SignUpPage.tsx
- apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/SkillSummaryTable.tsx
- apps/web/src/pages/Pools/ViewPoolPage/ViewPoolPage.tsx
- apps/web/src/pages/Pools/ViewPoolPage/components/UnArchiveProcessDialog.tsx
- apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/EstimatedCandidates.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchForm.tsx
- apps/web/src/pages/SearchRequests/SearchPage/components/SearchResultCard.tsx
- apps/web/src/pages/Skills/components/SkillPortfolioTable.tsx
- apps/web/src/pages/TalentEvents/components/helpers.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/components/NominatedForList.tsx
- apps/web/src/pages/TalentNominations/NominationGroup/components/fullCareerExperiencesUtils.ts
- packages/eslint-config-custom/react.mjs
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/formMessages.ts
🤖 Resolves #12832 
Re-enables some of the rules and fixes instances of them.
I left off some because I lack the knowledge authority to enable them :sweat_smile: 
- [`no-multiple-plurals`](https://formatjs.github.io/docs/tooling/linter#no-multiple-plurals)
- We have strings with multiple plurals and I'm not sure how to modify them to not use it
- [`enforce-plural-rules`](https://formatjs.github.io/docs/tooling/linter#enforce-plural-rules)
- This requires we supply a value of `one` but some we don't and I'm not sure if that is valid or not since `one` is the same as `other` :confused:   
I did not change any of the  [`no-literal-string-in-jsx`](https://formatjs.github.io/docs/tooling/linter#no-literal-string-in-jsx) because it is primarily punctuaion and I don't feel condfident in modifying …
> [Fix] formatjs eslint rules

- api/lang/en/assessment_decision.php
- api/lang/fr/assessment_decision.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/components/AssessmentSummary.tsx
🤖 Resolves #13584
👋 Introduction
This PR updates the Record of Decision (ROD) skill assessment. It removes the text "(Remove from process)" from the "Not demonstrated" option and fixes a small grammar issue in the French version.
🕵️ Details
- Removed "(Remove from process)" from the English "not demonstrated" translation in api/lang/en.
- Removed "(supprimée du processus)" from the French "not demonstrated" translation in api/lang/fr.
- Updated French label and description for "Démontrée" to correct grammar (added missing "e").
- Updated frontend strings to match revised translations.
🧪 Testing
1. Build app
3. Navigate to `admin/pool-candidates` and select a candidate
4. Select a requirement to assess
5. Verify copy `(Remove from process)` was removed from "not …
> [Copy] rod dialogue edits

- packages/ui/src/components/ToggleSection/ToggleSection.tsx
🤖 Resolves #13580 
Migrates the `ToggleSection` component to tailwindcss.
> [Debt] Migrate `ToggleSection` to tailwind

- packages/ui/src/components/NotFound/NotFound.tsx
🤖 Resolves #13567.
This PR migrates the `NotFound` component to tailwind.
2. Verify `NotFound` component is the same visually as before
> [Debt] Migrate `NotFound` to tailwind

- packages/ui/src/components/TreeView/TreeView.tsx
- packages/ui/src/components/TreeView/index.ts
- packages/ui/src/index.tsx
🤖 Resolves #13581 
Migrates the `TreeView` component to use tailwindcss.
> [Debt] Migrate `TreeView` to tailwindcss

- apps/web/src/pages/CommunityInterests/UpdateCommunityInterestPage/UpdateCommunityInterestPage.tsx
- apps/web/src/pages/CommunityInterests/form.ts
🤖 Resolves #13615
Resolve the initial values bug
I believe the issue lies within `FormValues`
If there are 20 possible development programs, there will be 20 radio groups. If the user has only set say 19 interests, there is a discrepancy. The interests passed in and the object `FormValues["interestInDevelopmentPrograms"]` they associate with are of varying lengths.
So I instead built the `FormValues["interestInDevelopmentPrograms"]` field starting from the community instead
1. Be unable to replicate the bug from the issue
2. Use for sample instructions https://github.com/GCTC-NTGC/gc-digital-talent/issues/13615#issuecomment-2917301318
> [Bug] Community interest development programs initial values

- packages/ui/src/components/Separator/Separator.stories.tsx
- packages/ui/src/components/Separator/Separator.tsx
🤖 Resolves #13571 
Migrates the `Separator` component to tailwind.
> [Debt] Migrate `Separator` to tailwind

- packages/ui/src/components/Sidebar/Content.tsx
- packages/ui/src/components/Sidebar/Sidebar.tsx
- packages/ui/src/components/Sidebar/Wrapper.tsx
- packages/ui/src/components/ToggleSection/ToggleSection.tsx
🤖 Resolves #13572 
Migrates the `Sidebar` component to use tailwindcss.
Noticed a dark mode issue with `ToggleSection` and fixed in since it is semi-related :sweat_smile: 
1. No significant chromatic diff.
> [Debt] Migrate `Sidebar` to tailwind

- packages/ui/src/components/Announcer/Announcer.tsx
🤖 Resolves #13550 
Migrates `Announcer` component to tailwindcss.
1. Make sure it is still hidden
> [Debt] Migrate `Announcer` to tailwind

- packages/ui/src/components/Loading/Loading.tsx
🤖 Resolves #13563 
Migrates the `Loading` component to tailwindcss.
> [!NOTE]
> This is a component that is only really used by the `Pending` component so when testing that is a good place to check. 
> [Debt] Migrate `Loading` to tailwind

- packages/forms/src/components/Checklist/Checklist.tsx
- packages/forms/src/components/Combobox/Combobox.tsx
- packages/forms/src/components/Combobox/Menu.tsx
- packages/forms/src/components/Combobox/Selected.tsx
- packages/forms/src/components/DateInput/ControlledInput.tsx
- packages/forms/src/components/Field/BoundingBox.tsx
- packages/forms/src/components/Input/Input.tsx
- packages/forms/src/components/RadioGroup/RadioGroup.tsx
- packages/forms/src/components/RichTextInput/ControlledInput.tsx
- packages/forms/src/components/Select/Select.tsx
- packages/forms/src/components/TextArea/TextArea.stories.tsx
- packages/forms/src/components/TextArea/TextArea.tsx
- packages/forms/src/hooks/useInputStyles.ts
- packages/forms/src/index.tsx
- packages/forms/src/styles.ts
🤖 Resolves #13671.
This PR migrates the `TextArea` component to tailwind.
> [!NOTE]
> `inputStyles` and `selectStyles` changes provides a path for other input styles and the select styles on other components. 
2. Verify `TextArea` story has no visual differences from original
> [Debt] Migrate `TextArea` to tailwind

- apps/web/src/hooks/useNotificationInfo.ts
- apps/web/src/hooks/useRoutes.ts
🤖 Resolves #13692.
This PR removes the `fragmentIdentifier` argument from `profileAndApplications` path.
1. Search for `fragmentIdentifier` in codebase
2. Verify there are no instances of `fragmentIdentifier` in codebase
> [Debt] Removes `fragmentIdentifier` from `profileAndApplications`

- .gitignore
- api/opcache.php
- apps/locust/testSearchPage.py
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #12686 
This PR doesn't actually tune the app services at all.  It turns out that we're not leaving any performance on the table.  :cry: It's actually quite easy to already pin the CPU to 100% in our UAT app service.  It might be better to take another shot at this, from the perspective of "how do we reduce the CPU usage of our app".  I did spend a bit of time checking that opcache was working and it seems that it is.
This PR just provides the Locust test and the opcache debugging to help with future efforts.
1. Restart the webserver container 
2. Visit http://localhost:8000/opcache.php
3. Observe that `opcache_enabled` = 1.
4. Observe that the various keys in `opcache_statistics` change as you use the site.
1. I [installed Locust locally with …
> [Debt] Tune app services

- apps/playwright/tests/support-page.spec.ts
- apps/web/src/lang/fr.json
- apps/web/src/lang/whitelist.yml
- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
🤖 Resolves #4805.
This PR updates the `SupportForm` subject label and options.
2. Navigate to http://localhost:8000/en/support
3. Verify `subject` field label is Reason for contact
4. Verify `subject` field options are, in this order: Question, Bug report, Feedback
6. Verify `subject` field label is Motif du contact
7. Verify `subject` field options are, in this order: Question, Signalement de bogue, Commentaires
> [Copy] Updates `SupportForm` subject label and options

- api/lang/fr/headings.php
- packages/i18n/src/lang/fr.json
🤖 Resolves #13704.
This PR fixes the spelling of the French translation for Contact email address.
Did not find any other instances of "Address" in French other than the two files changed.
1. Search codebase for Address (`fr.json` files; `api/lang/fr/*.php`)
2. Verify only instances of Address are for English strings
> [Copy] Fixes spelling of French translation for Contact email address

- packages/forms/src/components/Field/BoundingBox.tsx
- packages/forms/src/components/Field/Fieldset.tsx
- packages/forms/src/components/Field/Label.tsx
- packages/forms/src/components/Field/Legend.tsx
- packages/forms/src/components/Field/Required.tsx
- packages/forms/src/components/Field/Wrapper.tsx
- packages/forms/src/components/Field/styles.ts
🤖 Resolves #13664 
Migrates all the `Field.*` components to use tailwindcss.
> [Debt] Migrate `Field.*` to tailwind

- apps/web/src/lang/fr.json
- apps/web/src/pages/CertificationExamVouchersPage/CertificationExamVouchersPage.tsx
🤖 Resolves #13593
This PR updates a small copy change and button links on the Certification Exam Vouchers page in both English and French.
Changes include:
Updated English copy from:
- "We'll respond to your application within 7 business days."
to
- "We'll respond to your application within 14 days."
Updated French copy from:
- "Nous répondrons à votre demande dans les sept jours ouvrables."
to
- "Nous répondrons à votre demande dans les 14 jours."
Updated both English and French form buttons to link to the new form:
- EN: https://forms-formulaires.alpha.canada.ca/en/id/cmb13t7jr00cxx601nzt7gfpk
- FR: https://forms-formulaires.alpha.canada.ca/fr/id/cmb13t7jr00cxx601nzt7gfpk
1. Navigate to `en/it-training-fund/certification-exam-vouchers`
2. Confirm the copy now says: "We'll respond to …
>  [Copy] Exam Vouchers Page Copy and Links Updated

- packages/forms/src/components/SwitchInput/SwitchInput.stories.tsx
- packages/forms/src/components/SwitchInput/SwitchInput.tsx
- packages/ui/src/components/Switch/Switch.tsx
🤖 Resolves #13670 
Migrates the `SwitchInput` component to tailwindcss.
> [Debt] Migrate `SwitchInput` to tailwind

- api/app/Listeners/ComputeCandidateAssessmentStatus.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #12781
When creating an assessment result, if the status is new application update it to under assessment. Otherwise, do not change the status. 
1. Work through a new application flow and assessing it I suppose?
> [Feature] Assessment result saved updates candidate status

- apps/web/src/lang/fr.json
🤖 Resolves #13734.
This PR updates the French translation of Unclaimed as it refers to _une exigence_ (f).
2. Navigate to http://localhost:8000/fr/admin/candidates/:candidate-id/application
3. Verify one of the values renders _Non réclamée_ and not _Non réclamé_
4. Verify no other instances of _Non réclamé_ in codebase
> [Copy] Updates French translation of Unclaimed

- api/lang/fr/headings.php
- apps/web/src/lang/fr.json
🤖 Resolves #13726.
This PR fixes incorrect French translation of Written exam language.
1. Search codebase for any instance of _Examen de langue écrit_
2. Verify no instances of Examen de langue écrit in codebase
> [Copy] Fixes incorrect French translation of Written exam language

- apps/web/src/lang/fr.json
🤖 Resolves #13736.
This PR updates the French copy for lead-in text for application information.
2. Navigate to http://localhost:8000/fr/admin/candidates/:candidate-id/application
3. Verify paragraph after _Information sur la demande_ heading is up to date
> [Copy] Updates French Lead-in text for application information

- apps/web/src/components/BoolCheckIcon/BoolCheckIcon.tsx
- apps/web/src/components/CommunityInterest/CommunityInterest.tsx
- apps/web/src/components/CommunityInterest/DevelopmentProgramInterestItem.tsx
🤖 Resolves #13715 
Migrates the `CommunityInterest` component to tailwindcss.
> [!NOTE]
> I migrated the `BoolCheck` icon as well to match the styles of the custom icons here. Otherwise, it looked odd. 
> [Debt] Migrate `CommunityInterest` to tailwind

- api/app/GraphQL/Handlers/LoggingErrorHandler.php
- api/config/lighthouse.php
🤖 Resolves #12843 
Adds depth and complexity limits to the API.
Unfortunately, I wasn't able to find a deterministic way to measure the depth and complexity of our various queries.  I wasn't able to even find a good way to log them.  So I did trial-and-error and just clicked around the site bumping up the limits as I hit them.  :clown_face:   As a result, I roughly doubled the highest values I found to give a generous safety margin.  We can try bringing these down in the future if we want.
There were two queries that resulted in suspiciously high complexity values: AvailablePoolsToAddTo and PoolsInFilter.  I'm going to start a ticket to investigate those.
1. Click around the site
2. Confirm you didn't hit any limits.
> [Debt] Add depth and complexity limits to API

- apps/playwright/fixtures/TalentManagement.ts
- apps/web/src/components/NextRoleAndCareerObjective/CareerObjectivePreview.tsx
- apps/web/src/components/RecruitmentProcesses/RecruitmentProcessDialog.tsx
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessDialog.tsx
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewTalentNominationDialog.tsx
- packages/ui/src/components/PreviewList/PreviewList.tsx
🤖 Resolves #13793 
Fixes the talent managment tests, including the `PreviewList` component.
This fixes the talent management tests that broke in different ways. One of those ways was the `PreviewList` component props and another was a link not being on the initial table.
1. Confirm talent management tests pass consistently
2. Confirm `PreviewList` component works as expected
> [Fix] Talent management tests

- api/app/Models/Classification.php
- apps/web/src/lang/fr.json
- apps/web/src/pages/SearchRequests/SearchPage/labels.ts
🤖 Resolves #13797.
This PR adds EC-02 to EC-08 to `scopeAvailableInSearch` so that they are available as options in the classification filter of the search for talent form.
1. Navigate to http://localhost:8000/en/search
2. Verify EC-02 to EC-08 are options with English job titles in classification filter select
4. Verify EC-02 to EC-08 are options with French job titles in classification filter select
> [Feature] Adds EC-02 to EC-08 to `scopeAvailableInSearch`

- apps/web/src/components/NextRoleAndCareerObjective/CareerObjective.tsx
- apps/web/src/components/NextRoleAndCareerObjective/NextRole.tsx
- apps/web/src/components/NextRoleAndCareerObjective/NextRoleAndCareerObjective.tsx
🤖 Resolves #13731 
Migrates the `NextRoleAndCareerObjective` components to tailwindcss.
1. Navigate to nomination group
2. Confirm no diff in next role and career object section
> [Debt] Migrate `NextRoleAndCareerObjective` to tailwind

- apps/playwright/playwright.config.ts
Bump up the expect time to try and reduce test flakiness. For reference, currently shards 2 and 3 are being troublesome
Appears to get shard 2 to at least be capable of passing. Good enough for now
> Bump Playwright expect timeout

- api/app/GraphQL/Types/LocalizedEnumTypeRegistrar.php
- api/app/Models/TalentNomination.php
🤖 Resolves #12906 
Adds another case to our localized enum type in graphql to support enum casting.
Our original graphql type expected a string or array but with casting, it is now an instance of the enum. This adds another case in the resolver to handle that case.
Added one example of this. 
> [!NOTE]
> You don't need to use this example and just add another easier to test cast . I just used it because it was the one referenced int he ticket. 
1. Confirm the cast works in both laravel and the graphql api
> [Feat] Support casts in `LocalizedEnum` types

- apps/web/src/components/Header/Header.tsx
- apps/web/src/components/NavMenu/MainNavMenu.tsx
- apps/web/src/components/NotificationDialog/NotificationDialog.tsx
- packages/helpers/src/hooks/useIsSmallScreen.ts
- packages/ui/src/components/NavMenu/NavMenu.tsx
🤖 Resolves #13233 
Possible fix for the colours not matching when transitioning into the `sm` breakpoint.
We had a hook `useIsSmallScreen` that was using a dwebounced even listener watching for screen size changes and adjusting from `innerWidth`. This could have been causing issues in safari if the inner width was not updating in sync with the css media queries.
This refactors that hook to accept our tialwind sizes and react based on media query change rather than window size which should help it sync up with the CSS :thinking: 
1. Build the site `pnpm build:fresh`
2. Open the site at a size larger than 1080px width in safari
3. Reduce the window size until it collapses to a mobile menu
4. Confirm the background colour is corrext as well as links
> [Fix] Mobile menu colour mismatch in safari

- apps/web/src/components/NavMenu/MainNavMenu.tsx
- apps/web/src/components/NavMenu/useMainNavLinks.tsx
🤖 Resolves #13802 
- Fixes the alignment of the home link, with the header (goc icon line) above.
2. Ensure home link lines up with container edge
3. Ensure everything else remains aligned
> [Bug] Fix home link alignment on main nav menu

- api/app/Generators/PoolCandidateCsvGenerator.php
- api/lang/en/assessment_decision.php
- api/lang/en/common.php
- api/lang/fr/assessment_decision.php
- api/lang/fr/common.php
- apps/playwright/tests/admin/candidate-assessment.spec.ts
- apps/playwright/tests/admin/pool-candidate-actions.spec.ts
- apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx
- apps/web/src/components/ScreeningDecisions/useOptions.ts
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #13875.
This PR updates assessment decision labels for `hold` and `noDecision`.
2. Navigate to Screening and assessment page for a pool candidate
3. Verify `hold` and `noDecision` options in table and dialog reflect requested updates in English and French
https://github.com/user-attachments/assets/b16e4c0d-2634-498c-8131-2dbe4d3fc605
> [Copy] Updates assessment decision labels for `hold` and `noDecision`

- apps/playwright/tests/applicant/application-iap.spec.ts
- apps/playwright/tests/applicant/application.spec.ts
🤖 Resolves #13928 
Mark the application tests as slow to give them some more time to run in CI.
1. Confirm that it at least doesnt time out now
> [Test] Increase application timeout

- infrastructure/conf/php-fpm-www.conf
🤖 Resolves #12686 
Bumps the max PHP-FPM worker count and also the starting worker count.
Over the last two weeks when we've been struggling with performance I have been trying some different settings for PHP-FPM.  The setting in this PR reduces the number of "your server seems busy, try upping the working count" warnings.  It also stays well within the CPU and memory available to our app service.
1. Restart the web server container (or deploy into an Azure app service).
2. Shell into the web server container (or SSH into the Azure app service).
3. Run `php-fpm -t` to confirm that the settings are valid
4. Run `curl 127.0.0.1:8080/fpm-status` to confirm that at least 30 workers were started
5. Confirm that the app still runs well
> [Debt] More PHP-PFM workers

- apps/web/src/lang/fr.json
- apps/web/src/messages/experienceMessages.ts
- apps/web/src/utils/experienceUtils.tsx
🤖 Resolves #13894.
This PR accounts for legacy data within a pool candidate's `profile_snapshot` that contains education experience which had previously been a string and that is not an object.
> [!IMPORTANT]
> Bonus: [Fix type label value](https://github.com/GCTC-NTGC/gc-digital-talent/commit/0fd6208b816450be7f3966c05b8b6712324fde80) that used the `localized` value incorrectly.
2. Find a row in `pool_candidates` table with an education experience in the `profile_snapshot` column
3. Replace `type` value (that should be an object) with a string of BACHELORS_DEGREE
4. Navigate to the view pool candidate page for the row changed on the previous step
5. Verify that the card for the education does not render the type in the "title"
6. Verify that the card for non-legacy …
> [Fix] Education experience `type` label

- apps/web/src/components/CandidateDialog/ChangeStatusDialog.tsx
🤖 Resolves #13616.
This PR filters legacy pool candidate statuses from options so that they are no longer able to be saved.
2. Navigate to a pool candidate with a status that is part of the legacy list
3. In the candidate status section, click the status value to open the dialog
4. Verify the legacy status is not in the pool status `select` input field
5. Verify none of the legacy statuses appears as options in the pool status `select` input field
https://github.com/user-attachments/assets/5fd1e160-300e-4af7-a013-4651b42f643b
> [Feature] Filters legacy pool candidate statuses from pool status options

- apps/web/src/components/Profile/components/GovernmentInformation/FormFields.tsx
🤖 Resolves #13975.
This PR fixes spacing for two inputs on the government section of a user profile.
2. Navigate to http://localhost:8000/en/applicant/personal-information#government-section
3. Verify spacing between Current Classification Group and Current Classification Level inputs
4. Verify spacing on bottom of these inputs and the next input
> [Fix] Current classification spacing

- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
🤖 Resolves  #13926
This PR adds the "Selection process number" to the bottom of the Employment Details card while keeping the existing placement at the bottom of the page, it appears in both places.
Added "Selection process number" to Employment Details Card
- New DataRow for "Selection process number" placed at the bottom of the employment details card.
- Uses the label "Selection process number".
1. Build app, login as `Admin`
2. Navigate to `/browse/pools`
3. Verify "Selection process number" appears:
- In the Employment Details card (at the bottom of the employment details card).
- At the bottom of the page (unchanged).
> [Feat] Highlight Selection process number on advertisement

- apps/web/src/pages/SupportPage/components/SupportForm/SupportForm.tsx
🤖 Resolves #13973.
This PR removes some unused copy.
> [!NOTE]
> No French translation of the string was present in codebase.
1. Verify no instances of `QX1l/C` in codebase
2. Verify no instances of `Support form success paragraph three` in codebase
> [Debt] Removes Support form success paragraph three

- apps/web/src/components/ExperienceCard/WorkContent/WorkStreamsContent.tsx
🤖 Resolves #14028 
Forces the list to have no bullets.
This was due to our list compnent trying to be smart and adding a circle rather than disc for nested lists. So, we had to add imprtant to override that.
1. Login as an applicant
2. Add a work experience with one or more work stream
3. Go to the card for that experience
4. Confirm no bullets on the nested work stream list on an experience card
> [Fix] `ExperienceCard` work stream list styles

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- apps/web/src/components/SpinnerIcon/SpinnerIcon.tsx
🤖 Resolves #13963 
Fixes an issue where the spinner icon showing during file downloads was wobbling.
This was caused by the wrapping `span` (that was not necessary now with tailwind) having margin right which made it an irrefular shape leading to the wobble.
This removed the wrapping span and uses `taildwind-variants` to properly merge the classes and remove the added margin.
> [!TIP]
> Make it easier to test by removing the `isDownloading` condition for adding the spinner icon on a specific download button 
3. Navigate to a table
4. If you did not temporariyl remove the condition, trigger a download by selecting rows and clicking download
5. Observe the icon does not wobble
> [Fix] Spinner icon wobble

- apps/web/src/components/AssessmentStepTracker/AssessmentStepTracker.tsx
- packages/ui/src/components/DropdownMenu/DropdownMenu.tsx
🤖 Resolves #13982 
Fixes the dropdown menu from overlaying content by reducing its absurdly high `z-index`
3. Navigate to a communities "Manage access" tab
4. Open the actions dropdown
5. Click on an option
6. Confirm the dropdown menu shows below the dialog
> [Fix] Dropdown menu z-index

- apps/web/src/components/Table/ResponsiveTable/ColumnDialog.tsx
🤖 Resolves #13981 
Adds the `name` and `id` attribute to the table column dialog for a11y.
3. Navigate to any table `/admin/users`
4. Open the "Show/hide columns" dialog
5. Confirm the checkboxes had IDs and names
> [Fix] Add missing name/id to column toggle checkboxes

- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/CitizensNote.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/Display.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
🤖 Resolves #13934 
Takes existing note/warning from display and adds it to the edit form as well.
3. Navigate to create a pool `/admin/pools/create`
4. Creatge the poool
5. Open the "Basic information" form
6. Select "Open to public"
7. Select "Canadian citzens only"
8. Confirm the warning appears
9. Deselect "Canadian citizens only"
10. Confirm the warning dissapears
> [Fix] Add Canadian citzen note to pool basic info form

- api/app/Models/User.php
- api/app/Traits/Generator/GeneratesUserDoc.php
🤖 Resolves #14103 
Fixes an issue where downloading a document with user information in it was showing the incorrect language information.
Looks like there were more issues than the one repored :cry: 
- We were wrapping the display in incorrect condition checks
- We were accessing the incorrect properties from the user
- Unrelated but also noticed we had an incorrect mapping in the snapshot
2. Set your language info to have different levels for each category (comprehension, written, verbal)
3. Apply to any Process
4. Download the application submitted in step 3
5. Confirm the language info matches what was set in step 2
> [Fix] User download showing incorrect language info

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
- apps/web/src/components/PoolCandidatesTable/tableMessages.ts
- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationDialog.tsx
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewApplicationPreviewList.tsx
- apps/web/src/pages/PoolCandidates/IndexPoolCandidatePage/IndexPoolCandidatePage.tsx
- apps/web/src/pages/Users/UserInformationPage/components/UserCandidatesTable/helpers.tsx
- apps/web/src/utils/poolCandidate.ts
🤖 Resolves #14078.
This PR adds the Candidate-facing status column to the pool candidates table.
In addition to adding the Candidate-facing status column to the pool candidates table, this PR:
- removes some superfluous copy from `IndexPoolCandidatePage.tsx`
- fixes a variable typo
- adds `screeningQuestionCount` for the `getApplicationStatusChip` function for efficiency
2. Navigate to http://localhost:8000/en/admin/pool-candidates
3. Verify Candidate-facing status column value is the same as what is rendered on the related card for applicant dashboard Applications and processes > Job applications
> [Feature] Adds Candidate-facing status column to pool candidates table

- packages/ui/src/components/TaskCard/TaskCard.stories.tsx
- packages/ui/src/components/TaskCard/TaskCard.tsx
🤖 Resolves #14091 
Adds a the `locked` variant of `TaskCard` which overrides, heading and link colour along with the icon.
1. Run storybook `pnpm storybook`
2. Navigate to the "TaskCard" story
3. Confirm the locked variant matchs [the mockup ](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard--All-users-?node-id=4372-104068&m=dev)
> [Feat] Add `locked` variant of `TaskCard`

- packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
🤖 Resolves #13858.
This PR fixes `ToggleGroup` dark mode and therefore, the `ThemeSwitcher` component that uses the `ToggleGroup` component.
2. Navigate to `ToggleGroup` in dark mode
3. Verify base and hover states are correct
4. Navigate to `ThemeSwitcher` in dark mode
5. Verify base and hover states are correct
> [Fix] `ToggleGroup` dark mode

- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #14076
Possibly the regex match was broken by the webpack -> vite change and the pattern no longer applied.
Assets appear to follow `name-AAAAAAAA.xyz` where name represents the source file and the repeating "A" represents exactly 8 characters forming the hash. 
1. To test locally, make the changes below to your **_local_** file
2. Comment or uncomment the marked lines
> [Bug] Nginx asset caching time

- api/config/rolepermission.php
🤖 Resolves #13679.
This PR updates the French versions of Process Operator, Community Recruiter, Community Administrator, and Platform Administrator.
1. `make artisan CMD="db:seed --class=RolePermissionSeeder"`
2. Navigate to http://localhost:8000/fr/admin as admin@test.com
3. Verify roles in Vos rôles section use update copy
4. Navigate to an existing process > Gestion de l'accès > Ajoutez un membre
5. Verify role options in Rôles use update copy
6. Navigate to an existing community > Gestion de l'accès > Ajoutez un membre
7. Verify role options in Rôles use update copy
`make artisan CMD="db:seed --class=RolePermissionSeeder"`
> [Copy] Updates French versions of Process Operator, Community Recruiter, Community Administrator, Platform Administrator

- api/app/Generators/DocGenerator.php
- api/app/Generators/JobPosterTemplateGenerator.php
- api/app/GraphQL/Mutations/DownloadJobPosterTemplateDoc.php
- api/app/Models/JobPosterTemplate.php
- api/app/Traits/Generator/GeneratesDoc.php
- api/graphql/schema.graphql
- api/lang/en/filename.php
- api/lang/en/gcpedia.php
- api/lang/en/headings.php
- api/lang/en/job_poster_template.php
- api/lang/en/skill_level.php
- api/lang/fr/filename.php
- api/lang/fr/gcpedia.php
- api/lang/fr/headings.php
- api/lang/fr/job_poster_template.php
- api/lang/fr/skill_level.php
- api/storage/app/lighthouse-schema.graphql
- apps/web/src/lang/fr.json
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/JobPosterTemplatePage.tsx
- apps/web/src/pages/JobPosterTemplates/JobPosterTemplatePage/components/JobPosterDownloadButton.tsx
- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/DownloadButton.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #11440 
Adds a download button to the job poster template page.
The styles of the document are not exact to the samples provided. However, none of our documents are stellar in their styling so I createdd a new ticket to scope out updating our docs to look better.
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/14114
> [!IMPORTANT]
> `PhpWord` does not support adding footnores to titles. @NienkeBr helped me work out a solution to this. The footnote for the different skills titles is now a paragraph just below the title with a "Special note" prefix. 
> 
> See the following image for updated example
3. Navigate to the job poster templates page `/job-templates`
4. Click on a specific template
5. Confirm download button …
> [Feat] Job poster template download

- apps/web/vite.config.ts
🤖 Resolves #14077 
Removes tiptap from from manual chunks to allow it to lazy load.
There is currently a bug in vite that forces all manual chunks to load before the entry point bundle. Since this is about 100kb and we don't really need to manual chunk it, removing it allows it to auto lazy load the resources.
```sh
index.js   998.11 kB │ gzip: 308.87 kB │ map: 2,174.69 kB
tiptap.js  327.82 kB │ gzip: 104.56 kB │ map: 1,494.74 kB
index.js   998.43 kB │ gzip: 308.91 kB │ map: 2,174.69 kB
```
> [!TIP]
> Before testing, make sure you do not have a sitewide announcement. Having one will load tiptap dependencies since it needs it. 
1. Build main and take not of the bundle size for `index.js` and `tiptap.js`
2. Checkout branch and build `pnpm dev:fresh`
3. Confirm no `tiptap.js` bundle.
4. …
> [Fix] Remove tiptap from manual chunk

- apps/web/src/components/Footer/Footer.tsx
- apps/web/src/components/NavMenu/MainNavMenu.stories.tsx
- apps/web/src/components/NavMenu/MainNavMenu.tsx
- apps/web/src/components/NavMenu/useMainNavLinks.tsx
- packages/ui/src/components/NavMenu/NavMenu.tsx
- packages/ui/src/components/Separator/Separator.tsx
- packages/ui/src/index.tsx
🤖 Resolves #12228 
Adjusts the mobile menu layout to increase activate target size.
Unfortunatlety, since the same links are used across both, I had to make some minor adjusts to the desktop as well. I hope the diff isnt too bad :sweat_smile: 
2. Confirm menu matches mock up in both anonymous and asuthenticated states
> [Fix] Mobile menu layout

- api/app/Builders/PoolCandidateBuilder.php
- apps/web/src/components/PoolCandidatesTable/helpers.tsx
🤖 Resolves #14152
Attempt to resolve the issue with erratic candidate rows across table pages
The problem seems to be that if you sort by something that has a lot of equal results that it splits across pages, you don't get consistent or predictable ordering. Seems that results 1-10 of 25 and results 11-20 of 25 may follow different ordering. 
Went with Eric's suggestion to add what could be called a tiebreaker sort
1. Ensure you have many candidates seeded
2. Navigate to various candidates tables
3. Exhaustively test sorting
If needed, run
`make artisan CMD='db:seed --class=BigSeederPoolCandidateUser'`
> [Bug] Handle sorting candidates to account for non-unique columns

- packages/ui/src/components/CallToAction/utils.ts
- packages/ui/src/components/Tabs/utils.ts
- packages/ui/src/utils/btnStyles.ts
🤖 Resolves #11984 
Updates the link and button components to add a small amount of underline offset.
This should be relatively simple but just pushes the underlines down a bit making the text a bit easier to read at smaller sizes.
2. Confirm the offset exists
3. Confirm it doesn't create a significant diff (sohuld be very subtle) :crossed_fingers:
> [Style] Add offset to link/button underline

- api/app/Checkers/ProtectedRequestUserChecker.php
- api/tests/Unit/ProtectedRequestUserCheckerTest.php
🤖 Resolves #11149 
Updates the protected user checker to support array values.
1. Confirm new tests pass
2. Open a laravel tinker session `make artisan CMD="tinker"`
3. Find applicant user `$applicant = User::where('email', 'applicant@test.com')->first()`
4. Compare the results of `$applicant->isAbleTo('view-own-application') and $applicant->isAbleTo(['view-own-application'])`
> [Fix] Support arrays in protected user checker

- apps/web/src/components/FeatureBlock/FeatureBlock.tsx
- apps/web/src/components/GradientImage/GradientImage.tsx
- apps/web/src/components/SkewedContainer/SkewedImageContainer.tsx
- apps/web/src/pages/Home/HomePage/components/Hero.tsx
- axe-linter.yml
- packages/ui/src/components/Image/Image.stories.tsx
- packages/ui/src/components/Image/Image.tsx
- packages/ui/src/index.tsx
🤖 Resolves #14186 
Adds a new `Image` component to handle source sets and lazy loading.
It looks like wdith and height are no longer a hard requirement for `loading=lazy` so I tweakerd this a bit. Instead of providing a `boolean` prop for the `lazy` properties, I simply use the `img` attributes to handle this to make it eaiser when passing in multiple sources.
We should still be providing these values when we can, however when you provide multiple sources, you can't really set them since each source would have a different width/height.
We can likely improve this over time if we feel the need.
2. Open the network tab and filter by `img` requests
3. Navigate to the homepage
4. Observe, only those near the viewport are loaded
5. Scroll the page and notice that as …
> [Feat] New `Image` component

- apps/web/src/lang/fr.json
- apps/web/src/pages/Home/HomePage/components/Opportunities.tsx
🤖 Resolves #14233.
This PR replaces the abbreviation of CIO in executive community block on the homepage for clarity.
2. Navigate to http://localhost:8000/en/
3. Verify no instances of CIO
5. Verify no instances of DPI
> [Copy] Replaces abbreviation CIO with Chief Information Officer

- apps/web/src/lang/fr.json
- apps/web/src/pages/Users/UserEmployeeInformationPage/UserEmployeeInformationPage.tsx
🤖 Resolves #14021.
This adds a `null` state for the employee profile for when community interests are empty.
2. Navigate to a GC employee profile where the user has not set any community interests
3. Verify null state includes a `Well` with a message
> [Fix] Null state for `employeeProfile.communityInterests`

- apps/web/src/lang/__snapshots__/lang.test.ts.snap
- apps/web/src/lang/fr.json
- apps/web/src/messages/talentRequestMessages.ts
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewTalentRequestDialog.tsx
- apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx
- apps/web/src/pages/Applications/ApplicationSkillsPage/ApplicationSkillsPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
- apps/web/src/pages/Pools/PoolAdvertisementPage/PoolAdvertisementPage.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/commonMessages.ts
🤖 Resolves #14229.
This PR provides a consistent translation of skill requirements in French, consolidate the string into a single source.
1. Verify there are no instances of _Exigences relatives aux compétences_ in the codebase
2. Verify Skill requirements is only ever translated as _Exigences en matière de compétences_  in the codebase
> [Copy] Consistent translation of skill requirements in French

- apps/web/src/components/NotificationList/NotificationListPage.tsx
🤖 Resolves #13357 
Fixes an issue where the notification dialog focus was reset when the polling query fired.
This results in a little pop-in since the query runs initially when opening but does improve the interactions after that.
I think we could reduce the pop-in by querying notifications outsiode the dialog and drilling them in, or using a cache-first strategy? :thinking: 
> [!TIP]
> I found it easiest to have two windows open, one to generate files for notifications and another with the dialog open to see it update after a poll.  You can aslo pause the queue, focus an item and then boot it back up so the next poll with have new notifications.
2. Start queue so we can eaisly cvrete notifications `make queue-work`
3. Login as admin `admin@test.com`
4. Create …
> [Fix] Notification dialog poling removes focus

- Makefile
- Makefile.nix
- api/.env.example
- api/app/Http/Kernel.php
- api/app/Providers/AppServiceProvider.php
- api/app/Providers/EventServiceProvider.php
- api/composer.json
- api/composer.lock
- api/config/timing.php
- api/programmatic-types.graphql
- documentation/environment-variables.md
- maintenance/scripts/refresh_api.sh
- maintenance/scripts/setup.sh
🤖 Resolves #14173 
Adds tooling to help with API performance testing
I ended up leaving the server timing tool as a regular dependency rather than a dev dependency.  I was worried about forgetting the middleware enabled in code and then pushing it out to prod for it to fail.  I saw that it has a config value that can be set to disable it. I think that's a much safer way to turn it off in prod.
Oh, I also had the wrong library in the issue.  That's why it is different.
1. Setup fresh with makefile OR
1. `cp api/.env.example api/.env --preserve=all`
2. `cd api && composer install --prefer-dist`
2. Observer the server timings
3. Enable the query logging in api/app/Providers/AppServiceProvider.php
1. Observer the SQL is logged with bindings already substituted
5. Try the optimization
1. …
> [Feature] API perf tooling

- packages/ui/src/components/ResourceBlock/SingleLinkItem.tsx
🤖 Resolves #11284 
Replaces the deprecated `ArrowRightSmallIcon` with the mini version of the `ArrowRightIcon`.
1. Confirm no uses of `ArrowSmallRightIcon`
2. Confirm resource block arrow is the mini version of `ArrowRightIcon`
> [Debt] Replace deprecated arrow icon

- apps/web/src/components/NotificationList/NotificationItem.tsx
- packages/forms/src/components/DateInput/ControlledInput.tsx
- packages/forms/src/components/Repeater/ActionButton.tsx
- packages/i18n/src/components/richTextElements.tsx
- packages/i18n/src/utils/lang.tsx
🤖 Resolves #14268 
Updates instances of `dark:text-gray-300` with `dark:text-gray-200` to improve colour contrast.
1. Confirm no instances of `dark:text-gray-300`
2. Confirm the `dark:text-gray-200` meets colour contrast ratio requirements
> [Fix] Gray text colour contrast in dark mode

- apps/web/src/components/AssessmentResultsTable/AssessmentResultsTable.tsx
- apps/web/src/components/Table/ResponsiveTable/Table.tsx
- apps/web/src/table.d.ts
🤖 Resolves #12207 
Adds proper semantics to the assessment table row headers.
3. Navigate to a pool candidate
4. Confirm that the first column in each row has the proper element, role and scope
- Role: `rowheader`
- Scope: `row`
- Element: `th`
> [Fix] Add row header semantics to assessment table

- api/database/factories/CommunityExperienceFactory.php
- api/database/factories/EducationExperienceFactory.php
- api/database/factories/PersonalExperienceFactory.php
- api/database/factories/WorkExperienceFactory.php
🤖 Resolves #14253 
This is another attempt to stabilize the snapshots.
It looks like we had another date issue with the snapshots either from an un-updated snapdhot getting merged or the dates not being stable.
The one thing I noticed was the use of `$this->faker->boolean()` to optional set end date. I'm not sure if this is stable and it does seem like it is always end date having the issue.
Since this is a non-standard way of setting a field optionally, I updated this to use the `$this->faker->optional()` modifier instead. I think maybe this could be more deterministic? :thinking: 
1. Run snapshot tests multiple times
2. Confirm they consistnelty pass
> [Fix] Stabilize snapshots (again)

- api/app/Traits/Generator/GeneratesUserDoc.php
🤖 Resolves #14377 
Adds the "additional details" field to award, personal, and work experiences in the DOCX downloads.  
The scope of the issue was education and work experiences but Nienke confirmed that all experience types should have the field.  
I never found anything wrong with education experiences.  Dasha is OK with proceeding with just the fix for work experiences.
Additionally, a small refactor to consolidate the three "if work experience" blocks together.  It seems like having three blocks led to [the original bug](https://github.com/GCTC-NTGC/gc-digital-talent/pull/13883/files#diff-7324a58fd6f56a2082cfb8bad8301e54fa4e0710b3da3da6fee03873bda8518cL465).
1. As an applicant...
1.  add an experience from all five types to your profile.
2.  submit an application to a pool
2. As an …
> [Fix] Add missing "additional details" fields to DOCX files

- api/database/migrations/2025_08_26_161523_add_unique_constraint_work_streams_table_key_column.php
🤖 Resolves #13387 
Adds a unique constraint to the `key` column on the `work_sreams` table.
1. Migrate data `make artisan CMD="migrate"
2. Confirm the constraint is added
3. Rollback `make artisan CMD="migrate:rollback --step=1"
4. Confirm it removes the constraint
Will need to test to confirm their are no violations first.
> [Fix] Add unique constraint index to `work_streams.key`

- apps/web/vite.config.ts
🤖 Resolves #12414 
Lets Vite fallback to undefined instead of a string with empty quotes.
1. Rebuild locally and confirm env variables properly populated in the fallback values
2. Deploy in Azure and confirm env variables properly populated with empty fallback values
> [Bug] Fix fallback values

- api/app/Builders/PoolBuilder.php
🤖 Resolves #14375.
This PR updates the `whereClosed` function for processes so that in order to be returned as CLOSED in the query, a process needs to have a `published_at` value that is not `NULL`.
1. `make refresh-api; make seed-fresh; pnpm i; pnpm run build:fresh;`
2. Create a draft process with a closing date one day in the future from now
3. Manually update the `closing_date` field of that process to be one day in the past from now
4. Navigate to http://localhost:8000/en/admin/pools?f=%7B%22publishingGroups%22%3A%5B%5D%2C%22statuses%22%3A%5B%22CLOSED%22%5D%2C%22workStreams%22%3A%5B%5D%2C%22classifications%22%3A%5B%5D%7D
5. Verify that the draft process created does not render in the table for `CLOSED`
> [Fix] Updates `whereClosed` on `PoolBuilder` logic

- api/lang/en/headings.php
- api/lang/fr/headings.php
- api/tests/Feature/Generators/__snapshots__/JobPosterTemplateGeneratorTest__testJobPosterTemplateDocSnapshot__1.html
🤖 Resolves #14451.
This PR updates **Work stream** to be two words in English and to use the consistent term for its translation, **Volet de travail**, in French.
2. Navigate to a job template in http://localhost:8000/en/job-templates
3. Download and verify the document contains Work stream and not Workstream
5. Download and verify the document contains Volet de travail and not Flux de travail
> [Copy] Updates work stream to be two words in English; consistent term in French

- apps/web/src/pages/Applications/ApplicationReviewPage/ApplicationReviewPage.tsx
🤖 Resolves #13787 
Sets the signature default value on the application review page if a user navigates back to it after submission.
This is an interim solution untl we replace the applicatioin with some read-only view in the future.
REF: https://github.com/GCTC-NTGC/gc-digital-talent/issues/13787#issuecomment-3233830378
3. Apply to a job
4. Navigate back to the review section
5. Confirm the signature field has your signature as a default value
- NOTE: You still can;t re-submit but at least it shows all the relevant info now
> [Fix] Set signature default value on application review page

- apps/web/src/utils/poolCandidate.test.ts
- apps/web/src/utils/poolCandidate.ts
🤖 Resolves #14384 
Removes the candidates current assessment step number from the candidate status chip.
3. Navigate to the candidates table `/admin/pool-candidates`
4. Confiorm the "To assess" chips under the "Final decision" column no longer display the users current step number
> [Debt] Remove step number from candidate status chip

- apps/web/src/components/CandidateDialog/ChangeStatusDialog.tsx
🤖 Resolves #14457
Adds NEW_APPLICATION back to the status change dialog.
1. Log in as one of the admin roles.
2. Navigate to a pool candidate evaluation.
3. Use the status dialog to change the status to NEW_APPLICATION.
> Add NEW_APPLICATION back to the status change dialog

- apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/MoreActions/MoreActions.tsx
🤖 Resolves #14450 
Fixes the candidate page to no longer show the dialog to remove a candidate when they have already been removed or disqualified from a process.
3. Navigate to a candidate
4. Remove them from the process
5. Confirm the button to remove dissapears
6. Reinstante the candidate
7. Disqualify them
8. Confirm the button to remove dissapears
> [Fix] Hide remove candidate button when removed or disqualified 

- api/database/factories/PoolFactory.php
🤖 Resolves #14478 
Fixes an issue where the `PoolFactory` could create duplicate assessment steps that violate the unique constraint.
This was caused by a combination of two states `withQuestions` and `withAssessments`. Both of these methods were attempting to insert a screening question step at position 2. Since this is now a unique field, we can no longer do that.
To fix this, I simply prevented the `withAssessments` from creating any screening question types. If we want a screening question step, we should use `withQuestions`.
1. Run `make artisan CMD="db:seed --class=BigSeederPoolCandidateUser"`
2. Enter a large number
3. Confirm no unique constraint errors
> [Fix] `BigSeederPoolCandidateUser` creating duplicate assessment steps

- api/database/migrations/2025_08_29_220331_make_email_columns_case_insensitive.php
🤖 Resolves #13874.
Changes the email and work_email columns to the [citext](https://www.postgresql.org/docs/current/citext.html) type which is case insensitive.
1. Get a user with a capitalised email.
2. Attempt to set another users email to a lowercase version of that.
3. Confirm you get a uniqueness error.
4. Repeat for work emails.
Any duplicate emails will need to be manually cleaned up **before** running the migration.
> Make email columns case sensitive

- api/lang/en/placement_type.php
- api/lang/fr/placement_type.php
- apps/web/src/components/PoolCandidateDialogs/JobPlacementForm.tsx
- apps/web/src/lang/fr.json
- apps/web/src/messages/poolCandidateMessages.ts
🤖 Resolves #14088
This PR updates the radio choice label in the job placement status dialog to match the sidebar `Offer in progress`
The sidebar is currently showing `Offer in progress` but the dialog displays `Tentatively placed (verbal or email confirmation)` This PR updates the radio choice label to match the sidebar. 
1. Build app
2. Login in as `admin`
3. Navigate to `/pool-candidates` and select a candidate
4. In the sidebar open the status dialogue from the Job placement field
5. Confirm that the option now displays:
- Label: `Offer in progress` 
- subtitle `Tentatively placed (verbal or email confirmation)` 
6. Confirm updates appear correctly in French
> [Feature] Update "Offer in progress" copy on job placement status dialog

- apps/web/src/components/RecruitmentProcesses/RecruitmentProcessesPreviewList.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/ApplicantDashboardPage/components/ReviewRecruitmentProcessPreviewList.tsx
- apps/web/src/pages/Users/AdminUserRecruitmentPage/AdminUserRecruitmentPage.tsx
- apps/web/src/pages/Users/AdminUserRecruitmentPage/components/OffPlatformRecruitmentProcesses.tsx
- packages/i18n/src/lang/fr.json
- packages/i18n/src/messages/navigationMessages.ts
- packages/ui/src/components/TableOfContents/Section.tsx
🤖 Resolves #14383 
This adds the off-platform recruitment processes section to the admin user page.
3. Add some off-platform processes
4. Navigate to the admin view of your own user
5. Navigate to the "Recruitment" tab
6. Confirm you see the new section and it matches the mockup
> [Feat] Add off-platform recruitment processes section to admin user page

- packages/ui/src/components/Card/Card.stories.tsx
- packages/ui/src/components/Card/Card.tsx
- packages/ui/src/components/Card/CardGrid.tsx
- packages/ui/src/types.ts
🤖 Resolves #14547 
Adds the ability to add a grid to a `Card` component with sub component sof `Card.Grid` and `Card.GridItem`
This inherits the space from the card like the separator (which was hopefully the correct design decision). 
```
<Card space="md">
<Card.Grid coloums={2}>
<Card.GridItem>...</Card.GridItem>
<Card.GridItem>...</Card.GridItem>
<Card.GridItem>...</Card.GridItem>
<Card.GridItem>...</Card.GridItem>
</Card.Grid>
<Card.Separator />
<p>Some footer content</p>
</Card>
```
1. Run storybook `pnpm storybook`
2. Confirm the component matches [the mockup](https://www.figma.com/design/ToAqDP2DsrAOaNJPh4qsF9/Digital-careers-at-National-Defence--All-users-?node-id=110-4200&m=dev)
> [Feat] Add divider component for cards

- apps/playwright/fixtures/ExperiencePage.ts
🤖 Resolves #13632
Updates one of the work experience e2e tests to include adding a work stream.
1. Confirm e2e tests pass in CI.
2. Confirm e2e tests pass locally.
> Add a work stream to a work experience e2e test

- api/app/Models/PoolCandidate.php
- api/tests/Feature/CandidateFinalDecisionTest.php
🤖 Resolves #14554 
Makes some changes to the setup of the final decision test in an attempt to stabilize it.
I believe this test was flaky because the factory could create a candidate who has no assessment step set. This attempts to address that by manually setting it to the first step and then refreshes the candidate before computing the decision. This should help keep the candidate the same across tests.
```sh
make artisan CMD="test --filter=testFinalDecisionComputation"
```
1. Run the test multiple times (try 20+)
2. Confirm it consistently passes
> [Fix] Stabilize compute final decision test

- .storybook/main.ts
🤖 Resolves #14631.
This PR removes filter for `git-version` plugin to fix storybook watch mode.
2. Verify stories render
3. `pnpm build-storybook; npx http-server storybook-static -o`
4. Verify stories build and render
> [Fix] Storybook watch mode

- apps/playwright/tests/admin/accessibility.spec.ts
- apps/web/src/components/Router.tsx
- apps/web/src/hooks/useRoutes.ts
- apps/web/src/utils/poolUtils.tsx
🤖 Resolves #14551.
This PR hides the screening assessment page that will eventually be deleted.
2. Navigate to a published pool on http://localhost:8000/en/admin/pools
3. Verify there is no Screening and assessment tab
4. Add `/screening` to the URL and navigate to that URL
5. Verify `NotFoundError` rendered
> [Feature] Hides screening assessment page

- apps/web/src/components/PoolStatusTable/PoolStatusTable.tsx
- apps/web/src/pages/Users/AdminUserRecruitmentPage/components/RecruitmentProcesses.tsx
🤖 Resolves #14611 
Updates the recruitment tab for viewing a user in the context of a admin to only show applications that have been qaulified (recruitment processes).
This adds a prop to the `PoolStatusTable` component called `onlyRecruitmentProcesses` which tells the table to filter out any pool candidates that have not been qualified.
2. Login as any user (preferrably one with no pool candidates to make testing easier)
3. Apply to a process, or multiple
4. Login as `admin@test.com`
5. Go to view that user
6. Navigate to the recruitment tab
7. Confirm the table shows no pool candidates
8. Update one of the pool candidates you applied to in step 3 to be qualified
9. Relead the recruitment tab
10. Confirm the qualified pool candidates now appear
> [Fix] Only show qualified applications on user recruitment tab

- api/app/Models/User.php
🤖 Resolves #14668
The observer class was deleted (by accident I assume) from the user model, turns out it doesn't run if you do that. Added it back in 
1. PHP tests pass
> [Bug] Undo `UserObserver` deletion from user model

- api/resources/views/notification_government_experience_verify_work_email/in_app_message_fr.blade.php
- apps/web/src/lang/fr.json
🤖 Resolves #14645.
This PR improves consistency of email verification copy in French.
2. Navigate to anywhere that uses **Verify** for email
4. Verify the verb _confirmer_ is used instead of _verifier_
> [Copy] Improves consistency of email verification copy in French

- api/app/Models/PoolCandidate.php
- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- api/tests/Feature/PoolCandidateTest.php
- apps/web/src/components/ScreeningDecisions/SupportingEvidence.tsx
- packages/fake-data/src/fakePoolCandidates.ts
🤖 Resolves #14629 
Fixes an issue where the snapshot could not resolve the experiences marked as education requirements after they had been deleted.
This is accomplished by adding an attibute to get the IDs for those experiences from the pivit table since it still exists even when the referenced table row does not.
3. Apply to a process taking note of the experiences you used in the educaiton requirement section
4. Delete all your experiences
5. View the  application as an admin
6. Confirm the experiences from the snapshot are still rendered even when the live versions do not exist
> [Fix] Resolve deleted education requirement experiences in snapshot

- api/app/Models/PoolCandidate.php
- api/tests/Feature/CandidateAssessmentStatusTest.php
🤖 Resolves #14667 
Updates the computation of the assessment status for application screening to skip essential skills if they are behavioural.
2. Create a process that has at least 2 assesment steps including essential behavioural skills
3. Apply to the process created in step 2
4. Assess the application created in step 3
5. Confirm you do _**not**_ need to assess any essential behavioural skills to pass the first step only
> [Fix] Application screening test assessment status computation

- apps/web/src/components/NavMenu/Menu.tsx
- packages/ui/src/components/Link/ScrollToLink.tsx
🤖 Resolves #14574 
This adds an offset to our scroll link so that the targeted section is not obscured by the sticky nav menu.
2. Navigate to a page with a tabe of contents
3. Activate a link in the table of contents
4. Confirm the section it scrolls to is not obsrcued by the sticky nav
> [Fix] Offset scrolling by menu

- infrastructure/conf/nginx-conf-deploy/default
- infrastructure/conf/nginx-conf-local/default
🤖 Resolves #14717 
Expands the location rule for our long (1 year) cache rule for assets.
> [!TIP]
>  This is disabled locally so you need to make some changes to test
1. open the local nginx config (`infrastructure/conf/nginx-conf-local/default`)
2. Uncomment the cache control header on L231
3. Reload nginx (i usually just do `make down; make up`)
4. Navigate to any page
5. Check the headers for files that have a `-` in their hash
6. Confirm it has a cache control for `31536000` (1 year)
> [Fix] Allow `-` in hashes for nginx long cache rule

- apps/web/src/pages/Departments/UpdateDepartmentPage.tsx
🤖 Resolves #14778.
This PR sets the `departmentNumber` value to an integer to match the type in the database.
2. Navigate to departments table http://localhost:8000/en/admin/settings/departments
3. Edit a department with a different value that is not an existing department number in the database
4. Verify the form saves without error
> [Fix] Type of `departmentNumber` in update department form

- api/graphql/schema.graphql
- api/storage/app/lighthouse-schema.graphql
- apps/playwright/tests/admin/process-action-update.spec.ts
- apps/playwright/tests/admin/process-published-action-update.spec.ts
- apps/web/src/components/ToggleForm/LabelledTrigger.tsx
- apps/web/src/lang/fr.json
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.test.tsx
- apps/web/src/pages/Pools/EditPoolPage/EditPoolPage.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/Display.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/PoolNameSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/components/PoolNameSection/utils.ts
- apps/web/src/pages/Pools/EditPoolPage/components/ProcessNumberSection.tsx
- apps/web/src/pages/Pools/EditPoolPage/types.ts
- apps/web/src/validators/process/classification.ts
🤖 Resolves #13925 
Updates the process number to allow it to be edited after publishing.
2. Login as `community@test.com`
3. Create and publish a pool
4. Edit the process number
5. Confirm it requires justification and can be updated
6. Confirm the change is tracked in the activity log
> [Feat] Allow editing process number after publishing
